#1000 フォローのタイムライン機能(近藤佑哉)
yukihiroLaravel/joint_develop pull request #1001
Opened 2024-03-08 17:08 UTC by yuyakondo333

## issue
 - Closes #1000 
## 概要
 - フォローのタイムライン機能
## 動作確認手順
 - ユーザー詳細ページのフォローボタンをクリックしてフォローしたユーザーの一覧が表示される
 - ユーザー詳細ページのフォロワーボタンをクリックしてフォロワーの一覧が表示される
## 考慮してほしいこと
 - 今回は特にありません。
## 確認してほしいこと
 - 今回は特にありません。

2024-03-10 05:39 UTC, yukihiroLaravel requested changes
いくつかわかりやすいよう
動画とテキストでレビューしましたので
ご確認ください！

https://www.loom.com/share/65bfb933325e456280c45bdc9d3d251b?sid=c57b8615-14af-422a-9599-f1a970b92740

2024-03-10 05:39 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('users/{id}/followers', 'UsersController@followers')->name('user.followers');
ここはusers/{id}のURLが３つ連なっているので
prefixでまとめられそうですね！

2024-03-10 05:39 UTC, yukihiroLaravel commented on app/User.php
> +
上の関数と全く同じなので
followingsを変えないといけない。。。？

2024-03-10 05:39 UTC, yukihiroLaravel commented on resources/views/follow/follow.blade.php
> +        <form method="POST" action="{{ route('follow', $userId ?? $following->id ?? $follower->id) }}">
$user->idのみにする

2024-03-10 15:52 UTC, yuyakondo333 commented on app/User.php
> +
```
    public function followings()
    {
        return $this->belongsToMany(User::class, 'followers', 'following_user_id', 'followed_user_id')->withTimestamps();    // 第三引数と第四引数が入れ替わっている
    }

    public function followers() 
    {
        return $this->belongsToMany(User::class, 'followers', 'followed_user_id', 'following_user_id')->withTimestamps();    / 第三引数と第四引数が入れ替わっている
    }
```
returnの第三引数、第四引数が逆になっているので全く同じ関数ではないと思います！
また、followings→フォローしているユーザーの取得
followers→自分のフォロワーの取得
このようになっており挙動としてもおかしくない状態のため変更せず提出いたします。

2024-03-10 15:52 UTC, yuyakondo333 commented on routes/web.php
> +Route::get('users/{id}/followers', 'UsersController@followers')->name('user.followers');
かしこまりました！prefixでまとめます。

2024-03-10 15:56 UTC, yuyakondo333 commented on resources/views/follow/follow.blade.php
> +        <form method="POST" action="{{ route('follow', $userId ?? $following->id ?? $follower->id) }}">
$user->idのみにしたかったのですが、posts.blade.phpの25行目のincludeで使われている変数をuserにするのはおかしいかと思いました。理由としてはこのposts.blade.phpでは、主に投稿一覧を取得する表示をしているためpostのままの方がいいのではないかと思いました。したがって!==以降は以下のように変更しました。

` ($post ?? $user->id)`

2024-03-11 00:09 UTC, yukihiroLaravel requested changes
また少しコメントしましたのでご確認ください！

https://www.loom.com/share/5a72236fef4841d5963e5173bb46d793?sid=585be70d-d8fd-44e5-8393-a99cde239b9e

2024-03-11 14:14 UTC, yukihiroLaravel requested changes
１行のみ削除願います

2024-03-11 14:14 UTC, yukihiroLaravel commented on resources/views/posts.blade.php
> +    {{-- 以下は投稿に関してだからpostのままにする --}}
削除

2024-03-11 14:25 UTC, yukihiroLaravel approved these changes
マージしました！
おつかれさまでした！！

2024-03-11 14:25 UTC, merged