#904投稿削除
yukihiroLaravel/joint_develop pull request #1002
Opened 2024-03-09 14:51 UTC by kiyoharu420

## 　904投稿削除

## 　確認方法
-　ログインして投稿削除をクリックして投稿削除されるか

2024-03-10 01:03 UTC, yukihiroLaravel requested changes
時間はかかりましたが、結構いい感じですね！
いくつか修正依頼しましたのでご確認ください！

https://www.loom.com/share/4d898e07d57a43b0b3b99efec959167a?sid=bd3bbe7f-98cd-4de1-b6fe-3e2c11d08e89

2024-03-10 01:03 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
>      }
空行１行

2024-03-10 01:03 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
>                          <button type="submit" class="btn btn-danger">削除</button>
インデント

2024-03-10 01:03 UTC, yukihiroLaravel commented on routes/web.php
> -});
移動

2024-03-12 13:51 UTC, kiyoharu420 commented on routes/web.php
> -});
ありがとうございます。
修正しました。
プルリクします。

2024-03-12 13:52 UTC, kiyoharu420 commented on routes/web.php
> -});
@yukihiroLaravel 
修正いたしました。
よろしくお願いいたします。

2024-03-13 06:33 UTC, yukihiroLaravel requested changes
ご確認お願いします！

2024-03-13 06:33 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        if (\Auth::id() === $post->user_id) {
動作確認きちんとされましたでしょうか？
僕の方でやってみましたが、削除されません、、、！

おそらく、ここの部分===ではなく
==でうまくいく気がしますので

再度コードを修正して試してみてから問題なければ
pushしてください。

よろしくお願いします！

2024-03-13 13:13 UTC, kiyoharu420 commented on app/Http/Controllers/PostsController.php
> +        if (\Auth::id() === $post->user_id) {
すみません動作確認して、削除されたと思ったのですが、再度やってみたら消えませんでした。
修正後、削除されました。
再度プルリクしました。よろしくお願いいたします。

2024-03-13 14:34 UTC, yukihiroLaravel approved these changes
OKかと思いますのでマージしました！
おつかれさまでした！

2024-03-13 14:34 UTC, merged