Feature/ohtomo/#980 favolites function
yukihiroLaravel/joint_develop pull request #1003
Opened 2024-03-10 07:48 UTC by to-ohtomo

## issue
・Closes #980

## 概要
「いいね機能」作成

## 動作確認手順
【TOP画面】
・「いいね」を許可するチェックボタンが表示されることを確認
・ログインしていない状態、ログインしている状態で、各投稿に「いいね」数が表示されることを確認
・投稿毎に「いいね！を押す」ボタンが表示され、ボタンを押せること、
「いいね！を外す」ボタンに表示が変わることを確認、この時「いいね」数が増えることも確認
・「いいね！を外す」ボタンが押せることを確認、ボタンが押すと「いいね！を押す」ボタンに表示が変わり、
「いいね」数が減ることを確認
・「いいね」された投稿の「いいね」countが増えることを確認

【ユーザ詳細画面】
・タイムライン/フォロー中/フォロワー/お気に入りカラムが表示されること確認
・「タイムライン」表示の下に、投稿件数が表示されることを確認、
また、「タイムライン」をクリックするると投稿した内容が確認できることを確認
・「フォロー中」表示の下にフォローしているユーザ数が表示されることを確認
また、「フォロー中」をクリックするとフォローしているユーが確認できることを確認
・「フォロワー中」表示の下にフォローされているユーザ数が表示されることを確認
また、「フォロワー」をクリックするとフォローされているユーザが確認できることを確認
・「お気に入り」表示の下に「いいね」している件数が表示されることを確認
また、「お気に入り」を「いいね」している投稿が確認できることを確認
・「いいね」した投稿がある場合、「お気に入り」countが増えることを確認
・投稿時、いいね許可チェック有無を選択できることを確認
・いいね許可チェック無しで投稿した際、投稿に対し「いいね」出来ないことを確認

【フォローcount確認】
・ユーザ詳細画面にて、フォローしているユーザがある場合、「フォロー中」countが増えることを確認
また、フォローされている場合、「フォロワー」countが増えることを確認

## 確認してほしいこと
いいね機能関連およびユーザ詳細のフォロー中/フォロワーのcount表示についてレビューをお願い致します

2024-03-11 22:29 UTC, Osk0830 requested changes
お疲れ様でした！
おおむねよくできていると思います！
ただ、全体を通して、`favorite_flag`が本当に必要なのか検討してみる必要がありそうです。
その点含めてコメントしましたので、確認よろしくお願いします！

2024-03-11 22:29 UTC, Osk0830 commented on app/User.php
> +        }
- 自分自身の投稿に「いいね」できてしまうのは少しおかしい気がします。Blade側でボタン自体は表示を切り分けてはいますが、内部的にも自分自身の投稿には「いいね」できないようにしておきましょう。

2024-03-11 22:29 UTC, Osk0830 commented on app/User.php
> +        }
- こちらも上記同様、自分自身の投稿の場合は絶対に処理が走らないようにしておきましょう。

2024-03-11 22:29 UTC, Osk0830 commented on resources/views/favolite/favorite_button.blade.php
> +        <form method="POST" action="{{ route('unfavorite', $post->user_id && $post->favorite_flag) }}">
- 「いいねする・はずす」のボタンの表示切り分け条件として、投稿が「誰かに」いいねされているか？という条件を設定するのはおかしくないでしょうか？あくまで、「ログインユーザー自身」が既にいいねしているかどうかによりボタンが切り替わるべきかと思います。そのように考えると、今回の実装で、`favorite_flag`は特に不要ではないでしょうか？以上を踏まえて、フラグに関する記述がある箇所は、全体を通して検討・修正してみてください。

2024-03-11 22:29 UTC, Osk0830 commented on resources/views/partials/user_tabs.blade.php
> +        </div>
- `</div>`(閉じタグ)だけ改行されているのはおかしいので、改行はなくしてしまいましょう。4箇所調整お願いします。

2024-03-16 04:56 UTC, to-ohtomo commented on app/User.php
> +        }
承知しました。修正させていただきます。

2024-03-16 04:56 UTC, to-ohtomo commented on app/User.php
> +        }
承知しました。修正させていただきます。

2024-03-16 04:56 UTC, to-ohtomo commented on resources/views/favolite/favorite_button.blade.php
> +        <form method="POST" action="{{ route('unfavorite', $post->user_id && $post->favorite_flag) }}">
確かに不要と思いましたので、削除させていただきます。

2024-03-16 04:57 UTC, to-ohtomo commented on resources/views/partials/user_tabs.blade.php
> +        </div>
承知しました。修正させていただきます。

2024-03-16 05:44 UTC, to-ohtomo commented
下記修正させていただきましたので、お手数ですが、レビューをお願い致します。
### resources/views/partials/user_tabs.blade.php
タグの位置を修正しました

### app/User.php
自分自身の投稿には、処理が走らないように記述を追加しました

### resources/views/favolite/favorite_button.blade.php
favorite_flag を削除しました。
なお、favorite_flag を削除に伴い、下記ファイルについても対処しました。
### ①database/migrations/2024_03_10_143022_add_favorite_flag_to_posts_table.php
ファイルを削除しました

### ②app/Http/Controllers/PostsController.php
下記行を削除しました
（$post->favorite_flag = $request->favorite_flag ? 1 : 0;）

### ③resources/views/posts/posts.blade.php
favorite_buttonを追記しました
（@include('favorite.favorite_button', ['post' => $post])）

2024-03-17 10:24 UTC, to-ohtomo commented
.skip_posts_flash_message')ファイルを削除しましたので、レビューをお願い致します。
お手数お掛けし申し訳ございませんでした。

2024-03-20 11:37 UTC, Osk0830 approved these changes
お疲れ様でした！
実装的には問題ないと思います！
1箇所もう少しスマートに書けそうな箇所があり、コメントしましたが、
現状でも内容的にはOKそうなので、
一旦マージしますね！

2024-03-20 11:37 UTC, Osk0830 commented on app/User.php
> +            return false;
- `return`する内容が共に`false`で同じなので、if文を分けるのではなく、論理演算子を用いて条件を一つにまとめるとより良さそうですね。

2024-03-20 11:37 UTC, Osk0830 commented on app/User.php
> +        }
- こちらも同様に、if文は一つにまとめるのが良さそうですね。

2024-03-20 11:37 UTC, merged