検索機能追加@横井
yukihiroLaravel/joint_develop pull request #1004
Opened 2024-03-10 09:49 UTC by KosukeYokoi

概要
•トップページに検索機能の追加

動作確認手順
•検索フォームにキーワードを入力後、検索ボタンを押下すると
キーワードにHITしている投稿のみ再表示させる。

考慮してほしいこと
• 特にありません。

確認してほしいこと
• 挙動的にこれで良いか

2024-03-11 01:05 UTC, yukihiroLaravel requested changes
良い感じですが、指摘させて頂きましたのでご確認ください！
https://www.loom.com/share/a93ae5bf035244ad8958a1282d8341c8?sid=706b861e-6b16-4ee5-8882-2b686c800be8

2024-03-11 01:05 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        return view('welcome', compact('posts'));
compactを使わない方がいい

2024-03-11 01:05 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +<h5 class="text-center mb-3">"趣味や仕事"について140字以内で会話しよう！"</h5>
"は不要

2024-03-11 01:05 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +            <input type="text" name="search" placeholder="投稿を検索" class="form-control" style="flex: 3; min-width: 350px;">
検索したワードが入るように

2024-03-11 01:05 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +            <input type="text" name="search" placeholder="投稿を検索" class="form-control" style="flex: 3; min-width: 350px;">
また、ここではないが
posts.blade.php
のページネーションでも検索ワードが入るように

2024-03-11 01:05 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $posts = Post::where('content', 'like', "%{$search}%")->paginate(10);
ordeBy関数で降順に並び替え

2024-03-13 11:09 UTC, KosukeYokoi commented on app/Http/Controllers/PostsController.php
> +        return view('welcome', compact('posts'));
以下の配列方式に書き換えました。

return view('welcome', [
            'posts' => $posts,
]);

2024-03-13 11:10 UTC, KosukeYokoi commented on resources/views/welcome.blade.php
> +<h5 class="text-center mb-3">"趣味や仕事"について140字以内で会話しよう！"</h5>
”を削除しました。

2024-03-17 04:14 UTC, KosukeYokoi commented on resources/views/welcome.blade.php
> +            <input type="text" name="search" placeholder="投稿を検索" class="form-control" style="flex: 3; min-width: 350px;">
１ページ目でも2ページ目でも検索窓内にキーワードが残るようにいたしました。

posts.blade.phpの最終行目付近の処理に変更を加えました。
`<div class="m-auto" style="width: fit-content">{{ $posts->appends(['search' => request('search')])->links('pagination::bootstrap-4') }}</div>`

2024-03-17 04:15 UTC, KosukeYokoi commented on app/Http/Controllers/PostsController.php
> +        $posts = Post::where('content', 'like', "%{$search}%")->paginate(10);
並び替え処理を組み込みました。IDでソートしてます。

2024-03-17 23:07 UTC, yukihiroLaravel approved these changes
問題ないのでマージしました！
お疲れ様でした😃

2024-03-17 23:08 UTC, yukihiroLaravel requested changes
コンフリクトが起きているのでその点だけ修正願います！
それ以外は完璧でした！

2024-03-19 02:34 UTC, yukihiroLaravel approved these changes
OKですのでまーじしました！
お疲れ様でした！！

2024-03-19 02:34 UTC, merged