フラッシュメッセージの表示
yukihiroLaravel/joint_develop pull request #1009
Opened 2024-03-10 14:36 UTC by yamaha-win

## issue
 - Closes #915
## 概要
 - ページの遷移と共にフラッシュメッセージの表示ができるようにしました。
 - 新規登録、ログイン、ログアウト、新規投稿、投稿の編集・削除、フォローする・フォロー解除、ユーザー情報の変更、退会処理
## 動作確認手順
 - 10の操作で、フラッシュメッセージが表示されるか確認をお願いします。
## 考慮してほしいこと
 - 今回は特にありません。
## 確認してほしいこと
 - 表示のしかたに問題が無いかご確認よろしくお願いします。

2024-03-11 01:15 UTC, yukihiroLaravel requested changes
少しコメントしましたのでご確認ください！

https://www.loom.com/share/eb4aa3e9395d4f30bc7e518c3d43000c?sid=743f98f1-304e-41d0-891e-cac9ccdc5e06

2024-03-11 01:15 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +            </div>
色や形が同じなら統一できる

2024-03-11 01:15 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                {{ session('updatesuccess') }}
もう少し普遍的な名前

2024-03-11 01:15 UTC, yukihiroLaravel commented on resources/views/users/edit.blade.php
> +        	{{ session('editsuccess') }}
もう少し普遍的な名前

2024-03-11 01:15 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +            </div>
もう少し普遍的な名前

2024-03-11 14:08 UTC, yukihiroLaravel requested changes
コメントしました！

2024-03-11 14:08 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                {{ session('updatesuccess') }}
updateSuccessMessage

2024-03-11 14:08 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +            {{ session('updateMessage') }} <!-- 新規登録、ユーザー情報変更、投稿内容変更 -->
updateSuccessMessage

2024-03-11 14:08 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +@endif
消せる？

2024-03-11 14:08 UTC, yukihiroLaravel commented on resources/views/users/edit.blade.php
> +        	{{ session('updateMessage') }} <!-- ユーザー情報変更 -->
updateSuccessMessage

2024-03-11 14:08 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        return redirect('/')->with('updateMessage', '投稿を更新しました');
updateSuccessMessage

2024-03-11 14:08 UTC, yukihiroLaravel commented on app/Http/Controllers/Auth/RegisterController.php
> +        session()->flash('updateMessage', 'ユーザーを登録できました');
updateSuccessMessage

2024-03-13 09:25 UTC, yamaha-win commented on resources/views/welcome.blade.php
> +@endif
logoutMessge → successMessageに変更しました

2024-03-13 14:48 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
お疲れ様でした！

2024-03-13 14:48 UTC, merged