Feature/nishida/follow
yukihiroLaravel/joint_develop pull request #1010
Opened 2024-03-10 15:26 UTC by osmnishida

## 概要
フォロー機能　"フォローする"ボタン、"フォローを外す"ボタン　実装
## 動作確認手順
- 下記urlにアクセスし、ユーザ詳細画面を表示する。
http://localhost:8080/users/[（ログインしているユーザ以外のユーザのid（整数値）]）
- フォローしていないユーザには、"フォローする"ボタンが表示される。
- "フォローする"ボタンをクリックし、データベースAdminer のfollowersテーブルに変更内容が反映されているかを確認
- フォローしているユーザには、"フォローを外す"ボタンが表示される。
- "フォローを外す"ボタンをクリックし、データベースAdminer のfollowersテーブルに変更内容が反映されているかを確認
- なお、ログインしているユーザ自身のユーザ詳細画面には、"フォローする"ボタン、及び、"フォローを外す"ボタンは表示されないことを確認。

2024-03-11 00:41 UTC, yukihiroLaravel requested changes
いくつかコメントさせていただきました！
よろしくお願いします☺️

https://www.loom.com/share/a54ff85092cc49a48f5ff19dcf6af4e2

2024-03-11 00:41 UTC, yukihiroLaravel commented on app/Follower.php
> +}
不要？

2024-03-11 00:41 UTC, yukihiroLaravel commented on app/User.php
> +    }
使われていない関数で上と同じ

2024-03-11 00:41 UTC, yukihiroLaravel commented on app/User.php
> +    public function isFollower($followerId)
$followerId を $userId に統一

2024-03-11 00:41 UTC, yukihiroLaravel commented on resources/views/follower/follower_button.blade.php
> +@endif
インデントがおかしいですね！
PHPコーディング規約ではスペース４つ分

2024-03-11 00:41 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                @endauth
インデントがおかしいですね！
PHPコーディング規約ではスペース４つ分

2024-03-11 00:41 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::get('{id}','UsersController@show')->name('user.show');
user詳細のルーティングは上に存在するので削除

2024-03-11 00:41 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('users/{id}/followers','UsersController@folloowers')->name('user.followers');
使われていないルーティングで
今後必要かもしれませんが、今は使われていないので削除

2024-03-11 00:41 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::post('follower','FollowerController@store')->name('follower');
followerというよりfollow

2024-03-11 00:41 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::delete('unfollower','FollowerController@destroy')->name('unfollower');
unfollowerというより
unfollow

2024-03-12 10:14 UTC, osmnishida commented on app/Follower.php
> +}
Follower.phpモデルは使っていなかったので、削除します。

2024-03-12 10:15 UTC, osmnishida commented on app/User.php
> +    }
使っていない関数でしたので、削除します。

2024-03-12 10:25 UTC, osmnishida commented on app/User.php
> +    public function isFollower($followerId)
$followerIdでは、確かに命名がおかしいところがあるとわかりました。$userIdに統一します。

2024-03-12 10:37 UTC, osmnishida commented on resources/views/follower/follower_button.blade.php
> +@endif
インデントについて、VS codeのタブの設定が、”2”になっていました。
設定を”4”にして、スペース４つ分に修正しました。

2024-03-12 10:40 UTC, osmnishida commented on resources/views/users/show.blade.php
> +                @endauth
こちらもスペース４つ分になるよう修正しました。

2024-03-12 10:43 UTC, osmnishida commented on routes/web.php
> +        Route::get('{id}','UsersController@show')->name('user.show');
40行目は重複していましたので、削除します。

2024-03-12 10:44 UTC, osmnishida commented on routes/web.php
> +Route::get('users/{id}/followers','UsersController@folloowers')->name('user.followers');
使っていないルーティングでしたので、削除します。

2024-03-12 10:49 UTC, osmnishida commented on routes/web.php
> +        Route::post('follower','FollowerController@store')->name('follower');
followerから、動詞のfollowに変更します。

2024-03-12 10:50 UTC, osmnishida commented on routes/web.php
> +        Route::delete('unfollower','FollowerController@destroy')->name('unfollower');
こちらも動詞のunfollowに修正します。

2024-03-13 15:03 UTC, yukihiroLaravel requested changes
１点指摘しましたので、ご確認お願いします！

2024-03-13 15:03 UTC, yukihiroLaravel commented on database/seeds/FollowersTableSeeder.php
> +            'followed_user_id' => 2
こちら、今のままだと
php artisan migrate:fresh --seed
というコマンドでイチからマイグレーションとシーダーを実行すると
エラーが出ます！

理由はusersTableシーダーがid 1~4までしかデータがないのに
このファイルでは5を使っているので
usersテーブルとフォロワーテーブルで不整合が起きているからです・・・！

修正お願いします！

2024-03-14 11:53 UTC, osmnishida commented on database/seeds/FollowersTableSeeder.php
> +            'followed_user_id' => 2
usersTableシーダーについてidを6まで増やして、エラーがないことを確認しました。

2024-03-14 13:13 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした☺️

2024-03-14 13:13 UTC, merged