フラッシュメッセージ1回目(川原)
yukihiroLaravel/joint_develop pull request #1011
Opened 2024-03-11 14:47 UTC by natsumi-kawahara-epkotsoftware

## issue
- Closes #899

## 概要
- 1回目として、新規投稿、投稿の編集時にフラッシュメッセージが表示されるようにしました。
- その他のフラッシュメッセージは、西田さん作業分がマージされた後に追加予定です。

## 動作確認手順
- http://localhost:8080/ へアクセスし、ログインした後、新規投稿、投稿の編集時にフラッシュメッセージが表示されるか確認をお願いします。

## 考慮して欲しいこと
- 今回は特にありません。

## 確認してほしいこと
- 表示に問題がないかご確認お願いいたします。

2024-03-12 12:41 UTC, yukihiroLaravel requested changes
いくつか指摘させて頂きましたので
ご確認ください！

2024-03-12 12:41 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        // return back();
ここ１行の不要になったコメントアウトは消してしまっていいと思います！

2024-03-12 12:41 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        // return redirect('/');
ここ１行の不要になったコメントアウトは消してしまっていいと思います！

2024-03-12 12:41 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +                {{ session('successMessage') }}
インデント２つ付けましょう（スペース８つ分右に移動させる）

2024-03-12 12:41 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +                {{ session('updatePost') }}
インデント２つ付けましょう（スペース８つ分右に移動させる）

2024-03-12 12:41 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +                {{ session('updatePost') }}
上のsuccessMessageという単語とupdatePostでは釣り合いが取れていない気がします！

2024-03-12 12:41 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +                {{ session('updatePost') }}
↓この解説動画ご確認ください！
https://www.loom.com/share/0195a63602a345779ddd53fcfb73e7bf?sid=8befe8b7-5d3f-437f-83e2-3bba02d9017a

2024-03-12 12:41 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        return redirect('/')->with('updatePost', '投稿を更新しました');
上のsuccessMessageという単語とupdatePostでは釣り合いが取れていない気がします！

↓この解説動画ご確認ください！
https://www.loom.com/share/0195a63602a345779ddd53fcfb73e7bf?sid=8befe8b7-5d3f-437f-83e2-3bba02d9017a

2024-03-13 12:48 UTC, natsumi-ohmura-dev commented on app/Http/Controllers/PostsController.php
> +        // return back();
@yukihiroLaravel 
削除対応させていただきました。

2024-03-13 12:52 UTC, natsumi-kawahara-epkotsoftware commented on app/Http/Controllers/PostsController.php
> +        // return redirect('/');
@yukihiroLaravel
削除対応させていただきました。

2024-03-13 13:43 UTC, natsumi-kawahara-epkotsoftware commented on resources/views/welcome.blade.php
> +                {{ session('updatePost') }}
@yukihiroLaravel 
動画ありがとうございます。
命名の際に汎用性を意識することをすっかり忘れていました。
今度かなり大切になってくるところだと思うので気をつけます。

2024-03-14 00:47 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！

2024-03-14 00:47 UTC, merged