#1014ユーザー情報の更新、退会処理のフラッシュメッセージ
yukihiroLaravel/joint_develop pull request #1019
Opened 2024-03-17 12:56 UTC by kiyoharu420

## issue 1014

## 概要
-　ユーザー情報の更新、ユーザー退会処理後のフラッシュメッセージ

## 動作確認手順
- ログインした状態で、ユーザー情報の更新、退会を行い、フラッシュメッセージを確認する。

## 考慮してほしいこと
　現状、ユーザー情報更新時に、メールアドレスを変えないと更新できない仕様になっているので、メールアドレスを変更してください。

2024-03-17 23:14 UTC, yukihiroLaravel requested changes
コメントしましたので、ご確認お願いいたします！

2024-03-17 23:14 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        return redirect('/')->with('updateMessage', 'ユーザーを削除しました');
ここのupdateMessageも
deleteMessageなどに書き換えた上で、

resources/views/welcome.blade.php
このファイルに
updateMessageなどの表示を真似する形で
deleteMessageのような内容を
記述すべきかと思いました！
（その場合は、CSSのクラスのところをあえて変えて
　alert-danger などで赤文字にするなども有効です）

2024-03-18 06:23 UTC, kiyoharu420 commented on app/Http/Controllers/UsersController.php
> +        return redirect('/')->with('updateMessage', 'ユーザーを削除しました');
ありがとうございます。

再度プルリクいたしました。
よろしくお願いいたします。

2024-03-19 02:36 UTC, yukihiroLaravel approved these changes
いいですね！
ちゃんと修正できてます😃
マージしましたのでお疲れ様でした！

2024-03-19 02:36 UTC, merged