#100 共通ファイル作成、#101 ヘッダー・フッター & トップページのタイトルのみ表示「Topic Posts」(そばた)
yukihiroLaravel/joint_develop pull request #102
Opened 2023-01-10 06:33 UTC by youzousobata

## issue
-Closes #100 
-Closes #101

## 概要
-共通ファイル作成
-ヘッダー・フッター & トップページのタイトルのみ表示「Topic Posts」

## 動作確認手順
-ブラウザのlocalhost:8080にアクセスして、ちゃんとトップページが表示されていることを確認

## 考慮してほしいこと
-なし

## 確認してほしいこと
-表示させているページの中で、余分なもの、不要なものがあれば教えてください。

2023-01-11 01:46 UTC, Osk0830 requested changes
お疲れ様です！
すごくよく書けていると思います！

いくつかコメントしたのでご確認ください。

2023-01-11 01:46 UTC, Osk0830 commented on resources/views/commons/header.blade.php
> +        </div>
- こちら、9行目に開かれた<ul>タグの閉じタグが抜けていないでしょうか？

2023-01-11 01:46 UTC, Osk0830 commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="" class="nav-link text-light">新規ユーザ登録</a></li>
- ここら辺は、今の段階でもできるので、ログイン時と非ログイン時に表示される内容が切り替わるような記述をしておいた方が良さそうですね。

2023-01-11 01:46 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +            <div class="w-75 m-auto">エラーメッセージが入る場所</div>
- 「エラーメッセージが入る場所」がここにあるようですが、app.bladeの方でもincludeされているようで。。。どれをどこに書くのが要件に適しているか確認してみてくださいね。

2023-01-11 02:03 UTC, youzousobata commented on resources/views/commons/header.blade.php
> +        </div>
ホントですね！
</ul>が、入ってなかったです。
ありがとうございます。

2023-01-11 02:06 UTC, yozosobata commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="" class="nav-link text-light">新規ユーザ登録</a></li>
わかりました！
ログイン機能のとこを参考にするといいでしょうか？

2023-01-11 02:08 UTC, youzousobata commented on resources/views/welcome.blade.php
> +            <div class="w-75 m-auto">エラーメッセージが入る場所</div>
はい、確認してみます！
ありがとうございます！

2023-01-16 03:15 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらしっかりと修正できているのでマージしますね！

マージ後は、

- develop_b_mutsuki_rabに戻る
- develop_b_mutsuki_rabのリポジトリの内容をプルする
- そこから新しい作業ブランチを切る

の順で作業進めてくださいね！

2023-01-16 03:15 UTC, merged