#993 コメント機能（オオハシ）
yukihiroLaravel/joint_develop pull request #1020
Opened 2024-03-18 15:46 UTC by kenta-oohashi

## issue
- Colses #993 
## 概要
- コメント機能
## 確認していただきたいこと
- トップページに表記されている投稿一覧の各投稿に「コメントする」ボタンが表記されており、そのボタンを押したら、コメント投稿ページへと飛ぶか
- コメント投稿ページでは、①一番上に、コメントをしたい投稿が表記されているか。②その下にその投稿にコメントされた一覧が出ているか。③さらにその下にコメント投稿フォームがあるか。
- コメント投稿フォームに入力し、「コメントをする」ボタンを押したら、アドマイナーに登録され、コメント一覧の所にコメントが反映されて表記されているか
- 140文字以上入力などをした際にバリデーションエラーがちゃんと出るか

2024-03-20 11:19 UTC, Osk0830 requested changes
お疲れ様でした！
概ねよくできていると思います！
修正が必要そうな箇所コメントしましたので、
確認よろしくお願いします！

2024-03-20 11:19 UTC, Osk0830 commented on app/Http/Controllers/CommentsController.php
> +        $comment->user_id = $user->id;
- ログイン中のユーザーのidだけが必要な場合、`Auth::id()`でidだけダイレクトに取得できます。そうなると、28行目と31行目をもう少しだけシンプルにまとめられそうですね。

2024-03-20 11:19 UTC, Osk0830 commented on database/migrations/2024_03_06_225930_create_comments_table.php
> +        $table->foreign('post_id')->references('id')->on('posts')->onDelete('cascade');
- こちらインデントがおかしくなってるので、インデントを揃えましょう。

2024-03-20 11:19 UTC, Osk0830 commented on database/migrations/2024_03_14_235201_add_soft_deletes_to_create_comments_table.php
- 今回はじめてコメントテーブル用のマイグレーションファイルを作っているので、別ファイルで追加するのではなく、一つのファイルにまとめて書きましょう。

2024-03-20 11:19 UTC, Osk0830 commented on resources/views/comments/show.blade.php
> +    <div style="margin-top: 40px;"></div>
- 4行目や6行目のように余白を設けるためだけに空要素を入れるのは避け、構造を考え直してみましょう。

2024-03-20 11:19 UTC, Osk0830 commented on resources/views/comments/form.blade.php
> +     <div class="w-75 m-auto">@include('commons.error_messages')</div>
- `body`ではユーザーが何のことだかわからないので、分かりやすい表現になるようにしましょう。

[![Image from Gyazo](https://i.gyazo.com/7ed0c054ef9fb395dfafdcc8753cb4bf.png)](https://gyazo.com/7ed0c054ef9fb395dfafdcc8753cb4bf)

2024-03-20 11:19 UTC, Osk0830 commented on routes/web.php
> +        Route::get('', 'CommentsController@index')->name('comments.index');
- 下記ページ、必要でしょうか？

[![Image from Gyazo](https://i.gyazo.com/615dc0808274498cf34d7d18ad572b1d.png)](https://gyazo.com/615dc0808274498cf34d7d18ad572b1d)

2024-03-20 11:19 UTC, Osk0830 commented on app/Http/Controllers/CommentsController.php
> +    }
- ルーティング部分でコメントした内容を検討いただき、ページが不要となれば、このアクション自体も不要になると思います。

2024-03-20 11:19 UTC, Osk0830 commented on app/Comment.php
- `Post`がソフトデリート（論理削除）となっているので、投稿削除時にそれに紐づいているコメントも削除するようにする記述を `Post.php`に追記する必要がありそうです。

2024-03-20 11:19 UTC, Osk0830 commented on app/Http/Controllers/CommentsController.php
> +            'user' => $user,
- 44行目でBladeに渡している `$user`のデータはどこで利用しているでしょうか？もし利用していないようであれば、渡す必要はないですね。そうなると 40行目での取得も不要になりますね。

2024-03-22 09:20 UTC, kenta-oohashi commented on app/Http/Controllers/CommentsController.php
> +        $comment->user_id = $user->id;
修正しました！

2024-03-22 09:20 UTC, kenta-oohashi commented on database/migrations/2024_03_06_225930_create_comments_table.php
> +        $table->foreign('post_id')->references('id')->on('posts')->onDelete('cascade');
インデントをそろえました！

2024-03-22 09:22 UTC, kenta-oohashi commented on database/migrations/2024_03_14_235201_add_soft_deletes_to_create_comments_table.php
softdeleteを足すためのテーブルを削除し、コメントテーブル用に追記し、php artisan migrate:fresh --seed
を行い、softdeleteを追加しました！

2024-03-22 09:23 UTC, kenta-oohashi commented on resources/views/comments/show.blade.php
> +    <div style="margin-top: 40px;"></div>
<div class="container mt-3">をそれぞれに使う事で解消しました

2024-03-22 09:23 UTC, kenta-oohashi commented on resources/views/comments/form.blade.php
> +     <div class="w-75 m-auto">@include('commons.error_messages')</div>
bodyを文字数に変更しました

2024-03-22 09:24 UTC, kenta-oohashi commented on routes/web.php
> +        Route::get('', 'CommentsController@index')->name('comments.index');
Route::get('', 'CommentsController@index')->name('comments.index');を使わずに一覧を表示できたので、削除しました

2024-03-22 09:25 UTC, kenta-oohashi commented on app/Http/Controllers/CommentsController.php
> +    }
indexルーティングを削除したのでこちらもコントローラから削除しました

2024-03-22 09:25 UTC, kenta-oohashi commented on app/Comment.php
そのような仕様にへんこうしました

2024-03-22 09:25 UTC, kenta-oohashi commented on app/Http/Controllers/CommentsController.php
> +            'user' => $user,
＄userを削除しました

2024-03-22 09:29 UTC, kenta-oohashi commented
## issue
- Colses #993 
## 概要
- コメント機能
## 確認していただきたいこと
- HANさんから頂いたご指摘の数々が修正されていて問題なくコメント機能が機能するようになっているか

2024-03-22 12:10 UTC, Osk0830 requested changes
お疲れ様でした！
修正確認できました！
1箇所だけおかしな箇所があるので、そこだけ確認お願いします！

2024-03-22 12:10 UTC, Osk0830 commented on resources/lang/ja/validation.php
> +        'body' => '文字数',
- これを文字数にしてしまうと、何も入力しないで送信した場合のメッセージ、おかしな感じになりませんかね？

2024-03-23 12:00 UTC, kenta-oohashi commented on resources/lang/ja/validation.php
> +        'body' => '文字数',
文字数を投稿に変更し、統一感を持たせました

2024-03-23 12:11 UTC, kenta-oohashi commented
## issue
- Colses #993 
## 概要
- コメント機能
## 確認していただきたいこと
- HANさんから頂いたバリデーションエラーの表記の統一が出来たか
- コンフリクトが起きていたのが解消したか

2024-03-25 12:26 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKそうなのでマージしますね！

2024-03-25 12:26 UTC, merged