#1021 画像付き投稿機能(近藤佑哉)
yukihiroLaravel/joint_develop pull request #1022
Opened 2024-03-18 16:48 UTC by yuyakondo333

## issue
 - Closes #1021 
## 概要
 - 画像付き投稿機能
## 動作確認手順

1.  トップページで画像を選択
2. 投稿するボタンをクリックして投稿一覧に表示されていることを確認
3. 文字か写真どちらかを必須を入力しないとバリデーションエラーが出ることを確認
4. ユーザー詳細画面でも画像付きの投稿があることを確認
5. 投稿の編集画面で画像が表示されており、画像を再選択して更新すると反映されていることを確認

## 考慮してほしいこと
 - 文字か写真どちらかを必須にしました。
## 確認してほしいこと
 - 上記の1~5の動作確認をお願い致します。
 - 全体の修正ポイントとして、他ユーザーの詳細画面へ遷移する動きも追加しました。

2024-03-19 02:47 UTC, yukihiroLaravel requested changes
かなりいい精度でできていると思います！

一部指摘させていただきましたのでご確認ください😃

2024-03-19 02:47 UTC, yukihiroLaravel commented on resources/views/posts.blade.php
> +            </p>
こちら、ログインできている場合に、
どのユーザの名前を押しても自分の詳細ページに遷移できてしまうのはおかしい気がします・・・！
元の記述に戻した方が良さそうですね

2024-03-19 02:47 UTC, yukihiroLaravel commented on resources/views/posts/edit.blade.php
> +        @endif
インデントを１つ付けましょう！

2024-03-19 14:34 UTC, yuyakondo333 commented on resources/views/posts.blade.php
> +            </p>
ミーティングでご指摘いただいた10行目だけ残して残りを削除します

2024-03-19 14:35 UTC, yuyakondo333 commented on resources/views/posts/edit.blade.php
> +        @endif
上記の5行全て1つインデントをつけます。

2024-03-20 00:47 UTC, yukihiroLaravel approved these changes
OKですのでマージしました！
お疲れ様でした😃

2024-03-20 00:48 UTC, merged