＃１０２４フォロー、フォロー解除のフラッシュメッセージ
yukihiroLaravel/joint_develop pull request #1030
Opened 2024-03-21 06:22 UTC by kiyoharu420

## issue 1024

# フォロー・フォロー解除のフラッシュメッセージ

# ログイン後、ユーザーのフォロー、フォロー解除をクリックして、フラッシュメッセージを確認お願いします。

2024-03-21 12:58 UTC, yukihiroLaravel requested changes
少しだけコメントしましたのでご確認ください！

2024-03-21 12:58 UTC, yukihiroLaravel commented on app/Http/Controllers/FollowController.php
> +        return redirect('/')->with('UnfollowMessage', $unfollowedUser->name . 'のフォローを解除しました');
UnfollowMessage
のUは小文字にしましょう！

2024-03-21 12:58 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +                        {{ session('UnfollowMessage') }}
UnfollowMessage
のUは小文字にしましょう！

2024-03-21 13:28 UTC, kiyoharu420 commented
・修正、再プルリクいたしました。よろしくお願いいたします。

2024-03-22 00:26 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした☺️

2024-03-22 00:26 UTC, merged