フォロー中、フォロワー表示（西田　修）
yukihiroLaravel/joint_develop pull request #1034
Opened 2024-03-23 11:41 UTC by osmnishida

## 概要
- フォロー中のアカウント表示、フォロワーアカウント表示
## 動作確認手順
- 下記urlにアクセスし、ユーザ詳細画面を表示する。
[http://localhost:8080/users/[（ログインしているユーザ以外のユーザのid（整数値）]）]
- "フォロー中"タグをクリックする。
フォロー中のアカウント（email、アバター画像、名前）が表示されることを確認
- "フォロワー"タグをクリックする。
フォロワーのアカウント（email、アバター画像、名前）が表示されることを確認

2024-03-23 23:59 UTC, yukihiroLaravel requested changes
いくつか指摘しました！

あと、コンフリクトが起きていますので解消願います！

2024-03-23 23:59 UTC, yukihiroLaravel commented on resources/views/users/followed.blade.php
> +    @endphp
不要なコードはプルリク前に必ずチェックして
消すようにしましょう！！

2024-03-23 23:59 UTC, yukihiroLaravel commented on resources/views/users/followed.blade.php
> +    @endphp
不要なコードはプルリク前に必ずチェックして
消すようにしましょう！！

2024-03-23 23:59 UTC, yukihiroLaravel commented on resources/views/users/following.blade.php
> +                {{$following->email}}
下記画像のように、メールアドレスの長さによって
複数フォローするといびつになってしまうので
メールアドレスの表示はないほうがいい気がします・・・！

2024-03-23 23:59 UTC, yukihiroLaravel commented on resources/views/users/following.blade.php
> +                    @endauth
pタグの終了タグを忘れていると思います！

2024-03-23 23:59 UTC, yukihiroLaravel commented on resources/views/users/following.blade.php
> +            </div>
なぜかcreated_atが最後のものしか表示されないので
これも消してもいいと思います（following_user_idも消してもいい気がします・・・！）

2024-03-23 23:59 UTC, yukihiroLaravel commented on resources/views/users/following.blade.php
> +            </div>
<img width="1164" alt="スクリーンショット 2024-03-24 8 53 00" src="https://github.com/yukihiroLaravel/joint_develop/assets/93365035/5282d62c-2e79-4e06-b099-39e35215f516">

2024-03-23 23:59 UTC, yukihiroLaravel commented on resources/views/users/following.blade.php
> +                    @endauth
<img width="1164" alt="スクリーンショット 2024-03-24 8 53 00" src="https://github.com/yukihiroLaravel/joint_develop/assets/93365035/8f86753c-53ec-4979-8fdb-cc853c51294e">

2024-03-24 00:11 UTC, osmnishida commented on resources/views/users/followed.blade.php
> +    @endphp
チェック漏れでした。不要なコード消しました。

2024-03-24 00:12 UTC, osmnishida commented on resources/views/users/followed.blade.php
> +    @endphp
チェック漏れでした。不要なコード消しました。

2024-03-24 00:13 UTC, osmnishida commented on resources/views/users/following.blade.php
> +                {{$following->email}}
メールアドレスの表示は、消しました。

2024-03-24 00:23 UTC, osmnishida commented on resources/views/users/following.blade.php
> +                    @endauth
pタグの終了タグを入れました。

2024-03-24 00:27 UTC, osmnishida commented on resources/views/users/following.blade.php
> +            </div>
created_at、following_user_id、両方消しました。
また、followed.blade.phpも同様にしました。

2024-03-24 04:00 UTC, yukihiroLaravel approved these changes
問題ないのでマージしました！
おつかれさまでした！

2024-03-24 04:00 UTC, merged