posts（投稿）テーブルのマイグレーションとシーダー作成
yukihiroLaravel/joint_develop pull request #1049
Opened 2024-04-09 15:52 UTC by yuuhei-koutoku

## issue
- 現在なし

## 概要
- 言語設定を日本語に修正
- Laravel Debugbarをインストール
- postsテーブル用のマイグレーションファイルを作成
- postsテーブルの初期データをシーダで作成

## 動作確認手順
- Laravel Debugbarを動作させるため、最新のコードをpullした後に、`composer install`を実行
- php artisan migrateでpostsテーブルを作成
- php artisan db:seedでpostsテーブルのシーダを作成

## 考慮して欲しいこと
- usersテーブルとの外部キー制約

## 確認して欲しいこと
- Laravel Debugbarをインストールして問題ないか
- たまやまさん(@masashi-tamayama)とのソースコードの競合
    [users（ユーザ）テーブルのマイグレーションとシーダー作成(たまやま) #1047](https://github.com/yukihiroLaravel/joint_develop/pull/1047)
- 修正したソースコード、全体を通して、ミスがないか

2024-04-10 01:20 UTC, Osk0830 requested changes
お疲れ様でした！
ほとんど問題なく書けていると思います。
コメントした内容と、以下2点確認お願いします。

①
外部キー制約を付与していますが、
まだユーザー情報が登録されていないので、
今のままだとエラーが起こると思います。
ちょうど玉山さんの内容がチームブランチにマージされましたので、
それを取り込み、再度マイグレーション＆シーディングを実行し、
問題がないことを確認してみてください。

②
上記過程に行うことになると思いますが、
コンフリクトが発生しているので、
解消よろしくお願いします！

※デバッガーを入れるかどうかはチーム内で確認・共有できてますでしょうか？

2024-04-10 01:20 UTC, Osk0830 commented on database/seeds/PostsTableSeeder.php
> +                'user_id' => 1,
- 一人の投稿だけですと、自分の投稿の場合と他人の投稿の場合の処理を実装する際に援用できないので、複数人の投稿が入るようにするのがいいですね。

2024-04-10 01:20 UTC, Osk0830 commented on database/seeds/PostsTableSeeder.php
> +        ];
- この方法もいいですが、単純に後ろの数字だけ増えていくのであれば、for文のカウンターを活用するのがスマートそうですね。仮にダミー投稿を100件登録したいとなると、この方法だとかなり冗長になりそうですね。

2024-04-11 07:00 UTC, yuuhei-koutoku commented
@Osk0830 

お疲れ様です！
いくつか修正したので、共有させていただきます。

- コンフリクト解消
    - `DatabaseSeeder.php`のコンフリクトを解消しました。
- 言語設定を元に戻す
    - `local`を`ja`から`en`に修正しました。別の方が日本語に修正対応を行います。
- Laravel Debugbarをアンインストール
    - チーム内で話し合った結果、今はLaravel Debugbarを使用しない方針となりました。（将来的には使うかもしれません。）
    - `composer remove barryvdh/laravel-debugbar`コマンドを実行して、アンインストールを行いました。
    - 参考：[安全に削除する方法Laravel Debugbar](https://www.web-dev-qa-db-ja.com/ja/php/%E5%AE%89%E5%85%A8%E3%81%AB%E5%89%8A%E9%99%A4%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95laravel-debugbar/836466761/)
- `posts`テーブルのシーダを改善しました。
    - 1人のユーザーだけではなく、複数人のユーザーの初期データを設定しました。
    - `for`文を使用し、できるだけスマートな記述にしました。
    - 他の方にも理解しやすいように、コメントアウトでの説明を多めに記載しています。
    - 将来的にページネーション（1ページ10件）を実装することを想定し、少し多めの30件のレコードを作成する仕組みにしています。

※ postsテーブルのシーダを抜粋（id：1〜10）
| id  | user_id | content     | created_at | updated_at | 
| --- | ------- | ----------- | ---------- | ---------- | 
| 1   | 1       | 初期ポスト1 | 現在日時   | 現在日時   | 
| 2   | 2       | 初期ポスト2 | 現在日時   | 現在日時   | 
| 3   | 3       | 初期ポスト3 | 現在日時   | 現在日時   | 
| 4   | 4       | 初期ポスト4 | 現在日時   | 現在日時   | 
| 5   | 1       | 初期ポスト5 | 現在日時   | 現在日時   | 
| 6   | 2       | 初期ポスト6 | 現在日時   | 現在日時   | 
| 7   | 3       | 初期ポスト7 | 現在日時   | 現在日時   | 
| 8   | 4       | 初期ポスト8 | 現在日時   | 現在日時   | 
| 9   | 1       | 初期ポスト9 | 現在日時   | 現在日時   | 
| 10  | 2       | 初期ポスト10 | 現在日時   | 現在日時   | 

※ 想定通りにpostsテーブルにレコードが作成されていることを確認済み
<img width="574" alt="スクリーンショット 2024-04-11 15 53 11" src="https://github.com/yukihiroLaravel/joint_develop/assets/68803595/056d14cb-cb77-4cf5-92de-9c8f3f88b9d3">

「`PostsTableSeeder.php`のロジックが問題ないか」と「コンフリクトが正しく解消されているか」を重点的に見ていただけると幸いです。
ご確認お願いいたします。

2024-04-11 12:24 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらしっかり修正できていると思いますので、
マージしますね！
引き続き頑張っていきましょう！

2024-04-11 12:24 UTC, merged