#98 users（ユーザ）テーブルのマイグレーションとシーダー作成（岡田）
yukihiroLaravel/joint_develop pull request #105
Opened 2023-01-12 10:42 UTC by yusukeokada2125

## issue
- Closes #98

## 概要
- users（ユーザ）テーブルのマイグレーションとシーダー作成

## 動作確認手順
- 【マイグレーション】
ターミナル上でphp artisan migrationを実行。
localhost:8088、Adminerのlaraveldb内のテーブルにusersが作成されていることを確認。
- 【シーダー】
php artisan db:seed --class=UsersTableSeederを実行
Adminerでusersテーブルに5個のレコードが保存されていることを確認。

## 考慮してほしいこと
- UsersTableSeeder.phpのテストデータ(test1~5)をfor文などで簡潔に書けていません。

## 確認してほしいこと
- 不足な点ありましたらよろしくお願いいたします。

2023-01-13 00:46 UTC, Osk0830 requested changes
お疲れ様でした！
概ね良くできていると思います。

少しコメントしましたのでご確認いただければと思います！

2023-01-13 00:46 UTC, Osk0830 commented on database/seeds/UsersTableSeeder.php
> +        ]);
- 今回は5件のデータなのでこの方式でもそれでも可能そうですが、実務においては数百、数千のダミーデータを登録しなければならないようなこともあり得ます。その場合、この方式だとさすがに厳しいと思います。コメントにも書いてらしたように、是非ループ文を使う形で修正してみてくださいね。

- 実際に登録されたデータを見ていただくとわかる通り、`DB::table()->insert()`メソッドですと、`created_at`と`updated_at`のカラムに値が入らず空のままになると思います。なので、これらのカラムにも値が入るように記述を追加するか、もしくは、モデルの`save()`メソッドを使う形に変更してこれらのカラムに自動的に値が入るようにしてみましょう。

2023-01-14 01:48 UTC, yusukeokada2125 commented on database/seeds/UsersTableSeeder.php
> +        ]);
2点の修正、承知いたしました。
「created_atとupdated_atのカラムに値が入らず空のままになる」というのがあまりピンと来ていませんが、調べて取り組ませていただきます。
行き詰まった場合は、ご質問いたします。

2023-01-15 04:30 UTC, Osk0830 approved these changes
お疲れ様でした！
こちら問題なく修正できているのでマージしますね！

マージされた内容をプルして、そこからブランチ切って、新しいタスクに進んでくださいね！

2023-01-15 04:30 UTC, merged