共通ファイル・ヘッダー・フッター & トップページのタイトル表示「Topic Posts」（とさか）
yukihiroLaravel/joint_develop pull request #1052
Opened 2024-04-13 11:52 UTC by tosakafullyremote

## issue
なし

## 概要
- 共通ファイル・ヘッダー・フッター & トップページのタイトル表示「Topic Posts」

## 動作確認手順
http://localhost:8080/
を表示。

- Router
┗（routes/web.php）の編集
- Controller
┗UsersControllerの作成　下記コマンドを実行と上書き
　┗php artisan make:controller UsersController
- View
┗全体に影響を与える大元の下記ファイル作成
　resources/views/layouts/app.blade.php
┗共通ファイルの下記作成
　resources/views/commons/error_messages.blade.php
　resources/views/commons/header.blade.php
　resources/views/commons/footer.blade.php

## 確認してほしいこと
- welcome.blade.php　に自信がなく確認いただきたい。
　┗9行目　「エラーメッセージが入る場所」の文字列は削除したほうが良いでしょうか？

2024-04-14 07:48 UTC, Osk0830 requested changes
お疲れ様でした！
ほぼ完璧にできてますね！
一点だけ修正必要な箇所がありコメントしましたので、
確認よろしくお願いします！

2024-04-14 07:48 UTC, Osk0830 commented on resources/views/layouts/app.blade.php
> +            @include('commons.error_messages')
- こちらにエラーメッセージようの部品を読み込んでしまうと、デモサイトとは違う箇所にエラーが表示されるようになってしまいます。エラーメッセージを表示させるためのパーツはどこに読み込むべきか、デモサイトを確認・検討してみてください。

2024-04-20 14:22 UTC, tosakafullyremote commented
## issue
#1052

## 概要
- 共通ファイル・ヘッダー・フッター & トップページのタイトル表示「Topic Posts」

## 動作確認手順
http://localhost:8080/
を表示。
View
┗resources/views/layouts/app.blade.php

## 確認してほしいこと

`            @include('commons.error_messages')
`
上記の記述について、削除いたしました。

私が検討した修正内容については下記です。
➀`@include('commons.error_messages')`　左記記述を削除
➁[welcome.blade.php](https://github.com/yukihiroLaravel/joint_develop/pull/1052/files#diff-45282f234e46f9b7d1e7afbdde83d06b670975a958ac221b0ec3c91d0156017d)　
の
`        <div class="w-75 m-auto">エラーメッセージが入る場所</div>`
を削除し、
`            @include('commons.error_messages')`
を追記する？と思いました。
しかし、現時点で「`http://localhost:8080/`」で再現できず、対応方法がよくわからなかったため、
チームMTG（4/20（土）21時開催）時に、メンバーと話し合いをさせていただきました。

結論としては、私のタスクの範囲外ではないか、という話になりましたので記述を削除いたしました。
あとあと必要ということであれば、その時に私が対応すればいいのではないか。という話にもなったのですが、こちらの対応でよろしいでしょうか？
お手数ですが、ご確認よろしくお願いいたします。

2024-04-20 23:32 UTC, Osk0830 requested changes
修正お疲れ様でした！
修正必要な箇所コメントしましたので、
確認よろしくお願いします！

2024-04-20 23:32 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +        <div class="w-75 m-auto">エラーメッセージが入る場所</div>
- 前回 layouts/appブレードあった、「エラー表示」に関する部品の読み込みが、ただ消されただけですかね？トップページでは少なくともこの9行目に読み込みましょう。「エラーメッセージが入る場所」というテキストと置き換えればOKですね。

2024-04-21 19:58 UTC, tosakafullyremote reviewed
## 動作確認手順
http://localhost:8080/
を表示。

## 確認してほしいこと
- [resources/views/welcome.blade.php]　を修正いたしました。
　┗9行目　「エラーメッセージが入る場所」の文字列削除し、9行目に　「        @include('commons.error_messages')」を記述。

2024-04-22 15:23 UTC, Osk0830 requested changes
お疲れ様でした！

エラーメッセージが表示される場所自体は正しい位置になりましたね！

ただ、少しだけ修正お願いしたい箇所がありコメントしましたので、
確認よろしくお願いします！

2024-04-22 15:23 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +        @include('commons.error_messages')
- エラーメッセージが表示される位置はこれでOKですが、もともとあったHTMLのタグまで削除してしまったため、エラーメッセージの表示幅がデモサイトと異なるものになってしまっています。

【現状】（臨時でエラーメッセージを表示させてみたものです）

[![Image from Gyazo](https://i.gyazo.com/4e4005fcb50da50f8293e35353baf5d7.png)](https://gyazo.com/4e4005fcb50da50f8293e35353baf5d7)

【デモサイト】

[![Image from Gyazo](https://i.gyazo.com/db0b0cbb979373251e029ec63c44e2a9.png)](https://gyazo.com/db0b0cbb979373251e029ec63c44e2a9)

2024-04-22 15:23 UTC, Osk0830 commented on resources/views/commons/header.blade.php
> +            </ul>
- 前回指摘できておらず恐縮ですが、ヘッダーの下記箇所は、ログインしている場合としていない場合で表示される内容が切り替わるようにしておきましょう。

[![Image from Gyazo](https://i.gyazo.com/142d321ff2d23e5cc4d9b65594170f0c.png)](https://gyazo.com/142d321ff2d23e5cc4d9b65594170f0c)

2024-04-23 21:57 UTC, tosakafullyremote commented
## 動作確認手順
http://localhost:8080/
を表示。

## 確認してほしいこと
- [resources/views/welcome.blade.php]
　9～11行目
削除してしまったhtmlタグを記述。

- resources/views/commons/header.blade.php
　10～16行目
@ifで条件分岐を追記
ログインしている場合としていない場合で表示される内容が切り替わるよう修正。

2024-04-24 05:31 UTC, Osk0830 approved these changes
修正お疲れ様でした！
こちらOKそうなのでマージしますね！
引き続き頑張っていきましょう！

2024-04-24 05:31 UTC, merged