Feature/toke/toppage display (toke)
yukihiroLaravel/joint_develop pull request #1056
Opened 2024-04-17 12:21 UTC by tokechan

## issue
- Closes #908 

## 概要
-トップページの投稿表示
-Fakerでダミーデータを実装（英語）
-Gravatorをインストールしてダミーアバター画像実装

## 動作確認手順
-下記コマンドを実行
php artisan migrate:fresh --seed
- Adminerでusersテーブル,postsテーブルに10個のレコードが保存されていることを確認

## 考慮して欲しいこと
状況に応じて、下記コマンドで動作確認する必要あり
php artisan migrate:fresh --seed

## 確認して欲しい事
posts.blade.phpのコードのリファクタリングをしたいです。他の書き方やスマートな書き方があれば教えて欲しいです。

```
@foreach ($posts as $post)

            <li class="mb-3 text-center">
                <div class="text-left d-inline-block w-75 mb-2">
                      <img class="mr-2 rounded-circle" src="{{ Gravatar::src($post->user->email, 55) }}" alt="ユーザのアバター画像">
                       <p class="mt-3 mb-0 d-inline-block"><a href="#">{{ $post->user->name ?? 'Unknown User' }}</a></p>
                       <p>{{ $post->content }}</p>
                       <p>{{ $post->created_at }}</p>
              </div>
           </li>
        @endforeach

```

2024-04-17 14:52 UTC, yukihiroLaravel requested changes
いくつか指摘させていただきましたので
ご確認お願いします！

2024-04-17 14:52 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $posts = Post::with('user')->orderBy('created_at', 'desc')->paginate(5);
orderBy('id', 'desc')
の方がいいと思います。

orderBy('created_at', 'desc')
だともし同タイミングで作成された場合、順番が
どちらが先かわからなくなるので！

2024-04-17 14:52 UTC, yukihiroLaravel commented on app/Post.php
> +
不要な空行は消しましょう！

2024-04-17 14:52 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +                       <p class="mt-3 mb-0 d-inline-block"><a href="#">{{ $post->user->name ?? 'Unknown User' }}</a></p>
なぜこのようにされているでしょうか？
{{ $post->user->name ?? 'Unknown User' }}

原則、postが存在するけどuserのnameがないという状況は考えにくいので
シンプルに下記になると思います！
{{ $post->user->name }}

2024-04-17 14:52 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +           </li>
この閉じタグの
インデントがおかしくないでしょうか？

2024-04-17 14:52 UTC, yukihiroLaravel commented on routes/web.php
> +// Route::get('/', 'UsersController@index');
こちらはコメントアウトせずに消してしまっていいと思います！

2024-04-17 14:52 UTC, yukihiroLaravel commented on database/seeds/UsersTableSeeder.php
> +        }
この辺りは伊藤さんのタスクの範疇になるかと思うのですが
その辺りが相談できているならOKです！

2024-04-17 14:52 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +                'created_at' => $createdAt(),
シーダー実行すると、この辺りで下記エラーが出ませんか？
Function name must be a string

2024-04-17 14:52 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +{{ $posts->links('pagination::bootstrap-4') }}
ページネーションは表示させてみてお手本のように正しい位置に表示されることを
確認されましたか？

これは下記のように間に入れることによって真ん中に表示されるのでこのように変えましょう。
<div class="m-auto" style="width: fit-content">{{ $posts->links('pagination::bootstrap-4') }}</div>

2024-04-17 14:52 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $posts = Post::with('user')->orderBy('created_at', 'desc')->paginate(5);
あと、お手本ですと
１０個/ページごとの表示なので
paginate(10);
だと思います！

2024-04-20 13:29 UTC, tokechan commented
## 現情報告
-全体的に修正完了しました
-[database/seeds/UsersTableSeeder.php]の部分だけイトウさんに相談ができておらずです

## 変更した所
-全体MTGの日に相談した、投稿が最新の降順うまく表示されない問題
-Fakerを使う項目と使わない項目を切り分けました
-forループを使用して、user_idを順番で出力
-ページネイションを正しい位置変更


## 確認して欲しい事
-再度、全体的にレビューお願いいたします

2024-04-20 19:17 UTC, yukihiroLaravel requested changes
ほぼOKですが、
不要な関数が残っていたのでそれだけ削除お願いします！

2024-04-20 19:17 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
>      }
PostsControllerのindexメソッドが使われるようになったことで
現状、この関数は使われなくなったので削除しましょう！

2024-04-21 15:42 UTC, tokechan commented
## 報告
-コンフリクトが起きていたので、動画を見ながら進めてなんとかコンフリクトを解消しました。

また、イトウさんが作成したUsersTabelSeederファイルのダミーデータ数が４件しかなく、私が書いたPostsTableSeederで設定していた最大数が合わなかったので、エラーが発生。
解消するべく、一旦イトウさんが作成したダミーデータ数に合わせてPostsTableSeeder内のダミーデータを4件にしております。
この件に関しては、明日の作業会にでも相談してページネイションが出せるくらいの数にしようと思っています。
以上です。

2024-04-22 00:04 UTC, yukihiroLaravel approved these changes
OKですのでマージしました！
シーダーの件もありがとうございます！！
お疲れ様でした！

2024-04-22 00:05 UTC, merged