#907 ユーザ詳細（三井）
yukihiroLaravel/joint_develop pull request #1059
Opened 2024-04-21 03:33 UTC by mtakk

## issue
- Closes #907 

## 概要
- ユーザ詳細

## 動作確認手順
- ローカル環境の場合、http://localhost:8080/users/1 に遷移する。（この例の場合はid:1のユーザが登録済みであることが前提）
- ページングの動作は、Adminerでpostsレコードのuser_idを全て同じにする。（http://localhost:8080/users/1の場合は「1」）

## 確認してほしいこと
- 別issueのログイン機能が未実装のため
   - 「ユーザ情報の編集」ボタンは表示されません。
- ヘッダーのログインユーザ名からの画面遷移は実装していません。（ログイン未実装のため）
- タイムラインクリック時の画面遷移は実装していません。（ログイン未実装のため）
- トップページの投稿からの画面遷移は実装していません。
- Gravatarはこのブランチで導入し、他のメンバーはcomposer update,composer installを実行してもらう想定です。

2024-04-21 09:19 UTC, yukihiroLaravel requested changes
ほぼ完璧ですが
細かい点でいくつか更に実装進められるところがありましたので
ご確認お願いいたします・・・！

2024-04-21 09:19 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +        <div class="m-auto" style="width: fit-content"></div>
ページネーションが中央揃えとなるように下記のように
タグの間にページネーションを挟みましょう！
```<div class="m-auto" style="width: fit-content">{{ $posts->links('pagination::bootstrap-4') }}</div>```

2024-04-21 09:19 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +        <div class="m-auto" style="width: fit-content"></div>
このタスクでは絶対ではないのですが
今後他の部分で使いやすいように
posts.blade.phpなどのファイルに
共通化してもいいと思いました！

2024-04-21 09:19 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                    <p class="mt-3 mb-0 d-inline-block"><a href="">{{ $user->name }}</a></p>
このページの実装だけだと分かりにくいですが
この部分はトップページの投稿一覧でも利用されるので
href=""のところに、このリンクをクリックしたら
このユーザ詳細画面に遷移するように記載しておきましょう！

2024-04-21 09:19 UTC, yukihiroLaravel commented on app/User.php
> +            ->orderBy('created_at', 'desc')
created_atでも悪くないのですが
同時間に投稿があった場合の判断が難しくなるので
idの降順にした方がいいかなと思いました！

2024-04-21 09:19 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $data = ['user'=> $user, 'posts'=>$posts];
ここも細かいのですが、より見やすい記述方法として
```
$data = [
    'user'=> $user,
    'posts'=>$posts
];
```
このようにしてもいいと思いました！

2024-04-21 09:19 UTC, yukihiroLaravel commented on routes/web.php
> +});
このファイルとは無関係ですが、お手数ながら
ログイン（新規登録）した後のヘッダーの自分の名前のところからも
ユーザ詳細画面に遷移できるように
ヘッダーも変更お願いします！

2024-04-21 09:19 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                </div>
ログイン機能が未実装だったので編集ボタンなどを配置していないということですが
（これもやや手間で恐縮ですが）
新規登録機能は実装済なので、それでログイン状態は作れるので
できれば新規登録後に、データベース上で登録したユーザの投稿を新規に１つ作って
編集ボタンなどの表示（クリックした後の動作は実装しなくてOK）を
確認してもらうことできますでしょうか？

2024-04-22 02:52 UTC, mtakk commented on resources/views/users/show.blade.php
> +        <div class="m-auto" style="width: fit-content"></div>
確かにですね...修正しました！

2024-04-22 02:57 UTC, mtakk commented on resources/views/users/show.blade.php
> +                    <p class="mt-3 mb-0 d-inline-block"><a href="">{{ $user->name }}</a></p>
追記しました！

2024-04-22 03:00 UTC, mtakk commented on app/User.php
> +            ->orderBy('created_at', 'desc')
idにしました！

2024-04-22 03:01 UTC, mtakk commented on app/Http/Controllers/UsersController.php
> +        $data = ['user'=> $user, 'posts'=>$posts];
修正しました！

2024-04-22 03:08 UTC, mtakk commented on routes/web.php
> +});
新規登録の時点でも動作確認も可能なんですね、実装しました！

2024-04-22 03:28 UTC, mtakk commented on resources/views/users/show.blade.php
> +                </div>
新規登録で動作確認できました！投稿の削除・編集もボタン追加しました！

2024-04-22 03:37 UTC, mtakk commented on resources/views/users/show.blade.php
> +        <div class="m-auto" style="width: fit-content"></div>
ここに分離しました！
views
└posts
　└post.blade.php

2024-04-22 09:38 UTC, yukihiroLaravel approved these changes
OKですのでマージしました！
お疲れ様でした😃

2024-04-22 09:38 UTC, merged