#910 ユーザログイン・ログアウト(あちょこ)
yukihiroLaravel/joint_develop pull request #1060
Opened 2024-04-21 16:16 UTC by achoko3

## issue
- Closes #910

## 概要
- ユーザのログイン・ログアウト

## 動作確認手順
- localhost:8080のヘッダーのログインをクリック
- ユーザログイン画面へ遷移するので今回はテストユーザーのe-mail,パスワードを入力し登録ボタンを押す
- トップページへ遷移したら右上にログインしたユーザの名前が表示されるか確認
- 名前の横のログアウトボタンを押すとログイン前の画面に戻る

## 確認して欲しいこと
- 各遷移先、表示が合っているか（コードの書き方も）を見て欲しいです

2024-04-22 11:53 UTC, achoko3 commented
コンフリクトの解消をしましたので再提出します。
よりしくお願いいたします。

2024-04-22 12:56 UTC, yukihiroLaravel requested changes
１点修正

2024-04-22 12:56 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('/', 'UsersController@index');
これ不要

2024-04-24 14:11 UTC, yukihiroLaravel approved these changes
マージしました！

2024-04-24 14:11 UTC, merged