#910 ユーザログイン・ログアウト (ミン)
yukihiroLaravel/joint_develop pull request #1061
Opened 2024-04-23 02:11 UTC by MinHubname

## issue
• Closes #910

## 概要
• ユーザログイン・ログアウトの実施

## 動作確認手順
•下記トップページにて右上のログインボタンをクリック
http://localhost:8080
または
http://localhost:8080/login
でログイン画面に代わる事を確認

ログアウトも出来るかの確認

## 考慮してほしい事
• ログアウト機能も確認のため
新規ユーザ登録をする必要があるかと思います

2024-04-23 20:38 UTC, yukihiroLaravel requested changes
少しコメントしましたのでご確認ください！

2024-04-23 20:38 UTC, yukihiroLaravel commented on composer.json
> +        "dionbosschieter/gravatar": "^0.2.0",
gravatarはもう入っているかと思うのでここで記述する必要はないかと思いました！

2024-04-23 20:38 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="{{ route('login.post') }}" class="nav-link text-light">ログイン</a></li>
ここはログイン画面に遷移すべきなので
{{ route('login') }}
ではないでしょうか？

2024-04-24 06:13 UTC, MinHubname commented
## 質問事項

ディレクトリファイル
composer.jsonの
12行目にあった
  "dionbosschieter/gravatar": "^0.2.0",

もう入ってると言う事なので・・どこに入ってるのかはわかりませんが
こちらは削除してよかったのですね

composer.json　がよくわかってない部分なのですが

composerが
PHPのパッケージ・ライブラリ管理ツールのようなので


今回ドッカー内で下記コマンドでインストールしたのですが
```composer require dionbosschieter/gravatar```

もしかしたら三井さんが先にインストールしてるので本来は
```composer install```
でよかったのだろうか・・・

なにやらよくわからないので

少し教えて頂ければと思います

2024-04-24 08:41 UTC, yukihiroLaravel approved these changes
> もしかしたら三井さんが先にインストールしてるので本来は
> composer install
> でよかったのだろうか・・・
その通りで、composer install で三井さんのインストールしたライブラリは
ミンさんの手元にも入るので、自分でgravatarをインストールするコマンドは必要ないですね。
ただ、もうやってしまったことは仕方ないので
今からはcomposer系に関しては何もしなくて大丈夫です！

それ以外はOKなのでマージしました！
お疲れ様でした😃

2024-04-24 08:41 UTC, merged