#905 投稿新規作成（三井）
yukihiroLaravel/joint_develop pull request #1067
Opened 2024-04-26 08:09 UTC by mtakk

## issue
- Closes #905  

## 概要
- 投稿新規作成

## 動作確認手順
- 以下ローカル環境の場合
- ログインせずにhttp://localhost:8080/ に遷移し、投稿入力欄と「投稿する」ボタンが表示されていないことを確認
- ログインして、http://localhost:8080/ に遷移し、投稿入力欄と「投稿する」ボタンが表示されていることを確認
- 0文字または141文字以上入力して投稿すると、エラーメッセージが表示されることを確認
- 1文字以上、140文字以下で入力して投稿すると、処理が終了する
- adminerでPostsテーブルにデータが登録されていることを確認できる

## 確認してほしいこと
- 遠藤さんがPosts→Postの名前変更対応中ですが、このブランチでは未対応なのでPostsのままです。
  - マージタイミングによりコンフリクトが発生したら直します。

2024-04-26 10:33 UTC, yukihiroLaravel requested changes
少しコメントしましたのでご確認お願いします！

2024-04-26 10:33 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +  }
インデントがスペース２つ分になっているので
PHPでは一般的なスペース４つ分に変更しましょう

2024-04-26 10:33 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +  }
ここは遠藤さんのタスクなので今回の実装では削除しましょう

2024-04-26 10:33 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::post('', 'PostsController@store')->name('post.store');
結果は同じですが、
Route::post('/',
このように分かりやすよう、スラッシュを入れておきましょう。

2024-04-26 10:33 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +            <textarea class="form-control" name="content" rows=""></textarea>
rows="4"
にして、入力欄に高さが出るようにしましょう

2024-04-26 12:18 UTC, mtakk commented on app/Http/Controllers/PostsController.php
> +  }
修正しました！

2024-04-26 12:19 UTC, mtakk commented on app/Http/Controllers/PostsController.php
> +  }
削除しました！

2024-04-26 12:19 UTC, mtakk commented on routes/web.php
> +        Route::post('', 'PostsController@store')->name('post.store');
修正しました！

2024-04-26 12:20 UTC, mtakk commented on app/Http/Controllers/PostsController.php
> +  }
修正しました！

2024-04-26 12:21 UTC, mtakk commented on resources/views/welcome.blade.php
> +            <textarea class="form-control" name="content" rows=""></textarea>
修正しました！

2024-04-29 14:30 UTC, yukihiroLaravel approved these changes
OKにつき、マージしました！
お疲れ様でした😃

2024-04-29 14:30 UTC, merged