#910 ユーザログイン・ログアウト（とさかゆうすけ）
yukihiroLaravel/joint_develop pull request #1069
Opened 2024-04-27 00:08 UTC by tosakafullyremote

## issue
- Closes #910 

## 概要
- ユーザログイン・ログアウト

## 動作確認手順
- http://localhost:8080/ へアクセス
画面右上にある「ログイン」を押下し、ログイン画面になっていることを確認
- テストのため、tinkerにてユーザーを作成
メールアドレス：'yusuke@sample.com'
パスワード：'yusuke'
を入力し、ログインボタンを押下
- ログイン後の画面が「Topic Posts」であることを確認し、右上に「ユーザー名」「ログアウト」があることを確認
- 右上の「ログアウト」を押下し、トップページに遷移することを確認

## 考慮してほしいこと
特にありません。

## 確認してほしいこと
特にありません。

2024-04-29 00:54 UTC, Osk0830 requested changes
お疲れ様でした！
ほぼOKです！
1箇所だけ修正いただきたい箇所がありますので、
確認よろしくお願いします！

2024-04-29 00:54 UTC, Osk0830 commented on resources/views/auth/login.blade.php
> +                </div>
- バリデーションで弾かれた際に、パスワードは既存の入力内容保持させず、再度入力させるようにした方が良さそうです。

2024-05-01 21:51 UTC, tosakafullyremote commented
## issue
- Closes #910 

## 概要
- ユーザログイン・ログアウト

## 動作確認手順
- http://localhost:8080/ へアクセス
画面右上にある「ログイン」を押下し、ログイン画面になっていることを確認
パスワードが残らないように下記のように修正

[resources/views/auth/login.blade.php]　２０行目
`<input id="email" type="text" class="form-control" name="email" value="{{ old('email') }}">
`の
`{{ old('email') }}`　を削除

## 考慮してほしいこと
特にありません。

## 確認してほしいこと
routes/web.php
にてコンフリクトが発生し解消しております。
併せてご確認よろしくお願いいたします。

2024-05-02 01:40 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKそうなのでマージしますね！
引き続き頑張っていきましょう！

2024-05-02 01:40 UTC, merged