ユーザ詳細（ゆうへい）
yukihiroLaravel/joint_develop pull request #1073
Opened 2024-04-29 15:18 UTC by yuuhei-koutoku

## issue
- Closes #907 

## 概要
- ユーザ詳細を実装。

## 動作確認手順
- Dockerコンテナを起動した状態で http://localhost:8080 にアクセス。
- 投稿一覧におけるユーザのリンクをクリック。
- 既存の投稿がない場合は、`php artisan migrate:fresh --seed`コマンドにて初期データを登録することを推奨。

## 考慮して欲しいこと
- ユーザ情報編集、タイムライン、フォローなどは、ハリボテの状態であること。

## 確認して欲しいこと
- `web.php`におけるコンフリクトを解消した。問題なくコンフリクトを解消できているかどうかを確認して欲しい。

## イメージ画像
<img width="990" alt="スクリーンショット 2024-04-30 0 23 28" src="https://github.com/yukihiroLaravel/joint_develop/assets/68803595/72f4a03a-35a8-464a-ba9a-8dd50052c150">

2024-04-30 03:54 UTC, Osk0830 requested changes
お疲れ様でした！
ほぼ問題ないと思います！

少しだけコメントしましたので、確認よろしくお願いします。

あと、ヘッダーの該当箇所にも、ユーザー詳細画面へのリンク貼っておいてください。

2024-04-30 03:54 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +                        </div>
- このへんインデントが少しおかしくなっているので調整お願いします！

2024-04-30 03:54 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="" class="nav-link {{ Request::is() ? 'active' : '' }}">タイムライン</a></li>
- この部分（18行目）だけは現状で実装してしまえると思います！その際、`Request::is()`もいいですが、それだと記述が煩雑になっていくので、`Request::routeIs()`がよりスマートそうです。

https://ensei1375.com/laravel-url-judge/

2024-04-30 04:17 UTC, yuuhei-koutoku commented
@Osk0830 
コードレビューありがとうございます。
ご指摘いただいた2点を修正いたしました。

- `div`タグのインデントを修正
- タイムラインリンクの三項演算子の条件式を修正

ご確認をお願いいたします。

2024-05-01 06:32 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKなのでマージしますね！

2024-05-01 06:32 UTC, merged