ユーザ新規登録（たわらつみだ　まなぶ）
yukihiroLaravel/joint_develop pull request #1074
Opened 2024-04-29 22:44 UTC by manabuandy

## issue
- なし

## 概要
- ユーザ新規登録実装

## 動作確認
- localhost:8080/signupにて確認をお願いします

## 考慮して欲しいこと
- app.blade.phpファイルが実装された状態で動作確認しております
- 動作確認ができない場合は、register.blade内の次の記述を削除してから動作確認をお願いします　
　@extends('layouts.app')
　@section('content')
　@endsection

## 以下作成内容を示します
- web.php
　新規登録のルーティング記載しております

- register.blade
　新規作成しております

- header.blade.php
　新規登録画面遷移用のルーティングを記載しております
　 <li class=・・・<a href="{{ route('signup') }}" ・・・・新規ユーザ登録</a></li>

- RegisterController.php
　新規登録画面遷移後トップページへ遷移する内容を記載しております
　protected $redirectTo = '/';

##　間違えたこと
-　RegisterController.phpへユーザ退会の記述を一部記載してしまったので元へ戻しております

## 確認して欲しいこと
-    説明文の記載形式についてわかりやすいかのアドバイスをいただけると助かります

2024-04-30 03:45 UTC, Osk0830 requested changes
お疲れ様でした！
大枠ではできていると思います。
修正が必要な箇所コメントしましたので、
確認よろしくお願いします！

2024-04-30 03:45 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +    </div>
- ぷれびゅーしてみると、表示崩れが起きているようです。HTMLのタグに問題がありそうですので、モックアップと照らし合わせながらおかしな箇所がないか確認し、修正お願いします。

[![Image from Gyazo](https://i.gyazo.com/5238d571948eb9ff941b24b69a2e6817.png)](https://gyazo.com/5238d571948eb9ff941b24b69a2e6817)

2024-04-30 03:45 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +    <div class="row mt-5 mb-5">
- バリデーションで弾かれた際にエラーメッセージが表示されません。エラーメッセージ用のパーツを適切な場所に読み込み動作確認してみてください。（メッセージは日本語化が完了していない段階なので、英語表示でOKです）

[![Image from Gyazo](https://i.gyazo.com/7528196f03cb1cc960d714a3b3cb2ca7.png)](https://gyazo.com/7528196f03cb1cc960d714a3b3cb2ca7)

2024-04-30 03:45 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +                </div>
- パスワードと確認用パスワードは、バリデーションで弾かれた際に、既存の入力内容を保持・表示させず、再度入力させるようにしましょう。

2024-05-01 08:12 UTC, manabuandy commented
プレビューした場合の表示崩れをまだ解消しておりません。
全体に影響を与えるapp.blade.phpへエラーメッセージ表記を記載してしまいました。
こちらはregister.blade.phpへ記載修正します。全てを修正しプルリクエストいたします。もう少しお待ちください。

2024-05-01 12:24 UTC, manabuandy commented
プレビューした場合の表示崩れをまだ解消しております。
最新のdevelop_c_uduki_draを作業ブランチへマージしました。
新規登録画面内で新規登録押下した際に画面がトップページ遷移しません。
このような状態で確認する方法があれば是非アドバイスをお願いします。

2024-05-02 05:26 UTC, manabuandy commented
ユーザ新規登録後の画面遷移を修正しました。
コンフリクト解消しました。

2024-05-02 11:28 UTC, Osk0830 requested changes
お疲れ様でした！
前回の指摘内容がある程度修正されていますね！
ただ、まだ修正できていなかったり、デモサイトと違っていたりする箇所がありますので、
確認よろしくお願いします！

2024-05-02 11:28 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +                </div>
- こちら修正できていないようですが、いかがでしょう？

2024-05-02 11:28 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +    <div class="row mt-5 mb-5">
- バリデーションメッセージは表示されるようになりましたが、メッセージの赤いボックスのサイズがデモサイトと違っていると思います。パーツを読み込む位置を調整し、ボックスのサイズがデモサイトと同じになるようにしましょう。

[![Image from Gyazo](https://i.gyazo.com/8ada2d257822b7e409a46f5f9e8991fb.png)](https://gyazo.com/8ada2d257822b7e409a46f5f9e8991fb)

2024-05-02 14:29 UTC, manabuandy commented
パスワード入力とパスワード確認欄ですがregister内の
該当記述内のold関数を削除し、動作確認を行ったところ
パスワードが一致しないとう画面が出て新規登録ができない
状態となりましたので、エラーメッセージの表示のみをご確認いただけると幸いです
よろしくお願いします

2024-05-04 14:14 UTC, manabuandy commented
パスワード入力とパスワード確認が一致しないエラーが解消しました
よろしくお願いします

2024-05-05 07:26 UTC, manabuandy commented
前回登録した内容では何も入力しない状況で
パスワード欄に******があることがわかりましたので
再度修正いたしました。
パスワード入力とパスワード確認が一致しないエラーが解消しました
よろしくお願いします

2024-05-05 09:11 UTC, Osk0830 approved these changes
お疲れ様でした！
こちら機能的にはOKそうなのでマージしますね！

ただ、下記箇所がまた表示崩れ起きているようですので、
他のタスクの作業時にでも修正しておいてくださいね！

[![Image from Gyazo](https://i.gyazo.com/835c82f369b71693bddf69f59c4f8306.png)](https://gyazo.com/835c82f369b71693bddf69f59c4f8306)

2024-05-05 09:12 UTC, merged