#903 posts edit display update add (Tokeshi)
yukihiroLaravel/joint_develop pull request #1077
Opened 2024-05-01 08:57 UTC by tokechan

## issue
- Closes #903 

## 概要
- 投稿編集、更新を実装完了
- Route 設定　投稿編集関連　edit,updateを実装
- Controller 設定　PostsControllerにedit,update関数メソッドを実装
- Requests 設定　RequestsフォルダにPostRequest.phpファイルを作成しバリデーションを実装

## 動作確認手順
- Dockerコンテナを起動した状態でhttp://localhost:8080/にてtestアカウントでログインする
- http://localhost:8080/users/1/edit のURLを直接入力して投稿編集画面へ遷移する
- ログインしていないユーザーはloginへ遷移することを確認
- 投稿内容を140以内であれば、更新成功
- 140以上であればバリデーションエラーが表示
- 成功すると、リダイレクトによりtoppageへ遷移する

## 考慮して欲しいこと
- ユーザー詳細がまだ未実装のため、/users/1/edit直URL打ちで確認してます

## 確認して欲しい事
- 投稿更新後にtoppageに遷移する際のメソッドはredirectでよかったのかどうか悩みました。
下記のコードでもいいかと思いましたが、シンプルの方がいいと思いredirectにしました。
考え方は間違ってないでしょうか。

```
public function update(PostRequest $request, $id) 
{
    $post = Post::findOrFail($id);
    $post->content = $request->content;
    $post->save();

    // ポストを更新した後、全てのポストを取得
    $posts = Post::orderBy('id', 'desc')->paginate(10);  // ページネーションも考慮

    return view('welcome', ['posts' => $posts]);
}
```

2024-05-01 10:46 UTC, yukihiroLaravel requested changes
いくつか指摘させていただきましたので
ご確認お願いします！

2024-05-01 10:46 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        return redirect()->route('posts.index'); //toppageへリダイレクト
PRGの原則というのがありますので
viewを返すのだとうまくいかないので
リダイレクトを使わないといけないので合っています！

2024-05-01 10:46 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +            return view('posts.edit', ['post' => $post,]);
細かいですが
['post' => $post,
ここの最後のカンマは不要かと思います！

2024-05-01 10:46 UTC, yukihiroLaravel commented on routes/web.php
> +
ここの空行も特に意味はないかと思いますので消しましょう！

2024-05-01 10:46 UTC, yukihiroLaravel commented on resources/views/posts/edit.blade.php
> +            <textarea id="content" class="form-control" name="content" rows="5"></textarea>
今の状態だと
お手本のように変更前のcontentが表示されていないので
表示されるようにしましょう

2024-05-01 10:46 UTC, yukihiroLaravel commented on resources/views/posts/edit.blade.php
> +@extends('layouts.app')
このファイルとは無関係ですが、
トップページなどから編集画面に遷移できるように
ログインしたら編集ボタンが出現するような対応もお願いします！

2024-05-02 13:52 UTC, tokechan commented on app/Http/Controllers/PostsController.php
> +        return redirect()->route('posts.index'); //toppageへリダイレクト
完了

2024-05-02 13:52 UTC, tokechan commented on app/Http/Controllers/PostsController.php
> +            return view('posts.edit', ['post' => $post,]);
削除完了

2024-05-02 13:53 UTC, tokechan commented on routes/web.php
> +
削除完了

2024-05-02 13:53 UTC, tokechan commented on resources/views/posts/edit.blade.php
> +            <textarea id="content" class="form-control" name="content" rows="5"></textarea>
修正完了

2024-05-02 13:53 UTC, tokechan commented on resources/views/posts/edit.blade.php
> +@extends('layouts.app')
あちょこさんに依頼して、マージして最新化完了

2024-05-02 16:15 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
お疲れ様でした！

2024-05-02 16:15 UTC, merged