#911 Feature/mizuki/user register(mizuki ito)
yukihiroLaravel/joint_develop pull request #1078
Opened 2024-05-01 14:19 UTC by mizuki012

## issue
- Closes #911 
-
## 概要
-ユーザー新規登録の実装

## 動作確認手順
-Dockerコンテナを起動した状態で http://localhost:8080/ にアクセスし、お手本通りに起動するかを確認。

## 考慮して欲しいこと
-特になし。

## 確認して欲しい事
-複数の箇所のコンフリクトを解消しました。問題なくコンフリクトを解消できているかどうかを確認していただきたいです。

2024-05-01 21:36 UTC, yukihiroLaravel requested changes
いい感じだと思いますが、
一点だけ指摘がありまして、

login.blade.phpを少しだけ書き換えて
「新規ユーザ登録する？」
というリンクを押した時に
register.blade.phpが表示されるように
しましょう！

2024-05-01 21:36 UTC, yukihiroLaravel commented on resources/views/auth/register.blade.php
> +@endsection
いい感じだと思います！

このファイルではありませんが、
login.blade.phpを少しだけ書き換えて
「新規ユーザ登録する？」
というリンクを押した時に
register.blade.phpが表示されるように
しましょう！

2024-05-02 14:31 UTC, mizuki012 commented on resources/views/auth/register.blade.php
> +@endsection
修正しました！

修正してした際に、新しいブランチを切らずにユーザー詳細のタスクをこなそうとしたために、
追加したファイルの影響により、正しい挙動ができなくなったため、追加したファイルを削除しております。

そのうえで、修正した内容で、正しく作動するかを確認いたしました。
ご確認よろしくお願い致します。

2024-05-02 16:17 UTC, yukihiroLaravel approved these changes
かしこまりました！
OKなのでマージしました！
お疲れ様でした！！

2024-05-02 16:17 UTC, merged