#903 投稿編集画面・更新（ゆうへい）
yukihiroLaravel/joint_develop pull request #1082
Opened 2024-05-03 00:52 UTC by yuuhei-koutoku

## issue
- Closes #903

## 概要
- 投稿編集画面・更新

## 動作確認手順
- Dockerコンテナを起動した状態で http://localhost:8080/ にアクセスする。
- ログインする。（例：メールアドレス：test1@test.com、パスワード：test1）
- 「編集する」ボタンをクリックする。
- 本文を編集する。
- 「更新する」ボタンをクリックする。

## 考慮して欲しいこと
- 特になし。

## 確認して欲しいこと
- 編集画面の「更新する」ボタンをクリックすると、想定通りにポストが更新され、トップページに遷移すること。
- #1081 とのコンフリクトが発生するか。（もし発生するなら、こちらのプルリクエストでコンフリクトを解消したい。）

## 完成イメージ
https://github.com/yukihiroLaravel/joint_develop/assets/68803595/0874da58-93aa-4add-b885-11429e741c2b

2024-05-05 09:20 UTC, Osk0830 requested changes
お疲れ様でした！
概ね問題ないと思います！
少しだけコメントしましたので、確認よろしくお願いします！

2024-05-05 09:20 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +}
- 投稿の編集・更新という作業ですので、コントローラー内でも、投稿者本人である場合にのみ処理できるようにした方がいいですね。

2024-05-05 09:20 UTC, Osk0830 commented on resources/views/posts/edit.blade.php
> +        </div>
- ユーザビリティの観点から、バリデーションで弾かれた際に既存の入力内容が保持されるようにできているといいですね。

2024-05-05 09:20 UTC, Osk0830 commented on routes/web.php
> +Route::get('/', 'PostsController@index')->name('/');
- nameは、`top`とかの方がわかりやすくないでしょうか？

2024-05-05 09:20 UTC, Osk0830 commented on routes/web.php
> +  Route::patch('posts/{id}/update', 'PostsController@update')->name('posts.update');
- `posts`の部分が共通しているので、`prefix`を用いてまとめてあげると良さそうですね！

2024-05-06 07:46 UTC, yuuhei-koutoku commented
コードレビューありがとうございます。
指摘内容と改めて自分で見つけた改善点を修正したので、ご確認をお願いいたします。

- コントローラーにて、現在認証しているユーザーの投稿のみ編集・更新ができるよう、バリデーションとそれに伴うエラーメッセージ表示を追加しました。
- 本文未入力時のバリデーションとそれに伴うエラーメッセージ表示を追加しました。
- 編集画面初期アクセス時は既存の本文(`posts`テーブルの該当レコードの`content`カラムの値)、バリデーションで弾かれた際は直前の投稿内容を保持する仕組みに修正しました。
- `/`の名前付きルートを`top`に修正しました。
- 投稿関連のルーティングに関して、`posts`の箇所を`prefix`で共通化しました。

2024-05-06 09:35 UTC, Osk0830 requested changes
お疲れ様でした！
とてもいい感じにできていると思います！
バリデーションに関して一点だけ調整お願いします！

2024-05-06 09:35 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        ]);
- こちら、文字数制限のバリデーションも付け加えてください。

2024-05-07 14:22 UTC, yuuhei-koutoku commented
@Osk0830 
他の方が作成された`PostRequest`クラスを使用することで、バリデーションの修正を行いました。
ご確認をお願いいたします。

2024-05-08 00:33 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKそうなのでマージしますね！

2024-05-08 00:33 UTC, merged