#906 ユーザ編集画面・更新 （ミン）
yukihiroLaravel/joint_develop pull request #1083
Opened 2024-05-03 16:21 UTC by MinHubname

## issue
- Closes #906

## 概要
- ユーザ編集画面・更新

## 動作確認手順
- 下記ログインページにて登録してあるメールアドレス、パスワードを入力してログインする
http://localhost:8080/login  
ユーザの情報の編集を押した後
編集画面が表示される事を確認
別の名前、メールアドレス、パスワードなど変更したい部分を入力して
更新ボタンを押し、入力情報が更新されユーザログイン画面に戻る事を確認

## 考慮してほしいこと
- 誤った文字や文字数などでバリデーション表示がでるのかも確認していただければと思います
- 時間経過でログアウトしてしまった場合はトップページに戻るかも確認していただければと思います

2024-05-03 22:53 UTC, yukihiroLaravel requested changes
いくつかご指摘させていただきましたので
ご確認ください😊

2024-05-03 22:53 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        return view('users.edit', $data);
今の状態ですと、投稿した本人以外の人が投稿を編集しようとするとできてしまうので
条件分岐を使って本人しか投稿編集できないようにしてみましょう。

具体的にいうとこんな感じです。

if (本人以外を弾く条件) {
    return view('users.edit', $data)
}
abort(403)

2024-05-03 22:53 UTC, yukihiroLaravel commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255'],
Laravelでemailが他人と重複していた時に登録できないようにしないと
同じメールアドレスで登録できてしまいます！
下記の記事を参考にここのバリデーションを対応しましょう！

https://qiita.com/Hashimoto-Noriaki/items/69dcb1b128c4b2dc95e7

2024-05-03 22:53 UTC, yukihiroLaravel commented on resources/views/users/edit.blade.php
> +        <input type="hidden" name="id" value="" />
この１行は使われていないので今回は不要かと思いました！

2024-05-05 08:31 UTC, MinHubname commented
今回指摘があった
UsersController.php
のところなんですが

指摘に近い感じで直したのですが
この部分が
```        
        $data = [
            'user'=> $user,
        ];
        return view('users.edit', $data);
```

$dataを使わずにこの方がよいのかなとも

```
       return view('users.edit', ['user' => $user]);
```
どちらでも同じ意味とは思うのですが
どうなのでしょうか？

2024-05-05 09:05 UTC, yukihiroLaravel requested changes
OKです！
修正は完璧です！

聞いていただいた部分に関しては
このままでも悪くないと思ったので指摘しなかったのですが
せっかくならこちらも修正しましょう！

2024-05-05 09:05 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        return view('users.edit', $data);
これはこのままでも悪くはないですが
おっしゃる通り$dataに入れている変数が１種類なので
そのまま['user'=> $user]の形で
return view()
の()の中に入れてしまった方がいいですね！

2024-05-05 09:55 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
難しいところをお疲れ様でした😊

2024-05-05 09:55 UTC, merged