#917 フォロー機能（たまやま）
yukihiroLaravel/joint_develop pull request #1085
Opened 2024-05-04 13:15 UTC by masashi-tamayama

## issue
- closes  #917
## 概要
- ### MVCの流れで作成 [**中間テーブル用DB⇒UserModel⇒Router⇒Controller⇒View**]
- **中間テーブル用DB作成**
`database/migrations/2024_05_03_162606_create_follows_table.php`
`follower_id` と `followed_id` の二つの外部キーを設定
ユニーク制約を設定することで、同じユーザーを重複してフォローすることを防止
- **Userモデル実装**
`followers()` と `following()` にリレーションを設定
User モデルに特定のユーザーが他のユーザーをフォローしているかどうかをチェックする機能やフォローを解除する
機能を追加することで、フォローの確認や解除をより効率的に行うことができ、コードの保守性を向上
Tinkerによるモデルの動作を試験的に確認実施⇒問題なし
- **Router**
`routes/web.php`
認証ミドルウェアの設定を行いセキュリティ性を確保
- **Controller**
`app/Http/Controllers/FollowController.php`
ルーティングの認証ミドルウェア設定に対応した記述を行い `(auth()->user())`  を直接使用して
フォローやアンフォローの操作を行える様にコントローラを実装
- **View**
`resources/views/follow/follow_button.blade.php`
1. 自分自身をフォローできないようにする
2. フォロー状態の判断し条件に応じて異なるフォームを表示
3. CSRF保護を適用しフォームセキュリティを強化
- **View**
`resources/views/users/show.blade.php`
1. ユーザ詳細ページのカードの下に「フォローをする」ボタンを配置
2. ボタン周りはビューの見た目を整えつつ、必要なスペースを確保

## 動作確認手順

1. Dockerコンテナを起動した状態で `http://localhost:8088/` にアクセスする
2.  Adminerにてfollowsを選択し5つのカラム登録、2つの外部キー登録、ユニーク制約に `follower_id` と `followed_id` の2つの登録を確認
3. `http://localhost:8080/` にアクセスする
4. 新規ユーザ登録orログイン実行
5. ログイン後、トップページの投稿一覧から現在ログインしているユーザネームをクリックする
6. ユーザ詳細ページに移動し「フォローをする」ボタンの表示なしを確認
7. ログイン後画面に戻り、トップページの投稿一覧から現在ログインしているユーザネーム以外のユーザネームをクリックする
8. ユーザ詳細ページに移動し「フォローをする」ボタンの表示ありを確認
9. 「フォローをする」ボタンをクリックすると同じページになり「フォローを解除する」ボタンになる
10. Adminerにてfollows⇒データを選択し、フォローの登録内容を確認
11. ユーザ詳細ページに戻り「フォローを解除する」ボタンをクリックすると同じページになり「フォローをする」ボタンになる
12. Adminerにてfollows⇒データを選択し、フォローの削除内容を確認
13. ログアウトをクリックしトップページの投稿一覧からどれでも良いのでユーザネームをクリックする
ユーザ詳細ページに移動し「フォローをする」ボタンの表示なしを確認
## 考慮して欲しいこと
- 場合によっては下記コマンドの実行が必要
`php artisan migraet:fresh --seed`
- ヘッダーリンク修正マージ後、ユーザネームをクリック後にユーザ詳細ページに移動し「フォローをする」ボタンの表示なしの確認が必要
## 確認して欲しいこと
- 各コメントアウトの意味があっているか確認をお願いします。
- 先日のMTGで話に上がった単数形、複数形の使い分けが曖昧になってしまったので問題があるようであればご指摘の方をお願いします。

2024-05-05 09:40 UTC, Osk0830 requested changes
お疲れ様でした！
全体的んよくできていると思います！
少しだけ修正した方が良さそうな箇所コメントしましたので、
確認よろしくお願いします！

2024-05-05 09:40 UTC, Osk0830 commented on app/User.php
> +    }
- 現状、ロジック的に、自分自身についてもフォロー・アンフォローできてしまいます。自分自身である場合はフォローなどできないようにしておくのが良さそうですね。

[![Image from Gyazo](https://i.gyazo.com/12c014646615b0e6a49cf6ce4dd8569d.png)](https://gyazo.com/12c014646615b0e6a49cf6ce4dd8569d)

- 現在、コントローラー含めてフォロー対象ユーザーのデータをやり取りするのに、ユーザーモデルのインスタンスそのものをやり取りしているかと思います。もちろんこれでも全く問題はないですが、記述が若干煩雑な印象はありますので、対象ユーザーのIDだけやり取りする形もいいかもしれませんね。

2024-05-08 22:16 UTC, masashi-tamayama commented on app/User.php
> +    }
- 修正しました。Tinker画像添付します。ご確認をお願いします。
![スクリーンショット 2024-05-09 062806](https://github.com/yukihiroLaravel/joint_develop/assets/156323724/99fdab5b-a8a6-4b1e-8ee6-71a934b0252d)

2024-05-09 02:45 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKそうなのでマージしますね！

以下2点は検討してみる可能性もありますが、
今のままでも問題ないと思います！

- idの使用だけで全て統一するかどうか（今混在している感じだと思います）
- if文を分けて書くか一つにまとめるか（returnする結果が同じなので一つにまとめて書くことも結構ある印象です）

2024-05-09 02:45 UTC, merged