#906ユーザ編集画面・更新（とさか）
yukihiroLaravel/joint_develop pull request #1088
Opened 2024-05-05 20:24 UTC by tosakafullyremote

## issue
- Closes #906

## 概要
- ユーザ編集画面・更新

## 動作確認手順
- http://localhost:8080/ へアクセス
メールアドレス：'yusuke@sample.com'
パスワード：'yusuke'
を入力し、ログインボタンを押下
ユーザー編集画面への導線がないため、URLに下記を打ち込む
`http://localhost:8080/users/5/edit`

## 考慮してほしいこと
チームMTG時に共有で共有できていればよかったが、編集画面への導線がない。

## 確認してほしいこと
特にありません。

2024-05-06 01:17 UTC, Osk0830 requested changes
お疲れ様でした！
概ねよくできていると思います！
何点かコメントしましたので、確認よろしくお願いします！

また、詳細画面の下記箇所に、編集画面へ遷移するためのリンクも貼っておいてくださいね。
（本人のページでだけボタンが表示されるようにお願いします）

[![Image from Gyazo](https://i.gyazo.com/8e2f6652a2ae4ff90a9d00c529688bc4.png)](https://gyazo.com/8e2f6652a2ae4ff90a9d00c529688bc4)

2024-05-06 01:17 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +        $user = User::find($id);
- 何らかの要因でDBに存在しないidが渡された場合でも内部的なエラーにならないよう、`findOrFail()`を使うようにしましょう。

2024-05-06 01:17 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +        return redirect()->route('users.show', ['user' => $user,]);
- 要件に合わないデータが送られてきた際にエラーが出るよう、バリデーションをしっかり挟みましょう。
- ブラウザ以外からのアクセスがあった場合にも対応できるよう、こちらでも`edit()`アクション同様、本人のみデータを更新できる仕組みにしておきましょう。
- パスワードを変更したい場合はどうするのでしょうか？変更したい場合はするし、変更しようとしていない場合はしない、とかでもいいかもですね。

2024-05-06 01:17 UTC, Osk0830 commented on resources/views/users/edit.blade.php
> +        <input type="hidden" name="id" value="" />
- こちらの `input`要素はどこかで使ってますでしょうか？不要であれば削除しましょう。

2024-05-13 15:16 UTC, tosakafullyremote commented
## issue
- Closes #906

## 概要
- ユーザ編集画面・更新

## 動作確認手順
- http://localhost:8080/ へアクセス
メールアドレス：'yusuke@sample.com'
パスワード：'yusuke'
を入力し、ログインボタンを押下
`http://localhost:8080/users/5/edit`

## 考慮してほしいこと
レビューいただいた点につきましては、修正のうえ、検証済みです。
よろしくお願いいたします。

## 確認してほしいこと
特になし

2024-05-14 02:30 UTC, Osk0830 requested changes
お疲れ様でした！
ほぼほぼOKだと思います！

少しだけ修正が必要な箇所がありコメントしましたので、
確認よろしくお願いします！

2024-05-14 02:30 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +        $user->email = $request-> email ;
- `->`と後続するプロパティ名の間は空白を入れずにつけて書きましょう。

2024-05-14 02:30 UTC, Osk0830 commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
- 現状ですと、一度登録したメールアドレスは使えない状態になってしまうと思います。メアドの変更を希望しない場合は元のものを使えるよう、ログイン者自身のメアドと同じであれば重複OKにしてください。

2024-05-14 02:54 UTC, merged

2024-05-14 05:41 UTC, tosakafullyremote commented
## issue
- Closes #906

## 概要
- ユーザ編集画面・更新

## 動作確認手順
- http://localhost:8080/ へアクセス
メールアドレス：'yusuke@sample.com'
パスワード：'yusuke'
を入力し、ログインボタンを押下
`http://localhost:8080/users/5/edit`

## 考慮してほしいこと
特になし

## 確認してほしいこと
一度登録したメールアドレスは使えない状態になってしまってましたが、メアドの変更を希望しない場合は元のものを使えるよう、ログイン者自身のメアドと同じであれば重複OKに修正済み。