Feature/mizuki/user detail
yukihiroLaravel/joint_develop pull request #1092
Opened 2024-05-08 14:04 UTC by mizuki012

## issue
- Closes #907　
## 概要
-ユーザ詳細の実装
1.Routing 設定  
2.Controller 設定  
3.View 設定  

## 動作確認手順
-Dockerコンテナを起動した状態で http://localhost:8080/ にアクセスし、お手本通りに起動するかを確認。

## 考慮して欲しいこと
-特になし。

## 確認して欲しい事
-　ユーザ詳細のタイムラインのところがこれでよいか不安なので、ここを確認していただきたいです。

2024-05-08 21:33 UTC, yukihiroLaravel requested changes
いくつかGitHubで指摘しましたのでご確認願います！

あと、プルリクのConversationの下の方に出ている通り
コンフリクトが発生していますので
コンフリクト解消方法の動画をみながら解消もお願いいたします！

2024-05-08 21:33 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="https://laravel-fly2.fly.dev/users/141" class="nav-link {{ Request::is() ? 'active' : '' }}">タイムライン</a></li>
href="https://laravel-fly2.fly.dev/users/141"
これですと、リンクがお手本の方のアプリに向かっているので
ここにはチーム開発のアプリのリンクを記述しましょう！

2024-05-08 21:33 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                    <img class="rounded-circle img-fluid" src="https://secure.gravatar.com/avatar/b606b891dcd211da9576dc78e5a9bfc8?s=400&r=g&d=identicon" alt="">
src="https://secure.gravatar.com/avatar/b606b891dcd211da9576dc78e5a9bfc8?s=400&r=g&d=identicon"
ここも、
posts.blade.phpを参考に
書き直しましょう！

2024-05-08 21:33 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +    @include('posts.posts', ['user' => $user, 'posts' => $posts])
内部で$userは使っていないと思うので、下記の記述でいいと思います！
@include('posts.posts', ['posts' => $posts])

2024-05-08 21:33 UTC, yukihiroLaravel commented on resources/views/users/users.blade.php
> +                        @else
このファイルは今回は使っていないですよね？
であれば削除したほうがいいと思います！

2024-05-08 21:33 UTC, yukihiroLaravel commented on routes/web.php
> +//Route::get('/', 'UsersController@index');
このコメントアウトの記述は不要かと思うので消しましょう！

2024-05-08 21:33 UTC, yukihiroLaravel commented on app/Http/Controllers/Controller.php
> +    }
Laravel応用の真似でこの記述をされたのだと思いますが
このcountPostsが現状どこにも使われていない
（投稿の数を表示させるような仕様になっていない）
ので、消した方がいいかと思います！

2024-05-08 21:33 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $data += $this->userCounts($user);
Laravel応用の真似でこの記述をされたのだと思いますが
このcountPostsが現状どこにも使われていない
（投稿の数を表示させるような仕様になっていない）
ので、
$data += $this->userCounts($user);
この１行は消した方がいいかと思います！

2024-05-09 06:04 UTC, mizuki012 commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="https://laravel-fly2.fly.dev/users/141" class="nav-link {{ Request::is() ? 'active' : '' }}">タイムライン</a></li>
@yukihiroLaravel 

ご指摘、ありがとうございます。
こちら修正いたしました。

2024-05-09 07:39 UTC, mizuki012 commented on resources/views/users/show.blade.php
> +                    <img class="rounded-circle img-fluid" src="https://secure.gravatar.com/avatar/b606b891dcd211da9576dc78e5a9bfc8?s=400&r=g&d=identicon" alt="">
@yukihiroLaravel 
こちらもご指摘、ありがとうございます。
この箇所につきましても、書き直しました。

2024-05-09 07:40 UTC, mizuki012 commented on resources/views/users/show.blade.php
> +    @include('posts.posts', ['user' => $user, 'posts' => $posts])
@yukihiroLaravel 

こちらにつきましても、修正しました。
ご指摘ありがとうございます。

2024-05-09 07:42 UTC, mizuki012 commented on resources/views/users/users.blade.php
> +                        @else
@yukihiroLaravel 
ご指摘ありがとうございます。
こちらのファイルは削除いたしました。

2024-05-09 07:44 UTC, mizuki012 commented on routes/web.php
> +//Route::get('/', 'UsersController@index');
@yukihiroLaravel 
ご指摘ありがとうございます。
こちらにつきましても、削除いたしました。

2024-05-09 07:46 UTC, mizuki012 commented on app/Http/Controllers/Controller.php
> +    }
@yukihiroLaravel 
ご指摘ありがとうございます。
こちらにつきましても、削除いたしました。

2024-05-09 09:03 UTC, mizuki012 commented on app/Http/Controllers/UsersController.php
> +        $data += $this->userCounts($user);
@yukihiroLaravel 

ご指摘ありがとうございます。
こちらにつきましても、削除いたしました！

2024-05-09 22:17 UTC, yukihiroLaravel requested changes
修正は確認できました！
さらに追加で修正必要な点がありますので、
ご確認お願いします！

動画で撮影しました。
https://www.loom.com/share/7ff7d8f35a4c4418909b522d0d994b74?sid=b2a2a8b3-4a6f-4e30-a700-faae3ffe817d

2024-05-09 22:17 UTC, yukihiroLaravel commented on routes/web.php
> +});
ここは下記のようにインデントをつけるべきですね！
```
Route::prefix('users')->group(function () {
    Route::get('{id}', 'UsersController@show')->name('user.show');
});
```

2024-05-09 22:17 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                            <a href="" class="btn btn-primary btn-block">ユーザ情報の編集</a>
ユーザ編集画面への遷移

2024-05-09 22:17 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +        </div>
この辺りに
@include('posts.posts', ['posts' => $posts])
をおく

2024-05-09 22:17 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +    @include('posts.posts', ['posts' => $posts])
posts.blade.php
に詳細画面へのリンクを追加する

2024-05-09 22:17 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="http://localhost:8080/" class="nav-link {{ Request::is() ? 'active' : '' }}">タイムライン</a></li>
直っていない
```
<li class="nav-item"><a href="{{ route('user.show', ['id' => $user->id]) }}" class="nav-link {{ Request::is('users/' . $user->id) ? 'active' : '' }}">タイムライン</a></li>
```

2024-05-16 02:39 UTC, yukihiroLaravel requested changes
いくつか動作確認漏れかと思われる点が発生しているので
指摘させていただきましたので、ご確認ください！

https://www.loom.com/share/7fa4e58acf93401daba7b6d1bce903cd?sid=f9d5234b-ea5a-415a-921b-33356ffe59bd

2024-05-16 02:39 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                            <a href="{{ route('user.edit', $user->id) }}" class="btn btn-primary btn-block">ユーザ情報の編集</a>
ログインユーザの場合のみボタンを表示させる

2024-05-16 02:39 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +                       <p class="mt-3 mb-0 d-inline-block"><a href="{{ route('user.show', ['id' => $post->user->id]) }}">{{ $post->user->name }}</a></p>
この１行以外は元に戻す

2024-05-18 02:30 UTC, yukihiroLaravel approved these changes
いいですね！

OKですのでマージしました！
おつかれさまでした！

2024-05-18 02:30 UTC, merged