ユーザ退会処理（たわらつみだ　まなぶ）
yukihiroLaravel/joint_develop pull request #1093
Opened 2024-05-09 14:18 UTC by manabuandy

## issue
- なし

## 概要
- ユーザ退会処理（論理削除）の実装

## 動作確認
- localhost:8080
- 新規ユーザ登録の必要有若しくは既存ユーザを使用し削除
- localhost:8088（ユーザ削除情報の確認）

## 考慮して欲しいこと
- UserControllerのユーザ削除
　 public function destroy($id)
    {
    $user = User::findOrFail($id);

    _if (!$user) **{**
    **}**_
    $user->delete();
    return redirect()->route('top'); 
    }

### 以下質疑
   _if (!$user) **{**
    **}**_の{}を外したら動作しませんでした。
ここについて理解できておりません。

## 今後チャレンジしてみたいこと
- 現在、ユーザ退会においてエラーを作成しておりません。
　ユーザ名が違うとかそのユーザは存在しないとかのエラーがあると
実際に操作する人に親切ではなかと思う。

## アドバイスしていただきたいこと
- 今回、実際のローカルweb画面で動作を確認したいため、他の方が作成するタスクを
仮に作成し、動作環境を構築しました。ユーザ退会処理のみ作成する場合は、どのように
作成したらよろしいでしょうか。

2024-05-11 13:04 UTC, manabuandy commented
ユーザ退会処理は、担当タスクのみに修正しました。方法がわからず動作確認ができておりません。
register.blade新規登録画面時のTopic Postsh表示画面を修正しました。
login.bladeの新規登録する？押下後の画面遷移を修正しました。
ご確認をお願いします。

2024-05-12 09:20 UTC, Osk0830 requested changes
お疲れ様でした！
基本的な内容はできていると思います！

修正が必要な箇所いくつかコメントしましたので、
確認よろしくおねがいします！

また、現在、ユーザーはソフトデリート（論理削除）されるようになっているため、
現状では、削除しようとしているユーザーに紐づく投稿データが削除されず、
投稿一覧表示などでエラーが出てしまう状況になっています。
ユーザー削除時に、それに紐づく投稿データも削除されるようにしましょう。

[![Image from Gyazo](https://i.gyazo.com/4697f25824f74fd797ae1b29373a98de.png)](https://gyazo.com/4697f25824f74fd797ae1b29373a98de)

2024-05-12 09:20 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
>      }
- 現状ではここは不要ではないでしょうか？

2024-05-12 09:20 UTC, Osk0830 commented on resources/views/users/edit.blade.php
- こちらのファイルは一旦削除する対象ではないでしょうか？

2024-05-12 09:20 UTC, Osk0830 commented on routes/web.php
> +     Route::delete('{id}/edit', 'UsersController@destroy')->name('users.delete'); //ユーザ削除
- 削除のURLが `users/{id}/edit`となるのはおかしくないでしょうか？
- 40行目はインデントが一つ中に入り必要があると思いますので、調整よろしくお願いします。

2024-05-12 09:20 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +    return redirect()->route('top'); // 一覧画面へのルート名を適宜変更 // 削除したらリダイレクト
- 削除しようとしているユーザーのデータがログイン者自身のデータである場合にのみ削除できる仕組みにしましょう。

2024-05-19 10:12 UTC, closed without merging