#915 Feature/toke/flash message(Tokeshi)
yukihiroLaravel/joint_develop pull request #1094
Opened 2024-05-11 02:36 UTC by tokechan

## issue
- Closes #915 

## 概要
- フラッシュメッセージの実装

## 動作確認手順
- ユーザー編集画面にて
退会機能　toppageに遷移して、赤いスタイリングでフラッシュメッセージが表示
更新機能　遷移せず同じ画面で、緑のスタイリングでフラッシュメッセージが表示

- 投稿一覧画面にて
メッセージ更新　遷移せずに同じ画面で、緑のスタイリングでフラッシュメッセージが表示
メッセージ削除　遷移せずに同じ画面で、赤いスタイリングでフラッシュメッセージが表示

## 考慮して欲しいこと
- 未実装の機能箇所に関してはフラッシュメッセージの設置はしておりません
投稿一覧画面でメッセージを投稿する
ユーザー詳細画面での削除、編集etc

## 確認して欲しい事

-  if構文の書き方がこれで正しいかどうかご教授ください。
もっと、スマートな書き方あるのであれば知りたいです。

```
        @if (session('alertMessage'))
                <div class="alert alert-danger text-center mx-auto w-75 mb-3">
                        {{ session('alertMessage') }}
                </div>
        @elseif (session('info'))
                <div class="alert alert-success text-center mx-auto w-75 mb-3">
                        {{ session('info') }}
                </div>
        @elseif (session('success'))
                <div class="alert alert-danger text-center mx-auto w-75 mb-3">
                        {{ session('success') }}
                </div>        
        @endif

```
-  今回の実装機能はControllerにwithメソッドとflashメソッドのどちらかを使うと良いというのを知りました。
現時点での私の理解はflashメソッドよりはwithメソッドの方がシンプルで実装しやすかったので採用しましたが、どちらを使うのが良かったのか？アドバイスもいただきたいです。
```
    public function update(UserRequest $request, $id)
    {
        $user = User::findOrFail($id);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->save();

        return redirect()->route('user.edit', $user->id)->with('successMessage', 'ユーザー情報を更新しました。');//withメソッドを使用してユーザー編集フラッシュメッセージを記述
    }

    public function destroy($id)
    {
        $user = User::findOrFail($id);
        if(\Auth::id() === $user->id) {
            $user->delete();
        }
        return redirect()->route('posts.index')->with('alertMessage', '退会が完了しました');//withメソッドを使用してユーザー退会フラッシュメッセージを記述
    }
}
```

2024-05-11 04:45 UTC, yukihiroLaravel requested changes
withメソッドでもflashメソッドでも
大差はないのでどちらでも問題ないと思います！

またいくつか指摘させていただきましたので
ご確認お願いします☺️

2024-05-11 04:45 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +        @endif
successとalertMessage
は同じ色を表し、条件分岐させる意味が薄いので
たとえば、
redMessageのような名前で統一すべきかとおもいます！

2024-05-11 04:45 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +                        {{ session('info') }}
infoだと漠然とした名前で他の方からすると使い勝手がわかりにくいため
infoMessageなどとするか
下記のredMessageの対で
greenMessage
などとすべきかと思います！

2024-05-11 13:04 UTC, tokechan commented on resources/views/posts/posts.blade.php
> +        @endif
なるほどです。指摘いただいて、今書いたコードの動きをしっかりと理解しました笑
redMessageとしておけば、表示される色と同じなので他者にもわかりやすいですね。
修正いたします。

2024-05-11 13:10 UTC, tokechan commented on resources/views/posts/posts.blade.php
> +                        {{ session('info') }}
こちらも、先に指摘いただいたコード部分と同じ意味合いですね。
infoというワードと投稿編集後に表示させる「更新が成功しました」というワードが一意のものと間違った認識でした。
info（key）の部分に共通の要素持たせれば表示の色を共通化でき、「更新が成功しました」（value）は表示させたい文言を書けば良いのですね。

2024-05-11 22:55 UTC, yukihiroLaravel requested changes

2024-05-11 22:55 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +                        {{ session('greenMessage') }}
すみません！
追加で一点気付いたのですが、
posts.bladeにフラッシュメッセージを置くと
各投稿のところに１つ１つフラッシュメッセージが表示されるようになり
変にならないでしょうか？

あと、
<!-- 投稿編集後のフラッシュメッセージの実装 -->
<!-- ユーザー退会後のフラッシュメッセージの実装 -->
これらはredMessage・greenMessageなどの名前にしたことから
他の用途で使われる（可能性も）ことも出てきたので
これらのコメントも削除すべきかと思います！

よろしくお願いします！

2024-05-13 02:32 UTC, tokechan commented on resources/views/posts/posts.blade.php
> +                        {{ session('greenMessage') }}
指摘部分、修正完了。

１、posts.bladeからwelcom.bladeへフラッシュメッセージの記述を変更
２、今後の他の用途で使用される可能性を考慮して、コメントを削除

2024-05-13 04:03 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
お疲れ様でした！！

2024-05-13 04:03 UTC, merged