#917 フォロー機能
yukihiroLaravel/joint_develop pull request #1100
Opened 2024-05-16 01:31 UTC by ShintaroYasuda

## issue
- Closes #917 

## 概要
- フォロー機能の実装

## 動作確認手順
- ログインした状態でログインユーザー以外の適当なユーザ詳細画面に行き、フォローボタンの表示を確認して、ボタンを押すと「フォロー」↔︎「フォロー解除」の切り替わるのを確認した。
- ログインユーザーと同一のユーザ詳細画面では、フォローボタンが表示されない事を確認した。

## 考慮してほしい事
- フォローカウント機能に取り掛かっていたので、ControllerとUsersControllerに変更がありますが、次回のタスクで完成させますので、今回はスルーでお願いします。

2024-05-16 02:53 UTC, yukihiroLaravel requested changes
フォローするところのコードなどはほぼ完璧です！

プルリクの最初のコメントに記載されていましたが
ただ、今回のように現段階で
動作確認が取れない（とりにくい）関数の場合は

そのままマージされると危険なコードが含まれる可能性もありますので
お手数ですが、一旦はプルリクにあえて混ぜないようにしましょう！

そのあたり中心にコメントしましたのでご確認ください！

2024-05-16 02:53 UTC, yukihiroLaravel commented on app/Http/Controllers/Controller.php
> +    }
プルリクの最初のコメントに記載されていましたが
今回のように現段階で
動作確認が取れない（とりにくい）関数の場合は

そのままマージされると危険or不要なコードが含まれる可能性もありますので
お手数ですが、一旦はプルリクにあえて混ぜないようにしましょう！

2024-05-16 02:53 UTC, yukihiroLaravel commented on app/Http/Controllers/FollowingController.php
> +        \Auth::user()->unfollow($id);
こちら確認ですが、
フォローしました！はフラッシュメッセージがあるのに
フォロー解除はフラッシュメッセージがないのは理由がありますでしょうか？

2024-05-16 02:53 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +    }
プルリクの最初のコメントに記載されていましたが
今回のように現段階で
動作確認が取れない（とりにくい）関数の場合は

そのままマージされると危険なコードが含まれる可能性もありますので
お手数ですが、一旦はプルリクにあえて混ぜないようにしましょう！

2024-05-16 02:53 UTC, yukihiroLaravel commented on routes/web.php
> +    Route::get('following', 'UsersController@following')->name('following');
プルリクの最初のコメントに記載されていましたが
今回のように現段階で
動作確認が取れない（とりにくい）関数の場合は

そのままマージされると危険なコードが含まれる可能性もありますので
お手数ですが、一旦はプルリクにあえて混ぜないようにしましょう！

2024-05-16 02:53 UTC, yukihiroLaravel commented on routes/web.php
> +// Route::get('/', 'UsersController@index');
この１行のコメントアウトは不要かと思います！

2024-05-17 01:03 UTC, ShintaroYasuda commented on app/Http/Controllers/UsersController.php
> +    }
ありがとうございます。削除いたしました。

2024-05-17 01:04 UTC, ShintaroYasuda commented on app/Http/Controllers/FollowingController.php
> +        \Auth::user()->unfollow($id);
ありがとうございます。フォロー解除にもフラッシュメッセージ追加いたしました。

2024-05-17 01:04 UTC, ShintaroYasuda commented on app/Http/Controllers/Controller.php
> +    }
ありがとうございます。削除いたしました。

2024-05-17 01:04 UTC, ShintaroYasuda commented on routes/web.php
> +    Route::get('following', 'UsersController@following')->name('following');
ありがとうございます。削除いたしました。

2024-05-17 01:04 UTC, ShintaroYasuda commented on routes/web.php
> +// Route::get('/', 'UsersController@index');
ありがとうございます。削除いたしました。

2024-05-17 12:23 UTC, yukihiroLaravel approved these changes
いいですね！
問題ないと思いますのでマージしました！
お疲れ様でした！☺️

2024-05-17 12:23 UTC, merged