#1086 フォロー機能（タイムライン（ユーザ詳細画面） の変更）（たまやま）
yukihiroLaravel/joint_develop pull request #1101
Opened 2024-05-17 02:30 UTC by masashi-tamayama

## issue
- closes  #1086
## 概要
- **フォロー機能時のアドバイスを検討しユーザモデルを修正**
（下記2点を修正）`User.php`
> -  idの使用だけで全て統一するかどうか（今混在している感じだと思います）
↳すべての処理をユーザーIDベースで行うよう統一し、コードの一貫性と効率を向上。
> - if文を分けて書くか一つにまとめるか（returnする結果が同じなので一つにまとめて書くことも結構ある印象です）
↳論理演算子の活用を行い、コードの可読性と簡潔性が向上し、メソッドの動作が明確になるように実装

- ### このタスクにおける目標

1. ”ユーザネーム”をクリックするとユーザ詳細画面に遷移しタイムラインに自分自身の投稿が表示される事
2. ”フォロー中”をクリックすると自分がフォローしているユーザのネームとアバター画像が表示される事
3. ”フォロワー”をクリックすると自分のフォロワーのネームとアバター画像が表示される事
4. タブの下にカウント数が表示されること
5. フォローボタン表示の位置を定位置に固定
![スクリーンショット 2024-05-14 192423](https://github.com/yukihiroLaravel/joint_develop/assets/156323724/4639b51e-84f5-487a-8cef-a2d10dbe847c)
![スクリーンショット 2024-05-16 210438](https://github.com/yukihiroLaravel/joint_develop/assets/156323724/1c5f44cc-96eb-4cbe-950b-a227f938e6d9)
![スクリーンショット 2024-05-17 081708](https://github.com/yukihiroLaravel/joint_develop/assets/156323724/ac34756f-7eae-4a9f-8d59-373a889b176f)

- ###  各タブの投稿表示機能をカウント表示付きで実装
- **MVCの流れで作成[Router⇒Controller⇒View⇒DBファイル⇒View]**
- **Router**
`routes/web.php`
ルーティング記述
- **Controller**
`app/Http/Controllers/UserController.php`
showメソッド修正、`followings`、`followers`メソッド追加
各メソッドにカウント情報取得コード記述
`app/Http/Controllers/Controller.php`
カウント関数記述
- **View**
`resources/views/users/show.blade.php`
`resources/views/follow/followings.blade.php` 🆕
`resources/views/follow/followers.blade.php`  🆕
ルーティングや取得したカウント情報をビューに記述し表示
- **DBファイル**
`database/seeds/UsersTableSeeder.php`
`database/seeds/PostsTableSeeder.php`
`database/seeds/FollowsTableSeeder.php`  🆕
`database/seeds/DatabaseSeeder.php`  🆕
Seeding ファイルの追加、一部変更及びテストデータの作成
- **View**
`resources/views/users/show.blade.php`
`resources/views/follow/followings.blade.php`
`resources/views/follow/followers.blade.php` 
`resources/views/layouts/user_profile.php`  🆕
ビューの共通レイアウトファイルを作成しフォローボタンを定位置に表示
## 動作確認手順

1. `php artisan migraet:fresh --seed`コマンド実行
2. Dockerコンテナを起動した状態で `http://localhost:8088/` にアクセスしログイン実行
3. トップページの投稿一覧から現在ログインしているユーザネームをクリックする
4. タイムラインタブに自分自身のみの投稿表示を確認
5. タブを切り替えアクティブ動作を確認
6. 各タブの直下に投稿数のカウント表示を確認
7. ページネーション機能動作を確認
8. トップページに移動しトップページの投稿一覧から任意のユーザを選択
9. 3から6の手順と同様に確認
10. フォローをするボタンの機能動作及び配置を確認

![スクリーンショット 2024-05-16 211022](https://github.com/yukihiroLaravel/joint_develop/assets/156323724/6133fa18-585b-4e7f-a9ff-729fbad9944c)
![スクリーンショット 2024-05-17 081708](https://github.com/yukihiroLaravel/joint_develop/assets/156323724/8cd69d4e-2300-4349-8136-136d22b7f940)

## 考慮して欲しいこと
- ブランチ名にハイフンを使用してしまい一貫性を損なってしまいました。
`feature/tamayama/follow-based-timeline`
- 変更点が多く講評がやり辛くなってしまった為、このタスクも2個程度に切り分けて提出するべきでした。
- テストデータの件数は今後を見越して多めに作成しております。
## 確認して欲しいこと
- 動作に関してお手本とするものがなく初めての事が多かったので今一度実装した機能、動作がちゃんと出来ているのかの確認をよろしくお願いします。

2024-05-18 06:42 UTC, Osk0830 requested changes
お疲れ様です！
内容的にはよくできていると思います！
もう少しスマートに整理するためなどコメントしましたので、
確認よろしくお願いします！

2024-05-18 06:42 UTC, Osk0830 commented on resources/views/follow/followers.blade.php
> +        </ul>
- この辺は、他の3つのBladeと単純に重複しているので、パーツとして切り出してしまう方がよくないでしょうか？

2024-05-18 06:42 UTC, Osk0830 commented on resources/views/follow/followers.blade.php
> +        </ul>
- ここも、`followings`のブレードとほぼ同じようですね。そうなると変数名だけ工夫して、コントローラーからリターンする時の名前を調整すれば、`followers`と`followings`のブレード自体、一元化できそうではないでしょうか？

2024-05-18 06:42 UTC, Osk0830 commented on resources/views/layouts/user_profile.blade.php
> +<div style="margin-top: 20px;"> <!-- 20ピクセルの上マージンを追加 -->
- せっかくBootstrapを使っているので、マージンの挿入も Bootstrapを使ってもいいかもしれませんね。

2024-05-18 06:42 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +</style>
- できれば、Bladeに `style`タグを挿入せず、スタイルシートの読み込みに変更してみるのがいいかもしれないですね。

2024-05-18 07:37 UTC, masashi-tamayama commented on resources/views/follow/followers.blade.php
> +        </ul>
修正しました。

2024-05-18 07:38 UTC, masashi-tamayama commented on resources/views/follow/followers.blade.php
> +        </ul>
修正しました。かなりすっきりしコードの可読性が向上しました。ありがとうございます。

2024-05-18 07:49 UTC, masashi-tamayama commented on resources/views/layouts/user_profile.blade.php
> +<div style="margin-top: 20px;"> <!-- 20ピクセルの上マージンを追加 -->
Bootstrap　class="mt-3"に差し替えました。

2024-05-18 08:08 UTC, masashi-tamayama commented on resources/views/posts/posts.blade.php
> +</style>
スタイルシートとは、通常、CSSファイルを指すのですね。
public/css/custom.cssを作成し読み込み記述をapp.blade.phpに記述しました。
スタイルの管理が容易になり、コードがクリーンになりました。

2024-05-19 09:42 UTC, Osk0830 approved these changes
お疲れ様でした！
コードがかなりスッキリしましたね！
いい感じに修正できていると思うので、マージしますね！

2024-05-19 09:42 UTC, merged