#1103  いいね機能（とさか）
yukihiroLaravel/joint_develop pull request #1105
Opened 2024-05-17 19:49 UTC by tosakafullyremote

## issue
- Closes #1103

## 概要
- いいね機能

## 動作確認手順
- http://localhost:8080/ へアクセス
メールアドレス：'test1@test.com'
パスワード：'test1'
を入力し、ログインボタンを押下

- 自分の投稿には「いいね！」ボタン非表示
- 他のユーザーの投稿には「いいね！」ボタン表示

## 考慮してほしいこと
- 特になし

## 確認してほしいこと
- いいねボタンを左に配置するために、header.blade.phpを修正、styles.cssを新規作成したが正しいか

## 今後の続きの実装について　案
- いいねがいくつおされたかカウントをいいねボタンの近くに表示したい
- いいねボタンの横の数字のカウントを押すと、どのユーザーがいいねを押したかわかるようにしたい。モーダル、ポップアップみたいな。
- 自分がいいねをした投稿の一覧を見たいので、ユーザー詳細画面のタブの「フォロワー」の右側にいいねを追加したい
- タブにいいねした数を表示したい

2024-05-18 07:46 UTC, Osk0830 requested changes
お疲れ様でした！
概ねよくできていると思います！
修正必要な箇所いくつかコメントしましたので、
確認よろしくお願いします！

2024-05-18 07:46 UTC, Osk0830 commented on app/User.php
> +    }
- 現状だとロジック的に自分の投稿でもいいねできてしまいます。自分の投稿の場合いいねできないロジックにしておきましょう。

[![Image from Gyazo](https://i.gyazo.com/1b1620d6393e5b31ed870718ab9d727b.png)](https://gyazo.com/1b1620d6393e5b31ed870718ab9d727b)

2024-05-18 07:46 UTC, Osk0830 commented on app/User.php
> +    }
- こちらも上記と同じです。

2024-05-18 07:46 UTC, Osk0830 commented on public/css/styles.css
> +}
- これくらいの指定でしたら、せっかくBootstrapを使っているので、それを使って指定するようにするのがスマートかもしれないですね。

2024-05-18 07:46 UTC, Osk0830 commented on resources/views/commons/header.blade.php
> +</head>
- `head`要素は `layouts`の方のブレードにあるので、ここにもう一つ入るのはおかしいです。

2024-05-18 07:46 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                </p>
- 現状、`post`に `title`カラムは存在しないようですが、こちらは何でしょう？

2024-05-18 07:46 UTC, Osk0830 commented on routes/web.php
> +  Route::group(['prefix' => 'posts/{id}'],function(){
- ログイン必須になるようミドルウェアを挟みましょう。
- ここに分けて書くのもいいですが、投稿関連の場所にまとめておくのも良さそうですね。

2024-05-31 09:12 UTC, tosakafullyremote commented
## issue
- Closes #1103

## 概要
- いいね機能

## 動作確認手順
- http://localhost:8080/ へアクセス

## 考慮してほしいこと
- 特になし

## 確認してほしいこと
- 作業ブランチから切ってしまったのですが、下記プルリクエスとはクローズしております。
https://github.com/yukihiroLaravel/joint_develop/pull/1135

問題ない想定ですが、考慮いただけますと幸いです

2024-06-01 01:20 UTC, Osk0830 approved these changes
お疲れ様でした！
こちら if文を整理するなどもう少し整理できそうな部分ありそうですが、
基本的にはOKそうですのでマージしますね！

自分がいいねしている投稿一覧や誰かにいいねされている投稿一覧なんかも見れるようにすると良さそうですね。

2024-06-01 01:20 UTC, merged