ユーザ退会（たわらつみだ　まなぶ）
yukihiroLaravel/joint_develop pull request #1110
Opened 2024-05-19 10:54 UTC by manabuandy

## issue
- ユーザ退会 #902 ユーザ退会処理

## 概要
- ユーザ退会処理（論理削除）の実装
- 同時に退会ユーザの投稿内容削除の実装
-  **追記**　ログインユーザと退会するユーザ等が一致した場合のみ処理を実行する内容に修正

## 動作確認
- localhost:8080
- 新規ユーザ登録の必要有若しくは既存ユーザを使用し削除
- **追記**　ログインユーザと異なるユーザ名ユーザe-mail入力後に退会実行
-  localhost:8088（退会ユーザ情報の確認）

## 確認したいところ（あまり意味がわかってないところ）
UsersController
`//ユーザ削除
       protected function destroy($id)
       {
       // 指定されたIDのユーザーを取得
       $user = User::findOrFail($id);
       
       // 指定されたユーザかどうかを確認
       if (\Auth::check() && \Auth::id() == $id) {
       return redirect()->route('top'); // 一覧画面へのルート名を適宜変更 // 削除したらリダイレクト
       }
       $user->delete();// ユーザーを削除
       return redirect()->route('top'); // 一覧画面へのルート名を適宜変更 // 削除したらリダイレクト`
があります。
usersディレクトリ内のedit.blade
`  
@if (Auth::id() === $user->id) ユーザ名とメールアドレスがログインユーザ名と一致しないため退会できません。
    <div class="modal-footer d-flex justify-content-between">
    <form action="{{ route('users.delete', $user->id) }}" method="POST">
   @csrf
   @method('DELETE')
    <button type="submit" class="btn btn-danger">退会する</button>
    </form>
    @endif
`
`(Auth::id() === $user->id) `は
//中略
コントローラーとエディットにそれぞれ記載してうまく動作しました。
 ** 質疑
両方に記載する必要があったのでしょうか。動作がよくわかりません。
行ってないことは
片方を削除した場合の動作確認は行っておりません**。

## アドバイスいただきたいところ
- ユーザ名とe-mailアドレスが異なった場合にエラーを出したい

- ユーザ名とメールアドレスがログインユーザ名と一致しないため退会できませんと出た場合に退会ボタンが押せないようにしたい

- 条件で一致しな場合はいきなり
[ユーザ名とメールアドレスがログインユーザ名と一致しないため退会できません]
[もう一度入力を見直してください] [戻る]
-と表示させたい

- ユーザ詳細画面においてパスワードを入力した場合に退会画面が出ないようにしたい
（今回担当タスク外）

2024-05-21 02:45 UTC, Osk0830 requested changes
お疲れ様でした！
いい感じにできていると思います！
ほとんどOKですが、いくつか修正が必要な箇所がありコメントしましたので、
確認よろしくお願いします！

2024-05-21 02:45 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +       return redirect()->route('top'); // 一覧画面へのルート名を適宜変更 // 削除したらリダイレクト
- 削除しようとしているユーザーデータがログイン者自身のものと一致する場合にのみ削除できるようなロジックを挟みましょう。

2024-05-21 02:45 UTC, Osk0830 commented on app/User.php
> +        });
- チームブランチをマージしたらリレーションメソッドが `posts()`と複数形になっていないでしょうか？玉山さんがそのように修正されたと思います。

2024-05-22 11:19 UTC, manabuandy commented
お疲れ様です。
内容を修正しました。
「チームブランチをマージしたらリレーションメソッドが posts()と複数形になっていないでしょうか？玉山さんがそのように修正されたと思います。」
こちらは修正するの忘れてました。次回修正いたします。

2024-05-25 14:16 UTC, manabuandy commented
contorollerのクラス定義変更しました。
リレーションメソッドの件修正しました。
よろしくお願いします。

2024-05-26 10:21 UTC, manabuandy commented
ユーザ編集画面の表示崩れを修正いたしました。
ご確認をお願いします。

2024-05-27 01:38 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKそうなのでマージしますね！

2024-05-27 01:38 UTC, merged