コメント機能(えんどう）
yukihiroLaravel/joint_develop pull request #1118
Opened 2024-05-24 19:46 UTC by deuro-ki

# issue
- #1116 

# 概要
- 追加機能　コメント機能

# 動作確認手順
- コメント保存
いいねアイコン・badge下のコメントフォームからコメントを保存 (store同期通信）
保存時に空と500文字制限のバリデーションを実装（それぞれの条件でバリデーションが掛かることを確認）
ログインしているユーザーの投稿にはコメントフォームが表示されない事を確認
投稿に対するコメントがユーザー詳細ページでも確認できることを確認

- コメント編集・削除はAjax(edit、destroy非同期通信）で実装
コメント編集時にも空と500文字制限のバリデーションを実装（それぞれの条件でバリデーションが掛かることを確認）
コメント編集完了時にリロードなく、動的に編集が完了することを確認
コメント削除時にリロードすることがなく、動的に削除が完了することを確認
ログインユーザーの投稿に対するコメントをログインユーザーが変更出来ない事を確認
コメント登録時、編集、削除時にバリデーションが表示されることを確認
登録時はコントローラーへ、編集、削除時はjavascriptで実装（３秒間表示した後、消える）

# その他伝達事項
- jsで実装したフラッシュメッセージををhtml表示させる場合、もう少しスマートな書き方があれば知りたいです。
(comment_list.blade.phpの先頭付近のコード)
- まだまだ基礎を学習中の身でアブノーマルな実装に走ってしまいましたが、自分自身にとってはとても良い学びになりました。一通りコードをご確認頂ければと思います。

2024-05-25 02:35 UTC, yukihiroLaravel requested changes
細部までこだわられていて
素晴らしい出来だと思います！

いくつか細かい点をお話ししましたのでご確認ください！

https://www.loom.com/share/263afb0972be411d9e352dc93eb6e6ee?sid=64ab334f-77b0-4d48-94f6-91b1150d0c70

2024-05-25 02:35 UTC, yukihiroLaravel commented on app/Http/Requests/CommentRequest.php
> +            'comment' => 'required|max:500'
投稿との上限文字数のバランス

2024-05-25 02:35 UTC, yukihiroLaravel commented on resources/views/comments/comment_list.blade.php
> +                    {{ $comment->comment }}
長文の時に突き抜ける問題

2024-05-25 02:35 UTC, yukihiroLaravel commented on resources/views/comments/comment.blade.php
> +                    <textarea class="form-control w-100" name="comment" placeholder="コメントを入力..." rows="10">{{ old('comment') }}</textarea>
rows="10"
だと、投稿欄に比べて縦が高すぎる印象

2024-05-25 02:35 UTC, yukihiroLaravel commented on resources/views/comments/comment_list.blade.php
> +            }, 3000);
関数に切り出せばスマートにできます

2024-05-25 02:35 UTC, yukihiroLaravel commented on resources/views/comments/comment_list.blade.php
> +            }, 3000);
関数に切り出せばスマートにできます

2024-05-25 02:35 UTC, yukihiroLaravel commented on resources/views/comments/comment_list.blade.php
> +                    showFlashMessage('コメントは500文字以内で入力してください。');
上限文字数

2024-05-25 02:35 UTC, yukihiroLaravel commented on app/Http/Controllers/CommentsController.php
> +        $comment = Comment::findOrFail($comment_id);
$commentId
などキャメルケースに統一

2024-05-25 02:35 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::delete('{comment_id}', 'CommentsController@destroy')->name('comment.destroy');
{commentId}
などキャメルケースに統一

2024-05-25 02:35 UTC, yukihiroLaravel commented on app/Http/Controllers/CommentsController.php
> +        }
微妙な書き方の違いですが、こちらの方が少し読みやすいかと思います
```
if ($comment) {
            $comment->delete();
            return response()->json(['success' => true, 'message' => 'Comment deleted']);
}
return response()->json(['success' => false, 'message' => 'Comment not found'], 404);
```

2024-05-25 02:35 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        }
意味をなしていない？

2024-05-25 02:35 UTC, yukihiroLaravel commented on app/Comment.php
> +    }
使われてない？

2024-05-25 02:35 UTC, yukihiroLaravel commented on resources/views/comments/comment_list.blade.php
> +                        // エラーハンドリング
エラーなし？

2024-05-28 03:14 UTC, deuro-ki commented on app/Http/Requests/CommentRequest.php
> +            'comment' => 'required|max:500'
確かにバランス悪いですね....。　自分は長いコメントをする人も居ると思ったので、一旦敢えて長めにしてみました。投稿と同じmax140文字に揃えます。

2024-05-28 03:35 UTC, deuro-ki commented on resources/views/comments/comment.blade.php
> +                    <textarea class="form-control w-100" name="comment" placeholder="コメントを入力..." rows="10">{{ old('comment') }}</textarea>
バランス悪いので、投稿に合わせrows=4に変更致します。

2024-05-29 06:50 UTC, deuro-ki commented on resources/views/comments/comment_list.blade.php
> +                    {{ $comment->comment }}
ご指摘ありがとうございます！コメント登録試行錯誤中に設定しておりましたが、コードを元に戻した後に再追加するのを忘れてしまいました。

2024-05-29 06:52 UTC, deuro-ki commented on resources/views/comments/comment.blade.php
> +                    <textarea class="form-control w-100" name="comment" placeholder="コメントを入力..." rows="10">{{ old('comment') }}</textarea>
確かにバランス悪いですね....。　自分は長いコメントをする人も居ると思ったので、一旦敢えて長めにしてみました。しかしビュー見た目を考えるとおかしいので、今回は投稿と同じmax140文字に合う高さrows=4に設定致します。

2024-05-29 06:53 UTC, deuro-ki commented on routes/web.php
> +        Route::delete('{comment_id}', 'CommentsController@destroy')->name('comment.destroy');
なるほど！助言の書き方の方がより分かりやすいですね！
修正致します。

2024-05-29 07:23 UTC, deuro-ki commented on app/Http/Controllers/CommentsController.php
> +        }
助言ありがとうございます！
elseの記述よりもコードがより分かりやすいですね。
修正致します。

2024-05-30 04:14 UTC, deuro-ki commented on app/Http/Controllers/PostsController.php
> +        }
自分の勘違いで、$post->commnetsをビューで表示させる前に、コントローラーで定義が必要だと思っておりました。しかし、消すとコメントが最新順で表示されなくなってしまうので、
$posts = Post::with(['comments' => function ($query) {
      $query->orderBy('created_at', 'desc');
 }])->orderBy('id', 'desc')->paginate(10);
というように$postsの定義を変更致しました。

2024-05-30 04:17 UTC, deuro-ki commented on app/Comment.php
> +    }
コメントに紐づいた投稿は表示予定がないので、上記コードを削除します。
リレーション定義でも使わないメソッド側は記述していなくても良いという事は今回勉強になりました！

2024-05-30 12:58 UTC, deuro-ki commented on resources/views/comments/comment_list.blade.php
> +                        // エラーハンドリング
コメント削除と同様でconsole.error('Failed to edit comment:', data.message);を記入致しました。

2024-05-31 07:33 UTC, deuro-ki commented on resources/views/comments/comment_list.blade.php
> +            }, 3000);
出来る限り一つにまとめてみました！

2024-05-31 07:33 UTC, deuro-ki commented on resources/views/comments/comment_list.blade.php
> +            }, 3000);
出来る限り一つにまとめてみました！

2024-05-31 10:11 UTC, yukihiroLaravel approved these changes
修正について、完璧ですのでマージしました！
おつかれさまでした☺️

2024-05-31 10:11 UTC, merged