#1121 Feature/toke/comment function(Tokeshi)
yukihiroLaravel/joint_develop pull request #1122
Opened 2024-05-25 15:46 UTC by tokechan

2024-06-02 06:58 UTC, tokechan commented
## issue
-  Closes #1121  

## 概要
- コメント機能実装
- 投稿機能
- 投稿編集機能
- 投稿削除
- フラッシュメッセージ

## 動作確認手順

1. ログインできるユーザーのみコメント可能です
2. ログインor 新規登録をお願いします
3. 投稿されているポストにコメントをクリックする
4. コメント画面に遷移するので、コメントを投稿する
5. 遷移先で編集ボタンと削除ボタンが表示されます
6. 5のそれぞれのボタンをクリックするとアクションが実行されます
7. 各アクションにそれぞれフラッシュメッセージが表示されます

## 考慮して欲しいこと
コメント機能を細分化せずに機能を実装してしまったので変したコードが多く分かりづらくなっています
すませんでした。以後は細分化していこうと思います

## 確認して欲しい事

全体のコード修正がないかの確認
こうすると良いというようなものがあればご指導お願いします

2024-06-03 01:44 UTC, yukihiroLaravel requested changes
多機能でめちゃくちゃすばらしいですね☺️

いくつかコメントしました！

https://www.loom.com/share/11d1970b1961489bac63531ba4704fce?sid=67720c34-c453-4e0f-bc21-f477220ce1b3

2024-06-03 01:44 UTC, yukihiroLaravel commented on app/Http/Controllers/CommentsController.php
> +        return view('comments.index', compact('comments', 'post'));
配列の形で変数渡すようにする。
（他の部分も同様）

2024-06-03 01:44 UTC, yukihiroLaravel commented on app/Http/Controllers/CommentsController.php
> +        ]);
コメントにあるように
CommentRequestファイルがあるのでそれ使ってバリデーション を記述するのがスマート

2024-06-03 01:44 UTC, yukihiroLaravel commented on app/Http/Controllers/CommentsController.php
> +    }
使用していないメソッドは原則消す

2024-06-03 01:44 UTC, yukihiroLaravel commented on resources/views/comments/create.blade.php
> +    <a href="{{ route('comments.edit', $comment) }}" class="btn btn-primary">編集</a>
ここで
$comment
というオブジェクトを渡していますが
URLにオブジェクトを渡すケースはあまりないので
$comment->idなどを渡した方がいいかと思います！

2024-06-03 01:44 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::get('{comment}/edit', 'CommentsController@edit')->name('comments.edit');
ここで
$comment
というオブジェクトを渡していますが
URLにオブジェクトを渡すケースはあまりないので
{id}などを渡した方がいいかと思います！

2024-06-03 01:44 UTC, yukihiroLaravel commented on resources/views/comments/edit.blade.php
> +    <form action="{{ route('comments.update', $comment) }}" method="POST">
ここで
$comment
というオブジェクトを渡していますが
URLにオブジェクトを渡すケースはあまりないので
$comment->idなどを渡した方がいいかと思います！

2024-06-03 01:44 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::patch('{comment}', 'CommentsController@update')->name('comments.update');
ここで
$comment
というオブジェクトを渡していますが
URLにオブジェクトを渡すケースはあまりないので
{id}などを渡した方がいいかと思います！

2024-06-03 01:44 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::delete('{comment}', 'CommentsController@destroy')->name('comments.delete');
ここで
$comment
というオブジェクトを渡していますが
URLにオブジェクトを渡すケースはあまりないので
{id}などを渡した方がいいかと思います！

2024-06-03 01:44 UTC, yukihiroLaravel commented on resources/views/comments/create.blade.php
> +                    <form action="{{ route('comments.delete', $comment) }}" method="POST">
ここで
$comment
というオブジェクトを渡していますが
URLにオブジェクトを渡すケースはあまりないので
$comment->idなどを渡した方がいいかと思います！

2024-06-03 01:44 UTC, yukihiroLaravel commented on app/Http/Controllers/CommentsController.php
> +    public function create(Post $post)
ここで
$post
というオブジェクトを渡していますが
URLにオブジェクトを渡すケースはあまりないので
$idなどを渡した方がいいかと思います！

2024-06-03 01:44 UTC, yukihiroLaravel commented on app/Http/Controllers/CommentsController.php
> +    public function edit(Comment $comment)
ここで
$comment
というオブジェクトを渡していますが
URLにオブジェクトを渡すケースはあまりないので
$idなどを渡した方がいいかと思います！

2024-06-03 01:44 UTC, yukihiroLaravel commented on app/Http/Controllers/CommentsController.php
> +    public function update(Request $request, Comment $comment)
ここで
$comment
というオブジェクトを渡していますが
URLにオブジェクトを渡すケースはあまりないので
$idなどを渡した方がいいかと思います！

2024-06-03 01:44 UTC, yukihiroLaravel commented on app/Http/Controllers/CommentsController.php
> +    public function destroy(Request $request, Comment $comment)
ここで
$comment
というオブジェクトを渡していますが
URLにオブジェクトを渡すケースはあまりないので
$idなどを渡した方がいいかと思います！

2024-06-03 01:44 UTC, yukihiroLaravel commented on app/Http/Controllers/CommentsController.php
> +        // dd($comment->user_id !== auth()->id());
コメントアウト削除

2024-06-03 01:44 UTC, yukihiroLaravel commented on routes/web.php
> +    Route::get('/posts/{post}/coments', 'CommentsController@index')->name('comment.index');
ここで
$post
というオブジェクトを渡していますが
URLにオブジェクトを渡すケースはあまりないので
{id}などを渡した方がいいかと思います！

2024-06-03 01:44 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::get('create/{post}', 'CommentsController@create')->name('comments.create');
ここもpostではなく
{id}などを渡した方がいいかと思います！

2024-06-03 01:44 UTC, yukihiroLaravel commented on app/Http/Controllers/CommentsController.php
> +        ]);
CommentRequestファイルがあるのでそれ使ってバリデーション を記述するのがスマート

2024-06-03 01:44 UTC, yukihiroLaravel commented on database/migrations/2024_05_23_140406_create_comments_table.php
> +            $table->unsignedBigInteger('post_id')->index();
同じ意味のはずなので、どちらでもOKです。
たしかに、完結であれば下の方がいいかもしれません！
どちらかに統一しましょう！

2024-06-03 01:44 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +            </div>
このボタンは「コメント」という名前にすべき？

2024-06-03 01:44 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::get('create/{post}', 'CommentsController@create')->name('comments.create');
このルーティングはログインしていなくてもアクセスできるようにすべき？

2024-06-03 01:44 UTC, yukihiroLaravel commented on resources/views/comments/create.blade.php
> +        <input type="hidden" name="post_id" value="{{ $post->id }}">
この辺はログインしていなければ非表示にする

2024-06-05 13:30 UTC, yukihiroLaravel approved these changes
OKです！
問題ないと思いますのでマージしました！

難しいタスクでしたが、大変おつかれさまでした☺️！！

2024-06-05 13:30 UTC, merged