投稿詳細画面実装（たわらつみだ　まなぶ）
yukihiroLaravel/joint_develop pull request #1124
Opened 2024-05-27 23:37 UTC by manabuandy

##　issue
- なし

## 概要
- 投稿詳細
（投稿内容と作成時間がでるように設定しております。戻るボタンで直前の画面へ遷移するように設定しております）

## 動作確認
- localhost:8080
- トップページからの投稿詳細ボタン押下後の確認
- ログインした状態でユーザ詳細画面遷移後で投稿詳細確認

## アドバイスをいただきたいところ
- 投稿詳細画面のところにユーザ情報を表示したかったが現時点表示できておりません。
- ボタン配置を自由に変更したいがコードが理解できていない。

2024-05-31 14:26 UTC, manabuandy commented
再度プルリクエスト行います。ご確認よろしくお願いします。

2024-06-01 09:33 UTC, Osk0830 requested changes
お疲れ様でした！
ほとんど問題なくできていますね！
1箇所だけ修正が必要な箇所がありますので、
確認よろしくお願いします！

2024-06-01 09:33 UTC, Osk0830 commented on resources/views/posts/show.blade.php
> +<a href="#" class="btn btn-secondary" onclick='window.history.back(-1);'><戻る</a><!-- ユーザ詳細画面に戻る -->
- `href`をアンカーリンク `#`にしたままJavaScriptでページ遷移させてますが、もしJSを用いるのであれば、アンカーリンクは不要ですね。一長一短ありますが、ここはLaravelのルーティングで十分指定可能な箇所でもありますので、今回はその方法に変えるのがいいと思います。なお、現状ですと、戻るボタンをクリックした際に一瞬URL末尾に `#`がついてしまいますが、それもよくないです。

https://gyazo.com/d637bad2ba91d03872ffe47aa4f360cb

2024-06-01 10:56 UTC, manabuandy commented
・戻るボタンをクリックした際に一瞬URL末尾に #がついていることが確認できました。
・HTML形式（アンカーリンクタグ）を使用して、画面遷移とトップページいくよう変更しました。
もし
**「アンカーリンクタグを利用しないでトップページへ遷移」**
するようにご指摘いただいているのであれば再度ご連絡いただけると助かります。
よろしくお願いします。

2024-06-02 02:01 UTC, manabuandy commented
・HTML要素（アンカーリンクタグ）を使用して、画面遷移とトップページいくよう変更しました。
・投稿詳細ボタン配置を変更しました。
ご確認をお願いします。

2024-06-02 09:02 UTC, Osk0830 approved these changes
お疲れ様でした！
トップへの遷移にされたんですね。
こちらOKそうなのでマージしますね！

2024-06-02 09:02 UTC, merged