#1086 フォローによるタイムライン変更（ユーザ詳細）
yukihiroLaravel/joint_develop pull request #1132
Opened 2024-05-30 00:55 UTC by ShintaroYasuda

## issue
- Closes #1086 

## 概要
- ユーザ詳細画面でのフォロー、フォロワータブにおけるタイムライン変更機能の実装

## 動作確認手順
- ユーザ詳細画面でフォロー、フォロワーそれぞれのタブをクリックしてそのユーザーがフォローしたユーザー一覧、そのユーザーをフォローしているユーザーの一覧がそれぞれ表示されるのを確認
- フォロー、フォロワータブにそれぞれフォロー人数、フォロワー人数のカウントされたバッジ表記を確認
- ログインした状態で、リアルタイムであるユーザーをフォローしてフォローのカウント数とユーザ一覧の変化を確認
- フォロー先のユーザーでログインして、フォロワータブの変化も確認

## 確認してほしい事
- show blade ファイルの60〜63行目のコードが if 文の外にあり、不要と思うので、削除してもよいでしょうか？

2024-05-30 02:34 UTC, yukihiroLaravel requested changes
いいですね！
苦労された分、ほぼ完璧ですが
細かい点指摘させていただきました！

ご確認お願いします！

https://www.loom.com/share/dc203672178f4e8ebd258550f0777d7a

2024-05-30 02:34 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +        <!-- </div> -->
消してはダメでelseの中に入れるべき

2024-05-30 02:34 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +            </ul>
ここにもページネーション 必要

2024-05-30 02:34 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +            </ul>
ここにもページネーション 必要

2024-05-30 02:34 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
>              <li class="nav-item"><a href="{{ route('user.show', $user->id) }}" class=" nav-link {{ Request::is('users/'. $user->id) ? 'active' : '' }}">タイムライン</a></li>
タイムライン選択したときの縦線がない

2024-05-31 00:49 UTC, ShintaroYasuda commented on resources/views/users/show.blade.php
> +        <!-- </div> -->
ご指摘ありがとうございます。
修正しました。

2024-05-31 00:49 UTC, ShintaroYasuda commented on resources/views/users/show.blade.php
> +            </ul>
ご指摘ありがとうございます。
修正しました。

2024-05-31 00:49 UTC, ShintaroYasuda commented on resources/views/users/show.blade.php
> +            </ul>
ご指摘ありがとうございます。
修正しました。

2024-05-31 00:49 UTC, ShintaroYasuda commented on resources/views/users/show.blade.php
>              <li class="nav-item"><a href="{{ route('user.show', $user->id) }}" class=" nav-link {{ Request::is('users/'. $user->id) ? 'active' : '' }}">タイムライン</a></li>
ご指摘ありがとうございます。
修正しました。

2024-05-31 04:21 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！

大変だったと思いますがお疲れ様でした☺️

2024-05-31 04:21 UTC, merged