#94 ユーザテーブルのマイグレーションとシーダー作成(松本)
yukihiroLaravel/joint_develop pull request #1147
Opened 2024-06-11 09:07 UTC by kazu-777

## issue
-Closes #94

## 概要
・ユーザテーブルのマイグレーションとシーダー作成

## 動作確認
・下記コマンドを実行。
php artisan migrate
Adminerでusersテーブルに4個のレコードが保存されていることを確認

2024-06-11 10:01 UTC, yukihiroLaravel requested changes
ほぼ完璧なのですが細かい点のみ指摘させていただきました！
プルリクの最初の文章の

-Closes ~

だとマークダウンが反応しないので

- Closes ~

とCの前にスペースを１つ入れればいいと思いました！
（入力済みの内容も編集（edit）から変更できると思います！）

2024-06-11 10:01 UTC, yukihiroLaravel commented on database/seeds/UsersTableSeeder.php
> +
細かいですが、
ここの空行は不必要かと思います！
不必要な空行はできるだけなくしていきましょう！

2024-06-12 08:31 UTC, kazu-777 commented on database/seeds/UsersTableSeeder.php
> +
変更しました！
宜しくお願いいたします。

2024-06-12 15:41 UTC, yukihiroLaravel approved these changes
マージしました！
おつかれさまでした！！

2024-06-12 15:41 UTC, merged