#94 users（ユーザ）テーブルのマイグレーションとシーダー作成(G2/辻)
yukihiroLaravel/joint_develop pull request #1148
Opened 2024-06-12 13:16 UTC by maxmindl

## issue

- Closes #94 

## 概要

ユーザテーブルのマイグレーションとシーダ作成

## 動作確認

・下記コマンドを実行。
php artisan migrate
(お願い)Adminerでusersテーブルに4個のレコードが保存されていることを確認

## 確認してほしいこと
シーダーの下記の箇所についてスマートな書き方があれば教えて欲しいです。

        DB::table('users')->insert([
            'name' => 'test1',
            'email' => 'test1@test.com',
            'password' => bcrypt('test1')
        ]);
        DB::table('users')->insert([
            'name' => 'test2',
            'email' => 'test2@test.com',
            'password' => bcrypt('test2')
        ]);
        DB::table('users')->insert([
            'name' => 'test3',
            'email' => 'test3@sample.com',
            'password' => bcrypt('test3')
        ]);
        DB::table('users')->insert([
            'name' => 'test4',
            'email' => 'test4@test.com',
            'password' => bcrypt('test4')
        ]);

code

2024-06-12 15:39 UTC, yukihiroLaravel requested changes
いい感じですので
このままマージしてもいいのですが
より綺麗な書き方も記述しましたので
書き直したい場合は、書き直してご連絡ください！

2024-06-12 15:39 UTC, yukihiroLaravel commented on database/seeds/UsersTableSeeder.php
> +        ]);
>シーダーの下記の箇所についてスマートな書き方があれば教えて欲しいです。

今の形でもOKですが、
1番綺麗なのは下記のような書き方ですね！

```
for ($i = 1; $i <= 4; $i++) {
    DB::table('users')->insert([
            'name' => 'test'. $i,
            'email' => 'test'. $i. '@test.com',
            'password' => bcrypt('test'. $i)
    ]);
}
```

2024-06-12 19:59 UTC, maxmindl commented on database/seeds/UsersTableSeeder.php
> +        ]);
確認しました。
わかりやすく記述いただきありがとうございます。

2024-06-12 22:59 UTC, maxmindl commented on database/seeds/UsersTableSeeder.php
> +        ]);
書き直しを実行しました。
確認をお願いします。

2024-06-12 23:11 UTC, yukihiroLaravel requested changes
細かいですが
少しインデント（行開始位置）がおかしかったので記述させて頂きました！
ご確認ください！

2024-06-12 23:11 UTC, yukihiroLaravel commented on database/seeds/UsersTableSeeder.php
> +                    'password' => bcrypt('test'. $i)
僕のお手本的に分かりづらかったかもしれませんが、
インデントが右から始まりすぎていて
おかしいので書き直しましょう！

16-18行目は
DB::のDの位置から数えて
スペース4つ分右から開始するのが正しいです！

2024-06-13 13:39 UTC, maxmindl commented on database/seeds/UsersTableSeeder.php
> +                    'password' => bcrypt('test'. $i)
16-18行目の訂正分を行いました。
ご確認願います。

2024-06-13 22:24 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
お疲れ様でした😃

2024-06-13 22:24 UTC, merged

2024-06-14 12:58 UTC, maxmindl commented
ゆきひろさん

mergeを確認しました。
ありがとうございました。