ヘッダー・フッター & トップページのタイトル表示
yukihiroLaravel/joint_develop pull request #1150
Opened 2024-06-14 13:00 UTC by mizuki012

概要
・共通ファイル・ヘッダー・フッター & トップページのタイトル表示「Topic Posts」の作成

動作確認手順
・routes(web.php)編集
・Controller作成
・View作成

確認していただきたいこと
・タイトルの「Topic Posts」の横の飛行機マークはつけなくてもよろしいでしょうか？
・ヘッダーの右上の箇所に、「[ログインユーザ名][ログアウト][ログイン][新規ユーザ登録]」と表示されたままですが、現時点ではこのままでよろしいでしょうか？

2024-06-14 13:33 UTC, yukihiroLaravel requested changes
修正お願いします！

2024-06-14 13:33 UTC, yukihiroLaravel commented on resources/views/layouts/app.blade.php
> +        <title>YouTubeまとめ×コミュニケーション</title>
トップページのモックアップ

2024-06-14 13:33 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('/', 'UsersController@index');
UsersControllerではなく
PostsController

2024-06-14 13:33 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +class UsersController extends Controller
ファイル名・クラス名ともに
UsersControllerではなく
PostsController

2024-06-14 13:45 UTC, mizuki012 commented on resources/views/layouts/app.blade.php
> +        <title>YouTubeまとめ×コミュニケーション</title>
修正しました！

2024-06-14 13:45 UTC, mizuki012 commented on routes/web.php
> +Route::get('/', 'UsersController@index');
修正しました！

2024-06-14 13:45 UTC, mizuki012 commented on app/Http/Controllers/UsersController.php
> +class UsersController extends Controller
修正しました！

2024-06-17 04:01 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！☺️
お疲れ様でした！

あと、欲を言えば
ここまで一緒に考えてきたので、
どこが間違っていてどう解決したのか？
簡単にでもいいので共有いただいた方がいいと思いました💦

今後でいいのでよろしくお願いします！

2024-06-17 04:02 UTC, merged