#95 posts（投稿）テーブルのマイグレーションとシーダー作成（鍵野）
yukihiroLaravel/joint_develop pull request #1151
Opened 2024-06-15 17:41 UTC by kimonoremark

## issue
- Closes #95

## 概要

- posts（投稿）テーブルのマイグレーションとシーダー作成

## 動作確認手順
- 下記コマンドを実行
php artisan migrate --seed
- Adminerでpostsテーブルに5個のレコードが保存されていることを確認

## 考慮して欲しいこと
- 状況に応じて、下記コマンドで動作確認する必要あり。
php artisan migrate:fresh --seed
- usersテーブルのidカラムに2～４が登録されている状態で確認

2024-06-15 22:46 UTC, yukihiroLaravel requested changes
わかりやすいよう動画で撮影しました！https://www.loom.com/share/1fc75a51bf574e14b34b7741e1257b42?sid=08d1ea9f-77a4-4263-9762-69ccfab2ef77

2024-06-15 22:46 UTC, yukihiroLaravel commented on database/migrations/2024_06_14_235613_create_posts_table.php
> +            //$table->bigInteger('user_id')->unsigned()->index();
コメントアウトを外す

2024-06-15 22:46 UTC, yukihiroLaravel commented on database/migrations/2024_06_14_235613_create_posts_table.php
> +            //$table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
コメントアウトを外す

2024-06-15 22:46 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +
空行不要

2024-06-15 22:46 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +
空行不要

2024-06-15 22:46 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +        ]);
１１個投稿ができるようにしましょう

2024-06-16 15:18 UTC, kimonoremark commented on database/migrations/2024_06_14_235613_create_posts_table.php
> +            //$table->bigInteger('user_id')->unsigned()->index();
コメントアウト外しました

2024-06-16 15:18 UTC, kimonoremark commented on database/migrations/2024_06_14_235613_create_posts_table.php
> +            //$table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
コメントアウト外しました

2024-06-16 15:18 UTC, kimonoremark commented on database/seeds/PostsTableSeeder.php
> +
空行削除しました

2024-06-16 15:18 UTC, kimonoremark commented on database/seeds/PostsTableSeeder.php
> +
空行削除しました

2024-06-16 15:18 UTC, kimonoremark commented on database/seeds/PostsTableSeeder.php
> +        ]);
11個分作成しました

2024-06-17 02:37 UTC, yukihiroLaravel requested changes
シーダーの修正などはOKですが、
空行削除について認識間違い？で消えていないところがあったようです！

ご確認お願いします！

2024-06-17 02:37 UTC, yukihiroLaravel commented on database/migrations/2024_06_14_235613_create_posts_table.php
> +
こちらも２４行目は空行不要ですね！

2024-06-17 02:37 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +
下記の空行が１０個ほどあると思いますが
消えていないですね！
下記を消して欲しいという意味でした！

```
DB::table('posts')->insert([
  ~~
]);
(←ここの空行削除)
DB::table('posts')->insert([
  ~~
]);
```

2024-06-17 13:02 UTC, kimonoremark commented on database/migrations/2024_06_14_235613_create_posts_table.php
> +
不要行削除しました

2024-06-17 13:04 UTC, kimonoremark commented on database/seeds/PostsTableSeeder.php
> +
空行削除しました

2024-06-17 13:24 UTC, yukihiroLaravel approved these changes
OKですので、マージしました！
おつかれさまでした☺️

2024-06-17 13:24 UTC, merged