#107 ユーザー新規登録(G2/辻)
yukihiroLaravel/joint_develop pull request #1152
Opened 2024-06-16 23:20 UTC by maxmindl

## issue
- Clouses #107 

## 概要
-ユーザー新規登録

## localhost 8080: 上でsignup/をURLにつけ、

・名前
・メールアドレス

2024-06-17 02:31 UTC, yukihiroLaravel requested changes
今の動作確認しにくい状況でよく対応されたと思います！

ほぼOKですが、
少しだけコメントしましたのでご確認ください☺️

2024-06-17 02:31 UTC, yukihiroLaravel commented on routes/web.php
> +
１行空行不要ですので削除しましょう！

2024-06-17 02:31 UTC, yukihiroLaravel commented on resources/views/auth/register.blade.php
> +                    <input id="password" type="password" class="form-control" name="password" value="{{ old('password') }}">
今は確認しにくいですが
バリデーションエラーが起きた場合、
パスワードがエラー後に残るのは仕様として
不自然（ハッキングなどの可能性）なため
ここのold関数はなくていいと思います！

2024-06-17 12:41 UTC, maxmindl commented on resources/views/auth/register.blade.php
> +                    <input id="password" type="password" class="form-control" name="password" value="{{ old('password') }}">
ありがとうございます。確認し、修正を行いました。

2024-06-17 12:41 UTC, maxmindl commented on routes/web.php
> +
ありがとうございます。確認し、１行空行を消す修正を行いました。

2024-06-20 02:29 UTC, yukihiroLaravel requested changes
OKかと思いますが
１点だけ指摘しましたので
ご確認ください！

2024-06-20 02:29 UTC, yukihiroLaravel commented on routes/web.php
> +});
この３行は２１行目と結果的に
welcomeを表示するという意味で同じなので不要ですね！

2024-06-20 13:16 UTC, maxmindl commented on routes/web.php
> +});
お疲れ様です。
18~20行目を消去しました。

2024-06-20 19:45 UTC, yukihiroLaravel requested changes

2024-06-20 19:45 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('/', 'PostController@index');
すみません、
こちら上と全く同じルーティングがありませんか？
二重に同じルーティングが存在するのだとおかしいので
削除しましょう！

2024-06-20 22:22 UTC, maxmindl commented on routes/web.php
> +Route::get('/', 'PostController@index');
Laravel講座を見て、正しいコードを参考にし訂正しましたことを報告します。

2024-06-20 23:26 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
お疲れ様でした😊！！

2024-06-20 23:26 UTC, merged