ユーザログイン・ログアウト
yukihiroLaravel/joint_develop pull request #1153
Opened 2024-06-17 08:00 UTC by mizuki012

概要
・ユーザログイン・ログアウトの実装

動作確認手順
・ログイン前のトップページにおいて、ヘッダー部分に[ログイン][新規ユーザ登録]が出現するか確認
・ヘッダー部分のログインをクリックすると、ログイン画面に遷移するか確認
・ログイン画面に、メールアドレスとパスワードを適切に入力してログインボタンをクリックすると、マイページに遷移するか確認
・マイページに遷移した際、ヘッダー部分に[ユーザー名][ログアウト]が出現するか確認
・マイページのログアウトボタンをクリックすると、ログイン前のトップページに遷移するか確認

確認していただきたいこと
・特になし

2024-06-17 16:07 UTC, yukihiroLaravel requested changes
ほぼ完璧です！☺️
少しだけ指摘させていただきましたのでご確認ください！

2024-06-17 16:07 UTC, yukihiroLaravel commented on routes/web.php
> +
この空行は２行不要かと思います！

2024-06-17 16:07 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
> +            @if(Auth::check())
ここはスペース４つ分右に移動しないと
インデントが変ですね！

2024-06-17 16:07 UTC, yukihiroLaravel commented on resources/views/auth/login.blade.php
> +            <form method="POST" action="{{ route('login.post') }}">
app.bladeからエラーメッセージを移動させて
この辺りに埋め込まないと
バリデーション エラーの出る場所が
お手本と異なることになりますね💦

2024-06-17 16:11 UTC, mizuki012 commented on routes/web.php
> +
ご指摘ありがとうございます！
修正しました。

2024-06-17 16:19 UTC, mizuki012 commented on resources/views/commons/header.blade.php
> +            @if(Auth::check())
ご指摘ありがとうございます！
修正しました。

2024-06-17 17:12 UTC, mizuki012 commented on resources/views/auth/login.blade.php
> +            <form method="POST" action="{{ route('login.post') }}">
修正いたしました！

2024-06-17 22:14 UTC, yukihiroLaravel requested changes

2024-06-17 22:14 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="{{ route('logout') }}" class="nav-link text-light">ログアウト</a></li>
ここも右にスペース4つ分インデント付けないとおかしいですね！

2024-06-17 22:14 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
>                      <li class="nav-item"><a href="" class="nav-link text-light">新規ユーザ登録</a></li>
ここも右にスペース4つ分インデント付けないとおかしいですね！

2024-06-17 22:14 UTC, yukihiroLaravel commented on resources/views/auth/login.blade.php
> +            <form method="POST" action="{{ route('login.post') }}">
これはバリデーションエラーの動作確認されましたか？
今のままだと２つエラーメッセージが出て変なことになるので
app.bladeのエラーメッセージは消すべきだと思います！

2024-06-19 00:24 UTC, yukihiroLaravel approved these changes

2024-06-19 00:24 UTC, merged