#95 posts（投稿）テーブルのマイグレーションとシーダー作成(中川)
yukihiroLaravel/joint_develop pull request #1155
Opened 2024-06-21 14:54 UTC by 396sss

## issue
- Closes [posts（投稿）テーブルのマイグレーションとシーダー作成 #95](https://github.com/yukihiroLaravel/joint_develop/issues/95)

## 概要
- posts（投稿）テーブルのマイグレーションとシーダー作成

## 動作確認手順
- 下記コマンドを実行
php artisan migrate --seed
 - Adminerでpostsテーブルに11個のレコードが保存されていることを確認

## 考慮して欲しいこと
- 状況に応じて、下記コマンドで動作確認する必要あり。
php artisan migrate:fresh --seed
usersテーブルのidカラムに2～４が登録されている状態で確認

2024-06-21 22:04 UTC, yukihiroLaravel requested changes
プルリクまでお疲れ様でした！！

少し指摘させていただきましたので
ご確認・修正ください！

あとは、MTGのときにお伝えの通り
コードの意味なども理解しながら進めていきましょう！

2024-06-21 22:04 UTC, yukihiroLaravel commented on app/Posts.php
> +class Posts extends Model
このクラス名は
Post
と単数形にしましょう！

同時にファイル名は
Post.php
と単数形にしましょう！

2024-06-21 22:04 UTC, yukihiroLaravel commented on app/Posts.php
> +        return $this->belongsTo(Posts::class);
ここは
return $this->belongsTo(User::class);
じゃないといけませんね！

今の状態だと、
PostクラスがPostクラスに属している
という状態になってしまっています💦

2024-06-22 13:19 UTC, 396sss commented on app/Posts.php
> +        return $this->belongsTo(Posts::class);
ありがとうございます

return $this->belongsTo(Posts::class);　×
return $this->belongsTo(User::class);　に修正しました

2024-06-22 13:21 UTC, 396sss commented on app/Posts.php
> +class Posts extends Model
ありがとうございます

class Posts extends Model　×
class Post extends Model　に修正し

ファイル名を
Posts.php　×
Post.php　へと修正致しました

2024-06-22 23:06 UTC, yukihiroLaravel approved these changes
OKですのでマージしました！
大変だったと思いますが、
お疲れ様でした☺️

早速ではありますが、次のタスクに移りましょう！

2024-06-22 23:06 UTC, merged