#113 トップページの投稿表示(鍵野)
yukihiroLaravel/joint_develop pull request #1157
Opened 2024-06-24 15:55 UTC by kimonoremark

2024-06-25 00:40 UTC, yukihiroLaravel requested changes
いい感じですね！
ただ、他の方のタスクに掛かってしまっている部分もありますので
その点などコメントしましたので修正しましょう！
https://www.loom.com/share/1f5e9e796c1b4e7a9f03e5435c752fcc?sid=e4378f62-6fa1-40a4-962e-39881000b9bb

2024-06-25 00:40 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +        <form method="POST" action="{{ route('post.store') }}" class="d-inline-block w-75">
削除

2024-06-25 00:40 UTC, yukihiroLaravel commented on app/Http/Controllers/PostController.php
> +        return back();
削除

2024-06-25 00:40 UTC, yukihiroLaravel commented on app/Http/Requests/PostRequest.php
> +}
削除

2024-06-25 00:40 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +use App\Post;
削除

2024-06-25 00:40 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +    </div>
ページネーションを移動

2024-06-25 00:40 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +<div class="m-auto" style="width: fit-content"></div>
ページネーションをここに移動

2024-06-25 16:09 UTC, kimonoremark commented on resources/views/welcome.blade.php
> +        <form method="POST" action="{{ route('post.store') }}" class="d-inline-block w-75">
削除しました

2024-06-25 16:09 UTC, kimonoremark commented on app/Http/Controllers/PostController.php
> +        return back();
削除しました

2024-06-25 16:13 UTC, kimonoremark commented on app/Http/Requests/PostRequest.php
> +}
Requestsフォルダごと削除しました

2024-06-25 16:14 UTC, kimonoremark commented on database/seeds/PostsTableSeeder.php
> +use App\Post;
削除しました

2024-06-25 16:32 UTC, kimonoremark commented on resources/views/welcome.blade.php
> +    </div>
移動しました

2024-06-25 16:33 UTC, kimonoremark commented on resources/views/posts/posts.blade.php
> +<div class="m-auto" style="width: fit-content"></div>
追加しました

2024-06-25 22:35 UTC, yukihiroLaravel requested changes
お疲れ様でした！

いくつか細かい点だけ追記して指摘しましたので
ご確認お願いします！

2024-06-25 22:35 UTC, yukihiroLaravel commented on app/Http/Controllers/PostController.php
> +use App\Http\Requests\PostRequest;
この１行は今の時点では使っていないので
消しておきましょう！

2024-06-25 22:35 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> -            <form method="" action="" class="d-inline-block w-75">
指示がわかりにくく、すみません。

action=""やmethod=""の
""の中身だけ消すべきでした！

この記述自体は残して欲しいので
`<form method="" action="" class="d-inline-block w-75">`
この状態で１行復活させましょう！

2024-06-25 22:35 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +<div class="m-auto" style="width: fit-content"></div>
この１行は現在は意味をなしていないと思いますので
（ページ送りのために必要な記述）
１行削除しましょう！

2024-06-28 20:48 UTC, yukihiroLaravel approved these changes

2024-06-28 20:48 UTC, merged