#113　トップページの投稿表示(松本)
yukihiroLaravel/joint_develop pull request #1160
Opened 2024-07-01 03:01 UTC by kazu-777

## issue
- Closes #113 

## 概要
- トップページの投稿表示

## 動作確認
- Adminerのpostテーブルに12個目を作成
- コメントとアップデートの日時を記入
- localhost:8080で
　投稿の一番上に表示されていること
　コメント
　アップデートの日時
　アバター画像
が表示されていることを確認
-投稿表示ユーザが10人分が表示され、それ以降は次のページで表示されていることを確認

## 確認してほしいこと
viewの記述はこれで合ってますでしょうか？
よろしくお願いいたします。

2024-07-01 14:17 UTC, yukihiroLaravel requested changes
いいですね！
細かい点だけ修正お願いします！☺️

https://www.loom.com/share/1a0806fea962462f85be7761946abba3?sid=00bc158a-ab20-48f1-acf9-79269dcf7708

2024-07-01 14:17 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $posts = post::orderBy('created_at','desc')->paginate(10);
post → Post

id順の方がよりいい

2024-07-01 14:17 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +use App\post;
post → Post

2024-07-01 14:17 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +                    </div>
インデントを減らすのと
これらのボタンは
ログインユーザ本人の投稿のときだけ表示させるように
変更しましょう！

2024-07-01 14:17 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +
空行不要

2024-07-02 12:51 UTC, yukihiroLaravel requested changes

2024-07-02 12:51 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +                    </div>
@if ($post->user_id == ログインユーザID)

2024-07-02 20:16 UTC, kazu-777 commented on app/Http/Controllers/PostsController.php
> +        $posts = post::orderBy('created_at','desc')->paginate(10);
変更しました！

2024-07-02 20:17 UTC, kazu-777 commented on app/Http/Controllers/PostsController.php
> +use App\post;
変更しました！

2024-07-02 20:18 UTC, kazu-777 commented on resources/views/posts/posts.blade.php
> +                    </div>
変更しました！
viewは少しずつ理解できるように頑張ります！

2024-07-03 02:29 UTC, yukihiroLaravel requested changes
OKです！
問題ないのでマージしました！
お疲れでした😃

2024-07-03 02:30 UTC, yukihiroLaravel approved these changes
OKです！
問題ないのでマージしました！
お疲れでした😃

2024-07-03 02:30 UTC, merged