Feature/a minaduki dra/user withdrawl
yukihiroLaravel/joint_develop pull request #1171
Opened 2024-07-20 08:16 UTC by maxmindl

## issue
- Code #125 ユーザー退会(辻/G2)

## 概要
・ユーザー退会

## 動作確認手順
https://jam.dev/c/7b2e5cac-54a5-4ac9-821d-09ed9c130572

上記のURLの動画手順と同じように、
①test1でメールアドレス(test1@test.com)、パスワード(test1)でログイン
②トップページのヘッダー「test1」へ移動し、ユーザー情報の詳細へと移動。
③「ユーザー情報を編集する」の赤いボタン「退会する」でtest1のユーザー情報を消す。
④トップーページの投稿リストにtest1投稿が消えているか確認。

## 考慮いただきたい点
「ユーザー詳細」タスクのshow.blade.phpにてAuthについての記述を失念していました。
  動作確認は実行済みです。トップページの他ユーザーから「ユーザー情報の編集」が見れないか確認願います。
  
 ## 確認してほしい点
 特にございません。

2024-07-20 11:55 UTC, yukihiroLaravel requested changes
ほぼ完璧かと思います！😃
１点だけコメントしましたので
その点だけ修正ください！

https://www.loom.com/share/60594e3dae3e484fb1715651378b90d2

2024-07-20 11:55 UTC, yukihiroLaravel commented on app/Console/Kernel.php
> -<?php
復活させるべき

2024-07-20 11:55 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                    @endif
ありがとうございます！

2024-07-21 00:00 UTC, maxmindl commented on app/Console/Kernel.php
> -<?php
git push -f origin...を使って復活させました。確認ください。

2024-07-21 01:47 UTC, yukihiroLaravel approved these changes

2024-07-21 01:48 UTC, merged