#127 フォロー機能(松本)
yukihiroLaravel/joint_develop pull request #1173
Opened 2024-07-23 11:15 UTC by kazu-777

## issue
- Closes #127 

## 概要
- フォロー機能

## 動作確認手順
- ログイン後、ユーザ詳細画面に移動。ログインした本人以外の詳細画面にフォローボタンがあることを確認
- フォロー後、直前に開いていたユーザ詳細画面に遷移し、”フォローする”ボタンが”フォロー外す”ボタンに変わったのを確認
- Adminerのfollowsのデータに保存されたのを確認
- フォローしたユーザ詳細画面で”フォローを外す”ボタンを押す。”フォロー外す”ボタンが”フォローする”ボタンに変わったのを確認
- Adminerのfollowsのデータが削除されたのを確認

2024-07-23 13:06 UTC, yukihiroLaravel requested changes
修正お願いします！

2024-07-23 13:06 UTC, yukihiroLaravel commented on routes/web.php
> +    Route::delete('/unfollow/{id}','FollowController@destroy')->name('unfollow');
usersのprefixのなかに入れて
users/{id}/follow
のようになるようにする

2024-07-23 13:06 UTC, yukihiroLaravel commented on app/User.php
> +        if($exist){
if ($exist) {

2024-07-24 00:36 UTC, kazu-777 commented on routes/web.php
> +    Route::delete('/unfollow/{id}','FollowController@destroy')->name('unfollow');
修正しました！

2024-07-24 00:36 UTC, kazu-777 commented on app/User.php
> +        if($exist){
修正しました！

2024-07-24 05:55 UTC, yukihiroLaravel approved these changes
完璧ですね！！
OKですのでマージしました！
おつかれさまでした😊

2024-07-24 05:55 UTC, merged