画像投稿機能(松本)
yukihiroLaravel/joint_develop pull request #1179
Opened 2024-07-29 08:28 UTC by kazu-777

## issue
- 画像投稿機能

## 概要
- 画像投稿機能の追加

## 動作確認
- ユーザーログイン後、投稿フォームにテキストと投稿したい画像を選択し、投稿ボタンを押す。
- 投稿が表示されていること、Adminerでpathが入っていることを確認。
- 画像が選択されていなくても投稿できることを確認
- 指定した形式でない場合や画像のみの投稿にはエラーメッセージが出ることを確認

2024-07-29 10:19 UTC, yukihiroLaravel requested changes
かなりいい感じですね！

細かい点のみ指摘させていただきました！

あとこれが完成したら次は
（余裕があればですが）
投稿編集機能にも画像を添付できるような
機能をつけてもいいかもですね！

2024-07-29 10:19 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +                    <img src="{{ asset('storage/'.$post->image_path) }}" class="card-img-top" alt="...">
ここにはマウスをホバーした時などに出る文字をかくべきなので
alt="投稿した画像"
こんな感じに書きましょう！

2024-07-29 10:19 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +                        <button type="submit" class="btn btn-primary">投稿する</button>
ファイルを選択するボタンと
投稿するボタンの間に
隙間があまりないので
もう少し開けて頂いた方がいいかなと思います！

2024-07-30 01:33 UTC, kazu-777 commented on resources/views/posts/posts.blade.php
> +                    <img src="{{ asset('storage/'.$post->image_path) }}" class="card-img-top" alt="...">
変更しました！

2024-07-30 01:33 UTC, kazu-777 commented on resources/views/welcome.blade.php
> +                        <button type="submit" class="btn btn-primary">投稿する</button>
変更しました！

2024-07-30 02:06 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした😃

2024-07-30 02:06 UTC, merged