#115 ユーザ詳細(大川)
yukihiroLaravel/joint_develop pull request #1195
Opened 2024-08-18 14:20 UTC by ookawa999jp

## issue
- Closes #115

## 動作確認手順
https://www.dropbox.com/scl/fi/9uneo617l2iggd9xmlnpt/UT.xlsx?rlkey=g41oltom0bgryte9octfibd9g&dl=0
の
ユーザ詳細のUT.xlsx
にて、UTをしました。
前、タスクと同様のテストドライバーのモジュールにローカル配置してます。（　それらは、現タスクでプッシュしません )

https://www.dropbox.com/scl/fi/7g50lshrojwu27uoh7s3x/temporaryAvatarImage.png?rlkey=5vc1yqv1xlwmpsd0nsc185w7u&dl=0
の
temporaryAvatarImage.png
と、
https://www.dropbox.com/scl/fi/p2meup23ic9n1auv526w0/thumbnailTemporaryAvatarImage.png?rlkey=d5dcf5krje2rityry694n6n1c&dl=0
の
thumbnailTemporaryAvatarImage.png

の２つの画像を、ローカルの環境で、
publicフォルダの直下に、配置し

imgタグに、
 src="{{ asset('temporaryAvatarImage.png') }}" 
 src="{{ asset('thumbnailTemporaryAvatarImage.png') }}" 
のような形で指定しておき、表示（デザインの確認だけしてます）
その件、TODOコメントしてます。

最終形では、要らないため
これらの画像はプッシュには含めませんでした
slackにて、連携します。

## 考慮してほしいこと
app/Http/Controllers/Controller.php
にダミー実装を仕込んでの動作させてます。
その他、アバター画像のところもTODOです
ダミーや、TODOで、強引に前進してますが、
ある程度の、形あるモノ作って前進しないと
会話のネタにもなりませんし、ある程度、ダミーでもいいから前進してみて
気が付くこともあり、一旦は、これでよしとしました。
フォロー関連、アバター関連は、別途、MTGなどで話すしかないです。
Postのモデルも、項目名textもダミー実装で、仮想定でしましたが
ここの機能は、どうせ、手を加える必要ありなので
一旦は、それでよいかと判断し、プルリクエストを出しています

2024-08-19 00:09 UTC, yukihiroLaravel requested changes
いくつか指摘させていただきましたので
ご確認ください！

2024-08-19 00:09 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +    }
フォローのルーティングやコントローラのメソッドは
フォローの対応タスクの方が行うので
一旦そのままで置いておいていいのではないでしょうか？
なので一旦削除しておいていいと思います！

2024-08-19 00:09 UTC, yukihiroLaravel commented on routes/web.php
> +    Route::get('followers','UsersController@followers')->name('user.followers');
フォローのルーティングやコントローラのメソッドは
フォローの対応タスクの方が行うので
一旦そのままで置いておいていいのではないでしょうか？
なので一旦削除しておいていいと思います！

2024-08-19 00:09 UTC, yukihiroLaravel commented on resources/views/posts/show.blade.php
> +                <img class="mr-2 rounded-circle" src="{{ asset('thumbnailTemporaryAvatarImage.png') }}" alt="ユーザのアバター画像">
アバター画像の部分は、Gravatorという外部サービスを使ってる感じになります。
なので下記を行いましょう！

手順としては、
① composer.jsonの下記の部分に追記
https://gyazo.com/61627c4076d75a6369261f489cfaee29
追記する内容
 "thomaswelton/laravel-gravatar": "~1.0"

②
composer install
を実行

③
画像（img）の srcの部分に、下記のように記載
`<img class="mr-2 rounded-circle" src="{{ Gravatar::src(投稿者のメールアドレス, 55) }}" alt="ユーザのアバター画像">`
投稿者のメールアドレス部分は変数から取り出す必要があります。

2024-08-21 13:43 UTC, yukihiroLaravel reviewed
２点ほどコメントしましたので
ご確認ください！

2024-08-21 13:43 UTC, yukihiroLaravel commented on app/Http/Controllers/Controller.php
> +        return $user->posts()->orderBy('created_at', 'desc')->paginate(10);
このままでもいいのですが
created_at
を
id
に変更すれば、今の
PostsSeederの記述の仕方でも問題ないかなと思いました！

2024-08-21 13:43 UTC, yukihiroLaravel commented on app/Http/Controllers/Controller.php
> +    }
上記と関連して、
このファイルではないのですが
下記はこれからチームメンバーと相談して
このように変更される可能性がある、という認識であっていますでしょうか？
```
        for($i = 1; $i < 31; $i++){

            if ($i !== 2) {
                continue;
            }

            // ユーザ2だけ。

            for($postIndex = 0; $postIndex < 21; $postIndex++){
                DB::table('posts')->insert([
                    'user_id'=> $i,
                    'content'=> $i . '番の中の' . ($postIndex + 1) . '番です',
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);    
                sleep(2); // 2秒ずらして、created_atの値が変わるようにして、created_atの降順の取得を確認したい！！
            }
        }
```

2024-08-21 14:28 UTC, ookawa999jp commented on app/Http/Controllers/Controller.php
> +        return $user->posts()->orderBy('created_at', 'desc')->paginate(10);
対応しました。
同じように、ユーザの投稿の新しい順(Postのidの降順)
で、３ページ見ました。

2024-08-21 15:35 UTC, ookawa999jp commented on app/Http/Controllers/Controller.php
> +    }
Postのシーダーのほうは、なおしてもよいかと思うのですが
会話できてないです。
idの降順ならば、別に、2秒待つ必要もないため
全ユーザに対しても、実行時間はかからないでしょうから
そのほうが便利だと思うけど・・・。

下記に案をいくつか、示しておきました。
いずれも、動作確認済です。
しかし、これは、このissueなのか？

案_その１）
現状のまま、ユーザー30人分、全員投稿1件

案_その２）ユーザー30人分、全員投稿21件
```
    public function run()
    {
        //テスト代入件数　30件
        for($i = 1; $i < 31; $i++){
            for($postIndex = 0; $postIndex < 21; $postIndex++){
                DB::table('posts')->insert([
                    'user_id'=> $i,
                    'content'=> $i . '番の中の' . ($postIndex + 1) . '番です',
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);    
            }
        }
    } 
```

案_その３）ユーザー毎に投稿件数を指定できる、指定なしはデフォルト件数
```
    public function run()
    {
        // UsersTableSeeder.phpの件数と同期をとってください
        $userCounts = 30;

        // ユーザーごとのデフォルトの投稿件数
        $defaultPostCounts = 21;

        //テスト代入件数　30件
        for($userIndex = 0; $userIndex < $userCounts; ++$userIndex){

            $userId = ($userIndex + 1);

            // ********************************************************
            // テストケースに合わせてユーザー毎の投稿件数を変更できます
            // パラメータ指定がないものは、$defaultPostCounts件になります。
            // 終わったら、
            // git checkout HEAD -- database/seeds/PostsTableSeeder.php
            // で変更を戻せます。
            // ********************************************************
            // keyがuserId, valueが投稿件数
            // 書いてなかったら、$defaultPostCounts
            $paramMap = [ 
                5 => 1,
                7 => 10,
                10 => 15,
                11 => 18,
            ];
            // ********************************************************

            $currentUserPostCounts = $defaultPostCounts;
            if (array_key_exists($userId, $paramMap)) {
                $currentUserPostCounts = $paramMap[$userId];
            }
            
            for($postIndex = 0; $postIndex < $currentUserPostCounts; $postIndex++){
                DB::table('posts')->insert([
                    'user_id'=> $userId,
                    'content'=> $userId . '番の中の' . ($postIndex + 1) . '番です',
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);    
            }
        }
    } 
```

案_その４）その３に加えて、content を140文字以内のfakerで生成した文字列を指定。
```
<?php

use Illuminate\Database\Seeder;
use Faker\Factory as Faker;

class PostsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker::create('ja_JP');

        // UsersTableSeeder.phpの件数と同期をとってください
        $userCounts = 30;

        // ユーザーごとのデフォルトの投稿件数
        $defaultPostCounts = 21;

        //テスト代入件数　30件
        for($userIndex = 0; $userIndex < $userCounts; ++$userIndex){

            $userId = ($userIndex + 1);

            // ********************************************************
            // テストケースに合わせてユーザー毎の投稿件数を変更できます
            // パラメータ指定がないものは、$defaultPostCounts件になります。
            // 終わったら、
            // git checkout HEAD -- database/seeds/PostsTableSeeder.php
            // で変更を戻せます。
            // ********************************************************
            // keyがuserId, valueが投稿件数
            // 書いてなかったら、$defaultPostCounts
            $paramMap = [ 
                5 => 1,
                7 => 10,
                10 => 15,
                11 => 18,
            ];
            // ********************************************************

            $currentUserPostCounts = $defaultPostCounts;
            if (array_key_exists($userId, $paramMap)) {
                $currentUserPostCounts = $paramMap[$userId];
            }

            for($postIndex = 0; $postIndex < $currentUserPostCounts; $postIndex++){

                // 1から2の範囲でスムーズさを調整、
                // 2に近いほどスムーズ。それを乱数調整
                $smooth = rand(1, 2);

                // 140文字以内で、上記のスムーズさでの文字列生成
                $content = $faker->realText(140, $smooth);

                DB::table('posts')->insert([
                    'user_id'=> $userId,
                    'content'=> $content,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);    
            }
        }
    } 
}
```

2024-08-21 22:07 UTC, yukihiroLaravel approved these changes
> 2つ目の分は、そもそも、このissueなの？？　私は、どうすれば？？
こちらでおっしゃっていた通り
同じプルリクで対処しなくてもいい内容だと思いましたので
勝手ながらすみませんが
一旦ここまででマージしました！

2024-08-21 22:07 UTC, merged