ユーザ詳細(有田)
yukihiroLaravel/joint_develop pull request #1198
Opened 2024-08-22 01:31 UTC by irochi1184

## issue
- Closes #115 

## 概要
- ユーザ詳細

## 動作確認手順
- 下記コマンドを実行
```nu-script
docker exec laravel_app bash -c "cd /var/www/html/laravelapp && php artisan migrate:fresh --seed"
```

- Adminerにて`users`テーブルに5つのレコードが追加されることを確認
http://localhost:8088/?server=db&username=dbuser&db=laraveldb&select=users

- 下記URLにてユーザ詳細画面が表示されていることを確認
http://localhost:8080/users/1

- また、ログインユーザの詳細画面では[ユーザ情報の編集]リンクが追加されることを確認
- 下記URLから新規ユーザ登録する
http://localhost:8080/signup

- シーダー実行後、users/6に新たなユーザが登録されるため、以下URLにてリンクが追加されていることを確認する
http://localhost:8080/users/6

イメージ図（bootstrap適用時であり、現時点では装飾なし）
<img width="1440" alt="スクリーンショット 2024-08-22 8 57 00" src="https://github.com/user-attachments/assets/618f6124-e227-48df-8f97-f73e58e1ebbb">

<img width="1440" alt="スクリーンショット 2024-08-22 8 58 04" src="https://github.com/user-attachments/assets/c29a334a-f560-4f83-90b5-41e3aa70d4d0">

### 考慮して欲しいこと
- 状況次第で下記のエラーになることがある
<img width="1440" alt="スクリーンショット 2024-08-22 9 33 04" src="https://github.com/user-attachments/assets/c8a36b43-20ad-4a6e-a3e1-e7705959b2f0">

> [!IMPORTANT]
> 画像出力にGravatarを利用しているためdockerコンテナ内で下記コマンドを実行する必要がある
> ```shell
> composer update
> composer install
> ```

## 確認して欲しいこと
- resources/views/users/show.blade.phpの比較演算子を`==`としたがこの記述で問題ないか？
```php
@if (Auth::id() == $user->id)
```

2024-08-22 12:12 UTC, yukihiroLaravel requested changes
他の方が作業中でつくりにくいと思いますが
よく実装されたと思います！

上記踏まえていくつかご指摘しましたので
ご確認ください！😃

2024-08-22 12:12 UTC, yukihiroLaravel commented on app/Http/Controllers/Controller.php
> +            'countPosts' => $countPosts,
このcountPostsの配列は
現状は特に使われておらず、お手本の方でも特に投稿数カウントは存在しませんが
今後投稿数カウントを使う予定、もしくは、使いたい、ということでしょうか？

使う場合は、現時点でも投稿数カウントを表示できるようにしておいていいと思いますし
使わない場合は消しておきましょう！

2024-08-22 12:12 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $data += $this->userCounts($user);
このuserCountsの配列は
現状は特に使われておらず、お手本の方でも特に投稿数カウントは存在しませんが
今後投稿数カウントを使う予定、もしくは、使いたい、ということでしょうか？

使う場合は、現時点でも投稿数カウントを表示できるようにしておいていいと思いますし
使わない場合は消しておきましょう！

2024-08-22 12:12 UTC, yukihiroLaravel commented on app/User.php
> +        return $this->hasMany(Post::class);
他の方が作業中でつくりにくいと思いますが
今のままではPostモデルがないので動作しないですよね？
このモデルは特にだれが作るなどタスクによって分けていないため
有田さんがつくってもいいと思います！

2024-08-22 12:12 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +</div>
他の方の実装がまだでこれもやりにくいと思いますが
UsersControllerで下記の実装を行うなら
現時点で
`$posts = $user->posts()->orderBy('id', 'desc')->paginate(9);`
このあたりに投稿が表示されるように実装してもいいかと思います！

2024-08-23 00:18 UTC, irochi1184 commented on app/Http/Controllers/Controller.php
> +            'countPosts' => $countPosts,
ありがとうございます！
特に現状では特に実装を予定していないため
消させていただきます！

2024-08-23 00:19 UTC, irochi1184 commented on app/Http/Controllers/UsersController.php
> +        $data += $this->userCounts($user);
ありがとうございます！
特に現状では特に実装を予定していないため
消させていただきます！

2024-08-23 00:19 UTC, irochi1184 commented on app/User.php
> +        return $this->hasMany(Post::class);
おっしゃる通りテスト環境ではPostモデルを作成して実装しておりました！
今回のプルリクに含めたいと思います！

2024-08-23 00:35 UTC, irochi1184 commented on resources/views/users/show.blade.php
> +</div>
そちら失念しておりました！
せっかくなので表示するように修正いたします！

2024-08-23 00:43 UTC, irochi1184 commented
前コミットから
修正した箇所は以下の通りです。

- app/Http/Controllers/Controller.php
  - userCounts($user)メソッドの削除
- app/Http/Controllers/UsersController.php
  - `$data += $this->userCounts($user);`の削除
- resources/views/users/show.blade.php
  - `{{ $posts->links('pagination::bootstrap-4') }}`の追加
-  app/Post.phpの追加

2024-08-23 11:57 UTC, yukihiroLaravel approved these changes

2024-08-23 11:57 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        // $posts = $user->posts()->orderBy('id', 'desc')->paginate(9);
// TODO: 投稿一覧表示機能がマージされたらコメントアウトをはずして、ユーザ詳細にも投稿が表示されるようにする

2024-08-23 11:57 UTC, merged