ヘッダー有効化とバリデーション
yukihiroLaravel/joint_develop pull request #1210
Opened 2024-08-28 23:26 UTC by irochi1184

## issue
- Closes #107 #115 

## 概要
- ユーザ新規登録・詳細画面のヘッダー有効化とバリデーション

## 動作確認手順
- [ ] 下記URLにアクセスし、ヘッダー等レイアウトが整っていることを確認
http://localhost:8080/signup
- [ ] 何も入力せずに「新規登録」ボタンを押下すると
画像のようにバリデーションエラーメッセージが出現することを確認
<img width="1440" alt="スクリーンショット 2024-08-29 8 17 18" src="https://github.com/user-attachments/assets/fe67602a-b375-47cb-9665-05bc47e08f61">

- [ ] 登録完了後、下記URLからユーザ詳細画面に遷移してヘッダー等レイアウトが整っていることを確認
http://localhost:8088/?server=db&username=dbuser&db=laraveldb&select=posts
<img width="1440" alt="スクリーンショット 2024-08-29 8 22 41" src="https://github.com/user-attachments/assets/a63d0338-e6da-4327-9533-8cbf42b65a23">

## 考慮して欲しいこと
- 特になし

## 確認して欲しいこと
- 特になし

2024-08-29 01:31 UTC, yukihiroLaravel requested changes
１点別途コメントしたのと

それと別に
新規ユーザ登録した後に
ヘッダーがお手本と同じように変化する（ログインユーザ名がヘッダーに表示される）ように
今はなっていないと思います。

そちらは誰がどのタスクで対応されるか決められていますでしょうか？
決めていなければ、
このタスクを行うありけんさんもしくは
ログイン機能のタスクを行う方のいずれかが対応するのが
自然かなと思いました！

2024-08-29 01:31 UTC, yukihiroLaravel commented on resources/views/auth/register.blade.php
> +@include('commons.error_messages')
これだと、バリデーションメッセージの位置が
お手本と異なる、少し不自然な配置になっていないでしょうか？

位置の修正をお願いします！

2024-08-30 11:27 UTC, irochi1184 commented
<img width="1440" alt="スクリーンショット 2024-08-30 20 27 03" src="https://github.com/user-attachments/assets/0755c58e-bbaa-41fd-8395-84cbf8ac2404">

エラーメッセージ表示位置の変更しました！

2024-08-30 11:46 UTC, yukihiroLaravel approved these changes

2024-08-30 11:46 UTC, merged