post(投稿)テーブルのマイグレーションとシーダー(大畑)修正3
yukihiroLaravel/joint_develop pull request #1211
Opened 2024-08-30 13:22 UTC by echono10

## issue
- Closes #95

## 概要
- posts（投稿）テーブルのマイグレーションとシーダー作成修正

## 動作確認手順

### 考慮して欲しいこと

## 確認して欲しいこと

2024-08-30 13:44 UTC, yukihiroLaravel requested changes

2024-08-30 13:44 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('logout','Auth\LoginController@logout')->name('logout');
たぶん、ご自身で別ブランチで実装中の内容を
引き連れてきてしまっていますので
このブランチでは不要なので消しましょう💦！

2024-09-02 12:43 UTC, echono10 commented
修正しました。
ご確認お願いいたします。

2024-09-02 13:28 UTC, yukihiroLaravel approved these changes

2024-09-02 13:28 UTC, merged