#115　ユーザ詳細(西山しょうこ)
yukihiroLaravel/joint_develop pull request #1214
Opened 2024-09-01 13:08 UTC by Kujiran40

## issue
- Closes #115

## 概要
- ユーザ詳細

## 動作確認手順
- Adminerにて、Posts(投稿)テーブルにデータが反映されたことを確認。
　http://localhost:8088/?server=db&username=dbuser&db=laraveldb&select=posts

- ローカルで、ユーザ詳細画面に表示されるべき項目が表示されることを確認。
　http://localhost:8080/users/1

## 確認して欲しいこと
Postモデル（App/Post.php）で7行目のコードによりエラーが発生したので、コメントアウトしました。

2024-09-02 04:11 UTC, yukihiroLaravel requested changes
見た目もほぼ完璧ですばらしいですね！
少しだけ指摘しましたのでご確認ください！

2024-09-02 04:11 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +                <p class="mt-3 mb-0 d-inline-block"><a href="{{ route('user.show', $user->id) }}">{{ $post->user->name }}</a></p>
ここは
posts.bladeに$userを渡さなくて済むように
$post->user->id
にしましょう！

2024-09-02 04:11 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +            @include('posts.posts', ['user' => $user, 'posts' => $posts])
ここは上記の通り、
posts.bladeに$userを渡さなくて済むように
すればいいので、
'user' => $userは消しましょう！

2024-09-02 04:11 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $posts = $user->posts()->orderBy('id', 'desc')->paginate(9);
お手本だと１ページ10投稿だと思いますので
paginate(10)にしましょう

2024-09-03 00:03 UTC, Kujiran40 commented on resources/views/posts/posts.blade.php
> +                <p class="mt-3 mb-0 d-inline-block"><a href="{{ route('user.show', $user->id) }}">{{ $post->user->name }}</a></p>
6行目　href の中、$user->id  を  $post->user->id に変更しました。

2024-09-03 00:03 UTC, Kujiran40 commented on resources/views/users/show.blade.php
> +            @include('posts.posts', ['user' => $user, 'posts' => $posts])
'user' => $user　消去しました。

2024-09-03 00:04 UTC, Kujiran40 commented on app/Http/Controllers/UsersController.php
> +        $posts = $user->posts()->orderBy('id', 'desc')->paginate(9);
変更OKです！

2024-09-03 05:49 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！！
難しい部分もありましたが、よくできていると思います。
おつかれさまでした😃

2024-09-03 14:15 UTC, merged