フォロー機能(有田)
yukihiroLaravel/joint_develop pull request #1215
Opened 2024-09-03 01:04 UTC by irochi1184

2024-09-03 06:10 UTC, yukihiroLaravel requested changes
コードは完璧に近くてすばらしいですね！

ただ、上手く動かない部分と
少し指摘がありましたのでご確認ください！

2024-09-03 06:10 UTC, yukihiroLaravel commented on routes/web.php
> +    Route::get('{id}/followers', 'UsersController@followers')->name('user.followers');
すべて{id}がついているので
prefixをつけてまとめましょう！

2024-09-03 06:10 UTC, yukihiroLaravel commented on routes/web.php
> +    Route::delete('/users/{user}/unfollow', 'UsersController@unfollow')->name('unfollow');
すべてusers/{id}がついているので
prefixをつけてまとめましょう！

2024-09-03 06:10 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                <a href="" class="nav-link {{ Request::is() ? 'active bg-primary text-white' : '' }}">タイムライン</a>
このタスクでやるべきか微妙ですが
ここのhrefが記述ないので
タイムラインに戻れない状態になっているので
記述しておきましょう

2024-09-03 06:10 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                @endif
これだとログインしていても
フォローしていない相手のユーザ詳細画面にいったときに
フォローするボタンが出ないと思います！

2024-09-03 14:42 UTC, yukihiroLaravel requested changes

2024-09-03 14:42 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                <a href="" class="nav-link {{ Request::is() ? 'active bg-primary text-white' : '' }}">タイムライン</a>
hrefと合わせて
Request::is()
この()の中にもタイムライン=通常のユーザ詳細のルーティングが入るのが自然かとおもいます！

2024-09-12 22:17 UTC, yukihiroLaravel requested changes

2024-09-12 22:17 UTC, yukihiroLaravel commented on resources/views/users/followers.blade.php
> +                                <button type="submit" class="btn btn-outline-secondary rounded-pill">フォロー中</button>
フォロー解除などの方がいい？

2024-09-12 22:17 UTC, yukihiroLaravel commented on resources/views/users/followings.blade.php
> +                                <button type="submit" class="btn btn-outline-secondary rounded-pill">フォロー中</button>
フォロー解除などの方がいい？

2024-09-12 22:17 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                    <a href="{{ route('login') }}" class="btn btn-primary rounded-pill">フォローする</a>
ログインしていない場合もフォローすると表示するのはあえてでしょうか？

2024-09-12 22:17 UTC, yukihiroLaravel commented on resources/views/users/followings.blade.php
> +                        <a href="{{ route('login') }}" class="btn btn-outline-primary rounded-pill">フォローする</a>
ログインしていない場合もフォローすると表示するのはあえてでしょうか？

2024-09-13 00:48 UTC, irochi1184 commented on resources/views/users/show.blade.php
> +                    <a href="{{ route('login') }}" class="btn btn-primary rounded-pill">フォローする</a>
Xの仕様に合わせており、
あえて未ログイン状態で「フォロー」という機能が存在していることを認知させるために実装しています！

2024-09-13 00:48 UTC, irochi1184 commented on resources/views/users/followings.blade.php
> +                        <a href="{{ route('login') }}" class="btn btn-outline-primary rounded-pill">フォローする</a>
Xの仕様に合わせており、
あえて未ログイン状態で「フォロー」という機能が存在していることを認知させるために実装しています！

2024-09-14 09:14 UTC, irochi1184 commented on resources/views/users/followers.blade.php
> +                                <button type="submit" class="btn btn-outline-secondary rounded-pill">フォロー中</button>
ボタンの見た目自体はXにあわせて「フォロー中」と表示させ、
ホバーした際に「フォロー解除」というボタンに切り替えるように実装しました！
<img width="1440" alt="スクリーンショット 2024-09-14 17 56 28" src="https://github.com/user-attachments/assets/07f5d875-0853-41b6-ad69-214436f1197a">

2024-09-14 09:15 UTC, irochi1184 commented on resources/views/users/followings.blade.php
> +                                <button type="submit" class="btn btn-outline-secondary rounded-pill">フォロー中</button>
ボタンの見た目自体はXにあわせて「フォロー中」と表示させ、
ホバーした際に「フォロー解除」というボタンに切り替えるように実装しました！
以下は「Lola」さんのアカウントの「フォロー中」にカーソルがある状態の例です

<img width="1440" alt="スクリーンショット 2024-09-14 17 56 28" src="https://github.com/user-attachments/assets/07f5d875-0853-41b6-ad69-214436f1197a">

2024-09-15 15:56 UTC, irochi1184 commented
前回ご指摘いただいた、
トップページのフォロー解除未実装部分を実装しました。

また、実装に伴い４箇所でフォローボタンの実装をしており、どれもほぼ同様のコードだったため
共通部品として`common`フォルダ内に`follow_button.blade.php`を作成し、
フォローボタン実装箇所のbladeファイルにてincludeする仕様に変更しました

2024-09-16 12:55 UTC, yukihiroLaravel approved these changes

2024-09-16 12:55 UTC, merged