ユーザログイン・ログアウト#110
yukihiroLaravel/joint_develop pull request #1216
Opened 2024-09-04 15:30 UTC by gi-take

## issue
- Closes #110

## 概要
- ユーザログインログアウト
- ヘッダー右上の表示切替（ログイン等）

## 動作確認手順
- tinkerでユーザ登録してその内容でログインログアウト動作の確認
- 上記と合わせてヘッダー表示の切り替えの確認
　ログイン時の表示・・ログインユーザ名　ログアウト
　未ログイン時の表示・・ログイン　新規登録

### 考慮して欲しいこと
- なし

## 確認して欲しいこと
- 以下のタスクが今回の実装で満たしているかご確認お願いします。
〇実装済みであるユーザ新規登録へのヘッダーの遷移リンク

2024-09-05 23:16 UTC, yukihiroLaravel requested changes
全体的に悪くないですが
細かい点で指摘させていただきましたので
ご確認お願いします！😆

2024-09-05 23:16 UTC, yukihiroLaravel commented on app/Http/Controllers/Auth/LoginController.php
> +    //protected $redirectTo = RouteServiceProvider::HOME;
この行は消してしまいましょう！

2024-09-05 23:16 UTC, yukihiroLaravel commented on resources/views/auth/login.blade.php
> +    @endsection
インデント的に
@endsectionは、
左にスペース４つ分移動したほうがいいですね！

2024-09-05 23:16 UTC, yukihiroLaravel commented on resources/views/auth/login.blade.php
> +<div class="text-center">
インデント的に
このdivタグは、
右にスペース４つ分移動したほうがいいですね！

2024-09-05 23:16 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
> +@endif
こちらお手本ですと、
ログイン後のヘッダーの中にユーザ名が入った状態となると思いますので
そのように修正しましょう！

2024-09-05 23:16 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
> +                    <!-- <li class="nav-item"><a href="" class="nav-link text-light">ログインユーザ名</a></li>
下記のユーザ名に関わる記述は
この記述を利用してつくりましょう

2024-09-05 23:16 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="" class="nav-link text-light">新規ユーザ登録</a></li> -->
このコメントアウトは消してしまっていいと思います！

2024-09-06 11:41 UTC, yukihiroLaravel requested changes

2024-09-06 11:41 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="" class="nav-link text-light">{{ Auth::user()->name }}</a></li>
hrefにユーザ詳細のルーティングを指定

2024-09-07 14:15 UTC, gi-take commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="" class="nav-link text-light">{{ Auth::user()->name }}</a></li>
質問のご回答ありがとうございます。ご教示いただいたとおりに
書き換えたところうまくいきました。

2024-09-07 15:54 UTC, yukihiroLaravel requested changes
まだすこし修正がありましたので
お手数ですがご確認ください！

2024-09-07 15:54 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="{{ route('logout') }}" class="nav-link text-ilght">ログアウト</a></li>
ここの文字はお手本だと白色なのでそのようにしましょう
classのtext-lightの文字が誤っているからだと思います。

2024-09-07 15:54 UTC, yukihiroLaravel commented on resources/views/auth/login.blade.php
> +        <div class="col-sm-6 offset-sm-3">
ログイン失敗したときのエラーメッセージをこの辺りに出るようにしましょう！

2024-09-09 11:08 UTC, gi-take commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="{{ route('logout') }}" class="nav-link text-ilght">ログアウト</a></li>
ログイン失敗時のエラー表示に行き詰っているのでひとまずこちらpushしました。

2024-09-09 13:45 UTC, yukihiroLaravel approved these changes

2024-09-09 13:45 UTC, merged