#113 トップページの投稿表示(ゆうじ)
yukihiroLaravel/joint_develop pull request #1219
Opened 2024-09-08 07:15 UTC by yujiLaravel

## issue
- Closes #113

## 概要
- トップページの投稿表示

## 動作確認手順
- 下記コマンドを実行
```
php artisan migrate:fresh --seed
```

- Adminerにて`users`と`posts`テーブルに各12個のレコードが登録されていることを確認
http://localhost:8088/?server=db&username=dbuser&db=laraveldb&select=users
http://localhost:8088/?server=db&username=dbuser&db=laraveldb&select=posts

- トップページにAdminerのデータに基づいたユーザーの投稿が表示されていることを確認
http://localhost:8080

- トップページ１ページ目の投稿表示数が10件であり、ページ下部のページ遷移リンクから2ページ目に遷移すると11件目以降が表示されていることを確認
http://localhost:8080/?page=2

- ユーザー名のリンクを押下すると各ユーザー詳細ページに遷移することを確認

- ログインしている場合のみ、ログインユーザーの投稿に編集削除ボタンが表示されていることを確認

### 考慮して欲しいこと
> ログイン中の動作確認については、ログイン機能が未実装の状態の為、新規ユーザー登録を行い、新規投稿を作成して確認する必要あり
> http://localhost:8080/signup

## 確認して欲しいこと
- なし

2024-09-08 14:14 UTC, yukihiroLaravel requested changes
いい感じですね！
いくつか細かい点を指摘させていただきましたので
ご確認ください！

2024-09-08 14:14 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +         ]);
インデントがおかしいのでこのようにしましょう！
```
return view('welcome', [
    'posts' => $posts
]);
```

2024-09-08 14:14 UTC, yukihiroLaravel commented on routes/web.php
こちらは結果的に使われなくなったので
UsersControllerのindexメソッドとともに消してしまっていいと思います！

ただ、welcomeというルーティング名は他で使われているようでしたら
17行目の最後につけないといけないかもしれませんのでそれだけ気をつけて下さい！

2024-09-09 13:31 UTC, yujiLaravel commented on app/Http/Controllers/PostsController.php
> +         ]);
インデント変更いたしました

2024-09-09 13:35 UTC, yujiLaravel commented on routes/web.php
不要なルーティングとUsersControllerのindexメソッドを削除いたしました。

2024-09-09 13:43 UTC, yukihiroLaravel approved these changes

2024-09-09 13:43 UTC, merged