#117 ユーザ編集画面・更新
yukihiroLaravel/joint_develop pull request #1222
Opened 2024-09-11 02:28 UTC by Kujiran40

## issue
- Closes #117

## 概要
- ユーザ編集画面・更新

## 動作確認手順
- ローカルにて、以下の手順で、ユーザ編集画面とユーザ情報の更新確認を行った。
① http://localhost:8080/signup  から、ユーザを1人新規作成( id:9 )し、ログインしている状態のトップページへ遷移。
② 投稿を1つ新規作成して、トップページにid:9 のユーザ名と投稿を表示させた。そのURL付きのユーザ名（id:9）をクリックし、ユーザ詳細画面へ移動。
③「ユーザ情報の編集」をクリックし、 http://localhost:8080/users/9/edit が表示されることを確認。
④実際にユーザ名を変更&更新してみて、元の編集画面に戻ることを確認。

## 確認したいこと。
- validationの書き方や場所がこれでよいのか、少し不安です。
- 動作確認手順がこれで良かったのか気になります。もし、より良い方法があれば教えていただきたいです。

2024-09-11 14:37 UTC, yukihiroLaravel requested changes
いくつか指摘させていただきました！
ご確認願います！

2024-09-11 14:37 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        return view('users.edit', ['user' => $user]);
これだとログインしていてurlにuser_idを直入力すれば
他人の名前やパスワードも編集できてしまうので
ログインユーザ本人以外の編集ページにアクセスしようとしたら
403などのエラーを出すようにしましょう。

ヒント→
ログインユーザ本人以外の編集ページにアクセスしようとしたら
abort(403);
というコードを実行するようにすれば、本人以外のアクセス時に403エラーを出せる

2024-09-11 14:37 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $user->password = $request->password;
パスワードは暗号化しないとパスワード変更後ログインできないのではないでしょうか？

2024-09-11 14:37 UTC, yukihiroLaravel commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
この状態ですと、同じユーザでメールを変えず名前だけ変えたい時に
メールを強制的にかえないといけないようになりませんか？

ヒントとしては、下記のようなコードを使うので、少し検索してみてください。
Rule::unique

2024-09-11 14:37 UTC, yukihiroLaravel commented on routes/web.php
> +    });
Route::prefix('users/{id}')
でここはまとめられると思います！

2024-09-13 12:06 UTC, yukihiroLaravel commented on routes/web.php
> +    });
修正します or 修正しました

2024-09-14 05:49 UTC, Kujiran40 commented on app/Http/Controllers/UsersController.php
> +        return view('users.edit', ['user' => $user]);
解決しました！
if文でもできることも理解しました。

2024-09-14 05:50 UTC, Kujiran40 commented on app/Http/Controllers/UsersController.php
> +        $user->password = $request->password;
解決しました！

2024-09-14 05:50 UTC, Kujiran40 commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
解決しました！

2024-09-14 05:51 UTC, Kujiran40 commented on routes/web.php
> +    });
修正しました！

2024-09-14 06:28 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした😊

2024-09-14 06:28 UTC, merged