#117 ユーザ編集画面・更新(ゆうじ)
yukihiroLaravel/joint_develop pull request #1229
Opened 2024-09-15 04:37 UTC by yujiLaravel

## issue
- Closes #117

## 概要
- ユーザ編集画面・更新

## 動作確認手順
- 下記の手順でユーザ編集画面とユーザ情報の更新動作を確認
① http://localhost:8080/signup にてユーザを新規作成し、ログイン状態でユーザ詳細画面にある「ユーザ情報の編集」ボタンを押下する。
②「 ユーザ名、メールアドレス、パスワード、パスワードの確認」を変更入力し、「更新する」ボタンを押下してユーザ詳細画面に遷移することを確認する。
③Adminerにて`users`テーブルのレコードが更新されていることを確認。

### 考慮して欲しいこと
特になし

2024-09-15 14:57 UTC, yukihiroLaravel requested changes
本人のみユーザ編集できるようになっていたり
とても素晴らしいですが少しコメントしましたので
その点ご確認ください😊

2024-09-15 14:57 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +            $user = \Auth::user();
ここの１行は、上の$userの中身と結果的に同じになるので
なくても変わらないと思います！

2024-09-15 14:57 UTC, yukihiroLaravel commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
'unique:users'の書き方ですと、同じユーザでメールを変えず名前だけ変えたい時に
メールを強制的にかえないといけないようになりませんか？

ヒントとしては、下記のようなコードを使うので、少し検索してみてください。
Rule::unique

2024-09-15 14:57 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::put('{id}', 'UsersController@update')->name('user.update');
ここは{id}をまとめて
Route::prefix('users/{id}')
の方がいいと思いました！

2024-09-18 13:09 UTC, yujiLaravel commented on app/Http/Controllers/UsersController.php
> +            $user = \Auth::user();
修正いたしました。

2024-09-18 13:09 UTC, yujiLaravel commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
修正いたしました。

2024-09-18 13:09 UTC, yujiLaravel commented on routes/web.php
> +        Route::put('{id}', 'UsersController@update')->name('user.update');
修正いたしました。

2024-09-18 13:39 UTC, yukihiroLaravel requested changes

2024-09-18 13:39 UTC, yukihiroLaravel commented on routes/web.php
> +    });
Route::prefix('users/{id}')->group(function () {
});

ここの部分が下記のフォローの箇所と全く同じですので
フォローのprefixの中に
これらのユーザ編集・更新ルーティングも入れるようにした方がいいと思いました！

（// フォロー や // ユーザー編集・更新 などのコメントアウトは書き換える必要がありますが）

2024-09-20 11:56 UTC, yujiLaravel commented on routes/web.php
> +    });
// フォロー や // ユーザー編集・更新 などのコメントアウトを書き換えたのと、インデントを揃える点を修正いたしました。

2024-09-20 12:30 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした☺️

2024-09-20 12:30 UTC, merged