不要ファイルのクリーンナップコマンドおよび、ロックファイル作成コマンドなど(大川)
yukihiroLaravel/joint_develop pull request #1237
Opened 2024-09-20 16:49 UTC by ookawa999jp

## issue
- Closes Draft 不要ファイルのクリーンナップコマンドおよび、ロックファイル作成コマンドなど

MTGで説明しとおり
現状）
編集モードのときに、
アップロードの追加／削除時に、storageの追加、削除と、
および、
user_images
または、
post_images
のDELETE/INSERTによる画面でアップロード分として表示されている分を
DB反映している

今後の改修イメージ）
削除時に、storageの削除はしないで放置する
編集モードのときに、編集系の画面で、更新する　のボタンを押した時の
DB処理で、
user_images
または、
post_images
のDELETE/INSERTによる画面でアップロード分として表示されている分を
DB反映する方向性

上記、対応すると、削除はアップロードのサムネイルのUIを画面から消すだけで
storageのファイルは残したまま放置になる。
また、
新規投稿時は、元々、投稿するまでDB反映されないため
アップロードだけして、投稿しませんでしたのケースでも
同様に、不要なファイルが残ったまま

不要ファイルのクリーンナップ処理の必要性が生じたため
Laravelのコマンドの自作の方法で、その実装をした

php artisan cleanup:unused-files
のコマンドで
CleanupUnusedFiles.php
が動くようになっている

ここで不要ファイルのクリーンナップ処理を実装した。
実装内容は、CleanupUnusedFiles.phpのコメント部に詳細書いた

アップロード時に、今回新設した、unused_file_checkersテーブルに
check_countが0でレコード作成する

config/app.phpで指定値での、直近の期間を除いて
check_countの昇順で、N件取得( このN件も、config/app.phpで指定値 )

画面側の操作により、
user_images
または、
post_images
のDELETE/INSERTが走る時に、
ちょうど、DELETE/INSERT処理のDELETEして、INSERTする前のタイミングで
クリーンナップ処理が裏で動くなどして、
消しはいけないファイルが消されてしまう、レアケースでの可能性を
防ぐために

Helper.phpで定義した、doWithLock()
での排他ロックをかけたコールバック実行で
DELETE/INSERTの処理と、
クリーンナップ処理の本体部分の処理を囲っている

排他ロックのやり方の詳細は、doWithLock()内のコメントを参照のこと。

ps -ef | grep "apache"
id www-data
で、
dockerコンテナ内のapacheの実行ユーザが
ユーザ名 : www-data
グループ名 : www-data
であることを確認したうえで、
php artisan prepare:lock-files www-data www-data
を実行すると、
PrepareLockFiles.php
が、
所有者 : www-data、所有グループ : www-data
にて、
storage/app/public
に、
avatar.lock
post.lock
のゼロバイトファイルを作る。
Helper.phpで定義した、doWithLock()は、
'avatar'、'post'
のいずれかを引数指定すると
avatar.lock
post.lock
に対するflock()での排他ロックをしたうえで、コールバック実行する実装となっている

## 動作手順

php artisan migrate
で、新設の
unused_file_checkers
のテーブル定義をしてもらう必要がある。

前述の
```
ps -ef | grep "apache"
id www-data
で、
dockerコンテナ内のapacheの実行ユーザが
ユーザ名 : www-data
グループ名 : www-data
であることを確認したうえで、
php artisan prepare:lock-files www-data www-data
を実行すると、
PrepareLockFiles.php
が、
所有者 : www-data、所有グループ : www-data
にて、
storage/app/public
に、
avatar.lock
post.lock
のゼロバイトファイルを作る。
```
で、環境を作ることが必要。

それから、今、ある程度、sotrageにファイルがあるが、
unused_file_checkers
のデータはゼロ件のため
php artisan maketestdata:unused_file_checkers
で、
InsertUnusedFileCheckers.php
が動き、
sotrageの内容にしたがって、
unused_file_checkersへデータ投入する
(  開発時のテストデータ投入のため、作成した、シーダーともいえない使い方なのでコマンドにした )

## 考慮してほしいこと

画面側の操作により、
user_images
または、
post_images
のDELETE/INSERTの部分は、
今、Helper.phpのdoWithLock()のコールバック実行の範囲にしてる
たしかに、これでクリーンナップ処理とで、
排他ロックの制御ができるが、

この副作用として、複数ユーザが同時に画像のアップロードがある
編集画面利用時でも、そのユーザ同士で
排他ロックがかかり、タイミングによっては、少し、待たされる（スピナー表示時間がその分、わずかに長くなる）
副作用がある

この件は、
doWithLock()をラップして、
同じようにコールバック実行するfunctionを準備し、
日本時間で深夜などのメンテナンス時間に限ってた
doWithLock()を使った排他ロックしてのコールバック実行として
それ以外の時間帯は、そのまま引数で受けたコールバック処理で
コールバックする

そして、クリーンナップ処理のcronなどによる、スケジュール実行の登録を
その深夜の時間帯だけとすれば

**************
この副作用として、複数ユーザが同時に画像のアップロードがある
編集画面利用時でも、そのユーザ同士で
排他ロックがかかり、タイミングによっては、少し、待たされる（スピナー表示時間がその分、わずかに長くなる）
副作用がある
**************
に相当する副作用について、その深夜の時間以外は、なくすことができるのではないかと
考えているので、将来的には、どこかのタイミングで
その改修をいれれば、いいなぁ
と思っている

# 今後
直近は、下記の対応を改修を行う
********************
今後の改修イメージ）
削除時に、storageの削除はしないで放置する
編集モードのときに、編集系の画面で、更新する　のボタンを押した時の
DB処理で、
user_images
または、
post_images
のDELETE/INSERTによる画面でアップロード分として表示されている分を
DB反映する方向性
********************

2024-09-21 15:24 UTC, yukihiroLaravel requested changes
全体的にすばらしいと思います！

細かい点ですが
同じ条件だったり似た内容だったりする部分があるので
もう少し簡潔に書けるかなと思い少しだけ指摘させていただきました！

2024-09-21 15:24 UTC, yukihiroLaravel commented on app/Console/Commands/PrepareLockFiles.php
> +                }
細かい点ですが
このあたり、同じ条件だったり似た内容だったりする部分があるので
もう少し簡潔に書けるかなと思いました！

2024-09-21 17:06 UTC, ookawa999jp commented on app/Console/Commands/PrepareLockFiles.php
> +                }
```
                $isOK = true;
                if ($isOK) {
                    if (!chown($lockFilePath, $user)) {
                        $this->error("Failed to chwon {$lockFilePath} to {$user}");
                        $isOK = false;
                    }
                }
                if ($isOK) {
                    if (!chgrp($lockFilePath, $group)) {
                        $this->error("Failed to chgrp {$lockFilePath} to {$group}");
                        $isOK = false;
                    }
                }
```
上記のようにした意図は、
今は、chownと、chgrpの２つしかないが、これが、10個ぐらい増えたとしても
同じ構造にできるメリットを考えたからです。

・単純な時に、わかりやすいからといって、複雑化したときに通用しない方法はしたくない

・単純な時も、複雑なときも、同様なやり方で対処したい

・その結果、単純な時に、ちょっと複雑なるのは、許容する

ような考え方でやってました。

if ($isOK) { のようにして、どれか１つでも、ダメだったら他はやらない
をしたかった。
１つ目のほうは、if ($isOK) { は不要だが
３つ、４つに増えたり、また、実行順序を入れ替える
などが、後で、しやすい構造にしたかったため
あえて、同期をとって、１つ目にも、if ($isOK) { をしていた。

それなら、ループの中だから、continueすればよいではないかと思うが
それだと、下に、追加実装がしにくくなる

要するにガード条件に相当するものをループの先頭位置で、
途中、continueするのであれば、後で、問題になりにくいが

ループの途中段階のやりたい系の処理部での事柄なので
後続で、やりたい系の仕様が増えたときに、

メンテしにくいから

if ($isOK) { の連打にしていた。

上記、構造ならば、いかようにも、柔軟に変更かのうなので

”””その結果、単純な時に、ちょっと複雑なるのは、許容する”””

の思考法をしていた



なのですが、

一旦は、

メソッドを定義して、そちらに移動しました。

メソッド内ならば、上記のcontinueの代わりに、

途中、returnで刻んでいけるからです。

メッセージ部分に関しては十分に短く

$this->error("Failed to chwon {$lockFilePath} to {$user}");
$this->error("Failed to chgrp {$lockFilePath} to {$group}");

これをまとめることは、しないでおきます。


*************************************************************
＜テスト、その１＞
*************************************************************
ロックファイルが無い状況で、
php artisan prepare:lock-files
を実行すると、
root所有で作られた
この状況で
php artisan prepare:lock-files www-data www-data
を実行すると
既にあるロックファイルが
www-dataの所有に変わった

root@0a1b985d97c1:/var/www/html/laravelapp# ls -l /var/www/html/laravelapp/storage/app/public
total 0
root@0a1b985d97c1:/var/www/html/laravelapp#
root@0a1b985d97c1:/var/www/html/laravelapp# php artisan prepare:lock-files
created at: /var/www/html/laravelapp/storage/app/public/avatar.lock
created at: /var/www/html/laravelapp/storage/app/public/post.lock
root@0a1b985d97c1:/var/www/html/laravelapp#
root@0a1b985d97c1:/var/www/html/laravelapp# ls -l /var/www/html/laravelapp/storage/app/public
total 0
-rw-rw-r--+ 1 root root 0 Sep 21 16:50 avatar.lock
-rw-rw-r--+ 1 root root 0 Sep 21 16:50 post.lock
root@0a1b985d97c1:/var/www/html/laravelapp#
root@0a1b985d97c1:/var/www/html/laravelapp# php artisan prepare:lock-files www-data www-data
already exists: /var/www/html/laravelapp/storage/app/public/avatar.lock
succeeded to chwon /var/www/html/laravelapp/storage/app/public/avatar.lock to www-data
succeeded to chgrp /var/www/html/laravelapp/storage/app/public/avatar.lock to www-data
already exists: /var/www/html/laravelapp/storage/app/public/post.lock
succeeded to chwon /var/www/html/laravelapp/storage/app/public/post.lock to www-data
succeeded to chgrp /var/www/html/laravelapp/storage/app/public/post.lock to www-data
root@0a1b985d97c1:/var/www/html/laravelapp#
root@0a1b985d97c1:/var/www/html/laravelapp#
root@0a1b985d97c1:/var/www/html/laravelapp# ls -l /var/www/html/laravelapp/storage/app/public
total 0
-rw-rw-r--+ 1 www-data www-data 0 Sep 21 16:50 avatar.lock
-rw-rw-r--+ 1 www-data www-data 0 Sep 21 16:50 post.lock
root@0a1b985d97c1:/var/www/html/laravelapp#
root@0a1b985d97c1:/var/www/html/laravelapp#

*************************************************************


*************************************************************
＜テスト、その２＞
*************************************************************
ロックファイルが無い状況で、
php artisan prepare:lock-files www-data www-data
を実行すると
www-dataの所有で作成された


root@0a1b985d97c1:/var/www/html/laravelapp# ls -l /var/www/html/laravelapp/storage/app/public
total 0
root@0a1b985d97c1:/var/www/html/laravelapp#
root@0a1b985d97c1:/var/www/html/laravelapp# php artisan prepare:lock-files www-data www-data
created at: /var/www/html/laravelapp/storage/app/public/avatar.lock
succeeded to chwon /var/www/html/laravelapp/storage/app/public/avatar.lock to www-data
succeeded to chgrp /var/www/html/laravelapp/storage/app/public/avatar.lock to www-data
created at: /var/www/html/laravelapp/storage/app/public/post.lock
succeeded to chwon /var/www/html/laravelapp/storage/app/public/post.lock to www-data
succeeded to chgrp /var/www/html/laravelapp/storage/app/public/post.lock to www-data
root@0a1b985d97c1:/var/www/html/laravelapp#
root@0a1b985d97c1:/var/www/html/laravelapp# ls -l /var/www/html/laravelapp/storage/app/public
total 0
-rw-rw-r--+ 1 www-data www-data 0 Sep 21 16:54 avatar.lock
-rw-rw-r--+ 1 www-data www-data 0 Sep 21 16:54 post.lock
root@0a1b985d97c1:/var/www/html/laravelapp#
root@0a1b985d97c1:/var/www/html/laravelapp#

*************************************************************

2024-09-22 02:51 UTC, yukihiroLaravel approved these changes

2024-09-22 02:51 UTC, merged