動作の確認依頼
yukihiroLaravel/joint_develop pull request #1243
Opened 2024-09-23 11:37 UTC by irochi1184

2024-09-29 01:25 UTC, yukihiroLaravel requested changes
ファイルサイズ上限を超えるケースについて
いくつかコメントしましたのでご確認ください！
https://www.loom.com/share/1095553508d14b788ad77bf7e96764ac

2024-09-29 01:25 UTC, yukihiroLaravel commented on app/Http/Middleware/CustomPostSizeMiddleware.php
> +            return redirect()->back()->withErrors(['image' => 'ファイルサイズが大きすぎます。最大50MBまでです。']);
$maxをサーバーから持ってきているなら
最大50MBという数字ではなく
$maxの値を利用して、
エラーメッセージをつくっても良いと思ったのですが
最大50MBに制限している理由はありますか？
（場合によっては50MBが嘘になってしまう可能性があるので）

2024-09-29 01:25 UTC, yukihiroLaravel commented on app/Http/Middleware/CustomPostSizeMiddleware.php
> +class CustomPostSizeMiddleware
Illuminate\Http\Exceptions\PostTooLargeException
を通ってしまうケースあり

2024-09-30 10:53 UTC, irochi1184 commented on app/Http/Middleware/CustomPostSizeMiddleware.php
> +            return redirect()->back()->withErrors(['image' => 'ファイルサイズが大きすぎます。最大50MBまでです。']);
最大50MBに制限している理由は特にありませんので
$maxの値を利用しようと思います！

2024-10-03 22:28 UTC, irochi1184 commented on app/Http/Middleware/CustomPostSizeMiddleware.php
> +class CustomPostSizeMiddleware
おっしゃる通りPostTooLargeExceptionのタイミングを加味すると
ミドルウェアでの実装では難しいと判断し、
JavaScriptでそもそものファイル選択自体を拒否する仕様に変更します！

2024-10-04 02:36 UTC, yukihiroLaravel approved these changes

2024-10-04 02:37 UTC, merged