#127 フォロー機能（西山しょうこ）
yukihiroLaravel/joint_develop pull request #1248
Opened 2024-09-25 13:42 UTC by Kujiran40

## issue
- Closes #127

## 概要
- フォロー機能

## 動作確認手順
- 中間テーブル 用のマイグレーションファイルを作成しました
- Adminerで、手動でfollowsテーブルにデータを追加（user1がuser2と3をフォロー等。）
- tinkerで App¥User::find(1)->follows; を実行すると、user2と3の情報が表示されたので、フォローできていることを確認。
- 全ての実装が終わった後、ローカルでログインしてみて、自分ではないユーザの詳細画面を表示させたときに、「フォローする」ボタンが表示され、フォローを実行すると今度は「フォローを外す」ボタンが表示されることを確認。Adminerでもデータが追加されたり消されたりすることを確認。

## 確認して欲しいこと
今回はLaravel応用講座５の「いいね機能」の大半を利用したのと、プラスで自分が調べたことを合算してコーディングしました。動作確認では成功ですが、フォローする方もされる方も「ユーザ（user）」なので、書きながらこんがらがってしまうことが多かったです。余計なコードを書いていたり、変数やその他のネーミング等、おかしいところありませんでしょうか？

2024-09-25 15:10 UTC, yukihiroLaravel requested changes
素晴らしい出来ですね！
細かい点を指摘させていただきましたのでご確認ください！
https://www.loom.com/share/5e6265d08b7548169080b05ca2936874

2024-09-25 15:10 UTC, yukihiroLaravel commented on app/Http/Controllers/FollowController.php
> +    }
空行

2024-09-25 15:10 UTC, yukihiroLaravel commented on database/migrations/2024_09_25_113042_create_follows_table.php
> +            $table->timestamps();
timestampは最後に置く場合が多い

2024-09-26 00:02 UTC, Kujiran40 commented on app/Http/Controllers/FollowController.php
> +    }
承知しました！

2024-09-26 00:02 UTC, Kujiran40 commented on database/migrations/2024_09_25_113042_create_follows_table.php
> +            $table->timestamps();
修正完了しました！

2024-09-27 00:15 UTC, yukihiroLaravel approved these changes

2024-09-27 00:15 UTC, merged