投稿の検索機能（途中経過）
yukihiroLaravel/joint_develop pull request #1254
Opened 2024-10-03 23:57 UTC by Kujiran40

## issue
- 投稿の検索機能（途中経過）

## 概要
- 進捗は実装したかったことの半分程ですが、現状できたところまでを一旦プルリク上げます。

## 現時点で実装できたこと・動作確認
- ログイン前・ログイン後　共にヘッダーの一番右端に「検索フォーム」と「投稿を検索」ボタンの表示
- あいまい検索を可能とした
- ログイン前・ログイン後それぞれ、以下の①～③をローカルにて手動確認
　①存在するキーワードを入力：該当する投稿のみが全て表示される。検索フォームには、入力キーワードが保持される。2ページ目へ続く場合にも、URL・検索フォーム内のどちらにも検索キーワードを保持したまま遷移し、ちゃんと該当する投稿が表示できた。
　②存在しないキーワードを入力：何も表示されない（エラーにもならない）
　③検索フォームに何も入力せず、検索ボタンを押す：投稿が全件、表示される

## 懸念点
- 思い描いていたことがピンポイントでネット検索で見つからない場合、どうしてもAIに頼りがちになり、どんどんAIに質問をしてコードを追加していくたびに辻褄が合わなくなったり、今まで正常に動いていたところにもエラーが増えてくるようになり、頭がパニックになり諦めてしまった。実力不足、知識不足を実感しているところです。
null、empty、空、値がない（？）、issetじゃない（？）…等の「入力されていない」・「存在しない」あたりの本当の意味が理解できなさすぎてコーディングの仕方がわからない。

## 本当は実装したかったこと
- 上記①の場合、該当する投稿の一番上に「｛キーワード｝を含む投稿が見つかりました」を表示
- 上記②の場合、投稿が表示されるはずだった場所に「｛キーワード｝を含む投稿が見つかりません…」を表示
- 上記③の場合、「キーワードを入力してください」を表示
　しっかりと理解できていないまま、if文を使って複雑な条件分岐をしてしまった。トップページ（web.blade.php）にどんどんコードを追加していくたびに複雑になってエラーも増えてきたので、諦めて全て削除しました。

現状で方向性は合っているのか、また、実装したかったことを実現するためのアドバイス等をいただきたいです。
よろしくお願いいたします。

2024-10-04 02:45 UTC, yukihiroLaravel requested changes
参考：PHP isset, empty, is_null の違い早見表
https://qiita.com/shinichi-takii/items/00aed26f96cf6bb3fe62

2024-10-04 02:45 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
> +                  </li>
endifの後に書けば二重に書かなくても済む？

2024-10-04 02:45 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +<div class="m-auto" style="width: fit-content">{{ $posts->appends(['keyword' => request()->input('keyword')])->links('pagination::bootstrap-4') }}</div>
appendsいいですね

2024-10-04 02:45 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('searchPosts', 'PostsController@searchPosts')->name('searchPosts');
トップページのルーティング削除したほうがいい

2024-10-04 03:10 UTC, yukihiroLaravel requested changes
動くものとしては素晴らしくできていると思いますよ！
あとは悩まれている点についてのアドバイスです⇩

2024-10-04 03:10 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        }
クエリビルダを使ってみる
https://zenn.dev/naoki_oshiumi/articles/e8821b32524275

2024-10-04 03:10 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +@endphp
if ($keyword == "" || $keyword == NULL) {
   　// ③ キーワードを入力してください
} else {
   　 if (count($posts) > 0) {
    　　// ①｛キーワード｝で検索しました
　　} else {
    　　// ②｛キーワード｝を含む投稿が見つかりません…
　　}
}

2024-10-04 03:10 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +    $keyword = $keyword ?? '';
下記の場合、不要？

2024-10-04 03:10 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('searchPosts', 'PostsController@searchPosts')->name('searchPosts');
UsersControllerのindexメソッド削除

2024-10-06 14:11 UTC, Kujiran40 commented on app/Http/Controllers/PostsController.php
> +        }
資料ありがとうございます！今後、使いながら少しずつ理解していきたいです。
if($var) と empty が真逆、isset と is_null が真逆、という感じでおもしろいです。

2024-10-06 14:12 UTC, Kujiran40 commented on resources/views/commons/header.blade.php
> +                  </li>
確かに言われてみれば…！！気が付きませんでした、ありがとうございます👍

2024-10-06 14:52 UTC, Kujiran40 commented on routes/web.php
> +Route::get('searchPosts', 'PostsController@searchPosts')->name('searchPosts');
1つにまとめました！

2024-10-07 01:04 UTC, Kujiran40 commented on resources/views/welcome.blade.php
> +@endphp
ありがとうございます、自分ではこのi_(._.)_f文を調べたり考えたりするところまでたどり着けなかったので、そのまま使わせていただきました！！_(._.)_
「”” 又は NULL」 は、なんとなく今後もセットで使ってくいくことが多いのかな？と感じました。

トップページだけを表示したい（検索していない）場合でも、「キーワードを入力してください」と出ていたので、さらに最初の条件として「検索ボタンが押されたかどうか」というのも付け加えました💡

自分へのメモ 兼 チームメンバーへの説明のため、各ページにコメントアウトの日本語文字が多くなってしまっています。

2024-10-07 01:19 UTC, Kujiran40 commented on resources/views/welcome.blade.php
> +    $keyword = $keyword ?? '';
はい、下のほうで登場したのでこちら削除しました！

2024-10-07 11:28 UTC, yukihiroLaravel requested changes
よくなり完璧に近づきましたね✨
少しだけコメントしましたのでご確認ください！

2024-10-07 11:28 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        return view('welcome', compact('posts', 'keyword', 'submitted'));
他の部分と合わせて
compactは使わず配列形式でviewに渡すようにしましょう

2024-10-07 11:28 UTC, yukihiroLaravel commented on routes/web.php
> +// Route::get('/', 'UsersController@index')->name('user.index');
こちらコメントアウトではなく、削除してしまったほうがいいと思いますよ！

2024-10-07 11:41 UTC, Kujiran40 commented on routes/web.php
> +// Route::get('/', 'UsersController@index')->name('user.index');
削除しました！

2024-10-07 11:41 UTC, Kujiran40 commented on app/Http/Controllers/PostsController.php
> +        return view('welcome', compact('posts', 'keyword', 'submitted'));
承知しました！

2024-10-07 13:04 UTC, yukihiroLaravel requested changes

2024-10-07 13:04 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        return view('welcome', ['posts' => $posts, 'keyword' => $keyword, 'submitted' => $submitted]);
[
　　'posts' => $posts,
　　'keyword' => $keyword,
　　'submitted' => $submitted
]

2024-10-07 13:04 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +    } */
削除

2024-10-07 13:24 UTC, Kujiran40 commented on app/Http/Controllers/UsersController.php
> +    } */
削除しました！

2024-10-07 13:24 UTC, Kujiran40 commented on app/Http/Controllers/PostsController.php
> +        return view('welcome', ['posts' => $posts, 'keyword' => $keyword, 'submitted' => $submitted]);
ありがとうございます！

2024-10-08 03:03 UTC, yukihiroLaravel approved these changes

2024-10-08 03:03 UTC, merged