予約投稿機能(有田)
yukihiroLaravel/joint_develop pull request #1260
Opened 2024-10-07 00:31 UTC by irochi1184

## issue
- Closes #1259 

## 概要
- 予約投稿機能

## 動作確認手順

- [ ] `joint_develop_docker/Docker/App/Dockerfile` を以下のように修正し、サーバー上でcronを使えるようにする
```dockerfile
FROM php:7.4-apache

ADD php.ini /usr/local/etc/php/
ADD 000-default.conf /etc/apache2/sites-enabled/

RUN cd /usr/bin && curl -s http://getcomposer.org/installer | php && ln -s /usr/bin/composer.phar /usr/bin/composer

RUN apt-get update \
&& apt-get install -y \
git \
zip \
unzip \
vim \
libpng-dev \
libpq-dev \
cron \
&& docker-php-ext-install pdo_mysql

RUN mv /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled
RUN /bin/sh -c a2enmod rewrite

CMD cron && apache2-foreground
```
- [ ] 以下の手順でDocker環境を再ビルドする
  - `docker-compose down`
  - `docker-compose build`
  - `docker-compose up -d`

- [ ] `php artisan migrate`を実行する
- [ ] `crontab -e`コマンドにて以下の行を追加する※
  - `* * * * * /usr/local/bin/php /var/www/html/laravelapp/artisan schedule:run >> /dev/null 2>&1`

> [!IMPORTANT]
> ※Dockerコンテナの再ビルドの度に設定し直す必要あり

### 参考イメージ
<img width="1440" alt="スクリーンショット 2024-10-07 9 30 38" src="https://github.com/user-attachments/assets/52845dd9-6d5c-405f-b6a0-b61ac8e5e56c">

## 考慮して欲しいこと
- 特になし

## 確認して欲しいこと
- 特になし

2024-10-07 13:46 UTC, yukihiroLaravel requested changes
いくつか指摘しました！

また、今のままだと
postシーダーに入っているデータがすべて
is_published が0のままになり、ずっと表示されないと思いますので
初期値から1になるようにしましょう。

2024-10-07 13:46 UTC, yukihiroLaravel commented on database/migrations/2024_10_04_120736_add_scheduled_at_to_posts_table.php
> +}
マイグレーションファイルをis_publishedと分ける必要性が感じられないので
統合しましょう！

2024-10-07 13:46 UTC, yukihiroLaravel commented on database/migrations/2024_10_06_050416_add_is_published_to_posts_table.php
> +}
マイグレーションファイルをscheduled_atと分ける必要性が感じられないので
統合しましょう！

2024-10-08 05:20 UTC, irochi1184 commented
> いくつか指摘しました！
> 
> また、今のままだと postシーダーに入っているデータがすべて is_published が0のままになり、ずっと表示されないと思いますので 初期値から1になるようにしましょう。

シーダーのデータ全て is_published がtrue (1)になるように修正しました！

2024-10-08 05:20 UTC, irochi1184 commented on database/migrations/2024_10_04_120736_add_scheduled_at_to_posts_table.php
> +}
承知しました。
統合して対応させていただきます。

2024-10-08 05:20 UTC, irochi1184 commented on database/migrations/2024_10_06_050416_add_is_published_to_posts_table.php
> +}
承知しました。
統合して対応させていただきます。

2024-10-08 10:03 UTC, yukihiroLaravel approved these changes

2024-10-08 10:04 UTC, merged