#1261 返信機能(ゆうじ)
yukihiroLaravel/joint_develop pull request #1269
Opened 2024-10-12 17:30 UTC by yujiLaravel

## issue
- Closes #1261

## 概要
- 投稿への返信機能を実装

## 動作確認手順
- 下記コマンドを実行
```
php artisan migrate
```

- 下記の手順で動作確認を実行する

①Adminerにて`replies`テーブルが追加されることを確認。
http://localhost:8088/?server=db&username=dbuser&db=laraveldb&table=replies

②http://localhost:8080/ にて投稿内容の下部にあるコメントボタンを押下すると返信画面に遷移することを確認。

③新規ユーザー登録かログインを行い、ログイン状態で返信画面のテキストボックスに返信内容を入力し、コメントするボタンを押下すると返信内容が返信画面に正しく表示されることを確認。

④ユーザ名のリンク、戻るボタン、削除ボタン等の機能も問題なく動作することを確認。

### 考慮して欲しいこと

- 状況に応じて、下記コマンドで確認する必要あり
```
php artisan migrate:fresh --seed
```

## 確認して欲しいこと
なし

2024-10-12 18:58 UTC, yukihiroLaravel requested changes
細かいところまで配慮されていて
素晴らしいですね！

ほぼOKだと思いますが細かい点のみ指摘させていただきましたのでご確認願います！

2024-10-12 18:58 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +            return redirect()->back()->with('error', 'コメントの削除に失敗しました');
インデント
左にスペース４つ分移動

2024-10-12 18:58 UTC, yukihiroLaravel commented on routes/web.php
> +
不要な空行だと思います！

2024-10-12 18:58 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::delete('reply/{reply}', 'PostsController@deleteReply')->name('reply.delete');
ルートモデルバインディングを使われていていいですね！

2024-10-13 02:55 UTC, yujiLaravel commented on app/Http/Controllers/PostsController.php
> +            return redirect()->back()->with('error', 'コメントの削除に失敗しました');
修正しました。

2024-10-13 02:55 UTC, yujiLaravel commented on routes/web.php
> +
削除しました。

2024-10-13 02:56 UTC, yujiLaravel commented on routes/web.php
> +        Route::delete('reply/{reply}', 'PostsController@deleteReply')->name('reply.delete');
便利なので上手く使っていきたいです！

2024-10-13 17:33 UTC, yukihiroLaravel requested changes
１点修正ねがいます！

2024-10-13 17:33 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        return redirect()->back()->with('success', 'コメントを削除しました');
ここは修正する必要がなかったです💦
戻して、右にスペース4つ分インデントを移動させましょう！

2024-10-14 01:29 UTC, yujiLaravel commented on app/Http/Controllers/PostsController.php
> +        return redirect()->back()->with('success', 'コメントを削除しました');
失礼しました！修正いたしました。

2024-10-14 02:18 UTC, yukihiroLaravel approved these changes

2024-10-14 02:18 UTC, merged