#115　ユーザー詳細（小宮山）
yukihiroLaravel/joint_develop pull request #1286
Opened 2024-10-27 07:08 UTC by Neito5865

## issue
 - Closes #115 

## 概要
 - ユーザー詳細

## 動作確認手順
 - 下記へURLへアクセス。（URL末尾の数字がユーザーID、存在しないIDの場合404エラー表示となる）
 http://localhost:8080/users/1

## 考慮してほしいこと
 - 投稿一覧は他のメンバーのタスクと認識しており、作成していません。bladeファイルでは影響する部分をコメントアウトしています。

## 確認してほしいこと

2024-10-27 14:18 UTC, yukihiroLaravel requested changes
存在しないユーザ番号があったときの対応含めて
とてもいいですね！

ただ、おぎどうさんとファイルがかぶる件で
少しありましたのでご確認ください！

2024-10-27 14:18 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +            {{-- @include('posts.posts', ['user' => $user, 'posts' => $posts]) --}}
このposts.bladeは現時点でないですが、
お手数ながら小宮山さんがつくってしまっていいと思いますが
いかがでしょうか？

もしオギドウさんがこのファイルをつくられているのであれば
そのファイルをSlackなどでファイルごと渡してもらって
小宮山さんの環境でファイルごと反映してもいいかと思いました！

2024-10-27 14:18 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="" class="nav-link {{ Request::is() ? 'active' : '' }}">タイムライン</a></li>
Request::is()
↑このカッコの中にはすでにURLを記述すべきかと思います！

2024-10-27 14:18 UTC, yukihiroLaravel commented on app/Post.php
> +<?php
このファイルつくるのは問題ないですね！
オギドウさんと被っている懸念はあるので確認したほうがいいかもしれないですが
作らないと進まないと思いますので
「こんな感じでつくりました」と共有しておけばOKかと思います！

2024-10-28 11:40 UTC, Neito5865 commented on app/Post.php
> +<?php
荻堂さんと共有いたしました。

2024-10-28 11:40 UTC, Neito5865 commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="" class="nav-link {{ Request::is() ? 'active' : '' }}">タイムライン</a></li>
記述追加しました。

2024-10-29 04:00 UTC, Neito5865 commented on resources/views/users/show.blade.php
> +            {{-- @include('posts.posts', ['user' => $user, 'posts' => $posts]) --}}
こちら、荻堂さんが作成されていたので共有していただきました。

2024-10-29 04:00 UTC, Neito5865 commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="" class="nav-link {{ Request::is() ? 'active' : '' }}">タイムライン</a></li>
記述しました。

2024-10-29 05:16 UTC, yukihiroLaravel requested changes
１点だけ指摘しました！
ご確認お願いします！

2024-10-29 05:16 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +{{ $posts->links('pagination::bootstrap-4') }}
おぎどうさんにもお伝え済みなのですが、
ページネーションを正しい配置とするためには、
```
<div class="m-auto" style="width: fit-content">{{ $posts->links('pagination::bootstrap-4') }}</div>
```
こうする必要がありますので
修正しましょう！

2024-10-29 06:16 UTC, Neito5865 commented on resources/views/posts/posts.blade.php
> +{{ $posts->links('pagination::bootstrap-4') }}
見落としていました。。
修正いたしました！

2024-10-29 12:50 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした！！

2024-10-29 12:50 UTC, merged