#115 ユーザ詳細 (Shinya)
yukihiroLaravel/joint_develop pull request #1287
Opened 2024-10-27 15:35 UTC by Shinya-Nakaguchi

## Issue
- Closes #115 

## 概要
- ユーザ詳細
	
## 動作確認手順
- URLへhttp://localhost:8080/users/id を入力
- URLのuser idに対応したuser名が表示されることを確認
- アイコンが表示されることを確認
- ログインユーザのみ”ユーザ情報の編集”が表示されることを確認
- タイムラインがActiveになっていることを確認
	
## 考慮して欲しいこと

## 確認して欲しいこと

2024-10-28 02:08 UTC, yukihiroLaravel requested changes
ほぼ完璧ですね！！

少しコメントしましたのでご確認ください！

2024-10-28 02:08 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $data=[
細かいですが、
コーディング規約的に下記のようにスペースを入れた方がいいかと思います！
$data = [

2024-10-28 02:08 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +    </div>
このあたりにユーザ本人の投稿が表示されるよう
posts.blade.phpを配置しましょう。

ご理解されているかもしれませんが、
いずみさんが同じファイルを作っているため同じファイルを作るとコンフリクトが起きる可能性がありますが
下記のファイルから内容を完全にコピーしてくれば、
コンフリクトはほぼ起きないのでそのようにしましょう！

https://github.com/yukihiroLaravel/joint_develop/pull/1282/files

2024-10-28 12:10 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +    </div>
最新developをマージする

2024-10-28 15:01 UTC, Shinya-Nakaguchi commented on app/Http/Controllers/UsersController.php
> +        $data=[
修正いたしました！

2024-10-28 15:11 UTC, Shinya-Nakaguchi commented on resources/views/users/show.blade.php
> +    </div>
最新developをmerge後に、posts.blade.phpをusers/show.blade.phpの中に配置しました!

添付画像のcomposer.lockのconflictをどのように解消すれば良いかよく分かっておりません。
versionが新しい方をacceptすれば良いでしょうか？
<img width="740" alt="Screenshot 2024-10-28 at 23 56 36" src="https://github.com/user-attachments/assets/ff369ec8-c304-434c-950d-acb6f3873bb1">
<img width="962" alt="Screenshot 2024-10-28 at 23 55 57" src="https://github.com/user-attachments/assets/0fbee539-ac56-410d-b7dd-35e294bfeb8b">

2024-10-28 23:45 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +    </div>
いえ、HEADが自分の変更で
develop_aがいずみさんのすでにされている変更だと思いますので
いずみさんの変更の方を生かしましょう！

2024-10-29 15:24 UTC, Shinya-Nakaguchi commented on resources/views/users/show.blade.php
> +    </div>
ありがとうございます！
incoming changes をacceptしました！

2024-10-29 21:42 UTC, yukihiroLaravel approved these changes

2024-10-29 21:43 UTC, merged