#113 トップページの投稿表示 (オギドウ）
yukihiroLaravel/joint_develop pull request #1290
Opened 2024-10-28 13:31 UTC by takeshi-ogido

## issue
- Closes #113 

## 概要
- #113 トップページの投稿表示 (オギドウ）

## 動作確認手順
・データベースに仮情報を入れて、データを取得し、トップページの表示が確認できた。
php artisan migrate->php artisan db:seed --class=UsersTableSeeder->php artisan db:seed --class=PostsTableSeeder
シーダーで実装。

・Adminerでpostsテーブルに15個のレコードが保存されていることを確認後、15個の投稿をページネーションを用いて表示できた

## 考慮して欲しいこと

## 確認して欲しいこと
きちんとしたコードで書けているかの確認をお願いします！

2024-10-29 03:54 UTC, yukihiroLaravel requested changes
大筋はOKですが
動作確認不足の点がいくつかありましたので
修正願います！

お願いいたします！

2024-10-29 03:54 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +{{ $posts->links('pagination::bootstrap-4') }}
ページネーションを正しい配置とするためには、
```
<div class="m-auto" style="width: fit-content">{{ $posts->links('pagination::bootstrap-4') }}</div>
```
こうする必要がありますね

2024-10-29 03:54 UTC, yukihiroLaravel commented on app/User.php
> +    }
作成するならメソッド名は
postsが正しいと思うのと、
前提として現段階で使用していないメソッドを記述しておくのは
ミスがあった場合危険なので一旦削除しておきましょう！

2024-10-29 03:54 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        ]);
return view('welcome', [
       　 'posts' => $posts,
]);

このように書くのが通常ですね！

2024-10-29 03:54 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +                    <p class="text-muted">{{$post->create_at}}</p>
データベース（Adminer）上で操作するなどして
動作確認されましたか？

これだと綴りが間違っていて投稿時間が表示されません。
$post->create_at
ではなく
$post->created_at
です

2024-10-29 03:54 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +        @if(Auth::check() && Auth::id() === $post->user_id)
ログインした状態で動作確認したら
$post がnot foundとエラーが出ますね。
動作確認不足です！

同じ状態を再現してエラーを解消しましょう

2024-10-30 05:04 UTC, takeshi-ogido commented on resources/views/posts/posts.blade.php
> +{{ $posts->links('pagination::bootstrap-4') }}
正しい位置に移動させました。

2024-10-30 05:06 UTC, takeshi-ogido commented on resources/views/welcome.blade.php
> +        @if(Auth::check() && Auth::id() === $post->user_id)
ログイン後に投稿画面の表示確認できました。
確認済みです。

2024-10-30 10:03 UTC, yukihiroLaravel requested changes
すべて変わっていないです！
files changed のGitHubプルリク上のタブをpush後にきちんと見ましょう！

そしてコンフリクトも発生していますので解消ください。

また、修正の場合はslackでの連絡はスレッド上でお願いします！

2024-10-30 10:03 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        ]);
こちら変わっていないです！
files changed のGitHubプルリク上のタブをpush後にきちんと見ましょう！

2024-10-30 10:03 UTC, yukihiroLaravel commented on app/User.php
> +    }
消えていません！

2024-10-30 10:03 UTC, yukihiroLaravel commented on composer.json
> +}
composer.json
composer.lock
ともにうまくいけば差異がこちらに出てこない形になるはずです！

2024-10-30 10:03 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +                    <p class="text-muted">{{$post->create_at}}</p>
変わっていません！

2024-10-30 10:03 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +{{ $posts->links('pagination::bootstrap-4') }}
変わっていません！

2024-10-30 10:03 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +        @if(Auth::check() && Auth::id() === $post->user_id)
変わっていません！

2024-10-30 11:30 UTC, takeshi-ogido commented on composer.json
> +}
そのまんまコピペして触ってないのですが、この差異は}の位置がズレているということでしょうか？

2024-10-30 13:56 UTC, yukihiroLaravel requested changes
またいくつか指摘しました！
ご確認ください！

2024-10-30 13:56 UTC, yukihiroLaravel commented on composer.json
> +}
おそらく改行コードの微妙な違いにより別のものと認識されているようですが
違いはないためcomposer.jsonはこれで大丈夫です！

ただ、これとは別ファイルですが
composer.lock は大きく違いが出てしまっているようなので
下記をもう一度コピペした上で
add とcommit してpush してください！

・composer.lock
https://github.com/yukihiroLaravel/joint_develop/blob/develop_b_kannaduki_dra/composer.lock

2024-10-30 13:56 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +        </div>
今気づきましたが
ここを記述するのなら
下記のエラーメッセージbladeをincludeした方がよくないですか？

https://github.com/yukihiroLaravel/joint_develop/blob/develop_b_kannaduki_dra/resources/views/commons/error_messages.blade.php

2024-10-30 13:56 UTC, yukihiroLaravel commented on app/User.php
> -    }
すみません、こちら状況変わりまして、
小宮山さんが自分で作られて今はマージされているようなので
消してしまうとまずいですね・・・！

2024-10-31 02:32 UTC, takeshi-ogido commented on resources/views/welcome.blade.php
> +        </div>
・composer.lockコピペし直しました！

・エラーメッセージを＠includeしました！

2024-10-31 02:34 UTC, takeshi-ogido commented on app/User.php
> -    }
コードコピペし直しました！

2024-10-31 20:56 UTC, yukihiroLaravel approved these changes
composer.lockはこれでOKです！

ただ、またコンフリクトが起きていますので
再度お手数ですが対応願います！

2024-11-01 14:18 UTC, yukihiroLaravel approved these changes
マージしました！
おつかれさまでした！！

2024-11-02 05:12 UTC, merged