#123 投稿編集画面（小宮山）
yukihiroLaravel/joint_develop pull request #1294
Opened 2024-10-30 06:14 UTC by Neito5865

## issue
 - Closes #123 

## 概要
 - 投稿編集画面・更新

## 動作確認手順
 - トップページへアクセスし、以下ユーザーでログインを行う。
トップページ：http://localhost:8080/
メールアドレス：user1@test.com
パスワード：password

 - ヘッダーナビゲーションのユーザー名が表示されているところをクリックして、ユーザー詳細ページへ移動。

 - ユーザー詳細のタイムライン上の投稿のいずれかの編集ボタンをクリック。

 - 入力フォームに文字を入力後、更新するボタンをクリックすると処理が実行される。
何も文字を入力しなかった場合と140文字以上入力した場合、バリデーション機能でエラーメッセージが表示される。
成功した場合、トップページに遷移する。

 - Adminerでpostsテーブルのcontentカラムの値が変更されていることを確認。
 
 - 補足
投稿編集ページのURL（http://localhost:8080/posts/1/edit）のposts/の後の数字がpostsテーブルのidを表す。存在しないidの場合は404エラー表示となる。

## 考慮してほしいこと
特にありません。

## 確認してほしいこと
特にありません。

2024-10-30 09:50 UTC, yukihiroLaravel requested changes
かなり素晴らしいですが
少しコメントしました！
ご確認ください！

2024-10-30 09:50 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('/', 'PostsController@index')->name('index');
indexより統一性的に
post.index
という名前の方がいいかと思います！

2024-10-30 09:50 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +    public function update(PostRequest $request, $id){
改行位置をここにしましょう
```
public function update(PostRequest $request, $id)
{
```

2024-10-30 09:50 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +                    <p class="mb-2">{!! nl2br(e($post->content)) !!}</p>
改行コードを含む対応ありがとうございます！

2024-10-30 09:50 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +            'user' => $user,
こちら$user使っていなくないでしょうか？

2024-10-30 09:50 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $user = \Auth::user();
こちら$user使っていなくないでしょうか？

2024-10-31 06:22 UTC, Neito5865 commented on app/Http/Controllers/PostsController.php
> +            'user' => $user,
確かに！使ってなかったです！
削除しました。

2024-10-31 06:23 UTC, Neito5865 commented on app/Http/Controllers/PostsController.php
> +        $user = \Auth::user();
削除しました！

2024-10-31 06:23 UTC, Neito5865 commented on routes/web.php
> +Route::get('/', 'PostsController@index')->name('index');
承知しました！修正しました。

2024-10-31 06:24 UTC, Neito5865 commented on app/Http/Controllers/PostsController.php
> +    public function update(PostRequest $request, $id){
修正しました。

2024-10-31 09:30 UTC, yukihiroLaravel approved these changes
OKですのでマージしました！
おつかれさまでした！！

2024-10-31 09:31 UTC, merged