#117 ユーザ編集画面・更新(いずみ)
yukihiroLaravel/joint_develop pull request #1296
Opened 2024-10-31 17:31 UTC by izumi-sakamoto

## issue
- Closes #117 

## 概要
- ユーザ編集画面の表示と更新

## 動作確認
- http://localhost:8080/signup
から、ユーザを1人新規作成( id:11 )。
- http://localhost:8080/users/11/edit 
(id11のユーザ詳細画面)に遷移後、ユーザ名、メールアドレスのどちらか、または両方に変更を加え更新ボタンを押し「ユーザ情報が更新されました。」と表示されることを確認。
- 変更が実行された場合に「閉じる」ボタン、変更が実行されていない場合は「戻る」ボタンが表示されることを確認。
- 「閉じる」または「戻る」ボタンを押し、ユーザ詳細画面に遷移することを確認。

## 考慮してほしいこと

## 確認してほしいこと

2024-10-31 21:44 UTC, yukihiroLaravel requested changes
いくつかコメントしましたので
ご確認願います！

2024-10-31 21:44 UTC, yukihiroLaravel commented on routes/web.php
> +// });
今のログイン機能がない状態でテストをするのなら
新規ユーザ登録した状態でテストをすればいいので
このコメントアウトは外しておいていいと思いますよ！

2024-10-31 21:44 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        return view('users.edit', $date);
このファイルではありませんが
ユーザ詳細画面の
"ユーザ情報の編集"ボタンを押した時に
編集画面に遷移してくるようにしましょう！

2024-10-31 21:44 UTC, yukihiroLaravel commented on resources/views/users/edit.blade.php
> +    @endif
ここはすでに存在する下記ファイルを使いましょう！https://github.com/yukihiroLaravel/joint_develop/blob/develop_a_kannaduki_dra/resources/views/commons/error_messages.blade.php

2024-10-31 21:44 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        ]);
お手本だと、更新後ユーザ詳細ページに遷移するように
なっていると思いますので
そのように対応しましょう！

2024-10-31 21:44 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +            'updated' => $updated
この$updatedが
trueだろうとfalseだろうと無関係だと思いますので
全て$updatedは不要ではないでしょうか？

2024-10-31 21:44 UTC, yukihiroLaravel commented on app/Http/Requests/UserRequest.php
> +            'email' => ['nullable', 'string', 'email', 'max:255'],
この状態だと、他ユーザとメールが被ったときに
Integrity constraint violation
というエラーが出てしまうのでバリデーションにてそれを回避できるようにしましょう。

また、上記の対応をすると
更新者本人のメアドと被ったときもバリデーションエラーが出てしまうことになるのですが
実はそれを回避する方法もあるので少し考えてみてください！

2024-11-01 16:59 UTC, izumi-sakamoto commented on routes/web.php
> +// });
コメントアウト外しました！

2024-11-01 17:02 UTC, izumi-sakamoto commented on app/Http/Controllers/UsersController.php
> +        return view('users.edit', $date);
resources/views/users/show.blade.php　の14行目に追記しました！

2024-11-01 17:07 UTC, izumi-sakamoto commented on resources/views/users/edit.blade.php
> +    @endif
resources/views/layouts/app.blade.php　の12行目にエラーメッセージを追記し、resources/views/users/edit.blade.php　の1行目の　@extends('layouts.app')　に埋め込むようにしようと考えたのですが、考え方と実装方法が合っているのか自信がありません。

2024-11-01 17:09 UTC, izumi-sakamoto commented on app/Http/Controllers/UsersController.php
> +        ]);
対応しました！
更新後ユーザ詳細ページに遷移することで、前回私が実装していた「閉じる」「戻る」ボタンは必要ないと思い削除しました。

2024-11-01 17:12 UTC, izumi-sakamoto commented on app/Http/Controllers/UsersController.php
> +            'updated' => $updated
削除しました！
更新をしない項目があった場合の切り分けが必要かと思い、$updatedを加えてしまいました。

2024-11-01 17:15 UTC, izumi-sakamoto commented on app/Http/Requests/UserRequest.php
> +            'email' => ['nullable', 'string', 'email', 'max:255'],
現在のユーザIDを除外してバリデーションルールを設定する方法を調べて実装してみましたが
こちらも自信がないです。

2024-11-01 17:27 UTC, izumi-sakamoto commented
ここでは関係ないですが、エラーが発生していた箇所があったので
resources/views/posts/posts.blade.php　の6行目を修正しております。

2024-11-02 05:10 UTC, yukihiroLaravel requested changes
概ねOKですが、
少し変えないといけない部分に気づきましたのでご確認ください！

2024-11-02 05:10 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $date = [
今気づきましたが、
$dateではなく$dataが正しいのと
あとviewに渡す変数が１つでしたら、とくに$dataという
複数をまとめる変数に入れ直す必要性はないかな、と思います！

2024-11-02 05:10 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $user = User::findOrFail($id);
指摘もれていましたが、
今の状態ですと、本人以外のユーザが
ユーザ編集ページにアクセスできてしまいますので
（たとえば、user1でログインしているのに、
　/users/2/editというURLを直接打てばアクセスできてしまう）
本人以外がアクセスした際にエラーを出すようにしましょう。

エラーの出し方のヒントとしては下記の１行のコードです。
```
abort(403);
```

2024-11-02 05:10 UTC, yukihiroLaravel commented on app/Http/Requests/UserRequest.php
> +            'email' => ['nullable', 'string', 'email', 'max:255', 'unique:users,email,'. $this->id],
この書き方でOKです！

2024-11-02 05:10 UTC, yukihiroLaravel commented on resources/views/users/edit.blade.php
> +        @include('commons.error_messages')
この書き方でOKです！

app.blade.phpにエラーメッセージを置いてもいいのですが
それだとお手本と同じ位置にエラーが出なくなってしまいますので
この位置の方がよりいいと思います！

2024-11-02 17:30 UTC, izumi-sakamoto commented
ご確認ありがとうございました。
３つプッシュしておりますが、１つ目は最新のdevelopをマージする際のコンフリクトの解消で、２つ目をプッシュ後ミスに気付いたので３つ目をプッシュいたしました。プッシュ前にミスがないように気を付けます。

2024-11-02 19:01 UTC, yukihiroLaravel requested changes
１点だけコメントしました！

2024-11-02 19:01 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $user = \Auth::user();
下記のように書くのであれば
この$userは機能していないので消しましょう！

2024-11-02 19:01 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $user = User::findOrFail($id);
これでOKです😆

2024-11-03 11:59 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +
$user = User::findOrFail($request->id);

2024-11-03 12:01 UTC, yukihiroLaravel approved these changes
マージしました！

2024-11-03 12:01 UTC, merged