#123 投稿編集画面・更新 (Shinya)
yukihiroLaravel/joint_develop pull request #1297
Opened 2024-11-01 15:14 UTC by Shinya-Nakaguchi

## Issue
- Closes #123 

## 概要
- 投稿編集画面・更新
	
## 動作確認手順
- "編集する"ボタンから編集ページへ遷移することを確認
- 投稿を入力し、"更新する"ボタンを押すと、投稿が更新され、トップページへ遷移することを確認
- 140字以上でエラーが出ることを確認
	
## 考慮して欲しいこと

## 確認して欲しいこと

2024-11-02 04:51 UTC, yukihiroLaravel requested changes
いくつかコメントしたのと
他タスクマージの関係でweb.phpにてコンフリクト発生しましたので
お手数ながら解消お願いします！

2024-11-02 04:51 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $data=[
コーディング規約的には
$data = [
このようにスペースを入れましょう！

2024-11-02 04:51 UTC, yukihiroLaravel commented on app/Http/Requests/PostRequest.php
> +            'content' => 'max:140',
これだと投稿内容が何もないときもエラーが出ず
承認されてしまわないでしょうか？
お手本だとそうなっていないと思いますのでご確認ください！

2024-11-02 04:51 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $user = \Auth::user();
$userを使っていないのではないでしょうか？

2024-11-02 04:51 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +            'user' => $user,
$userを使っていないのではないでしょうか？

2024-11-02 04:51 UTC, yukihiroLaravel commented on routes/web.php
> +
こちら無駄に空白が空きすぎているので
特に意味がなければ２行の無駄な空行消しましょう！

2024-11-02 04:51 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('/', 'PostsController@index')->name('index');
nameは
post.index
の方が他との統一性的に相応しいかもしれません！

2024-11-02 05:49 UTC, Shinya-Nakaguchi commented on app/Http/Controllers/PostsController.php
> +        $data=[
スペースを入れました！

2024-11-02 05:49 UTC, Shinya-Nakaguchi commented on app/Http/Requests/PostRequest.php
> +            'content' => 'max:140',
配列形式でrequiredを追加しました！

2024-11-02 05:50 UTC, Shinya-Nakaguchi commented on app/Http/Controllers/PostsController.php
> +        $user = \Auth::user();
$user = \Auth::user();を削除しました！

2024-11-02 05:50 UTC, Shinya-Nakaguchi commented on app/Http/Controllers/PostsController.php
> +            'user' => $user,
'user' => $user,を削除しました！

2024-11-02 05:50 UTC, Shinya-Nakaguchi commented on routes/web.php
> +
空白行を削除しました！

2024-11-02 05:51 UTC, Shinya-Nakaguchi commented on routes/web.php
> +Route::get('/', 'PostsController@index')->name('index');
post.indexに変更しました！

2024-11-02 19:29 UTC, yukihiroLaravel requested changes
１点指摘漏れていましたので
すみませんがご確認ください！

2024-11-02 19:29 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $post = Post::findOrFail($id);
指摘もれていましたが、
今の状態ですと、投稿者本人以外のユーザが
編集ページにアクセスできてしまいますので
（たとえば、2つ目の投稿した人以外のユーザでログインしているのに、
　/posts/2/editというURLを直接打てばアクセスできてしまう）
本人以外がアクセスした際にエラーを出すようにしましょう。

エラーの出し方のヒントとしては下記の１行のコードです。
```
abort(403);
```

2024-11-03 07:52 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
お疲れ様でした😃

2024-11-03 07:52 UTC, merged