#127　フォロー機能（小宮山）
yukihiroLaravel/joint_develop pull request #1302
Opened 2024-11-04 06:14 UTC by Neito5865

## issue
 - Closes #127 

## 概要
 - フォロー機能（フォローボタンの作成まで）

## 動作確認手順
 - user1でログインする
メールアドレス：user1@test.com  
パスワード：password

 - ログインしているユーザー（user1）以外のユーザー詳細ページへアクセスする
 - ユーザーアイコン下の「フォローする」ボタンをクリックする
 <img width="400" alt="スクリーンショット 2024-11-04 15 04 26" src="https://github.com/user-attachments/assets/f357a0d3-f7ad-4183-a0f5-bd3abf2cce04">

- 「フォローする」ボタンが「フォローを外す」に変わることを確認

 - Adminerでfollowsテーブルにレコードが追加されていることを確認
http://localhost:8088/

 - 「フォローを外す」ボタンをクリックする
 - 「フォローを外す」ボタンが「フォローする」に変わることを確認
 - Adminerでfollowsテーブルの対象のレコードが消えていることを確認
http://localhost:8088/

## 考慮してほしいこと
特にありません

## 確認してほしいこと
特にありません

2024-11-06 11:08 UTC, yukihiroLaravel requested changes
ほぼ完璧ですね！
１点だけご指摘しました😃

2024-11-06 11:08 UTC, yukihiroLaravel commented on routes/web.php
> +    Route::group(['prefix' => 'users/{id}'], function(){
２３行目の
Route::get('/users/{id}', 'UsersController@show')->name('user.show');
このルーティングもこのgroupの中に入れられると思います！
よろしくお願いします！

2024-11-07 06:46 UTC, Neito5865 commented on routes/web.php
> +    Route::group(['prefix' => 'users/{id}'], function(){
Route::get('/users/{id}', 'UsersController@show')->name('user.show');
のルーティングですが、ログインしなくても見られるように、ログイン後のルーティングのグループから外しています。
ログイン後の方に移してしまっていいのですか？

2024-11-07 10:25 UTC, yukihiroLaravel approved these changes

2024-11-07 10:25 UTC, merged