#119 投稿新規作成（いずみ）
yukihiroLaravel/joint_develop pull request #1303
Opened 2024-11-04 14:15 UTC by izumi-sakamoto

## issue
- Closes #119

## 概要
- 投稿新規作成の実装

## 動作確認手順
- ユーザログイン後、トップページの投稿フォームに投稿内容を記入し投稿ボタンを押す
- トップページに投稿内容が表示されることを確認
- 140字以上だった場合エラーメッセージが出ることの確認

## 考慮してほしいこと
- バリデーションエラーの日本語化の実装がまだのためエラー文が未完成です

## 確認してほしいこと

2024-11-05 03:03 UTC, yukihiroLaravel requested changes
質問とプルリクについて
ご指摘しました！
ご確認ください！

https://www.loom.com/share/2b466f698f904843bdd4b54f68b06caa

2024-11-05 03:03 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +    }
不要なメソッドです

2024-11-05 03:03 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +        </div>
ログインしていない状態では
ここが表示されない状態にしましょう！

2024-11-05 03:03 UTC, yukihiroLaravel commented on routes/web.php
> +});
ルーティングの位置変更

2024-11-05 07:51 UTC, izumi-sakamoto commented on routes/web.php
> +});
変更しました！

2024-11-05 07:54 UTC, izumi-sakamoto commented on resources/views/welcome.blade.php
> +        </div>
修正しましたが @auth は不要ですか？💧
現時点では @auth は入れています。

2024-11-05 12:50 UTC, yukihiroLaravel requested changes
１点コメントしました！
ご確認ください😃

2024-11-05 12:50 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +        </div>
こちらのコード同じ意味なので
@auth
かもしくは
@if (Auth::check())
いずれか一方だけで大丈夫です！

2024-11-06 07:46 UTC, yukihiroLaravel approved these changes
OKですので、マージしました！
おつかれさまでした😃

2024-11-06 07:47 UTC, merged