#125 ユーザー退会（竹内)
yukihiroLaravel/joint_develop pull request #1306
Opened 2024-11-06 23:47 UTC by ter0ter0

# issue
- Closes #125 

# 概要
- ユーザー退会の実装

# 動作確認
- 退会ボタンを押すとユーザーと投稿が削除されていることを確認。
- Adminerでログインしていたユーザーと投稿が削除されているいとを確認。

# 考慮して欲しいこと
特にございません

# 確認して欲しいこと
特にございません

2024-11-07 10:40 UTC, yukihiroLaravel requested changes
いくつかご指摘と、
コンフリクトが発生しておりますので
お手数ですが解消お願いします！

2024-11-07 10:40 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        {
コーディング規約的にこのように書きましょう！
```
if ($user->id === \Auth::id()) {
```

2024-11-07 10:40 UTC, yukihiroLaravel commented on routes/web.php
> +    });
ログイン状態でないと
このルーティングは機能してはいけないので、
```
Route::group(['middleware' => 'auth'], function(){
});
```
この中に記述するようにしましょう！

2024-11-07 11:23 UTC, ter0ter0 commented on app/Http/Controllers/UsersController.php
> +        {
見落としておりました！
修正いたします！

2024-11-07 11:27 UTC, ter0ter0 commented on routes/web.php
> +    });
<img width="689" alt="スクリーンショット 2024-11-07 20 24 57" src="https://github.com/user-attachments/assets/fde1a8b1-3e7d-4c81-bded-342fe71f976c">

間違っていたらすみません！
元々groupの中に入れていたつもりなのですがいかがでしょうか？

2024-11-11 02:27 UTC, yukihiroLaravel requested changes
インデントのずれだけ修正をおねがいします！
それ以外もお話ししていますが、その修正だけでOKです😃
↓
https://www.loom.com/share/eec819c126e842289095d054a15507e3

2024-11-11 02:27 UTC, yukihiroLaravel commented on routes/web.php
> +    });
インデントのずれ

2024-11-11 05:22 UTC, ter0ter0 commented on routes/web.php
> +    });
修正しました！

2024-11-11 11:03 UTC, yukihiroLaravel approved these changes
OKですのでマージしました！
おつかれさまでした😃

2024-11-11 11:03 UTC, merged