#99 ”posts（投稿）テーブルのマイグレーションとシーダー作成”
yukihiroLaravel/joint_develop pull request #131
Opened 2023-01-14 13:31 UTC by mao-fukushi

#isshue
closes#99

#概要
posts（投稿）テーブルのマイグレーションとシーダー作成

#動作確認手順

--------------------------------
1. ユーザーズテーブル
--------------------------------
1-1. ターミナルで下記のコマンドを実行
    php artisan db:seed --class=UsersTableSeeder

1-2. AdminerにてusersのDB情報が保存されていることを確認

--------------------------------
2. 投稿テーブル
--------------------------------
2-1. ターミナルで下記のコマンドを実行 
    php artisan db:seed --class=PostsTableSeeder

2-2. AdminerにてpostsのDB情報が保存されていることを確認

#考慮して欲しい事
特にありません。

#確認してほしいこと
 ・posts投稿の内容に改行コードの必要有無について
・そのほか、何かありましたらご教示ください。

以上、ご確認ほどよろしくお願い致します。

2023-01-15 04:27 UTC, Osk0830 requested changes
お疲れ様でした！
色々と考えて進めてらっしゃって実に素晴らしいと思います！

いくつかコメントを残しましたが、
一番重要なこととして、
共同作業において、「今の自分のタスクの守備範囲はどこか」を明確にしましょう！

コメントを参考に修正してみてくださいね！

2023-01-15 04:27 UTC, Osk0830 commented on app/Post.php
> +use Illuminate\Database\Eloquent\SoftDeletes;
- 今の段階での要件では、投稿は論理削除の状態で残しておく必要はなさそうです。そうなると、`softDelete`関連の機能の利用も不要ではないでしょうか？

2023-01-15 04:27 UTC, Osk0830 commented on app/Post.php
> +    use SoftDeletes;
- 今の段階での要件では、投稿は論理削除の状態で残しておく必要はなさそうです。そうなると、`softDelete`関連の機能の利用も不要ではないでしょうか？

2023-01-15 04:27 UTC, Osk0830 commented on app/User.php
>       * The attributes that are mass assignable.
- ユーザー関連の作業は、今回の福士さんのタスクの範囲外かと思います。。このファイルの作業は不要なので、元に戻しておいてくださいね。

2023-01-15 04:27 UTC, Osk0830 commented on database/migrations/2014_10_12_000000_create_users_table.php
- ユーザー関連の作業は、今回の福士さんのタスクの範囲外かと思います。。このファイルの作業は不要なので、元に戻しておいてくださいね。

2023-01-15 04:27 UTC, Osk0830 commented on database/migrations/2023_01_11_234631_create_posts_table.php
> +            $table->softDeletes();
- 今の段階での要件では、投稿は論理削除の状態で残しておく必要はなさそうです。そうなると、`softDelete`関連の機能の利用も不要ではないでしょうか？

2023-01-15 04:27 UTC, Osk0830 commented on database/migrations/2023_01_11_234631_create_posts_table.php
> +            $table->string('title')->nullable();
- 今の段階の要件では、投稿に「タイトル」は不要ではないでしょうか？

2023-01-15 04:27 UTC, Osk0830 commented on database/migrations/2023_01_11_234631_create_posts_table.php
> +            $table->text('content')->nullable();
- 投稿の本文がnullを許容する状態になっているのはおかしくないでしょうか？

2023-01-15 04:27 UTC, Osk0830 commented on database/migrations/2023_01_11_234631_create_posts_table.php
> +            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
- 記述はしっかりとできていますね！ただ、この部分に関しては、岡田さんが担当されているユーザー関連のマイグレーションとシーダーの内容がマージされるまでは使えないので、現段階では一旦コメントアウトしておいて、岡田さんのブランチがマージされた後にその内容をプルして、改めて動作確認行っていただければと思います！

2023-01-15 04:27 UTC, Osk0830 commented on database/seeds/DatabaseSeeder.php
> +        $this->call(UsersTableSeeder::class);
- ユーザー関連の作業は、今回の福士さんのタスクの範囲外かと思います。。この部分の変更は元に戻しておいてくださいね。

2023-01-15 04:27 UTC, Osk0830 commented on database/seeds/PostsTableSeeder.php
> +    }
- 内容を具体的に入力されていていいですね！笑　今回はダミーデータですので、もちろん、もっと単純なデータでもOKです！

- 現在の要件として、`title`は要らないと思われます。

- 今回は5件のデータなのでこの方式でもそれでも可能そうですが、実務においては数百、数千のダミーデータを登録しなければならないようなこともあり得ます。その場合、この方式だとさすがに厳しいと思います。是非ループ文を使う形で修正してみてくださいね。

- 実際に登録されたデータを見ていただくとわかる通り、`DB::table()->insert()`メソッドですと、`created _at`と`updated_at`のカラムに値が入らず空のままになると思います。なので、これらのカラムにも値が入るように記述を追加するか、もしくは、モデルの`save()`メソッドを使う形に変更してこれらのカラムに自動的に値が入るようにしてみましょう。

2023-01-15 04:27 UTC, Osk0830 commented on database/seeds/UsersTableSeeder.php
> +<?php
- ユーザー関連の作業は、今回の福士さんのタスクの範囲外かと思います。。このファイルの作業は不要なので、元に戻しておいてくださいね。

2023-01-15 09:03 UTC, mao-fukushi commented
> お疲れ様でした！ 色々と考えて進めてらっしゃって実に素晴らしいと思います！
> 
> いくつかコメントを残しましたが、 一番重要なこととして、 共同作業において、「今の自分のタスクの守備範囲はどこか」を明確にしましょう！
> 
> コメントを参考に修正してみてくださいね！

HANさん
レビューいただきありがとうございます。
コメント確認しました。
頂いた内容をもとに、修正後、プルリク修正します。
よろしくお願い致します。

2023-01-15 11:23 UTC, mao-fukushi commented on app/Post.php
> +use Illuminate\Database\Eloquent\SoftDeletes;
SoftDaletesをコメントアウトしました。

2023-01-15 11:23 UTC, mao-fukushi commented on app/Post.php
> +    use SoftDeletes;
SoftDaletesをコメントアウトしました。

2023-01-15 11:24 UTC, mao-fukushi commented on app/User.php
>       * The attributes that are mass assignable.
変更した箇所の記述を元に戻しました。

2023-01-15 11:25 UTC, mao-fukushi commented on database/migrations/2014_10_12_000000_create_users_table.php
変更した箇所の記述を元に戻しました。

2023-01-15 11:27 UTC, mao-fukushi commented on database/migrations/2023_01_11_234631_create_posts_table.php
> +            $table->softDeletes();
SoftDaletesをコメントアウトしました。

2023-01-15 11:28 UTC, mao-fukushi commented on database/migrations/2023_01_11_234631_create_posts_table.php
> +            $table->string('title')->nullable();
タイトルのカラムを削除しました。

2023-01-15 11:38 UTC, mao-fukushi commented on database/migrations/2023_01_11_234631_create_posts_table.php
> +            $table->text('content')->nullable();
投稿の本文のnullを許容する記述を削除しました。

2023-01-15 11:40 UTC, mao-fukushi commented on database/migrations/2023_01_11_234631_create_posts_table.php
> +            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
L22 SoftDeletes
L24 外部キー制約のcascade
上記２箇所をコメントアウトしました。

2023-01-15 11:41 UTC, mao-fukushi commented on database/seeds/DatabaseSeeder.php
> +        $this->call(UsersTableSeeder::class);
// $this->call(UsersTableSeeder::class);　の通り、コメントアウトの状態に戻しました。

2023-01-15 11:44 UTC, mao-fukushi commented on database/seeds/PostsTableSeeder.php
> +    }
- ダミーデータ用の記述に単純化しました。
- titleのカラムを削除しました。
- 5件から10件へ増やしました。ループ文を使う形に修正しました。
- DB::table()->insert()メソッドについて、created _atとupdated_atのカラムに値が入るように記述を追加しました。

2023-01-15 11:46 UTC, mao-fukushi commented on database/seeds/UsersTableSeeder.php
> +<?php
ファイルごと削除しました。

2023-01-16 03:10 UTC, Osk0830 requested changes
お疲れ様です！
こちらしっかりと修正されていて作業内容は概ね問題なさそうですね！
一点だけコメントしましたので、ご確認ください。

また、現在、コンフリクトが発生しているので、
こちらの解消もお願いします！

[![Image from Gyazo](https://i.gyazo.com/68929ae2b23db405869894160899be3f.png)](https://gyazo.com/68929ae2b23db405869894160899be3f)

よろしくお願いします！

2023-01-16 03:10 UTC, Osk0830 commented on database/seeds/PostsTableSeeder.php
> +                'id' => $i,
- `id`のカラムは自動的に増えるようになっているので、シーディングの内容には含まなくても大丈夫です。

2023-01-16 13:38 UTC, mao-fukushi commented on database/seeds/PostsTableSeeder.php
> +                'id' => $i,
idのカラムを削除しました。

2023-01-16 16:11 UTC, mao-fukushi commented
> お疲れ様です！ こちらしっかりと修正されていて作業内容は概ね問題なさそうですね！ 一点だけコメントしましたので、ご確認ください。
> 
> また、現在、コンフリクトが発生しているので、 こちらの解消もお願いします！
> 
> [![Image from Gyazo](https://camo.githubusercontent.com/c4bfe284083f8710ac62a00f3745a089048e81a0650b8bb965a047a3d00cf6d3/68747470733a2f2f692e6779617a6f2e636f6d2f36383932396165326232336462343035383639383934313630383939626533662e706e67)](https://gyazo.com/68929ae2b23db405869894160899be3f)
> 
> よろしくお願いします！

レビューいただきありがとうございます。
ご指摘いただきました下記のファイルについて、idカラムをシーディングに含めないように、カラムの記述を削除しました。
[database/seeds/PostsTableSeeder.php]

以上、よろしくお願い致します。

2023-01-17 12:37 UTC, Osk0830 approved these changes
お疲れ様でした！
こちら大丈夫そうなのでマージしますね。
引き続き頑張ってくださいね！

2023-01-17 12:37 UTC, merged