#117 ユーザ編集画面・更新(オギドウ)
yukihiroLaravel/joint_develop pull request #1312
Opened 2024-11-10 03:23 UTC by takeshi-ogido

## issue
- Closes #117 

## 概要
- ユーザ編集画面・更新 (オギドウ）

## 動作確認手順
ユーザー情報を入力後、更新ボタンを押すとユーザー情報が更新されたのを確認。
## 考慮して欲しいこと
## 確認して欲しいこと
コード全体あっているか、また違う書き方ができるのあればご教授お願いします。
特にUserRequest.phpファイル。

2024-11-10 08:06 UTC, yukihiroLaravel requested changes
いくつかコメント差し上げました！
ご確認ください！

https://www.loom.com/share/9e0fc565fcc54f899940c766eb64ceb0

2024-11-10 08:06 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        );
この部分は１行にするか、
２行にするなら下記の書き方にしましょう。

```
return view('users.edit', [
　　'user' => $user
]);
```

2024-11-10 08:06 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +}
閉じガッコ周りが変なことになっているので
これはよく見れば気づけることだと思いますので、今後は気づき
修正しましょう！

```
    public function update(UserRequest $request, $id)
    {
         $user = User::findOrFail($id);
         $user->name = $request->name; // フォームから送られてきたname
         $user->email = $request->email;// フォームから送られてきたemail
         if ($request->filled('password')) {
                $user->password = Hash::make($request->password);     
                $user->save();
                return back();
         }
     }
}
```

2024-11-10 08:06 UTC, yukihiroLaravel commented on app/Http/Requests/UserRequest.php
> +                'password' => ['required', 'string', 'min:8', 'confirmed'],
インデントはスペース４つ分

2024-11-10 08:06 UTC, yukihiroLaravel commented on resources/views/users/edit.blade.php
> +    @endif
使われていないので今は不要

2024-11-10 08:06 UTC, yukihiroLaravel commented on routes/web.php
> +Route::put('/users/{id}', 'UsersController@update')->name('user.update');
ルーティングを
```
Route::group(['middleware' => 'auth'], function(){
});
```
の中に置いた上で
```
Route::prefix('users/{id}')->group(function(){
});
```
というprefixでまとめる

2024-11-10 08:06 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $user = User::findOrFail($id);
今の状態ですと、本人以外のユーザが
ユーザ編集ページにアクセスできてしまいますので
（たとえば、ユーザID: 1 でログインしているのに、
　/users/2/editというURLを直接打てばアクセスできてしまう）
本人以外がアクセスした際にエラーを出すようにしましょう。

エラーの出し方のヒントとしては下記の１行のコードです。
```
abort(403);
```

2024-11-10 08:06 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +    }
app/Http/Requests/UserRequest.php
でpasswordがrequiredつまり必須になっていますので
ここで条件付けをしなくても
passwordがない場合は必ずバリデーションで弾かれるので
不要ですね！

2024-11-10 08:06 UTC, yukihiroLaravel commented on app/Http/Requests/UserRequest.php
> +                'email' => ['required', 'string', 'email', 'max:255'],
この状態だと、他ユーザとメールが被ったときに
Integrity constraint violation
というエラーが出てしまうのでバリデーションにてそれを回避できるようにしましょう。

また、上記の対応をすると
更新者本人のメアドと被ったときもバリデーションエラーが出てしまうことになるのですが
実はそれを回避する方法もあるので少し考えてみてください！
（調べて不明でしたら回答します！）

2024-11-11 02:38 UTC, takeshi-ogido commented on app/Http/Requests/UserRequest.php
> +                'email' => ['required', 'string', 'email', 'max:255'],
今回、メールアドレスは他のユーザーと重複してもいいということでしょうか？

2024-11-11 12:06 UTC, yukihiroLaravel requested changes
コンフリクト解消含め、
いくつか対応お願いします！

2024-11-11 12:06 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        return back();
ユーザ詳細画面に遷移するように変更

2024-11-11 12:06 UTC, yukihiroLaravel commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255','unique:users,email,' . $this->route('id')],
routeのところを
. $this->id
に変更

2024-11-11 12:06 UTC, yukihiroLaravel commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255','unique:users,email,' . $this->route('id')],
パスワードだけ変えた時に更新されるかチェックお願いします。

2024-11-11 12:06 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $user = User::findOrFail($id);
```
if (\Auth::id() !== (int) $id) {
        abort(403);
}
return view('users.edit', [
            'user' => $user 
]);
```

2024-11-12 05:49 UTC, takeshi-ogido commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255','unique:users,email,' . $this->route('id')],
$user->password = bcrypt($request->password);   
追加でパスワードとアップデート時間が更新された。

2024-11-12 09:51 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
お疲れ様でした😀

2024-11-12 09:55 UTC, merged