#127 フォロー機能：フォロワー・フォロー中ユーザー一覧表示（小宮山）
yukihiroLaravel/joint_develop pull request #1314
Opened 2024-11-12 04:50 UTC by Neito5865

## issue
 - Closes #127 

## 概要
 - フォロワーとフォロー中のユーザー一覧の表示
 - フォロワーとフォロー中の数の取得

## 動作確認手順
 - ユーザー詳細ページへアクセスする
例）user5の場合  
http://localhost:8080/users/5

 - ユーザー詳細ページのフォロー中タブをクリックすると、user5がフォローしているユーザーの一覧が表示される
 - フォロワータブをクリックすると、user5をフォローしているユーザーの一覧が表示される
 - ログインした状態では、各ユーザーの横にフォローボタンが表示される
<img width="800" alt="スクリーンショット 2024-11-12 13 45 08" src="https://github.com/user-attachments/assets/4dc286ef-e592-46f4-b799-140b685bc4e6">

## 考慮してほしいこと
 - 特にありません

## 確認してほしいこと
 - 特にありません

2024-11-12 10:06 UTC, yukihiroLaravel requested changes
難しい実装でしたが
素晴らしい出来です！！おつかれさまでした😀

細かい点のみ指摘しましたのでご確認ください！

2024-11-12 10:06 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +    // フォロワーの投稿表示
// フォロワーの表示
が正しいのではないでしょうか？

2024-11-12 10:06 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="{{ route('user.followers', $user->id) }}" class="nav-link {{ $tab === 'followers' ? 'active' : '' }}">フォロワー<br><div class="badge badge-secondary">{{ $cou
```</div>```
タグの数？のせいか、タイムラインのタブの縦線が切れていますので
修正しましょう！
<img width="956" alt="スクリーンショット 2024-11-12 22 58 52" src="https://github.com/user-attachments/assets/85767a04-d13f-47c6-be07-53d7a76725d2">

2024-11-12 10:06 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +            @endif
$tabでわかりやすく各ページが分岐していていいですね！

2024-11-13 03:30 UTC, Neito5865 commented on app/Http/Controllers/UsersController.php
> +    // フォロワーの投稿表示
修正しました。

2024-11-13 04:29 UTC, Neito5865 commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="{{ route('user.followers', $user->id) }}" class="nav-link {{ $tab === 'followers' ? 'active' : '' }}">フォロワー<br><div class="badge badge-secondary">{{ $cou
タイムラインタブのaタグにスタイルを適用して修正しました。
この修正の仕方で良いのでしょうか？

2024-11-13 14:07 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！！
おつかれさまでした！

2024-11-13 14:08 UTC, merged