#107ユーザ新規登録(たろう）
yukihiroLaravel/joint_develop pull request #132
Opened 2023-01-16 11:03 UTC by afurotanaka

## issue
 - closes #107 
 
## 概要
- ユーザ新規登録の実装

## 動作確認手順
- 下記のコマンドを実行
　- http://localhost:8080/signup
　 新規登録画面にアクセス出来ていることを確認

     - http://localhost:8088
     name email  passwordを入力した後にデータベース上にデータがあるか確認

## 考慮して欲しいこと
-  状況に応じて、バリデーションエラーを入れたので、確認して欲しい

## 確認してほしこと
- コントローラーがないとモデルのデータが取得出来ないと思い、routeの記述の変更とUsersContollerの作成したために他の方がpushする際にコンフリクトエラーが出る可能性があります。

状況に応じて変更しますのでよろしくお願いいたします。

-  マグレーションがsoftDeleteの為にデータベース上に残る気がするのですが？
- 退会した人が新規登録した場合は、どうなるのかを知りたいです。
-もう一度、新しいマグレーションを作るのが正解なのか知りたいです。
　
ご確認の程よろしくお願いいたします。

2023-01-16 13:47 UTC, yukihiroLaravel requested changes
RedirectIfAuthenticated.phpも修正する

2023-01-16 13:47 UTC, yukihiroLaravel commented on app/User.php
> +use Illuminate\Database\Eloquent \SoftDeletes;
スペース削除

2023-01-16 13:47 UTC, yukihiroLaravel commented on resources/views/auth/register.blade.php
> +                  </div>
インデント

2023-01-16 13:47 UTC, yukihiroLaravel commented on routes/web.php
> +
空行削除

2023-01-18 09:45 UTC, afurotanaka commented
確認しました。

2023-01-18 14:00 UTC, afurotanaka commented
## issue
-closes#107

## 概要
ー ユーザ新規登録の修正

## 動作確認手順
ー下記のコマンドを実行
http://localhost:8088/signup

新規登録画面にアクセス出来ていることを確認
新規登録後にトップ画面に移動
トップ画面に移動後、下記のコマンドを実行してトップ画面にいることを確認
http://localhost:8088/signup

## 考慮して欲しい事
新規登録後に
http://localhost:8088/signupにアクセスしてもトップ画面にいることを確認

## 確認してほしいこと

middleware/RedirectIfAuthenticated.phpの変更
register.blade.phpのインデントの修正
web.phpのインデントの修正

以上の３つの確認のほどよろしくお願いいたします。

2023-01-19 02:30 UTC, yukihiroLaravel requested changes
良い感じかと思います。

コメントした１つインデントの箇所だけ修正願います！

あと、前回MTGでお伝えしていたことですが
各コメントに対して Reply... の箇所に
「修正します」
などと入力して返信しておくようにしましょう！

2023-01-19 02:30 UTC, yukihiroLaravel commented on resources/views/auth/register.blade.php
> +    </div>
ここですが
`<div class="row mt-5 mb-5"></div>`
の中に入っているので、インデントをまた１つ下げないとイケないと思います！

2023-01-19 03:53 UTC, afurotanaka commented on resources/views/auth/register.blade.php
> +    </div>
記述箇所確認しました。

そうですね。

<div class="row mt-5 mb-5"></div>

の中、全体のインデントの修正行います

2023-01-19 03:55 UTC, afurotanaka commented on resources/views/auth/register.blade.php
> +    </div>
<div class="row mt-5 mb-5"></div>の中、全体のインデント修正

2023-01-19 09:01 UTC, afurotanaka commented
## issue
- closes#107

## 概要
ー ユーザ新規登録の修正

## 動作確認手順
- viewのインデントの修正の確認のため、特になし

##考慮して欲しい事
-　きちんと指摘された所のインデントの修正が出来ているのか

##確認してほしいこと
- 1行1行、インデントの修正しているので他に効率良くインデント修正出来る方法があれば知りたいです。

よろしくお願いいたします。

2023-01-22 15:30 UTC, afurotanaka commented
## issue
-closes#107

## 概要
ー ユーザ新規登録の修正

## 動作確認手順

- 下記の手順を実行

http://localhost:8080
top画面のヘッダーから新規登録画面に行ける事を確認

考慮して欲しい事

お手数をおかけしますが、上のインデントの修正も確認してもらいたいです。


確認してほしいこと
header.blade.phpの新規登録の画面に行けるかを確認。
auth/register.blade.phpのインデントの修正

２つの確認よろしくお願いいたします。

2023-01-23 04:25 UTC, GutFamilie approved these changes
OKですので、こちらでマージします！
お疲れ様でした。

今回厳密にタスクの範囲を決めてませんでしたが

`ユーザ登録すると、
ヘッダーの「新規ユーザ登録」の文字が消えて、
ユーザ名とログアウトの文字が出てくる`

という実装はふじおかさんの
ログイン・ログアウト機能の実装と同時にお願いする
という方向で大丈夫でしょうか？

その方向であれば、ふじおかさんにもその旨を伝えて
進めていただければと思います☺️

2023-01-23 04:26 UTC, yukihiroLaravel approved these changes
OKですので、こちらでマージします！
お疲れ様でした。

今回厳密にタスクの範囲を決めてませんでしたが

ユーザ登録すると、 ヘッダーの「新規ユーザ登録」の文字が消えて、 ユーザ名とログアウトの文字が出てくる

という実装はふじおかさんの
ログイン・ログアウト機能の実装と同時にお願いする
という方向で大丈夫でしょうか？

その方向であれば、ふじおかさんにもその旨を伝えて
進めていただければと思います☺️

2023-01-23 04:26 UTC, merged