#95 posts（投稿）テーブルのマイグレーションとシーダー作成
yukihiroLaravel/joint_develop pull request #133
Opened 2023-01-16 13:57 UTC by shunsukeotsubo

## issue
- Closes #95 

## 概要
- posts（投稿）テーブルのマイグレーションとシーダー作成

## 動作確認手順
- 下記コマンドを実行してください。
- 【マイグレーション】  
   　ターミナル上でphp artisan migrationを実行。  
   　localhost:8088、Adminerのlaraveldb内のテーブルにpostsが作成されており、
　   4つのレコードが保存されていることを確認。

- 【シーダー】  
   php artisan db:seed --class=PostsTableSeederを実行

## 考慮して欲しいこと
- 状況に応じて下記コマンドで動作確認する必要があります。
　php artisan migrate:fresh --seed

## 確認して欲しいこと
- create_posts_tableの20行目の$table->text('content')について
　投稿系のアプリの投稿部分はtext('content')を使うことが多いでしょうか。

2023-01-17 01:34 UTC, yukihiroLaravel requested changes
お手数ですが、複数箇所コメントさせていただきましたので、
ご確認と修正願います☺️

宜しくお願いします！

2023-01-17 01:34 UTC, yukihiroLaravel commented on database/migrations/2023_01_14_234436_create_posts_table.php
> +            $table->string('title')->nullable();
タイトルはなぜ必要だと思われましたか？
お手本のアプリを見ても、タイトルを入力する欄はないので
特に不要かと思います！

2023-01-17 01:34 UTC, yukihiroLaravel commented on database/migrations/2023_01_14_234436_create_posts_table.php
> +            $table->text('content')->nullable();
ご質問の件ですが、これはcontentでいいと思いますね！
postテーブルという名前で投稿という名前が付いているので、その投稿の中身=contentという認識で
contentでいいと思います。

また、これはnullableにすると、中身がなしでも投稿できてしまうということになりますが
お手本だと投稿の中身を空にして投稿しようとするとエラーが出ていたと思うので
nullableは消しましょう！

2023-01-17 01:34 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +
この空行はない方がいいですね！

2023-01-17 01:34 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +
この空行はない方がいいですね！

2023-01-17 01:34 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +
この空行はない方がいいですね！

2023-01-17 01:34 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +            'title' => 'ダイエットに効果的なもの',
idは指定しなくても自動で割り振られるのでなしでいいですね！
titleは上記の通りカラム自体不要かと思うので、titleも消して下さい。

他の項目も、id, titleは削除してください！

2023-01-17 01:34 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +        ]);
１ページに10個以上の投稿があった場合の
ページ遷移を今後確認しやすいように
お手数ですが、合計11個以上の投稿を作ってみてください！

2023-01-17 12:54 UTC, shunsukeotsubo commented on database/seeds/PostsTableSeeder.php
> +        ]);
確認ありがとうございます。
修正いたします。

2023-01-17 14:59 UTC, shunsukeotsubo commented
## 概要
- posts（投稿）テーブルのマイグレーションとシーダー作成　修正
- 修正箇所
- ①PostsTableのtitleカラムの削除
- ②PostsSeederのtitleカラムとidカラムの削除
- ③PostsSeederのスペースとnullableの削除
- ④PostsSeederのデータの追加（合計12個）

## 動作確認手順
- ターミナル上で下記のコマンドを実行してください。
　php artisan migrate:fresh --seed

## 確認して欲しいこと
- PostsTableのtitleカラムの削除は以下の方法で行ったのですが間違いないでしょうか。
- ①vsコードで $table-> title();を直接削除して保存
- ②ターミナルでphp artisan migrate:fresh --seedのコマンドを実行
- ③databaseで確認

- 気になったことはphp artisan migrate:fresh --seedを打ったらgit hub上で修正箇所の表示が出なかったことです。
- 他に方法がありましたら教えていただけますでしょうか。
ご確認お願いします。

2023-01-18 07:33 UTC, yukihiroLaravel approved these changes
OKです！
完璧に修正いただいたと思います😃

マージしました。

2023-01-18 07:34 UTC, merged