#1346　アバター画像の設定
yukihiroLaravel/joint_develop pull request #1347
Opened 2024-12-02 06:19 UTC by Neito5865

## issue
 - Closes #1346 

## 概要
 - ユーザー編集画面にてアバター画像を設定できるようにする。

## 動作確認手順
 - 下記コマンドを実行。
 - マイグレーションの実行。
php artisan migrate
 - Adminerでusersテーブルにimageカラムが追加されていることを確認。
 - ユーザー編集画面にて、「画像を選択する」をクリックすると、  
ローカルから画像を選択しアップロードできる。  
アバター画像（円の部分）にアップロードした画像が表示されることを確認。
 - バリデーションについて
jpg、jpeg、pngのデータ形式を許可するのと、2MB以下の画像を許可するように設定しました。
 - 更新ボタンを押すと画像が更新されることを確認。

## 考慮してほしいこと
 - 状況に応じて、下記コマンドで動作確認する必要があります。
php artisan migrate:fresh
php artisan db:seed —class=UsersTableSeeder

 - 返信機能の方になってしまうのですが、  
退会したユーザーの返信が残っている返信一覧を表示させようとすると、エラーが発生しました。  
その関係で、RepliesControllerとreply_button.blade.phpも修正しています。

## 確認してほしいこと
 - 特にありません。

2024-12-02 11:56 UTC, yukihiroLaravel requested changes
修正願います

2024-12-02 11:56 UTC, yukihiroLaravel commented on app/User.php
> +        'name', 'email', 'password', 'image',
'image',
なくてOK

2024-12-02 11:56 UTC, yukihiroLaravel commented on app/Http/Controllers/RepliesController.php
> +        })
修正

2024-12-03 06:35 UTC, Neito5865 commented on app/Http/Controllers/RepliesController.php
> +        })
修正しました。

2024-12-03 06:36 UTC, Neito5865 commented on app/User.php
> +        'name', 'email', 'password', 'image',
修正しました。

2024-12-03 11:25 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした😃

2024-12-03 11:25 UTC, merged