#1348 タグ機能（小宮山）
yukihiroLaravel/joint_develop pull request #1352
Opened 2024-12-06 21:38 UTC by Neito5865

## issue
 - Closes #1348 

## 概要
 - タグ機能の追加

## 動作確認手順
 - 下記コマンドを実行。

 - マイグレーションの実行
php artisan migrate
 - Adminerでtagsテーブルとpost_tagテーブルが作成されていることを確認。

 - ログイン後、新規投稿を実行。  
タグの入力フォームに任意のタグを入力。  
タグの入力は「#」を頭につける。また、複数のタグを入力する場合は、半角スペースで区切って入力する。
 - 新規投稿実行後、Adminerのtagsテーブルとpost_tagテーブルにデータが保存されていることを確認。
 - ビューの確認：トップページで投稿文の下にタグが付けられていることを確認。
 - タグをクリックすると同じタグが付けられた投稿の一覧ページに遷移することを確認。

## 考慮してほしいこと
 - 特にありません。

## 確認してほしいこと
 - 特にありません。

2024-12-07 04:06 UTC, yukihiroLaravel requested changes
確認しましたが、
かなりハイレベルですばらしいと思います😊

細かい点だけ指摘させていただきましたのでご確認ください！

2024-12-07 04:06 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +            $post->tags()->sync($tagIds); // 中間テーブルを更新
今だと、中間テーブルに作成・更新日時が入るようになっていないので
中間テーブルに作成・更新日時が入るようにしましょう！

2024-12-08 07:29 UTC, Neito5865 commented on app/Http/Controllers/PostsController.php
> +            $post->tags()->sync($tagIds); // 中間テーブルを更新
postモデルとtagモデルに`withTimestamps()`を追加しました。  
動作確認済みです。よろしくお願いします！

2024-12-08 08:56 UTC, yukihiroLaravel approved these changes
OKなので
マージしました！！
おつかれさまでした！✨

2024-12-08 08:56 UTC, merged