Feature/ogido/media management
yukihiroLaravel/joint_develop pull request #1357
Opened 2024-12-11 04:36 UTC by takeshi-ogido

## issue
- 

## 概要
- 画像と動画の投稿機能　(オギドウ）

## 動作確認手順
・アップロードボタンで画像、動画いずれかを選択後、プレビュー画面で表示されたことを確認。
・画像ボタンで動画を選択すると、エラーが出ることを確認。その逆も確認済み。

## 考慮して欲しいこと
## 確認して欲しいこと
・jsのファイルをどこに書くのが適正でしょうか。
・その他のコードも怪しいので、ご確認お願いします。

2024-12-11 11:17 UTC, yukihiroLaravel requested changes
コメントしました！
精度高くできていてすばらしいですが
基本のコンフリクト解消ができていなかったので
今後プルリクの際は十分注意するようにしましょう！

https://www.loom.com/share/87217071ac014d6da93e3666a694513b

2024-12-11 11:17 UTC, yukihiroLaravel commented on resources/views/layouts/app.blade.php
> +        </script>
今回はこの場所でもいいかもしれませんが
JSファイルをまとめるなら、
resources/jsフォルダの中に、app.jsなどのファイルを作っておきますね。

2024-12-11 11:17 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +                    @endif
インデントがおかしい

2024-12-11 11:17 UTC, yukihiroLaravel commented on app/Http/Requests/PostRequest.php
> +            'video' => 'nullable|mimes:mp4,avi,mov|max:10000', // 10MBまで
ファイルサイズによってはこのバリデーション以前に
PHPの最大許容ギガ数を超えてしまって、LaravelやPHPエラーが出てしまう場合があるので、
今回のプルリクとは別に、下記動画の後半でやっているように
Dockerfileを書き換えないといけないかなと思います。

https://www.loom.com/share/f67f81c7ef2040f9abc1ca21abc4ed62

2024-12-11 11:17 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +            $post-> video_path = basename($path);
-> の直後のスペース不要

2024-12-11 11:17 UTC, yukihiroLaravel commented on resources/sass/app.scss
> +}
public/css/style.cssに書いた方がいい？

2024-12-11 11:17 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +                    @endif
ここが使われてなくないでしょうか？

2024-12-11 11:17 UTC, yukihiroLaravel commented on resources/sass/app.scss
> +}
適用されてないんだったら消す

2024-12-13 03:45 UTC, takeshi-ogido commented on resources/views/layouts/app.blade.php
> +        </script>
app.jsのファイルが元からあるのですが、そこに上記のファイルを書いた後assetで呼び出せば使えますでしょうか？

2024-12-15 11:14 UTC, yukihiroLaravel commented on resources/views/layouts/app.blade.php
> +        </script>
すでに存在する
require('./bootstrap');
これなどは消さないようにおいておいた上で
assetなどで呼び出せば使えると思います！

2024-12-15 11:29 UTC, yukihiroLaravel approved these changes
修正含めてOKなのでマージしました！
ご質問の回答はGitHub上に書いていますのでご確認ください！

おつかれさまでした✨

2024-12-15 11:29 UTC, merged