#121 投稿削除(佐藤泰志)
yukihiroLaravel/joint_develop pull request #1362
Opened 2024-12-11 10:56 UTC by yasusato1030

## issue
　#121

## 概要
　投稿削除

## 動作確認手順
　・Topic Postsへログイン（test1ユーザーでログイン）
　・会話を新規登録する
　・新規登録した会話が表示されたことを確認
　・登録された会話の削除ボタンをクリックする
　・投稿が削除されたことを確認

## 考慮してほしいこと

## 確認してほしいこと

2024-12-11 11:23 UTC, yukihiroLaravel requested changes
いくつかコメントしました！

検索結果を表示する部分を消してしまっているのはまずいので
修正しましょう・・・！

2024-12-11 11:23 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +       session()->flash('flash-message', '投稿を削除しました。');
インデントスペース１つ分右に移動

2024-12-11 11:23 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> -                        {{ $posts->appends(['keyword' => $keyword])->links('pagination::bootstrap-4') }}
検索結果を表示する部分を消してしまっているのはまずいので
修正しましょう・・・！

2024-12-11 11:23 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> -    @endif
他の方が実装された
検索結果を表示する部分を消してしまっているのはまずいので
修正しましょう・・・！

2024-12-13 12:23 UTC, yasusato1030 commented
別ブランチでプッシュするため本プッシュは削除いたします。

2024-12-13 12:23 UTC, closed without merging