#109 ユーザログイン・ログアウト（岡田）
yukihiroLaravel/joint_develop pull request #137
Opened 2023-01-19 12:14 UTC by yusukeokada2125

## issue
- Closes #109

## 概要
- ユーザログイン・ログアウト

## 動作確認手順
- ①<http://localhost:8080>を入力し、トップ画面でログイン表記があることを確認。
- ②『ログインの確認』→ログインを押し、ログイン画面へ遷移することを確認。
- ③<http://localhost:8088>より任意のユーザのメールアドレスとパスワードを入力し、ログインボタンを押すとトップ画面でログイン状態になることを確認。
画面右上に登録ユーザ名とログアウトが表示されることも確認。
- ④『ログアウトの確認』ログアウトボタンを押し、トップ画面のままログインと新規ユーザ登録の表記になったことを確認
- ⑤『ログイン時入力エラーの確認』
⑤-1 メールアドレス、パスワードのいずれかが未入力の場合、入力必須というバリデーションエラーが表示されることを確認。
⑤-2 どちらも入力したが間違っていた場合、登録と一致していないというエラーが表示されることを確認。

## 考慮してほしいこと
- ありません。

## 確認してほしいこと
- 不備ありましたら、ご教示お願いいたします。

2023-01-19 12:46 UTC, Osk0830 requested changes
お疲れ様でした！
ほぼOKですが、一点修正した方が良さそうなので、MTGでお伝えしますね。

2023-01-19 12:46 UTC, Osk0830 commented on app/Http/Controllers/Auth/LoginController.php
> +
- ここの記述は不要ですが、理由を書き始めるとものすごく長くなるので、MTGでご説明しますね。

2023-01-19 12:46 UTC, Osk0830 commented on resources/views/auth/login.blade.php
> +                @csrf
- この行はインデントを一つ下げた方が良さそうですね。

2023-01-20 12:14 UTC, yusukeokada2125 commented on app/Http/Controllers/Auth/LoginController.php
> +
承知しました。削除いたします。

2023-01-20 12:14 UTC, yusukeokada2125 commented on resources/views/auth/login.blade.php
> +                @csrf
16行目ですね。一つ下げます。

2023-01-21 02:02 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらマージしますね！

2023-01-21 02:02 UTC, merged