活動記録の投稿機能（小宮山）
yukihiroLaravel/joint_develop pull request #1370
Opened 2024-12-16 07:11 UTC by Neito5865

## issue
 - Closes #1368 

## 概要
 - 活動記録を投稿する機能とトップページへの一覧表示

## 動作確認手順
 - 下記コマンドを実行。
 - マイグレーションの実行
```
php artisan migrate
```
 - シーディングの実行
```
php artisan db:seed --class=AreasTableSeeder
```
 - Adminerでareasテーブルとactivitiesテーブルが作成され、areasテーブルに都道府県のデータが作成されていることを確認。
 - トップページにアクセスし、ログイン後ヘッダーナビゲーションの「記録する」をクリック。
 - 新規投稿ページへ遷移するので、フォームに入力し「投稿する」をクリック。
 - トップページにリダイレクトされ、サクセスメッセージが上部に表示されることを確認。
 - トップページは、普通の投稿と活動記録をタブで分けて表示するようにしています。  
「ラ活報告」のタブをクリックすると、新規登録した活動記録の一覧が表示されることを確認。※ラ活=ラーメン活動です！

## 考慮してほしいこと
 - 特にありません。

## 確認してほしいこと
 - 特にありません。

2024-12-16 09:37 UTC, yukihiroLaravel requested changes
すばらしい機能ですね✨
編集機能などは今後追加される予定ということですよね？

いくつかコメントしましたのでご確認願います！

2024-12-16 09:37 UTC, yukihiroLaravel commented on resources/views/activities/activities.blade.php
> +                            <img src="{{ asset('storage/icons/menuName_icon.svg') }}" alt="メニューアイコン" width="20" height="20" style="vertical-align: text-top">
これが現在僕の環境だと表示されないため
publicの下のフォルダの中などに画像を入れてアップロードの必要があると思います！

2024-12-16 09:37 UTC, yukihiroLaravel commented on app/Http/Controllers/ActivitiesController.php
> +        }
imageはバリデーションで必須になっているので
このifは不要かなと思いました！

2024-12-16 09:37 UTC, yukihiroLaravel commented on app/Area.php
> +    }
この関数は現状使っていますか？

2024-12-16 09:37 UTC, yukihiroLaravel commented on database/migrations/2024_12_14_151509_create_areas_table.php
> +            $table->string('area', 10);
すでにareaという文字はテーブル名で使っていて重複するので
例えば prefectureとかcontentなど別の単語の方がいいと思います！

2024-12-16 09:37 UTC, yukihiroLaravel commented on database/migrations/2024_12_14_154743_create_activities_table.php
> +            $table->string('menuName');
テーブル名にはあまりshopNameなどのキャメルケースは使わず、
shop_name
menu_name
などのスネークケースを使いますね！

2024-12-16 09:37 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::post('create', 'ActivitiesController@store')->name('activity.store');
ここのURLがcreateとなるのは少し変な気がします！

2024-12-17 06:51 UTC, Neito5865 commented on app/Area.php
> +    }
リレーションで記述しなければならないものだと勘違いしていました！
関数自体はつかていないので削除しました。

2024-12-17 06:52 UTC, Neito5865 commented on app/Http/Controllers/ActivitiesController.php
> +        }
if文は削除して修正しました。

2024-12-17 07:02 UTC, Neito5865 commented on database/migrations/2024_12_14_151509_create_areas_table.php
> +            $table->string('area', 10);
prefectureに修正しました！

2024-12-17 07:08 UTC, Neito5865 commented on database/migrations/2024_12_14_154743_create_activities_table.php
> +            $table->string('menuName');
修正しました！

2024-12-17 07:19 UTC, Neito5865 commented on resources/views/activities/activities.blade.php
> +                            <img src="{{ asset('storage/icons/menuName_icon.svg') }}" alt="メニューアイコン" width="20" height="20" style="vertical-align: text-top">
public/imagesディレクトリの中に保存したら表示できました！

2024-12-17 07:20 UTC, Neito5865 commented on routes/web.php
> +        Route::post('create', 'ActivitiesController@store')->name('activity.store');
修正しました！

2024-12-17 10:49 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした😀

2024-12-17 10:49 UTC, merged