パスワード変更機能（Shinya）
yukihiroLaravel/joint_develop pull request #1375
Opened 2024-12-16 14:23 UTC by Shinya-Nakaguchi

## Issue
- Closes #

## 概要
- パスワード変更機能

## 動作確認手順
- Top pageの左のサイドバーの設定から設定画面にいくことを確認。
- パスワード変更を押すと、パスワード変更画面にいくことを確認。
- 現在のパスワード、新しいパスワード、新しいパスワード（確認）を入力し、パスワードが更新されることを確認。
- エラーメッセージが適切に出ることを確認。
	
## 考慮して欲しいこと
- 退会するのリンクは現段階では機能していません。このブランチがマージ後に退会するのViewを作成し退会機能を実装します。
以前、ユーザ編集内に作成した、退会ボタンは削除予定です。

## 確認して欲しいこと
-

2024-12-17 06:18 UTC, yukihiroLaravel requested changes
とてもいいですね！

ただ、細かい点でご指摘させていただきましたので
お手数ですがご確認ください😀

2024-12-17 06:18 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +
新しいパスワード２つが合致していないときの
バリデーションのエラーが
「new passwordとnew password確認が一致しません。」
とnew passwordという英語になっているため、日本語になるようにしましょう！

2024-12-17 06:18 UTC, yukihiroLaravel commented on app/Http/Controllers/SettingsController.php
> +}
今後、設定ページを大きく拡張する必要がある場合は
SettingsControllerとして作ってもいいと思うのですが
現時点ではあくまでユーザ関連の変更の一部のページでしかないので
UsersControllerの１つのメソッドとしてこのindexメソッドを作り直して
SettingsControllerは消してしまってもいいかなと思いました・・・！

2024-12-17 06:18 UTC, yukihiroLaravel commented on routes/web.php
>  });
今後、設定ページを大きく拡張する必要がある場合は
設定のルーティング群として分けてもいいと思うのですが
現時点ではあくまでユーザ関連の変更の一部のページでしかないので
ユーザ編集・更新関連のルーティングとしてこのルーティングを
もっと上に移動させてもいいかなと思いました・・・！

2024-12-19 12:49 UTC, Shinya-Nakaguchi commented on app/Http/Controllers/UsersController.php
> +
新しいパスワードが一致しません。
とエラーが出るように修正いたしました！

2024-12-19 12:49 UTC, Shinya-Nakaguchi commented on app/Http/Controllers/SettingsController.php
> +}
SettingsControllerは削除して、UsersControllerに追加いたしました！

2024-12-19 12:50 UTC, Shinya-Nakaguchi commented on routes/web.php
>  });
ユーザ編集・更新関連のルーティングに移動いたしました！

2024-12-19 20:58 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
お疲れ様でした✨

2024-12-19 20:58 UTC, merged