活動記録の編集・削除機能、マイページでの一覧表示（小宮山）
yukihiroLaravel/joint_develop pull request #1379
Opened 2024-12-19 03:28 UTC by Neito5865

2024-12-19 19:15 UTC, yukihiroLaravel requested changes
素晴らしい出来ですが
１点ご指摘しましたのと、

下記質問事項に関する回答です！
よろしくお願いします！😀

https://www.loom.com/share/9a588c3a7df244ee82f2c376a834be26

2024-12-19 19:15 UTC, yukihiroLaravel commented on app/Http/Controllers/ActivitiesController.php
> +    public function update(ActivityRequest $request, $id)
おそらくActivityRequestにて
更新時も画像が必須となってしまっていたので
画像を更新したくない場合は画像を投稿しなくてすむように
バリデーションを改善しましょう！

2024-12-20 05:27 UTC, Neito5865 commented on app/Http/Controllers/ActivitiesController.php
> +    public function update(ActivityRequest $request, $id)
ActivityRequestを修正しました。
よろしくお願いします！

2024-12-20 11:44 UTC, yukihiroLaravel requested changes
1点だけお願いします

2024-12-20 11:44 UTC, yukihiroLaravel commented on app/Http/Requests/ActivityRequest.php
> +        }
```
        $rulesImageExist = 'required';
        if ($this->isMethod('put')) {
            $rulesImageExist = 'nullable';
        }
        $rules['image'] = $rulesImageExist . '|image|mimes:jpg,jpeg,png|max:2048';
        return $rules;
```

2024-12-20 20:42 UTC, Neito5865 commented on app/Http/Requests/ActivityRequest.php
> +        }
こちら修正しました！

2024-12-20 22:10 UTC, yukihiroLaravel approved these changes

2024-12-20 22:10 UTC, merged