Featuer/kisio/user edit update(たろう）
yukihiroLaravel/joint_develop pull request #139
Opened 2023-01-25 10:34 UTC by afurotanaka

## ssue
-closes#117

 
## 概要
ーユーザ編集画面・更新

## 動作確認手順
ー下記のコマンドを実行
http://localhost:8080にアクセスしてから
http://localhost:8080/users/6/editを実行

## 考慮して欲しい事
データベース上に保存されているかどうか
バリデーションエラーが正確に出るかどうか

##確認してほしいこと
パスワードの確認の記述が正しく出来ているのかどうか
password_confirmationではなくpasswordで大丈夫か確認してもらいたいです。
確認よろしくお願いいたします。

2023-01-26 02:24 UTC, yukihiroLaravel requested changes
> password_confirmationではなくpasswordで大丈夫か確認してもらいたいです。
こちらは現状だとうまくいっていないので、コメントしました！
こちらやその他複数箇所にコメントしましたので、修正願います🙇‍♂️

あと、何度かお伝えしましたが、Conversation のプルリクの最初の概要コメントもうまくマークダウン形式でかけていないですね。

## 見出し
- 項目
```
## 見出し
- 項目
```

のように、１つスペースを開けてから日本語を書くとうまく動作すると思いますのでやってみて下さい！

2023-01-26 02:24 UTC, yukihiroLaravel commented on routes/web.php
> +
ここの空行は不要ですね！

2023-01-26 02:24 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +
この改行も特に不要ですかね

2023-01-26 02:24 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +       $user = \Auth::user();
１７行目で$userが上書きされているので、こちらのコードは意味を成していないですね！
削除しましょう。

2023-01-26 02:24 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +       return view('users.edit', $data);
viewに渡すデータが１つなのであれば
$data に代入しなくてOKだと思います。

このようにしましょう。

```
return view('users.edit', [
       'user' => $user,
]);
```

2023-01-26 02:24 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +            'password' => ['required', 'string', 'min:8'],
```
'password' => ['required', 'string', 'min:8', 'confirmed'],
```

このように、confirmed をつけることで、パスワード確認欄とパスワード欄が合っているかを確認できます！

2023-01-26 02:24 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +
ここの改行も不要ですね

2023-01-26 02:24 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $user = user::findOrFail($id);
動作確認テストされましたか？

ここでuserがUserと大文字になっていないとエラー出ませんか？

2023-01-26 02:24 UTC, yukihiroLaravel commented on resources/views/users/edit.blade.php
> +            <input class="form-control" type="password" name="password" />
Laravel応用講座や新規登録画面のように、
```
name="password_confirmation"
```
としないとダメですね！

2023-01-26 06:58 UTC, afurotanaka commented on routes/web.php
> +
了解しました。修正いたします。

2023-01-26 06:59 UTC, afurotanaka commented on app/Http/Controllers/UsersController.php
> +
了解しました。直しておきます。

2023-01-26 06:59 UTC, afurotanaka commented on app/Http/Controllers/UsersController.php
> +       $user = \Auth::user();
わかりました。

2023-01-26 07:00 UTC, afurotanaka commented on app/Http/Controllers/UsersController.php
> +       return view('users.edit', $data);
確認しました。

2023-01-26 07:02 UTC, afurotanaka commented on app/Http/Controllers/UsersController.php
> +            'password' => ['required', 'string', 'min:8'],
サンプル見ながらやった時に不要かと思ってました。

もう一度、きちんとサンプル見て修正いたします。

2023-01-26 07:02 UTC, afurotanaka commented on app/Http/Controllers/UsersController.php
> +
確認しました。

2023-01-26 07:04 UTC, afurotanaka commented on app/Http/Controllers/UsersController.php
> +        $user = user::findOrFail($id);
updateは、画面表示がなかった為にreturn back();を外してデータベース上に保存されるか確認しました。
なので、エラー表示が出なかったのかと

2023-01-26 07:05 UTC, afurotanaka commented on resources/views/users/edit.blade.php
> +            <input class="form-control" type="password" name="password" />
わかりました。修正いたします。

2023-01-28 14:10 UTC, afurotanaka commented
## issue
- closes#117
## 概要
- ユーザ編集画面・更新修正

## 動作確認手順
- 下記のコマンドを実行

- http://localhost:8080　にアクセスしてトップ画面からログインしていることを確認
- http://localhost:8080/users/16/edit で編集画面にいけることを確認
編集画面からhttp://localhost:8080/users/1/edit でトップ画面にいけることをかくにん

## 考慮して欲しいこと
- ログイン画面がない為、エラーを防ぐためトップ画面に設定してある

## 確認してほしこと
- 他のユーザがログインしている状態で、編集画面にいかないようにするには、この記述が正解なのか知りたいです。
　
- 色々と調べていたらmiddleware, policy , gate、クッキーなどいろいろでてきたので、ただ、新しくmiddlewareを作成したら大変なことになるきがしたのでためせてないです。

　よろしくお願いいたします。

2023-01-28 14:53 UTC, yukihiroLaravel requested changes
本人以外のユーザが
編集画面にアクセスしたときの処理など素晴らしいですね！
詳細はコメントしてますが大体合っています☺️

ほぼ完璧ですが、もう少しだけ修正が必要な箇所がありますので
少し修正願います！

2023-01-28 14:53 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        return view('users.edit', ['user' => $user]);
こちらインデントを１つ下げましょう！

2023-01-28 14:53 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        return redirect('/');
ログインユーザー以外がアクセスした場合を考える処理は
こちら素晴らしいと思います！

ただ、いきなりユーザが
トップページにリダイレクトすると何が起こったかよくわからないのと
お手本通りに動作するように、下記のように書き換えましょう。

`return redirect('/');`
こちらの行を
`abort(404);`
こちらに変更して下さい。

ちょっと難しいですが
本人以外がアクセスした場合４０４というLaravel備え付けのエラーを出してくれる
便利なコードです！

2023-01-28 14:53 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +    }
ここに１行改行があった方がいいですね！

2023-01-28 15:07 UTC, afurotanaka commented on app/Http/Controllers/UsersController.php
> +        return view('users.edit', ['user' => $user]);
わかりました。

2023-01-28 15:07 UTC, afurotanaka commented on app/Http/Controllers/UsersController.php
> +        return redirect('/');
了解しました。

2023-01-28 15:08 UTC, afurotanaka commented on app/Http/Controllers/UsersController.php
> +    }
わかりました。

2023-01-30 03:52 UTC, afurotanaka commented
## issue
- closes#117

## 概要
- ユーザ編集のコントローラーの修正

## 動作確認手順
- ログインしていることを確認して
http://localhost:8080　でログインしていることを確認
http://localhost:8080/users/1/edit 　でエラーメッセージが出る事を確認

## 考慮して欲しいこと
- インデント修正とエラー表示が出来ているかどうかを確認して欲しい

## 確認して欲しいこと
-  考慮して欲しいことと同上

以上

確認よろしくお願いいたします。

2023-01-30 06:49 UTC, yukihiroLaravel requested changes
１点だけ修正願います！

2023-01-30 06:49 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +            abort(404);
こちらムダに１つインデントが付いてしまっているので削除して下さい！

2023-01-31 03:18 UTC, afurotanaka commented on app/Http/Controllers/UsersController.php
> +            abort(404);
確認しました

2023-01-31 03:29 UTC, afurotanaka commented
## issue
- closes#123

## 概要
- インデントの修正

## 動作確認手順
- 今回はインデントの修正のため、動作手順なし

## 考慮して欲しいこと
- app/http/controllers/UsersController.php
インデントの修正が出来ているかどうか

## 確認してほしいこと
- 今回は、インデントの修正の為に特になし

2023-01-31 07:59 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
お疲れ様でした⭐️

2023-01-31 07:59 UTC, merged