#95 posts（投稿）テーブルのマイグレーションとシーダー作成(yurika)
yukihiroLaravel/joint_develop pull request #1393
Opened 2024-12-30 04:59 UTC by yurikashley

## issue
-Closes #95

## 概要
-posts（投稿）テーブルのマイグレーションとシーダー作成

##動作確認手順
-下記コマンドを実行。
php artisan db:seed --class=PostsTableSeeder
シーダーの作成が成功していることを確認。

## 確認してほしいこと
-シーダーの下記の箇所について、追加した方が良いものがあれば教えてほしいです。
```
public function run()
    {
        for ($i = 1; $i <= 10; $i++) {//ここから追加
            DB::table('posts')->insert([
                'user_id' => $i,
                'content' => 'これは最初の投稿の内容です。',
                'title'=>'string',
                'created_at' => now(),
                'updated_at' => now()
            ]);
        }
    }
```

2024-12-30 08:25 UTC, yukihiroLaravel requested changes
いくつかご指摘しましたのでご確認ください！

2024-12-30 08:25 UTC, yukihiroLaravel commented on database/migrations/2024_12_29_034432_create_posts_table.php
> +            $table->string('title',140);//タイトル文字数制限
コーディング規約的に、140の前に半角スペースを１つ入れるべきかと思います。
ただ、最初はお手本のアプリと同じ内容を目指して実装するので
それに当たってはtitleカラムはなしで、contentのみでいいかと思います。

2024-12-30 08:25 UTC, yukihiroLaravel commented on database/migrations/2024_12_29_034432_create_posts_table.php
> +            $table->text('content');// 投稿の内容　文字数制限なし
お手本のアプリだと140文字以上の文字数だと
投稿できないようエラーが出るようになっているので

`$table->string('content', 140);`

このようにしましょう。

2024-12-30 08:25 UTC, yukihiroLaravel commented on database/migrations/2024_12_29_034432_create_posts_table.php
> +            $table->timestamps();
論理削除にするのなら
`$table->softDeletes();`
これもカラムに必要となります！

2024-12-30 08:25 UTC, yukihiroLaravel commented on database/migrations/2024_12_29_034432_create_posts_table.php
> +            $table->timestamps();
Laravel応用の４章と同じように、下記の外部キー制約を記述しましょう。

`$table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');`

ただ、usersテーブルがマージされていない現段階でこれを記載すると
うまくうごかないので、jinさんのタスクがマージされるまでは
一旦下記のようにコメントアウトして記述しておく、ということでいいと思います。

`// $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');`

2024-12-30 08:25 UTC, yukihiroLaravel commented on database/seeds/DatabaseSeeder.php
> +         $this->call(PostsTableSeeder::class);
細かいですが、コーディング規約的に
半角スペース１つ分左に移動させましょう。
（１４行目の頭の半角スペースを１つ削除）

2024-12-30 08:25 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +                'updated_at' => now()
上のカラム変更に合わせて
シーダーのカラムの中身も変更しましょう！

2024-12-30 08:25 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +        for ($i = 1; $i <= 10; $i++) {//ここから追加
今後の話ですが、
１ページ１０投稿なので
２ページ目も表示できるよう
全体として１１投稿が出るように
`for ($i = 1; $i <= 11; $i++)`
このようにしましょう！

2024-12-30 08:27 UTC, yukihiroLaravel requested changes
いくつかご指摘しましたのでご確認ください！

また、プルリクの最初のコメント部分は
-posts（投稿）テーブルのマイグレーションとシーダー作成
↑
このハイフンとpostsの間にスペースを入れるようにしましょう！
そうでないとうまく箇条書きで表示されないので。

2024-12-30 11:48 UTC, yurikashley commented on database/migrations/2024_12_29_034432_create_posts_table.php
> +            $table->string('title',140);//タイトル文字数制限
コーディング規約にて140の前に半角スペース入力いたしました。
しかし、
....create_posts_table.phpの$table->string('title', 140);//タイトル文字数制限
こちらのtitleカラムを削除してもよろしいのでしょうか？

2024-12-30 11:53 UTC, yurikashley commented on database/migrations/2024_12_29_034432_create_posts_table.php
> +            $table->text('content');// 投稿の内容　文字数制限なし
ご指摘ありがとうございます。

こちら19行目を修正いたしました。

2024-12-30 12:01 UTC, yurikashley commented on database/migrations/2024_12_29_034432_create_posts_table.php
> +            $table->timestamps();
コメントアウトで上記を記載しました。

 Jinさんのタスクがマージされたら外したいと思います。

2024-12-30 12:05 UTC, yurikashley commented on database/seeds/DatabaseSeeder.php
> +         $this->call(PostsTableSeeder::class);
14行目の// $thisの間の半角スペースを削除しました。

2024-12-30 12:24 UTC, yurikashley commented on database/seeds/PostsTableSeeder.php
> +        for ($i = 1; $i <= 10; $i++) {//ここから追加
全体として11投稿が表示されるように
14行目をfor ($i = 1; $i <= 11; $i++)に変更しました。

2024-12-30 12:57 UTC, yurikashley commented on database/seeds/PostsTableSeeder.php
> +                'updated_at' => now()
論理削除を21行にこのように追加しました。

'softDeletes'=> now(),
このような修正でよろしかったでしょうか？

2025-01-01 00:15 UTC, yukihiroLaravel requested changes
変更が反映されていないですが、
ゆりかさんの認識が間違っているところがありましたので
GitHubに記載しました。
ご確認ねがいます！

2025-01-01 00:15 UTC, yukihiroLaravel commented on database/migrations/2024_12_29_034432_create_posts_table.php
> +            $table->string('title',140);//タイトル文字数制限
はい、削除お願いします！

2025-01-01 00:15 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +                'updated_at' => now()
いえ、論理削除のカラムに値を入れると投稿自体が削除されてしまうので
そのような修正はダメですね。

論理削除は入れなくてOKで、
マイグレーションの方で削除したtitleカラムなどを
シーダーでも削除するなどの対応が必要です！

2025-01-02 20:57 UTC, yukihiroLaravel requested changes
いくつかご指摘しましたのでご確認の上
修正お願いします！

2025-01-02 20:57 UTC, yukihiroLaravel commented on database/seeds/DatabaseSeeder.php
> +        //$this->call(PostsTableSeeder::class);
こちらのコメントアウトは外して
こういう状態にしないといけませんね！

```
public function run()
{
        $this->call(UsersTableSeeder::class);
        $this->call(PostsTableSeeder::class);
```

2025-01-02 20:57 UTC, yukihiroLaravel commented on database/migrations/2024_12_29_034432_create_posts_table.php
> +            $table->text('content');// 投稿の内容　文字数制限なし
`$table->string('content', 140);`
このようにできていないですね・・・！

2025-01-02 20:57 UTC, yukihiroLaravel commented on database/migrations/2024_12_29_034432_create_posts_table.php
> +            //$table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
今はJINさんのタスクがマージされているので
このコメントアウトを外してから、下記の動画をもとに最新の
develop_b_shimotsuki_dra
をpullしてマージしましょう。
その際にコンフリクト解消も下記動画をもとに行いましょう！

④コンフリクト解消方法解説動画
https://youtu.be/xS2Z54yKv7I

2025-01-02 20:57 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +        }
Jinさんが言って来れていた通り、

> テーブルに外部キー制約を付ける必要があると、以前ゆきひろさんから指摘があったと思います。
> 僕のコードがマージされた時点では、ユーザーIDは確かに5まででした。シーダーを作成する際に、ユーザーIDが6以上存在する場合、エラーが発生しないか少し気になりましたので、共有させていただきます。

ゆりかさんのコードですと、user_idが現在1~11まで存在してしまうので
外部キー制約のコメントアウトを外すとエラーになってしまいます。
なので、for文で書くのをやめて、シンプルに下記のように書いた方がいいと思いました！

```
{
            DB::table('posts')->insert([
                'user_id' => 1,
                'content' => 'これは1番目の投稿の内容です。',
                'created_at' => now(),
                'updated_at' => now()
            ]);
            DB::table('posts')->insert([
                'user_id' => 2,
                'content' => 'これは2番目の投稿の内容です。',
                'created_at' => now(),
                'updated_at' => now()
            ]);
            DB::table('posts')->insert([
                'user_id' => 3,
                'content' => 'これは3番目の投稿の内容です。',
                'created_at' => now(),
                'updated_at' => now()
            ]);
            DB::table('posts')->insert([
                'user_id' => 4,
                'content' => 'これは4番目の投稿の内容です。',
                'created_at' => now(),
                'updated_at' => now()
            ]);
            DB::table('posts')->insert([
                'user_id' => 5,
                'content' => 'これは5番目の投稿の内容です。',
                'created_at' => now(),
                'updated_at' => now()
            ]);
            DB::table('posts')->insert([
                'user_id' => 1,
                'content' => 'これは6番目の投稿の内容です。',
                'created_at' => now(),
                'updated_at' => now()
            ]);
            DB::table('posts')->insert([
                'user_id' => 2,
                'content' => 'これは7番目の投稿の内容です。',
                'created_at' => now(),
                'updated_at' => now()
            ]);
            DB::table('posts')->insert([
                'user_id' => 3,
                'content' => 'これは8番目の投稿の内容です。',
                'created_at' => now(),
                'updated_at' => now()
            ]);
            DB::table('posts')->insert([
                'user_id' => 4,
                'content' => 'これは9番目の投稿の内容です。',
                'created_at' => now(),
                'updated_at' => now()
            ]);
            DB::table('posts')->insert([
                'user_id' => 5,
                'content' => 'これは10番目の投稿の内容です。',
                'created_at' => now(),
                'updated_at' => now()
            ]);
            DB::table('posts')->insert([
                'user_id' => 1,
                'content' => 'これは11番目の投稿の内容です。',
                'created_at' => now(),
                'updated_at' => now()
            ]);
}
```

2025-01-05 05:14 UTC, yukihiroLaravel requested changes
コンフリクト解消などはうまくできていますね😃

ただ、また少しコメントしました！
再度お手数ですがご確認ねがいます！！

2025-01-05 05:14 UTC, yukihiroLaravel commented on database/migrations/2024_12_29_034432_create_posts_table.php
> +            $table->text('content');// 投稿の内容　文字数制限なし
`$table->string('content', 140);`
このカラムがすでに存在するので、
下記のカラムは不要になりますね・・・！
下記は削除しましょう！
`$table->text('content');// 投稿の内容　文字数制限なし`

2025-01-05 05:14 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +        }
この80行目の } は
コーディング規約的に
スペース４つ分左に移動させましょう！

2025-01-05 20:25 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした✨

2025-01-05 20:25 UTC, merged