Feature/jin/show top page
yukihiroLaravel/joint_develop pull request #1394
Opened 2024-12-30 14:19 UTC by Jin6hara

## トップページの要件定義
1.トップには最近新規登録した最後の3ユーザーのプロファイル写真、名前を含め「が新規登録しました。」と表示する
2.投稿を最新の方から上に表示していく（プロファイル写真、ユーザー名を含む）。
3.わかりやすくするため、5行により次のページへ移ることにする。

※トップページのプロトタイプはモックアップファイル、それに基づき、上記の3点を追加しました。
※効果を見やすいように、自分用に「tempLayout」（従来のlayout.app）をモックアップに基づき作成しました。まささんの分出来上がり次第、入れ替える予定です。

## トップページ仮内容の作成
下記の仮内容は要件定義中の項目2と3をうまく実現できることを確認するために先に埋め込んだものです。下記の変数定義に苦戦しておりました。レビューの対象になるかどうかはわからないですが、本来でしたらもっといい方法があったのでしょうか？

```
@php
$factors = [];

foreach ($users as $user) {
$factors[] = [
'nickname' => $user->nickname,
'comment' => $user->comment . "{$user->nickname}です！<br>よろしく！",
'email' => $user->email,
'updated_at' => $user->updated_at
];
}
@endphp
```
※コメント投稿できるようになれば、順番は$comment->created_atを利用し、コメントは$user->commentで引き出し、$commentと$userの定義はコントローラ側で再度行う予定です。

## トップページのエラー文
モックアップの中に`<div class="w-75 m-auto">エラーメッセージが入る場所</div>`というのがありましたのでそこに記述しました。

ご確認お願い致します。

2024-12-30 19:50 UTC, yukihiroLaravel requested changes
いくつか下記動画とGitHubにてコメントしましたのでご確認ください！

https://www.loom.com/share/2d9ecd9081f245faa4c08abbdcaf959c

> git push origin後、すぐにdevelop_b_shimotsuki_draに切り替えました。不思議なのがwelcome.blade.phpだけが切り替え前の内容になっており、その他は初期化されてます。

ブランチを切り替えるとdevelop_bにマージされていないものが
初期化されるのは正常ですね。
ただ、welcome.blade.phpだけが切り替え前の内容になるのは原因がはっきり不明ですが
おそらくwelcome.blade.phpだけがcommitできていない状態でブランチ切り替えると
welcome.blade.phpの内容を引き連れてブランチを移動してしまうのが原因かと思います。
なのでブランチ移動する際には誤ってコミット忘れがないかどうか？を必ず確認しましょう！

2024-12-30 19:50 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        return view('welcome', compact('newUsers', 'users'));
yurikaさんのタスクがマージされないと作りにくいが、
usersではなくpostsをデータベースから取ってきて表示する

2024-12-30 19:50 UTC, yukihiroLaravel commented on app/User.php
> +    use SoftDeletes;
最新のdevelop_b_shimotsuki_dra
をpullしてマージすれば消えるはず

2024-12-30 19:50 UTC, yukihiroLaravel commented on resources/views/components/error_messages.blade.php
> +@endif
現時点では不要

2024-12-30 19:50 UTC, yukihiroLaravel commented on resources/views/components/status.blade.php
> +@endif
現時点では不要

2024-12-30 19:50 UTC, yukihiroLaravel commented on resources/views/components/success.blade.php
> +@endif
現時点では不要

2024-12-30 19:50 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +</div>
現時点では不要

2024-12-30 19:50 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
モックアップの投稿表示部分に基づき
resources/views/posts/posts.blade.phpを作り
その中に記述する。

その際に、Gravatorをインストールして
src="https://www.gravatar.com/avatar/
このような記述がなくてもアイコンが表示されるようにする

2024-12-30 19:50 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +class UsersController extends Controller
yurikaさんのタスクがマージされないと作りにくいが、
usersではなくpostsをデータベースから取ってくる形にすると
UsersControllerでもなくなる

2024-12-30 19:50 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +</div>
現時点では不要

2024-12-30 19:50 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +@endphp
・インデントがおかしい
・users やuserではない

2025-01-05 23:01 UTC, Jin6hara commented
## Controllerの変更
- UsersからPostsに変更。
- したがって、Routeも変更。
- Viewに渡す変数も$userから$postに変更。

## config/gravatar.phpの追加
- src="{{ Gravatar::src(投稿者のメールアドレス, 55) }}"の書式で表示させるにあたり、僕の場合はgravatar.phpをconfigに追加する必要がありました。
- 僕の場合、```composer install```だけじゃエラーが出ていたため```composer update thomaswelton/laravel-gravatar```も実施し、結果的にcomposer.lockにも一部gravatarに関する内容が追加されています。

## ファイル・内容削除 
- 指摘いただいた現状必要のないものは基本全部削除しました。
- 混乱を防ぐためにtempLayoutも削除しました。

2025-01-06 00:07 UTC, yukihiroLaravel requested changes
とてもいいですね！

少しだけコメントしましたのでご確認ください😃

2025-01-06 00:07 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $posts = Post::orderBy('created_at', 'desc')->paginate(10);
投稿日時が被った場合（今回のようにシーダーだと同時刻に登録される場合も含む）
id順の方がいいので、下記のように書きましょう！

$posts = Post::orderBy('id', 'desc')->paginate(10);

2025-01-06 00:07 UTC, yukihiroLaravel commented on resources/views/post/post.blade.php
> +            </div>
ここはJINさんのタスクではないのですが
現時点で削除ボタンなどが見えるのは良くないので
ログインしていて、かつ
本人の投稿の下にのみ、削除ボタン・編集ボタンが出現するようにしましょう！

2025-01-06 00:07 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +</div>
ここではなく、post.blade.php に
ページネーションを置くようにしたほうが
他ページでpost.blade.phpを使うパターンを考えると
よりいいですね！

2025-01-06 00:07 UTC, yukihiroLaravel commented on resources/views/post/post.blade.php
> +<div class="m-auto" style="width: fit-content"></div>
こちら２４行目に
ページネーションを置くようにしたほうが
他ページでpost.blade.phpを使うパターンを考えると
よりいいですね！

2025-01-06 00:23 UTC, Jin6hara commented
## paginationの場所を変更
- welcome.bladeからpost.bladeに移しました。
## PostsControllerの変更
- 表示順番を変更（created_atをidに変更しました）。
## ボタン表示の変更
- 下記のif文で囲みました。
```
@if(Auth::check() && Auth::user()->id === $post->user_id)
...
@endif
```

2025-01-06 12:58 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした✨

2025-01-06 12:59 UTC, merged