#114 トップページの投稿表示（岡田）
yukihiroLaravel/joint_develop pull request #140
Opened 2023-01-25 14:03 UTC by yusukeokada2125

issue
- Closes #114

概要
- トップページの投稿表示

動作確認手順
- トップページ画面での確認
①<http://localhost:8080>を入力し、トップ画面でアイコン、ユーザ名、投稿内容、投稿時間が表示されることを確認（<http://localhost:8088>のusersテーブル、postsテーブルに同じ）
②下部のページリングで、10人目以降のユーザが次のページに表示されていることを確認

- tinkerで新しい投稿を行って、トップページに表示されるか確認
tinkerで下記内容を記述
①$user = User::find(1)　でユーザ1番を指定。
②use App\Post;　、$post = new Post;　でインスタンス作成。
③$post->content = '投稿内容';　で投稿内容を記述
④$post->save();　でデータベース上へ保存。
⑤<http://localhost:8088>のPostsテーブルへ保存されていることを確認。
また、<http://localhost:8080>のトップページで一番上（最新）の投稿として表示されることを確認

- ログイン後の投稿表示の確認
①トップページのログインボタンから任意の（<http://localhost:8080>上に保存されているユーザ）ユーザでログイン。
②トップページへ遷移し、"○○"について140字以内で会話しよう！の下に投稿フォームと投稿ボタンが表示されることを確認。

考慮してほしいこと
- route/web.phpのUsersControllerのルーティングは使用しなくなったのですが、一応残しているためコメントアウトしています。
- resources/views/posts/posts.blade.phpの14行目〜20行目は担当外だと思いましたが、モックアップに含まれており、今後使いますのでコメントアウトしています。
- paginateは、仮で9人のユーザにしています。

確認してほしいこと
- 表示させているページの中で、余分なもの、不要なものがあればご教示お願いします。

2023-01-26 01:02 UTC, Osk0830 requested changes
お疲れ様でした！
とても良くできていると思います！

少しコメントしましたので、確認よろしくお願いします！

2023-01-26 01:02 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                </div> -->
- ここはコメントアウトするのではなく、下記のように、ログインしている状態にありなおかつログインしている本人の投稿である場合は各ボタンが表示され、ログインしていない場合や他人の投稿である場合はボタンが表示されないようにしてみてくださいね。

　[![Image from Gyazo](https://i.gyazo.com/846d2612c20509e460eeb8ab590cb517.png)](https://gyazo.com/846d2612c20509e460eeb8ab590cb517)

2023-01-26 12:12 UTC, yusukeokada2125 commented on resources/views/posts/posts.blade.php
> +                </div> -->
承知しました！

2023-01-27 12:16 UTC, Osk0830 requested changes
お疲れ様でした！
こちら実装自体はOKそうですね！ただ、インデントが少しガタガタなので、その点だけ修正頂ければと思います。

2023-01-27 12:16 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +            </div>
- こちら実装自体はOKそうですね！ただ、インデントが少しガタガタなので、その点だけ修正頂ければと思います。

2023-01-27 12:59 UTC, yusukeokada2125 commented on resources/views/posts/posts.blade.php
> +            </div>
インデントの位置の修正、承知しました。

2023-01-27 23:51 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらしっかりと修正できているのでマージしますね！
引き続き頑張ってくださいね！

2023-01-27 23:51 UTC, merged