#118 ユーザ編集画面・更新（福士）
yukihiroLaravel/joint_develop pull request #141
Opened 2023-01-25 22:36 UTC by mao-fukushi

## issue
- Closes #118 

## 概要
-　ユーザ編集画面・更新

## 動作確認手順
- １．Topic Postsトップページを表示する。<http://localhost:8080/>

## 考慮してほしいこと
-　担当した部分以外の動作が想定していない動作になることがあります。
- 　ログイン、トップページ表示　など
- 　プルリクを上げる時、トップページ表示の＃を消す時間がなかったです。

## 確認してほしいこと
-　他に良い書き方がありましたらご教示ください。
-  ルーターに記述したルーティングページに飛ばなかったので、どのようにしたら飛ぶのかご教示ください。

以上、よろしくお願い致します。

2023-02-06 09:50 UTC, mao-fukushi commented
@Osk0830 さん
コンフリクトの解消と併せて、外部キー制約のコメントアウトを元に戻しました。
コンフリクトがweb.phpだったこともあり、ルーティングの順番を少し整えました。

2023-02-06 12:53 UTC, Osk0830 requested changes
体調がすぐれない中お疲れ様でした！
いくつかコメントしましたので、確認よろしくお願いします！

2023-02-06 12:53 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +use App\Http\Controllers\Controller;
- このClass自体がControllersというnamespaceに置かれていて、11行目のextendsでControllerクラスを継承している感じです。なので、useの記述は追記しなくても大丈夫そうですね。

2023-02-06 12:53 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +use Illuminate\Foundation\Auth\AuthenticatesUsers;
- こちらのuseの記述は不要ではないでしょうか？

2023-02-06 12:53 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +    use AuthenticatesUsers;
- 上に同じです。いかがでしょう？

2023-02-06 12:53 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +
- こちら、要りますでしょうか？

2023-02-06 12:53 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +    }
- 22行目で `$user`に値を代入して、すぐに23行目で値を書き換えていますね。。いずれかの記述が不要ではないでしょうか？
- ユーザー情報の編集画面なので、ログインしている本人のページしか表示できないようにする必要があります。今の状態ですと、仮にid=1のユーザーとしてログインしている状態で、ブラウザで、/users/2/editと叩いても表示されてしまうと思います。この点、改善してみてくださいね。

2023-02-06 12:53 UTC, Osk0830 commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
- この状態ですと、仮にemailは変更しなくてもいい場合でも、一度使ったものは使えない、という状態になってしまいそうですね。ユニークじゃなきゃ行けないけど、編集しようとしている本人のものと同じ場合は例外、というバリデーションになる必要がありそうですね。

2023-02-06 12:53 UTC, Osk0830 commented on app/Http/Requests/UserRequest.php
> +            'password' => 'パスワード',
- これらは、下記ファイルで既に指定されているので、変更したい場合を除いては、記述は不要です。

　[![Image from Gyazo](https://i.gyazo.com/c34cb4ac278a7b9f398370dd5d29d590.png)](https://gyazo.com/c34cb4ac278a7b9f398370dd5d29d590)

2023-02-06 12:53 UTC, Osk0830 commented on resources/views/users/edit.blade.php
> +    @if (Auth::id() === $user->id)
- 本来的に、上に書いたように、コントローラーで、表示できる人の制限をかけるので、こちらではifでの表示切り替えは不要ですね。

2023-02-06 12:53 UTC, Osk0830 commented on resources/views/users/edit.blade.php
> +                <input type="hidden" name="id" value="{{ old('id', $user->id) }}">
- 4行目で`route()`メソッドの引数としてidの値を渡しているかと思います。そうなると<input>でさらに渡す必要があるか検討してみてくださいね。また、hiddenの状態で、`old()`とかはありますでしょうか？

2023-02-06 12:53 UTC, Osk0830 commented on routes/web.php
>  //Route::get('/', 'UsersController@index');
- 41行目も要らなそうなので、よかったら削除しといてください。

2023-02-06 12:53 UTC, Osk0830 commented on routes/web.php
> +        Route::post('{id}/edit', 'UsersController@store')->name('users.store');
- URIの`edit`は冗長のような感じがしますが、いかがでしょう？

2023-02-07 13:57 UTC, mao-fukushi commented on app/Http/Controllers/UsersController.php
> +use App\Http\Controllers\Controller;
7行目のコントローラーのuseの記述を削除しました。

2023-02-07 14:17 UTC, mao-fukushi commented on app/Http/Controllers/UsersController.php
> +use Illuminate\Foundation\Auth\AuthenticatesUsers;
９行目の下記の記述を削除しました。
use Illuminate\Foundation\Auth\AuthenticatesUsers;

2023-02-07 14:19 UTC, mao-fukushi commented on app/Http/Controllers/UsersController.php
> +    use AuthenticatesUsers;
おっしゃる通りです。
９行目に記述してあったuseの関連記述なので、削除しました。

2023-02-07 14:22 UTC, mao-fukushi commented on app/Http/Controllers/UsersController.php
> +
web.phpのルーティングで不要となっていた箇所と同じなので、いらないですね。
以下の記述を削除しました。

```
public function index()
    {
        return view('welcome');
    }
```

2023-02-07 14:31 UTC, mao-fukushi commented on routes/web.php
>  //Route::get('/', 'UsersController@index');
41行目の記述は削除しておきました。
`//Route::get('/', 'UsersController@index');`

2023-02-12 13:51 UTC, mao-fukushi commented on routes/web.php
> +        Route::post('{id}/edit', 'UsersController@store')->name('users.store');
31行目の/editの記述は削除しました。

2023-02-12 14:53 UTC, mao-fukushi commented on app/Http/Controllers/UsersController.php
> +    }
22行目の記述を有効にした場合
　$userにログイン認証したユーザが代入される
23行目の記述を有効にした場合
　$userにユーザ登録済ユーザが代入される
　
今の記述は、23行目の記述が有効になっているため、
ログインしているユーザ以外のユーザが他のユーザの編集画面を表示できるようになっていると理解しました。

よって、22行目の記述を有効にし、23行目の記述を削除します。

2023-02-12 15:17 UTC, mao-fukushi commented on app/Http/Requests/UserRequest.php
> +            'password' => 'パスワード',
[app/Http/Requests/UserRequest.php]のattributesの記述箇所について、
今回のファイル記述ではvalidation.phpのattributesのデフォルトのまま使うため変更をしないので、
UserRequest.phpのattributesの記述は削除しました。

2023-02-12 16:27 UTC, mao-fukushi commented on resources/views/users/edit.blade.php
> +    @if (Auth::id() === $user->id)
/users/edit.blade.phpの3行目にあった、
ifでの表示切り替えは削除しました。

2023-02-12 16:38 UTC, mao-fukushi commented on resources/views/users/edit.blade.php
> +                <input type="hidden" name="id" value="{{ old('id', $user->id) }}">
4行目ですでにroute()メソッドの引数としてidを渡しているため、
・10行目のvalueの記述でさらに渡している記述（$user->id部分）が不要
・10行目のvalueのold（）の記述は、ユーザーが入力後に入力値を保持する要件がないため、不要
・input type="hidden"の記述が、ユーザが気にする部分ではなくサーバへ送りたい情報を記述するためのものであり、value属性は省略可能なことが分かった。今回、value属性に設定したい項目がないため、削除しました。
[https://catnose.me/learning/html/input-hidden](url)

2023-02-12 18:45 UTC, mao-fukushi commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
30行目のemailのユニークの記述を見直しました。

2023-02-12 18:50 UTC, mao-fukushi commented
> 体調がすぐれない中お疲れ様でした！ いくつかコメントしましたので、確認よろしくお願いします！

レビューいただきありがとうございます！
コメントを拝見して、コードを見直しました。
ご確認のほどお願い致します。

2023-02-15 01:41 UTC, Osk0830 approved these changes
お仕事お忙しい中お疲れ様でした！
レビュー遅くなってすみません！

しっかり修正できていると思いますので、マージしますね！

引き続き頑張ってくださいね！

2023-02-15 01:41 UTC, merged

2023-02-16 02:59 UTC, mao-fukushi commented
> お仕事お忙しい中お疲れ様でした！
> 
> レビュー遅くなってすみません！
> 
> 
> 
> しっかり修正できていると思いますので、マージしますね！
> 
> 
> 
> 引き続き頑張ってくださいね！

ご多忙の中、レビュー頂きありがとうございます。
引き続き、投稿削除の作業を進めていきます！