#113 トップページの投稿表示（大坪）
yukihiroLaravel/joint_develop pull request #142
Opened 2023-01-30 11:42 UTC by shunsukeotsubo

## issue
- Closes #113 

## 概要
- トップページの投稿表示

## 動作確認手順
- ①http://localhost:8080/ を入力し、トップ画面でユーザー名、アイコン画像、投稿内容、投稿時間が表示されることを確認
- ②ページネーションの位置が中央になっていること、２ページ目に行けることを確認
- ③tinkerで新規投稿後、トップページで一番上に新規投稿が表示されるか確認

  tinker記述内容
- ①use App\User
- ②$use = User::Find(1);
- ③use App\Post;
- ④$post = new Post;
- ⑤$post->content = '投稿内容';
- ⑥$post->user_id = user->id;
- ⑦$post->save();
- ⑧http://localhost:8080/ で新規作成投稿の確認

## 考慮して欲しいこと
- 特になし

## 確認して欲しいこと
- トップページの投稿欄の枠の大きさはどこの作業の担当になりますでしょうか。
- welcome.blade.phpの9行目でエラーメッセージが表示されるようにincludeしたのですが、コードの書き方と挿入箇所は合っていますでしょうか。
- 余計な記述がありましたら教えていただきたいです。よろしくお願いします。

2023-01-30 14:50 UTC, yukihiroLaravel requested changes
修正願います！

2023-01-30 14:50 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
>  {
// TODO: 中身は●●機能実装の際に記述

2023-01-30 14:50 UTC, yukihiroLaravel commented on app/Http/Controllers/Auth/UsersController.php
> +    }
ファイルごと不要

2023-01-30 14:50 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +<ul class="list-unstyled">
インデント１つ下げる

2023-01-30 14:50 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +                    <p class="text-muted">{{$post->created_at}}</p>
{{ $post->content }}

2023-01-30 14:50 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
>                  </div>
インデント１つ下げる

2023-01-31 08:50 UTC, shunsukeotsubo commented on app/Http/Controllers/Auth/UsersController.php
> +    }
修正します。

2023-01-31 08:50 UTC, shunsukeotsubo commented on app/Http/Controllers/UsersController.php
>  {
修正します

2023-01-31 08:50 UTC, shunsukeotsubo commented on resources/views/posts/posts.blade.php
> +<ul class="list-unstyled">
修正します

2023-01-31 08:50 UTC, shunsukeotsubo commented on resources/views/posts/posts.blade.php
> +                    <p class="text-muted">{{$post->created_at}}</p>
修正します

2023-01-31 08:50 UTC, shunsukeotsubo commented on resources/views/welcome.blade.php
>                  </div>
修正します

2023-02-02 04:24 UTC, yukihiroLaravel requested changes
２点だけコメント修正願います！

2023-02-02 04:24 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +use App\User;
なぜか２回 use App\User; が書かれているので、
１回は消して下さい！

このあたりも、プルリク挙げた際にご自身で気づければなお良いですね✨

2023-02-02 04:24 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +                    <p class="mb-2">{{ $post->content }}</p>
ここだけ

`<p class="mb-2">{!! nl2br(e($post->content)) !!}</p>`

このようにしておきましょう！
こうすることで、投稿中の改行が反映されるようになります！

2023-02-02 05:46 UTC, yukihiroLaravel approved these changes
これでOKですのでマージしました！
お疲れ様でした✨

2023-02-02 05:46 UTC, merged