Featuer/kisio/user_ delete(たろう）
yukihiroLaravel/joint_develop pull request #144
Opened 2023-01-31 09:40 UTC by afurotanaka

## issue
- closes#125

## 概要
- ユーザ退会

## 動作確認手順
- http://localhost:8080 でログインしていることを確認
- http://localhost:8080/users/{id}/edit で編集画面に移動した事を確認して退会を実行
- http://localhost:8088 でデータベース上にuserとpost履歴がない事を確認

## 考慮して欲しいこと
データベース上にuserとpost履歴がない事を確認

## 確認して欲しいこと
コードが出来ているのか確認して欲しい

以上

よろしくお願いいたします

2023-02-01 06:26 UTC, yukihiroLaravel requested changes
すばらしいですね！

１点きれいにコードを書くところだけ修正いただければOKです☺️

2023-02-01 06:26 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $user -> forceDelete();
`$user->forceDelete();`
このように、アロー演算子で繋ぐ時は前後にスペースは不要ですので
スペースを消しましょう！

また forceDelete で物理削除するのでもOKですが
app/User.php に下記のようなメソッドをつくることで
ユーザが所有している post のデータを削除する方法もあります。
参考までに覚えておいて下さい✨

```
public static function boot()
{
        parent::boot();

        static::deleted(function ($user) {
            $user->posts()->delete();
        });
}
```

2023-02-02 09:28 UTC, afurotanaka commented on app/Http/Controllers/UsersController.php
> +        $user -> forceDelete();
記述かくにんしました。

public static function boot()
{
        parent::boot();

        static::deleted(function ($user) {
            $user->posts()->delete();
        });
}
bootというモデルの初期化処理を行い、ユーザが持っているポストを削除するという意味なんですね。
色々と調べて勉強になりました。
やっぱり、クラスとオブジェクト余り理解できてなかったので、もう一度、ゆきひろさんのphpの動画拝見しました。
＿＿constructの勉強にもなりました。
やっぱり、クラスオブジェクト難しいですね涙
しっかりと理解できるように頑張ります。

2023-02-02 09:34 UTC, afurotanaka commented
## issue
- closes#125
## 概要
- コントローラーのインデントの修正
## 動作確認手順
- 今回は、コントローラーのインデントの修正のためになし
## 考慮して欲しいこと
- 今回は、インデントの修正の為に特になし
## 確認して欲しいこと
- 同上

2023-02-02 09:37 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $user -> forceDelete();
頑張りましょう✨

2023-02-02 09:38 UTC, yukihiroLaravel approved these changes
OKですが、コンフリクト解消をお願いします！

2023-02-02 13:57 UTC, yukihiroLaravel approved these changes

2023-02-02 13:57 UTC, merged