#124 投稿編集画面・更新（岡田）
yukihiroLaravel/joint_develop pull request #145
Opened 2023-02-01 12:51 UTC by yusukeokada2125

## issue
- Closes #124

## 概要
- 投稿編集画面・更新

## 動作確認手順
- 編集・更新
① <localhost:8080>にアクセスし、ログインを行う。（データベース上任意のユーザを選択しログイン。ex.ユーザ1番、email：test1@test.com、pass：test1 など）
②ログイン後、ログインユーザのみ編集するボタンが表示されることを確認。
③編集するボタンを押すと、投稿を編集するページへ移ることを確認。
その時、既に投稿した内容がテキストエリア内に保持されていることも確認。
④テキストエリアに文字や数字を入力し、更新するボタンを押すとトップページ遷移し、入力した投稿に変わっていることを確認。
また、 <http://localhost:8088>のpostsテーブルでログインしているuser_idのcontentが更新されていることを確認。

- エラー表示
上記④で、テキストエリア内に何も入力せず更新するボタンを押した場合、バリデーションエラー（投稿必須のエラー）が表示されることを確認。

## 考慮してほしいこと
- 特にありません。

## 確認してほしいこと
- 不要なものがあればご教示お願いします。

2023-02-02 00:18 UTC, Osk0830 requested changes
お疲れ様です！
フォームリクエストも活用できていて、また大筋でできていて、素晴らしいですね！
いくつかコメントしましたので、確認よろしくお願いします！

2023-02-02 00:18 UTC, Osk0830 commented on app/Http/Requests/PostRequest.php
> +        ];
- フォームリクエストを使えていて素晴らしいですね！ただ、投稿には文字数の制限があるかと思うので、そちらにも対応する記述を追加する必要があるかと思います。
- もし可能であればでOKですが、「投稿は必ず`指定してください`」というメッセージだとユーザーに伝わりにくいところもあるので、お手本サイトを少し改良する意味で、「投稿は必ず`入力してください`」とかにしてみるのもいいかもですね。

2023-02-02 00:18 UTC, Osk0830 commented on resources/views/posts/edit.blade.php
> +      <button type="submit" class="btn btn-primary" >更新する</button>
- この辺のインデント、少しだけ揃えましょう。

2023-02-02 00:18 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        ];
- Bladeの方でユーザー情報は特に求めていないようですし、必要であればBladeの方でもログインしているユーザー本人の情報は容易に取り出せるので、ここでユーザー情報をBladeに渡す処理は、今回は不要ではないでしょうか？
- 今の状態ですと、ログインさえしていれば、他人の投稿も編集できてしまいます。例えば、1番のユーザーでログインしている状態で、

　http://localhost:8080/posts/2/edit

のようにブラウザで叩くと、2番のユーザーの投稿の編集ページにアクセスでき、編集もできてしまいます。
本人だけが編集ページを開けるよう、処理を追加しましょう！

2023-02-02 00:18 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        $post->save();
- こちらも、`edit()`同様、本人だけがアクセスできるよう処理を追加してみてください。

2023-02-03 11:16 UTC, yusukeokada2125 commented on app/Http/Requests/PostRequest.php
> +        ];
・文字数制限140文字以内となるように修正します。
・エラーメッセージの変更を行ってみます。

2023-02-03 11:17 UTC, yusukeokada2125 commented on resources/views/posts/edit.blade.php
> +      <button type="submit" class="btn btn-primary" >更新する</button>
11行目のインデントを修正いたします。

2023-02-03 11:20 UTC, yusukeokada2125 commented on app/Http/Controllers/PostsController.php
> +        ];
・編集画面ではユーザー情報が特に必要ありませんね。23行目は残し修正します。
・ログインユーザー以外が編集できてしまう部分修正します。

2023-02-03 11:21 UTC, yusukeokada2125 commented on app/Http/Controllers/PostsController.php
> +        $post->save();
edit()と同様の処理でよろしいでしょうか？同じ条件分を追加します。

2023-02-06 01:25 UTC, Osk0830 approved these changes
お疲れ様でした！
しっかり修正できているので、こちらマージしますね！
引き続き頑張っていきましょう！

2023-02-06 01:25 UTC, merged