#123 投稿編集画面・更新
yukihiroLaravel/joint_develop pull request #148
Opened 2023-02-09 09:56 UTC by shunsukeotsubo

## issue
- Closes #123

## 概要
- 投稿編集画面・更新

## 動作確認手順
- ログイン後トップページの編集ボタンから編集画面に移行できるか確認
- トップページのユーザー詳細ページに移行し、編集ボタンから編集画面に移行できるか確認
- Adminerで投稿内容を編集し、トップページで投稿内容が変わっているかを確認

## 考慮して欲しいこと
- 特になし

## 確認して欲しいこと
- 特になし

2023-02-09 13:57 UTC, yukihiroLaravel requested changes
修正お願いします

2023-02-09 13:57 UTC, yukihiroLaravel commented on resources/views/posts/edit.blade.php
> +            <textarea id="content" class="form-control" name="content" rows="{{ old('content') }}"></textarea>
ここに前回入力内容を残す

2023-02-09 13:57 UTC, yukihiroLaravel commented on resources/views/posts/edit.blade.php
> +            <textarea id="content" class="form-control" name="content" rows="{{ old('content') }}"></textarea>
row="5"
縦に長くできる

2023-02-09 13:57 UTC, yukihiroLaravel commented on resources/views/posts/edit.blade.php
> +            <textarea id="content" class="form-control" name="content" rows="{{ old('content') }}"></textarea>
```
>{{ old('content', $post->content) }}</textarea>
```

2023-02-09 13:57 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $posts = $user->posts()->orderBy('id','desc')->paginate(10);
不要！

2023-02-09 13:57 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +            'posts' => $posts,
不要

2023-02-09 13:57 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $user = \Auth::user();
不要

2023-02-09 13:57 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +            'user' => $user,
不要

2023-02-11 05:56 UTC, shunsukeotsubo commented on resources/views/posts/edit.blade.php
> +            <textarea id="content" class="form-control" name="content" rows="{{ old('content') }}"></textarea>
修正します

2023-02-11 05:59 UTC, shunsukeotsubo commented on app/Http/Controllers/PostsController.php
> +        $posts = $user->posts()->orderBy('id','desc')->paginate(10);
修正します

2023-02-11 05:59 UTC, shunsukeotsubo commented on app/Http/Controllers/PostsController.php
> +            'posts' => $posts,
修正します

2023-02-11 05:59 UTC, shunsukeotsubo commented on app/Http/Controllers/PostsController.php
> +        $user = \Auth::user();
修正します

2023-02-11 06:00 UTC, shunsukeotsubo commented on app/Http/Controllers/PostsController.php
> +            'user' => $user,
修正します

2023-02-13 04:06 UTC, yukihiroLaravel requested changes
お疲れ様です。

ほぼOKですが、
細かい点を修正願います☺️

2023-02-13 04:06 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        return view('posts.edit',$data);
こちら指摘していませんでしたが、
/users/10/edit のURL の番号を変えてアクセスすると
他人の投稿も編集できてしまうため、

```
if (\Auth::id() === $post->user_id) {
            return view('posts.edit', [
                'post' => $post,
            ]);
}
return back();
```

こんな感じにしましょう！

2023-02-13 04:06 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        ];
viewに渡す変数が１つだけの場合は
dataに代入しなくて大丈夫です！

2023-02-13 04:06 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $post->save();
念のためこちらも、他人が勝手に更新できないようにしておきましょう。

```
if (\Auth::id() === $post->user_id) {
           $post->content = $request->content;
           $post->save();
}
```

2023-02-13 04:19 UTC, shunsukeotsubo commented on app/Http/Controllers/PostsController.php
> +        return view('posts.edit',$data);
承知しました。
修正します。

2023-02-13 04:19 UTC, shunsukeotsubo commented on app/Http/Controllers/PostsController.php
> +        ];
承知しました。
修正します。

2023-02-13 04:19 UTC, shunsukeotsubo commented on app/Http/Controllers/PostsController.php
> +        $post->save();
承知しました。
修正します。

2023-02-13 05:06 UTC, yukihiroLaravel requested changes
コードはいいのですが、
インデントなどできていない部分があったので、その修正お願いします！

2023-02-13 05:06 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $post->save();
ここif(){}の中のインデントがおかしいですね！
インデントまでしっかり確認する癖をつけましょう！

あと、ifのカッコの前後にもスペースがコーディング規約で必要になります！

```
if (~) {
     ~
}
```

2023-02-13 05:06 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        if(\Auth::id() === $post->user_id){
ifのカッコの前後にもスペースがコーディング規約で必要になります！

```
if (~) {
     ~
}
```

2023-02-13 13:00 UTC, shunsukeotsubo commented on app/Http/Controllers/PostsController.php
> +        $post->save();
承知しました。
修正します。

2023-02-13 15:21 UTC, yukihiroLaravel requested changes
１つ指摘が直っていない部分があったので
再度十分確認の上、修正ください✨

2023-02-14 00:32 UTC, shunsukeotsubo commented on app/Http/Controllers/PostsController.php
> +        if(\Auth::id() === $post->user_id){
承知しました。
修正します。

2023-02-14 02:00 UTC, yukihiroLaravel approved these changes
OKです！
マージしました！

今気づきましたが、ブランチ名が前の
投稿表示機能のときのままになってますね。

これはたぶん、作業開始のときに新規にdevelpからブランチを切るのが
できていないということだと思うので
毎回しっかり確認しましょう！

今回は結果的にできていたから問題ないですが、
毎回developからブランチを切れていないと
重大なミスを招く可能性があるので！

宜しくお願いします！

2023-02-14 02:00 UTC, merged