#121投稿削除(藤岡)
yukihiroLaravel/joint_develop pull request #150
Opened 2023-02-12 07:03 UTC by ryomafujioka

## issue
- closes#121
## 概要
- #121投稿削除(藤岡)
## 動作確認手順
- 下記のコマンドを実行  
   -http://localhost:8080
にログインしている事を確認し、
データーベース上でクローンで投稿を作成し、
削除ボタンでデータベース上とブラウザ上で投稿が消えていることの確認。

## 考慮して欲しい事
- 特にありません
## 確認してほしいこと
- 特にありません

2023-02-13 03:50 UTC, yukihiroLaravel requested changes
全体的に良い感じでできてますね！
一部だけ修正ねがいます☺️

2023-02-13 03:50 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +            $post->forcedelete();
こちら、forcedelete() ではなく、 delete() の方がいいですね！

今だと完全に物理削除してしまっていますが、
論理削除と言って、データベース上に履歴を残す形の方が運用を考えると安全なので
deleteにしましょう！

2023-02-13 03:50 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +                        @method('DELETE')
ここは１つインデントをつけた方がみやすいですね！

2023-02-13 16:16 UTC, ryomafujioka commented on app/Http/Controllers/PostsController.php
> +            $post->forcedelete();
修正いたします。

2023-02-13 16:17 UTC, ryomafujioka commented on resources/views/posts/posts.blade.php
> +                        @method('DELETE')
承知しました。

2023-02-13 17:36 UTC, ryomafujioka commented
## issue
- closes#121
## 概要
- #121投稿削除(修正)
## 動作確認手順
- 下記のコマンドを実行  
   -http://localhost:8080
にログインしている事を確認し、
データーベース上でクローンで投稿を作成し、
データベース上で投稿が消えていない事の確認。

インデントが追加されていることの確認。

## 考慮して欲しい事
- 特にありません
## 確認してほしいこと
- 特にありません

2023-02-14 14:11 UTC, yukihiroLaravel approved these changes
OKです！マージしました☺️
おつかれさまでした！

2023-02-14 15:45 UTC, ryomafujioka commented
コンフリクト解消いたしました。

2023-02-16 01:35 UTC, yukihiroLaravel requested changes
こちらトップページにアクセスしたら、エラーが出ますね！

たぶん動作確認されてませんよね？
動画でも言っている通り、コンフリクト解消したら必ず動作確認するようにしましょう！！

消している２つのルーティングは消してしまうとダメです・・・💦
（他の人がつくった大事なコードを消していることになるので）

投稿編集・更新の５行が消えていない形に戻しましょう・・・！

2023-02-16 01:35 UTC, yukihiroLaravel commented on routes/web.php
> -    });
こちらトップページにアクセスしたら、エラーが出ますね！

たぶん動作確認されてませんよね？
動画でも言っている通り、コンフリクト解消したら必ず動作確認するようにしましょう！！

この２つのルーティングは消してしまうとダメです・・・💦
（他の人がつくった大事なコードを消していることになるので）

この５行が消えていない形に戻しましょう・・・！

2023-02-16 14:03 UTC, ryomafujioka commented on routes/web.php
> -    });
承知しました

2023-02-16 14:31 UTC, ryomafujioka commented on routes/web.php
> -    });
コンフリクト解消いたしました。

2023-02-17 01:28 UTC, yukihiroLaravel approved these changes
OKです！
マージしましたので、次のタスクに取り掛かりましょう✨

2023-02-17 01:28 UTC, merged