#127 フォロー機能の中間テーブル(たろう)
yukihiroLaravel/joint_develop pull request #153
Opened 2023-02-18 06:25 UTC by afurotanaka

## issue
- closes#127
## 概要
-  フォロー機能の中間テーブル
## 動作確認手順
- php artisan migrate:fresh --seed を実行し
followersテーブルが作成されていることを確認

## 考慮して欲しいこと
git bash上で:
- use App\User;
- $user2 = User::find(2);
- $user4 = User::find(4);

データベース上にあるユーザを作成

- $user2->followings()->get(); でフォローされてない事を確認
- $user2->follow(4); でtureでフォローされていることを確認
- $user2->unfollow(4); でfalseでフォローが外ずれていることを確認
- http://localhost:8088 でデータベース上にない事を確認

## 確認して欲しいこと
- tinker上で確認不足がないか教えて欲しいです。

以上

よろしくお願いいたします。

2023-02-18 08:31 UTC, yukihiroLaravel requested changes
GitHubにコメントしたので、空行の部分だけ、入れましょう！

空行だけ入れたら、僕の方では今回は特にマージしないので
今いるブランチのまま作業を進めて下さい✨

2023-02-18 08:31 UTC, yukihiroLaravel commented on app/User.php
>      }
１行空行を入れましょう！

2023-02-18 08:31 UTC, yukihiroLaravel commented on app/User.php
> +    }
１行空行を入れましょう！

2023-02-18 08:31 UTC, yukihiroLaravel commented on app/User.php
> +    }
１行空行を入れましょう！

2023-02-18 08:31 UTC, yukihiroLaravel commented on app/User.php
> +    }
１行空行を入れましょう！

2023-02-18 08:31 UTC, yukihiroLaravel commented on app/User.php
> +    }
１行空行を入れましょう！

2023-02-18 11:57 UTC, afurotanaka commented on app/User.php
>      }
修正します。

2023-02-18 11:58 UTC, afurotanaka commented on app/User.php
> +    }
修正します。

2023-02-18 11:58 UTC, afurotanaka commented on app/User.php
> +    }
修正します。

2023-02-18 11:58 UTC, afurotanaka commented on app/User.php
> +    }
修正します。

2023-02-18 11:59 UTC, afurotanaka commented on app/User.php
> +    }
修正します。

2023-02-27 03:30 UTC, afurotanaka commented
## issue 
- closes127
## 概要
- フォロー機能
## 動作確認手順
- ログインしていることを確認しユーザ詳細画面で自分自身以外の人がフォロー機能出来ているかを確認
- フォロー中とフォローワーの人数がカウントされることを確認しフォロー中とフォローワーの人の投稿がすべてされていることを確認
## 考慮して欲しいこと
- php artisan migrate:fresh --seed 場合によっては実行してほしいです
## 確認して欲しいこと
- コードの記述についておかしいところがありましたら教えて欲しいです。

以上

よろしくお願いいたします。

2023-02-27 08:14 UTC, yukihiroLaravel requested changes

2023-02-27 08:14 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +
この空行２行不要ですね！

2023-02-27 08:14 UTC, yukihiroLaravel commented on app/Post.php
> +
この空行２行不要ですね！

2023-02-27 08:14 UTC, yukihiroLaravel commented on resources/views/follows/follows_button.blade.php
> +    @if (Auth::user() && Auth::id() !== $user->follow_id)
ここの　Auth::user() は上の Auth::check() とほぼ一致するので不要かなと思います！

2023-02-27 08:14 UTC, yukihiroLaravel commented on resources/views/follows/follows_button.blade.php
> +            @method('DELETE')
ここは１つインデントが必要ですね！

2023-02-27 08:14 UTC, yukihiroLaravel commented on resources/views/follows/follows_button.blade.php
> +            </form>
ここも１つインデント必要

2023-02-27 08:14 UTC, yukihiroLaravel commented on app/Http/Controllers/FollowsController.php
> +        $posts = Post::query()->whereIn('user_id',\Auth::user()->followings()->pluck('follow_id'))->orderBy('id', 'desc')->paginate(10);
２６行目の内容とやっていることがほぼ同じ一緒じゃないでしょうか？
２６行目の書き方の方がシンプルなので、２６行目の内容にpaginate()を付けて必要なユーザのみ取得できるようにしましょう

2023-03-02 15:30 UTC, afurotanaka commented
## issue
- closes#127
## 概要
- フォロー機能の修正
## 動作確認手順
- http://localhost:8088 でfollowersテーブルでfollow_idを作成しフォロー中とフォワーがカウントされていることを確認。

フォロー中とフォワーをアクセスした時にそれぞれユーザーが表示されることを確認をお願いします。

## 考慮して欲しいこと

- 修正の為に特にありません。

## 確認して欲しいこと
- 省いた方が良いコードがあると思うので、教えて貰えると助かります。

以上、よろしくお願いいたします。

2023-03-03 04:51 UTC, afurotanaka commented
## followUsersのｓが消えててエラーが出てたので修正したのでしたのでよろしくお願いいたします。

お手数をおかけしますが、よろしくお願いいたします。

2023-03-03 12:44 UTC, yukihiroLaravel requested changes
かなり素晴らしいですね！
よくここまで考えてつくられました！

細かい点だけですが修正箇所があるのでもう一歩書き換えてみてください☺️

2023-03-03 12:44 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +            <li class="nav-item"><a href="{{ route('user.followUsers', $user->id) }}" class="nav-link {{ Request::is('users/'. $user->id. '/followUsers') ? 'active' : '' }}">フォロワー<br><div class="badg
ここにもフォロー中、フォロワーの数字が入るようにしましょう！

2023-03-03 12:44 UTC, yukihiroLaravel commented on resources/views/users/followings.blade.php
> +                </div>
ここに１つインデントをつけましょう！

2023-03-03 12:44 UTC, yukihiroLaravel commented on resources/views/users/followUsers.blade.php
> +                </div>
ここに１つインデントをつけましょう！

2023-03-03 12:44 UTC, yukihiroLaravel commented on app/Http/Controllers/FollowsController.php
> +
ここの空行は不要ですね！

2023-03-05 16:15 UTC, afurotanaka commented
## issue
- closes#127
## 概要
- フォロー機能の修正
## 動作確認手順
show.blade.phpのタイムラインからもフォロー中、フォロワーの人数を確認出来る事を確認
## 考慮して欲しいこと
- もしかしたら、こちらの勘違いでゆきひろさんの指示している通りの実装になっていなければすみません。
## 確認して欲しいこと
- 考慮して欲しいことと同じです。

以上

よろしくお願いいたします。

2023-03-06 14:58 UTC, yukihiroLaravel approved these changes
動作確認含めて確認しましたが
OKなのでマージしました✨

最難関の機能でしたが本当におつかれさまでした！！
実務案件もがんばりましょう！

2023-03-06 14:58 UTC, merged