#116 ユーザ詳細（そばた）
yukihiroLaravel/joint_develop pull request #155
Opened 2023-02-19 05:55 UTC by youzousobata

## issue
- Closes #116

## 概要
- ユーザ詳細画面の実装

## 動作確認手順
- http://localhost:8080でアクセスして、トップページがちゃんと表示されていることを確認。
- トップページの投稿一覧のユーザから、そのユーザの詳細画面に移動できることを確認。
- ログインした後に、ヘッダーのユーザ名のとこから、ユーザ詳細画面を開けることを確認。

## 考慮してほしいこと
- 他に確認しなければいけないことがあれば教えてください。

## 確認してほしいこと
- ユーザ詳細画面が見本サイトのものと相違ないかどうか、お願いします。
- 不要なコードがないか、お願いします。

2023-02-19 07:05 UTC, Osk0830 requested changes
お疲れ様でした！
だいぶまとまってきましたね！
もう少しだと思います！

いくつかコメントしたので、確認よろしくお願いします！

2023-02-19 07:05 UTC, Osk0830 commented on .vscode/settings.json
> +}
- VS codeの設定ファイルは、.gitignoreに含めるなどして、プッシュする内容に含まれないようにしましょう
　
　https://www-creators.com/archives/1662

2023-02-19 07:05 UTC, Osk0830 commented on app/Http/Controllers/Controller.php
> +
- このファイル自体は変更不要ですが、空行が数行追加される変更を加えてしまったようですので、こちらはできれば元に戻しておきましょう。

2023-02-19 07:05 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +                        </div>
- ボタンの表示・非表示が、条件に応じて切り替わるようにしましょう。

　[![Image from Gyazo](https://i.gyazo.com/66888bbee5ebe6496fe51f5480266d21.png)](https://gyazo.com/66888bbee5ebe6496fe51f5480266d21)

- ボタンのリンク先が正しく指定できていないようです。hrefの内容がおかしいですね。

　[![Image from Gyazo](https://i.gyazo.com/cc25149a2688a6f05b30fc4f2f24cf8d.png)](https://gyazo.com/cc25149a2688a6f05b30fc4f2f24cf8d)

2023-02-19 07:05 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="{{ route('users.show', $user->id) }}" class="nav-link {{ Request::is() ? 'active' : '' }}">タイムライン</a></li>
- どのタブがアクティブかを示すためのクラスの指定がうまくできていないようです。

　【現状】
　[![Image from Gyazo](https://i.gyazo.com/4d7b14a5fed59d2d7365279263b34ddd.png)](https://gyazo.com/4d7b14a5fed59d2d7365279263b34ddd)

　【サンプルデモサイト】
　[![Image from Gyazo](https://i.gyazo.com/2c99f867b03d1ef48874a77acc550a43.png)](https://gyazo.com/2c99f867b03d1ef48874a77acc550a43)

2023-02-19 14:38 UTC, youzousobata commented on .vscode/settings.json
> +}
これは、falseのとこを、trueに書き換えればいいのでしょうか？

2023-02-19 14:38 UTC, youzousobata commented on app/Http/Controllers/Controller.php
> +
わかりました！

2023-02-20 06:09 UTC, youzousobata commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="{{ route('users.show', $user->id) }}" class="nav-link {{ Request::is() ? 'active' : '' }}">タイムライン</a></li>
わかりました！

2023-02-20 06:10 UTC, youzousobata commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="{{ route('users.show', $user->id) }}" class="nav-link {{ Request::is() ? 'active' : '' }}">タイムライン</a></li>
わかりました！

2023-02-24 07:50 UTC, Osk0830 requested changes
お疲れ様でした！
ほぼ完了に近い状態にまでなりましたね！
少しだけコメントしたのでご確認くださいね！

2023-02-24 07:50 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                <p class="mt-3 mb-0 d-inline-block"><a href="{{ route('users.show', $post->id) }}">＠{{ $post->user->name }}</a></p>
- `route('users.show', $post->id)`の部分ですが、`$post->id`ですと、投稿のidを用いてユーザーを探し出す、というおかしなことになってしまいます。今は、シーディングデータの関係でたまたま全ての投稿のidとユーザーのidが一致しているので、おかしくなさそうに見えますが、試しにAdminer上で新規にユーザー1番の投稿を一つ追加して、トップページなどで新しい投稿のユーザー名の部分をクリックした際に、ちゃんとユーザー1番のページに遷移できるか試してみてください。

　【Adminerで追加】
　　[![Image from Gyazo](https://i.gyazo.com/2216532ffdf5dcc60160ccf42e0a5bd4.png)](https://gyazo.com/2216532ffdf5dcc60160ccf42e0a5bd4)

　　[![Image from Gyazo](https://i.gyazo.com/ab4f1389b6eb402e3a26a42f4901b617.png)](https://gyazo.com/ab4f1389b6eb402e3a26a42f4901b617)

　【矢印の部分をクリック】
　　[![Image from Gyazo](https://i.gyazo.com/d8bb5515e24c693030b76b32682f47c1.png)](https://gyazo.com/d8bb5515e24c693030b76b32682f47c1)

2023-02-24 07:50 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +                </div>
- この部分、インデントが若干ガタガタなので、綺麗に揃えましょう！

2023-02-25 23:29 UTC, Osk0830 approved these changes
お疲れ様でした！
一点だけ確認が必要ですが、本質ではなく、後ろが詰まってもいるので、
一旦マージしますね！
コメントした内容については、必要であれば、
次のタスクを行う際にでもついでに対応してくださいね！

2023-02-25 23:29 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                <p class="mt-3 mb-0 d-inline-block"><a href="{{ route('users.show', $post->user_id) }}">＠{{ $post->user->name }}</a></p>
- こちらの `@`は、あえて入れてる感じでしょうか？

2023-02-25 23:29 UTC, merged

2023-02-26 13:45 UTC, youzousobata commented on resources/views/posts/posts.blade.php
> +                <p class="mt-3 mb-0 d-inline-block"><a href="{{ route('users.show', $post->user_id) }}">＠{{ $post->user->name }}</a></p>
あまり理解せずに入れていました😓