#126 ユーザ退会（福士）_1
yukihiroLaravel/joint_develop pull request #156
Opened 2023-02-19 10:43 UTC by mao-fukushi

## issue
- Closes #126 

## 概要
- ユーザ退会
## 動作確認手順
-
## 考慮してほしいこと
-
## 確認してほしいこと
-

2023-02-20 01:19 UTC, Osk0830 requested changes
お疲れ様でした！
モーダルの実装までされていて素晴らしいですね！
まず、一点は、コメントを残しましたので、確認よろしくお願いします。

もう一点、例えば、「ユーザー9番」などで退会処理をしようとすると、
下記のようにエラーが出るようですが、いかがでしょう？
既に投稿済みの投稿を持っていることと関連がありそうな感じはしますが、
そうなりますと投稿削除機能が完了・マージされ、
こちらのブランチに取り込まれた段階で、
再度動作確認が必要かもしれないですね。。

[![Image from Gyazo](https://i.gyazo.com/39f757a0e2d8f01c6631dac8795b5ef5.gif)](https://gyazo.com/39f757a0e2d8f01c6631dac8795b5ef5)

2023-02-20 01:19 UTC, Osk0830 commented on resources/views/users/edit.blade.php
> +        <input type="hidden" name="id">
- こちら、今回の実装ではなく、以前の実装内容で恐縮ですが、ユーザーのid情報はformのaction部分で引数として送っていますし、hiddenにはvalueもなく、実際この後の処理で使われてもいないので、不要な要素は削除しといた方がいいかもですね。

2023-03-09 01:03 UTC, youzousobata commented
確認しました。ＯＫです！

2023-03-09 01:23 UTC, Osk0830 approved these changes
僕の方でのチェック・確認はしていませんが、動作問題ないとのことなので、取り急ぎマージしますね！

2023-03-09 01:53 UTC, merged