#122 投稿削除（福士）
yukihiroLaravel/joint_develop pull request #157
Opened 2023-02-19 12:50 UTC by mao-fukushi

## issue
- Closes #122 

## 概要
- 投稿削除

## 動作確認手順

1. Topic Postsトップページを表示
    - [ ] <http://localhost:8080/>

2. 下記ユーザでログイン
    - [ ] ユーザ名：test1
    - [ ] メールアドレス：test1@test.com
    - [ ] パスワード：test1

    >  確認項目：ログイン後、トップページに画面遷移することを確認。

3. 「削除」ボタンの確認
    トップページの投稿表示画面から、ユーザ１番の投稿に、「削除」ボタンが表示されたことを確認する。
 

4. Adminerへ画面遷移
    別のブラウザを立ち上げ、Adminerのpostsテーブルでtest1ユーザの表示行を確認して控えておく。
    <http://localhost:8088/?server=db&username=dbuser&db=laraveldb&select=posts>
    - [ ] ユーザID：1
    >  確認項目：test1ユーザのcontentカラムに、投稿内容が表示されていることを確認。
    >  確認項目：test1ユーザのdeleted_atカラムがNULLであることを確認。

5.  Topic Postsへ画面遷移

6. 「削除」ボタン押下 
    トップページの投稿表示画面から、ユーザ１番の投稿の「削除」ボタンを押下する。
    >  確認項目：ユーザ１番の投稿が削除されたことを確認。

7. Adminer確認
    Adminerを立ち上げているブラウザに画面遷移し、postsテーブルを表示したまま、画面更新する。
    <http://localhost:8088/?server=db&username=dbuser&db=laraveldb&select=posts>
    >  確認項目：test1ユーザのcontentカラムにおいて、投稿内容が空欄であることを確認。
    >  確認項目：test1ユーザのdeleted_atカラムにタイムスタンプが表示されたことを確認。

8. Adminerを復元 
    8.1 Adminerのpostsテーブルから、test1ユーザのチェックボックスにチェックを入れて、編集を実行する。
    8.2 編集画面で、deleted_atカラムのタイムスタンプをNULLに設定して保存する。
    >  確認項目：test1ユーザの投稿内容が表示され、deleted_atカラムがNULLになったことを確認。

9. Topic Postsへ画面遷移
    >  確認項目：トップページの投稿表示画面から、ユーザ１番の投稿内容が元に戻っていることを確認。

10. ログアウトして終了

## 考慮してほしいこと

- 初回のプルリクは、トップページからの投稿削除のボタン表示と機能の動作確認に範囲を限定しております。

- ユーザ詳細画面への投稿削除ボタンの実装と、ユーザ詳細画面からの投稿削除機能の動作確認は、
ユーザ詳細画面のプルリクがチームブランチにマージされた後に、再度、こちらのプルリクを修正する形で行います。

## 確認してほしいこと
- 不要な記述、改善する箇所がありましたらご教示ください。

以上、よろしくお願い致します。

2023-03-03 04:32 UTC, Osk0830 requested changes
お疲れ様でした！
今の状態でもいいですが、少しコメントしましたので、確認よろしくお願いします！

2023-03-03 04:32 UTC, Osk0830 commented on app/Post.php
> +    use SoftDeletes;
- ソフトデリートを使わないことにしたと思いますので、こちらの2箇所はコメントアウトするか削除しましょう。

2023-03-03 04:32 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +            $post->forceDelete();
- ソフトデリート機能を無効にしている状態であれば、`forceDelete()`でなく`delete()`でも大丈夫そうですね。

2023-03-03 04:32 UTC, Osk0830 commented on database/migrations/2023_01_11_234631_create_posts_table.php
> +            $table->softDeletes();
- こちらも同じく、コメントアウトするか削除しましょう。

2023-03-04 07:31 UTC, mao-fukushi commented on app/Post.php
> +    use SoftDeletes;
ソフトデリートの記述を削除しました。

2023-03-04 07:32 UTC, mao-fukushi commented on app/Http/Controllers/PostsController.php
> +            $post->forceDelete();
delete()に修正しました。

2023-03-04 07:32 UTC, mao-fukushi commented on database/migrations/2023_01_11_234631_create_posts_table.php
> +            $table->softDeletes();
ソフトデリートのカラムを削除しました。

2023-03-05 02:12 UTC, Osk0830 approved these changes
お疲れ様でした！
こちら大丈夫なのでマージしますね！

2023-03-05 02:12 UTC, merged