#120 投稿新規作成（そばた）
yukihiroLaravel/joint_develop pull request #163
Opened 2023-03-01 02:12 UTC by youzousobata

## issue
- Closes #120 

## 概要
- 投稿新規作成の実装

## 動作確認手順
- http://localhost:8080/でブラウザにアクセスし、トップページが表示されることを確認。このときはまだログインしてない状態で、新規投稿する欄が出ていないことを確認。
- 次に、ログインして、トップページに新規投稿作成の欄と投稿ボタンが出ていることを確認。何も入力せずに投稿ボタンをクリックして送信すると、
「投稿は、必ず入力してください。」というメッセージが欄の上に表示される
ことを確認。次に140字以上を入力して投稿送信すると、140字以下にしてくださいと表示され、送信する直前の入力した文が残っている状態に戻っていることを確認。

- 投稿したら、ちゃんと投稿内容がトップページに反映されていることを確認。

- データベースの方にも、ちゃんと投稿のデータが保存されていること確認。

## 考慮してほしいこと
- データベースに投稿のデータを残しています。

## 確認してほしいこと
- コードの記述に不備がないかどうか、ご確認をお願いします。
- 動作の確認事項に不足してるものはないか、お願いします。

2023-03-01 03:18 UTC, Osk0830 requested changes
お疲れ様でした！
よくできていると思います！
少しだけコメントしたので、確認よろしくお願いします。

2023-03-01 03:18 UTC, Osk0830 commented on .vscode/settings.json
> +}
またVS codeの設定ファイルが不要に上がっちゃってるみたいですので、.gitignoreの対象になっているか、チェックお願いします！

2023-03-01 03:18 UTC, Osk0830 commented on resources/views/welcome.blade.php
>                          </div>
- ログインしていない状態ではフォームそのものが不要だと思うので、@if ... @endifでどこからどこまでを囲むべきかをもう一度検討してみてくださいね。

2023-03-01 03:18 UTC, Osk0830 commented on routes/web.php
> +        Route::delete('{id}', 'PostsController@destroy')->name('post.delete');
- この行は、今回のそばたさんのタスクとは関係なくないでしょうか？

2023-03-01 03:18 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +            $post->user_id = $request->user()->id;
- `$request->user()->id`は冗長な感じがします。ここでは、現在ログインしているユーザーのidを取得できればいいだけなので、もう少し簡潔に書いてみてくださいね。

2023-03-01 08:29 UTC, youzousobata commented on resources/views/welcome.blade.php
>                          </div>
はい、わかりました！

2023-03-01 08:29 UTC, yozosobata commented on .vscode/settings.json
> +}
はい、わかりました！

2023-03-01 09:23 UTC, youzousobata commented on routes/web.php
> +        Route::delete('{id}', 'PostsController@destroy')->name('post.delete');
すみません、おそらく、初めてルーティングの記述を始めたときに、理解もせず、わからないまま勝手に書き込んでたのを忘れていました。

2023-03-01 09:24 UTC, youzousobata commented on routes/web.php
> +        Route::delete('{id}', 'PostsController@destroy')->name('post.delete');
消しておきます。

2023-03-01 09:59 UTC, youzousobata commented on app/Http/Controllers/PostsController.php
> +            $post->user_id = $request->user()->id;
はい、わかりました！

2023-03-02 01:28 UTC, Osk0830 approved these changes
お疲れ様でした！
こちら修正は問題なさそうなんですが、コンフリクトが起きてるので、解消してプッシュし直してくださいね！

2023-03-02 07:18 UTC, merged