投稿削除のフラッシュメッセージ(そばた)
yukihiroLaravel/joint_develop pull request #166
Opened 2023-03-06 03:57 UTC by youzousobata

## issue
- Closes #

## 概要
- 投稿削除のフラッシュメッセージの実装

## 動作確認手順
- http://localhost:8080/でブラウザにトップページを表示させ、ログインして、新規投稿をして、その投稿をまずは、トップページの投稿一覧に表示されている削除ボタンを押して「・投稿を削除しました。」という表示が、トップページに出るのを確認。

- その次に、また新規投稿をして、その投稿を、今度はユーザ詳細画面に移ってから、ユーザ詳細画面の投稿一覧に表示されている削除ボタンを押して削除すると、自動でトップページに移り「・投稿を削除しました。」という表示が、また一回目のときと同じところに表示されたのを確認。

## 考慮してほしいこと
- メッセージの枠の色はチームに相談して、赤色がいいということになりました。

## 確認してほしいこと
- 他にするべき確認事項はあるでしょうか？修正すべき点はあるでしょうか？

- コードの記述の仕方など。

2023-03-07 09:29 UTC, Osk0830 requested changes
お疲れ様です！
こちら、現状のものをレビューしたので、確認・修正お願いします！
修正後はチーム内でレビュー・マージしてくださってOKです！

2023-03-07 09:29 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +    </div>
- こちら、エラーメッセージがログイン時にのみ出る仕組みなのであれば、<div>自体をifで囲んであげた方がいいですね。でないと常に空の<div>が出力されると思います。
- また、`@if`と`@endif`はペアですが、`@if`に対する`@endif`が足りなくないでしょうか？ただ、今のようにしたいのであれば、`@if`の条件式を `&&`で一つにまとめるのがいいように思います。

2023-03-09 12:27 UTC, mao-fukushi commented
@youzousobata さん
下記のファイルでコンフリクトが発生しているので、解消ご対応のほどお願いします。

resources/views/welcome.blade.php

2023-03-11 15:36 UTC, mao-fukushi commented
お疲れ様でした！マージボタン押せるようになったら押しますね。

2023-03-12 23:36 UTC, mao-fukushi approved these changes

2023-03-13 09:40 UTC, Osk0830 approved these changes
マージします！

2023-03-13 10:53 UTC, merged