#200共通ファイル作成(橋本)、#199ヘッダー・フッター & トップページのタイトルのみ表示「Topic Posts」(橋本)
yukihiroLaravel/joint_develop pull request #207
Opened 2023-03-21 14:21 UTC by Hashimoto-Noriaki

# issue

https://github.com/yukihiroLaravel/joint_develop/issues/199

https://github.com/yukihiroLaravel/joint_develop/issues/200

# 概要
・共通ファイル作成
・ヘッダー・フッター & トップページのタイトルのみ表示「Topic Posts」
# 動作確認手順
localhost:8080で起動

# 考慮してほしいこと
フッター、文字の位置などの確認

## 確認してほしいこと
・localhost:8080で起動して想定通りに表示されていること
・タスク通りできているか確認してほしい
・何か追加で実装した方がいいことあれば確認して欲しい

2023-03-21 15:16 UTC, yukihiroLaravel requested changes
お疲れ様でした！
いくつか指摘しましたので
ご確認お願いします☺️

2023-03-21 15:16 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
> +                <li class="nav-item"><a href="" class="nav-link">ログイン</a></li>
新規ユーザ登録とログインの並びが
お手本アプリと逆ですね！

原則お手本に忠実につくりましょう！

2023-03-21 15:16 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
> +    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
ヘッダーの色だけ、ダーク色になってて変ですね！
お手本と同じく、青色に統一しましょう！

2023-03-21 15:16 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('/', 'UsersController@index');
トップページが
ユーザーズコントローラの制御下にあるのは少し違和感があるので、
現時点では変更までの下記コードのままでいいかなと思います！

```
Route::get('/', function () {
    return view('welcome');
});
```

2023-03-21 15:16 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +}
ルーターのところにも書いた通り、トップページが
ユーザーズコントローラの制御下にあるのは少し違和感があるので、
一旦このファイルは消しておいていいかなと思います🙇‍♂️

2023-03-21 15:16 UTC, yukihiroLaravel commented on resources/views/commons/footer.blade.php
> +
ここの謎の空行は不要ですね！

2023-03-21 15:16 UTC, yukihiroLaravel commented on resources/views/layouts/app.blade.php
> +        <title></title>
slackで書いていた通り、titleは一旦
Topic Posts
にしましょう

2023-03-22 03:43 UTC, yukihiroLaravel approved these changes
OKですので、マージしました！

ただ、今後でいいのですが、
レビュアーがコメントしたところには
対応したのがわかりやすいように
それぞれ必ずコメントを返しましょう！
（「対応しました」などの短文でも大丈夫です）

一旦お疲れ様でした！

2023-03-22 03:43 UTC, merged

2023-03-22 03:45 UTC, Hashimoto-Noriaki commented on resources/views/commons/header.blade.php
> +                <li class="nav-item"><a href="" class="nav-link">ログイン</a></li>
対応しました。

2023-03-22 03:46 UTC, Hashimoto-Noriaki commented on resources/views/commons/header.blade.php
> +    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
対応しました

2023-03-22 03:46 UTC, Hashimoto-Noriaki commented on routes/web.php
> +Route::get('/', 'UsersController@index');
対応しました

2023-03-22 03:46 UTC, Hashimoto-Noriaki commented on app/Http/Controllers/UsersController.php
> +}
対応しました

2023-03-22 03:46 UTC, Hashimoto-Noriaki commented on resources/views/commons/footer.blade.php
> +
対応しました

2023-03-22 03:46 UTC, Hashimoto-Noriaki commented on resources/views/layouts/app.blade.php
> +        <title></title>
対応しました