#196 ユーザログイン・ログアウト(山田)
yukihiroLaravel/joint_develop pull request #210
Opened 2023-03-23 05:40 UTC by yamadaman-bs

## issue
・Closes ユーザログイン・ログアウト #196 

##概要
・ユーザログイン・ログアウトの作成

##動作確認手順
-ブラウザのlocalhost:8080にアクセスして、手本アプリを元に表示されていることを確認

##考慮してほしいこと
・login.blade.php 内の
{{ route('〇〇') }}
に入力していない箇所があります。
他の方のissueによるためと考え、空欄としています。

##確認してほしいこと
・web.phpのルートがこちらであっているか確認してほしいです。
・共同開発の際今回のように他の方のissueとのやりとりがある場合は、
・どのように進めていくのが良いか,
・どこまで進めて良いかご教授頂きたいです。
例：slack上で「ルートの記述はどのようにしますか？」などのやりとりを行う。

よろしくお願いいたします。

2023-03-26 02:04 UTC, Osk0830 requested changes
お疲れ様でした！
実装内容自体は問題ないですね！
一つだけ追加作業お願いしたくコメントしたので、よろしくお願いします！

2023-03-26 02:04 UTC, Osk0830 commented on resources/views/auth/login.blade.php
> +            <div class="mt-2"><a href="{{}}">新規ユーザ登録する？</a></div>
- 新規登録機能が既にマージされているので、ルーティング確認してリンク貼って頂ければと思います！

2023-03-26 16:48 UTC, yamadaman-bs commented on resources/views/auth/login.blade.php
> +            <div class="mt-2"><a href="{{}}">新規ユーザ登録する？</a></div>
お疲れ様です。
新規登録機能のリンクを貼り、再度プルリクエスト致しました。
ご確認のほど、よろしくお願いいたします。

2023-03-27 01:06 UTC, Osk0830 approved these changes
お疲れ様でした！
こちら問題なさそうなのでマージしますね！
引き続き頑張っていきましょう！

2023-03-27 01:07 UTC, merged