Feature/katsu/poststable migration seeder(katsu)
yukihiroLaravel/joint_develop pull request #211
Opened 2023-03-23 11:08 UTC by ka2ki1

## issue
- Closes #197 

## 概要
- posts（投稿）テーブルのマイグレーションとシーダー作成

## 動作確認手順
・ 下記コマンドを実行。
①php artisan migrate でPostsテーブル作成
②php artisan db:seed --class=PostsTableSeeder

・ Adminerでusersテーブルに13個のレコードが保存されていることを確認

## 考慮してほしいこと
・ 状況に応じて、下記コマンドで動作確認する必要あり。
php artisan migrate:fresh --seed

## 確認してほしいこと
一度削除して作り直したためか、adminerの連番が続きとなっています。一からに戻すのはどうればいいでしょうか？この段階だとリレーションの設定は不要なのでしょうか？

2023-03-23 13:44 UTC, yukihiroLaravel requested changes
変更お願いします

2023-03-23 13:44 UTC, yukihiroLaravel commented on app/Posts.php
> +
原則不要だが、あっても問題ないので
今回は含んでOK

2023-03-23 13:44 UTC, yukihiroLaravel commented on app/User.php
> +
不要な空行削除してください

2023-03-23 13:44 UTC, yukihiroLaravel commented on app/User.php
> +
不要な空行削除してください

2023-03-23 13:44 UTC, yukihiroLaravel commented on database/migrations/2023_03_19_133742_create_posts_table.php
> +            // $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
コメントアウト解除してやってみてください。

2023-03-23 13:44 UTC, yukihiroLaravel commented on database/migrations/2023_03_19_133742_create_posts_table.php
> +             // 外部キー制約
半角インデントを消してください

2023-03-23 13:44 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +     }
インデントを半角スペース４つ分に変更してください

2023-03-23 13:44 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +     for($val =1; $val <= 13; $val++){
コーディング規約にならって変更してください
`for ($val = 1; $val <= 13; $val++) {`

2023-03-23 13:44 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +            'user_id' => 1+$val,
コーディング規約にならって変更してください
`'user_id' => $val + 1,`

2023-03-23 14:45 UTC, ka2ki1 commented on app/Posts.php
> +
OKです。

2023-03-23 14:45 UTC, ka2ki1 commented on app/User.php
> +
対応できました

2023-03-23 14:45 UTC, ka2ki1 commented on app/User.php
> +
対応できました

2023-03-23 14:45 UTC, ka2ki1 commented on database/migrations/2023_03_19_133742_create_posts_table.php
> +            // $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
対応できました

2023-03-23 15:08 UTC, ka2ki1 commented on database/migrations/2023_03_19_133742_create_posts_table.php
> +             // 外部キー制約
合っているか不安です

2023-03-23 15:12 UTC, ka2ki1 commented on database/seeds/PostsTableSeeder.php
> +     }
合っているか不安です

2023-03-23 15:12 UTC, ka2ki1 commented on database/seeds/PostsTableSeeder.php
> +            'user_id' => 1+$val,
対応できました

2023-03-23 15:12 UTC, ka2ki1 commented on database/seeds/PostsTableSeeder.php
> +     for($val =1; $val <= 13; $val++){
対応できました

2023-03-24 14:02 UTC, yukihiroLaravel requested changes
こちら、現状のコードに変更してから
migration と seeder 実行してやってみましたか？

僕の方で実行するとエラーが出るので、おそらく試されていないと思いますが
少しでもコードを変えたら、テストで試してみるのが原則ですので
今後は試しましょう！

コメントしましたので、エラー部分も踏まえて修正お願いします！

2023-03-24 14:02 UTC, yukihiroLaravel commented on database/migrations/2023_03_19_133742_create_posts_table.php
> +            $table->string('text')->nullable();
今気づきましたが、nullable ということはnullを許容するということなので
投稿に空欄を許容することになってしまうので
nullableは消した方がいいですね！

2023-03-24 14:02 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +            'user_id' => $val + 1,
こちら、現状 migration 実行してやってみましたか？
僕の方でやってみたところ、 user_id の部分でエラーが発生します。

これは、存在しない user_id も含んでしまっているからです。
つまり、ここでは　user_id が2 ~ 14 までの番号が入力されていますが
杉原さんがシーダーで登録されているのは
1~10番までなので、その間の数字を指定する必要があります！

2023-03-24 14:02 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +          }
やはりインデントがまだおかしいですね。
このままの書き方なら、下記のようにする必要があります！

```
for ($val = 1; $val <= 13; $val++) {
       DB::table('posts')->insert([
            'text' => 'test'.$val,
            'user_id' => $val + 1,
       ]);
}
```

2023-03-24 14:02 UTC, yukihiroLaravel commented on database/seeds/DatabaseSeeder.php
>          $this->call(UsersTableSeeder::class);
Usersテーブルシーダーを実行してから
Postのシーダーを実行しないと、user_idがないというエラーが出てしまうので
順番は逆でないとエラーが出ると思います！
逆にしましょう！

```
$this->call(UsersTableSeeder::class);
$this->call(PostsTableSeeder::class);
```

2023-03-24 14:02 UTC, yukihiroLaravel commented on database/migrations/2023_03_19_133742_create_posts_table.php
> +             // 外部キー制約
まだおかしいですね！
ここをすべて揃えるということですよ？

```
    $table->softDeletes();
    // 外部キー制約
    $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
```

2023-03-25 01:25 UTC, ka2ki1 commented on database/migrations/2023_03_19_133742_create_posts_table.php
> +             // 外部キー制約
対応しました

2023-03-25 01:25 UTC, ka2ki1 commented on database/migrations/2023_03_19_133742_create_posts_table.php
> +            $table->string('text')->nullable();
対応しました。

2023-03-25 01:25 UTC, ka2ki1 commented on database/seeds/PostsTableSeeder.php
> +            'user_id' => $val + 1,
対応しました

2023-03-25 01:25 UTC, ka2ki1 commented on database/seeds/PostsTableSeeder.php
> +          }
対応しました

2023-03-25 01:28 UTC, ka2ki1 commented on database/seeds/DatabaseSeeder.php
>          $this->call(UsersTableSeeder::class);
対応しました。こちらの順番は先にUsersテーブルが優先されるからなのでしょうか？

2023-03-25 14:25 UTC, yukihiroLaravel requested changes
良い感じだと思いますが
含んでOKと言っていた分がコメントアウトされてしまっていたのと
インデントがまだおかしい部分があるので
修正願います！

2023-03-25 14:25 UTC, yukihiroLaravel commented on app/Posts.php
> +        // return $this->belongsTo(User::class);
今回は含んでOKと言っていたので、
コメントアウトしなくて大丈夫です！

2023-03-25 14:25 UTC, yukihiroLaravel commented on app/User.php
> +        // return $this->hasMany(Posts::class);
今回は含んでOKと言っていたので、
コメントアウトしなくて大丈夫です！

2023-03-25 14:25 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +               ]);
まだインデントがおかしいですね、、、！
forとDBの間のインデントは、
タブキー１回押下分（半角スペース４つ分）です！

今だと、見る限り半角スペース７つ分のインデントが付いてしまっています・・・！
お手数ですが修正願います！

2023-03-26 00:50 UTC, yukihiroLaravel approved these changes
OKなので、
マージしました！

おつかれさまでした！

2023-03-26 00:52 UTC, yukihiroLaravel commented on database/seeds/DatabaseSeeder.php
>          $this->call(UsersTableSeeder::class);
上から順番に実行されて、
Usersテーブルシーダーを実行してから
Postのシーダーを実行しないと、user_idがないというエラーが出てしまうからです

2023-03-26 00:52 UTC, merged