#194 トップページの投稿表示(﨑園)
yukihiroLaravel/joint_develop pull request #218
Opened 2023-04-02 07:10 UTC by tomoakisakizono

## Issue
- Closes #194 

## 概要
- トップページのユーザーの投稿部分のみ表示させる。

## 動作確認手順
- localhost:8080へアクセス。
- 投稿入力欄の下部にユーザーの投稿が降順で表示されているか確認。
- 表示項目はユーザーネーム、テキスト投稿、登録時間、アバターの４項目。
- １１投稿目からは２ページ目へ移行（ページ下部に２ページ目の表示があります）。

## 考慮してほしいこと
-posts.blade.phpにするとエラーメッセージが表示さましたが、post.blade.phpに変更すると表示できました。
-postsテーブルに投稿登録数が１０件以下ですとページネートの確認ができないので、テストデータを入力する必要があるかもしれません。

## 確認してほしいこと
- 前回のMTGでもお話させていただきましたresourcesのpostsフォルダ内にposts.blade.phpとファイルを作るとエラーが出て表示されませんでした。MTG時の確認方法以外でpostsで登録できる方法などございましたご教授のほど何卒よろしくお願い致します。

2023-04-03 00:31 UTC, Osk0830 requested changes
お疲れ様でした！
概ね良く書けていると思います！
現状、このブランチに、西田さんが作業したpostsテーブル関連のマイグレーションとシーダーが取り込まれていないので、動作確認ができませんでした。
まずはこちらの対応からお願いします！

[![Image from Gyazo](https://i.gyazo.com/2df7e6725bd8b144da62bfd76cdbd94e.png)](https://gyazo.com/2df7e6725bd8b144da62bfd76cdbd94e)

[![Image from Gyazo](https://i.gyazo.com/2eb9f31ea19061d32e7fc49b3f029c41.png)](https://gyazo.com/2eb9f31ea19061d32e7fc49b3f029c41)

現状、ソースだけ見ていくつかコメントしましたので、こちらも合わせてご確認くださいね！

2023-04-03 00:31 UTC, Osk0830 commented on resources/views/posts/post.blade.php
> +                    <p class="mt-3 mb-0 d-inline-block"><a href="#">{{ $post->user->name }}</a></p>
- 3〜5行目でせっかく`$post->user`を`$user`に格納しているので、９行目も８行目のような値の取り出し方をできそうですね。もしくは９行目のように書くのであれば、８行目もそれに揃えましょう！いずれにせよ2種類の書き方が混在しないようにするのが、見通しの良いコードになりますので、整理してみてくださいね。

2023-04-03 00:31 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +            </div>
- ソースを見てみますと、このファイル全体を通してインデントがおかしなことになってるようですので、インデントを綺麗に揃えてみてください。

2023-04-03 00:31 UTC, Osk0830 commented on resources/views/posts/post.blade.php
> +                        <p class="mb-2">{{ $post->text }}</p>
- ここの`$post->text`は、西田さんのマイグレーションファイルではどうなっているか確認するのを忘れないでくださいね。

2023-04-04 00:38 UTC, tomoakisakizono commented on resources/views/posts/post.blade.php
> +                        <p class="mb-2">{{ $post->text }}</p>
- 西田さんのマイグレーションファイルも投稿内容部分はtextで統一されておりましたこと確認できました！！

2023-04-04 00:38 UTC, tomoakisakizono commented on resources/views/welcome.blade.php
> +            </div>
- 修正致しました！
ご確認のほど何卒よろしくお願い致します。
修正点ございましたら、何度も申し訳ございませんがご教示ください！修正致します！

2023-04-04 00:39 UTC, tomoakisakizono commented on resources/views/posts/post.blade.php
> +                    <p class="mt-3 mb-0 d-inline-block"><a href="#">{{ $post->user->name }}</a></p>
- かしこまりました！勉強になります！ありがとうございます！！
修正致しましたのでご確認のほど何卒よろしくお願い致します。

2023-04-04 07:18 UTC, Osk0830 requested changes
色々とお疲れ様でした！
ありがとうございました！
ほぼ問題ないのですが、少しだけコメントしましたので、ご確認いただければと思います！

2023-04-04 07:18 UTC, Osk0830 commented on app/Post.php
> +
- 現状の要件では、postは論理削除（ソフトデリート）をしなくてもOKです。マイグレーションでもソフトデリート用のカラムを設けないようにしようとしていた感じです。論理削除にしてしまうと、後々の削除などで実装でレベルが上がりすぎてしまうこともあり、一旦は物理削除（ハードデリート）にすることにしています。なので、６行目と１０行目は一旦削除しましょう。

2023-04-04 07:18 UTC, Osk0830 commented on database/migrations/2023_03_23_004939_create_posts_table.php
> +            $table->softDeletes();
- こちら、上記理由から、一旦はなしでOKです！コメントアウトではなく、削除しといていただいてOKです！

2023-04-04 07:39 UTC, tomoakisakizono commented on database/migrations/2023_03_23_004939_create_posts_table.php
> +            $table->softDeletes();
かしこまりました！！
削除完了致しました！！

2023-04-04 07:41 UTC, tomoakisakizono commented on app/Post.php
> +
こちらも認識確認かしこまりました！
削除完了しました！！

2023-04-04 08:32 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらマージしますね！　

2023-04-04 08:32 UTC, merged