#7 共通ファイル作成  #8 ヘッダー・フッター & トップページのタイトルのみ表示「Topic Posts」（かねこなおき）
yukihiroLaravel/joint_develop pull request #22
Opened 2022-07-04 01:51 UTC by Kaneko0000

## issue
- Close #7 
- Close #8

## 概要
- 共通ファイルの作成
- commonsフォルダでheader, footerの作成
- トップページのタイトルのみ表示

## 動作確認手順
- headerナビメニューのhover時の変化

## 考慮してほしいこと
- issueですが#7と#8を同時に作成したため、プルリクしてしまうことになりました。申し訳ありませんがよろしくお願いいたします。

## 確認してほしいこと 
-  headerナビ部分のhover時の色ですが、bootstrapで変えようとしましたがわからず、cssで作成しました。それもhtml上に記述しましたが、cssファイル作成した方がよかったでしょうか。

2022-07-04 02:40 UTC, yukihiroLaravel reviewed
プルリクメッセージなども良い感じで書いていただいていると思います！☺️
コードのレビューはHANさんにお任せしようと思いますが、
１点プルリクメッセージで気になった点があったので、直せたら直してみて下さい！

`動作確認手順： headerナビメニューのhover時の変化`

と書かれていたのですが、今回はhover時以外に、
「トップページにアクセスしてきちんと表示できるどうか？」
が1番重要なので
アクセスすべきURLはどこなのか？をこちらに書くようにしましょう！

```
例）下記URLにアクセスして、トップページとヘッダー・フッターが表示されることを確認
　localhost:8080
```

2022-07-04 05:10 UTC, Kaneko0000 commented
ご指摘ありがとうございます。
プルリク編集しました。

2022-07-05 00:06 UTC, Osk0830 requested changes
お疲れ様です。
少し遅くなってしまいましたが、レビューさせて頂きました。

すごく綺麗にしっかりと書けていて、素晴らしいと思います！

> headerナビ部分のhover時の色ですが、bootstrapで変えようとしましたがわからず、cssで作成しました。それもhtml上に記述しましたが、cssファイル作成した方がよかったでしょうか。

こちらですが、下記の箇所ですね。

[![Image from Gyazo](https://i.gyazo.com/e482d86f083c5d525b9dc500d66cc31c.png)](https://gyazo.com/e482d86f083c5d525b9dc500d66cc31c)

そうですね。
役割に応じてファイルは切り離していた方が、
色々とメンテナンスなどにも強くなりますし、
タグに直接インラインで当てたスタイルは、
後から上書きなどもしにくくなるので、
できればCSSファイルに別途書いた方がいいと思います。

CSSの設置場所や読み込み方の確認も兼ねて、
是非一度CSSに書き分けてみていただければと思います！

2022-07-05 00:31 UTC, Kaneko0000 commented
お疲れ様です。
レビューして頂き、ありがとうございます。

そうですね。おっしゃる通り今後のメンテナンスや書き換えのことも考えてcssファイルを作成すべきでした。cssの復習も兼ねて一度cssファイルを作成してやってみたいと思います。

2022-07-05 05:06 UTC, Kaneko0000 commented
お疲れ様です。
Cssファイル作成しました。
確認お願いいたします。

2022-07-05 10:26 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらマージしますね！

2022-07-05 10:26 UTC, merged

2022-07-06 10:33 UTC, yukihiroLaravel commented
close #7 #8