#214 ユーザ編集画面・更新、エラーメッセージ編集（山田）
yukihiroLaravel/joint_develop pull request #222
Opened 2023-04-05 14:46 UTC by yamadaman-bs

## issue
- Closes #214

## 概要
- ユーザ編集画面・更新
- バリデーションメッセージ変更後→エラーメッセージ編集

## 動作確認手順
#214 
- web.php、UsersControllerを変更
- edit.blade作成
- UsersRequest 作成

エラーメッセージ
- login.blade、error_messages.blade 変更

## 考慮して欲しいこと
- UsersControllerの表記が間違っていないか見て頂きたい。
``` $user = User::findOrFail($id);
        $data=[
            'user' => $user,
        ];
        return view('users.edit',$data);
```

## 確認して欲しいこと
- UserRequestのrulesで他の書き方などがあれば教えていただきたい。
```
return [
                'name' => ['required', 'string', 'max:255'],
                'email' => ['required', 'string', 'email', 'max:255',
                            Rule::unique('users')->ignore(Auth::id())],
                'password' => ['required', 'string', 'min:8', 'confirmed'],
            ];
    }
```

2023-04-08 03:31 UTC, Osk0830 requested changes
お疲れ様でした！
綺麗に書けていますし、概ね問題もないと思います！素晴らしいです！
いくつかだけコメントしましたので、確認よろしくお願いします！

2023-04-08 03:31 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +    }
- 現状ですと、ログインさえしていれば、他のユーザーの編集画面にもアクセスできてしまいます。仮にidが1のユーザでログインしていても、/users/2/editにGETリクエストを送ると、ページが表示されてしまいます。ログインしているユーザー自身のページのみ表示されるようにして、そうでない場合はトップページにリダイレクトされるようにしてみてください。

2023-04-08 03:31 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +    }
- こちらも上記同様、ログインしてる本人のみ更新できるような仕組みにしましょう。

2023-04-08 03:31 UTC, Osk0830 commented on resources/lang/ja/validation.php
> +    'confirmed'            => ':attributeとパスワード確認が一致していません。',
- `confirmed`は、パスワード以外でも汎用的に用いられるものなので、ここを「パスワード確認」と変更してしまうのはよくないと思います。フォームリクエスト内で上書きするようにした方が良さそうです。

2023-04-08 03:31 UTC, Osk0830 commented on resources/views/users/edit.blade.php
> +        <input type="hidden" name="id" value="{{ $user->id }}" />
- パラメータとしてidを送っているのでここではhiddenで改めて送る必要は、今の実装だと、なさそうですね。

2023-04-09 12:40 UTC, yamadaman-bs commented on app/Http/Controllers/UsersController.php
> +    }
$user = \Auth::user();
を追加しました。
挙動も確認しましたが私の環境では問題ありませんでした。
ご確認のほど、よろしくお願いいたします。

2023-04-09 12:41 UTC, yamadaman-bs commented on app/Http/Controllers/UsersController.php
> +    }
$user = \Auth::user();
を追加しました。
ご確認のほど、よろしくお願いいたします。

2023-04-09 12:41 UTC, yamadaman-bs commented on resources/views/users/edit.blade.php
> +        <input type="hidden" name="id" value="{{ $user->id }}" />
ご指摘いただいた箇所は削除いたしました。
ご確認のほどよろしくお願いいたします。

2023-04-09 12:43 UTC, yamadaman-bs commented on resources/lang/ja/validation.php
> +    'confirmed'            => ':attributeとパスワード確認が一致していません。',
フォームリクエスト内に
public function messages()
    {
        return [
            'confirmed' =>'パスワードとパスワード確認が、一致していません。'];
    }
を追加いたしました。
ご確認をお願いいたします。

2023-04-16 23:48 UTC, Osk0830 requested changes
お疲れ様でした！
だいぶ仕上がって来ましたね！もう一息だと思います。

いくつかコメントしましたので、確認よろしくお願いします！

2023-04-16 23:48 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +    }
- 36行目は不要なコメントアウトだと思いますので、こういうコメントアウトは削除しましょう。

- if文での判定は、前回のMTGにお伝えした通りの挙動になるように実装されていると思います。素晴らしいですね！ただ、今の実装では、if文の条件に合致しなかった場合に何も返せてあげていないので、仮にuser1でログイン中に、user2の編集ページにアクセスしようとした場合に、ページが真っ白になり、そこで処理が終わってしまいます。他人の編集ページにアクセスした場合、つまりif文の条件に合致しなかった場合の処理まで追記してみてくださいね。

　[![Image from Gyazo](https://i.gyazo.com/a3c47b264f096bcfbd33411cde3a6f87.png)](https://gyazo.com/a3c47b264f096bcfbd33411cde3a6f87)

2023-04-16 23:48 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +       };
- インデントが崩れているので、まずは揃えてくださいね。

- 修正すべき内容は、edit()ファンクションと同じです。

2023-04-16 23:48 UTC, Osk0830 commented on app/Http/Requests/UserRequest.php
> +            ];
- 34行目の不要な改行は削除しましょう。

2023-04-16 23:48 UTC, Osk0830 commented on app/Http/Requests/UserRequest.php
> +    }
- 他の箇所と合わせて、41行目の最後の `];`は、次の行に来るようにするのが良さそうですね。その際、インデントにも気をつけてくださいね。

2023-04-16 23:48 UTC, Osk0830 commented on resources/views/users/edit.blade.php
> +        </div>
- 29行目の不要な改行は削除しましょう。

2023-04-16 23:48 UTC, Osk0830 commented on routes/web.php
> +    });
- 他の行とのインデントがずれているようなので、みやすく整理してみてくださいね。
- また、もし可能であれば、26行目から36行目までは、同じ `/users`に関するものなので、一つにまとめられるといいですね。山田さんの方で整理できそうであれば、整理してみていただければと思います。

2023-04-17 02:55 UTC, yamadaman-bs commented on app/Http/Controllers/UsersController.php
> +    }
・コメントアウトは削除しました。
・if文を修正しました。
西田さんのshow.blade.phpを参考にしました。

ご確認ください。

2023-04-17 02:56 UTC, yamadaman-bs commented on app/Http/Controllers/UsersController.php
> +       };
・インデントを揃えております。

2023-04-17 02:56 UTC, yamadaman-bs commented on app/Http/Requests/UserRequest.php
> +            ];
・コメントアウトは削除しました。

2023-04-17 02:56 UTC, yamadaman-bs commented on app/Http/Requests/UserRequest.php
> +            ];
・行削除しております。

2023-04-17 02:57 UTC, yamadaman-bs commented on app/Http/Requests/UserRequest.php
> +    }
・インデントを揃えております。

2023-04-17 02:58 UTC, yamadaman-bs commented on resources/views/users/edit.blade.php
> +        </div>
・不要な行は削除しております。

2023-04-17 03:16 UTC, yamadaman-bs commented on routes/web.php
> +    });
・インデントを整理しました。
・ログインの箇所は/loginまたは/logoutから始まっています。
おっしゃって頂いているのは全て頭に/usersをつけてURLを作成するということでしょうか？
ご教授願います。

2023-04-18 07:41 UTC, Osk0830 requested changes
お疲れ様でした！
ルーティングの整理もありがとうございます！

ほぼOKですが、少しだけ前回の問題がクリアできていない箇所があるので、確認よろしくお願いします！
修正後は動作確認も行って、想定通りの挙動になっているかも確認してみてくださいね！

2023-04-18 07:41 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +    }
- こちら、前回の問題点が改善できていないようですね。。動作確認など行ってみた感じでしょうか？ログインした状態で、`/users/ログインしている本人のidではないid/edit`にアクセスした場合に、画面が真っ白にならないようにしましょう。お手本サイトでは404ページが表示されていますのでそれでもいいですし、トップページなどに強制的に戻すのでもOKです。

2023-04-18 07:41 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +        };
- こちら、インデントが少しおかしいようです。
- こちらも、editと同じように、本人ではない場合の処理を念のために追加しておきましょう。

2023-04-18 09:36 UTC, yamadaman-bs commented on app/Http/Controllers/UsersController.php
> +        };
・return箇所のインデントを修正しております。
・上記と同じようにabort`(404);`で記載しております。

2023-04-18 09:36 UTC, yamadaman-bs commented on app/Http/Controllers/UsersController.php
> +    }
お疲れ様です。

ご指摘内容の修正できておらず申し訳ございませんでした。
下記のようなコードを記載しました。
ご確認をお願いいたします。


```php

```

2023-04-18 09:37 UTC, yamadaman-bs commented on app/Http/Controllers/UsersController.php
> +    }
お疲れ様です。

ご指摘内容の修正できておらず申し訳ございませんでした。
下記のようなコードを記載しました。
ご確認をお願いいたします。


```

```

2023-04-18 09:38 UTC, yamadaman-bs commented on app/Http/Controllers/UsersController.php
> +    }
お疲れ様です。

ご指摘内容の修正できておらず申し訳ございませんでした。
下記のようなコードを記載しました。
ご確認をお願いいたします。
```
if(\Auth::check() && \Auth::id() == $user->id){
            $data=[
                'user' => $user,
            ];
            return view('users.edit',$data);
        }else{
            abort(404);
        };
```

2023-04-18 09:54 UTC, Osk0830 approved these changes
お疲れ様でした！
こちら大丈夫そうなのでマージしますね！
引き続き頑張っていきましょう！

2023-04-18 09:54 UTC, merged