#194 トップページの投稿表示(杉原）
yukihiroLaravel/joint_develop pull request #223
Opened 2023-04-06 12:50 UTC by kenta327

## issue
・Closes #194 
## 概要
・トップページの投稿表示
# 動作確認手順
・http://localhost:8080/にアクセス
・投稿画面が表示されている事を確認
・投稿内容：４項目（ユーザー名、投稿コメント、コメント作成日時、Gravatarの表示）
・投稿日時の新しいデータから降順に表示されている事を確認
・画面下部にpaginate機能の確認→２を押下しページが遷移されることを確認
・ヘッダー部のログインからログインしトップページに遷移する事を確認
・ログインしたユーザーの投稿のみ編集、削除ボタンが表示されていることを確認

考慮して欲しいこと
　paginate機能で１０件以上は次ページに出力される事を確認する為、
　PostsTableSeederを15件分作成するように変更しました。
　PostsTableSeederを流した後に、追加で同一ユーザーで複数投稿したデータでの検証もお願いしたいので
   　tinker又はadmainerのinsert文にて１投稿追加してからの動作確認お願いします。
```
 php artisan migrate:fresh
 php artisan db:seed
```

```
 use App\posts
> $posts = new  posts;
> $posts->id = 16;
> $posts->text = "test16";
> $posts->user_id = "1";
> $posts->created_at = now();
> $posts->save();
```

確認して欲しいこと
宜しくお願いいたします。

2023-04-06 13:31 UTC, yukihiroLaravel requested changes

2023-04-06 13:31 UTC, yukihiroLaravel commented on resources/views/post/post.blade.php
> +                <p class="mt-3 mb-0 d-inline-block"><a href="">{{$user->name}}</a></p>
$post->user->name

2023-04-06 13:31 UTC, yukihiroLaravel commented on resources/views/post/post.blade.php
> +                <img class="mr-2 rounded-circle" src="{{ Gravatar::src($user->email, 55) }}" alt="ユーザのアバター画像">
$post->user->email

2023-04-06 13:31 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +<!-- @include('post.post') -->
削除しましょう

2023-04-06 13:31 UTC, yukihiroLaravel commented on routes/web.php
> +// });
削除しましょう

2023-04-07 10:47 UTC, yukihiroLaravel requested changes
動作確認したところいくつか新規に変更していただきたい箇所が見つかりましたので
３つ修正お願いします🙇‍♂️

2023-04-07 10:47 UTC, yukihiroLaravel commented on resources/views/post/post.blade.php
> +<div class="m-auto" style="width: fit-content">{{ $posts->links('pagination::bootstrap-4') }}</div>
フッターとの間隔が空いていないので
（下記の通りだとうまくいかないかもしれないので調整が必要ですが）

`<div class="m-auto pb-5"`

こんな感じでフッターとの感覚を空けるための対応が必要になるかと思います！

2023-04-07 10:47 UTC, yukihiroLaravel commented on resources/views/post/post.blade.php
> +
ここの空行は不要です！

2023-04-07 10:47 UTC, yukihiroLaravel commented on app/Http/Controllers/PostController.php
> +        $posts = Posts::orderBy('created_at','desc')->paginate(10);
先日お聞きしていた通り
今の形だと

test1
test2
test3
・
・
・

こんな感じで
お手本と逆の並びになっていませんか？

ただしくはこうならないといけないと思います

test11
test10
test9
・
・
・

逆にするには
やっぱりお伝えしていた通り

`$posts = Posts::orderBy('id', 'desc')->paginate(10);`
とする必要がありそうです！

2023-04-07 12:57 UTC, kenta327 commented on resources/views/post/post.blade.php
> +<div class="m-auto" style="width: fit-content">{{ $posts->links('pagination::bootstrap-4') }}</div>
footer.blade.phpファイルの
クラス内に.fixed-bottom
モックアップにも元々記述されていないのですが
.fixed-bottom
でページ最下部固定が入れられていたのでこの記述を削除しました。
これで再度実行したところモックアップと同じ間隔になっていることを確認しました。

2023-04-08 08:02 UTC, kenta327 commented on resources/views/post/post.blade.php
> +                <p class="mt-3 mb-0 d-inline-block"><a href="">{{$user->name}}</a></p>
修正しました。

2023-04-08 08:03 UTC, kenta327 commented on resources/views/post/post.blade.php
> +                <img class="mr-2 rounded-circle" src="{{ Gravatar::src($user->email, 55) }}" alt="ユーザのアバター画像">
修正しました

2023-04-08 08:03 UTC, kenta327 commented on resources/views/welcome.blade.php
> +<!-- @include('post.post') -->
削除しました

2023-04-08 08:03 UTC, kenta327 commented on routes/web.php
> +// });
３行削除しました。

2023-04-08 08:05 UTC, kenta327 commented on resources/views/post/post.blade.php
> +
空白削除しました。

2023-04-08 08:06 UTC, kenta327 commented on app/Http/Controllers/PostController.php
> +        $posts = Posts::orderBy('created_at','desc')->paginate(10);
create_atからではなくidから取得するに変更しました。

2023-04-08 11:51 UTC, yukihiroLaravel approved these changes
OKですので、マージしました✨
おつかれさまでした！

2023-04-08 11:51 UTC, merged