#182 投稿削除（杉原）
yukihiroLaravel/joint_develop pull request #228
Opened 2023-04-14 10:54 UTC by kenta327

## issue
・ Closes #182 
## 概要
・ 投稿削除
## 動作確認手順
・ 下記操作を実行。  
①http://localhost:8080/を開きログインする
②ログインしたユーザの投稿を探し削除ボタンを押下する
## 確認してほしいこと
①削除ボタン押下後現在いるページにリロードされている事
②削除対象に指定した投稿が画面上から削除されている事
③adminerにて削除対象のデータが論理削除されている事を確認

宜しくお願いいたします。

2023-04-15 00:33 UTC, yukihiroLaravel requested changes
確認しまして、
１点インデントのみ修正いただければOKです！☺️

2023-04-15 00:33 UTC, yukihiroLaravel commented on resources/views/post/post.blade.php
> +                        @method('DELETE')
１つインデントが必要ですかね！

2023-04-16 10:38 UTC, kenta327 commented on resources/views/post/post.blade.php
> +                        @method('DELETE')
修正しました。

2023-04-17 12:25 UTC, yukihiroLaravel approved these changes
マージ

2023-04-17 12:25 UTC, merged