#184 投稿更新（山田）
yukihiroLaravel/joint_develop pull request #238
Opened 2023-04-22 16:23 UTC by yamadaman-bs

## issue
- Closes #184 

## 概要
- 投稿編集画面・更新

## 動作確認手順
#184 
- web.php、PostsControllerを変更
- edit.blade.php(posts)作成
- PostRequest 作成

## 考慮して欲しいこと
- PostRequestの書き方は表記の方法を現時点でマージされたものを元に作成しております。

## 確認して欲しいこと
- バリデーションの内容に相違がないかご確認願います。

2023-04-23 03:29 UTC, Osk0830 requested changes
お疲れ様でした！
概ね良くできていると思います！
少しだけ修正が必要で、コメントしましたので、確認よろしくお願いします！

2023-04-23 03:29 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        }else{
- こちら、不要な記述がいくつか含まれているようですので、どれが要るもので要らないものか検討して、整理してみてくださいね。
- if文の条件がおかしくないでしょうか？

2023-04-23 03:29 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +            return view('welcome',$data);
- welcomブレードにreturnする内容としてどれが要るものなのか検討してみてもらえると良さそうですね。

2023-04-23 15:08 UTC, yamadaman-bs commented on app/Http/Controllers/PostsController.php
> +            return view('welcome',$data);
下記のように修正いたしました。
```
public function update(PostRequest $request, $id)
    {
        $post = Post::findOrFail($id);
        if(\Auth::id() === $post->user_id){
            $post->text = $request->text;
            $post->save();
            $posts = Post::orderBy('created_at','desc')->paginate(10);
            $data =[
                'post'=> $post,
                'posts' => $posts,
            ];
            return view('welcome',$data);
        }else{
            abort(404);
        }
    }
```

修正したのですが、
`$posts = Post::orderBy('created_at','desc')->paginate(10);`
は他に記述方法があるのでしょうか。
ご確認ください。

2023-04-23 15:08 UTC, yamadaman-bs commented on app/Http/Controllers/PostsController.php
> +        }else{
ご指摘頂いた部分を修正いたしました。
```
public function edit($id)
    {
        $post = Post::findOrFail($id); 
        if(\Auth::id() === $post->user_id){
            return view('posts.edit', ['post' => $post]);
        }else{
            abort(404);
        };
    }
```

2023-04-24 01:21 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +            return view('welcome',$data);
お疲れ様です！

①
`$posts = Post::orderBy('created_at','desc')->paginate(10);`

これはこの記述で問題ないですよ！

②
`welcome.blade.php`で、どのようなデータを必要としているか、
bladeの方を今一度チェックしてみてください。
現状のコントローラーの記述では、bladeの方で必要としていないデータまで渡してないでしょうか？

2023-04-24 06:16 UTC, yamadaman-bs commented on app/Http/Controllers/PostsController.php
> +            return view('welcome',$data);
ありがとうございます。

こちらの内容で修正いたしました。
ご確認ください。
```
public function update(PostRequest $request, $id)
    {
        $post = Post::findOrFail($id);
        if(\Auth::id() === $post->user_id){
            $post->text = $request->text;
            $post->save();
            $posts = Post::orderBy('created_at','desc')->paginate(10);
            view('welcome',['posts' => $posts]);
        }else{
            abort(404);
        }
    }
}
```

2023-04-24 22:57 UTC, Osk0830 requested changes
お疲れ様でした！
動作確認が抜けている箇所があるようですので、今一度確認よろしくお願いします！

2023-04-24 22:57 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +            view('welcome',['posts' => $posts]);
- こちら動作確認済みでしょうか？現状では、必要な記述が抜けているため、更新完了後に意図通りの挙動にならなくないでしょうか？

2023-04-25 16:56 UTC, yamadaman-bs commented on app/Http/Controllers/PostsController.php
> +            view('welcome',['posts' => $posts]);
大変失礼いたしました。
returnが抜けておりました。

2023-04-25 23:33 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらマージしますね！
引き続き頑張っていきましょう！

2023-04-25 23:33 UTC, merged