#188 フォロー機能
yukihiroLaravel/joint_develop pull request #243
Opened 2023-04-28 02:47 UTC by tomoakisakizono

## issue
- Closes #188

## 概要
- フォロー機能とフォロー機能によるユーザ詳細画面のタイムラインタブ切り替え

## 動作確認手順
- フォロー機能の確認
1. マイグレーションにて中間テーブルを作成(TableName:follow_users)
　ーーコマンド:`php artisan migrate`ーー
2. アプリへ移動し、登録されているユーザでログイン
3. トップページに表示されているログインユーザ以外の他ユーザの詳細画面へ移動
4. ユーザアバターの下側に”フォローをする”ボタンが表示されているか確認
5. ”フォローをする”ボタン押下→同時に画面が更新され”フォローを外す”にボタンが変化することを確認
6. アドマイナーのfollow_usersテーブルにログインユーザと該当他ユーザのIDでフォローの登録があることを確認
7. 次に”フォローを外す”ボタン押下→同時に画面が更新され”フォローをする”にボタンが変化することを確認
8. アドマイナーにて手順6.のフォロー登録が消えていることを確認
9. ログインユーザ詳細ページに移動したときに、ボタンが”ユーザ情報の編集”であることも確認

-フォロー機能によるタイムラインタブ切り替え
1. 登録ユーザでログイン
2. ログインユーザにて他ユーザをフォローする
3. ログインユーザ詳細画面へ移動し、フォロー中タブを押下
4. 手順2でフォローしたユーザが表示されていることを確認
5. 手順1〜4を実行したユーザとは違うユーザでログイン
6. 手順1〜4のユーザをフォローする
7. 手順1〜4のユーザで再ログイン
8. ユーザ詳細画面へ移動し、フォロワータブ押下
10. 手順6.のユーザが表示されていることを確認
11. 各項目タブ表示の下の数字は各項目の表示数であることも確認

## 考慮してほしいこと
- 応用講座(いいね機能とお気に入り動画タブ変更)を参考にコード入力
- issue#188フォロー機能と#190フォロー機能によるタイムライン切り替えを同じブランチで作成してしまいました。申し訳ございません。

## 確認してほしいこと
- 無駄なところや改善点などございましたらご教授のほど何卒よろしくお願い致します。

2023-04-29 02:39 UTC, Osk0830 requested changes
お疲れ様でした！
かなり難易度の高い実装を、とてもしっかり綺麗に書けていると思います！素晴らしいです！

量がかなり多く、まだ見落としている部分もあるかもしれませんが、ひとまず気づいた点について書きましたので、ご確認いただければと思います！

2023-04-29 02:39 UTC, Osk0830 commented on app/User.php
> +    }
- 基本的な記述は問題なさそうですね！ただ、今の状態だと、自分自身をフォローできてしまわないでしょうか？仕様として良くないと思いますので、自分自身はフォローできないようにしてみてください。このモデル内に自分自身であるかどうかをチェックした結果を返すクラスメソッドを作り、それを活用する感じで進めてみるといいかもしれません。

　[![Image from Gyazo](https://i.gyazo.com/804df6b9601aa18f553f1dfa4aa1409a.png)](https://gyazo.com/804df6b9601aa18f553f1dfa4aa1409a)

2023-04-29 02:39 UTC, Osk0830 commented on app/User.php
> +    }
- こちらも上記と同様の仕組みを組み込んでみてくださいね。

2023-04-29 02:39 UTC, Osk0830 commented on resources/views/users/follower.blade.php
> +      </ul>
- この部分ですが、`users/show.blade`, `users/follower.blade`, `users/following.blade`で基本的には共通しているようなので、ユーザー情報を表示するカードの部分、タブの部分などに分けて考えて、各部分を部品化してしまうなどして、パーツのコードは1つだけにした方が良さそうですね。今の状態ですと、例えばデザインの変更などが生じた場合、3つのBladeをそれぞれ修正しなければならず、メンテナンスなどにかなり手間が生じてしまうような気がします。。

2023-05-01 15:07 UTC, tomoakisakizono commented on app/User.php
> +    }
確認が至りませんでした！
ご指摘いただきました内容、学習させていただきました！
修正完了致しました！！

2023-05-01 15:07 UTC, tomoakisakizono commented on app/User.php
> +    }
こちらも同様に修正完了致しました！
ありがとうございます！！

2023-05-03 12:54 UTC, tomoakisakizono commented on resources/views/users/follower.blade.php
> +      </ul>
仰る通りです。
考え方に苦労しましたが修正完了致しました！
学習しました！！

2023-05-04 09:25 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらしっかり修正できているのでマージしますね！
パーツ化は色々なやり方があると思いますので、今後また、どんな感じでパーツ化したらより良いかを考えてみるのもいいかもしれませんね。

引き続き頑張っていきましょう！

2023-05-04 09:25 UTC, merged