更新フラッシュメッセージ（平林）
yukihiroLaravel/joint_develop pull request #245
Opened 2023-04-29 22:22 UTC by ka2ki1

## 概要
- 更新のフラッシュメッセージの表示

## 動作確認手順
- 編集画面から更新ボタンを押した際にトップページに遷移し更新フラッシュメッセージが出ることを確認。

## 確認してほしいこと
- 前回の内容にはなるんですがユーザー詳細画面の削除フラッシュメッセージをタイムラインのタブの幅で真上に持ってくるやり方を教えていただきたいです。  そのような配置でもおかしくないでしょうか？

2023-04-30 02:05 UTC, yukihiroLaravel requested changes
コメントしましたので、修正願います！

2023-04-30 02:05 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +@if (session('updateMessage'))
updateMessage の if文をつくらなくていいと思います！
内容的に、successMessage と全く同じだからです！

updateMessage は削除していいと思います！

2023-04-30 02:05 UTC, yukihiroLaravel commented on app/Http/Controllers/PostController.php
> +        return redirect('')->with('updateMessage', '更新しました！');
successMessage に変更した方がいいと思います。

また、他の箇所で「しました！」とびっくりマークはついていましたでしょうか？
「。」で終わっていた気がするのでそこはきっちり統一しましょう。

エンジニアはこういう結構細かい部分が求められるので
誤っていれば修正しましょう✨

2023-04-30 16:11 UTC, ka2ki1 commented on resources/views/welcome.blade.php
> +@if (session('updateMessage'))
対応しました。

2023-04-30 16:15 UTC, ka2ki1 commented on app/Http/Controllers/PostController.php
> +        return redirect('')->with('updateMessage', '更新しました！');
対応しました。

2023-05-01 00:27 UTC, yukihiroLaravel approved these changes
OKなのでマージしました✨
おつかれさまでした！

2023-05-01 00:28 UTC, merged