#190フォローによるタイムライン変更（杉原）
yukihiroLaravel/joint_develop pull request #250
Opened 2023-04-30 13:08 UTC by kenta327

## issue
* Closes #190
## 概要
* ユーザー詳細画面のタブの切り替えによる表示の切り替え（タイムライン、フォロー、フォロワー）
## 動作確認手順
## 下記操作を実行。  
* 事前データ要　１ユーザを選択し投稿11件　フォロー11件　フォロワー11件分を実行したデータを作成しておく
1.  詳細画面に遷移
* 初期表示→タイムラインに投稿が表示されている事を確認
2. フォロー中タブを選択しフォロー中リンクを押下する
*  テストユーザーがフォローしているユーザーが昇順で表示されている事を確認
*  10ユーザー以上の表示によりページ送りの表示も確認
*  表示されているユーザーがadminerにてテストユーザがフォローしているユーザーである事を確認
*  タブもフォロー中が選択された状態(active)になっている事を確認
*  表示されているユーザー数とタブ上に表示されている数が一致していることを確認
3. フォロワータブを選択しフォローワーリンクを押下する
*  テストユーザーをフォローしているユーザーが昇順で表示されている事を確認
*  10ユーザー以上の表示によりページ送りの表示も確認
*  表示されているユーザーがadminerにてテストユーザがフォローされているユーザーである事を確認
*  タブもフォワーが選択された状態(active)になっている事を確認
*  表示されているユーザー数とタブ上に表示されている数が一致していることを確認
4. タイムラインタブを選択しタイムラインリンクを押下する
*  テストユーザーが投稿したデータが降順で表示されている事を確認
*  10投稿の表示によりページ送りの表示も確認
*  表示されている投稿がadminerにてテストユーザが投稿しているデータである事を確認
*  タブもタイムラインが選択された状態(active)になっている事を確認
*  表示されている投稿数とタブ上に表示されている数が一致していることを確認
5. フォロワーを外すボタンを押下する
*  フォロワータブの数字が１減算されていることを確認
*  表示もフォローを外したユーザは表示されていない事を確認
## 考慮してほしいこと
* 処理を作っている段階で被っているソースコードが多数出た為、共通化してみましたがいまいちかもしれないので元ソースはこちらでも念のため退避しています。
## 確認してほしいこと
都合上時間があいてしまいなかなか進めませんでした、おそくなり大変申し訳ございません。ご確認宜しくお願いいたします。

2023-05-01 02:24 UTC, yukihiroLaravel requested changes
素晴らしい出来です！
細かい点のみ、修正お願いします。

2023-05-01 02:24 UTC, yukihiroLaravel commented on app/Http/Controllers/FollowController.php
> +        $followings = $user->followings()->orderBy('id','asc')->paginate(10);
並び替え

2023-05-01 02:24 UTC, yukihiroLaravel commented on app/Http/Controllers/FollowController.php
> +        $followers = $user->followers()->orderBy('id','asc')->paginate(10);
並び替え

2023-05-01 02:24 UTC, yukihiroLaravel commented on app/Http/Controllers/FollowController.php
> +    public function followings_show($id)
followingsShow

2023-05-01 02:24 UTC, yukihiroLaravel commented on resources/views/commons/UserDetailsCard.blade.php
> +<div class="card bg-info">
ファイル名→スネークケース user_details_card

2023-05-01 02:24 UTC, yukihiroLaravel commented on resources/views/follow/followings.blade.php
> +        @include('commons.UserDetailsTab', ['followUser'=>$user])
['followUser' => $user]

2023-05-04 13:22 UTC, kenta327 commented on app/Http/Controllers/FollowController.php
> +        $followings = $user->followings()->orderBy('id','asc')->paginate(10);
修正しました。

2023-05-04 13:26 UTC, kenta327 commented on app/Http/Controllers/FollowController.php
> +        $followers = $user->followers()->orderBy('id','asc')->paginate(10);
修正しました。

2023-05-04 13:28 UTC, kenta327 commented on app/Http/Controllers/FollowController.php
> +    public function followings_show($id)
//testsors削除しました。
メソッド名、キャメルケースに変更しました。

2023-05-04 13:31 UTC, kenta327 commented on resources/views/commons/UserDetailsCard.blade.php
> +<div class="card bg-info">
ファイル名、スネークケースに変更しました

2023-05-04 14:02 UTC, kenta327 commented on resources/views/follow/followings.blade.php
> +        @include('commons.UserDetailsTab', ['followUser'=>$user])
半角スペースを入れました。

2023-05-04 14:42 UTC, yukihiroLaravel requested changes
一部のみコメントしました！
ご確認ください！

2023-05-04 14:42 UTC, yukihiroLaravel commented on app/Http/Controllers/FollowController.php
> +        $followings = $user->followings()->orderBy('id','desc')->paginate(10);
これだと
user_id の降順となるため、
フォローした順にしたい場合は

created_at の desc とかにしたほうがいいかもしれないですね！

2023-05-04 14:42 UTC, yukihiroLaravel commented on app/Http/Controllers/FollowController.php
> +        $followers = $user->followers()->orderBy('id','desc')->paginate(10);
これだと
user_id の降順となるため、
フォローした順にしたい場合は

created_at の desc とかにしたほうがいいかもしれないですね！

2023-05-08 14:30 UTC, kenta327 commented on app/Http/Controllers/FollowController.php
> +        $followings = $user->followings()->orderBy('id','desc')->paginate(10);
フォローした降順で表示するように修正しました。

2023-05-08 14:31 UTC, kenta327 commented on app/Http/Controllers/FollowController.php
> +        $followers = $user->followers()->orderBy('id','desc')->paginate(10);
フォローした降順で表示するように修正しました。

2023-05-09 09:21 UTC, yukihiroLaravel approved these changes
OKです。問題ないのでマージします！
おつかれさまでした！！

2023-05-09 09:21 UTC, merged