#251 ユーザー周りフラッシュメッセージ（山田）
yukihiroLaravel/joint_develop pull request #252
Opened 2023-05-02 03:58 UTC by yamadaman-bs

## issue
- Closes #251 

## 概要
- フラッシュメッセージ（ユーザ登録/編集更新/削除）

## 動作確認手順
#251 
- UsersController,RegistersUsers
に追記
- welcome.blade、show.bladeに追記

## 考慮して欲しいこと
- 登録、削除に関して、
welcome.bladeには@if,@elseifで記述しています。
ご確認をお願いいたします。

## 確認して欲しいこと
- コントローラーの書き方は他に方法はありますでしょうか。
EX,
   ` return redirect('/')->with('flash_message', '投稿が完了しました');`

2023-05-02 08:24 UTC, Osk0830 requested changes
お疲れ様でした！
基本的な仕組みはできているようですね！

いくつか確認いただく必要がある箇所があるようです。
コメント残しておきましたので、よろしくお願いします！

2023-05-02 08:24 UTC, Osk0830 commented on app/Http/Controllers/Auth/RegisterController.php
> +use Illuminate\Http\Request;
- こちら追記されたようですが、どのような意図からでしたでしょうか？意図を把握できていないでの質問になってしまっていたらすみません！

2023-05-02 08:24 UTC, Osk0830 commented on resources/views/layouts/app.blade.php
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
- スタイルシートの読み込みは<head>内で行いましょう。
- 20行目は重複しているので不要そうですね。もし、slimではなくこちらが必要なようであれば、15行目の読み込みをやめ、この行を15行目に持っていきましょう。
- インデントが揃っていないので揃えてくださいね。

- ただ、全体をレビューしてみたところ、結局のところ、このライブラリは使ってないようですが、いかがでしょう？使っていないようでしたら削除してくださいね。

2023-05-02 08:24 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +
- こちらはテストで作ってみて使わなくなった感じですかね？それならば不要なコードは残さず削除しておいてくださいね。

2023-05-02 08:24 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +   </div>
- この部分は機能していないようですが、動作確認は済んでますでしょうか？

2023-05-02 13:16 UTC, yamadaman-bs commented on app/Http/Controllers/Auth/RegisterController.php
> +use Illuminate\Http\Request;
こちらは試作の段階で記述していたコードの削除忘れです。
失礼いたしました。
削除いたしました。

2023-05-02 13:21 UTC, yamadaman-bs commented on resources/views/auth/register.blade.php
> +
こちらは削除し忘れです。
大変失礼いたしました。
削除ずみです。

2023-05-02 13:26 UTC, yamadaman-bs commented on resources/views/welcome.blade.php
> +   </div>
私の環境下では動作確認済みです。
いかがでしょうか。
ご確認のほど、よろしくお願いいたします。

2023-05-02 13:29 UTC, yamadaman-bs commented on resources/views/layouts/app.blade.php
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
- 「スタイルシートの読み込みは内で行いましょう。」
　→こちらはheader内ということでよろしいでしょうか？
　であれば修正いたしましたのでご確認ください。
よろしくお願いいたします。

2023-05-02 13:30 UTC, yamadaman-bs commented on resources/views/layouts/app.blade.php
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
20行目は不要でしたので、インデント後に削除済みです。
よろしくお願いいたします。

2023-05-05 01:20 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKそうなので、マージしますね！
ラストスパート頑張っていきましょう！

2023-05-05 01:20 UTC, merged