ユーザ新規登録が完了時のフラッシュメッセージ
yukihiroLaravel/joint_develop pull request #256
Opened 2023-05-05 22:23 UTC by Hashimoto-Noriaki

# 概要
ユーザ編集画面・更新

動作確認手順
web.php変更
UsersControllerを変更
edit.blade作成い
UsersRequest 作成
config/app.php をenからjaに変更
validation.phpを日本語に翻訳

考慮して欲しいこと
不要なファイルなど削除した箇所が多いので少しごちゃごちゃしてしまっている感じがしました。

確認して欲しいこと
一旦は完成しました。
バリデーションはちゃんとかかっていましたが、念のためお願いします。
余分なコードなど混じっていないか確認お願いします。

2023-05-05 22:34 UTC, yukihiroLaravel requested changes
少し修正お願いします！

2023-05-05 22:34 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +@elseif (session('createUserMessage'))
successMessageと同じ内容だと思うので
createUserMessageは不要で
successMessageをそのまま使いましょう

2023-05-05 22:34 UTC, yukihiroLaravel commented on app/Http/Controllers/Auth/RegisterController.php
> +        session()->flash('createUserMessage','ユーザー登録が完了しました。');
successMessageと同じ内容だと思うので
createUserMessageは不要で
successMessageをそのまま使いましょう

2023-05-06 04:53 UTC, Hashimoto-Noriaki commented on app/Http/Controllers/Auth/RegisterController.php
> +        session()->flash('createUserMessage','ユーザー登録が完了しました。');
確認しました

2023-05-07 01:02 UTC, yukihiroLaravel approved these changes
OKです！
マージしました。お疲れ様でした✨

2023-05-07 01:03 UTC, merged