#10 ユーザログイン・ログアウト（ユウタ）
yukihiroLaravel/joint_develop pull request #26
Opened 2022-07-09 02:25 UTC by yuta2947

## issue
- closes #10 
## 概要
- ユーザログイン・ログアウトの実装

## 動作確認
- 下記のサンプルデータを元にログイン・ログアウトを実行
sample e-mail:       sample1@sample.com
sample password: sample1

- validationの動作確認を実行
メール、パスワードが空欄の場合のvalidationの動作確認

## 確認してほしい事
- validationの動作確認を別パターンもあれば確認お願いします。

2022-07-09 03:56 UTC, yukihiroLaravel requested changes
いくつかコメントしましたので、
お手数ですが修正願います☺️

2022-07-09 03:56 UTC, yukihiroLaravel commented on resources/views/layouts/app.blade.php
> +         @include('commons.error_messages')
下記写真のように、お手本アプリとエラーメッセージが出てくる位置が違うので
修正ください！

<img width="1396" alt="スクリーンショット 2022-07-09 12 45 51" src="https://user-images.githubusercontent.com/93365035/178090366-ca9f7b2b-4a3b-428f-bc94-139df2e46a30.png">

2022-07-09 03:56 UTC, yukihiroLaravel commented on resources/views/layouts/app.blade.php
> +    </ul>
この</ul>も不要ですよね？

2022-07-09 03:56 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('/', 'UsersController@index');
こちらは結果的に使われていないと思うので一旦削除してもらった方がいいかと思います！

2022-07-09 03:56 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +}
こちらのファイル全体は結果的に使われていないと思うので一旦削除してもらった方がいいかと思います！

2022-07-09 03:56 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="" class="nav-link">マイページ</a></li>
ログインしたら、お手本アプリのように
「マイページ」ではなく、ログインユーザの名前が表示されるようにしましょう！

2022-07-09 03:56 UTC, yukihiroLaravel commented on resources/views/Auth/login.blade.php
> +<div class="text-center">
こちらインデント１つ必要ですね！

2022-07-09 03:58 UTC, yukihiroLaravel requested changes

2022-07-09 03:58 UTC, yukihiroLaravel commented on resources/lang/ja/validation.php
> +        'numeric' => ':attributeは、:value以上でなければなりません。',
ここ、エラーある状態に戻しておかないといけなくないでしょうか？

2022-07-11 09:35 UTC, yuta2947 commented on resources/views/layouts/app.blade.php
> +         @include('commons.error_messages')
確認しました。修正します！

2022-07-11 09:35 UTC, yuta2947 commented on resources/views/layouts/app.blade.php
> +    </ul>
確認しました。修正します！

2022-07-11 09:36 UTC, yuta2947 commented on routes/web.php
> +Route::get('/', 'UsersController@index');
Route::get('/', 'UsersController@index');
こちらのコードを削除しますね！

2022-07-11 09:36 UTC, yuta2947 commented on app/Http/Controllers/UsersController.php
> +}
了解しました！

2022-07-11 09:37 UTC, yuta2947 commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="" class="nav-link">マイページ</a></li>
了解しました！

2022-07-11 09:37 UTC, yuta2947 commented on resources/views/Auth/login.blade.php
> +<div class="text-center">
了解しました！

2022-07-11 09:38 UTC, yuta2947 commented on resources/lang/ja/validation.php
> +        'numeric' => ':attributeは、:value以上でなければなりません。',
こちらのコード修正されたとのことですのでmergeしておきます！

2022-07-16 14:40 UTC, yukihiroLaravel approved these changes
close #26

2022-07-16 14:40 UTC, merged