検索機能実装
yukihiroLaravel/joint_develop pull request #285
Opened 2023-05-09 09:36 UTC by Hashimoto-Noriaki

# 概要
ユーザ編集画面・更新

# 動作確認手順
web.php変更
UsersControllerを変更
edit.blade作成

# 考慮して欲しいこと

# 確認して欲しいこと

2023-05-10 15:26 UTC, yukihiroLaravel requested changes
細かいところはレビューできていないのですが
ざっと見ておかしい部分はレビューしました！

一旦ご確認ください！

2023-05-10 15:26 UTC, yukihiroLaravel commented on app/Http/Controllers/PostController.php
> +        return view('welcome', compact('posts','search'));
他の部分では　compact 関数は使っていなかったかと思うので
通常通り配列の形で値を渡すようにしましょう！

2023-05-10 15:26 UTC, yukihiroLaravel commented on app/Http/Controllers/PostController.php
> +        $query->where('text', 'LIKE', "%{$search}%");
１つインデントが必要

2023-05-10 15:26 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +</div>
１つインデントが必要

2023-05-11 00:50 UTC, Hashimoto-Noriaki commented on resources/views/welcome.blade.php
> +</div>
確認しました

2023-05-11 00:50 UTC, Hashimoto-Noriaki commented on app/Http/Controllers/PostController.php
> +        $query->where('text', 'LIKE', "%{$search}%");
確認しました

2023-05-11 00:51 UTC, Hashimoto-Noriaki commented on app/Http/Controllers/PostController.php
> +        return view('welcome', compact('posts','search'));
確認しました

2023-05-11 14:23 UTC, yukihiroLaravel requested changes
修正お願いします！

2023-05-11 14:23 UTC, yukihiroLaravel commented on app/Http/Controllers/PostController.php
> +                $query->where('text', 'LIKE', "%{$search}%");
インデント

2023-05-11 14:23 UTC, yukihiroLaravel commented on app/Http/Controllers/PostController.php
> +        return view('welcome', ['posts' => $posts,'search' => $search]);
$posts, 'search'

2023-05-11 14:23 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('','PostController@index')->name('post.index');
消して、nameだけ１７行目につける

2023-05-11 14:23 UTC, yukihiroLaravel commented on routes/web.php
> +Route::post('/search', 'PostController@search')->name('post.search');
削除

2023-05-11 14:23 UTC, yukihiroLaravel requested changes
修正お願いします！

2023-05-12 02:51 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
お疲れ様でした！

2023-05-12 02:51 UTC, merged