youtube動画埋め込み（平林）
yukihiroLaravel/joint_develop pull request #286
Opened 2023-05-10 15:07 UTC by ka2ki1

## 概要
アプリ内へのyoutube動画埋め込み

## 確認してほしいこと
YouTubeの動画の配置はこちらでよろしいですか？

2023-05-10 15:34 UTC, yukihiroLaravel requested changes
コメントしました！

2023-05-10 15:34 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +    <iframe width="550" height="300" src="https://www.youtube.com/embed/Ex8fDyw_0Bk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyr
左側に動画がよっていて右側に文字があるのはなんか違和感がありますね、、、。
上に文字、下に動画の方がいいと思いますし、野球ボールと動画の間もぴったりしすぎていて変な感じがします。
あと、僕に見せる前に他メンバーの意見も聞きましょう！
<img width="1167" alt="スクリーンショット 2023-05-11 0 30 29" src="https://github.com/yukihiroLaravel/joint_develop/assets/93365035/456a4e64-8921-46d3-b6d0-8650218e748d">

あと、これはできたらですが
スマホサイズで見ると、文字がつぶれてこんな感じになってしまうので
きれば避けたいところです。。。
<img width="453" alt="スクリーンショット 2023-05-11 0 30 15" src="https://github.com/yukihiroLaravel/joint_develop/assets/93365035/75a297c0-505f-41cf-bdd8-b22938e7338e">

2023-05-14 21:46 UTC, ka2ki1 commented on resources/views/welcome.blade.php
> +    <iframe width="550" height="300" src="https://www.youtube.com/embed/Ex8fDyw_0Bk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyr
対応しました

2023-05-15 00:39 UTC, yukihiroLaravel approved these changes
OKなのでマージしました✨
おつかれさまでした！

2023-05-15 02:54 UTC, merged