#14 ユーザ編集画面・更新（かねこなおき）
yukihiroLaravel/joint_develop pull request #29
Opened 2022-07-25 14:47 UTC by Kaneko0000

## issue 
- Close #14

## 概要
- ユーザ編集画面

## 動作確認手順
- localhost:8080 で、メアド「sample1@sample.com」パスワード「sample111」でログイン後、
- localhost:8080/users/1/ edit　にアクセスし更新画面で、右上のheader部分にユーザ名が出ることを確認。
そこで、それぞれのフォームで変更の確認をお願いします。

id=1だけは
ユーザ名「sample1」
メールアドレス「sample1@sample.com」
パスワード「sample111」
としています。
他はシーダーファイルにある通りです。

- ユーザとメールアドレスは、Adminerでuserテーブル変更されていることを確認。
- パスワードの確認はログアウト後、再度ログインできるか入力して確認をお願いします。
- それぞれのバリデーションメッセージ（空欄、重複、パスワードが一致しない）も確認お願いします。

## 考慮してほしいこと
- 画面の作成だけで、「退会する」ボタンの機能は実装していません。
- 実際のアプリは更新ボタンで、ユーザ詳細画面に移りますが、まだ実装されていないため編集画面のままにしています。

## 確認してほしいこと
-特にありません。

2022-07-28 02:03 UTC, Osk0830 requested changes
お疲れ様です！
私用でバタついていたためにレビューが遅くなり申し訳ありません。。

この間の学習成果がしっかりと反映されていて素晴らしいですね！

いくつかコメントしましたので、確認よろしくお願いします。

2022-07-28 02:03 UTC, Osk0830 commented on app/Http/Requests/EditRequest.php
> +class EditRequest extends FormRequest
こちら、せきさんもSlackでおっしゃってましたが、命名の形式があまり好ましくないように思われます。
バリデーション用のフォームリクエストは、例えば、ユーザーに関するものや投稿にかんするものなど、都度別々に作る必要がありますが、`EditRequest`のようにしてしまうと、「何に関する情報をチェックするためのものなのか」が伝わらないばかりか、「編集」なら色々な対象を編集する可能性もあるため、名前が被らざるを得なくなります。
一方で、ユーザーの新規登録は、Laravelでデフォルトで用意されているものを使うため、あまり俎上に乗りませんが、例えば、独自に作る「投稿」関連のものの場合、新規投稿と編集で同じフォームリクエストを使うことも多くあります。
以上のような内容を検討され、どのような命名がわかりやすいか、一度検討してみてくださいね。

2022-07-28 02:03 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +    public function update(EditRequest $request, $id)
フォームリクエストの名前を変更した際は、こちら2箇所も忘れずに変更してくださいね。

2022-07-28 02:03 UTC, Osk0830 commented on app/Http/Requests/EditRequest.php
> +    }
この辺は、
resources/lang/ja/validation.php
で既に指定されているものと同じ内容である部分は、
特に記載し上書きしなくても大丈夫なので、
照合後、重複する内容は削除してしまいましょう。

2022-07-28 02:03 UTC, Osk0830 commented on resources/views/users/edit.blade.php
> +                </div>
パスワードに関しては、`old()`は不要ではないでしょうか？

2022-07-28 02:03 UTC, Osk0830 commented on routes/web.php
> +Route::get('logout', 'Auth\LoginController@logout')->name('logout');
ログアウトは金子さんのご担当でしたでしょうか？

2022-07-28 02:49 UTC, Kaneko0000 commented on app/Http/Requests/EditRequest.php
> +class EditRequest extends FormRequest
Laravel応用のフォームリクエストの名前の付け方から、アッパーキャメルで命名します。
そしてそのままですが
ユーザ編集のフォームリクエストなので、UserEditRequest.phpとします。

2022-07-28 02:49 UTC, Kaneko0000 commented on app/Http/Controllers/UsersController.php
> +    public function update(EditRequest $request, $id)
わかりました。

2022-07-28 03:56 UTC, Kaneko0000 commented on app/Http/Requests/EditRequest.php
> +    }
resources/lang/ja/validation.phpは、僕が作成したのに、わかりませんでした。

一つずつ確認して行ったところ、attributes、messages、全て消して機能しました。

2022-07-28 03:57 UTC, Kaneko0000 commented on resources/views/users/edit.blade.php
> +                </div>
そうでした。
消して確認したところ、不要だったことが確認できました。

2022-07-28 03:59 UTC, Kaneko0000 commented on routes/web.php
> +Route::get('logout', 'Auth\LoginController@logout')->name('logout');
ログアウトは僕の担当ではありません。
僕がもしかしたら改行したりしたことで、このように出たんでしょうか？

2022-07-29 05:12 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらマージしますね！

2022-07-29 05:12 UTC, merged