#260 posts（投稿）テーブルのマイグレーションとシーダー作成(三田村)
yukihiroLaravel/joint_develop pull request #297
Opened 2023-05-16 21:47 UTC by Mita-N4306

## issue
- Close #260
## 概要
- posts（投稿）テーブルのマイグレーションとシーダー作成
## 動作確認手順
 php artisan migrate --seed
- 上記のコマンドを実行する
- Adminerでposts(投稿)テーブルに３つのレコードが保存されているか確認
## 考慮してほしい事
- 状況に応じて、下記コマンドで動作確認をする必要あり。  
   php artisan migrate:fresh --seed
## 確認してほしい事
- 作成したカラムの内容・種類がコメント投稿機能として正しく行えるか
- 外部キー制約が正しく機能するか

2023-05-17 03:59 UTC, Osk0830 requested changes
お疲れ様でした！
初回プルリクまで色々とややこしい過程もあったかと思いますが、まずはワンステップクリアされて素晴らしいですね！
内容も概ね問題なく書けていると思います！

いくつかコメントしましたので、確認よろしくお願いします！

2023-05-17 03:59 UTC, Osk0830 commented on database/migrations/2023_05_14_233013_create_posts_table.php
> +            $table->string('comment_content');
- カラム名をあまり長くしてしまうとコードの入力時に面倒なので、必然的な理由がない限りはもう少しスマートにした方が良いと思います。ここの場合は、「投稿の本文」にあたるので、`content`あたりで良さそうですね。

2023-05-17 03:59 UTC, Osk0830 commented on database/migrations/2023_05_14_233013_create_posts_table.php
> +            $table->string('user_name');
- ユーザーの情報（名前など）は、すべて外部キーで紐づいている`users`テーブルで管理されていて、利用する際もそこから取り出します。そのために、`user_id`というカラムで`users`テーブルの`id`情報を保持することになります。ですので、それ以外のユーザー情報に関するカラムは、`posts`テーブルの方には不要になります。

2023-05-17 03:59 UTC, Osk0830 commented on database/migrations/2023_05_14_233013_create_posts_table.php
> +            $table->softDeletes();
- 22行目の記述は、「論理削除」という機能を実現させるのに必要な記述ですが、Postにこの機能を実現しようとすると色々とややこしくなってくるのと、今回のアプリではひとまず「物理削除」でOKですので、一旦22行目は削除しておきましょう。

2023-05-17 03:59 UTC, Osk0830 commented on database/migrations/2023_05_14_233013_create_posts_table.php
> +    }
- 外部キー制約の記述は問題ないですよ！ただ、24行目のうしろの`});`の位置がここだと見にくいので、次の行に来るようにしてください。その際インデントも注意してくださいね！

2023-05-17 03:59 UTC, Osk0830 commented on database/seeds/PostsTableSeeder.php
> +    }
- マイグレーションファイルを修正したら、それに応じてこちらも修正してくださいね。

2023-05-17 22:17 UTC, Mita-N4306 commented on database/seeds/PostsTableSeeder.php
> +    }
内容修正しましたので、よろしくお願いいたします。

2023-05-18 00:33 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらしっかり修正できているのでマージしますね！
引き続き頑張っていきましょう！

2023-05-18 00:33 UTC, merged