#12　トップページの投稿表示（ゆうた）
yukihiroLaravel/joint_develop pull request #30
Opened 2022-07-30 01:22 UTC by yuta2947

## issue 
-closes #12 

## 概要
- トップページに投稿を表示させる

## 動作確認
- トップページにアクセスし動作確認を実施

- pagenationでページ送りを実装
プレビューでページ送りを実施

## 考慮してほしいこと
-テキストのフォントサイズ、レイアウトが若干見本と違うため確認お願いします。

2022-08-01 06:40 UTC, yukihiroLaravel requested changes
いくつか指摘しましたが、全体的に綺麗に実装できていると思います！☺️

次は指摘した細かい点に配慮しながら実装できるとよりいいですね✨
お手数ですが修正願います！

2022-08-01 06:40 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +
ここの謎の空行は不要なので消しましょう！

2022-08-01 06:40 UTC, yukihiroLaravel commented on app/Post.php
> +
ここの空行は不要なので消しましょう！

2022-08-01 06:40 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +            'user_id' => 1,
ここに不要な空白が追加されているので消しましょう！

2022-08-01 06:40 UTC, yukihiroLaravel commented on app/Post.php
> +    public function user ()
user() で良いと思います！
user () とスペースを開けなくてOKです！

2022-08-01 06:40 UTC, yukihiroLaravel commented on resources/views/posts/create_posts.blade.php
> +        </li>
インデントが１つ（スペース４つ分）不要ですね！

2022-08-01 06:40 UTC, yukihiroLaravel commented on resources/views/posts/post.blade.php
> +        @endforeach
インデントが変になってますね汗

2022-08-01 06:40 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +
謎の空行３行は消しましょう！

2022-08-01 06:40 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('/', 'PostsController@index');
このルーティングができたら、もっと上に書いてある
下記部分は不要となるので消しましょう☺️

```
Route::get('/', function () {
    return view('welcome');
});
```

2022-08-01 06:40 UTC, yukihiroLaravel commented on resources/views/posts/create_posts.blade.php
> +        </li>
あと、このファイルって次のタスクで使うファイルなので
このブランチには本来ない方がいいので、
消せれば消しましょう！

（そのままこのブランチに入れてマージしてしまっても、悪くはないかなと思います！）

2022-08-01 07:00 UTC, yuta2947 commented on resources/views/posts/create_posts.blade.php
> +        </li>
create_post_blade.phpファイルを削除しました。次タスクにて新たに作成します！

2022-08-01 07:00 UTC, yuta2947 commented on app/Post.php
> +    public function user ()
9行目のuserの後ろのスペース削除しました！

2022-08-01 07:00 UTC, yuta2947 commented on database/seeds/PostsTableSeeder.php
> +            'user_id' => 1,
１６行目の文末のスペース削除しました！

2022-08-01 07:00 UTC, yuta2947 commented on app/Post.php
> +
１２行目の空白削除しました！

2022-08-01 07:00 UTC, yuta2947 commented on app/Http/Controllers/PostsController.php
> +
17行目の空白削除しました！

2022-08-02 09:33 UTC, yukihiroLaravel requested changes
2点コメントした点が変更できていなかったので
変更願います🙇‍♂️

2022-08-02 09:33 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +
ここが変わっていないですね！削除願います！

2022-08-02 09:33 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('/', 'PostsController@index');
ここが変わっていないですね！
削除願います！

2022-08-04 14:36 UTC, yukihiroLaravel approved these changes
一部変な点はありますが、いったんマージします

2022-08-04 14:36 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +    public function index()
ココのズレ

2022-08-04 14:36 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> -            <h1><i class="fab fa-telegram fa-lg pr-3"></i>Topic Posts</h1>
jumbotron-extend 
と
<i class="fab fa-telegram fa-lg pr-3"></i>

2022-08-04 14:36 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> -            <h1><i class="fab fa-telegram fa-lg pr-3"></i>Topic Posts</h1>
class="fab fa-telegram fa-lg pr-3"></i>

2022-08-04 14:36 UTC, yukihiroLaravel commented on routes/web.php
> +| routes are loaded by the RouteServiceProvider within a group whichß
ß

2022-08-04 14:36 UTC, merged

2022-08-04 15:24 UTC, yuta2947 commented on routes/web.php
> +| routes are loaded by the RouteServiceProvider within a group whichß
βを削除しました。

2022-08-04 15:24 UTC, yuta2947 commented on resources/views/welcome.blade.php
> -            <h1><i class="fab fa-telegram fa-lg pr-3"></i>Topic Posts</h1>
該当のコードを追加しました。

2022-08-04 15:24 UTC, yuta2947 commented on app/Http/Controllers/PostsController.php
> +    public function index()
修正ブランチを作成してから修正しました。