#270 トップページの投稿表示（おおた）
yukihiroLaravel/joint_develop pull request #300
Opened 2023-05-18 07:04 UTC by u0222

## issue
- Closes #270

## 概要
- #270 トップページの投稿表示

## 動作確認手順
- 表示順が投稿日時の降順になっているか
- 10件ごとでページ繰りがされているか
- アイコン／ユーザー名／投稿文章／投稿日時が表示されているか
- レイアウトが崩れていないか。

## 考慮して欲しいこと
- 特になし

## 確認してほしいこと
- PostsControllerの下記箇所について、('created_at', 'desc')の記載でよかったでしょうか？laravel備え付けの関数（'id','desc'）をいじったのですが、応用講座で出てこないやり方なので不安です。

```
        $posts = Post::orderBy('created_at', 'desc')->paginate(10);
        return view('welcome', [
            'posts' => $posts,
        ]);
```

2023-05-19 01:09 UTC, Osk0830 requested changes
お疲れ様でした！
実装的には全く問題なく、非常によく書けていると思います！

少し細かい内容になり恐縮ですが、インデントの問題で一点だけコメントしましたので、確認よろしくお願いします！

また、OSの隠しファイルである、`.DS_Store`というファイルが作業ファイルに含まれて上がるようになってしまっているので、できれば `.gitignore`に含めて、git管理対象外にし、作業ファイルに含まれないようにしていただけるといいと思います！

[![Image from Gyazo](https://i.gyazo.com/b220f84ad5b0c96bd87c82df3e295e76.png)](https://gyazo.com/b220f84ad5b0c96bd87c82df3e295e76)

2023-05-19 01:09 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +    @endforeach
- 見やすさの問題ですが、Bladeのテンプレート（例：@foreach ... @endforeach など）とその中に含まれる要素も、実質的には入れ子関係にあるので、中に含まれる要素のインデントは一つ下げた方がいいですね。@if ... @endif とその中身も同様な感じです。

2023-05-19 02:46 UTC, u0222 commented on resources/views/posts/posts.blade.php
> +    @endforeach
ご確認ありがとうございます。インデント修正と、gitignoreに.DS_Storeを含めました。

2023-05-20 02:09 UTC, Osk0830 approved these changes
こちら諸々お疲れ様でした！
問題ないのでマージしますね！
引き続き頑張っていきましょう！

2023-05-20 02:09 UTC, merged