#281 ユーザー新規登録(ユウキ)
yukihiroLaravel/joint_develop pull request #306
Opened 2023-05-20 16:10 UTC by ykoh1119

## issue
- Closes #281 

## 概要
- ユーザ新規登録

## 動作確認手順  
- トップページのヘッダーから「新規ユーザー登録」をクリック。新規ユーザー登録画面に遷移することを確認
- 名前・メールアドレス・パスワードに不適切なもの(RegisterController.phpのValidatorに記載の条件に合わないもの)を入力し、新規登録ボタンをクリック。バリデーションが効いているかを確認(エラー文が表示されること)
- 名前・メールアドレス・パスワードに適切なものを入力し、新規登録ボタンをクリック。トップページに遷移すること(作成したユーザーでログインされていないこと)
- Adminerでusersテーブルに作成したユーザーが登録されていることを確認
- ログインページから作成したユーザー情報を用いてログインを実行。ログインできることを確認
- ログインページに記載の「新規ユーザー登録する？」をクリック。新規ユーザー登録画面に遷移することを確認

## 考慮して欲しいこと
- `docker exec -it laravel_app bash` でコンテナに入り、laravelappディレクトリで`composer dump-autoload`を実行する必要がある

## 確認して欲しいこと
- ユーザー新規登録をした際に自動でログインされてしまうのを解消するために、RegisterControllerクラス内で呼び出している`RegistersUsers(vendor\laravel\framework\src\Illuminate\Foundation\Auth\RegistersUsers.php)`で記載されている`$this->guard()->login($user);`をコメントアウトしようとしたのですが、ネットで調べるとvendor配下は修正すべきではないという情報があったため、そのページに基づき上書きするためのファイル(`app\Vendor\laravel\framework\src\Illuminate\Foundation\Auth\RegistersUsers.php`)を作成して、composer.jsonを修正してそちらを読み込ませるようにしてあります。

上記の方法で問題ないかという点と、上書きするにしても作成するファイルの場所などに適した場所などがありましたら教えていただけると幸いです。

2023-05-21 12:56 UTC, Osk0830 requested changes
お疲れ様でした！
とても良くできていると思います！素晴らしいです！

少しだけコメントしましたので、確認よろしくお願いします！

2023-05-21 12:56 UTC, Osk0830 commented on resources/views/auth/login.blade.php
> +            <div class="mt-2"><a href="signup">新規ユーザ登録する？</a></div>
- この方法でリンク先を指定するのももちろんありですが、URIに変更があった際などにあちこち変更する必要が出てくる可能性があります。ですので、基本はルーティングで名付けた名前を利用する方式を用いるようにしましょう。

2023-05-21 12:56 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +                    <input id="password_confirmation" type="password" class="form-control" name="password_confirmation" value="">
- 今回の実装通り、パスワードはバリデーションで弾かれた際に既存の情報を保持する必要はありませんね。なので、`value=""`自体不要ということなので、消してしまっても良さそうですね。

2023-05-21 12:56 UTC, Osk0830 commented on resources/views/layouts/app.blade.php
> +            @include('commons.error_messages')
- エラーメッセージは、共通レイアウト実装時に、ページごとにメッセージを表示する位置が変わってくることを考慮して、あえてここに入れていないと思います。新規登録のバリデーションメッセージが表示されるべき位置を確認し、そこに移動しましょう。

2023-05-21 12:56 UTC, Osk0830 commented on app/Http/Controllers/Auth/RegisterController.php
> +    protected $redirectTo = '/';
- これも間違ってはいませんが、変更箇所が多くならないよう、`RouteServiceProvider::HOME`自体を変更するのがよくないでしょうか？

2023-05-21 12:56 UTC, Osk0830 commented on app/Http/Middleware/RedirectIfAuthenticated.php
> +            return redirect('/');
- こちら、前述の通りです。

2023-05-21 14:02 UTC, ykoh1119 commented on resources/views/auth/login.blade.php
> +            <div class="mt-2"><a href="signup">新規ユーザ登録する？</a></div>
ご指摘ありがとうございます。
修正いたしました。

2023-05-21 14:02 UTC, ykoh1119 commented on resources/views/auth/register.blade.php
> +                    <input id="password_confirmation" type="password" class="form-control" name="password_confirmation" value="">
ご指摘ありがとうございます。
削除いたしました。

2023-05-21 14:02 UTC, ykoh1119 commented on resources/views/layouts/app.blade.php
> +            @include('commons.error_messages')
すみません。確認不足でした。
修正いたしました。

2023-05-21 14:02 UTC, ykoh1119 commented on app/Http/Controllers/Auth/RegisterController.php
> +    protected $redirectTo = '/';
仰る通りだと思いますので、修正を戻して、`RouteServiceProvider.php`の`HOME`を修正いたしました。

2023-05-21 23:56 UTC, Osk0830 requested changes
お疲れ様でした！
ほぼ問題なく修正できていると思います！

一箇所だけおかしな部分がありコメントしましたので、確認よろしくお願いします！

2023-05-21 23:56 UTC, Osk0830 commented on app/Http/Middleware/RedirectIfAuthenticated.php
> +            return $redirectTo = RouteServiceProvider::HOME;
- こちら、`return`する内容の記述がおかしいようです。ここは、ログインしている状態ではアクセスできないページに行こうとした場合に働く部分ですね。試しに、ログインしている状態で`/login`にアクセスするなどするとここが走ると思いますが、下記のようにエラーが出ます。元の記述を参考に修正し、動作確認してみてくださいね。

　https://gyazo.com/d618d53189083046d2e50a8f2ca92081

2023-05-22 00:37 UTC, ykoh1119 commented on app/Http/Middleware/RedirectIfAuthenticated.php
> +            return $redirectTo = RouteServiceProvider::HOME;
大変申し訳ありません。
修正して教えていただいた方法で動作確認を行い、トップページに遷移することを確認しました。

2023-05-22 01:53 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらしっかり修正できているのでマージしますね！
引き続き頑張っていきましょう！

2023-05-22 01:53 UTC, merged