#17 投稿編集・更新（かねこなおき）
yukihiroLaravel/joint_develop pull request #31
Opened 2022-07-30 03:26 UTC by Kaneko0000

## issue 
- Close #17

## 概要
- 投稿編集画面・更新

## 動作確認手順
- 下記コマンドを実行
localhost:8080でログイン後
localhost:8080/posts/1/edit　（投稿編集画面）にアクセス
フォーム欄に適当な文字入力後更新　→　トップ画面に戻ることを確認
localhost:8088にアクセス。
postsテーブルのデータに入力したものがあることを確認。
空欄で更新してバリデーションメッセージが出る。ことを確認。

## 考慮してほしいこと
特にありません。

## 確認してほしいこと
特にありません。

2022-08-02 15:07 UTC, Osk0830 requested changes
お疲れ様です。
遅くなってすみません。
いくつかコメントしましたので、ご確認いただければと思います。

2022-08-02 15:07 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        $post = Post::findOrFail($id);
投稿の編集用ページの表示なので、ログイン中のユーザが投稿を投稿した本人である場合のみページを表示できるようにして、そうでない場合はこのページを表示できないようにしたいところですね。

2022-08-02 15:07 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +    {
投稿の新規作成用のフォームリクエストはどうなっているのか確認し、内容的に同じであれば一つに統合するのも検討できるかもしれませんね。内容的に違うものにしなければならない場合は、なぜ違わなければならないのか考えてみるのも面白いかもしれませんね。

2022-08-02 15:07 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        $post->save();
ここも、編集ページ表示時同様、投稿者本人かどうかをチェックする処理を挟むのが良さそうですね。

2022-08-02 15:07 UTC, Osk0830 commented on resources/views/posts/edit.blade.php
> +      <form method="POST" action="{{ route('posts.update', $user->id) }}">
投稿の更新なのに、パラメータとして送る情報はユーザーのIDというのは、あってますでしょうか？

2022-08-02 15:07 UTC, Osk0830 commented on resources/views/posts/edit.blade.php
> +          </div>
動きに直接的な影響はなさそうですが、投稿内容を表示する箇所で、id属性をuser_idとしているのはなぜでしょうか？

2022-08-03 13:36 UTC, Kaneko0000 commented on app/Http/Controllers/PostsController.php
> +    {
投稿の新規作成のタスクはまだ実装されてなくても、laravelのフレームワークにフォームリクエストは実在するんでしょうか？

2022-08-03 13:37 UTC, Kaneko0000 commented on resources/views/posts/edit.blade.php
> +      <form method="POST" action="{{ route('posts.update', $user->id) }}">
$user->id　から　$post->id　に訂正しました。

2022-08-03 13:44 UTC, Kaneko0000 commented on resources/views/posts/edit.blade.php
> +          </div>
そうですね。id="content"としました。

2022-08-06 01:43 UTC, Kaneko0000 commented on app/Http/Controllers/PostsController.php
> +        $post = Post::findOrFail($id);
ifの中に下の記述していた、viewを入れることで解決しました。

2022-08-06 01:43 UTC, Kaneko0000 commented on app/Http/Controllers/PostsController.php
> +    {
投稿の新規投稿作成者のユウタさんにはその旨伝えました、使うということなので、作成したままにしておきます。

2022-08-06 01:44 UTC, Kaneko0000 commented on app/Http/Controllers/PostsController.php
> +        $post->save();
これもif分でチェックするコードを記述することで解決しました。

2022-08-08 05:27 UTC, Osk0830 requested changes
お疲れ様です。
レビューしましたので、2点だけ確認お願いします。

2022-08-08 05:27 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +            return redirect('User::findOrFail($id');
僕の勘違いかもしれないですが、こちら、$idのdの後に、閉じカッコ ) は不要でしたでしょうか？

2022-08-08 05:27 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        return back();
この部分は不要ではないでしょうか？

2022-08-08 05:27 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +    {
了解です。

2022-08-08 06:07 UTC, Kaneko0000 commented on app/Http/Controllers/PostsController.php
> +            return redirect('User::findOrFail($id');
return redirect('User::findOrFail($id)');
と、書き換えました。

2022-08-08 06:07 UTC, Kaneko0000 commented on app/Http/Controllers/PostsController.php
> +        return back();
不要と考え消去しました。

2022-08-08 09:13 UTC, Osk0830 approved these changes
こちらマージしますね！

2022-08-08 09:13 UTC, merged