ユーザ詳細ページ(postテーブル除く部分)実装（あめみや）
yukihiroLaravel/joint_develop pull request #315
Opened 2023-05-24 08:35 UTC by Tomoki-Amemiya

## issue
- Close #314

## 概要
- ユーザ詳細ページ(postテーブル除く部分)実装

## 動作確認手順
- 下記URLページへアクセス
http://localhost:8080/users/1

## 考慮してほしいこと
- postテーブルが未実装
post系のコードはコメントアウトや、コード未調整の状態となっております。
ユーザ詳細ページ内のタイムラインも何も表示されていない状態です。

## 確認してほしいこと
- ユーザ情報編集リンクについて
今後実装予定のユーザー情報編集リンクの下記コードを残したままにしております。
`<a href="" class="btn btn-primary btn-block">ユーザ情報の編集</a>`
今後実装予定なので、ここにコードをかくとわかりやすいかと思い残しておりますが、消しておくべきでしたでしょうか。

- post系のコードについて
コメントアウトなどせず、全て消した状態の方がよろしかったでしょうか。

- postテーブル実装後の対応について
方法については下記２点があるかと思います。
①postテーブルが実装された後に、またこちらのブランチを再度編集し、再プルリクエストをするのでしょうか。
その場合、マージはpostテーブル実装後の全てが完成されたタイミングでしょうか。
または、
②こちらの「ユーザ詳細」はプルリクエストが終わればマージされ、新たに「ユーザ詳細タイムライン」というissueを新規作成し、postテーブル実装後に別タスク「ユーザ詳細タイムライン」として行うべきでしょうか。
その場合は、現在プルリクエストしているものは先にマージされて、別タスクを後日行うこととなると思うのですが、
そうすると、コメントアウトだらけのコードは何かと問題があるかとも思います。

2023-05-24 12:32 UTC, Tomoki-Amemiya commented
## issue
- Close #314

## 概要
- 指摘箇所の修正

## 動作確認手順
- 下記URLページへアクセス
http://localhost:8080/users/1

## 考慮してほしいこと
- 特になし

## 確認してほしいこと
- post系のコードをpost系実装時に再編集しやすくコメントアウトし直しました。

2023-05-24 14:39 UTC, yukihiroLaravel requested changes
お願いします

2023-05-24 14:39 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('/', 'UsersController@index');
上とかぶっているので不要

2023-05-24 15:30 UTC, Tomoki-Amemiya commented
## issue
- Close #314

## 概要
- 指摘箇所の再修正

## 動作確認手順
- 下記URLページへアクセス
http://localhost:8080/users/1

## 考慮してほしいこと
- 特になし

## 確認してほしいこと
- web.phpの同じ内容のコードを削除いたしました。
何度も指摘させてしまい申し訳ありませんでした。
- それぞれのコメントアウト文章が簡潔ではなかったため、一行にまとめました。
- $countPostsの数字がshow.blade.phpにて表示するようにしました。
下記コードを用いて、数字が表示するようにしておきました。
`{{ $countPosts }}`

2023-05-25 06:06 UTC, Tomoki-Amemiya commented
## issue
- Close #314

## 概要
- 指摘箇所の再々修正

## 動作確認手順
- 下記URLページへアクセス
http://localhost:8080/users/1

## 考慮してほしいこと
- 特になし

## 確認してほしいこと
- カウント系コードの削除
投稿を10件表示しページを切り替えるためpaginateを使うかと思うのですが、
paginateを使うにはuserCountsなどのカウント系のコードが必要なのかと勘違いしておりました。
カウント系のコードを全て削除し、ページも問題なく表示されておりますのでよろしくお願いいたします。

2023-05-25 06:10 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした！

2023-05-25 06:11 UTC, merged