#319 ユーザ編集画面・更新（Ninomiya）
yukihiroLaravel/joint_develop pull request #320
Opened 2023-05-24 22:38 UTC by yuki-yuki1

## issue
- Close #319

## 概要
- ユーザー編集画面の作成、編集機能の実装

## 動作環境手順
ログイン状態でトップページの中心に配置してある「ユーザー情報の編集」をクリック。
※ユーザー詳細ページがまだないため、トップページに仮でボタンをセットしています。
ユーザ名、メールアドレス、パスワードを入力し、ユーザー情報を変更する。
「更新する」ボタンをクリックすると、情報が更新され、トップページへ戻る。

## 考慮してほしいこと
※ユーザー詳細ページがまだないため、トップページに仮でボタンをセットしています。

## 確認してほしいこと
ユーザー情報編集で
・ユーザー名のみ、メールアドレスのみ、ユーザー名とアドレス、全ての情報の変更などの各パターンで更新できること。
※下記UserRquestの
```
public function rules()
    {
        return [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', Rule::unique('users')->ignore($this->user())],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ];
    }
```
`Rule::unique('users')->ignore($this->user()`が問題なく実行されていること。
・更新後、ヘッダー右上のユーザー名が更新したものに切り替わる事
・EditUserControllerで
```
public function update(UserRequest $request, $id)
    {
        $user = \Auth::user();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->save();
        return view('welcome');
    }
```
と記載しておりますが、最初の行を`$user = User::findOrFail($id);`として、ユーザー情報の更新をかけた場合、
情報の更新はできるのですが、ヘッダー右上のユーザー名が切り替わりません(再読み込みすると切り替わります)。
最初の行を`$user = User::findOrFail($id);`とした時の正しい記述方法を教えていただけると幸いです。

2023-05-25 05:59 UTC, yukihiroLaravel requested changes

2023-05-25 05:59 UTC, yukihiroLaravel commented on app/Http/Controllers/EditUserController.php
> +        return view('users.edit',['user' => $user]);
if () {
     return view('users.edit',['user' => $user]);
}
abort(404);

2023-05-25 05:59 UTC, yukihiroLaravel commented on app/Http/Controllers/EditUserController.php
> +        return view('welcome');
PRGパターン
POST
Redirect
Get

2023-05-25 05:59 UTC, yukihiroLaravel commented on app/Http/Controllers/EditUserController.php
> +        return view('welcome');
return redirect();

2023-05-26 14:19 UTC, yuki-yuki1 commented on app/Http/Controllers/EditUserController.php
> +        return view('users.edit',['user' => $user]);
if文を使用したコードへ修正しました。

2023-05-26 14:19 UTC, yuki-yuki1 commented on app/Http/Controllers/EditUserController.php
> +        return view('welcome');
redirectへ変更、修正しました。

2023-05-27 09:48 UTC, yukihiroLaravel approved these changes
OKです！
完璧ですのでマージしました！

2023-05-28 01:55 UTC, yukihiroLaravel approved these changes
OKですのでマージしました！
質問についても回答しました！

2023-05-28 01:55 UTC, merged