投稿新規作成(postテーブル除く部分)（あめみや）
yukihiroLaravel/joint_develop pull request #324
Opened 2023-05-26 14:20 UTC by Tomoki-Amemiya

## issue
- Close #316

## 概要
- 投稿新規作成の実装

## 動作確認手順
- 下記コマンドを実行
php artisan migrate
- ユーザーでログイン後トップページの投稿フォームから送信
http://localhost:8080/
にアクセス→右上のログインよりページ移動→ユーザーでログイン
その後、トップページにて投稿
postテーブルに値が問題なく入っているかどうか

## 考慮してほしいこと
- postテーブルが無かったため、仮実装です。
- 状況に応じて、下記コマンドで動作確認をする必要あり。
php artisan migrate:fresh --seed

## 確認してほしいこと
- 投稿フォームがログイン時のみ表示されているか
- 投稿フォームのバリデーションに問題はないか

2023-05-27 09:58 UTC, yukihiroLaravel requested changes
宜しくお願いします！

2023-05-27 09:58 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $post->user_id = $request->user()->id;
ここに書く

2023-05-27 09:58 UTC, yukihiroLaravel commented on database/migrations/2023_05_26_221942_create_posts_table.php
> +            $table->string('text')->nullable();
nullableは不要

2023-05-27 09:58 UTC, yukihiroLaravel commented on resources/views/commons/new_post.blade.php
> +</div>
インデント

2023-05-27 11:39 UTC, Tomoki-Amemiya commented
## issue
- Close #316

## 概要
- 指摘箇所の修正

## 動作確認手順
（前回と同文）
- 下記コマンドを実行
php artisan migrate
- ユーザーでログイン後トップページの投稿フォームから送信
http://localhost:8080/
にアクセス→右上のログインよりページ移動→ユーザーでログイン
その後、トップページにて投稿
postテーブルに値が問題なく入っているかどうか

## 考慮してほしいこと
（前回と同文）
- postテーブルが無かったため、仮実装です。
- 状況に応じて、下記コマンドで動作確認をする必要あり。
php artisan migrate:fresh --seed

## 確認してほしいこと
- PostsController.phpのコメント位置修正
- create_posts_table.phpのnullable削除
- new_post.blade.phpのインデント調整

2023-05-28 07:39 UTC, Tomoki-Amemiya commented
## issue
- Close #323

## 概要
- 追加でpostテーブル＆シーダーの実装

## 動作確認手順
- 下記コマンドを実行
php artisan db:seed --class=PostsTableSeeder
- Adminerでpostsテーブルに11個のレコードが保存されていることを確認

## 考慮してほしいこと
- 状況に応じて、下記コマンドで動作確認をする必要あり。
php artisan migrate:fresh --seed
- 投稿表示については未実装
トップページなど投稿の表示はされませんのでデータベースのみでの確認です。

## 確認してほしいこと
-  特になし

2023-05-28 09:06 UTC, yukihiroLaravel requested changes
１点だけコメントしました。
お願いします！

2023-05-28 09:06 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +            'user_id' => '1',
こちらの以下すべて、文字列の数字ではなく、単なる数字で良いと思います！

2023-05-28 10:29 UTC, Tomoki-Amemiya commented
## issue
- Close #323

## 概要
- PostsTableSeederの修正
user_idの中身を文字列から数値に修正しました。

## 動作確認手順
- 下記コマンドを実行
php artisan migrate --seed
- Adminerでpostsテーブルに11個のレコードが保存されていることを確認

## 考慮してほしいこと
- 状況に応じて、下記コマンドで動作確認をする必要あり。
php artisan migrate:fresh --seed

## 確認してほしいこと
- 特になし

2023-05-28 15:14 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした！！

2023-05-28 15:14 UTC, merged