#328 ユーザ退会（Ninomiya）
yukihiroLaravel/joint_develop pull request #330
Opened 2023-05-28 12:21 UTC by yuki-yuki1

## issue
- Close #328 

## 動作環境手順
ログイン状態で「ユーザ詳細ページ」の「ユーザ情報の編集」ボタンをクリック。
「ユーザ編集ページ」左下の「退会する」ボタンをクリック。ポップアップが表示されるので
「退会する」ボタンをクリックする。ログアウト状態でトップページへ遷移される。
adminerから論理削除できていることを確認する。

## 考慮してほしいこと
物理削除ではなく論理削除にて実装しました。また、本来であればユーザーに紐づく投稿も削除する必要があるのですが
postsテーブルがまだないため、User.phpにコメントアウトして記述しております。
postsテーブル実装後、改めて確認予定です。

## 確認してほしいこと
- 問題なくページ遷移できる事。
- 論理削除できる事。
- 適切なコードで記載できているかどうか。
を確認してほしいです。

2023-05-28 15:27 UTC, yukihiroLaravel requested changes
ほぼ完璧です！
いくつかコメントしましたのでご確認ください！

2023-05-28 15:27 UTC, yukihiroLaravel commented on app/Http/Controllers/EditUserController.php
> +            Auth::logout();
デリートすると自動的にログアウトするので、こちらはなくてもいいと思います！
（あってもいいですが）

2023-05-28 15:27 UTC, yukihiroLaravel commented on app/User.php
> +    // }
postsテーブルが実装されたのと
これもOKだと思いますし、こちらのコメントアウトをなくしましょう！

2023-05-28 15:27 UTC, yukihiroLaravel commented on app/Http/Controllers/EditUserController.php
> +use Illuminate\Support\Facades\Auth;
下のものがなくなれば、こちらも不要ですね！

2023-05-29 13:54 UTC, yuki-yuki1 commented on app/Http/Controllers/EditUserController.php
> +            Auth::logout();
削除しました。

2023-05-29 13:54 UTC, yuki-yuki1 commented on app/User.php
> +    // }
コメントアウトを無くしました。

2023-05-29 13:54 UTC, yuki-yuki1 commented on app/Http/Controllers/EditUserController.php
> +use Illuminate\Support\Facades\Auth;
削除しました。

2023-05-30 06:43 UTC, yukihiroLaravel approved these changes
OKです！
完璧なのでマージしました！

2023-05-30 06:43 UTC, merged