#15 投稿新規作成（ユウタ）
yukihiroLaravel/joint_develop pull request #34
Opened 2022-08-09 12:46 UTC by yuta2947

## issue
- closed #15

## 概要
- ログイン後に新規投稿機能を実装

## 動作手順
- 下記の情報でログインの実行
メールアドレス：sample@sample1.com
PW：sample

- 新規投稿機能の実行
ログイン後トップページに自動遷移します。テキストフォームが出現するので任意のテキストを入力し投稿ボタンクリック新規投稿を実行。投稿一覧にテキストが反映を確認しました。

- バリデーションの実行
文字数制限１４０文字、空欄禁止のバリデーションを実装しています。１４０文字以上の投稿と空欄の投稿を実施し、バリデーションの動作確認をしています。

## 考慮してほしいこと
- 英文字、かな、カナの投稿確認は実行しましたが特殊文字などの投稿は未実行です。

2022-08-09 23:10 UTC, yukihiroLaravel reviewed
一旦少しコメントしました！

2022-08-09 23:10 UTC, yukihiroLaravel commented on routes/web.php
> +
ここの空欄は消しましょう✨

2022-08-09 23:10 UTC, yukihiroLaravel commented on resources/views/posts/new_post.blade.php
> +<div class="w-75 m-auto"></div>
1行目とほぼ同じコードになっているので２行目は不要ですね！

2022-08-10 09:12 UTC, yukihiroLaravel requested changes
確認しまして、実装も綺麗に動くようにできていると思います✨

指摘した細かい空行などの点に
プルリク前に気付いて修正できるようになれば
レベルの高いエンジニアに近づけると思いますので
意識してみて下さい☺️

2022-08-10 09:12 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +    public function store(PostRequest $request)
`public function store(PostRequest $request)`
の前には１行空行を開けたほうがいいですね！

2022-08-10 09:12 UTC, yukihiroLaravel commented on resources/views/posts/new_post.blade.php
> +
あと、今回のタスクではなく前回のタスクの実装箇所で修正してほしい部分なのですが
このファイルではなく、post.blade.php で下記の２点を変更をしてほしいです。

①今だと、下記画像のように140文字以上の文字を連続して入力すると、自動的に改行されることがなく、無限に右に表示されてしまいます。
下記のように<p>要素のcssに書き加えることで、自動的に改行されるようになるので、
cssに書き加えてみて下さい！

②また、もう1点投稿訂正してほしいのですが、
今のままだと、投稿内容に有害なjavascriptなどのコードが悪意を持って仕込まれていたら
（クロス・サイト・スクリプティングというので調べてみてください！）
そのまま投稿として表示してしまうことになってしまいます。
なので表示の箇所に無害化処理を書く必要があり、下記のように書きます。

下記は、「改行は許容するけど、悪意ある処理は無害化しますよ」みたいな意味です！
`{!! nl2br(e($post->content)) !!}`

```
<div class="">
     <div class="text-left d-inline-block w-75">
         <p class="mb-2">{!! nl2br(e($post->content)) !!}</p>
         <p class="text-muted">{{ $post->created_at }}</p>
      </div>
</div>
```

2022-08-10 09:14 UTC, yukihiroLaravel commented on resources/views/posts/new_post.blade.php
> +
<img width="1787" alt="スクリーンショット 2022-08-10 17 59 06" src="https://user-images.githubusercontent.com/93365035/183863674-5bec7474-7049-4be6-84fa-493347ea0ed2.png">

2022-08-11 00:40 UTC, yuta2947 commented on routes/web.php
> +
確認しました！削除します:ok_hand:

2022-08-11 00:40 UTC, yuta2947 commented on resources/views/posts/new_post.blade.php
> +<div class="w-75 m-auto"></div>
確認しました！訂正します:ok_hand:

2022-08-11 00:42 UTC, yuta2947 commented on app/Http/Controllers/PostsController.php
> +    public function store(PostRequest $request)
空欄を空けましました！:ok_hand:

2022-08-11 13:47 UTC, yukihiroLaravel approved these changes

2022-08-11 13:47 UTC, merged