#321 ユーザ詳細(postテーブル実装後)
yukihiroLaravel/joint_develop pull request #340
Opened 2023-05-31 05:55 UTC by Tomoki-Amemiya

## issue
- Close #321 

## 概要
- ユーザ詳細ページ、タイムラインの実装

## 動作確認手順
- ユーザ詳細ページへアクセス
http://localhost:8080/users/1
にアクセスし、タイムラインが表示されているかどうか。
- 削除ボタン、編集ボタンの表示
ログインし、ログインユーザの詳細ページのタイムラインに、削除と編集ボタンが表示されているかどうか。

## 考慮してほしいこと
- 状況に応じて、下記コマンドで動作確認をする必要あり。
php artisan migrate:fresh --seed

## 確認してほしいこと
- タイムラインの表示件数について
コントローラーの下記コードにて、
`$posts = $user->posts()->orderBy('id', 'desc')->paginate(10);`
10件表示としていますが、10件で問題なかったでしょうか。
デモサイトにて確認はできますが、
こういう場合、11回投稿を行い確認をした方がよいでしょうか。
11回では終わらない可能性もあるため、今回はトップページと同じといたしました。

2023-05-31 15:17 UTC, yukihiroLaravel requested changes
pagenate は できればご自身で確認した方がいいですが
言ってしまうと、 (10)で大丈夫です！

その他指摘しましたので、ご確認お願いします！

2023-05-31 15:17 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
>                      </div>
ここにインデントをつけましょう

2023-05-31 15:17 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                    @else
この @else は不要かと思います！

2023-05-31 15:17 UTC, yukihiroLaravel commented on resources/views/posts/user_post.blade.php
> +</div>
このファイルは、すでに存在する
post.blade.php
をそのまま利用できると思うので
新規ファイルとして作らずそのまま使いましょう！

2023-06-01 04:00 UTC, Tomoki-Amemiya commented
## issue
- Close #321

## 概要
- ご指摘箇所の修正

## 動作確認手順
（※前回と同文）
- タイムラインの表示
http://localhost:8080/users/1
上記ユーザ詳細ページへアクセスし、タイムラインが表示されているかどうか。
- 削除ボタン、編集ボタンの表示
ログインし、ログインユーザの詳細ページのタイムラインに、削除と編集ボタンが表示されているかどうか。

## 考慮してほしいこと
（※前回と同文）
- 状況に応じて、下記コマンドで動作確認をする必要あり。
php artisan migrate:fresh --seed
- 削除ボタン、編集ボタン未実装
ボタン自体はありますが、リンク未実装です。

## 確認してほしいこと
- pagenateについて
今回は10件でしたが、もし、100件表示や500件表示だった場合、
100件、500件と投稿を書き込み確認をするのでしょうか。
シーダーを仮に作って確認したりするのでしょうか。
シーダーを使う方法が有力な気はいたしますが、
こういった確認を行う場合は、シーダーを使うと思っておいてよろしいでしょうか。
- showブレイドファイルの修正
13-15行目にインデント追加
@elseの削除 
- include先の変更
posts.postsに変更し、ファイルを削除しました。
内容が同じでしたが、表示方法が、
トップページは投稿全て、
ユーザ詳細ページはユーザ分のみ、
だったため、別ファイルが必要と勘違いをいたしました。
コントローラーにて表示を変更できることを再確認いたしました。

2023-06-01 04:31 UTC, yukihiroLaravel approved these changes
OKですのでマージしました！
おつかれさまでした✨

ご質問の件、１００件とか多い場合は
大抵、シーダーを使ってテストしますね！

2023-06-01 04:31 UTC, merged

2023-06-01 05:41 UTC, Tomoki-Amemiya commented
ありがとうございました！
あとは投稿削除のタスクのみなので、
引き続き頑張ります！