#342 フォロー機能（おおた）
yukihiroLaravel/joint_develop pull request #343
Opened 2023-06-01 06:12 UTC by u0222

## issue
- Closes #342

## 概要
- フォロー機能

## 動作確認手順
- ユーザー詳細画面でフォローボタンを確認
- 自分のユーザー詳細画面ではフォローボタンは表示されないことを確認
- フォローボタンを押下した際に、フォローを外すボタンに切り替わることを確認
- フォローを外すぼたんを押下した際に、フォローボタンに戻ることを確認
- フォローボタンを押下した際に、Adminerのfollowsテーブルでデータが登録されていることを確認

## 考慮して欲しいこと
- はじめFollowモデル（Follow.php)を作ってしまいましたが、今回不要でした。削除の仕方があれば教えていただければ幸いです。

## 確認してほしいこと
- マイグレーションを一度以下の内容で登録してしまいました。
```
  public function up()
    {
        Schema::create('follows', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->bigInteger('user_id');
            $table->bigInteger('followed_user_id');
            $table->timestamps();
            // 外部キー制約
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
            $table->unique(['user_id']);
        });
    }
```

できればLaravel応用講座に合わせた以下の形で修正したいのですが、修正方法がわかりませんでした。

```
    public function up()
    {
        Schema::create('favorites', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->bigInteger('user_id')->unsigned()->index();
            $table->bigInteger('movie_id')->unsigned()->index();
            $table->timestamps();
            // 外部キー制約
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
            $table->foreign('movie_id')->references('id')->on('movies')->onDelete('cascade');
            $table->unique(['user_id','movie_id']);
        });
    }
```

現状の問題点

- php artisan migrate:rollback　を実施したところ、すべてのマイグレーションデータが消えてしまいました。
- 現状は以下の状態です。
- ターミナルで`composer dump-autoload` `php artisan migrate:fresh --seed`を実行しましたが、データが戻りませんでした。
- `php artisan db:seed --class=UsersTableSeeder`を実行するとユーザーデータだけは登録できました
- `php artisan db:seed --class=PostsTableSeeder`を実行するとメールアドレスが重複して登録できませんでした

2023-06-02 14:09 UTC, Osk0830 requested changes
お疲れ様でした！
難しい実装にも関わらず、ここまで書けていて本当に素晴らしいと思います！

見落としがあったら恐縮ですが、
気づいた点コメントしましたので、
確認よろしくお願いします！

2023-06-02 14:09 UTC, Osk0830 commented on app/Follow.php
> +}
- 少し難しい話になる（文字ではうまく説明しきれない）かもですが、結論から言うと、このモデルは不要ではないかと思います。モデルは、モデルに対応する何らかの対象物（例：ユーザー、投稿、コメントなど）が存在するとイメージです。フォローは、何らかの対象物ではなく、対象物と対象物の関係を表しているに過ぎず、関係の所有者はあくまで対象物として存在する（ゆえにモデルが存在し得る）ので、フォローのモデル、というのはちょっとおかしい感じです。（説明しきれてなくてすみません。。。）

2023-06-02 14:09 UTC, Osk0830 commented on app/User.php
> +    }
- とてもよく書けていますが、一点だけ惜しい部分があります。現状では、下記tinker画面で見るように、自分自身もフォローできてしまいます。これは仕様的には少しおかしいので自分自身はフォローできないようにしてみてください。

[![Image from Gyazo](https://i.gyazo.com/0eccfbb0183004e47f98cc8dc1026650.png)](https://gyazo.com/0eccfbb0183004e47f98cc8dc1026650)

2023-06-02 14:09 UTC, Osk0830 commented on app/User.php
> +    }
- こちらも念のため上述のような仕組みを追加しましょう。

2023-06-02 14:09 UTC, Osk0830 commented on routes/web.php
> +    Route::post('{id}', 'FollowController@store')->name('follow');
- 今のURIでも他とは重複しないので問題はなさそうですが、少しわかりにくいので、unfollowの場合と同じように、`/users/{id}/follow`のようにしてあげるのがいいかもですね。

2023-06-06 14:46 UTC, u0222 commented on app/User.php
> +    }
ありがとうございます！自分自身をフォローできないように修正しました。

2023-06-06 14:46 UTC, u0222 commented on app/User.php
> +    }
ありがとうございます！自分自身をアンフォローできないように修正しました。

2023-06-06 14:47 UTC, u0222 commented on routes/web.php
> +    Route::post('{id}', 'FollowController@store')->name('follow');
ありがとうございます！
/users/{id}/follow
に修正しました。

2023-06-07 05:26 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらしっかり修正できているのでマージしますね。

引き続き頑張っていきましょう！

2023-06-07 05:26 UTC, merged