Feature/tadano/user detail
yukihiroLaravel/joint_develop pull request #35
Opened 2022-08-09 22:19 UTC by TDN0526

2022-08-10 22:24 UTC, TDN0526 commented
• Close #13 ユーザ詳細

概要
• ユーザ詳細画面の実装

動作確認手順
・localhost:8080にアクセス  

考慮してほしいこと
・グラバターインストール不可

確認してほしいこと
・特にありません。

2022-08-11 08:13 UTC, yukihiroLaravel requested changes
何点か変更いただきたい点を記述しました！
ご確認ください！

2022-08-11 08:13 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                    <img class="rounded-circle img-fluid" src="{{ Gravatar::src($post->user->email, 400)}}" alt="">
ここは只野さんの環境だとエラーで分からないと思いますが、
今のままだと他の人の環境では$postがないという、エラーが出てしまうので
下記のように書き直して下さい！🙇‍♂️

`{{ Gravatar::src($user->email, 400)}}`

2022-08-11 08:13 UTC, yukihiroLaravel commented on app/User.php
> +
ここは空行１行のみでいいと思うので、
１行分の空行を削除しておきましょう☺️

2022-08-11 08:13 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
> +
こちらは空行なしでいいと思いますので
削除しましょう✨

2022-08-11 14:15 UTC, yukihiroLaravel approved these changes

2022-08-11 14:15 UTC, merged