#336 フォロー機能(Ninomiya)
yukihiroLaravel/joint_develop pull request #350
Opened 2023-06-03 08:47 UTC by yuki-yuki1

## issue
- Close #336 

## 動作環境手順
ログイン後、「ユーザ詳細画面」にて「フォローする/を外す」ボタンが出ていないことを確認。
ログインid以外のidで次のURLへ移動「`http://localhost:8080/users/{id}`」。
「フォローする」ボタンが表示される。ボタンをクリックするとfollowersテーブルに記録されるため
adminerのfollowersテーブルを確認する。
クリック後、同じ画面でボタンが「フォローする」から「フォローを外す」に切り替わっている事を確認。
「フォローを外す」をクリックするとfollowersテーブルの記録が物理削除されるため
adminerのfollowersテーブルにて物理削除されたことを確認する。
同じ画面でボタンが「フォローを外す」から「フォローする」に切り替わっている事を確認。

## 考慮してほしいこと
特にありません。

## 確認してほしいこと
- 問題のあるコードがないか、 不必要に長いコードになっていないかどうか
よりすっきりとした書き方があれば教えていただきたいです。

- ルートの記載を最初１にしておりましたが
```
１　Route::post('{id}/follow', 'FollowersController@store')
２　Route::post('follow/{id}', 'FollowersController@store')
```
URL：「`http://localhost:8080/users/{id}`」へ移動し404エラーとなりました。
２に変更したところ、うまくいったのですが、1だとうまくいかない理由を教えていただきたいです。
よろしくお願いします。

2023-06-03 09:19 UTC, yukihiroLaravel requested changes
全般的に綺麗にかけていてすばらしいと思います！

細かい点だけいくつか指摘しましたので
ご確認願います☺️

2023-06-03 09:19 UTC, yukihiroLaravel commented on app/User.php
> +        return $this->belongsToMany(User::class, 'followers', 'followed_user_id', 'following_user_id')->withTimestamps();
これがfollowing()と全く同じ内容になっていませんか？

2023-06-03 09:19 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::post('follow/{id}', 'FollowersController@store')->name('follow');
>ルートの記載を最初１にしておりましたが

>１　Route::post('{id}/follow', 'FollowersController@store')
>２　Route::post('follow/{id}', 'FollowersController@store')

>URL：「http://localhost:8080/users/{id}」へ移動し404エラーとなりました。

これに関しては原因謎ですね。
上記ルーティングなら１でもエラー出ないはずですが、出る状況であれば
エラーが再現する状態でpushしてもらえればと思います！

2023-06-03 09:19 UTC, yukihiroLaravel commented on app/User.php
> +    public function isFollow($followed_user_id)
ここは多くの場合もっとシンプルに引数を書くのと
あとキャメルケースで書くので

isFollow($userId)

のように描きましょう！

2023-06-03 09:19 UTC, yukihiroLaravel commented on app/User.php
> +    public function follow($followed_user_id)
ここは多くの場合もっとシンプルに引数を書くのと
あとキャメルケースで書くので

follow($userId)

のように描きましょう！

2023-06-03 09:19 UTC, yukihiroLaravel commented on app/User.php
> +    public function unfollow($followed_user_id)
ここは多くの場合もっとシンプルに引数を書くのと
あとキャメルケースで書くので

unfollow($userId)

のように描きましょう！

2023-06-03 09:19 UTC, yukihiroLaravel commented on app/Http/Controllers/FollowersController.php
> +
ここの空行は不要ですかね！

2023-06-03 11:10 UTC, yuki-yuki1 commented on app/User.php
> +    public function isFollow($followed_user_id)
引数を変更しました。

2023-06-03 11:10 UTC, yuki-yuki1 commented on app/User.php
> +    public function follow($followed_user_id)
引数を変更しました。

2023-06-03 11:10 UTC, yuki-yuki1 commented on app/User.php
> +    public function unfollow($followed_user_id)
引数を変更しました。

2023-06-03 11:10 UTC, yuki-yuki1 commented on app/Http/Controllers/FollowersController.php
> +
削除しました。

2023-06-03 11:11 UTC, yuki-yuki1 commented on routes/web.php
> +        Route::post('follow/{id}', 'FollowersController@store')->name('follow');
エラーが出る状態で再pushいたします。ご確認をお願いします。

2023-06-03 11:11 UTC, yuki-yuki1 commented on app/User.php
> +        return $this->belongsToMany(User::class, 'followers', 'followed_user_id', 'following_user_id')->withTimestamps();
削除しました。
この行を作成した理由は、今回のテーブルの関係について
・[userテーブル/フォローする人]ー∈[中間followersテーブル]∋ー[userテーブル/フォローされる人]
上記をイメージしていたためです。
また、フォロー機能についてネットで調べていた際に
Userテーブルにリレーションを二つ記載していたものがいくつかありました。
(一つだけ記載しているサイトもありました)
URL:https://omkz.net/laravel-follow/
URL:https://qiita.com/mitsu-0720/items/0c2fcdd367e8a6c5999c
二つ記載しなければできない事があるのでしょうか？
ご教授いただけますと幸いです。

2023-06-04 01:49 UTC, yukihiroLaravel commented on app/User.php
> +        return $this->belongsToMany(User::class, 'followers', 'followed_user_id', 'following_user_id')->withTimestamps();
いえ、多分誤解されていて
following() も followed() も両方必要になるので、消さなくていいです！
ただ、中身が同じメソッドが２つある必要はないので、内容を少し変える必要があるという意味でした！

```
    public function followed()
    {
        return $this->belongsToMany(User::class, 'followers', 'following_user_id', 'followed_user_id')->withTimestamps();
     }
```

こんな感じで followed_user_id  と following_user_id の配置を逆にすれば
同じメソッドにはならず、フォローする・されるの相互の関係を補完するメソッドになりますので
そのように変えましょう！

2023-06-04 01:57 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::post('follow/{id}', 'FollowersController@store')->name('follow');
僕の方でやってみても
エラーは出ないですね！

今の状態で二宮さんはエラー出ますか？

2023-06-04 01:58 UTC, yukihiroLaravel requested changes
各コメントに返信する形で対応しました！
修正お願いします！

2023-06-04 02:23 UTC, yuki-yuki1 commented on routes/web.php
> +        Route::post('follow/{id}', 'FollowersController@store')->name('follow');
お手数おかけしてすいません。
今エラーの出る条件が確認できました。
(エラー手順)
1.ルート条件⓵でフォローできることを確認
2.ＶＳコードで⓵をコメントアウトし、条件⓶を作成し保存
3.フォローボタンを押す
4.404エラーが出現
(解消方法)
手順２-3の間で画面を再読み込みする

中途半端な状態で動きのチェックをしていたため問題が生じたようです。
エラー手順に従うと、条件⓵及び条件⓶のいずれでもエラーが発生しました。
以上、ご報告いたします。

2023-06-04 05:42 UTC, yuki-yuki1 commented on app/User.php
> +        return $this->belongsToMany(User::class, 'followers', 'followed_user_id', 'following_user_id')->withTimestamps();
変更しました。

2023-06-04 05:44 UTC, yuki-yuki1 commented on routes/web.php
> +        Route::post('follow/{id}', 'FollowersController@store')->name('follow');
ルート条件⓵で問題ないことが分かった為、記述をユーザー編集のroute::prefixへまとめました。

2023-06-04 07:47 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした✨

2023-06-04 07:48 UTC, merged