#341 投稿編集画面・更新(三田村)
yukihiroLaravel/joint_develop pull request #353
Opened 2023-06-05 21:55 UTC by Mita-N4306

## issue
- Close #341
## 概要
- 投稿編集ページでのコメント更新・コメントの編集
## 動作確認手順
- http://localhost:8080/ トップページからログインし、投稿したコメント一覧にある編集ボタンを押して編集画面に移行するか確認
- 投稿編集でコメントを変更・更新後、正しく反映されているか確認
- コメントを更新後、更新ボタンを押した後トップページに移動するか動作確認
- コメント投稿を複数作成して、全てのコメントが編集更新まで正しく動作するか確認
- 投稿編集でバリデーションエラーメッセージが表示されるか確認
## 考慮してほしい事
- 特にありません
## 確認してほしい事
- 投稿編集画面に正しく移動するか、投稿編集で更新したコメントが正しく反映するか、コードのインデックスが正しくそろっているか、投稿更新ボタンを押した後トップページに飛ぶか、などの確認

2023-06-05 22:13 UTC, Mita-N4306 commented
コンフリクトを解消後再びpushします

2023-06-06 12:26 UTC, Osk0830 requested changes
お疲れ様でした！
全体的にとてもよく書けていると思います！

少しだけ修正が必要そうな箇所がありますので、
確認よろしくお願いします！

2023-06-06 12:26 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        $post->user_id = \Auth::id();
- 51行目の記述は何のために必要な記述になりますでしょうか？

2023-06-06 12:26 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +            $post->user_id = $request->user()->id;
- 投稿の更新時に、その投稿をした人が誰かという情報を書き換えることはないでしょうし、あってはいけないと思います。そう考えると、53行目は必要でしょうか？

2023-06-06 12:26 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        ];
- 編集画面のbladeで、ユーザーの情報が必要となるような記述が特にないようですが、そうだとしたら、わざわざコントローラーで取得してからviewに渡す必要はないと思いますが、いかがでしょうか？

2023-06-06 21:23 UTC, Mita-N4306 commented on app/Http/Controllers/PostsController.php
> +        ];
編集画面bladeファイルには確かにユーザーに関する情報がありませんのでわざわざ渡す必要ありませんでした、ありがとうございます

2023-06-07 06:11 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらしっかりと修正できているのでマージしますね！

2023-06-07 06:11 UTC, merged