#19 フォロー機能（かねこなおき）
yukihiroLaravel/joint_develop pull request #36
Opened 2022-08-12 05:24 UTC by Kaneko0000

## issue 
- Close #19

## 概要
- フォロー機能

## 動作確認手順
- localhost:8080でログイン後、ログインしたユーザ以外の詳細画面で、フォローボタンの有無の確認。
- ボタンをクリックして、挙動の確認。
- ログインしたユーザー本人の詳細ページで、ボタンがないこと確認。

## 考慮してほしいこと
先日のMTGでユキヒロさんとの話で、とりあえずフォロー機能の実装だけとなりました。
詳細画面のタグにあるフォロー・フォロワーの表示は、まだ記述していません。

## 確認してほしいこと
特にありません。

2022-08-12 06:54 UTC, Osk0830 requested changes
お疲れ様です！
すごくよくできていて素晴らしいですね！

少しだけコメント残しましたので、ご確認ください。

2022-08-12 06:54 UTC, Osk0830 commented on app/User.php
> +        if (!$existing && !$myself) {
- ここの条件は、`&&`ではなく、`||`ではないでしょうか？

2022-08-12 06:54 UTC, Osk0830 commented on routes/web.php
> +});
- この部分は、今回のPRの実装範囲のどの部分に関わってきますでしょうか？

2022-08-12 09:38 UTC, Kaneko0000 commented on routes/web.php
> +});
詳細ページにフォロー・フォロワーを一覧を表示させるための記述でした。
消し忘れなので消去しました。

2022-08-12 10:01 UTC, Kaneko0000 commented on app/User.php
> +        if (!$existing && !$myself) {
教えていただきたいです。
public function follow($userId)
    {
        $existing = $this->is_following($userId);
        $myself = $this->id == $userId;
        if (!$existing && !$myself) {
            $this->followings()->attach($userId);
        }
    }
自分自身をフォローしておらず、「かつ」すでにフォローしてもいないという条件下のみ
$this->followings()->attach($userId);
上のコマンドを実行する。
といった考えで記述していますが、違いますか？
&&を||に変えたところで、何も変わらないので、間違えているのか、わかりません。

2022-08-12 11:16 UTC, Osk0830 commented on app/User.php
> +        if (!$existing && !$myself) {
今の状態ではAND条件でもOR条件でもあまり変わりなく見えるかもしれませんが、
「自分が自分自身をフォローする」ということは、
既にフォローしているか如何に関わらず、起こってはいけないことだと思うので、
「なおかつ」ではなく、「もしくは」の方が理論的に正しいと思います！

2022-08-12 12:07 UTC, Kaneko0000 commented on app/User.php
> +        if (!$existing && !$myself) {
ありがとうございます。
&& → || に書き換えました。

2022-08-14 05:30 UTC, Osk0830 approved these changes
お疲れ様です！
こちらマージしますね！

2022-08-14 05:31 UTC, merged