Feature/yuki/follow user
yukihiroLaravel/joint_develop pull request #365
Opened 2023-06-08 16:33 UTC by ykoh1119

## issue
- Closes #344  

## 概要
- フォロー機能

## 動作確認手順  
1.  http://localhost:8080/　に移動
2. ログイン前の状態でトップページおよびユーザー詳細画面にて自身以外のアカウント名の右側に「フォローする(を外す)」ボタンが表示されていないこと。
3. 任意のユーザーでログインし、他ユーザーの投稿を確認する。アカウント名の右側に「フォローする(を外す)」ボタンが表示されている。
4. フォローしていないユーザーの「フォローする」をクリックする
5. フォローしたユーザーのユーザー名の右側のボタンが「フォローを外す」に表示が変わる
6. Adminerのfollowsテーブルのdataを確認し、フォローしたユーザーおよびフォロワーのidが反映されている
7. フォロー済のユーザーの右側に表示されている「フォローを外す」をクリックする。
8. フォローを外したユーザーのユーザー名の右側のボタンが「フォローする」に表示が変わる
9. Adminerのfollowsテーブルのdataを確認し、フォローを外したユーザーおよびフォローを外されたユーザーのidのデータが削除されている
10. 3.以降の操作をユーザー詳細ページで実施して同じ結果になることを確認する
11. 自身の投稿および詳細ページで アカウント名の右側に「フォローする(を外す)」ボタンが表示されていない

## 考慮して欲しいこと
ボタンを文字で表示しているためボタンが大きくなってしまっていますが、今後アイコンを使用したものに変更したいと思っています。
ユーザー詳細にて、フォローするのボタンの色が被ってしまっていますが、アイコンに変更することにより解消します。

## 確認して欲しいこと
FollowController.phpのコードおよびUser.phpのソースで似たような処理をしている部分があるので、うまくまとめられないかと考えましたが思いつきませんでした。
何か良い方法がありましたら教えていただきたいです。

2023-06-09 02:24 UTC, Osk0830 requested changes
お疲れ様でした！
難しい実装だったかと思いますが、
色々と考慮しながらとてもよく書けていると思います！

本筋ではない部分ではありますが、
少しだけ調整してもらいたい箇所がありコメントしましたので、
確認よろしくお願いします！

2023-06-09 02:24 UTC, Osk0830 commented on app/Http/Controllers/FollowController.php
> +        }
- ログインしているユーザーのidであれば、わざわざ `Auth::user()`でユーザーの情報全てを取得しなくとも、`Auth::id()`で取得できます。そちらを使った方が処理が短くスマートになりますね。

2023-06-09 02:24 UTC, Osk0830 commented on routes/web.php
- ルーディングも非常によく書けていますが、せっかくですので、ユーザー情報の編集や更新、削除なども全体的に一つにまとめて整理していただくといいですね。

2023-06-09 13:48 UTC, ykoh1119 commented on app/Http/Controllers/FollowController.php
> +        }
ありがとうございます！
Auth::id()　の記載の仕方をすっかり忘れていました。。

2023-06-09 13:49 UTC, ykoh1119 commented on routes/web.php
ありがとうございます！
冗長になっていますもんね。。
修正いたしました！

2023-06-10 07:03 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKなのでマージしますね！

引き続き頑張っていきましょう！

2023-06-10 07:03 UTC, merged