コメント投稿（あめみや）
yukihiroLaravel/joint_develop pull request #369
Opened 2023-06-09 14:13 UTC by Tomoki-Amemiya

## issue
- Close #356

## 概要
- コメント投稿

## 動作確認手順
- ユーザログイン後、コメントを投稿する。
下記ページそれぞれにて入力
http://localhost:8080/
http://localhost:8080/users/〇
結果、Adminerでcommentsテーブルにデータが入り、
かつ、ページ上に表示されていることを確認する。

## 考慮してほしいこと
- 状況に応じて、下記コマンドで動作確認をする必要あり。
php artisan migrate:fresh --seed

## 確認してほしいこと
- includeした方がよいのか
`@include('commons.comment)`などで、
コメント部分を分けておいた方が良いのでしょうか。
includeにて分けるタイミングといいますか、
分けるトリガーのようなものはあるのでしょうか。

2023-06-11 17:31 UTC, Tomoki-Amemiya commented
## issue
- Close #356

## 概要
- commentsファイルを作成し、コメント部分をposts.blade.php内に@includeで表示
- コメント投稿の入力フォームが複数あるため、どのフォームでエラーが出ているのかどうかわかるよう変更
・そのフォームのみにエラーメッセージを表示した。
・エラーが出た入力フォームのみを赤枠表示にした。

## 動作確認手順
- 前回同様

## 考慮してほしいこと
- 状況に応じて、下記コマンドで動作確認をする必要あり。
php artisan migrate:fresh --seed

## 確認してほしいこと
- CommentRequest.phpについて
下記部分ですが、
 ```
   public function attributes()
    {
        return [
            'comment.' . $this->post_id => 'コメント',
        ];
    }
```
post_idも使って、どの投稿に対するエラーなのかを文章でも表示すべきでしょうか。
現在サイト上で、投稿自体に番号がふられているわけではないため、
伝わるような文字での表示方法がありませんでした。
そのため、単なる「コメント」としております。
代わりに、フォーム自体にエラーメッセージを表示し赤枠としております。
何か他に検討すべきでしたでしょうか。

2023-06-12 18:13 UTC, Tomoki-Amemiya commented
## issue
- Close #356 

## 概要
- バリデーション修正
- 投稿時のエラー修正

## 動作確認手順
- 前々回同様

## 考慮してほしいこと
- 状況に応じて、下記コマンドで動作確認をする必要あり。
php artisan migrate:fresh --seed

## 確認してほしいこと
- 特になし

2023-06-14 03:34 UTC, SekiYukihiro requested changes
別アカウントからですが
コメントしましたので、その点だけ修正願います！
不明点はお聞きください！

2023-06-14 03:34 UTC, SekiYukihiro commented on app/Http/Requests/CommentRequest.php
> +        'comment.*.max' => 'コメントは140文字以下で入力して下さい',
インデントが１つ必要ですね！

2023-06-14 03:34 UTC, SekiYukihiro commented on resources/views/comments/comments.blade.php
> +                            value="{{ old('comment.'. $post->id) }}"></textarea><br>
今の状態ですと、
１４０文字以上投稿してバリデーション エラーがでたとき、
その内容がフォームに残っていない状態になってしまうので、修正しましょう！☺️

2023-06-14 04:00 UTC, Tomoki-Amemiya commented
## issue
- Close #356

## 概要
- 指摘箇所の修正
1. CommentRequest.php内、インデントの追加
1. comments.blade.php内、textareaタグのold関数の修正

## 動作確認手順
- 同様

## 考慮してほしいこと
- 同様

## 確認してほしいこと
- 特になし

2023-06-14 05:45 UTC, yukihiroLaravel approved these changes
完璧です！
最高難易度に難しいところでかなり苦労されたと思いますが
よく終えられたと思います！
引き続きがんばりましょう🔥

2023-06-14 05:45 UTC, merged