＃18ユーザ退会（ユウタ）
yukihiroLaravel/joint_develop pull request #37
Opened 2022-08-14 11:17 UTC by yuta2947

## issue
- #18 

## 概要
- 退会処理でエラーが発生
退会処理機を実装したのですがエラーが発生してしまいます。確認お願いします。
- 現状
ユーザ情報の編集から退会ボタンをクリック
　　　　　　　↓
モーダルウィンドウが出現し、退会するを選択すると419｜Page Expiredのページに遷移

## 本タスクで編集したファイル
- web.php
- UsersController.php
- User.php
- post.php
- views\users\edit.blade.php

　　　　　　　

2022-08-15 00:21 UTC, yukihiroLaravel requested changes
確認しまして、良い感じですね！
自分で検索するべきところを検索するなど、
自走力がついてきていると思います！

ただ、いくつか基本の記述に忠実に書いたほうがいいところもありますので
その点だけ修正願います☺️

2022-08-15 00:21 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +    }
この書き方でも悪くはないのですが、
削除機能の基本に忠実に、web.phpから$id を渡してくる書き方に
書き直してみましょう！

Laravel応用講座４章の、投稿削除機能を参考にすると良いと思います☺️

2022-08-15 00:21 UTC, yukihiroLaravel commented on routes/web.php
> +    Route::post('withdrawal', 'UsersController@destroy')->name('withdrawal');
退会は、ユーザ関連の処理なのでusersのprefixの中にいれるように変更しましょう！

また、そうなるとこちらも基本に忠実に、
users.delete というルーティング名などにしたほうがよさそうですね！

また、Route::postメソッドを使っていますが
Route::deleteメソッドを使ったほうが、URLも{id}だけの形にすることができて
よりスマートですね☺️

2022-08-15 00:21 UTC, yukihiroLaravel commented on app/User.php
> +        });
よくこの書き方にたどり着かれましたね！
検索力がすばらしいです！

2022-08-15 01:38 UTC, yuta2947 commented on routes/web.php
> +    Route::post('withdrawal', 'UsersController@destroy')->name('withdrawal');
こちらRoute：：deleteに変更しprefix(’users’)の中に記述し直しました 😄

2022-08-15 01:39 UTC, yuta2947 commented on app/User.php
> +        });
ありがとうございます😄

2022-08-15 01:39 UTC, yuta2947 commented on app/Http/Controllers/UsersController.php
> +    }
記述を変更しました😄

2022-08-16 07:36 UTC, yukihiroLaravel requested changes
１点だけ指摘がありますので、修正願います☺️

2022-08-16 07:36 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::delete('{id}/delete', 'UsersController@destroy')->name('users.delete');
こちら、`/delete` は不要ですね！

なぜかというと、メソッドにdeleteを記述しているので、
その時点で{id}のユーザを削除するのだなとわかるからです！

2022-08-16 13:40 UTC, yuta2947 commented on routes/web.php
> +        Route::delete('{id}/delete', 'UsersController@destroy')->name('users.delete');
削除いたしました:smile:

2022-08-16 13:46 UTC, yukihiroLaravel requested changes

2022-08-16 13:46 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $user->delete();}
```
if () {
    $user->delete();
}
```

2022-08-16 13:49 UTC, yuta2947 commented on app/Http/Controllers/UsersController.php
> +        $user->delete();}
修正しました！:smile:

2022-08-16 15:20 UTC, yukihiroLaravel approved these changes
OKです☺️

2022-08-16 15:20 UTC, merged