#352 フォロワーリストの作成(Ninomiya)
yukihiroLaravel/joint_develop pull request #373
Opened 2023-06-10 07:41 UTC by yuki-yuki1

## issue
- Close #352 

## 動作環境手順
「ユーザ詳細画面」(http\://localhost:8080/users/{id})へ移動
- タブ「タイムライン」,「フォロー中」,「フォロワー」の下に「投稿数」,「フォロー中ユーザ数」,「フォロワー数」が
表示される。
-「フォロー中」,「フォロワー」のタグをクリック、それぞれでフォロー中、フォロワーのユーザ名,最新の投稿,
最新投稿日が表示される。10人ずつページネーションする。
- 「フォロー中」の画面で「フォローを外す」ボタンが表示されないこと

ログインした状態で「ユーザ詳細画面」のログインユーザのページ(http\://localhost:8080/users/{ログインユーザのid})へ移動
- 「フォロー中」の画面で「フォローを外す」ボタンが表示される。クリックするとフォローが外れる。

## 考慮してほしいこと
特になし
## 確認してほしいこと
より少ないコード数やすっきりした書き方があれば教えて頂きたいです。

2023-06-10 11:59 UTC, yukihiroLaravel requested changes
コメントしましたので修正お願いします！

2023-06-10 11:59 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $data=[
$data = [

2023-06-10 11:59 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $data=[
$data = [

2023-06-11 06:36 UTC, yuki-yuki1 commented on app/Http/Controllers/UsersController.php
> +        $data=[
修正しました。

2023-06-11 06:36 UTC, yuki-yuki1 commented on app/Http/Controllers/UsersController.php
> +        $data=[
修正しました。

2023-06-12 11:43 UTC, yukihiroLaravel approved these changes
OKですのでマージしました！
難しい実装おつかれさまでした✨！

2023-06-12 11:44 UTC, merged