コメント削除（あめみや）
yukihiroLaravel/joint_develop pull request #380
Opened 2023-06-14 06:24 UTC by Tomoki-Amemiya

## issue
- Close #357

## 概要
- コメント削除の実装

## 動作確認手順
- ログイン後「コメント削除」ボタンでのコメント削除
### 下記ページにて実行
* http://localhost:8080/
* http://localhost:8080/users/〇
ログインユーザ自身のコメント下部にある「コメント削除」ボタンを実行する。

## 考慮してほしいこと
- 状況に応じて、下記コマンドで動作確認をする必要あり。
php artisan migrate:fresh --seed

## 確認してほしいこと
- 特になし

2023-06-15 00:23 UTC, yukihiroLaravel requested changes
１点コメントしましたのでご確認願います！

2023-06-15 00:23 UTC, yukihiroLaravel commented on app/Http/Controllers/CommentsController.php
> +        $comment = Comment::find($id);
こちら
findOrFail()
を使った方が、
idが存在する数字ではなかったときにエラーになるのを防げるのでいいと思います！

2023-06-16 04:11 UTC, Tomoki-Amemiya commented
## issue
- Close #357 

## 概要
- 指摘箇所の修正
commentコントローラーの`public function destroy`を修正しました。

## 動作確認手順
- 同様

## 考慮してほしいこと
- 同様

## 確認してほしいこと
- 特になし

2023-06-16 04:25 UTC, yukihiroLaravel approved these changes
OKです！
修正お疲れ様でした✨

2023-06-16 04:26 UTC, merged