フラッシュメッセージその2（あめみや）
yukihiroLaravel/joint_develop pull request #384
Opened 2023-06-14 15:16 UTC by Tomoki-Amemiya

## issue
- Close #377

## 概要
- フラッシュメッセージの実装(その2)
下記項目にフラッシュメッセージを追加
・ユーザ新規登録
・ユーザログイン・ログアウト
・投稿編集（未実装のため次回）
・フォローする
・フォロー外す
※投稿編集のみ次回実装予定（別issue作成済み）

## 動作確認手順
- 上記箇所それぞれ動作を実行する。

## 考慮してほしいこと
- 状況に応じて、下記コマンドで動作確認をする必要あり。
php artisan migrate:fresh --seed

## 確認してほしいこと
- ログアウトメッセージの記述箇所について
AuthenticatesUsers.phpに記述しております。
コミット前にgit statusをした際、表示される編集したファイルは下記しか出てきませんでした。
・modified:   app/Http/Controllers/Auth/LoginController.php
・modified:   app/Http/Controllers/Auth/RegisterController.php
・modified:   app/Http/Controllers/FollowersController.php
ログアウトのフラッシュメッセージは下記へと記述したのですが、

▼vendor\laravel\framework\src\Illuminate\Foundation\Auth\AuthenticatesUsers.php
```
    public function logout(Request $request)
    {
        $this->guard()->logout();

        $request->session()->invalidate();

        $request->session()->regenerateToken();

        return $this->loggedOut($request) ?: redirect('/')->with('redMessage', 'ログアウトしました');
    }
```
上記のようなファイルは編集すべきではないような気がしたのですが、
やはり編集してはいけないのでしょうか。
こちらのプルリク上にも表示がされておりません。
今までの講座などの中で話が出てきていたとしたら申し訳ございません。

- ログインメッセージの記述方法について
今までのフラッシュメッセージは全て、
`->with('greenMessage', '○○しました');`のような記述方式でした。
今回、上記ではエラーが出たため、ログインのみを、
`session()->flash('greenMessage', 'ログインしました');`といたしました。
検索を行ったところ、
フラッシュメッセージは３通りの記述方法があるようでしたが、
どれか１つ（今回なら`->with`）に統一するべきなのでしょうか。
（混在しているのは、何となくよろしくないような気がしたため。）

2023-06-15 00:30 UTC, yukihiroLaravel requested changes
ご確認願います！

2023-06-15 00:30 UTC, yukihiroLaravel commented on app/Http/Controllers/Auth/LoginController.php
> +        return '/';
質問いただいている通り、
こちらも with を使って統一しましょう！

2023-06-15 00:54 UTC, yukihiroLaravel reviewed
宜しくお願いします

2023-06-16 05:47 UTC, Tomoki-Amemiya commented
## issue
- Close #377

## 概要
- 記述方式をwithに統一
- vendorファイルから、
app\Http\Controllers\Auth\LoginController.phpに、書き直し

## 動作確認手順
- 同様

## 考慮してほしいこと
- 同様

## 確認してほしいこと
- コードの書き方が間違っている気がいたします。
```
protected function registered(Request $request, $user)
    {
        return redirect('/')->with('greenMessage', '新規登録しました');
    }
```
と、
```
protected function authenticated(Request $request, $user)
    {
        return redirect('/')->with('greenMessage', 'ログインしました');
    }
```
の、`(Request $request, $user)`部分について、
Requestが使用されていないようなのですが、
勘違いなのか、Requestは必要ないのか、記述自体が間違っているのか、
どうなのでしょうか。
一応`use Illuminate\Http\Request;`は追加しております。

2023-06-16 08:55 UTC, yukihiroLaravel requested changes
下記の点、２箇所にコメントしました！

おっしゃる通り、
Request $request, $user
これらが使われていないのなら()の中の引数を削除していいと思います！

また当初お伝えしていた通り、
できる限りレビューコメントには（対応しました！などだけでもいいので）返信するようにしましょう。
（今回は良いですが、行数が多い場合、対応したか？が不明確になってしまうので！）

2023-06-16 08:55 UTC, yukihiroLaravel commented on app/Http/Controllers/Auth/RegisterController.php
> +    protected function registered(Request $request, $user)
おっしゃる通り、
Request $request, $user
これらが使われていないのなら()の中の引数を削除していいと思います！

2023-06-16 08:55 UTC, yukihiroLaravel commented on app/Http/Controllers/Auth/LoginController.php
> +    protected function authenticated(Request $request, $user)
おっしゃる通り、
Request $request, $user
これらが使われていないのなら()の中の引数を削除していいと思います！

2023-06-17 13:14 UTC, Tomoki-Amemiya commented on app/Http/Controllers/Auth/LoginController.php
> +        return '/';
withに変更し、全体を統一いたしました。

2023-06-17 13:17 UTC, Tomoki-Amemiya commented on app/Http/Controllers/Auth/RegisterController.php
> +    protected function registered(Request $request, $user)
`use Illuminate\Http\Request;`
ならびに
`Request $request, $user`
を削除しました。

2023-06-17 13:17 UTC, Tomoki-Amemiya commented on app/Http/Controllers/Auth/LoginController.php
> +    protected function authenticated(Request $request, $user)
`Request $request, $user`
を削除しました。

2023-06-17 13:31 UTC, Tomoki-Amemiya commented
## issue
- Close #377

## 概要
- 指摘箇所の修正

## 動作確認手順
- 同様

## 考慮してほしいこと
- 同様

## 確認してほしいこと
- 特になし

2023-06-18 02:00 UTC, yukihiroLaravel approved these changes
これでOKです☺️
マージしました！

レビューコメントの返信もこれで全然問題ないです！

> 最後にも特に何もなかったのですが、コメントを記入いたしました。
これは特になにもなければ、なしでOKですよ✨

2023-06-18 02:00 UTC, merged