#394 フォロー機能コード共通化(ユウキ)
yukihiroLaravel/joint_develop pull request #395
Opened 2023-06-17 14:57 UTC by ykoh1119

## issue
- Closes #374  

## 概要
- フォロー機能コード共通化

## 動作確認手順  
修正前と変わらず、タイムライン/フォロー中/フォロワーリストの表示が動いているか

## 考慮して欲しいこと
特にありません。

## 確認して欲しいこと
共通化をするにあたって可読性が下がっているような気がしています。
少しやりすぎな部分もありそうなので、そのままで良い部分や、ここはもっと上手く共通化できるといった部分を教えていただけると幸いです。

2023-06-20 13:04 UTC, Osk0830 requested changes
お疲れ様でした！
色々と試行錯誤されていて素晴らしいですね！

首尾一貫した観点という立場から、
少しだけコメントしましたので、
検討してみていただければと思います。

2023-06-20 13:04 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +                </div>
- 3つのBladeを一つにまとめるという観点もありと思います。そうなると、このshowのBladeは、いわゆる骨組みになるBladeという位置付けになると思いますので、この部分はここに細かく書いてしまわずに、パーツとして切り出してしまった方が良さそうですね。
- 可読性や拡張性の観点から考えた場合、showのBladeとフォロー系Bladeとで分けとくのもありかもしれません。

2023-06-20 13:04 UTC, Osk0830 commented on resources/views/users/show.blade.php
>              </ul>
- タブ部分もパーツとして切り出した方が、骨組みとしてのこのBladeの役割が明確になりそうですね。

2023-06-20 13:04 UTC, Osk0830 commented on resources/views/users/show.blade.php
>              </div>
- カード部分も切り出してしまった方が、首尾一貫していて良さそうです。要するに、骨組みのBlade＋コンポーネントのBladeがあって、コンポーネントはいろいろな場所で使いまわせるし、修正などもコンポーネント単位で行う、といった観点ですね。

2023-06-20 15:31 UTC, ykoh1119 commented on resources/views/users/show.blade.php
> +                </div>
ご指摘ありがとうございます。
可読性や拡張性を考えるとファイルが増えてしまうのはしょうがないと思うので、bladeを分けて修正しようと思います。

2023-06-20 15:32 UTC, ykoh1119 commented on resources/views/users/show.blade.php
>              </ul>
asideタグ部分をコンポーネント化したいと思います。

2023-06-21 05:55 UTC, Osk0830 approved these changes
お疲れ様です！
だいぶ良い感じに整理できたように思われますので、
こちらマージしますね！

2023-06-21 05:55 UTC, merged