#391 投稿・コメントの検索機能(Ninomiya)
yukihiroLaravel/joint_develop pull request #396
Opened 2023-06-17 17:40 UTC by yuki-yuki1

## issue
- Close #391 

## 動作環境手順
トップページの検索窓から、キーワードを一つ入力し、キーワードが含まれる投稿、コメントが取得される事を確認。
キーワードを二つ以上入力し、すべてのキーワードが含まれる投稿、もしくはコメントが取得されることを確認。

## 考慮してほしいこと
投稿、コメント内容を検索範囲とした、単一及び複数キーワードでの検索機能を実装しています。

## 確認してほしいこと
- キーワードが含まれる投稿、コメントのみ表示されること。
- 複数キーワードにおいて、すべてのキーワードが含まれる投稿、コメントが表示されること(一つのキーワードしか含まれていないのに表示をしないこと)。
- 半角、全角を区別しない処理はしておりませんが、区別しない仕様となっております。この理由と、どの部分を変更すれば区別するしないを変更できるのか教えて頂きたいです。
- 冗長なコードとなっていないかを確認してほしいです。
- 今回間違えて、`git add .`をせずに`git commit`をしてしまったため、コミットを取り消そうと思い、`git reset HEAD～`を実行したところ
おそらく、今回自分が作成したところよりもっと前の段階にもどってしまいました。(`git add .`を実施したところ自分が今回作成していないファイルまで変更履歴として出てきました)。この場合どのような処理をすればよかったでしょうか。
今回私が追記したファイルは、PostsController.php、welcome.blade.php、web.phpの3ファイルとなります。ご確認をお願いします。

2023-06-18 12:54 UTC, yukihiroLaravel requested changes
コメントしました。ご確認下さい。

2023-06-18 12:54 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        ->paginate(10);
インデント

2023-06-18 12:54 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $request->flash();
なんのために必要？？

2023-06-18 13:53 UTC, yuki-yuki1 commented on app/Http/Controllers/PostsController.php
> +        ->paginate(10);
修正しました。

2023-06-19 11:16 UTC, yuki-yuki1 commented on app/Http/Controllers/PostsController.php
> +        $request->flash();
$request->flash()がない場合、old関数が効かずに、
ページが切り替わった際に入力したキーワードが保持されなくなってしまったため
このコードを記載しています。

2023-06-19 14:15 UTC, yukihiroLaravel approved these changes
お疲れ様でした！

2023-06-19 14:15 UTC, merged