ユーザ画像編集（あめみや）
yukihiroLaravel/joint_develop pull request #401
Opened 2023-06-20 05:32 UTC by Tomoki-Amemiya

## issue
- Close #379

## 概要
- ユーザ画像編集機能の実装

## 動作確認手順
- 下記コマンドを実行
php artisan migrate --seed
- Adminerでusersテーブルにprofile_imageカラムが追加されていることを確認
- ユーザ画像の変更
ログイン後、下記ページにてユーザ画像を変更する
http://localhost:8080/users/〇/edit
- バリデーションの確認
・ファイルの種類jpeg,png,jpg
・1MB以下まで
・横幅1000pxまで
上記以外はエラーとなる。
- 更新後ユーザ画像が変更されていることを確認
・トップページ
・ユーザ詳細ページ
・ユーザ情報編集ページ
上記それぞれのユーザ画像が変更されている事を確認
## 考慮してほしいこと
- 状況に応じて、下記コマンドで動作確認をする必要あり。
php artisan migrate:fresh --seed

## 確認してほしいこと
- 特になし

2023-06-20 07:51 UTC, yukihiroLaravel requested changes
きちんと動いていてかなりすばらしいと思います！！

ただ、細かい点を指摘しましたのでご確認いただければと思います。
宜しくお願いします！

2023-06-20 07:51 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +            $updateUser['profile_image'] = $profileImagePath;
今profile_imageカラムに保存されているのは

public/images/profiles/R0OBYoSQxDV3tiruHEYirp2N08ferUzYgWKG9ZKO.png

これが丸ごと保存されていますが、
public/images/profiles/
ここまではどのユーザでも同じだと思いますので保存しなくていいと思います！

また、今の状態だと保存先のフォルダを見ても
パッと見、どのファイルが誰のプロフィール画像なのか区別しにくいので
可能なら下記のように保存先ごとにフォルダを変えられると良いですね。

```
ユーザID: 1 の場合
　public/images/profiles/1/image.png

ユーザID: 2 の場合
　public/images/profiles/2/image.png
```

2023-06-21 06:38 UTC, Tomoki-Amemiya commented
## issue
- Close #379

## 概要
- 指摘箇所の修正
ご指摘いただいたコメントへ返信した通り修正を行いました。

## 動作確認手順
- 下記コマンドを実行
php artisan storage:link
php artisan migrate --seed
- Adminerでusersテーブルにprofile_imageカラムが追加されていることを確認
- ユーザ画像の変更
ログイン後、下記ページにてユーザ画像を変更する
http://localhost:8080/users/〇/edit
- バリデーションの確認
・ファイルの種類jpeg,png,jpg
・1MB以下まで
・横幅1000pxまで
上記以外はエラーとなる。
- 更新後ユーザ画像が変更されていることを確認
・トップページ
・ユーザ詳細ページ
・ユーザ情報編集ページ
上記それぞれのユーザ画像が変更されている事を確認

※シンボリックリンク表記が抜けていたため再記載

## 考慮してほしいこと
- 状況に応じて、下記コマンドで動作確認をする必要あり。
php artisan migrate:fresh --seed

## 確認してほしいこと
- 画像パスについて
今回のプロフィール画像の表示方法について、下記２種類から迷ったのですが、
`<img src="{{ Storage::url('images/profiles/'.$user->profile_image) }}">`
または、
`<img src="{{ asset('storage/images/profiles/'.$user->profile_image) }}">`
応用講座の時に、assetをよく見た気がしたため、asset表記で行いました。

どちらが良いとかあるのでしょうか。
やはり、全体を見て使われているコードに統一することが優先事項でしょうか。

2023-06-21 06:38 UTC, Tomoki-Amemiya commented on app/Http/Controllers/UsersController.php
> +            $updateUser['profile_image'] = $profileImagePath;
- DBには、
「id/アップロードされたファイル名」にて保存されるように変更しました。

- 保存するディレクトリは、
非公開ディレクトリの「public/images/profiles/(id)」ディレクトリ直下となっております。

- 「idが1」のユーザが「test1.png」という画像をアップした場合、
DBには、「1/test1.png」と保存され、
ディレクトリは、「public/images/profiles/1/test1.png」で保存されます。

2023-06-21 08:27 UTC, yukihiroLaravel requested changes
修正点はOKです！

ただ、パスワードを入れたとき、暗号化されて保存されず
そのまま保存されています！

バグなので直しましょう・・・！

2023-06-21 08:27 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
>          $user->password = Hash::make($request->password);
今気付いたのですが、
パスワードを入れたとき、暗号化されて保存されず
そのまま保存されています！

バグなので直しましょう！

2023-06-23 16:40 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした！

ただ、今後はバグっぽい挙動があれば
後回しにせず、事前にご連絡お願いします✨
（これは実務では特に大事です！）

2023-06-23 16:40 UTC, merged