#397 サイトのタイトル決め・ベースカラーなど(三田村)
yukihiroLaravel/joint_develop pull request #407
Opened 2023-06-22 22:10 UTC by Mita-N4306

#397 サイトのタイトル決め・ベースカラーなど(三田村)

## issue
- Close #397
## 概要
- サイトのタイトル決め(仮)・ベースカラーなどを変更して表示させる
## 動作確認手順
- サイトのタイトルを変更(仮)
- ベースカラーの変更
- トップページに画像を追加(２種類)
- ヘッダーのロゴを変更(仮)
- ログイン・新規投稿画面のタイトルを変更・ロゴ画像を追加
## 考慮してほしい事
- サイトのタイトルなどは現段階で仮となっており、今後改良修正が入る可能性が高いです
## 確認してほしい事
- コードの書き方がおかしくないか(見やすい書き方がないか)、などありましたらご指摘下さると幸いです。

2023-06-23 13:51 UTC, Osk0830 requested changes
お疲れ様でした！
とてもインパクトがあり、カラーテイストもテーマに良く合っていると思います！

少しだけ修正した方が良さそうな内容がありコメントしましたので、
確認よろしくお願いします！

2023-06-23 13:51 UTC, Osk0830 commented on resources/views/commons/carousel_img.blade.php
> +</div>
- カルーセルまで導入されてとてもいいかんじなのですが、カルーセル部分があまりに大きすぎて、画面を全部支配してしまい、投稿などがすぐに見えないため、この状態ですと初回訪問者の離脱を助長する可能性がありそうです。。カルーセルのサイズをもう少し小さくした方がいいような気がします。

[![Image from Gyazo](https://i.gyazo.com/b80476744be25be5f012a0ef6a5629ed.png)](https://gyazo.com/b80476744be25be5f012a0ef6a5629ed)

2023-06-23 13:51 UTC, Osk0830 commented on resources/views/commons/header.blade.php
> +        <a class="navbar-brand" href="/"><img src="{{ asset('img/logo.png') }}" alt="ロゴ画像" width="40" height="40">Ideal Ramen</a>
- アイコンとサイトタイトルの間に少し余白を入れた方が良さそうです。

[![Image from Gyazo](https://i.gyazo.com/3b5de13112d58f30d157d732f3c55fb4.png)](https://gyazo.com/3b5de13112d58f30d157d732f3c55fb4)

2023-06-24 03:05 UTC, Mita-N4306 commented on resources/views/commons/carousel_img.blade.php
> +</div>
確かに画像が大きすぎました、修正しましたm(__)m

2023-06-24 03:06 UTC, Mita-N4306 commented on resources/views/commons/header.blade.php
> +        <a class="navbar-brand" href="/"><img src="{{ asset('img/logo.png') }}" alt="ロゴ画像" width="40" height="40">Ideal Ramen</a>
余白を少し開けましたm(__)m

2023-06-25 08:56 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKそうなのでマージしますね〜！

2023-06-25 08:56 UTC, merged