#412 フォームにエラー表示追加その1（あめみや）
yukihiroLaravel/joint_develop pull request #414
Opened 2023-06-23 14:05 UTC by Tomoki-Amemiya

## issue
- Close #412

## 概要
- 入力フォームがエラーの時、赤くなるように変更

## 動作確認手順
- 各入力フォームにエラーになる入力を行う
・ログイン
・新規投稿
・新規ユーザ登録
・ユーザ情報編集

## 考慮してほしいこと
- 下記は未実装のため、実装後に追加予定
・投稿の編集・更新
・画像投稿
・ユーザ画像編集
※上記は未実装です。

## 確認してほしいこと
- 特になし

2023-06-23 17:00 UTC, yukihiroLaravel requested changes
コメントしました！

2023-06-23 17:00 UTC, yukihiroLaravel commented on resources/views/auth/register.blade.php
>                  <label for="password_confirmation">パスワード確認</label>
パスワード確認欄は赤くするのが抜けてないでしょうか？

2023-06-23 17:00 UTC, yukihiroLaravel commented on resources/views/users/edit.blade.php
>          <div class="form-group">
パスワード確認欄は赤くするのが抜けてないでしょうか？

2023-06-26 07:41 UTC, Tomoki-Amemiya commented on resources/views/users/edit.blade.php
>          <div class="form-group">
app\Http\Controllers\Auth\RegisterController.php
resources\lang\ja\validation.php
上記ファイルを修正いたしました。

2023-06-26 07:42 UTC, Tomoki-Amemiya commented on resources/views/auth/register.blade.php
>                  <label for="password_confirmation">パスワード確認</label>
app\Http\Controllers\Auth\RegisterController.php
resources\lang\ja\validation.php
上記ファイルを修正いたしました。

2023-06-26 07:51 UTC, Tomoki-Amemiya commented
## issue
- Close #412

## 概要
- パスワード確認フォーム追加
ご指摘いただいた箇所を修正
各bladeファイルにコードを追加し、
・app\Http\Controllers\Auth\RegisterController.php
・app\Http\Requests\UserRequest.php
・resources\lang\ja\validation.php
上記ファイルを修正いたしました。

## 動作確認手順
- 各入力フォームにエラーになる入力を行う
・ログイン
・新規投稿
・新規ユーザ登録
・ユーザ情報編集

## 考慮してほしいこと
- 下記は未実装のため、実装後に追加予定
・投稿の編集・更新
・画像投稿
※上記は未実装です。

## 確認してほしいこと
- パスワード確認フォームについて
「パスワードとパスワード確認が一致しません。」のエラーの場合のみ、
パスワード確認フォームを赤くすることができませんでした。
そもそもパスワードとすら一致がしていないため、
パスワード確認フォーム以前の問題かと思いますので、
パスワード確認フォームのエラー表示は不必要かと思いましたが、
間違っておりますでしょうか。

2023-06-26 14:55 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！

2023-06-26 14:55 UTC, merged