タイトルと投稿（シーダー）内容変更（あめみや）
yukihiroLaravel/joint_develop pull request #417
Opened 2023-06-23 16:12 UTC by Tomoki-Amemiya

## issue
- Close #416

## 概要
- タイトルと投稿（シーダー）内容の変更

## 動作確認手順
- php artisan migrate --seedコマンド実行
Adminerで
・usersテーブルに4個
・postsテーブルに11個
・commentsテーブルに24個
それぞれできていることを確認。

## 考慮してほしいこと
- 状況に応じて、下記コマンドで動作確認をする必要あり。
php artisan migrate:fresh --seed

## 確認してほしいこと
- シーダー内容が長文の場合、コードを複数行に書いた方がよいのでしょうか。
一行に書くと見にくい気がしたのですが、複数行に書くべきなのか、
もし複数行にする場合はどのように書くべきなのでしょうか。
現在下記のような感じです。
```
        DB::table('posts')->insert([
            'user_id' => 1,
            'text' => "家庭料理のレシピをシェアしよう！\n手軽にできる料理やスイーツを\n写真や手順を添えてシェアしませんか？",
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
```

2023-06-23 16:53 UTC, yukihiroLaravel requested changes
コメントしました

2023-06-23 16:53 UTC, yukihiroLaravel commented on database/seeds/CommentsTableSeeder.php
> +            'comment' => "「マーメイドのフルーツサラダ」のレシピ\n材料：\n・フェアリーブレッド：2個、切り分ける\n・マーメイドメロン：1個、種を取り除いて切り分ける\n・シルバーリーフ：適量\n・ムーンドロップ：数粒\n・フェアリーハニー：適量\n作り方：\n・フェアリーブレッドとマーメイドメロンを器に盛ります。\n・シルバーリーフを添え、ムーンドロップを散らしま
```
$str = '私は事実毫もこうした記憶物について事のためでありでしょなけれ。'
       .'はなはだほかを赴任めももちろん'
       .'そんな沙汰ありでかもを落ちが来るなをはふり思っうなかって、'
       .'しっかりにはいうないましうなけれ。';
```

ご質問の件、こういう書き方もありますね。
もちろんこのままでもいいですが、書き換えますか？

2023-06-23 16:57 UTC, Tomoki-Amemiya commented on database/seeds/CommentsTableSeeder.php
> +            'comment' => "「マーメイドのフルーツサラダ」のレシピ\n材料：\n・フェアリーブレッド：2個、切り分ける\n・マーメイドメロン：1個、種を取り除いて切り分ける\n・シルバーリーフ：適量\n・ムーンドロップ：数粒\n・フェアリーハニー：適量\n作り方：\n・フェアリーブレッドとマーメイドメロンを器に盛ります。\n・シルバーリーフを添え、ムーンドロップを散らしま
このままでも問題がないのでしたらこのままでも大丈夫です！
複数行の書き方がある事について覚えておきます！

2023-06-25 04:26 UTC, Tomoki-Amemiya commented
コンフリクトが発生したため、
修正を行い、再プッシュさせていただきました。

2023-06-25 09:19 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした！

2023-06-25 09:20 UTC, merged