Feature/ota/comment delete update
yukihiroLaravel/joint_develop pull request #419
Opened 2023-06-26 06:42 UTC by u0222

## issue
- Closes #418

## 概要
- #418 コメント（ボケ回答）削除・編集更新機能

## 動作確認手順
- 削除機能
- 投稿したコメント（ボケ回答）の下の削除ボタンを押下した際にコメントが削除されるか確認
- コメントを削除できるのは本人のみ
- 削除後にフラッシュメッセージが表示される

- 編集更新機能
- 投稿したコメント（ボケ回答）の下の更新ボタンを押下しするとコメント編集ページへ遷移する
- コメント編集ページでは、投稿済みのコメントが表示されている
- コメントを編集できるのはできるのはできるのは本人のみ
- コメントを編集して「更新するボタン」を押下するとコメントが更新される
- 各お題のコメント一覧ページへリダイレクトされ、フラッシュメッセージが表示される

## 考慮して欲しいこと
- 特にありません
 
## 確認してほしいこと
- コメントコントローラーのedit（下記箇所）について、もっとスマートな書き方があれば教えてほしいです

```
    public function edit($postId, $commentId)
    {
        $comment = Comment::findOrFail($commentId);
        if (\Auth::id() === $comment->user_id && $comment->post_id == $postId) {
            $posts = Post::findOrFail($postId);
            return view('posts.comment_edit', [
                'comment' => $comment,
                'posts' => $posts,
            ]);
        }
    }
```
の中の
`$posts = Post::findOrFail($postId);`
が唐突な感じがして少し気になっております

2023-06-28 03:23 UTC, Osk0830 requested changes
お疲れ様でした！
遅くなってすみません。。！

いい感じにできていると思います。
ただ、少しだけ修正した方がよさそうな箇所がありますので、
確認よろしくお願いします！

2023-06-28 03:23 UTC, Osk0830 commented on app/Http/Controllers/CommentController.php
> +        }
- if文の条件に合致しなかった際の処理がないため、仮にそのようなリクエストが入ると画面が真っ白になってしまいますね。

https://gyazo.com/a6bb22b53346e4d944693a278dd9a763

- また、`$postId`はもちろんパラメータとして渡ってきている値なので普通に考えれば投稿のIDで間違いないはずですが、このようなリクエストの場合、このidが間違いなく投稿のidなのかを確認するために一度データを取得してみて、その情報とコメントのpost_idを比較するのが正確だと思われます。（このような検討処理をバリデーション段階で行うことも可能そうですし、そうすることも多いかもしれません。）`$commentId`についても同様のことが言えるかもしれません。

2023-06-28 03:23 UTC, Osk0830 commented on app/Http/Controllers/CommentController.php
> +        }
- こちらはPOST（DELETE）リクエストなので、ブラウザだけでは再現しにくいですが、同様に条件に合致しなかった際の処理が求められます。

- `$postId`などに関しても前述のとおりです。

2023-06-28 03:23 UTC, Osk0830 commented on app/Http/Controllers/CommentController.php
> +    }
- `$postId`などに関して、前述のとおりです。

2023-06-28 08:26 UTC, u0222 commented on app/Http/Controllers/CommentController.php
> +        }
ありがとうございます！バリデーションの方は難しそうだったので、コントローラーの方を修正しております。
また、先ほどの修正に合わせview/comments/の中にコメント関連ファイルを入れております。

2023-06-28 08:26 UTC, u0222 commented on app/Http/Controllers/CommentController.php
> +        }
ありがとうございます！バリデーションの方は難しそうだったので、コントローラーの方を修正しております。
また、先ほどの修正に合わせview/comments/の中にコメント関連ファイルを入れております。

2023-06-28 08:26 UTC, u0222 commented on app/Http/Controllers/CommentController.php
> +    }
ありがとうございます！バリデーションの方は難しそうだったので、コントローラーの方を修正しております。
また、先ほどの修正に合わせview/comments/の中にコメント関連ファイルを入れております。

2023-06-29 00:16 UTC, Osk0830 requested changes
お疲れ様です！
前回レビューでお伝えした部分についてはOKだと思います！

あと少しだけコメントしましたので、
お手数ですが今一度確認いただければと思います。

2023-06-29 00:16 UTC, Osk0830 commented on app/Http/Controllers/CommentController.php
> +        $posts = Post::findOrFail($postId);
`$posts`としている変数には、1つ分のデータしか格納されないので、変数名は単数形がいいですね。

2023-06-29 00:16 UTC, Osk0830 commented on app/Http/Controllers/CommentController.php
> +        if (\Auth::id() === $comment->user_id && $comment->post_id === $posts->id) {
`\Auth::id() === $comment->user_id && $comment->post_id === $posts->id`の部分のように、`長い＆コントローラーの他の箇所でも何度も用いる`ような内容は、コントローラー内に別の関数として定義してあげるのがいいです。

そうしておくと、コントローラー内の他のアクションから、`$this->関数名(引数)`として呼び出せます。

今回のような場合は、諸々のid情報を受け取って確認したい値と等価かをチェックした結果としての真偽値をリターンするような関数にするといいですね。ちょうど、フォロー機能関連の実装時に、User.phpで、このidの人を既にフォローしているかどうかをチェックする関数を作ったところと似ていますね。

2023-06-29 00:16 UTC, Osk0830 commented on app/Http/Controllers/CommentController.php
> +        if (\Auth::id() === $comment->user_id && $comment->post_id === $posts->id) {
こちらもですね。

2023-06-29 00:16 UTC, Osk0830 commented on app/Http/Controllers/CommentController.php
> +        if (\Auth::id() === $comment->user_id && $comment->post_id === $posts->id) {
こちらもですね。

2023-06-29 02:26 UTC, u0222 commented on app/Http/Controllers/CommentController.php
> +        if (\Auth::id() === $comment->user_id && $comment->post_id === $posts->id) {
以下の別の関数を作り、削除・編集・更新でそれぞれ`$this->関数名(引数)`で呼び出しました。
```
    private function isCommentOwner($postId, $commentId)
    {
        $comment = Comment::findOrFail($commentId);
        $post = Post::findOrFail($postId);

        if (\Auth::id() === $comment->user_id && $comment->post_id === $post->id) {
            return true;
        } else {
            return false;
        }
    }
```

2023-06-29 02:26 UTC, u0222 commented on app/Http/Controllers/CommentController.php
> +        if (\Auth::id() === $comment->user_id && $comment->post_id === $posts->id) {
同上です。

2023-06-29 02:27 UTC, u0222 commented on app/Http/Controllers/CommentController.php
> +        if (\Auth::id() === $comment->user_id && $comment->post_id === $posts->id) {
こちらも同様に対応しました。

2023-06-29 02:27 UTC, u0222 commented on app/Http/Controllers/CommentController.php
> +        if (\Auth::id() === $comment->user_id && $comment->post_id === $posts->id) {
こちらも同様に対応しました。

2023-06-29 06:02 UTC, Osk0830 requested changes
お疲れ様です！
いい感じですね！

もう少しだけ可読性を高めたりスマートにできそうな感じがあってコメントしましたので、
確認よろしくお願いします！

2023-06-29 06:02 UTC, Osk0830 commented on app/Http/Controllers/CommentController.php
> +        }
この部分は下記のように1行でも書けますね。こちらのがスマートで一般的に多く使われている気がします。

```
return \Auth::id() === $comment->user_id && $comment->post_id === $post->id;
```

2023-06-29 06:02 UTC, Osk0830 commented on app/Http/Controllers/CommentController.php
> +        if ($this->isCommentOwner($postId, $commentId)) {
少し可読性を良くするために、下記のようにするのがいいかもですね。（他の箇所へのコメントは割愛しますね）

```
$isOwner = $this->isCommentOwner($postId, $commentId);

if  ($isOwner) {...
```

2023-06-29 07:03 UTC, u0222 commented on app/Http/Controllers/CommentController.php
> +        }
ありがとうございます！上記内容で修正させていただきました！

2023-06-29 07:04 UTC, u0222 commented on app/Http/Controllers/CommentController.php
> +        if ($this->isCommentOwner($postId, $commentId)) {
ありがとうございます！上記内容で修正させていただきました！削除、編集、更新それぞれ修正しております^^

2023-07-01 06:16 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらだいぶ見やすくなりましたね！
マージしますね〜！

2023-07-01 06:16 UTC, merged