#422 コメント（ボケ）新着一覧ページ（おおた）
yukihiroLaravel/joint_develop pull request #423
Opened 2023-06-27 07:17 UTC by u0222

## issue
- Closes #422

## 概要
- コメント（ボケ）新着一覧ページ（おおた）

## 動作確認手順
- ヘッダーに追加した「ボケ」から遷移　`/comments`
- コメント（ボケ）新着順で表示されていることを確認（削除・編集ボタンは未実装）
- ヘッダーには「お題」も追加しています。お題からはトップページへ遷移します
- 上記変更に伴い、web.php／header／welcomeファイルも一部修正をしました

## 考慮して欲しいこと
- いいねがマージされたチームのdevelopブランチからブランチを切りました。
　コンフリクト解消後、web.phpで以下の59行目が削除されていてエラーが起きたため復活しました。
        Route::post('{id}/comments', 'CommentController@store')->name('comment.store');

- Comment.phpのモデルファイルでpostsをpostに修正しました
変更前
```
  public function posts()
    {
        return $this->belongsTo(Post::class);
    }

```

変更後（今回のプルリク）
```
  public function post()
    {
        return $this->belongsTo(Post::class);
    }

```

## 確認してほしいこと
- 上記の修正で何かおかしな点があればご指摘をお願いします。

2023-06-28 03:41 UTC, Osk0830 requested changes
お疲れ様でした！
全般的に問題なさそうですね！

一点だけコメントしましたので、
確認よろしくお願いします。

2023-06-28 03:41 UTC, Osk0830 commented on resources/views/new.blade.php
> +@extends('layouts.app')
- こちら細かい話になりますが、`new.blade.php`という名前のBladeが`views`ディレクトリの一番上の階層にポツンと存在することになると、はじめてソースを見た人が何のBladeかすぐに見当つけるのが難しいと思います。まだ、今後機能拡張して、仮に何か他の新着一覧ができた場合にも名前がバッティングするかと思います。新着かどうかは今後変更が生ずる可能性もありますし、中立的に、`/views/comments/index.blade.php`のような感じが無難ではないでしょうか？もちろん、名前は、`new.blade.php`にするのもダメではないと思います。

[![Image from Gyazo](https://i.gyazo.com/883a50ba3a0e2d185ff174247523d718.png)](https://gyazo.com/883a50ba3a0e2d185ff174247523d718)

2023-06-28 04:24 UTC, u0222 commented on resources/views/new.blade.php
> +@extends('layouts.app')
ご確認有難うございました！
おっしゃる通りですね。先々のことも考える必要があること、勉強になりました！

/views/comments/index.blade.phpに修正しました。

また、commentsフォルダができたので、以下ファイルも整理した方が良いかと思い
/views/posts/comment.blade.php　を
/views/comments/comments.blade.php　に移動し、末尾にsをつけてposts/postsと統一しました。

※コントローラーのファイル名も上記を反映して修正しました

2023-06-29 00:27 UTC, Osk0830 approved these changes
お疲れ様です！
こちら整理されてかなり見やすくなりましたね！
マージしますね！

2023-06-29 00:27 UTC, merged