#378 画像投稿(Ninomiya)
yukihiroLaravel/joint_develop pull request #427
Opened 2023-06-28 17:42 UTC by yuki-yuki1

## issue
- Close #378 

## 動作環境手順
ログイン状態で、トップページに移動。①テキストのみ、⓶画像のみ、⓷テキスト及び画像の
3パターンの投稿ができる事を確認する。
テキスト、画像いずれも投稿しない場合はエラーとなる。

## 考慮してほしいこと
画像サイズ(容量)はバリデーションを作成していますが幅はバリデーションを作成しておりません。
共同開発終了までに時間があれば、適切な幅やリサイズされる機能を実装したいと考えています。

## 確認してほしいこと
特にありません。

2023-06-29 00:22 UTC, yukihiroLaravel requested changes
動画などでコメントしました。
ご確認ください！
https://www.loom.com/share/630092cf90854c7eaa27325c6aa1cbb0?sid=14898027-1b2e-48fa-9edf-4697019a4c9d

2023-06-29 00:22 UTC, yukihiroLaravel commented on resources/views/layouts/app.blade.php
> +        <link rel="stylesheet" href="{{ asset('css/style.css') }}">
インデント１つ減らす

2023-06-29 00:22 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
>                      <p class="text-muted">{{ $post->updated_at }}</p>
テキストのみ存在したときに
投稿日時消えないですか？

2023-06-29 00:22 UTC, yukihiroLaravel commented on database/migrations/2023_05_28_114945_create_posts_table.php
> +            $table->string('text')->default('');
いらない？

2023-06-29 00:22 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        }
いらない？

2023-06-29 12:28 UTC, yuki-yuki1 commented on resources/views/layouts/app.blade.php
> +        <link rel="stylesheet" href="{{ asset('css/style.css') }}">
CSSで画像投稿ボタンを装飾しようと考えてリンクを張っていたのですが、そこまで実施しなかったため、一旦削除します。

2023-06-29 12:43 UTC, yuki-yuki1 commented on resources/views/posts/posts.blade.php
>                      <p class="text-muted">{{ $post->updated_at }}</p>
ご指摘頂いた通り、投稿日時が消えるため、修正しました。

2023-06-29 14:52 UTC, yuki-yuki1 commented on database/migrations/2023_05_28_114945_create_posts_table.php
> +            $table->string('text')->default('');
defaultとif分岐を消すと、「textにnullを入れることができない」のエラーが発生しました。

前回試行錯誤した結果、次のように考えます。
検索のルーティング：検索欄が空白の結果が返される。textがnullの投稿は表示されず、それ以外は全て表示。
indexのルーティング：全ての投稿(textがnullの投稿も含む)が表示される。

⓵textにnullableを適用し、画像のみを投稿した場合
検索のルーティングを使用：textがnullのものは表示されない為、投稿が表示されない。
indexのルーティングを使用：textがnullのものも表示される為、投稿が表示される。

⓶textにnullを許容しないようにして、画像のみを投稿した場合
検索のルーティングを使用：「textにnullを入れることができない」エラー。
indexのルーティングを使用：「textにnullを入れることができない」エラー。(今回のdefaultとif分岐を消去したケース)

⓷textにnullを許容しないようにして、default('')とif分岐を作成、画像のみを投稿した場合
検索のルーティングを使用：投稿が表示される。(前回試行錯誤したときのケース)
indexのルーティングを使用：投稿が表示される。(今回のdefaultとif分岐を消去しなかったケース)

defaultとif分岐を消去し、nullableを適用することで⓵のパターンとなり、indexのルーティングを使用すれば
問題は生じません。しかし、空白でキーワード検索すると、画像のみの投稿が表示されなくなるため
今回は⓷のパターン(nullを許容しない、default('')とif分岐を作成)を採用しました。

2023-06-29 14:59 UTC, yuki-yuki1 commented on app/Http/Controllers/PostsController.php
> +        }
if分岐を消去するとtextにnullを入れることができない」のエラーが発生するため、残しています。

2023-06-30 11:58 UTC, yukihiroLaravel approved these changes
コメントしましたので、ご確認願います！🙇‍♂️

2023-06-30 11:58 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        }
かしこまりました！
それなら今の形でいきましょう！

2023-06-30 11:58 UTC, yukihiroLaravel commented on resources/views/posts/new_post.blade.php
> +                <input type="file" name="img_path" placeholder="画像投稿">
上のテキスト入力欄と画像選択フォームとが
くっついているので、少し離すようにしましょう！
お願いします！

2023-06-30 13:37 UTC, yuki-yuki1 commented on resources/views/posts/new_post.blade.php
> +                <input type="file" name="img_path" placeholder="画像投稿">
修正しました。また、投稿するボタンについても、22行目のdivタグ内について、mt-3をmt-5に変更してスペースを大きくしました。

2023-06-30 14:59 UTC, yukihiroLaravel approved these changes
OKです！
マージしました！
おつかれさまでした☺️

2023-06-30 14:59 UTC, merged