コメントページ遷移（あめみや）
yukihiroLaravel/joint_develop pull request #435
Opened 2023-07-02 06:45 UTC by Tomoki-Amemiya

## issue
- Close #421

## 概要
- コメントページの実装
投稿に対するコメントを閲覧するページを作成し、
ページ移動できるようしました。

## 動作確認手順
- 投稿ごとにコメントページがあることを確認
トップページの投稿に対し、
最後にコメントされたコメント１件が表示されていることを確認。
- コメントの下部に設置されているリンク「...さらにコメントを見る 」より、コメントページへ移動。
- コメントページにて投稿に対するコメントが降順に表示されていることを確認。

## 考慮してほしいこと
- 状況に応じて、下記コマンドで動作確認をする必要あり。
php artisan migrate:fresh --seed

## 確認してほしいこと
- 特になし

2023-07-02 07:07 UTC, yukihiroLaravel requested changes
まだ動作確認ができていませんが
現時点で気になる点だけお送りしました。
ご確認ください🙇‍♂️

2023-07-02 07:07 UTC, yukihiroLaravel commented on app/Http/Controllers/CommentsController.php
> +use COM;
これはなんでしょう？

2023-07-02 07:07 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +                                    @if ($comment->user->id == Auth::id())
こちらイコールが２つである理由はありますでしょうか？
可能なら厳密な判定であるイコール３つにした方が
万一のイレギュラー（ないとは思いますがuser->idに文字列の数字が入ってくる場合など）を省けていいですね！

2023-07-02 07:07 UTC, yukihiroLaravel commented on resources/views/comments/comment_list.blade.php
> +        @if ($comment->user->id == Auth::id())
こちらイコールが２つである理由はありますでしょうか？
可能なら厳密な判定であるイコール３つにした方が
万一のイレギュラー（ないとは思いますがuser->idに文字列の数字が入ってくる場合など）を省けていいですね！

2023-07-02 07:21 UTC, Tomoki-Amemiya commented on app/Http/Controllers/CommentsController.php
> +use COM;
ご指摘ありがとうございます。
自分でも追加した記憶がなかったのですが、
なしかしらの操作によって追加されていたのかもしれません。
削除し、再プッシュいたしました。

2023-07-02 07:25 UTC, Tomoki-Amemiya commented on resources/views/posts/posts.blade.php
> +                                    @if ($comment->user->id == Auth::id())
確かに厳密である方がより良いですね。
`($comment->user->id === Auth::id())`へと変更いたしました。

2023-07-02 07:25 UTC, Tomoki-Amemiya commented on resources/views/comments/comment_list.blade.php
> +        @if ($comment->user->id == Auth::id())
確かに厳密である方がより良いですね。
`($comment->user->id === Auth::id())`へと変更いたしました。

2023-07-03 07:38 UTC, Tomoki-Amemiya commented
## issue
- Close #421

## 概要
- コンフリクトの解消

## 動作確認手順
- 前回同様

## 考慮してほしいこと
- 状況に応じて、下記コマンドで動作確認をする必要あり。
php artisan migrate:fresh --seed
- Target class [〇〇〇TableSeeder] does not existのエラーが出た場合下記コマンド必要
composer dump-autoload
上記コマンドでリロードした後に下記コマンドで再作成
php artisan migrate:refresh --seed

## 確認してほしいこと
- 特になし

2023-07-03 11:03 UTC, yukihiroLaravel approved these changes
OKです！
完璧なのでマージしました☺️
おつかれさまでした！

2023-07-03 11:03 UTC, merged