#425 いいね機能（いいね数の表示を含む）（Ninomiya）
yukihiroLaravel/joint_develop pull request #436
Opened 2023-07-02 08:03 UTC by yuki-yuki1

## issue
- Close #425 
## 概要
- 投稿、コメントに「いいね」を押せるよう実装。
- いいねの数が表示される。
## 動作環境手順
ログインしていない時は、いいねボタンは表示されない。いいねの数は表示される。
ログイン後、投稿及びコメントにボタンが表示される。
- いいねしていないものは「いいね！を押す」ボタンが表示され、ボタンを押すといいねの数が１増え
　ボタンが「いいね！を外す」に切り替わる。
- いいね済みのものは「いいね！を外す」ボタンが表示され、ボタンを押すといいねの数が１減り
　ボタンが「いいね！を押す」に切り替わる。
-自分の投稿、コメントにはボタンが表示されない。
## 考慮してほしいこと
ユーザー⇔投稿、ユーザー⇔コメントの関係を一つの中間テーブルに記載し、処理しています。

## 確認してほしいこと
よりスマートな実装方法があれば教えて頂きたいです！

2023-07-02 13:27 UTC, yukihiroLaravel requested changes
少しコメントしましたのでご確認願います！

2023-07-02 13:27 UTC, yukihiroLaravel commented on app/Http/Controllers/FavoriteCommentsController.php
> +    public function storeComment($commentId)
こちら、FavoritePostsとコントローラを分けたので
store() という関数名でいいと思います！
何をstoreするかはファイル名でわかるので！

2023-07-02 13:27 UTC, yukihiroLaravel commented on app/Http/Controllers/FavoriteCommentsController.php
> +    public function destroyComment($commentId)
こちら、FavoritePostsとコントローラを分けたので
destroy() という関数名でいいと思います！
何をdestroyするかはファイル名でわかるので！

2023-07-02 13:27 UTC, yukihiroLaravel commented on app/Http/Controllers/FavoritePostsController.php
> +    public function storePost($postId)
こちら、FavoriteCommentsとコントローラを分けたので
store() という関数名でいいと思います！
何をstoreするかはファイル名でわかるので！

2023-07-02 13:27 UTC, yukihiroLaravel commented on app/Http/Controllers/FavoritePostsController.php
> +    public function destroyPost($postId)
こちら、FavoriteCommentsとコントローラを分けたので
destroy() という関数名でいいと思います！
何をdestroyするかはファイル名でわかるので！

2023-07-02 14:07 UTC, yuki-yuki1 commented on app/Http/Controllers/FavoriteCommentsController.php
> +    public function storeComment($commentId)
store()へ修正しました。関連するルーティングも併せて修正しました。

2023-07-02 14:07 UTC, yuki-yuki1 commented on app/Http/Controllers/FavoritePostsController.php
> +    public function storePost($postId)
store()へ修正しました。関連するルーティングも併せて修正しました。

2023-07-02 14:07 UTC, yuki-yuki1 commented on app/Http/Controllers/FavoriteCommentsController.php
> +    public function destroyComment($commentId)
destroy()へ修正しました。関連するルーティングも併せて修正しました。

2023-07-02 14:08 UTC, yuki-yuki1 commented on app/Http/Controllers/FavoritePostsController.php
> +    public function destroyPost($postId)
destroy()へ修正しました。関連するルーティングも併せて修正しました。

2023-07-03 00:40 UTC, yukihiroLaravel approved these changes
これで完璧でOKです！
難しい部分をおつかれさまでした✨

マージしました！！

2023-07-03 00:40 UTC, merged