#20 フォローによるタイムライン変更（かねこなおき）
yukihiroLaravel/joint_develop pull request #44
Opened 2022-08-25 13:22 UTC by Kaneko0000

## issue 
- Close #20

## 概要
- フォローによるタイムライン変更

## 動作確認手順
- localhost:8080にアクセス、詳細画面で、タブをフォロー、フォロワーに切り替えて、動作確認。

## 考慮してほしいこと
- 詳細画面で「ユーザ情報の編集」がログインしていれば、どのユーザでも表示されるようになってました。ログインしている本人以外のアクセスではエラーが返っていましたが、表示すること自体間違っていると思いました。
- 別のタスクで修正上げるべきかと思いましたが、こちらで修正まで行いました。@auth　→ @if(\Auth::id() === $user->id)に変更して、「ユーザ情報の編集」が、ログインしているユーザの詳細画面のみ表示させるようにしてます。

## 確認してほしいこと
- foreach($users as $user)をusersに入れようとしましたが、showのアクションに$usersを記述する方法がわからず、tabs.blade.php、users.blade.phpに記述しました。
- もっとスマートなまとめ方があるかと思います。アドバイスいただけたらと思います。

2022-08-26 04:54 UTC, Osk0830 requested changes
お疲れ様です！
もう少しですね！
いくつかコメント残しましたので、ご確認ください。

2022-08-26 04:54 UTC, Osk0830 commented on resources/views/users/followers.blade.php
> +        @include('users.users',['users'=>$users])
`['users'=>$users]`は不要ではないでしょうか？

2022-08-26 04:54 UTC, Osk0830 commented on resources/views/users/followers.blade.php
> +            @include('users.tabs',['user'=>$user])
`['user'=>$user]`は不要ではないでしょうか？

2022-08-26 04:54 UTC, Osk0830 commented on resources/views/users/followers.blade.php
> +            @endforeach
ここは、followingsのBladeと共通なので、ぜひ部品化しましょう。

2022-08-26 04:54 UTC, Osk0830 commented on resources/views/users/followings.blade.php
> +        @include('users.users',['users'=>$users])
`['users'=>$users]`は不要ではないでしょうか？

2022-08-26 04:54 UTC, Osk0830 commented on resources/views/users/followings.blade.php
> +            @include('users.tabs',['user'=>$user])
`['user'=>$user]`は不要ではないでしょうか？

2022-08-26 04:54 UTC, Osk0830 commented on resources/views/users/followings.blade.php
> +            @endforeach
ここは、followersのBladeと共通なので、ぜひ部品化しましょう。

2022-08-26 04:54 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +        @include('users.tabs',['user'=>$user])
`['user'=>$user]`は不要ではないでしょうか？

2022-08-26 04:54 UTC, Osk0830 commented on routes/web.php
> +});
このルーティングはログインしている時にだけアクセスできるよう、ミドルウェアを挟みましょう。

2022-08-26 05:54 UTC, Kaneko0000 commented on resources/views/users/followers.blade.php
> +        @include('users.users',['users'=>$users])
消しても何も変わらなかったので、消去します。

2022-08-26 05:54 UTC, Kaneko0000 commented on resources/views/users/followers.blade.php
> +            @include('users.tabs',['user'=>$user])
followingsにアクションに'user' => $userがあったので不要と思い、消去しました。

2022-08-26 05:54 UTC, Kaneko0000 commented on resources/views/users/followings.blade.php
> +        @include('users.users',['users'=>$users])
消去しました。

2022-08-26 05:54 UTC, Kaneko0000 commented on resources/views/users/followings.blade.php
> +            @include('users.tabs',['user'=>$user])
消去しました。

2022-08-26 05:55 UTC, Kaneko0000 commented on resources/views/users/show.blade.php
> +        @include('users.tabs',['user'=>$user])
showアクションに記述があったので不要と思い、消去しました。

2022-08-26 06:00 UTC, Kaneko0000 commented on routes/web.php
> +});
followings、followersをミドルウェアで挟み、アクセスがあればログインするようにしました。

2022-08-26 14:24 UTC, Kaneko0000 commented on resources/views/users/followers.blade.php
> +            @include('users.tabs',['user'=>$user])
消しておきました。

2022-08-26 14:24 UTC, Kaneko0000 commented on resources/views/users/followers.blade.php
> +            @endforeach
新たにファイルを作成して、記述しました。

2022-08-26 14:25 UTC, Kaneko0000 commented on resources/views/users/followings.blade.php
> +            @endforeach
ここも新たにファイルを作成して、記述しました

2022-08-27 02:52 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらマージしますね！

2022-08-27 02:53 UTC, merged