#440 コメント（ボケ）へのいいね機能
yukihiroLaravel/joint_develop pull request #441
Opened 2023-07-03 04:45 UTC by u0222

## issue
- Closes #440

## 概要
- コメント（ボケ）へのいいね機能

## 動作確認手順

＜いいね数（ワロタ）の表示＞
ログイン前
- コメント（ボケ）の下に、ワロタ数が表示されている
- /posts/{id}
- /comments

ログイン後
- コメント（ボケ）の下に、いいね数が表示されている
- /users/{id}/comment_favorites

＜いいね（ワロタ）機能＞
ログイン後
- /posts/{id}　
- 各お題のボケ回答ページで、いいね（ワロタ）ボタンを押下するとワロタ数が増える。ボタンが外すボタンに変わる
- ワロタを外すボタンを押下するとワロタ数が減る。ボタンが元に戻る
- /users/{id}/comment_favorites　ユーザー詳細ページのワロタタブにワロタしたコメントが一覧で表示される

- /comments　
- ボケ新着ページでも上記と同様の動きをする

## 考慮して欲しいこと
- 特にありません

## 確認してほしいこと
- 各メソッドの名称に違和感がないかかくにんいただければありがたいです

2023-07-03 23:08 UTC, Osk0830 requested changes
お疲れ様でした！
イイ感じにできてますね！

少しだけコメントしましたので、確認よろしくお願いします！

2023-07-03 23:08 UTC, Osk0830 commented on app/User.php
> +    }
- Bladeを拝見する限り、ログインしている本人のコメントである場合はイイねできないようにするのが要件のようですので、こちらでもそれをチェックして処理を切り分ける仕組みを組み込んでおきましょう。

2023-07-03 23:08 UTC, Osk0830 commented on app/Http/Controllers/CommentController.php
> +            $post = Post::findOrFail($postId);
- 処理を終えてなかったらすみません。。この行が必要になった理由が何かありましたでしょうか？

2023-07-04 03:56 UTC, u0222 commented on app/Http/Controllers/CommentController.php
> +            $post = Post::findOrFail($postId);
こちらエラー解消の試行錯誤の中で追記したのですが、最終的に不要になった１行でした。
削除を忘れていたたので削除いたしました。

2023-07-04 03:56 UTC, u0222 commented on app/User.php
> +    }
フォロー機能の実装で教えていただいた内容ですね！失念しておりすみません^^;
以下に修正しました。

```
    //コメントへのいいね
    public function commentFavorite($commentId)
    {
        $exist = $this->isCommentFavorite($commentId);
        $itsMe = $this->id === $commentId;
        if ($exist || $itsMe) {
            return false;
        } else {
            $this->commentFavorites()->attach($commentId);
            return true;
        }
    }

    //コメントへのいいねを外す
    public function commentUnFavorite($commentId)
    {
        $exist = $this->isCommentFavorite($commentId);
        $itsMe = $this->id === $commentId;
        if ($exist || $itsMe) {
            $this->commentFavorites()->detach($commentId);
            return true;
        } else {
            return false;
        }
    }
```

2023-07-04 09:05 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKですのでマージしますね！

2023-07-04 09:05 UTC, merged