#43 新規投稿のフラッシュメッセージ（ユウタ）
yukihiroLaravel/joint_develop pull request #46
Opened 2022-08-26 14:33 UTC by yuta2947

## issue
- closed #43 

## 概要
- 新規投稿のフラッシュメッセージ

## 動作確認
- 新規投稿による動作の確認をしました。
- 新規投稿による書き込み失敗の動作確認をしました。手順は以下の通り実行お願いします。
PostController.phpの24行目に下記のコードを入力しlocalhost:8080で投稿を実施してください。
throw new \Exception ();

2022-08-27 03:09 UTC, yukihiroLaravel requested changes
確認しまして、いくつかコメントしましたので、修正願います！☺️

2022-08-27 03:09 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        try{
下記のようにtryの後にスペースを入れましょう！
`try {`

2022-08-27 03:09 UTC, yukihiroLaravel commented on resources/views/commons/flash_message.blade.php
> +@if (session('error_content'))
こちらの@endif ~ @if までの２行を省略して
```
@elseif (session('error_content'))
```
このようにかけると思います。

2022-08-27 04:39 UTC, yuta2947 commented on app/Http/Controllers/PostsController.php
> +        try{
スペースを空けました！

2022-08-27 04:39 UTC, yuta2947 commented on resources/views/commons/flash_message.blade.php
> +@if (session('error_content'))
@endifと@ifを省略し@elseifに書き換えました！

2022-08-27 23:11 UTC, yukihiroLaravel requested changes
１点だけ修正願います！

2022-08-27 23:11 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +            //throw new \Exception;
これは完全に消しておいた方がいいですね！

2022-08-27 23:29 UTC, yuta2947 commented on app/Http/Controllers/PostsController.php
> +            //throw new \Exception;
分かりました！削除します:sweat_drops:

2022-08-29 11:33 UTC, yukihiroLaravel requested changes

2022-08-29 11:33 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +
空行削除

2022-08-29 11:41 UTC, yukihiroLaravel approved these changes
マージしました！

2022-08-29 11:41 UTC, merged