usersテーブル用のマイグレーションファイルに論理削除用のdeleted_atというからむを追加。usersテーブル作成。Seederを…(daiki)
yukihiroLaravel/joint_develop pull request #474
Opened 2023-07-15 17:26 UTC by i-k-i-a-d

…作り、既存のFactoryファイルを使って、ユーザーのテストデータ10件作成。

マイグレーションファイルのupメソッドの中に論理削除のために$table->softDeletes(); を加えましたが、downメソッドの方に、$table->dropColumn('deleted_at');を追加する必要があるかどうか迷っています。

また、自分のチームのメインレビュワーであるHANさんをレビュワーのリストから探しましたが、どの名前がHANさんか判断できず、関さんを指名しております。

よろしくお願いいたします。

2023-07-17 13:55 UTC, Osk0830 requested changes
お疲れ様でした！
連休も重なりレビューが遅くなりすみません。。！

初回タスクで、しっかり理解された上でなおかつチャレンジングに取り組まれていて素晴らしいと思います！

ほぼ問題ないのですが、少しだけコメントしましたので、一度ご検討いただければと思います。

2023-07-17 13:55 UTC, Osk0830 commented on database/factories/UserFactory.php
> +use App\Models\User;
- Laravelの最近のバージョンでは、デフォルトでモデルファイルを`\App\Models`配下に置く仕組みに変更されていますが、今開発に用いているバージョン6ではデフォルトではそのようになっていない状況です。もちろん、このようなディレクトリに置くこと自体は問題ないのですが、これはチームの開発の指針となるべき部分ですし、最初から備わっている他のファイルの記述にも影響する可能性もあります（多分問題ないとは思いますが）ので、熟考の上に決めていただくといいかと思います！

2023-07-17 13:55 UTC, Osk0830 commented on database/seeds/UsersTableSeeder.php
> +        factory(User::class, 10)->create();
- ファクトリーを用いて登録する方法も活用できていて素晴らしいですね！ただ、最初のうちログイン機能のテストを行なったりする上で、ファクトリーで登録されたアドレスやパスワードは幾分使いにくい部分もあると思います。（自分たちで決めた内容でないため）ですので、ファクトリーは今後用いることにして、ダミーのユーザーデータはチームメンバーやレビュワーが誰しも覚えやすいようなものにするともいいかもしれませんね。

2023-07-17 13:55 UTC, Osk0830 commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->softDeletes();
- ご質問にあった `down()`への記載如何の件ですが、今回は`Schema::create()`でテーブルそのものを作成するマイグレーションファイルなので、`down()`は既存の、テーブル削除の内容だけでOKです。カラムを追加するだけのマイグレーションファイルだった場合は、`down()`に当該カラムを削除する指示の記載が必要になってくる感じですね。

2023-07-18 16:08 UTC, i-k-i-a-d commented on database/factories/UserFactory.php
> +use App\Models\User;
これまで自分はLaravel10しか使ったことなかったので、laravel6の仕様に全然ついていけてないですね。今後の課題です。
また、ディレクトリの作成一つでもプロジェクトへ与える影響を考えないといけないと思い知りました。

2023-07-18 16:16 UTC, i-k-i-a-d commented on database/seeds/UsersTableSeeder.php
> +        factory(User::class, 10)->create();
連想配列の形式でSeederだけでもデータを入れられるのは、知っていましたが、今まではFactoryを使ったやり方しか知らなかったので、初めての経験ができ、勉強になりました。
また、テストデータを作り直そうと思い、usersテーブルの中身を全て削除する方法をググりましたが、結局見つけられず、最終的に一度全てテーブルを削除して、再度マイグレーションを実行するというコマンド『php artisan migrate:fresh --seed』を使ってテーブルを作り直しました。するとそのタイミングで、seederで作っていたテストデータも一緒に作られてしまいました。また、二つのデータが入った後に、再度factoryを使って10件のテストデータを作る際に、Seederだけで作ろうとしていた方の処理をコメントアウトせずにやったことで、Emailはユニークで設定DBを設計していたので、二つ同じアドレスを入れようとしてエラーになってしまいました。まだまだ、コマンドを使いこなせていないのと、コマンドの本当の意味が理解できていないのだと思います。

2023-07-20 04:16 UTC, Osk0830 requested changes
お疲れ様でした！
こちらほぼ問題なく修正できていると思います！

シーディングファイルについて少しだけコメントしましたので、
確認よろしくお願いします！

マイグレーション＆シーディングの再実行がうまくいかないなどありましたら、
slackの方か本日のMTG時にでもご相談くださいね！

2023-07-20 04:16 UTC, Osk0830 commented on database/seeds/UsersTableSeeder.php
> +            // ]);
この部分がエラーになったということですかね？email情報は別のものを使っているので問題ないかと思いますが、いかがでしょう？

- シーディングファイルを作る場合、`remember_token`の値は特に入れなくてOKです。
- 逆に、`DB::table()->insert()`メソッドだと、`created_at`と`updated_at`の値がnullになってしまうので、それが入るようにするといいですね。ちなみにですが、モデルの `save()`メソッドを用いる（例：$user = new User() ... $user->save() ）とそれらの値は勝手に入ります。
- パスワードは、上記のように入力せず、`bcrypt()`を用いるか、`Hash::make()`を用いてハッシュ化するようにしましょう。
- また、この部分、情報がほぼ同じなので、`for文のループ`を用いるとよりスマートに書けそうですね。

2023-07-21 13:57 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKなのでマージしますね！

2023-07-21 13:57 UTC, merged