#50 投稿編集のフラッシュメッセージ（ユウタ）
yukihiroLaravel/joint_develop pull request #51
Opened 2022-08-29 06:13 UTC by yuta2947

## issue
- closed #50 

## 概要
- 投稿編集した際フラッシュメッセージが表示される機能を追加

## 動作確認
- localhost:8080/posts/{posts id}/editにアクセスし投稿を編集し更新ボタンを押した際フラッシュメッセージが表示されることを確認しました。
※{posts id}はAdminerから適当なposts idを取得してください。
- PostsController.phpの５２行目に下記のコードを入力し投稿編集処理が失敗した際のフラッシュメッセージの表示を確認しました。
```
throw new \Exception;
```

2022-08-29 11:28 UTC, yukihiroLaravel requested changes
修正願います

2022-08-29 11:28 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +
空行は不要

2022-08-29 11:28 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +
空行不要

2022-08-29 11:28 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +                }
インデント１つ削除すべき

2022-08-29 11:28 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +            $request->session()->flash('content', '投稿を編集しました');
インデント１つ下げるべき

2022-08-29 11:28 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +            $request->session()->flash('error_content', '投稿の編集が失敗しました');
インデント１つ下げるべき

2022-08-29 11:38 UTC, yuta2947 commented on app/Http/Controllers/PostsController.php
> +
了解しました

2022-08-29 11:39 UTC, yuta2947 commented on app/Http/Controllers/PostsController.php
> +
削除しました

2022-08-30 09:02 UTC, yukihiroLaravel approved these changes
OKなので、マージします✨

2022-08-30 09:02 UTC, merged