共通ファイル・ヘッダー・フッター & トップページのタイトルのみ表示「Topic Posts」＃564(NARI)
yukihiroLaravel/joint_develop pull request #590
Opened 2023-07-19 12:41 UTC by yuuya-nari

## issue
- Closes #564 

## 概要
- 共通ファイル・ヘッダー・フッター & トップページのタイトルのみ表示「Topic Posts」

## 動作確認手順

## 考慮してほしいこと

## 確認してほしいこと
- laravel応用講座参考に作成しました。
形は出来ていると思うのですがこれで正しいのか分かりませんので細部まで御確認いただけると幸いです。
宜しくおねがいします。

2023-07-20 14:28 UTC, yukihiroLaravel requested changes
修正願います

2023-07-20 14:28 UTC, yukihiroLaravel commented on config/app.php
> +
空行が不要

2023-07-20 14:28 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +class UsersController extends Controller
ファイル名・クラス名ともに
PostsController
にする

2023-07-20 14:28 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="" class="nav-link text-light">新規ユーザ登録</a></li>
閉じタグ</ul>と
インデント変更

```
<ul class="navbar-nav">
　     <li class="nav-item"><a href="" class="nav-link text-light">ログイン</a></li>
         <li class="nav-item"><a href="" class="nav-link text-light">新規ユーザ登録</a></li>
</ul>
```

2023-07-20 14:28 UTC, yukihiroLaravel commented on resources/views/layouts/app.blade.php
> +          @yield('content')
インデント変更

2023-07-20 14:28 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +    <h5 class="text-center mb-3">"○○"について140字以内で会話しよう！</h5>
```
<div class="center jumbotron bg-info">
        <div class="text-center text-white mt-2 pt-1">
            <h1><i class="fab fa-telegram pr-2000 d-inline"></i>Topic Posts</h1>
        </div>
</div>
<h5 class="text-center mb-3">"○○"について140字以内で会話しよう！</h5>
```

2023-07-20 14:28 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('/', 'UsersController@index');
Route::get('/', 'PostsController@index');

2023-07-21 14:15 UTC, yuuya-nari commented on config/app.php
> +
対処しました。

2023-07-21 14:17 UTC, yuuya-nari commented on app/Http/Controllers/UsersController.php
> +class UsersController extends Controller
対処しました。

2023-07-21 14:18 UTC, yuuya-nari commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="" class="nav-link text-light">新規ユーザ登録</a></li>
閉じタグ追加済み

2023-07-22 08:30 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
修正おつかれさまでした！

2023-07-22 08:30 UTC, merged