posts_migration_seeder修正（クロシン）
yukihiroLaravel/joint_develop pull request #592
Opened 2023-07-22 03:57 UTC by shinken459

## issue
- posts（投稿）テーブルのマイグレーションとシーダー作成

## 概要
-  posts_migration_seeder修正（クロシン）

## 動作確認手順
- 　1️⃣git checkoutでチームブランチに戻る
- 　2️⃣ git pull originで最新の内容を読み込む
- 　3️⃣git checkout -bで新しいブランチに移動する
- 　4️⃣postsのマイグレーションとシーダー作成する
- 　5️⃣git push originでpushする
- adminerで５つのレコードが保存されていることを確認

## 考慮して欲しいこと
- 思考があやふやなまま作業しているため入力内容が合ってるかどうか確認と説明が欲しいです

確認して欲しいこと
-

2023-07-22 08:19 UTC, Osk0830 requested changes
お疲れ様でした！
とても綺麗に書かれていていい感じですね！
もう少しだけ修正が必要そうなので、以下2点、確認お願いします！

①
コードにコメントを付しましたので、確認・対応よろしくお願いします。

②
現在、`database/seeds/DatabaseSeeder.php`に、今回作成したシーディングファイルが登録されていないようです。

[![Image from Gyazo](https://i.gyazo.com/aa03da85528c557d5d7cd9c22b3b03ae.png)](https://gyazo.com/aa03da85528c557d5d7cd9c22b3b03ae)

- こちらに、作成したシーディングクラスを登録
- マイグレーション＆シーディングを実際に実行
- Adminerで、DBにデータがちゃんと登録されているかを確認

してみてくださいね。

2023-07-22 08:19 UTC, Osk0830 commented on database/migrations/2023_07_22_023155_create_posts_table.php
> +        });
- 投稿には必ず投稿者が存在するかと思います。投稿テーブルの各レコードには、誰が投稿したのかが分かるようにするためのカラムが必要になります。投稿はユーザー登録しているユーザーがするもので、そのユーザー情報は `users`テーブルで管理されているので、投稿テーブルの方では、idが何番のユーザーが投稿したものかだけが分かるように情報が格納されていればOKですね。
- その際、そのカラムに入り得る値は`users`テーブルに存在するidの値ではならないため、それ以外の値は許されないよう「外部キー制約」をつけてあげる必要があります。

2023-07-22 08:19 UTC, Osk0830 commented on database/seeds/PostsTableSeeder.php
> +    }
- マイグレーションで追加したユーザー情報を管理するカラムにも値を入れるよう追記してくださいね。

2023-07-22 12:22 UTC, shinken459 commented on database/seeds/PostsTableSeeder.php
> +    }
こんばんは　

ご指摘ありがとう御座います
ここ以外はなんとかなりそうですが、カラムに値をつけるというのはどうしたらいいいか分かりません。

よろしくお願いします

2023-07-25 01:00 UTC, Osk0830 requested changes
お疲れ様です。
いい感じに修正できましたね！

少しだけコメントしましたので、確認よろしくお願いします！

2023-07-25 01:00 UTC, Osk0830 commented on database/seeds/PostsTableSeeder.php
> +            //return $this->hasMany(Posts::class);
こちらは不要なコードだと思いますので、コメントアウトではなく削除しましょう。

2023-07-25 01:00 UTC, Osk0830 commented on database/migrations/2023_07_22_023155_create_posts_table.php
> +            $table->softDeletes();
こちらは、論理削除（ソフトデリート）という機能を用いるためのカラムですが、現段階では使うかどうか不明なので、一旦はコメントアウトするか削除しといても良さそうです。

2023-07-26 09:42 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらしっかり修正できているのでマージしますね！
引き続き頑張っていきましょう！

2023-07-26 09:44 UTC, merged