#566　共同開発チームa　users（ユーザ）テーブルのマイグレーションとシーダー作成（seiichi）
yukihiroLaravel/joint_develop pull request #593
Opened 2023-07-22 13:35 UTC by seiichi15

##issue
- #566 

##概要
- users（ユーザ）テーブルのマイグレーションとシーダー作成

##確認してほしいこと
- for文を使って書きましたが問題ないか（Adminerでは表示確認しています）
``` 
for ($i=1; $i <= 3; $i++){
         DB::table('users')->insert([
            'name' => 'test'.$i,
            'email' => 'test'.$i.'@test.com',
            'password' => bcrypt('test'.$i)
        ]);
        }  
```

2023-07-22 16:38 UTC, yukihiroLaravel requested changes
おおむねいい感じなので
一部のみ修正ねがいます☺️
ご確認ください！

2023-07-22 16:38 UTC, yukihiroLaravel commented on database/seeds/UsersTableSeeder.php
> +        }
書き方はいい感じです！
ただ、インデントがおかしいので、下記のように修正願います！

```
for ($i=1; $i <= 3; $i++){
         DB::table('users')->insert([
                  'name' => 'test'.$i,
                  'email' => 'test'.$i.'@test.com',
                  'password' => bcrypt('test'.$i)
        ]);
}  
```

2023-07-22 16:38 UTC, yukihiroLaravel commented on database/seeds/UsersTableSeeder.php
> +        }
上記について、インデントのスペースの個数が反映できていませんが
インデントはスペース１つ分にしてくださいね！

2023-07-25 13:26 UTC, seiichi15 commented
##issue
- users（ユーザ）テーブルのマイグレーションとシーダー作成♯566

##概要
- インデントの修正

##確認してほしいこと
- インデントの修正箇所等の確認をお願いします。

2023-07-27 14:05 UTC, yukihiroLaravel approved these changes
マージします！

2023-07-27 14:05 UTC, merged