ログインフォーム・
yukihiroLaravel/joint_develop pull request #595
Opened 2023-07-23 09:57 UTC by i-k-i-a-d

…・ログアウトができるように実装。またヘッダーにユーザー名が表示されるように実装。バリデーションメッセージが表示されるように、バリデーションメッセージようのテンプレートファイル作成。

2023-07-23 12:19 UTC, Osk0830 requested changes
お疲れ様でした！
全般的に良くできていると思います。

少しだけコメントしましたので、確認よろしくお願いします！

2023-07-23 12:19 UTC, Osk0830 commented on resources/views/auth/login.blade.php
> +                <input id="email" type="text" class="form-control" name="email" value="">
こちら、ユーザビリティの観点から、バリデーションに弾かれた際に既存の入力内容が表示されるようにした方が良さそうですね。

2023-07-23 12:19 UTC, Osk0830 commented on resources/views/layouts/layout.blade.php
> +        <meta name="csrf-token" content="{{ csrf_token() }}">
これは、すべてのBladeで必要なものではないので、formでPOST送信しなければならない箇所だけにあっても良さそうですね

2023-07-24 18:40 UTC, i-k-i-a-d commented on resources/views/auth/login.blade.php
> +                <input id="email" type="text" class="form-control" name="email" value="">
old関数を使って実装してみました。これはセキュリティ上の都合だと思いますが、passwordの方には効果がないですよね？

2023-07-24 18:41 UTC, i-k-i-a-d commented on resources/views/layouts/layout.blade.php
> +        <meta name="csrf-token" content="{{ csrf_token() }}">
該当箇所を削除しました。ただ一点公式ドキュメントに記載されている内容で気になった点があるので、slackで質問させていただきました。

2023-07-25 01:01 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKなのでマージしますね〜

2023-07-25 01:01 UTC, merged