トップページの投稿表示実装(DAIKI)
yukihiroLaravel/joint_develop pull request #597
Opened 2023-07-26 17:29 UTC by i-k-i-a-d

…が表示されるように実装。またページネーション機能も実装。PostControllerで、postsテーブルから投稿データを全て取得しtop.blade.phpファイルへ値を引き継げるように実装。

おそらく、ユーザーのアバター画像はユーザー詳細・編集・更新のところでの実装になると思い、今回は実装に含んでおりませんが大丈夫でしょうか。

2023-07-27 13:24 UTC, Osk0830 requested changes
お疲れ様です！
大枠では概ね良くできていると思います。

いくつか修正事項をコメントしましたので、
確認よろしくお願いします！

2023-07-27 13:24 UTC, Osk0830 commented on app/Http/Controllers/PostController.php
> +        $posts = DB::table('posts')->paginate(10);
- コントローラーでこのようなデータを取得してくる際は、基本的にモデルのメソッドを使う形が一般的ですので、その方法に統一しましょう。
- その際、データが、投稿日が新しいものから古いものへと並ぶようにしてください。

2023-07-27 13:24 UTC, Osk0830 commented on resources/views/posts/top.blade.php
> +                <p class="mt-3 mb-0 d-inline-block"><a href="">{{ App\User::find($post->user_id)->name }}</a></p>
- こちらの記述もモデルのリレーションメソッドを用いる方法で書くのがスマートですので、その方法に変更してみてください。

2023-07-27 13:24 UTC, Osk0830 commented on resources/views/posts/top.blade.php
> +                    <p class="text-muted">{{ $post->updated_at }}</p>
- こちら要件が不明瞭ではありますが、更新日ではなく初回投稿日でOKそうです。おそらくデータの並び順との兼ね合いからもそれがいいと思います。

2023-07-27 13:24 UTC, Osk0830 commented on resources/views/posts/top.blade.php
> +                </div> -->
- こちらはコメントアウトするのではなく、投稿者本人の投稿であった場合のみ表示される仕組みにしましょう。

2023-07-27 13:24 UTC, Osk0830 commented on resources/views/posts/top.blade.php
> +                <img class="mr-2 rounded-circle" src="" alt="ユーザのアバター画像">
- この段階でアバター画像も表示できるようにしておきましょう。そのための必要な手順はSlackで別途お伝えしますね。

2023-07-28 15:46 UTC, i-k-i-a-d commented on app/Http/Controllers/PostController.php
> +        $posts = DB::table('posts')->paginate(10);
自分の知識はいろいろ試しながらググりながら身に着けたたたき上げの知識なので、動きはするけど、あまり一般的ではない記述というのが、まだまだ自分では判断が付きません。

2023-07-28 15:49 UTC, i-k-i-a-d commented on resources/views/posts/top.blade.php
> +                <p class="mt-3 mb-0 d-inline-block"><a href="">{{ App\User::find($post->user_id)->name }}</a></p>
これについても、仕組み上動きはするけど、一般的ではないという発想自体ありませんでした。

2023-07-28 15:50 UTC, i-k-i-a-d commented on resources/views/posts/top.blade.php
> +                    <p class="text-muted">{{ $post->updated_at }}</p>
更新日の方がリアルタイムな感じがしてベターだと思って、このように書いたんですが浅知恵でした。

2023-07-28 15:51 UTC, i-k-i-a-d commented on resources/views/posts/top.blade.php
> +                </div> -->
ログインしたユーザーにしか表示されない仕組みとは気が付きませんでした。後々実装していくものと勝手に思い込んでました。

2023-07-28 15:52 UTC, i-k-i-a-d commented on resources/views/posts/top.blade.php
> +                <img class="mr-2 rounded-circle" src="" alt="ユーザのアバター画像">
Gravatorというサービス自体知らなかったんですが、これはウェブエンジニアにとっては常識的な外部サービスなんでしょうか？？

2023-07-30 05:52 UTC, Osk0830 commented on resources/views/posts/top.blade.php
> +                <img class="mr-2 rounded-circle" src="" alt="ユーザのアバター画像">
使うかどうかは別にして、知ってる人はまぁまぁいるって感じな気がします。。

2023-07-30 06:09 UTC, Osk0830 requested changes
お疲れ様です！
いい感じに修正できていると思います！

少しだけコメントしましたので、
確認よろしくお願いします！

2023-07-30 06:09 UTC, Osk0830 commented on resources/views/posts/top.blade.php
> +                <p class="mt-3 mb-0 d-inline-block"><a href="">{{ $post->user->find($post->user_id)->name }}</a></p>
- この部分、`$post->user`で投稿者のモデルのインスタンスを取得できるので、その`name`や`email`プロパティにアクセスして、`$post->user->name`などのように値を取れると思いますがいかがでしょう？

2023-07-30 06:09 UTC, Osk0830 commented on resources/views/posts/top.blade.php
> +                @endif
- 不要な空行はなくしましょう。（42行目）
- また、`@if ... @endif`の中は、入れ子関係であることが分かるようにインデントを一つ下げた方が良さそうですね。

2023-08-07 15:22 UTC, yukihiroLaravel approved these changes
さきほどZoom作業会で話してみて
問題ないと思いますので
マージしました！

おつかれさまでした！！

2023-08-07 15:24 UTC, merged