Usersテーブル・マイグレーション・シーダー実装
yukihiroLaravel/joint_develop pull request #599
Opened 2023-07-29 04:15 UTC by aaaperfect

## 概要
- Usersテーブル・マイグレーション・シーダー実装

## 動作確認
- 確認済

2023-07-29 12:26 UTC, yukihiroLaravel requested changes
１点だけコメントしました！

2023-07-29 12:26 UTC, yukihiroLaravel commented on database/seeds/UsersTableSeeder.php
> +        ]);DB::table('users')->insert([
ここだけ改行できていないので直しましょう！

2023-07-30 01:02 UTC, aaaperfect commented on database/seeds/UsersTableSeeder.php
> +        ]);DB::table('users')->insert([
修正完了しました！

2023-07-30 12:55 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
お疲れ様でした！

2023-07-30 12:55 UTC, merged