ログイン・ログアウト・新規ユーザー登録の実装
yukihiroLaravel/joint_develop pull request #600
Opened 2023-07-29 04:49 UTC by aaaperfect

## 概要
- ログイン・ログアウト・新規ユーザー登録の実装
- ルーチング作成等

## 動作確認
- ログイン・ログアウト・新規ユーザー登録確認済

## 不明点
- バリデーションエラーでemail→メールアドレスと表示する方法
- バリデーションエラーでのwidthの調整
- クラス属性でmt-3と指定しても上余白の調節ができなかった

## 現在出ているエラー
- users/users.blade.phpの23行目でTrying to get property 'text' of non-object

2023-07-29 12:40 UTC, yukihiroLaravel requested changes
いろいろコメントしましたので、ご確認ください！

`クラス属性でmt-3と指定しても上余白の調節ができなかった`
こちらに関しては、どこのことかわかりませんが
例えば真上にmb-4とかの領域があるとマージンどうし重なってしまいますので
パディングに変えて、pt-3などとするとうまくいくかもしれません！

2023-07-29 12:40 UTC, yukihiroLaravel commented on resources/views/users/users.blade.php
> +                </div>
全体的にですが、お手本ではこのように
ユーザーの最後の投稿だけを表示するようにはなっておらず、
投稿されたものを順番にすべて表示する形になっています！

2023-07-29 12:40 UTC, yukihiroLaravel commented on resources/lang/ja/validation.php
> +    'attributes' => [],
ご質問の件が、バリデーションでemailなどを日本語化する方法という意味を言われているなら
下記の内容をここに書き込めばOKです！

```
'attributes' => [
        'name' => '名前',
        'email' => 'メールアドレス',
        'password' => 'パスワード',
 ],
```

2023-07-29 12:40 UTC, yukihiroLaravel commented on resources/views/auth/register.blade.php
> +        <div class="col-sm-6 offset-sm-3">
たぶん、エラ〜メッセージをここに入れたらwidthがうまくいくと思います
`@include('commons.error_messages')`

2023-07-30 02:07 UTC, aaaperfect commented on resources/views/auth/register.blade.php
> +        <div class="col-sm-6 offset-sm-3">
ご指摘ありがとうございます。
修正完了しました！

2023-07-30 02:07 UTC, aaaperfect commented on resources/lang/ja/validation.php
> +    'attributes' => [],
ありがとうございます。
追加しました！

2023-07-30 02:24 UTC, aaaperfect commented on resources/views/users/users.blade.php
> +                </div>
上記７行目の
$post = $user->posts->last();を
$post = $user->posts();に変更しましたが、

これでは投稿されたものを順番にすべて表示する形になっていないと思います。

コントローラーでは$users = User::orderBy('id','desc')->paginate(9);としているので、
ユーザーが100人いたとしたら（1番目が古い、100番目が新しい）
100番目の人の投稿が一番先頭に来ると思っております。

今回の修正で投稿されたものを順番にすべて表示する形になっていなければ、
ヒントをいただいてもよろしいでしょうか？

2023-09-17 23:56 UTC, closed without merging