ユーザー詳細表示、編集機能等の実装
yukihiroLaravel/joint_develop pull request #601
Opened 2023-07-29 04:58 UTC by aaaperfect

## 概要
- ユーザー詳細表示、編集機能等の実装

## 動作確認
- 未確認

2023-07-29 12:48 UTC, yukihiroLaravel requested changes
いくつかコメントしました！

2023-07-29 12:48 UTC, yukihiroLaravel commented on resources/views/posts/edit.blade.php
> +            <textarea id="content" class="form-control" name="text" rows="6"></textarea>
質問の件、ここのことですかね？
であれば、
```
<textarea id="content" class="form-control" name="text" rows="6">{{  old('text', $post->text) }}</textarea>
```
などとすると編集前の値が表示されます！

2023-07-29 12:48 UTC, yukihiroLaravel commented on resources/views/users/edit.blade.php
> +            <input class="form-control" value="{{ Auth::user()->name }}" name="name" />
他の部分もですが、
`{{  old('name', Auth::user()->name) }}`
みたいに書かないとバリデーションエラー時に
入力値が消えちゃうのでイケないですね！

2023-07-30 01:19 UTC, aaaperfect commented on resources/views/users/edit.blade.php
> +        <input type="hidden" name="id" value="" />
質問の件はこちらになります。
モックのvalue属性の値が空で、
調べたのですが、何を書くべきか分かりませんでした。

2023-07-30 01:26 UTC, aaaperfect commented on resources/views/users/edit.blade.php
> +            <input class="form-control" value="{{ Auth::user()->name }}" name="name" />
ご指摘ありがとうございます！
修正完了しました。

2023-07-30 01:27 UTC, aaaperfect commented on resources/views/posts/edit.blade.php
> +            <textarea id="content" class="form-control" name="text" rows="6"></textarea>
勉強になります！
こちらのコードも追加しました！

2023-07-30 13:23 UTC, yukihiroLaravel requested changes

2023-07-30 13:23 UTC, yukihiroLaravel commented on resources/views/users/edit.blade.php
> +        <input type="hidden" name="id" value="" />
不要

2023-09-17 23:56 UTC, closed without merging