#2 Poststable、マイグレーション・シーダー実装
yukihiroLaravel/joint_develop pull request #603
Opened 2023-08-01 08:22 UTC by aaaperfect

## 概要　
- Poststable、マイグレーション・シーダー実装

## 動作確認
- データベースにデータが登録されてことを確認

2023-08-01 11:05 UTC, yukihiroLaravel requested changes
修正箇所をご連絡しました！

2023-08-01 11:05 UTC, yukihiroLaravel commented on database/migrations/2023_08_01_073127_create_posts_table.php
> +            $table->string('text')->nullable();
textがnullだと投稿すらできない仕様だと思いますので
nullableは不要です！

2023-08-01 11:05 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +        ]);
ぺージネーションも確認したいので11個以上投稿を作ってみましょう。
user_id も存在しないuser_idをつくるとエラーになるのでお気をつけください！

2023-08-02 01:35 UTC, aaaperfect commented on database/migrations/2023_08_01_073127_create_posts_table.php
> +            $table->string('text')->nullable();
修正完了しました！

2023-08-02 01:39 UTC, aaaperfect commented on database/seeds/PostsTableSeeder.php
> +        ]);
12個データを入れました。
データベースをいじったり、database/seeds/UsersTableSeeder.phpにも６個データを追加しました！
php artisan db:seedコマンドでデータベースへのデータの登録はできました！

2023-08-02 01:40 UTC, aaaperfect commented on database/seeds/PostsTableSeeder.php
> +        ]);
12個データを入れました。
データベースをいじったり、database/seeds/UsersTableSeeder.phpにも６個データを追加しました！
php artisan db:seedコマンドでデータベースへのデータの登録はできました！

2023-08-02 13:25 UTC, yukihiroLaravel requested changes
コメントしました！

2023-08-02 13:25 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +            'user_id' => '18',
ユーザーが１２人しかいない状態だとuser_idは
1~12までしか通常だといないということになるので
user_id が 18から始まったら

php artisan migrate:fresh --seed

などをやった人は、絶対にエラーになるので
このpostsTableSeederのuser_idは1~12まで（重複してもOK）
にしましょう

2023-08-03 03:48 UTC, aaaperfect commented on database/seeds/PostsTableSeeder.php
> +            'user_id' => '18',
修正完了しました！

2023-08-03 05:00 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！

2023-08-03 05:00 UTC, merged