#5 ユーザログイン・ログアウト
yukihiroLaravel/joint_develop pull request #606
Opened 2023-08-01 08:31 UTC by aaaperfect

# 概要
- ユーザログイン・ログアウト

# 動作確認
- 確認済

2023-08-04 11:57 UTC, aaaperfect commented on resources/views/auth/login.blade.php
> +                <input id="password" type="password" class="form-control" name="password" value="{{ old('password') }}">
type属性がpasswordだと、value属性でold関数を使っても、入力値の値を保持できないのですが、
type属性がpasswordの場合は、value属性でold関数を使っても、使わなくてもどちらでもOKという認識で
いいのでしょうか？

2023-08-04 13:10 UTC, yukihiroLaravel commented on resources/views/auth/login.blade.php
> +                <input id="password" type="password" class="form-control" name="password" value="{{ old('password') }}">
こちらはセキュリティの関係上、
原則保持できない方がいいので、
old関数やvalue自体削除しておいた方がいいです！

2023-08-04 13:11 UTC, yukihiroLaravel requested changes
１点だけコメントしましたので、ご確認ください！

2023-08-04 13:18 UTC, aaaperfect commented on resources/views/auth/login.blade.php
> +                <input id="password" type="password" class="form-control" name="password" value="{{ old('password') }}">
修正完了しました！

2023-08-05 02:07 UTC, yukihiroLaravel approved these changes
OKですのでマージしました！
おつかれさまでした！！

2023-08-05 02:07 UTC, merged