#7 トップページの投稿表示
yukihiroLaravel/joint_develop pull request #608
Opened 2023-08-01 08:39 UTC by aaaperfect

# 動作確認
- 動いてはいるが、編集や削除ボタンを正しく表示できませんでした。

# 不明点
- @endforeachを入れる箇所やfor文やif文も検討したが、編集や削除ボタンを正しく表示できませんでした。

# エラーが出てしまう箇所
- if文でAuth::id()＝Auth::user()->idとするとUndefined class constant 'id'と出てしまった。

2023-08-01 08:41 UTC, aaaperfect commented on resources/views/users/posts.blade.php
> +                @endforeach
23行目の@endforeachを30行目以降の場所に入れるとレイアウトが崩れていまいました。

2023-08-01 11:15 UTC, yukihiroLaravel requested changes
気になる部分をコメントしました。
ご確認下さい！

2023-08-01 11:15 UTC, yukihiroLaravel commented on resources/views/users/posts.blade.php
> +                @endphp
これをやらなくて、消していいかと思います

2023-08-01 11:15 UTC, yukihiroLaravel commented on resources/views/users/posts.blade.php
> +                @foreach ($users as $user)
このforeachも不要

2023-08-01 11:15 UTC, yukihiroLaravel commented on resources/views/users/posts.blade.php
> +                <img class="mr-2 rounded-circle" src="{{ Gravatar::src($user->email, 55) }}" alt="ユーザのアバター画像">
上記を消す代わりに、
`$post->user->email`
もしくは
`$post->user()->email`
こんな感じで値を持って来れます。

他の$user-> としている部分も同様です

2023-08-01 11:15 UTC, yukihiroLaravel commented on resources/views/users/posts.blade.php
> +                @endforeach
@endforeach
の場所は、
32行目あたりになるかな、と思います。

2023-08-01 11:15 UTC, yukihiroLaravel commented on resources/views/users/posts.blade.php
> +                    </div>
これらの削除・編集ボタンは
投稿した本人のみに表示しないといけない仕様ですので
今のままだとダメかと思います。

またこのタスクでは削除・編集機能まで含んでいないので、一旦この記述は取り除いておいてもいいと思います。

2023-08-02 01:42 UTC, aaaperfect commented on resources/views/users/posts.blade.php
> +                @endphp
消しました！

2023-08-02 01:43 UTC, aaaperfect commented on resources/views/users/posts.blade.php
> +                @foreach ($users as $user)
消去しました。

2023-08-02 01:43 UTC, aaaperfect commented on resources/views/users/posts.blade.php
> +                <img class="mr-2 rounded-circle" src="{{ Gravatar::src($user->email, 55) }}" alt="ユーザのアバター画像">
ありがとうございます！
問題なく取得できました。

2023-08-02 01:47 UTC, aaaperfect commented on resources/views/users/posts.blade.php
> +                    </div>
この記述を入れたまま、このブランチを元に、新しいブランチを６個作成してしまったのですが、取り除いた方がいいのでしょうか？

2023-08-02 02:06 UTC, aaaperfect commented on resources/views/users/posts.blade.php
> +                @endforeach
色々試してみましたが、レイアウトがうまくいきません。
モックには入っていない、bootstrapのコードやHMTLのコードを追加するのでしょうか？

2023-08-02 13:27 UTC, yukihiroLaravel commented on resources/views/users/posts.blade.php
> +                    </div>
最終的には取り除かないとイケないですが、
このブランチがマージされてから、最新のdevelopを各ブランチにマージしていけば
自動的に取り除かれると思います

2023-08-05 06:09 UTC, aaaperfect commented on resources/views/welcome.blade.php
> +                    <button type="submit" class="btn btn-primary mb-3">投稿する</button>
お手本サイトのソースとは異なりますが、こちらのmb-3で投稿するボタンの下に余白を入れました。

2023-08-05 06:11 UTC, aaaperfect commented on resources/views/users/posts.blade.php
> +                    </div>
かしこまりました！

2023-08-05 07:26 UTC, yukihiroLaravel requested changes

2023-08-05 07:26 UTC, yukihiroLaravel commented on resources/views/users/posts.blade.php
> +<ul class="list-unstyled">
このファイルがある場所がusersフォルダ内なのはおかしいですね。
（userとは直接関係が薄いファイルなので）
postsフォルダ内の方が自然なので
フォルダ名を変えましょう！

2023-08-05 07:58 UTC, aaaperfect commented on resources/views/users/posts.blade.php
> +<ul class="list-unstyled">
修正完了しました！

2023-08-05 11:43 UTC, yukihiroLaravel requested changes
１つコメントしました、それと

>色々試してみましたが、レイアウトがうまくいきません。
>モックには入っていない、bootstrapのコードやHMTLのコードを追加するのでしょうか？

これはすでに解決されましたでしょうか？

2023-08-05 11:43 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $posts = Post::orderBy('created_at','desc')->paginate(9);
postsシーダーが同一時刻で保存されているので表示が降順となっていないですね。
下記のようにすれば問題ないと思います！

`Post::orderBy('id,'desc')`

2023-08-05 12:01 UTC, aaaperfect commented on app/Http/Controllers/UsersController.php
> +        $posts = Post::orderBy('created_at','desc')->paginate(9);
ありがとうございます。
postsテーブルのidが新しい方から表示されるようになりました！

2023-08-05 16:28 UTC, yukihiroLaravel approved these changes
OKですのでマージしました！！

2023-08-05 16:28 UTC, merged