#8 ユーザ詳細
yukihiroLaravel/joint_develop pull request #610
Opened 2023-08-02 11:43 UTC by aaaperfect

# 概要　
- ユーザ詳細

# 不明点
- ユーザー名を押した後に各ユーザの詳細画面に移動した後、
タイムラインの下にログインユーザの投稿一覧や削除ボタン、編集ボタンを表示できなかった。

- コントローラでログインユーザの投稿一覧を変数で定義し、
変数を渡して表示しようとしたが、エラーが出てしまった。
（コード上ではコメントアウトしています）

- この方法だと削除ボタン、編集ボタンを表示出来ないため、

- ログインユーザの投稿一覧と削除ボタンと編集ボタンで
１つのビューファイルを作り、includeする方法なのかと
思っています。（まだこちらは試しておりません。）

2023-08-06 01:30 UTC, aaaperfect commented on app/Http/Controllers/UsersController.php
> +        $posts = $user->posts()->orderBy('id', 'desc')->paginate(9);
自分へのコメント

ここがポイント！

$posts = Post::orderBy('id','desc')->paginate(9);でも表示はできるが、
これだとトップページと同じ表示になってしまう。

  $user = User::findOrFail($id);
  $posts = $user->posts()->orderBy('id', 'desc')->paginate(9);とすることで、クリックされたユーザーの投稿のみを取得できる。つまり$idにusersテーブルのidカラムの値が渡されるため、$user->posts()でその特定のユーザの投稿一覧を取得している。

2023-08-06 03:59 UTC, aaaperfect commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="{{ route('user.show', Auth::id()) }}" class="nav-link text-light">{{ Auth::user()->name }}</a></li>
Auth::id()はAuth::user()->idに変更しても問題なく表示されました。
Auth::user()->nameはAuth::name()にするとMethod Illuminate\Auth\SessionGuard::name does not exist. 
というエラーが発生しました。

2023-08-06 14:45 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="{{ route('user.show', Auth::id()) }}" class="nav-link text-light">{{ Auth::user()->name }}</a></li>
これはシンプルに
Auth::id() でid()という関数はLaravelに備え付けであっても
name()という関数は備え付けで存在しないからですね

2023-08-06 15:12 UTC, yukihiroLaravel requested changes
概ねOKですが、一部コメントしました！

2023-08-06 15:12 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +            <p class="mt-3 mb-0 d-inline-block"><a href="{{ route('user.show',$post->user->id) }}">{{ $post->user->name }}</a></p>
カンマのあとに１つスペースを入れましょう
`{{ route('user.show', $post->user->id) }}`

2023-08-06 15:12 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="" class="nav-link {{ Request::is() ? 'active' : '' }}">タイムライン</a></li>
タブの中身が入力されていないので、
タイムラインが表示中のときにお手本のように
表示中のタブとして表示されていないですね

2023-08-06 23:33 UTC, aaaperfect commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="{{ route('user.show', Auth::id()) }}" class="nav-link text-light">{{ Auth::user()->name }}</a></li>
承知しました。

2023-08-06 23:33 UTC, aaaperfect commented on resources/views/posts/posts.blade.php
> +            <p class="mt-3 mb-0 d-inline-block"><a href="{{ route('user.show',$post->user->id) }}">{{ $post->user->name }}</a></p>
修正完了しました！

2023-08-06 23:34 UTC, aaaperfect commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="" class="nav-link {{ Request::is() ? 'active' : '' }}">タイムライン</a></li>
すみません、見落としておりました。
修正完了しました！

2023-08-06 23:38 UTC, aaaperfect commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="{{ route('user.show', $user->id) }}" class="nav-link {{ Request::is('user/'. $user->id) ? 'active' : '' }}">タイムライン</a></li>
現時点では使いませんが、フォロー機能とフォロワー機能を実装後に利用すると思い{{ route('user.show', $user->id) }}を追加しました。

2023-08-07 01:44 UTC, yukihiroLaravel approved these changes

2023-08-07 01:45 UTC, merged