#10 投稿新規作成
yukihiroLaravel/joint_develop pull request #612
Opened 2023-08-02 11:57 UTC by aaaperfect

# 概要
- 投稿新規作成

# 動作確認
- 投稿するボタンを押して、きちんと投稿できていることを確認

2023-08-07 12:00 UTC, aaaperfect commented on resources/views/welcome.blade.php
> +        <form method="POST" action="{{ route('post.store') }}" class="d-inline-block w-75">
route('post.store')の前後にも半角スペースは入れるべきでしょうか？

2023-08-08 03:10 UTC, yukihiroLaravel requested changes
コメントしました！

お手本サイト
https://laravel-fly2.fly.dev/
こちらでは下記のように問題なく文字数制限が出ましたがどうでしょうか？

下記は今バグっている箇所があるっぽく今は使わない方がいいかもしれません
https://laravel-fly.fly.dev/

<img width="1193" alt="スクリーンショット 2023-08-08 12 06 30" src="https://github.com/yukihiroLaravel/joint_develop/assets/93365035/26371210-9d11-4fe0-9991-a841b90cbb4c">

2023-08-08 03:10 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +        <form method="POST" action="{{ route('post.store') }}" class="d-inline-block w-75">
今の書き方でOKです！！

2023-08-08 03:10 UTC, yukihiroLaravel commented on routes/web.php
> +Route::post('post', 'PostsController@store')->name('post.store');
こちらログイン時にしかできたらダメなルーティングなので
`Route::group(['middleware' => 'auth'], function () {}`
このカッコの中に入れましょう

2023-08-08 03:26 UTC, aaaperfect commented on resources/views/welcome.blade.php
> +        <form method="POST" action="{{ route('post.store') }}" class="d-inline-block w-75">
承知しました。

2023-08-08 03:26 UTC, aaaperfect commented on routes/web.php
> +Route::post('post', 'PostsController@store')->name('post.store');
修正完了しました！

2023-08-08 06:02 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！

2023-08-08 06:02 UTC, merged