#11 投稿編集画面・更新
yukihiroLaravel/joint_develop pull request #613
Opened 2023-08-02 12:00 UTC by aaaperfect

# 概要
- 投稿編集画面・更新

# 動作確認
- きちんと表示され、更新できたことを確認

2023-08-08 11:47 UTC, aaaperfect commented on routes/web.php
> +        Route::get('{id}/update', 'UsersController@index');
Route::get('{id}/update', 'UsersController@index');
こちらを追加する前は、更新後に２ページ目に行こうとすると

Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
The GET method is not supported for this route. Supported methods: PUT.

というエラーが発生しました。

つまりここではwelcomeのビューは返せたが、getメソッドがないと
welcomeのビューを正常に読み込むことができないので、
ページネーションが正しく機能しなかったということでしょうか？

2023-08-08 15:47 UTC, yukihiroLaravel requested changes

2023-08-08 15:47 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        return view('welcome', [
return redirect('/');

2023-08-09 02:24 UTC, aaaperfect commented on resources/views/posts/editbutton.blade.php
> +@endif
if文の中の2~7行目にインデントを入れるべきか迷ったのですが、
入れる方が適切でしょうか？

2023-08-09 02:29 UTC, aaaperfect commented on app/Http/Controllers/PostsController.php
> +        return view('welcome', [
ありがとうございます！

2023-08-09 06:22 UTC, yukihiroLaravel requested changes
また少しいくつかコメントしましたのでお願いいたします！

2023-08-09 06:22 UTC, yukihiroLaravel commented on resources/views/posts/editbutton.blade.php
> +@endif
今の書き方が適切なので大丈夫です！

2023-08-09 06:22 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +    @include('posts.editbutton')
`edit_button`
viewファイル名は２単語以上になる場合、
こんな感じで、アンダーバーで区切る場合が多いです！

2023-08-09 06:22 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        if(\Auth::id() == $post->user_id){
`if (\Auth::id() == $post->user_id) {`

カッコの前後にはスペースを入れましょう！

2023-08-09 09:13 UTC, aaaperfect commented on resources/views/posts/editbutton.blade.php
> +@endif
承知しました。

2023-08-09 09:14 UTC, aaaperfect commented on resources/views/posts/posts.blade.php
> +    @include('posts.editbutton')
ありがとうございます。
修正完了しました！

2023-08-09 09:14 UTC, aaaperfect commented on app/Http/Controllers/PostsController.php
> +        if(\Auth::id() == $post->user_id){
修正完了しました！

2023-08-09 12:40 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
お疲れ様でした！

2023-08-09 12:40 UTC, merged