#13 ユーザ退会
yukihiroLaravel/joint_develop pull request #615
Opened 2023-08-02 12:12 UTC by aaaperfect

# 概要
- ユーザ退会

# 動作確認
- 退会するを押すとトップページへ、退会できていることを確認しました。
　

2023-08-02 12:21 UTC, aaaperfect commented on resources/views/users/posts.blade.php
> +                @if(empty( $post->user->deleted_at ))
userテーブルのdeleted_atのカラムが空である（論理削除が行われていないデータのみを取得）
データを取得しようとしましたが、エラーが出てしまいました。

まだ具体的なコードは考えておりませんが、if文とcontinueを使い、deleted_atカラムに日時が入っている時は
処理をスキップするという方法もできるかなと思ったのですが、いかがでしょうか？

2023-08-10 02:18 UTC, aaaperfect commented on app/Http/Controllers/UsersController.php
> +        if (\Auth::id() === $user->id) {
===で動作確認取れました。

2023-08-10 02:23 UTC, aaaperfect commented on app/User.php
> +    }
ユーザーテーブルを論理削除した際に、
postテーブルも論理削除しています。

```
 parent::boot();

 static::deleted(function ($user)
```
コードの書き方が理解できませんが、
処理の内容が理解できていればいいでしょうか？

2023-08-10 02:25 UTC, aaaperfect commented on resources/views/posts/posts.blade.php
> +    @if (is_null($post->user->deleted_at))
is_nullはemptyにしても動作確認できました。

2023-08-10 06:54 UTC, yukihiroLaravel requested changes
コメントしました。
ご確認ください

2023-08-10 06:54 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +    @if (is_null($post->user->deleted_at))
これは、(is_nullもしくはemptyいずれにしても)
ifによる条件分岐自体ない状態でも
Laravelが自動的に
削除されたものは除外して表示してくれると思うのですが
いかがでしょうか？

2023-08-10 06:54 UTC, yukihiroLaravel commented on app/User.php
> +    }
細かく理解する必要はないと思いますが

parentで
Userクラスの親にあたるModelクラスの
boot関数を実行して、論理削除の準備をしていて
deletedで削除実行、という意味だったと思います！

2023-08-10 12:48 UTC, aaaperfect commented on app/User.php
> +    }
承知しました！

2023-08-10 12:51 UTC, aaaperfect commented on resources/views/posts/posts.blade.php
> +    @if (is_null($post->user->deleted_at))
if文を消して表示されました。

2023-08-10 13:18 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
お疲れ様でした！

2023-08-10 13:18 UTC, merged