#560トップページの投稿表示（seiichi）
yukihiroLaravel/joint_develop pull request #616
Opened 2023-08-05 08:06 UTC by seiichi15

## issue
- Closes #560

## 概要
- トップページの投稿表示

## 動作確認手順
- [http://localhost:8080/]　のTopic Postsトップページで　「ユーザーのアバター画像」「投稿ユーザー名」「初回作成日時」が表示されていることを確認（Adminerの作成データと合致していることを確認）

## 確認してほしいこと
- モックアップにあったコードと応用講座のテキストコードを参考に混ぜて書きましたが、修正点はないか
- 「ユーザーのアバター画像」は現段階で画像表示されていないが、このままで良いのでしょうか

2023-08-05 11:47 UTC, yukihiroLaravel requested changes
全般的にOKですが細かい点のみいくつかコメントしました！
ご確認ください！

2023-08-05 11:47 UTC, yukihiroLaravel commented on resources/views/layouts/app.blade.php
> +<head>
ここが変にインデントがなくなってますね！もとにもどしましょう！

2023-08-05 11:47 UTC, yukihiroLaravel commented on resources/views/commons/error_messages.blade.php
> +@if (count($errors) > 0)
ここの機能ではこのファイルは使われていないと思いますがなぜ作られたのでしょうか？
もし今回の実装と無関係であれば消しましょう！

2023-08-05 11:47 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +use App\Post;
この下に１つ空行入れた方がいいですね！

2023-08-06 11:56 UTC, seiichi15 commented on resources/views/layouts/app.blade.php
> +<head>
インデント元に戻しました。

2023-08-06 11:57 UTC, seiichi15 commented on resources/views/commons/error_messages.blade.php
> +@if (count($errors) > 0)
間違ってここだけ作ってしまっていたようです。ファイル削除しました。

2023-08-06 11:57 UTC, seiichi15 commented on app/Http/Controllers/PostsController.php
> +use App\Post;
6行目の下に空行入れました。

2023-08-06 15:34 UTC, yukihiroLaravel requested changes
コメントしました

app.blade.phpにある
@include( 'error_messages')
これを削除

2023-08-06 15:34 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +    </ul>
インデント消す

2023-08-06 15:34 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +                </div>
閉じタグがない

2023-08-06 15:34 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +                <p class="mt-3 mb-0 d-inline-block"><a href="">投稿ユーザー名</a></p>
変数を使って表示

2023-08-06 15:34 UTC, yukihiroLaravel commented on public/css/styles.css
> +}
不要？

2023-08-06 15:34 UTC, yukihiroLaravel commented on resources/views/layouts/app.blade.php
> +        <link rel="stylesheet" href="{{ asset('/css/styles.css') }}">
不要

2023-08-15 15:53 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！

2023-08-15 15:53 UTC, merged