ユーザ編集画面・更新(DAIKI)
yukihiroLaravel/joint_develop pull request #618
Opened 2023-08-09 10:17 UTC by i-k-i-a-d

ユーザー情報編集画面作成。ユーザー情報更新のときのバリデーション作成。ユーザー情報を編集してDBへ保存する機能実装。

ユーザー情報を更新した後はユーザー情報詳細画面にリダイレクトさせる仕様になってますが、別のメンバーのタスクとなっており、実装前のため、現状は、トップ画面へ遷移させる仕様にしております。

以上、よろしくお願いいたします。

2023-08-10 02:18 UTC, Osk0830 requested changes
お疲れ様です！
色々と複雑な記述もしっかり理解されて行っていて素晴らしいですね！

いくつかコメントしましたので、確認よろしくお願いします。

2023-08-10 02:18 UTC, Osk0830 commented on resources/views/posts/edit_user.blade.php
> +    </div>
- バリデーションに弾かれた際は、元の登録データではなく、直前に入力していたデータが表示されるようにしてあげたほうが、ユーザビリティ的に良いと思います。

2023-08-10 02:18 UTC, Osk0830 commented on app/Http/Controllers/PostController.php
> +    }
- トランザクションまで挟んでいて素晴らしいですね！（2つのテーブルに連続してデータを入れ込んでいくようなケースでない場合にトランザクションを挟まない場合も多いですが、どちらでもOKです！）
- 悪意のあるアクセスに対する対策の一つとして、このアクションにも、本人からのアクセスの場合にのみ更新処理に進めるようなチェックを挟んであげてください。

2023-08-10 02:18 UTC, Osk0830 commented on app/Http/Controllers/PostController.php
>  class PostController extends Controller
- ユーザーに関する処理なので、このコントローラーではなく、UsersControllerに記述するほうが、見通しの良いコードになると思います。

2023-08-10 02:18 UTC, Osk0830 commented on routes/web.php
> +Route::post('update/user', 'PostController@updateUser')->name('updateuser');
- チームで取り決めがあればこの限りではないですが、チーム開発としての共同開発ですので、アクション名はともかくとして、ルーティングの名前は、`users.edit`などのように、Laravelのオーソドックスなネーミングを採用したほうが、他の開発者にとっても推測しやすくいいのではないかと思います。（個人的にはアクション名ももう少し単純でいいと思います。そのためにもコントローラーはわけるべきですね）

2023-08-10 11:30 UTC, i-k-i-a-d commented on resources/views/posts/edit_user.blade.php
> +    </div>
考えてなかったわけではないんですが、条件分岐させればいいという発想に至りませんでした。

2023-08-10 11:36 UTC, i-k-i-a-d commented on routes/web.php
> +Route::post('update/user', 'PostController@updateUser')->name('updateuser');
ここについては毎回どんなネーミングにするか迷うんですよね。
オーソドックスなネーミングがまだ経験不足のため、わからないのと、ルーティングの名前に.(ドット)を使っていいのも知りませんでした。

2023-08-11 02:10 UTC, Osk0830 requested changes
お疲れ様でした！
良い感じに整理されてきましたね！

少しだけコメントしましたので、確認よろしくお願いします。

2023-08-11 02:10 UTC, Osk0830 commented on app/Http/Requests/UserRequest.php
> +            'email' => 'required|max:255',
- こちらすみません。前回見落としていたようで。emailの箇所は、メールアドレスの形式であることをチェックするバリデーションも追加してください。

2023-08-11 02:10 UTC, Osk0830 commented on app/Http/Controllers/UserController.php
> +            return view('posts.edit_user', ['users' => $users]);
- こちらも前回気づけていませんでしたが、ここでは1人分のデータを格納しているので変数を複数形にするのは適切ではないです。1件のデータが格納される場合は単数形（例：`$user`）、複数件のデータが配列となって格納される場合は複数形（例：`$users`）のように使い分けましょう。

2023-08-11 02:10 UTC, Osk0830 commented on resources/views/posts/edit_user.blade.php
> +        @endif
このような場合のif文は、三項演算子を用いて、

```
value="{{ old('name') ? old('name') : $user->name }}”
```

のように書けますので、こちらを用いてコードをスリムにしてみてください。

2023-08-11 16:20 UTC, i-k-i-a-d commented on app/Http/Controllers/PostController.php
> +    }
この場合はトランザクションを書かなくてもいいんですね。知りませんでした。

これも入れようか迷ったんですが、編集フォームが表示されなければ大丈夫かと思って舐めてました。
やっぱりＵＲＬに直接攻撃される可能性もつぶしておいた方が安心ですよね。

2023-08-11 16:21 UTC, i-k-i-a-d commented on app/Http/Controllers/PostController.php
>  class PostController extends Controller
これもControllerを分けるか迷ったんですが、最終的に処理は同じになるので大丈夫かと思ってました。
やっぱり見やすさ重視で実装するようにします。

2023-08-11 16:23 UTC, i-k-i-a-d commented on app/Http/Requests/UserRequest.php
> +            'email' => 'required|max:255',
メールアドレスの形式のバリーデーションもいるのかなーと思って確認しましたが特にそこに触れられなかったので省いてました(;^_^A
やっぱりこれは必要ですよね。

2023-08-11 16:24 UTC, i-k-i-a-d commented on app/Http/Controllers/UserController.php
> +            return view('posts.edit_user', ['users' => $users]);
特に今まで変数の単数・複数は意識していなかったので、これから意識するようにします。

2023-08-11 16:25 UTC, i-k-i-a-d commented on resources/views/posts/edit_user.blade.php
> +        @endif
三項演算子はPHPの文法としては知っていたんですが、bladeファイルでも使う方法があるとは知りませんでした。

2023-08-12 03:43 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKなのでマージしますね！
引き続き頑張っていきましょう！

2023-08-12 03:43 UTC, merged