フォロー機能
yukihiroLaravel/joint_develop pull request #619
Opened 2023-08-11 09:26 UTC by aaaperfect

# 動作確認
- 動作確認できました。トップページに各ユーザのフォロワー数を表示しています。

# 修正が必要な点
- 細かなレイアウト調整とshow.blade.phpにて@include('posts.posts')をしているため、ユーザー詳細画面でタイムライン→フォロー中と画面切り替えをした際に、全ユーザの投稿を表示していることです。

- 切り替えた際フォロー中のユーザーのみの投稿を表示したいのですが、可能でしょうか？

2023-08-11 12:57 UTC, aaaperfect commented on resources/views/posts/posts.blade.php
> +        <span class="badge badge-pill badge-success">{{ $countFollowerUsers }}</span>
細かいレイアウト調整に関して
{{ $countFollowerUsers }}と

2023-08-11 13:03 UTC, aaaperfect commented on resources/views/posts/posts.blade.php
> +    @include('follow.follow_button')
@include('follow.follow_button')を
{{ $post->user->name }}の右に配置をしたくて、
試行錯誤したのですが、現状うまくできておりません。

レイアウトにはあまりこだわらず、機能拡充を優先した方がいいでしょうか？

2023-08-11 13:48 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +    @include('follow.follow_button')
グリッドシステム
https://websae.net/twitter-bootstrap-grid-system-21060224/

2023-08-11 13:55 UTC, yukihiroLaravel requested changes
コメントしました！

2023-08-11 14:25 UTC, aaaperfect commented on resources/views/posts/posts.blade.php
> +    @include('follow.follow_button')
ありがとうございます！

ちょっと時間を置いたら先ほどご質問した切り替えた際フォロー中のユーザーのみの投稿を表示する方法を
思い出しました。また試してからご連絡いたします。

2023-08-13 03:46 UTC, yukihiroLaravel requested changes
コメントしました！ご確認ください！

2023-08-13 03:46 UTC, yukihiroLaravel commented on resources/views/users/follow_follower_count.blade.php
> +    $countFollowingUsers = $post->user->followings()->count();
こちら
コントローラから

$countFollows
$countFollwers

という変数を既に渡していると思うので
ここで再計算しなくてもいいと思います。

2023-08-13 03:46 UTC, yukihiroLaravel commented on resources/views/users/follow_follower_count.blade.php
> +@endforeach
繰り返し３回目だとbreakしているのはなぜでしょう？

2023-08-13 04:56 UTC, aaaperfect commented on resources/views/users/follow_follower_count.blade.php
> +@endforeach
ご指摘ありがとうございます。

制作途中の動作確認で２回目の処理を止めないと
フォロー数やフォロワー数が重複して表示されていたのですが、
今改めて確認するとif文を取り除いて問題なく動作していることを確認しました。

2023-08-13 04:57 UTC, aaaperfect commented on resources/views/users/follow_follower_count.blade.php
> +    $countFollowingUsers = $post->user->followings()->count();
コントローラーより値を持ってくることができました！

2023-08-13 15:04 UTC, yukihiroLaravel approved these changes

2023-08-13 15:05 UTC, merged