ユーザー詳細画面実装(DAIKI)
yukihiroLaravel/joint_develop pull request #621
Opened 2023-08-12 11:26 UTC by i-k-i-a-d

・ユーザー詳細画面作成。
・ユーザー詳細画面を表示させるためのルーティングとUserController内に表示用のshowDetailメソッド作成。
・ヘッダーのユーザネームをクリックしたらユーザー詳細画面が表示されるように実装。
・前のタスクでユーザー情報を更新した後に、トップページへリダイレクトするように実装していたが、今回ユーザー詳細画面が実装されたので、更新後にユーザー詳細画面へリダイレクトするように修正。
・トップ画面の投稿一覧の中にあるユーザーネームをクリックしたらユーザー詳細画面が表示されるように実装。
・ユーザー詳細画面を開いても、ログインしているユーザーでないと削除、編集する、ユーザ情報の編集のボタンと投稿データの作成日時が表示されないように実装。

確認をお願い足します。

2023-08-13 00:05 UTC, Osk0830 requested changes
お疲れ様でした！
全体的に基本的に問題なくよく書けていると思います。

いくつかコメントしましたので、確認よろしくお願いします。

2023-08-13 00:05 UTC, Osk0830 commented on app/Http/Controllers/UserController.php
> +    /**
- URIに変更があった際にもあちこち修正しなくていいように、リダイレクト先はルーティング名を使って指定しましょう。
- `$input['id']`のように何度も用いる値は、記述の簡素化やメンテナンス性の向上など意味で、先に一度変数に入れてしまった方が良さそうですね。
- また、この程度の記述ですと、わざわざ `else { ... }`で囲まなくてもいいかもしれません。

2023-08-13 00:05 UTC, Osk0830 commented on app/Http/Controllers/UserController.php
> +        $user = User::find($id);
- 先にユーザーモデルのインスタンスを取得してしまえば、Postモデルのデータはリレーションメソッドを用いてもう少しシンプルに取得できると思いますので、調整してみてくださいね。

2023-08-13 00:05 UTC, Osk0830 commented on app/Http/Controllers/UserController.php
> +        return view('posts.user_detail', ['posts' => $posts, 'user' => $user]);
- Userに関するページのデータは、Postに関するものとは別の部類なので、`posts`というフォルダに格納してしまわずに、別途`users`フォルダを設けて格納した方が、可読性・メンテナンス性が高まりそうですね。そうするとBladeの名前にわざわざ`user_`のような接頭辞的な内容も不要になると思います。可能なものは短い名前にするのが望ましいです。（こちらもしかするとユーザー編集画面も同様ですかね。）

2023-08-13 00:05 UTC, Osk0830 commented on resources/views/layouts/header.blade.php
> +                <li class="nav-item"><a href="/users/{{ Auth::id() }}" class="nav-link text-light">{{ Auth::user()->name }}</a></li>
- こちらも、上述のもの同様、ルーティング名を用いた記述に変更しましょう。

2023-08-13 00:05 UTC, Osk0830 commented on resources/views/posts/top.blade.php
> +                <p class="mt-3 mb-0 d-inline-block"><a href="/users/{{ $post->user_id }}">{{ $post->user->name }}</a></p>
- こちらも同様ですね。

2023-08-13 00:05 UTC, Osk0830 commented on resources/views/posts/user_detail.blade.php
> +                        <a href="/users/{{ $user->id }}/edit" class="btn btn-primary btn-block">ユーザ情報の編集</a>
- こちらも同様ですね。

2023-08-13 00:05 UTC, Osk0830 commented on resources/views/posts/user_detail.blade.php
> +                            @endif
- ここはお手本サイトを見ても、本人かどうかなど無関係に表示させるべき箇所のようですが、いかがでしょう？

2023-08-13 00:05 UTC, Osk0830 commented on routes/web.php
> +Route::get('users/{id}', 'UserController@showDetail')->name('users.detail');
- 参考までに、Laravelのオーソドックスな名前で言うと`users.show`になります。

2023-08-13 19:33 UTC, i-k-i-a-d commented on app/Http/Controllers/UserController.php
> +    /**
ルーティング名を使って実装する際に、ルートパラメーターをどうやって引き継ぐのか知らなかったので、この方法で実装しておりました。
まさかroute関数の第二引数に指定できるとは知りませんでした。

確かに繰り返し使う値なら変数に入れるべきでした。

ここについてはelseを使うと何かしらデメリットはあるんでしょうか？

2023-08-13 19:34 UTC, i-k-i-a-d commented on app/Http/Controllers/UserController.php
> +        $user = User::find($id);
1対多のDBを扱う処理にあまり慣れていないもので、リレーションメソッドを使う方法を思いつきませんでした。

2023-08-13 19:35 UTC, i-k-i-a-d commented on app/Http/Controllers/UserController.php
> +        return view('posts.user_detail', ['posts' => $posts, 'user' => $user]);
これも前回の実装時にどうしようか迷ったんですが、以前にフォルダを追加するときはチームで話し合うべきだという指摘を受けたことがあったので、いったん現状のフォルダを流用してました。

2023-08-13 19:36 UTC, i-k-i-a-d commented on resources/views/layouts/header.blade.php
> +                <li class="nav-item"><a href="/users/{{ Auth::id() }}" class="nav-link text-light">{{ Auth::user()->name }}</a></li>
修正しました。

2023-08-13 19:36 UTC, i-k-i-a-d commented on resources/views/posts/top.blade.php
> +                <p class="mt-3 mb-0 d-inline-block"><a href="/users/{{ $post->user_id }}">{{ $post->user->name }}</a></p>
修正しました。

2023-08-13 19:36 UTC, i-k-i-a-d commented on resources/views/posts/user_detail.blade.php
> +                        <a href="/users/{{ $user->id }}/edit" class="btn btn-primary btn-block">ユーザ情報の編集</a>
修正しました。

2023-08-13 19:37 UTC, i-k-i-a-d commented on resources/views/posts/user_detail.blade.php
> +                            @endif
ユーザー１番の方は日付が入ってないので、そうなってるのかと思ったんですが、これは単純にDBに値が入ってないから表示されていないだけでしょうね。

2023-08-13 19:38 UTC, i-k-i-a-d commented on routes/web.php
> +Route::get('users/{id}', 'UserController@showDetail')->name('users.detail');
オーソドックスな名前に修正しました。

2023-08-14 13:03 UTC, Osk0830 commented on app/Http/Controllers/UserController.php
> +    /**
elseを使ったからといってデメリットというほどのものはありませんが、個人的には記述が若干冗長・煩雑になる印象を受けます。

2023-08-14 13:05 UTC, Osk0830 commented on resources/views/posts/user_detail.blade.php
> +                            @endif
そうですね。`DB::insert()`を使ってダミーデータ入れる際に、必要なカラムに値を指定しなかったのかもですね。

2023-08-14 13:07 UTC, Osk0830 approved these changes
お疲れ様です！
こちらしっかり修正できているのでマージしますね！

2023-08-14 13:07 UTC, merged