フラッシュメッセージ
yukihiroLaravel/joint_develop pull request #623
Opened 2023-08-14 06:51 UTC by aaaperfect

# 動作確認
- 動作確認できました。

2023-08-14 06:58 UTC, aaaperfect commented on resources/views/users/show.blade.php
> +            @includeWhen($timelineShow, 'posts.posts')
@includeWhenによってusers/follower.blade.phpとusers/follow.blade.phpの重複していたコードが削除できたので
コード量はかなり減りました。

ただUsersController.phpのshow、followings、followersメソッドのコード量が増えたので、処理の流れは読みづらくなってしまったのかなと思っています。

2023-08-14 07:07 UTC, aaaperfect commented on resources/views/follow/follow_button.blade.php
> +        <form method="POST" action="{{ route('unfollow', $user->id) }}">
ユーザー退会した後に、新規登録をしてヘッダーのログインユーザー名をクリックすると投稿がないためエラーが発生しました。$postを取り除いてきちんと動作することを確認しました。

2023-08-14 07:37 UTC, aaaperfect commented on public/js/main.js
> +  });
フラッシュメッセージを表示後にフェードアウトの機能をつけたいと思って試したのですが、
うまく機能させることができませんでした。

またlayouts/app.blade.phpのbodyタグ内でjQueryを既に読み込んでいるので、
新規でpublic/js/main.jsを作る必要性があるのか理解できておりません。

可能であればご教授いただけますと幸いです。

2023-08-15 02:53 UTC, yukihiroLaravel requested changes
コメントしましたのでお願いします！

2023-08-15 02:53 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        return back()->with('messageDelete', '投稿を削除しました');
こちらユーザ詳細画面上で
投稿を削除したときにも表示が出るようにしましょう

2023-08-15 02:53 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        return redirect('/')->with('messageUpdate', '投稿を更新しました');
こちらユーザ詳細画面上で
投稿を更新したときにも表示が出るようにしましょう

2023-08-15 02:53 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +                @endif
同じものとする

2023-08-15 04:36 UTC, aaaperfect commented on resources/views/welcome.blade.php
> +                @endif
ご指摘いただいた内容、修正完了しました！

2023-08-15 15:56 UTC, yukihiroLaravel approved these changes
OKです！
問題ないと思いますのでマージしました☺️
おつかれさまでした！！

2023-08-15 15:56 UTC, merged