画像投稿機能
yukihiroLaravel/joint_develop pull request #625
Opened 2023-08-16 06:47 UTC by aaaperfect

# 動作確認
- 投稿は入力必須、画像は任意で投稿できることを確認しました。

# 確認して欲しいこと
- 見た目は大丈夫でしょうか。
# 修正する点 

- 画像を投稿した後に投稿編集をしようとすると既に投稿済みの画像をうまく削除できず、
更新が行えないのですが、こちらのタスクでしょうか？

# お聞きしたいこと
- 画像投稿後に投稿編集をする際はまず投稿済みの画像を削除必要があると思うのですが、
postsテーブルのdeleted_atカラムに日時を入れずに、imageカラムのみをnullにすることはできるのでしょうか？

2023-08-16 06:51 UTC, aaaperfect commented on app/Http/Controllers/PostsController.php
> +        dd($post->image);
dd($post->image);にて画像の保存されているパスが確認できたのですが、
削除ができません。

2023-08-16 06:53 UTC, aaaperfect commented on app/Http/Controllers/PostsController.php
>      public function update(PostRequest $request, $id)
upadateメソッドのelseif以下は動作確認できております。

2023-08-16 09:31 UTC, yukihiroLaravel requested changes
コメントしました！
https://www.loom.com/share/82e7e25916814994b6cf8a45b8f90d4c?sid=c49e02b6-73f7-4c16-928e-b0be4026c619

2023-08-16 09:31 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        return back()->with('messageSuccess', '投稿しました');
インデント

2023-08-17 02:52 UTC, aaaperfect commented on app/Http/Controllers/PostsController.php
> +        return back()->with('messageSuccess', '投稿しました');
修正完了しました。

2023-08-17 12:57 UTC, yukihiroLaravel approved these changes
画像の編集・更新処理は他タスクに分けられたんですね。

見た目もかなりよくなったと思います！
OKなのでマージします☺️

2023-08-17 12:58 UTC, merged