新規ユーザー登録実装（shinsuke)
yukihiroLaravel/joint_develop pull request #627
Opened 2023-08-17 14:37 UTC by shinken459

2023-08-19 01:46 UTC, Osk0830 requested changes
お疲れ様でした！
コンフリクトの解消などお疲れ様でした！

こちらいくつかコメントしましたので、
確認よろしくお願いします。

2023-08-19 01:46 UTC, Osk0830 commented on app/Http/Controllers/Auth/RegisterController.php
> -    protected $redirectTo = RouteServiceProvider::HOME;
- これ自体を削除してしまうと、もしかしたらどこかでこの変数を参照しているような箇所があった場合に予期せぬ不具合が発生する可能性がありますので、`app/Providers/RouteServiceProvider.php`の`HOME`の値を変更するのがベストです。難しい場合は、ここの`protected $redirectTo =`の値をリダイレクトさせたい場所を直接指定する感じで書き換えましょう。

2023-08-19 01:46 UTC, Osk0830 commented on app/Http/Controllers/UserController.php
> +            return redirect (route('top'));
- 新規登録用のアクションは、`RegisterController.php`とそれが参照している各種ファイルで既にできあがっているので、特別な変更を加える必要がある場合を除いてはそれを用いるのがいいです。なので、今回はここにこのような記述を追加する必要はなさそうです。

2023-08-19 01:46 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +    <form method="POST" action="">
- 新規登録のデータを送る送信先が指定されていないようですね。

2023-08-19 01:46 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +        </div>
- バリデーションで弾かれた際に、既存の入力内容が残っているようにしてみてくださいね。

2023-08-21 15:12 UTC, shinken459 commented on app/Http/Controllers/Auth/RegisterController.php
> -    protected $redirectTo = RouteServiceProvider::HOME;
リダイレクトさせるメソッドを作って修正しました。

2023-08-21 15:13 UTC, shinken459 commented on app/Http/Controllers/UserController.php
> +            return redirect (route('top'));
既存のRegisterControllerを使った処理に変更しました。

2023-08-21 15:14 UTC, shinken459 commented on resources/views/auth/register.blade.php
> +    <form method="POST" action="">
送信先を指定しました。

2023-08-21 15:15 UTC, shinken459 commented on resources/views/auth/register.blade.php
> +        </div>
old関数を使って修正しました。

2023-08-22 05:09 UTC, Osk0830 requested changes
お疲れ様でした！
いい感じに修正できてきましたね！

1箇所だけコメントしましたので、
確認よろしくお願いします。

2023-08-22 05:09 UTC, Osk0830 commented on app/Http/Controllers/Auth/RegisterController.php
> +
こちらですが、

- リダイレクト先は、`RouteServiceProvider::HOME`の値になっている
- `RouteServiceProvider::HOME`の値は、`app/Providers/RouteServiceProvider.php`の下記の部分で指定されている

```
public const HOME = '/home';
```

ですので、上記の`/home`を必要な値に書き換えるだけでOKで、
別途ファンクションは追記いただかなくて大丈夫です！

2023-08-22 05:09 UTC, Osk0830 requested changes
お疲れ様でした！
いい感じに修正できてきましたね！

1箇所だけコメントしましたので、
確認よろしくお願いします。

2023-08-22 13:33 UTC, shinken459 commented on app/Http/Controllers/Auth/RegisterController.php
> +
指定された方法で修正しました。

2023-08-23 08:13 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらしっかり修正できているのでマージしますね！

引き続き頑張っていきましょう！

2023-08-23 08:14 UTC, merged