#557 新規投稿作成(nari)
yukihiroLaravel/joint_develop pull request #628
Opened 2023-08-17 15:33 UTC by yuuya-nari

## issues
-Closes #557 

## 概要　
- 新規投稿作成

## 動作確認手順
- ログイン後投稿欄に文字を打ち　http://localhost:8088に移動後
　Adminerのposts→データ→textにて確認願います。

## 確認してほしいこと
- 投稿欄のコードを自分なりに調べながら作成しましたのでもっとスマートな書き方があれば教えて頂きたいです。
　<textarea style="width:860px;" rows="5" name="text" value="{{ old('text') }}"></textarea>
- PostsControllerの名前空間は間違いないでしょうか？未だに名前空間の認識が曖昧なので心配です。

2023-08-18 00:25 UTC, yukihiroLaravel requested changes
いくつか修正箇所をお送りしましたので
ご確認願います！

よろしくお願いします！

2023-08-18 00:25 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +use App\User;
これは使っていないので不要ですかね

2023-08-18 00:25 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +@endsection
こちら全体的にインデントがおかしいので整えましょう！

2023-08-18 00:25 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +　　<textarea style="width:860px;" rows="5" name="text" value="{{ old('text') }}"></textarea>
ご質問のこちらは、
下記のようにすればおそらくうまくいくかなと思います！

`<textarea class="form-control" name="content" rows="4">{{ old('text') }}</textarea>`

valueのところも、タグの間に入れるようにした方がスマートですかね

2023-08-18 10:06 UTC, yuuya-nari commented on app/Http/Controllers/PostsController.php
> +use App\User;
消去しました。

2023-08-18 19:09 UTC, yuuya-nari commented on resources/views/welcome.blade.php
> +　　<textarea style="width:860px;" rows="5" name="text" value="{{ old('text') }}"></textarea>
アプリ見本では新規投稿枠の横幅が少々狭くなっているのに対しこちらのコードを打ち込んだ際は広くなってしまいました。御教示頂いたコードを打ち込んだ場合横幅が狭くなる方法を教えて頂きたいです。

2023-08-18 19:09 UTC, yuuya-nari commented on resources/views/welcome.blade.php
> +@endsection
対処しました。

2023-08-19 11:12 UTC, yuuya-nari commented on resources/views/welcome.blade.php
> +　　<textarea style="width:860px;" rows="5" name="text" value="{{ old('text') }}"></textarea>
対処しました。

2023-08-19 11:17 UTC, yukihiroLaravel approved these changes
OKかと思いますのでマージしました！
宜しくお願い致します！

2023-08-19 11:17 UTC, merged