投稿編集にて更新処理の追加
yukihiroLaravel/joint_develop pull request #630
Opened 2023-08-18 01:36 UTC by aaaperfect

# 動作確認
- upadateメソッドが意図したように動作していることを確認しました。

2023-08-18 08:43 UTC, yukihiroLaravel requested changes
よりスマートな書き方を書いてみましたので
ご確認ください！

2023-08-18 08:43 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        }
下記の３行はどのifでも共通する部分かと思いますので


```
            $post->text = $request->text;
            $post->save();
            return redirect('/')->with('messageSuccess', '投稿を更新しました');
```

たぶん下記のように書けますね！


```
if (isset($post->image)) {
       // 上記３行を省いたコード
} elseif (isset($request->image)) {
       // 上記３行を省いたコード
}
$post->text = $request->text;
$post->save();
return redirect('/')->with('messageSuccess', '投稿を更新しました');
```

2023-08-18 12:35 UTC, aaaperfect commented on app/Http/Controllers/PostsController.php
> +        }
ありがとうございます！確かにこちらの方がスマートな書き方ですごいです！
今後はこのようなコードを書けるように努力します！

修正後きちんと動作していることを確認しました。

2023-08-19 07:42 UTC, yukihiroLaravel requested changes
１点コメントしました！
ご確認ください！

2023-08-19 07:42 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        } elseif (isset($request->image)) {
こうなるのであれば、
この２行は
```
if (isset($request->image)) {
```
こちらの１行だけで完成しないですか？

2023-08-19 09:32 UTC, aaaperfect commented on app/Http/Controllers/PostsController.php
> +        } elseif (isset($request->image)) {
おっしゃる通り上記コードに修正してきちんと動作することを確認しました！
今回のような件に気付けるように日々精進していきます！

2023-08-19 09:37 UTC, yukihiroLaravel approved these changes
かなりスッキリしましたね！
OKなのでマージしました！おつかれさまでした！！

2023-08-19 09:41 UTC, merged