フォロー機能を実装(DAIKI)
yukihiroLaravel/joint_develop pull request #631
Opened 2023-08-19 16:36 UTC by i-k-i-a-d

・多対多のDBを作るためにマイグレーションファイルを作ってfollow_usersテーブルを中間テーブルとして作成。
・FollowUserモデルを作成。
・Userモデル内に多対多のリレーションメソッドを作成。
・フォローとフォロー解除機能のためのルーティング作成。
・ルーティング通りにFollowUserControllerを新たに作成してメソッドを二つ作成。
・フォロー・フォロー解除のボタンをユーザー詳細画面に設置して、条件分岐で表示を切り替えるように実装。
・ユーザーが退会した際にそのユーザーがフォローしたりフォローされたりしているデータも中間テーブルから削除されるように実装。

ユーザーが退会した際は、そのユーザーがフォローしていたデータとフォローされていたデータが全て中間テーブルから物理削除される仕様にしておりますがよろしいでしょうか？？

今回のタスクは、お手本のアプリにも機能がなく、全て手探りで進めた実装になりますので、もっと効率的な実装方法があるかもしれませんが、とりあえず要件通りに動くようには仕上げております。

レビューよろしくお願いいたします。

2023-08-21 07:59 UTC, Osk0830 requested changes
お疲れ様でした！
色々と考えながら実装を進められているのが伺えて非常に素晴らしいと思います。
ただ、フレームワークを用いる実装で重要になってくるポイントの一つは、フレームワークが用意している機能を活用していかにスマートにスリムに書けるか、という部分にもあります。
レビュー内容を踏まえて一度検討、修正してみてくださいね。

2023-08-21 07:59 UTC, Osk0830 commented on app/FollowUser.php
> +}
- ちょっと抽象的な話になってしまいますが、モデルは、ユーザーや投稿のように「物体」が存在する際に、その物体の雛形として存在するイメージです。中間テーブルはあくまで2つのモデルの「関係」を整理するためだけのものなので、モデルは不要です。

2023-08-21 07:59 UTC, Osk0830 commented on app/Http/Controllers/FollowUserController.php
> +    }
- 中間テーブルにデータを入れたり中間テーブルのデータを削除するのには、`attach／detach`というメソッドを用いるのが一般的です。リレーションメソッドとうまく組み合わせながら、`attach／detach`を活用して実装してみてください。
- なお、上記のような操作は、他の場所でも使いまわせるよう、モデルのメソッドとして定義し、コントローラーの各アクション内ではそれを呼び出すような形で記述するのがいいでしょう。ユーザーモデル内にメソッドを定義し、ここではそれを呼び出す形にしてみてくださいね。

2023-08-21 07:59 UTC, Osk0830 commented on app/Http/Controllers/UserController.php
> +        $follow = FollowUser::where('following_user_id', "=", Auth::id())->where('followed_user_id', "=", $id)->first();
- このような情報はリレーションメソッドを活用して取得するようにしましょう。ただ、コントローラーで取得し渡す必要はなく、Blade内で取得する感じで良さそうですね。

2023-08-21 07:59 UTC, Osk0830 commented on app/Http/Controllers/UserController.php
> +                }
- このような処理は、マイグレーションにある `onDelete('cascade')`により自動的に行われるようになるので、記述が不要ですね。

2023-08-21 07:59 UTC, Osk0830 commented on resources/views/users/detail.blade.php
>                  @endif
- モデル・コントローラーを変更・調整した結果に即して必要箇所調整くださいね。

2023-08-21 07:59 UTC, Osk0830 commented on routes/web.php
> +Route::post('users/{id}/unfollow', 'FollowUserController@unfollow')->name('unfollow');
- この機会にルーティングの整理も行ってみてください。その際、必要な箇所にはミドルウェアも挟みましょう。

2023-08-24 01:45 UTC, i-k-i-a-d commented on routes/web.php
> +Route::post('users/{id}/unfollow', 'FollowUserController@unfollow')->name('unfollow');
prefixを使って修正しました。

2023-08-24 01:46 UTC, i-k-i-a-d commented on resources/views/users/detail.blade.php
>                  @endif
条件分岐の内容をリレーションメソッドを使って書き換えました。

2023-08-24 01:47 UTC, i-k-i-a-d commented on app/Http/Controllers/UserController.php
> +                }
usersテーブルが論理削除の場合はマイグレーションにある onDelete('cascade')だけでは削除できないので、そのままの状態にしております。

2023-08-24 01:47 UTC, i-k-i-a-d commented on app/Http/Controllers/UserController.php
> +        $follow = FollowUser::where('following_user_id', "=", Auth::id())->where('followed_user_id', "=", $id)->first();
リレーションメソッドを使って修正しました。

2023-08-24 01:49 UTC, i-k-i-a-d commented on app/Http/Controllers/FollowUserController.php
> +    }
attach/detachを使って修正し、場所をUserモデル内に引っ越しました。
また、FollowUserControllerから静的なメソッドとして呼び出すように実装してます。

2023-08-24 01:51 UTC, i-k-i-a-d commented on app/FollowUser.php
> +}
FollowUserモデルを削除すると、ユーザー退会時のフォローの削除が行えなくなるため消さずに残しております。
また、attach/detachを使って中間テーブルに値を入れるようにしたので、$fillableの設定は不要となり、削除しております。

2023-08-24 04:47 UTC, Osk0830 requested changes
お疲れ様でした。
記述が比較的スマートになってきましたね。

モデルの問題と削除の問題は一旦保留し、それ以外について幾つかコメントしました。
確認よろしくお願いします。

2023-08-24 04:47 UTC, Osk0830 commented on app/User.php
> +    }
なかなかいい感じになってきましたね。ただ、いくつか再検討や修正をした方が良さそうな内容があります。

- フォローという操作的に考えた場合、フォローボタンを押下したユーザーを軸に、自分のidにフォロー相手のidを紐づける、という論理が順当でわかりやすいと思いますが、今はわざわざフォロー相手の情報を取得して、そのユーザーを軸に、ログインしているユーザーのidを紐づける、というしくみになってしまっています。ここら辺の論理と実装をもう少しスマートにしてみてください。

- 現状では、下記のように自分自身であった場合もフォローできてしまいます。自分自身はフォローできない仕組みにしましょう。

[![Image from Gyazo](https://i.gyazo.com/0f97cbcdfea7f7b7ed9b43da5d7e53a0.png)](https://gyazo.com/0f97cbcdfea7f7b7ed9b43da5d7e53a0)

[![Image from Gyazo](https://i.gyazo.com/19d79fe7ca5e637caae3f34aed3d6074.png)](https://gyazo.com/19d79fe7ca5e637caae3f34aed3d6074)

- また、フォロー関係（特定のidのペア）がすでに存在している場合にもフォローできてしまいます。同じ理屈で、関係が存在しなくても `detach()`が実行される仕組みになっています。すでにフォローしているかどうか（テーブルにidのペアが存在するか）に応じて処理が分岐されるようにしてみてください。

[![Image from Gyazo](https://i.gyazo.com/0fe6d4862ccbd350eea3ede1768c89c4.png)](https://gyazo.com/0fe6d4862ccbd350eea3ede1768c89c4)

- 既にフォローしているかどうかをチェックするロジックは、モデル内にメソッドとして定義しておくと、Bladeなどでもそれを利用でき記述がシンプルになると思います。

2023-08-24 04:47 UTC, Osk0830 commented on database/migrations/2023_08_17_174711_create_follow_users_table.php
> +            $table->timestamps();
- DBにも、idのペアはユニークなもので重複不可のように制約をかけておきましょう。

2023-08-24 04:47 UTC, Osk0830 commented on resources/views/users/detail.blade.php
> +                    @elseif ($user->followUsers()->where('following_user_id', Auth::id())->exists() && $user->followUsers()->where('followed_user_id', $user->id)->exists())
- 上述したように、モデルに必要なメソッドを用意してあげることで、ここら辺の記述ももう少しシンプルに書けると思います。

2023-08-24 04:47 UTC, Osk0830 commented on routes/web.php
> +});
- ログインしている場合しかアクセスできないようにする必要がある内容には、ミドルウェアを挟んでおきましょう。
- `update`って、id無関係でしたっけ？？

2023-08-24 18:55 UTC, i-k-i-a-d commented on routes/web.php
> +});
ミドルウェアでログイン状態のルーティングをまとめました。

2023-08-24 18:57 UTC, i-k-i-a-d commented on resources/views/users/detail.blade.php
> +                    @elseif ($user->followUsers()->where('following_user_id', Auth::id())->exists() && $user->followUsers()->where('followed_user_id', $user->id)->exists())
Userモデル内にフォロー状態をチェックできるメソッドを作って、$userインスタンスからbladeファイル内で呼び出して条件分岐できるように実装。

2023-08-24 18:58 UTC, i-k-i-a-d commented on database/migrations/2023_08_17_174711_create_follow_users_table.php
> +            $table->timestamps();
idのペアがユニークになるようにマイグレーションファイルで設定。

2023-08-24 19:10 UTC, i-k-i-a-d commented on app/User.php
> +    }
マイグレーションファイルでfollow_usersテーブル内のカラム名を修正。
特定のユーザーを基準にして、そのユーザーがフォローしているユーザー情報を全て取得するリレーションメソッドと、特定のユーザーがフォローされているユーザー情報を全て取得するリレーションメソッドを作成。
そのリレーションメソッドを使って、ログインしているユーザーを基準として、フォローするとログインしているユーザーのidとフォローされたユーザーのidがテーブルに挿入されるように実装。
また、FollowUserController内でログインユーザーとフォローされるユーザーのidが異なるときしかメソッドが実行されないように条件分岐を追加。

2023-08-25 13:07 UTC, i-k-i-a-d commented on routes/web.php
> +});
updateに関しては、ルートパラメーターでidを受け取らなくても、inputタグから直接Requestクラスへ、更新するユーザーのidが届くようになってます。

2023-08-26 01:13 UTC, Osk0830 requested changes
お疲れ様です！
かなりいい感じになってきたと思います！

少し検討が必要な箇所がありコメントしましたので、
確認よろしくお願いします！

2023-08-26 01:13 UTC, Osk0830 commented on app/Http/Controllers/FollowUserController.php
> +    }
- `abort(404)`は`return`の後に置かれているので、必ず`return`で処理完了してしまい、ここまで到達することはなくないでしょうか？

2023-08-26 01:13 UTC, Osk0830 commented on app/User.php
> +    }
- 「フォローボタンを押下した人（ログインしているユーザー）が引数として渡されたidに該当するユーザーを既にフォローしているかどうか」をチェックするものになるべきかな、と思いますが、こちら軸となるユーザーが変わってしまってませんでしょうか？今インスタンス化されているユーザー（ログインユーザー）が軸である場合、`$this`を活用できそうですね。

2023-08-26 01:13 UTC, Osk0830 commented on app/User.php
> +            if (Auth::id() !== $id && !$bool = $this->followCheck($id)) {
- この `$bool`はなぜ必要なのでしょうか？

2023-08-26 01:13 UTC, Osk0830 commented on app/User.php
> +            }
- if文の条件に合致しなかった場合の処理はどうなりますか？

2023-08-26 01:13 UTC, Osk0830 commented on app/User.php
> +    }
- こちらにも必要なチェックを挟むようにしましょう。

2023-08-26 01:13 UTC, Osk0830 commented on database/migrations/2023_08_17_174711_create_follow_users_table.php
> +            $table->unique(['user_id', 'followed_id']);
- この3つは、カラムそのものの作成ではないので、カラム作成に関するメソッドが全て終わってから1行空けて書くようにすると、より可読性が高まりそうですね。

2023-08-26 01:13 UTC, Osk0830 commented on routes/web.php
> +    });
- なるほど、`update`では`hidden`で渡している旨了解です。もちろんこのままでも間違いはないですが、統一性という観点から少しわかりにくいのもあるので、可能であればパラメーターで渡す形に統一するといいかもですね。今ではなくおいおいで全然OKですので、検討してみてくださいね。

2023-08-26 23:03 UTC, i-k-i-a-d commented on app/Http/Controllers/FollowUserController.php
> +    }
abort関数をfollowメソッド側に引っ越しさせ、条件分岐にはじかれた際の処理として実装してます。

2023-08-26 23:03 UTC, i-k-i-a-d commented on app/User.php
> +    }
ログインユーザーを基準としてリレーションメソッドを使うように修正してます。

2023-08-26 23:04 UTC, i-k-i-a-d commented on app/User.php
> +            if (Auth::id() !== $id && !$bool = $this->followCheck($id)) {
必要ありませんでしたね。
$thisの前に！を付けるのが、なんか不自然な気がして変数を置いてみました。

2023-08-26 23:04 UTC, i-k-i-a-d commented on app/User.php
> +            }
abort関数をfollowメソッドに実装済みです。

2023-08-26 23:13 UTC, i-k-i-a-d commented on app/User.php
> +    }
今回、ユーザー退会時にフォローデータが削除される仕様を実現するのに、このunfollow();メソッドを呼び出して削除させるように実装したので、あえて、ここのunfollow();メソッドには条件分岐を入れませんでした。

理由としては、
そもそも、自分で自分をフォローすることはできないようにfollow();メソッドで条件設定しているため、自分で自分のフォローを解除するという事象自体が起き得ないし、フォロー状態かどうかを確認してフォロー状態でないときは、中間テーブルにデータが存在しないときなので、unfollow();のメソッドが動いてもなにも変化がない。そして最大の理由が、unfollow();メソッドをユーザー退会処理の際にフォローデータを削除する際に使いまわせなくなる。
なぜなら、フォローチェックはログインしているユーザーがフォローしているユーザーの中に、ユーザー詳細画面に表示されているユーザーのidが入っているかどうかを確認する仕様なので、退会する処理の際はログインしているユーザーもユーザー詳細画面に表示しているユーザーも同じユーザーであり、これが成立する場合、自分で自分をフォローしていることになってしまう。
また、そもそもログインしている人が、ユーザー詳細画面に表示されているユーザーではないとき、という条件があるので、完全に条件の範囲外になる。

以上の理由でunfollow();には条件分岐を付けませんでしたが、今回はユーザー退会時のフォロー解除のロジックを別途で構築したのでunfollow();メソッドは使わずに対応しました。

なので、unfollow();メソッドに条件分岐を入れても問題はなくなり、ご指摘通りの実装となっております。

2023-08-26 23:14 UTC, i-k-i-a-d commented on database/migrations/2023_08_17_174711_create_follow_users_table.php
> +            $table->unique(['user_id', 'followed_id']);
カラム生成に関係ないものは一行スペースを空けてまとめました。

2023-08-26 23:15 UTC, i-k-i-a-d commented on routes/web.php
> +    });
今回ついでなので、やってしまいました。もともとのinputタグの削除、ルーティングの修正、route();関数の第二引数の指定、UserController内のメソッドで二つ目の引数を受取り、それを使って中のロジックの修正まで完了してます。

2023-08-29 06:54 UTC, Osk0830 requested changes
お疲れ様です！
昨日まで諸事情によりドタバタしていた関係で遅くなってしまいました。

レビューしましたので、確認よろしくお願いします。

2023-08-29 06:54 UTC, Osk0830 commented on app/User.php
> +        return $user->followings()->where('followed_id', $id)->exists();
- フォローチェックは常にログインしているユーザーを基準に行われるものなので、そのインスタンスのメソッドどして実行されるかと思います。なので、こちらは再度インスタンスを呼び出す必要はなく、`$this->`でOKだと思われますがいかがでしょうか？

2023-08-29 06:54 UTC, Osk0830 commented on resources/views/users/detail.blade.php
> +                    @elseif ($user->followCheck($user->id))
- こちら、前回は見逃してしまいましたが、フォローチェックの基準となるユーザーは、この画面に詳細が表示されている `$user`ではなく、常にログインしているユーザーではないでしょうか？

2023-08-29 06:54 UTC, Osk0830 commented on app/User.php
> +        if (Auth::id() !== $id && !$this->followCheck($id)) {
- フォロー解除をしようとすると、スクショのように404エラーになります。おそらくここら辺の条件がおかしそうですね。フォローチェックの結果がどのような場合にアンフォローできるべきか再検討してみてくださいね。

[![Image from Gyazo](https://i.gyazo.com/c38c7f6fab2083744b487ed5ba71da85.gif)](https://gyazo.com/c38c7f6fab2083744b487ed5ba71da85)

2023-08-29 06:54 UTC, Osk0830 commented on app/User.php
> +        if (Auth::id() !== $id && !$this->followCheck($id)) {
- パラメーターとして渡された値は文字列になります。`!==`を用いる場合は、型の問題にも一定程度配慮してあげましょう。

[![Image from Gyazo](https://i.gyazo.com/dcd7459f1706a3287e13bab5b9666857.png)](https://gyazo.com/dcd7459f1706a3287e13bab5b9666857)

[![Image from Gyazo](https://i.gyazo.com/a0cb8c74e8d340948b2dd9ac6c4eeee1.png)](https://gyazo.com/a0cb8c74e8d340948b2dd9ac6c4eeee1)

2023-09-01 10:22 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらしっかり修正できているのでマージしますね！

2023-09-01 10:22 UTC, merged