コメント機能
yukihiroLaravel/joint_develop pull request #632
Opened 2023-08-20 01:16 UTC by aaaperfect

# 動作確認
- できております。

# お聞きしたい事
- コメントをリレーションを用いて表示しようとしたところ、表示することができませんでした。
- エラー箇所を特定するためにコントローラーでdd($post->comments->content);を行った所、
Property [content] does not exist on this collection instance.というエラーが発生しました。
- このエラーより$post->comments->contentという書き方に問題があるのかと考えております。
- エラー名で検索を行い解決できる糸口を模索中でありますが、現状解決できておりません。
- ヒントを頂けないでしょうか？よろしくお願いいたします。

2023-08-20 01:20 UTC, aaaperfect commented on resources/views/comments/comment.blade.php
> +    @endif
こちらでコメントを表示したいと考えています。

2023-08-21 20:00 UTC, yukihiroLaravel requested changes
良い感じですね！
１点コメントしましたのでご確認ください！

2023-08-21 20:00 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::get('{id}/comment/new','CommentController@new')->name('new.comment');
newよりcreateなどの関数名の方がわかりやすいと思います！

2023-08-22 00:55 UTC, aaaperfect commented on routes/web.php
> +        Route::get('{id}/comment/new','CommentController@new')->name('new.comment');
修正完了しました！

2023-08-22 10:42 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！

あと、今回は仕様は魚住さんご自身で考えていただいたのですが
ツイッターなどは自分の投稿にもコメントできるのが普通なので
自分の投稿にも今後コメントできるようにしてもいいと思いました！

ひとまずはお疲れ様でした！

2023-08-22 10:42 UTC, merged