投稿の検索機能
yukihiroLaravel/joint_develop pull request #637
Opened 2023-08-24 02:35 UTC by aaaperfect

2023-08-24 02:55 UTC, aaaperfect commented on app/Http/Controllers/PostsController.php
> +        $query = Post::query();
こちらのquery()メソッドについて調べたのですが、
具体的にどのような処理を行なっているのか理解できませんでした。

ここではpostsテーブルとデータのやり取りをする上で必要ということでしょうか？

2023-08-24 02:57 UTC, aaaperfect commented on app/Http/Controllers/PostsController.php
> +            $query->where('text', 'LIKE', "%{$keyword}%");//←$queryに代入？
入力されたキーワードに該当するレコードを$queryに代入しているということでしょうか？

2023-08-24 02:59 UTC, aaaperfect commented on resources/views/posts/search.blade.php
> +        @endif
検索結果がなかった場合に表示したいのですが、表示する事ができませんでした。
ヒントをいただきたいです。よろしくお願いたします。

2023-08-24 08:37 UTC, yukihiroLaravel requested changes
コメントなどで解説しましたのでご確認ください！

2023-08-24 08:37 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $query = Post::query();
これはクエリビルダというもので、
裏側でSQLを用いてデータベースの検索を行っています！
この時点だとpostsテーブル全件をとってきている感じですね！

2023-08-24 08:37 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +            $query->where('text', 'LIKE', "%{$keyword}%");//←$queryに代入？
postのテキストに含まれるキーワード（前後に文字がある場合もない場合も含む）に合致するかを検索しています。

全件取得したあとにwhereで条件をつけて、そこから絞り込む処理ですね。
代入しているのではないです！

2023-08-24 08:37 UTC, yukihiroLaravel commented on resources/views/posts/search.blade.php
> +        @endif
おそらくですが、
@elseではなく

```
@if ($posts->count == 0)
```

みたいにすればうまくいく気がします！

2023-08-26 13:39 UTC, yukihiroLaravel requested changes
きちんと動いているのでOKですが
仕様的な部分などを指摘しましたので
ご確認願います。

宜しくお願いします🙇‍♂️

2023-08-26 13:39 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        // dd($posts);
ここは消しておいても良いんじゃないでしょうか？

2023-08-26 13:39 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::get('index', 'PostsController@index')->name('posts.index');
今更ですが、ログインしていなくても検索機能は使えたほうがいいと思うのですが
いかがでしょうか？

2023-08-26 13:39 UTC, yukihiroLaravel commented on resources/views/posts/search.blade.php
> +@section('content')
今更ですが、検索結果画面にも検索ボックスは存在して
さらに検索できるような仕様の方が再検索したい場合にやりやすいと思います！

2023-08-26 13:39 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +            </div>
検索ボックスの場所ですが、個人的にここではなく
中央寄せでおいておいた方が見やすいと思いました！

2023-08-27 02:32 UTC, aaaperfect commented on app/Http/Controllers/PostsController.php
> +        // dd($posts);
削除しました。

2023-08-27 02:32 UTC, aaaperfect commented on routes/web.php
> +        Route::get('index', 'PostsController@index')->name('posts.index');
ログインしていなくても検索機能を使えるように修正しました！

2023-08-27 02:33 UTC, aaaperfect commented on resources/views/posts/search.blade.php
> +@section('content')
ヘッダーの真ん中に置くように修正しました！

2023-08-27 14:26 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした！☺️

2023-08-27 14:27 UTC, merged