#555 投稿編集画面・更新(seiichi)
yukihiroLaravel/joint_develop pull request #638
Opened 2023-08-26 01:35 UTC by seiichi15

## issues
- Closes #555

## 概要
- 投稿編集画面・更新処理

## 動作確認手順
- ローカル環境でTopic Postsトップページよりログインし、ログインしたユーザーアカウントの投稿のみに編集ボタンが表示されていることを確認。
- 編集ボタンを押して編集画面への遷移を確認。投稿テキスト表示と、更新ボタンの表示を確認。
- 投稿テキストを変更し、更新ボタンを押すと、ログイン時の投稿表示画面に戻り変更したテキストが反映されていることを確認。

## 確認して欲しい箇所
- 各コードのもっと良い書き方が出来ないか
- インデントや空行修正箇所がないか

2023-08-26 05:08 UTC, seiichi15 commented
## コンフリクト解消
- 今回のタスク開始前に最新化したつもりでしたが、凡ミスで出来ていなかったようです。
以後確認を怠らず、注意します。

2023-08-26 05:11 UTC, seiichi15 commented
フォルダ名は　Requests　→　Request　に戻しました。

2023-08-26 08:22 UTC, yukihiroLaravel requested changes
ログインユーザIDと投稿の作成者のユーザIDの照合までできているのは
すばらしいですね！

ただ、不要な記述も多めだったので、
Laravel応用を真似してもいいですが、
「なぜ」それぞれの１行が必要なのか？
を考えながら実装していきましょう。

修正宜しくお願いします！

2023-08-26 08:22 UTC, yukihiroLaravel commented on resources/views/posts/edit.blade.php
> +<h2 class="mt-5">投稿を編集する</h2>
空欄の状態で更新ボタンを押してテストされましたでしょうか？
エラーが出ないのでこの辺りにエラーメッセージを置いておく必要があります！

2023-08-26 08:22 UTC, yukihiroLaravel commented on resources/views/posts/edit.blade.php
> +                <textarea id="content" class="form-control" name="text" rows="6">{{  old('text', $post->text) }}</textarea>
{{  old('text', $post->text) }}
ではなく
{{ old('text', $post->text) }}
とスペースは１つでOKです

2023-08-26 08:22 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        }
dataのところもインデントつけましょう！

```
       if ($post->user_id === \Auth::id()) {
            $data=[
                'post' => $post,
            ];
            return view('posts.edit', $data);
       }
```

2023-08-26 08:22 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $user = \Auth::user();
この$userは結局viewでもコントローラでも使われていないですよね？
であれば不要だと思います！

2023-08-26 08:22 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +            'user' => $user,
この$userは結局viewでもコントローラでも使われていないですよね？
であれば不要だと思います！

2023-08-26 08:22 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::delete('{id}', 'PostsController@destroy')->name('post.delete');
この３つのコントローラのメソッドと
ルーティングの記述は不要だと思うので消しましょう！

2023-08-26 13:44 UTC, yukihiroLaravel requested changes
まだ不十分な箇所がありましたので修正願います！

恐縮ながら動作確認不足が否めないので、
必ずお手本通りになっているか？の動作確認は行いましょう！

2023-08-26 13:44 UTC, yukihiroLaravel commented on resources/views/posts/edit.blade.php
> +</ul>
これだと、ずっと
「投稿は、必ず指定してください。」
がでっぱなしじゃないですか？

何度も言いますがきちんとお手本通りになるか動作確認しましょう。

バリデーションエラーをおこなっている同じアプリの他の箇所を参考に記述してください！

2023-09-01 12:01 UTC, yukihiroLaravel requested changes
細かい点ですが１点だけ指摘しました！ご確認おねがいします！

2023-09-01 12:01 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        }
こちらインデントがおかしいので

```
if ($post->user_id === \Auth::id()) {
        $data = [
            'post' => $post,
        ];
        return view('posts.edit', $data);
}
```
こんな感じで描かないといけないかと思います！

2023-09-02 04:01 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした！

2023-09-02 04:01 UTC, merged