フォローによるタイムライン変更を実装(DAIKI)
yukihiroLaravel/joint_develop pull request #642
Opened 2023-09-01 23:46 UTC by i-k-i-a-d

・フォローしている人とフォロワーを一覧で表示するbladeファイルを作成。
・新しく作った2つのbladeファイルを表示させるためのルーティングとUserController内のメソッドをそれぞれ作成。
・タブをクリックするとそれぞれのタブがアクティブになるように三項演算子で条件分岐作成。
・フォロー、フォロー解除後のリダイレクト処理をback();関数を使って修正。
・ログイン者が自分のユーザー詳細画面の中のフォロー中のタブを開くとフォローを解除するボタンが表示されるように実装。
・ログイン者が自分のフォロワータブを開き、もし、フォロワーをログイン者がフォローしていないときは、フォローするボタンが表示されるように実装。

ベストプラクティスかは自身ありませんが、とりあえず動くものには仕上がってます。
レビューよろしくお願いします。

2023-09-02 04:20 UTC, Osk0830 requested changes
お疲れ様でした。
全体的によくできていると思います。
少しだけコメントしましたので、確認よろしくお願いします。

2023-09-02 04:20 UTC, Osk0830 commented on resources/views/users/detail.blade.php
> +            <li class="nav-item"><a href="" class="nav-link {{ Request::route()->named('users.show') ? 'active' : '' }}">タイムライン</a></li>
- これでも間違いないではないですが、下記記事②の `Request::routeIs()`を用いるともう少しだけ処理がスマートになり記述も短くなりますので、今回の場合はこちらの方がいいかもですね。

https://shiro-changelife.com/laravel-url-judge/

2023-09-02 04:20 UTC, Osk0830 commented on resources/views/users/followed.blade.php
> +            <li class="nav-item"><a href="" class="nav-link {{ Request::route()->named('users.followed') ? 'active' : '' }}">フォロワー</a></li>
- こちらについては前述の通りです。

2023-09-02 04:20 UTC, Osk0830 commented on resources/views/users/followed.blade.php
> +            @foreach($user->followers()->get() as $follow)
- ここでデータを取得することも可能ですが、今後フォローとフォロワーの共通部分を部品化することを考えると、フォローの場合とフォロワーの場合とでBladeの記述を最大限同じにしておくことが望ましく、BladeごとにBlade内で異なるメソッドを実行しなければならない状況は色々と不便さを助長します。今回は、コントローラーの各アクション内でデータを取得してBladeに渡す形にしておきましょう。

2023-09-02 04:20 UTC, Osk0830 commented on resources/views/users/followed.blade.php
> +                    </div>
- <div class=""></div>がif文の外にあるため、条件に合致しなかった際に不要な空<div>ができてしまわないでしょうか？
- ボタン表示の理屈と内容は現状でOKだと思います。ただ、今後部品化を図っていくことになると、少し変更を加える必要が出てきそうですが、そちらについては次のタスクで考えてみるようにしましょう。

2023-09-03 02:15 UTC, i-k-i-a-d commented on resources/views/users/detail.blade.php
> +            <li class="nav-item"><a href="" class="nav-link {{ Request::route()->named('users.show') ? 'active' : '' }}">タイムライン</a></li>
そんな記述方法があったとは知りませんでした。
勉強になります。

2023-09-03 02:15 UTC, i-k-i-a-d commented on resources/views/users/followed.blade.php
> +            <li class="nav-item"><a href="" class="nav-link {{ Request::route()->named('users.followed') ? 'active' : '' }}">フォロワー</a></li>
修正しました。

2023-09-03 02:16 UTC, i-k-i-a-d commented on resources/views/users/followed.blade.php
> +            @foreach($user->followers()->get() as $follow)
部品化の意味ようやく理解しました。
この作業が部品化という呼ばれ方をするのはエンジニア共通認識でしょうか？？

2023-09-03 02:17 UTC, i-k-i-a-d commented on resources/views/users/followed.blade.php
> +                    </div>
完全に見落としでした。
htmlでの記述場所も意識しておかないといけないですね。

2023-09-04 01:49 UTC, Osk0830 commented on resources/views/users/followed.blade.php
> +            @foreach($user->followers()->get() as $follow)
部品化、パーツ化と言ったり、コンポーネント化と言うことが多い気がします。

2023-09-04 01:50 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKなのでマージしますね！

2023-09-04 01:53 UTC, merged