タブの部品化(DAIKI)
yukihiroLaravel/joint_develop pull request #644
Opened 2023-09-04 12:28 UTC by i-k-i-a-d

・タイムラインタブ・フォロー中タブ・フォロワータブを構成する3つのbladeファイルの共通部分をtemplate.blade.phpファイルにまとめた。
・3つのタブ用のbladeでtemplate.blade.phpファイルを読み込めるように実装。

レビューよろしくお願いします。

2023-09-05 04:02 UTC, Osk0830 requested changes
お疲れ様でした。
パーツ化のとっかかりはだいぶできてきているのではないかと思います。
部品化は、案件やルールによって、何をどう部品化するかが変わってくるものなので絶対解があるわけではないという点だけご理解いただいた上で、いくつか意見を書かせていただきましたので検討よろしくお願いします。

2023-09-05 04:02 UTC, Osk0830 commented on resources/views/layouts/template.blade.php
> +@endsection
- `template.blade.php`という名称はあまりに汎用的すぎて、どのページに用いるテンプレートなのかが伝わらず、また今後の拡張の可能性などに鑑みても、再考してみた方がよくないでしょうか？

2023-09-05 04:02 UTC, Osk0830 commented on resources/views/layouts/template.blade.php
> +    </div>
- この辺、インデントがおかしくなっているようです。再度調整してみてください。

2023-09-05 04:02 UTC, Osk0830 commented on resources/views/layouts/template.blade.php
> +        <div class="m-auto" style="width: fit-content"></div>
- この空 divはなんのためのものでしょうか？

2023-09-05 04:02 UTC, Osk0830 commented on resources/views/users/followed.blade.php
> +</ul>
- この部分、ユーザーのリスト＋状況に応じてボタンが表示される、という点では、フォロータブもフォロワータブも同じではないでしょうか？ボタンだけ汎用的に使える形にしておけば、この部分を一つの部品として書き出してしまって、それぞれのBladeで`include`するような形にした方がすっきりしますし、メンテナンス性も向上すると思います。他の観点として、そもそもフォロー用のBladeとフォロワー用のBladeは別々にせず、同じものを用いる、という選択も可能かもしれないですね。

2023-09-05 04:02 UTC, Osk0830 commented on resources/views/layouts/template.blade.php
> +                    @endif
- ボタンだけ考えると、もしかしたらこの辺も、フォローページ・フォロワーページで使っているボタンと共通のものとして処理する可能性もあるかもしれませんね。もちろん、検討してみて共通部品化は困難、となるかもしれませんが、あくまでも可能性として書かせていただきました。

2023-09-05 21:42 UTC, i-k-i-a-d commented on resources/views/layouts/template.blade.php
> +@endsection
改名しました。

2023-09-05 21:43 UTC, i-k-i-a-d commented on resources/views/layouts/template.blade.php
> +    </div>
無駄なスペースがあったので削除しております。

2023-09-05 21:44 UTC, i-k-i-a-d commented on resources/views/layouts/template.blade.php
> +        <div class="m-auto" style="width: fit-content"></div>
モックアップからコピペしただけなので元からあったようです。
確認したところ、コンテンツを中央ぞろえするためのdivのようです。ここでは不要と判断し削除しております。

2023-09-05 21:45 UTC, i-k-i-a-d commented on resources/views/users/followed.blade.php
> +</ul>
フォロー用のbladeとフォロワー用のbladeを統合し、条件分岐で表示を切り替えれるように実装しました。

2023-09-05 21:48 UTC, i-k-i-a-d commented on resources/views/layouts/template.blade.php
> +                    @endif
検討しましたが、ボタンのaction属性のroute関数の第二引数でrouteに渡す値が異なるため共通化は困難と判断し、今回はボタンの部品化は見送りました。
また、最終期限が近く、実装したいコンテンツもまだまだたくさんあるため、あまりここに時間を使いたくないため今回はこれでよろしくお願いします。

2023-09-07 05:25 UTC, Osk0830 approved these changes
お疲れ様でした！
こちら前回のレビューで書いたインデントの問題が残ってますが、
内容的にはOKだと思いますので、マージしますね！

2023-09-07 05:25 UTC, Osk0830 commented on resources/views/layouts/tab.blade.php
> +    </ul>
- 前回お伝えしたこの部分のインデントの問題が解消されていないようです。

2023-09-07 05:25 UTC, merged