投稿削除フラッシュメッセージ表示(seiichi)
yukihiroLaravel/joint_develop pull request #647
Opened 2023-09-07 14:35 UTC by seiichi15

## issues
- Close 投稿削除フラッシュメッセージ

## 概要
- 投稿削除時のフラッシュメッセージ表示機能追加

## 動作確認手順
- トップページからログインした状態で、ログインユーザーの投稿を削除した時に
投稿が削除されると共に「投稿削除に成功しました」というフラッシュメッセージが
表示される事を確認

2023-09-08 00:33 UTC, yukihiroLaravel requested changes
１点コメントしました！
よろしくおねがいします！

2023-09-08 00:33 UTC, yukihiroLaravel commented on resources/views/posts/edit.blade.php
> +    </div>
インデントとdivの位置がちょっと良くないので
このように変えましょう！
```
@if (session('postsDestroyMessage'))
      <div class="w-75 m-auto">
            <div class="alert alert-success text-center">
                {{ session('postsDestroyMessage') }}
            </div>
      </div>
@endif
```

2023-09-09 03:08 UTC, seiichi15 commented on resources/views/posts/edit.blade.php
> +    </div>
修正しました！

2023-09-09 03:54 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
お疲れ様でした！

2023-09-09 03:55 UTC, merged