いいね機能実装(DAIKI)
yukihiroLaravel/joint_develop pull request #648
Opened 2023-09-07 23:19 UTC by i-k-i-a-d

・いいね機能のための多対多用中間テーブルを作成するにあたってマイグレーションファイルを作成。
・いいねといいね解除用のルーティングと専用のLikeControllerを作成。
・UserモデルとPostモデルにリレーションメソッドを作成。
・Userモデル内にいいねといいね解除のメソッドを作成。
・LikeController内にいいねといいね解除のメソッドを呼び出すメソッドを作成。
・Userモデル内にいいね状態をチェックするメソッドを作成。
・トップページとユーザー詳細ページにいいねといいね解除のボタンを作成。
・トップページとユーザー詳細ページにいいねの数を表示させるように実装。
・tab.blade.phpファイルのインデントがおかしかったので修正。

2023-09-09 08:52 UTC, Osk0830 requested changes
お疲れ様でした！
ロジック的には問題ないと思います！
いくつかコメントしましたので、確認よろしくお願いします。

2023-09-09 08:52 UTC, Osk0830 commented on app/User.php
> +        $post = Post::find($id);
- `$id`に該当する投稿がなかった場合にサーバーエラーにならないよう、`findOrFail()`メソッドを使うようにするといいかもです。

2023-09-09 08:52 UTC, Osk0830 commented on app/User.php
> +        if (Auth::id() !== $post->User_id && !$this->likeCheck($id)) {
- $post->User_id`の`U`は小文字ではないでしょうか？

2023-09-09 08:52 UTC, Osk0830 commented on app/User.php
> +        $post = Post::find($id);
- こちらも念のため。

2023-09-09 08:52 UTC, Osk0830 commented on resources/views/posts/top.blade.php
> +                            <p>
- この部分に `<p>`を用いるのは、HTML的におかしいです。

2023-09-09 08:52 UTC, Osk0830 commented on resources/views/posts/top.blade.php
> +                                    @endif
- この部分は `<form>`内に含まれる必要はなさそうです。`<form>`とこのボタン部分を大きく`<div>`で囲いそこにflex指定すれば横に並びます。

2023-09-09 08:52 UTC, Osk0830 commented on resources/views/posts/top.blade.php
> +                        <p>
- 上と同じく<p>はおかしいです。
- ログインしていない時はボタンはなくてもよくないでしょうか？

2023-09-09 08:52 UTC, Osk0830 commented on resources/views/users/detail.blade.php
>                  </div>
- こうなることを考えても、前回のタスクでお伝えしたように、個人的には投稿一覧を表示する部分は、こことトップで共通して用いる部品として切り出すのが、作業効率が格段にあがるような気がします。
- そうしなくてももちろんOKです。その場合は、トップに書いた内容と同様の対応、こちらでもお願いします。

2023-09-09 12:04 UTC, i-k-i-a-d commented on app/User.php
> +        $post = Post::find($id);
このメソッド初めて知りました。エラーの詳細をユーザーに見えなくできるのは便利ですね。

2023-09-09 12:05 UTC, i-k-i-a-d commented on app/User.php
> +        if (Auth::id() !== $post->User_id && !$this->likeCheck($id)) {
見落としてました。というよりもカラム名って大文字・小文字を区別してないんですね。

2023-09-09 12:05 UTC, i-k-i-a-d commented on app/User.php
> +        $post = Post::find($id);
修正しました。

2023-09-09 12:06 UTC, i-k-i-a-d commented on resources/views/posts/top.blade.php
> +                            <p>
僕も不自然だなとは思ってました。divタグに変えておきました。

2023-09-09 12:07 UTC, i-k-i-a-d commented on resources/views/posts/top.blade.php
> +                                    @endif
class属性でd-flexを指定すると、確かに横並びにはなりますが、レイアウトが少し崩れたので、formタグをインライン要素に変えてやりました。

2023-09-09 12:09 UTC, i-k-i-a-d commented on resources/views/posts/top.blade.php
> +                        <p>
divタグに変えました。

あと、ここに関しては、twitterやyoutubeなどもログインしてなくてもいいねボタンがついており、ログインしてないときに押すとログイン画面へ誘導される仕様になっているので、ここはあえてこのように実装しております。

2023-09-09 12:09 UTC, i-k-i-a-d commented on resources/views/users/detail.blade.php
>                  </div>
ここに関しては完全に同じHTMLを使いまわせるので、部品化いたしました。

2023-09-11 05:59 UTC, Osk0830 approved these changes
お疲れ様でした。
こちらマージしますね。

2023-09-11 06:00 UTC, merged