アプリ表題テキスト変更（ユーザー詳細・編集画面以外動作確認）（seiichi）
yukihiroLaravel/joint_develop pull request #650
Opened 2023-09-11 13:48 UTC by seiichi15

## issues
- アプリ表題テキスト変更

## 概要
- アプリ表題のテキストを変更（Topic Posts→生活の知恵袋）
- ユーザー詳細・編集画面以外の動作確認実施

## 動作確認手順
- 以下の画面でそれぞれタイトル・ヘッダーのタイトル等が変更されている事を確認しました
- アプリトップページ
- ログイン後トップページ
- 新規ユーザー登録画面
- 投稿編集画面

- ユーザー詳細・編集画面はまだマージ前なので、動作確認未実施です

2023-09-13 15:29 UTC, yukihiroLaravel requested changes
１点コメントしたのと
あと、PostsTableSeederは変更しないのですか？

2023-09-13 15:29 UTC, yukihiroLaravel commented on database/seeds/UsersTableSeeder.php
> +        ]);
ここすべて、配列が無駄に１つ多く入れ子構造になってないですか？

```
DB::table('users')->insert([
                'name' =>'jyunpei',
                'email' => 'jyunpei@.com',
                'password' => bcrypt('jyunpei'),
]);
```

これでいい気がします！

2023-09-14 11:31 UTC, seiichi15 commented on database/seeds/UsersTableSeeder.php
> +        ]);
修正しました。
新規投稿内容にばかり考えがいって、既存投稿の変更をあまり考えていませんでした。
ポストシーダーで既存の投稿内容も修正しました。
併せてユーザー情報の編集機能でユーザー名も変更し、新規投稿も追加しました。

2023-09-14 11:56 UTC, yukihiroLaravel requested changes

2023-09-14 11:56 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +            'user_id' => 4,
こちらユーザーのシーダーに
id4の人は現状いないため
このまま実行するとエラーになると思います！

なので、
user_id は1〜3にしましょう！

2023-09-14 12:21 UTC, seiichi15 commented on database/seeds/PostsTableSeeder.php
> +            'user_id' => 4,
ポストシーダーでユーザーid4・5を削除しました。

2023-09-14 12:28 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした！

2023-09-14 12:28 UTC, merged