共通ファイル・ヘッダー・フッター＆トップページのタイトル表示「Topic Posts」
yukihiroLaravel/joint_develop pull request #721
Opened 2023-09-17 08:02 UTC by RahmatRamdani85

2023-09-17 12:54 UTC, yukihiroLaravel requested changes
全体的にいい感じにできていますね！

ただ、他の方が担当の内容も含まれていたため
すみませんが、そちらの内容などを元に戻す対応など
お願いいたします！

2023-09-17 12:54 UTC, yukihiroLaravel commented on resources/lang/ja/validation.php
> +<?php
こちらのファイルは別のタスクで作成するファイルですので
すみませんが一旦消してください！

2023-09-17 12:54 UTC, yukihiroLaravel commented on resources/lang/ja/passwords.php
> +<?php
こちらのファイルは別のタスクで作成するファイルですので
すみませんが一旦消してください！

2023-09-17 12:54 UTC, yukihiroLaravel commented on resources/lang/ja/pagination.php
> +<?php
こちらのファイルは別のタスクで作成するファイルですので
すみませんが一旦消してください！

2023-09-17 12:54 UTC, yukihiroLaravel commented on resources/lang/ja/auth.php
> +<?php
こちらのファイルは別のタスクで作成するファイルですので
すみませんが一旦消してください！

2023-09-17 12:54 UTC, yukihiroLaravel commented on config/app.php
> +    'locale' => 'ja',
こちらの日本語化は別のタスクで対応予定なので
すみませんが一旦元の英語に戻してください！

2023-09-17 12:54 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +class UsersController extends Controller
トップページは、誰が投稿したかに関わらず、
投稿一覧を表示している形になるので
こちらのファイル名とクラス名は

```
PostsController
```

の方が適切かと思います！

2023-09-17 12:54 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('/', 'UsersController@index');
トップページは、誰が投稿したかに関わらず、
投稿一覧を表示している形になるので
こちらのファイル名とクラス名は

PostsController
の方が適切かと思います！

2023-09-18 08:09 UTC, RahmatRamdani85 commented
トップページを修正しました。
ご確認お願い致します。

2023-09-18 10:17 UTC, RahmatRamdani85 commented on resources/lang/ja/validation.php
> +<?php
こちらはも消しました。

2023-09-18 10:17 UTC, RahmatRamdani85 commented on resources/lang/ja/passwords.php
> +<?php
こちらはも消しました。

2023-09-18 10:17 UTC, RahmatRamdani85 commented on resources/lang/ja/pagination.php
> +<?php
こちらはも消しました。

2023-09-18 10:17 UTC, RahmatRamdani85 commented on resources/lang/ja/auth.php
> +<?php
こちらはも消しました。

2023-09-18 10:18 UTC, RahmatRamdani85 commented on config/app.php
> +    'locale' => 'ja',
こちらはenに戻りました。

2023-09-18 10:19 UTC, RahmatRamdani85 commented on app/Http/Controllers/UsersController.php
> +class UsersController extends Controller
ファイル名を変更されました。

2023-09-18 12:54 UTC, yukihiroLaravel approved these changes

2023-09-18 12:54 UTC, merged