Feature/naoki yy/register users
yukihiroLaravel/joint_develop pull request #724
Opened 2023-09-20 13:47 UTC by naoki-yy

## issue 
- Closes #667   

## 概要 
- ユーザ新規登録

## 動作確認手順 
- http://localhost:8080/signup　にアクセスしてユーザの新規登録を行ない、
Adminerでusersテーブルに保存されているか確認
（下記、確認してほしいこと参照）

## 考慮してほしいこと 

- 状況に応じて、下記コマンドで動作確認する必要あり。 

php artisan migrate:fresh --seed 

## 確認してほしいこと 
- http://localhost:8080/signup　にアクセスしてユーザの新規登録を行なっても
ユーザテーブルに情報が反映されません。
しかし、tinkerを使ってユーザ登録を行うと、ユーザテーブルに情報が保存されています。

2023-09-23 09:08 UTC, Osk0830 requested changes
お疲れ様です！
内容的にはほぼ問題ないと思います！

少しだけコメントしましたので、確認よろしくお願いします！

2023-09-23 09:08 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +    </div>
- 全体的にインデントが揃っていない部分がありますので、インデントを綺麗に揃えてみてください。

2023-09-23 09:08 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +                    <input id="password_confirmation" type="password" class="form-control" name="password_confirmation" value="{{ old('password_confirmation') }}">
- パスワード関連は、バリデーションで弾かれて戻ってきた際にも、以前の入力データが表示されず、再入力させるのがいいと思います。なお、`old()`を用いない際は、`value属性`自体不要です。

2023-09-24 03:18 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらしっかり修正できているのでマージしますね！

引き続き頑張っていきましょう！

2023-09-24 03:18 UTC, merged

2023-09-24 08:03 UTC, naoki-yy commented on resources/views/auth/register.blade.php
> +    </div>
対応しました。

2023-09-24 08:03 UTC, naoki-yy commented on resources/views/auth/register.blade.php
> +                    <input id="password_confirmation" type="password" class="form-control" name="password_confirmation" value="{{ old('password_confirmation') }}">
対応しました。