#682 ユーザログイン・ログアウト
yukihiroLaravel/joint_develop pull request #729
Opened 2023-09-24 11:06 UTC by Jino225242

## issue
- Closes #682 

## 動作確認手順
- 下記URLにアクセスの上、ヘッダーの「ログイン」をクリックすると、ログインフォームが表示されること
　[http://localhost:8080](http://localhost:8080)
- 下記URLにアクセスの上、１と同様に ログインフォームが表示されること
　[http://localhost:8080/login](http://localhost:8080/login)
- 下記URLにアクセスの上、トップページが表示されること 
　[http://localhost:8080/logout](http://localhost:8080/logout)

## 考慮して欲しいこと
- 「ユーザ新規登録」がマージされていないため、ログイン自体は未実装

## 確認して欲しいこと
特になし

2023-09-25 16:03 UTC, yukihiroLaravel requested changes
お手数ですが、修正お願いします！

2023-09-25 16:03 UTC, yukihiroLaravel commented on app/Http/Controllers/Auth/LoginController.php
> +    protected $redirectTo = '/';    //ログイン後はトップページへ遷移するように変更
下記ファイル
app/Providers/RouteServiceProvider.php
の HOME 定数を
をスラッシュ(トップページ)に書き換えるのであれば、
ここは書き換えなくて良いと思います！

2023-09-25 16:03 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('logout','Auth\LoginController@logout')->name('logout');
お伝えの通りここを
middleware('auth')
で囲わないといけないですかね

2023-09-25 17:30 UTC, Jino225242 commented on routes/web.php
> +Route::get('logout','Auth\LoginController@logout')->name('logout');
ここをmiddleware('auth')で囲んでしまうと、誰もログインできない状態になってしまうと思うのですが、
middleware('auth')で囲むのは、
ログインユーザーに表示する必要がある以下のようなルータだと認識しているのですが、私の理解誤りでしょうか。
```
// ログイン後
Route::group(['middleware' => 'auth'], function () {
    // 投稿
    Route::prefix('posts')->group(function () {
        Route::get('{id}/edit', 'PostsController@edit')->name('post.edit');
        Route::put('{id}', 'PostsController@update')->name('post.update');
        Route::delete('{id}', 'PostsController@destroy')->name('post.delete');
    });
```

指摘いただいた部分を
```
Route::middleware(['auth'])->group(function () {
    Route::post('login', 'Auth\LoginController@login')->name('login.post');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
});
```
と変更したところ、ログインできなくなってしまいました。。。

2023-09-25 17:32 UTC, Jino225242 commented on app/Http/Controllers/Auth/LoginController.php
> +    protected $redirectTo = '/';    //ログイン後はトップページへ遷移するように変更
修正完了。（元の'RouteServiceProvider::HOME;' に戻し、完了。）
失礼いたしました。
app/Providers/RouteServiceProvider.php
の HOME 定数をを'/'スラッシュ(トップページ)に書換え後、反映失念してしておりました。

2023-09-26 02:28 UTC, yukihiroLaravel approved these changes
問題ないのでマージしました！

僕が認識を間違っていた部分があり、余計な指摘をしてしまいすみませんでした🙇‍♂️
動画で解説しましたが、
引き続き何かあれば聞いてください。よろしくお願いします！

https://www.loom.com/share/de880de77e5d4482b8fce55d792e423f?sid=68cbba09-6536-4305-aeac-8505e9da044a

2023-09-26 02:29 UTC, merged