#700 共通ファイル&ヘッダー・フッター & トップページのタイトルのみ表示「Topic Posts」 （ふるさわ）
yukihiroLaravel/joint_develop pull request #730
Opened 2023-09-25 14:00 UTC by furusawa501

## issue
- Closes
 #700 

## 概要
- 共通ファイル&ヘッダー・フッター & トップページのタイトルのみ表示「Topic Posts」

## 動作確認手順
- http://localhost:8080/
を表示。

## 考慮して欲しいこと
- 特にありません

## 確認して欲しいこと
- 特にありません

2023-09-26 13:09 UTC, Osk0830 requested changes
お疲れ様でした！
概ね良くできていると思います！

少しだけコメントしましたので、
確認よろしくお願いします！

2023-09-26 13:09 UTC, Osk0830 commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="" class="nav-link text-light">新規ユーザ登録</a></li>
- こちら、`<ul>`の閉じタグが抜けてませんでしょうか？

2023-09-26 13:09 UTC, Osk0830 commented on resources/views/layouts/app.blade.php
> +        </div>
- これですとただの空要素になってしまいますね。`.container`はBootstrapでも用いるクラスですが、お手本サイトのソースを見たりしながら、この`<div>`がどこに来るべきか検討してみましょう。

2023-09-29 12:59 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKなのでマージしますね！

2023-09-29 12:59 UTC, merged

2023-09-29 13:53 UTC, furusawa501 commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="" class="nav-link text-light">新規ユーザ登録</a></li>
ありがとうございます。確認しました

2023-09-29 14:44 UTC, furusawa501 commented on resources/views/layouts/app.blade.php
> +        </div>
コメントありがとうございます。
エラーメッセージが表示される部分ではないかと思っていましたが、自信がなかったため空にしていました。