posts(投稿)テーブルのマイグレーションとシーダー作成(yasuyuki)
yukihiroLaravel/joint_develop pull request #731
Opened 2023-09-25 21:24 UTC by YasuLaravel

##issue
-closes　

##概要
-posts（投稿）テーブルのマイグレーションとシーダー作成

##動作確認手順
-下記コマンドを実行
php artisan migrate --seed
-Adminerでpostテーブルに12個のレコードが保存されていることを確認

##考慮してほしいこと
・特になし

##確認してほしいこと
・app/User.phpに追加したものは今回必要か
・database/migrations/2023_09_20_125808_create_posts_table.php内の外部キー制約をコメントアウトしているが、
このままでいいか

2023-09-28 02:36 UTC, Osk0830 requested changes
お疲れ様でした！
こちら基本的には問題ないと思います！

修正が必要な箇所いくつかコメントしましたので、
確認よろしくお願いします！

2023-09-28 02:36 UTC, Osk0830 commented on app/Post.php
> +}
- こちら今回のタスクの範囲外になる部分ですので、現段階では削除しておいてください。

2023-09-28 02:36 UTC, Osk0830 commented on app/User.php
>  }
- こちらも同様の理由から、今回は削除しておきましょう。

2023-09-28 02:36 UTC, Osk0830 commented on database/migrations/2023_09_20_125808_create_posts_table.php
> +            //$table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
- チームのブランチをご覧いただくと、既にユーザーのマイグレーション＆シーダーはマージされてますので、こちらはコメントアウトする必要なないです。

[![Image from Gyazo](https://i.gyazo.com/0c7e2c8d7fb39bf8d149ad20155f29c9.png)](https://gyazo.com/0c7e2c8d7fb39bf8d149ad20155f29c9)

2023-09-28 02:36 UTC, Osk0830 commented on database/seeds/PostsTableSeeder.php
> +        ]);
- ユーザーのシーディングファイルを見ると、ユーザーは4件登録されており、`user_id`は4までしか存在しないことになりますので、このままだとエラーになってしまいます。`user_id`の箇所には`1〜4`の値をランダムに入れるようにしましょう。

[![Image from Gyazo](https://i.gyazo.com/71ee5695328f52f3f60570a8f91eccf8.png)](https://gyazo.com/71ee5695328f52f3f60570a8f91eccf8)

2023-09-29 23:05 UTC, YasuLaravel commented on app/Post.php
> +}
こちらファイルごと削除しました

2023-09-29 23:06 UTC, YasuLaravel commented on app/User.php
>  }
対象箇所削除しました

2023-09-29 23:06 UTC, YasuLaravel commented on database/migrations/2023_09_20_125808_create_posts_table.php
> +            //$table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
コメントアウト外しました

2023-09-29 23:06 UTC, YasuLaravel commented on database/seeds/PostsTableSeeder.php
> +        ]);
訂正しました

2023-10-01 01:25 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKですのでマージしますね！
引き続き頑張っていきましょう！

2023-10-01 01:26 UTC, merged