#701 posts（投稿）テーブルのマイグレーションとシーダー作成(寺島)
yukihiroLaravel/joint_develop pull request #733
Opened 2023-09-27 09:07 UTC by daihubemmono

## issue
- Closes #719

## 概要
- posts（投稿）テーブルのマイグレーションとシーダー作成

## 動作確認手順
- 下記コマンドを実行。
php artisan migrate

## 考慮して欲しいこと
- 状況に応じて、下記コマンドで動作確認する必要あり。
php artisan migrate:fresh --seed

## 確認してほしいこと

2023-09-28 01:49 UTC, Osk0830 requested changes
お疲れ様でした！
こちらほぼ問題なくできていると思います！

少しだけコメントしましたので、確認よろしくお願いします！

2023-09-28 01:49 UTC, Osk0830 commented on database/migrations/2023_09_20_213117_create_posts_table.php
> +            $table->bigInteger('user_id')->unsigned()->index();
- こちら内容的には問題ないですが、こちらで置いた順序でDBにカラムが生成され並ぶことになりますので、今の状態ですとタイムスタンプ関連の2つのカラムが前に来てしまいAdminerで中身を確認する際などに見にくくなってしまいます。タイムスタンプは、user_idの次あたりに置くといいですね。

2023-09-28 01:49 UTC, Osk0830 commented on database/migrations/2023_09_20_213117_create_posts_table.php
> +            $table->string('content')->nullable(false);
- `nullable(false)`はあえて無くても大丈夫そうな感じはします。あっても間違いではないです。

2023-09-28 01:49 UTC, Osk0830 commented on database/seeds/PostsTableSeeder.php
> +    }
- ダミーデータとしては数が少し少ない気がします。今後ページネーションの確認などもすぐにできるよう、10件くらいは登録しときたいところです。
- `content`の内容は、投稿のダミーテキストだと分かるよう、「投稿の本文です。」などにしておいてあげるとより良さそうですね。

2023-10-01 23:11 UTC, daihubemmono commented on database/migrations/2023_09_20_213117_create_posts_table.php
> +            $table->bigInteger('user_id')->unsigned()->index();
承知しました。
timestampsをuser_idの次に移します。

2023-10-01 23:12 UTC, daihubemmono commented on database/migrations/2023_09_20_213117_create_posts_table.php
> +            $table->string('content')->nullable(false);
あっても間違いではないのなら一応残しておきます。

2023-10-01 23:22 UTC, daihubemmono commented on database/seeds/PostsTableSeeder.php
> +    }
１０件に増やしてcontentの内容を「投稿の本文です。」に変更しました！

2023-10-02 05:24 UTC, Osk0830 requested changes
お疲れ様です！

一箇所だけ修正が必要な箇所がありますので、
確認よろしくお願いします！

2023-10-02 05:24 UTC, Osk0830 commented on database/seeds/PostsTableSeeder.php
> +        ]);
- すでにマージされているユーザー情報のシーダーファイルを見てみますと、ユーザー情報は8人分しかないので、idは1〜8の間しかないことになりますね。こちら、変更後にシーディングを再度実行していただくとエラーが出そうですが、修正後に動作確認は行なってみましたでしょうか？
- 上記事情に鑑みて、`use_id`の値には、1〜8までの整数がランダムに入れるようにしてください。（手動でランダムに入れる感じでもOKです）

[![Image from Gyazo](https://i.gyazo.com/bac88551ec974beddf2f33b84414db78.png)](https://gyazo.com/bac88551ec974beddf2f33b84414db78)

2023-10-02 23:34 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKなのでマージしますね！

引き続き頑張っていきましょう！

2023-10-02 23:34 UTC, merged