#699 「ユーザ新規登録」機能を作成（まきの）
yukihiroLaravel/joint_develop pull request #736
Opened 2023-09-29 22:22 UTC by ma34vn

### 概要
「ユーザ新規登録」機能を作成しました。

### 動作確認手順
1. Top画面を表示
　⇨ メニューが「ログイン」「新規ユーザ登録」だけになっていることを確認
2. Top画面から「新規ユーザ登録」をクリック
　⇨ 「新規ユーザ登録』画面が表示されることを確認
3. 「新規ユーザ登録』画面で、新しいユーザ情報を入力
　⇨ Top画面に戻り、ヘッダーが「新規登録したユーザ名」「ログアウト」になっていることを確認
　⇨ Adminerでユーザ情報が格納されていることを確認

### 考慮して欲しいこと
1. users テーブルがない環境の場合は、事前に以下のコマンドを入力してテーブルを作成してください。
`php artisan migrate:fresh --seed`

2. Laravel Debugbar を入れたので、`storage/debugbar/` を .gitignore に追記しています。
### 確認してほしいこと
特にありません

2023-10-01 01:50 UTC, Osk0830 requested changes
お疲れ様でした！
基本的には全く問題ないと思います！

少しだけコメントしましたので、
確認よろしくお願いいたします。

2023-10-01 01:50 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +                </div>
- バリデーションで弾かれた際、パスワードに関しては、再入力を求める仕組みにしましょう。

2023-10-01 01:50 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +    </div>
- エラーメッセージが表示される場所がお手本サイトと異なります。共通パーツ作成時に臨時で入れてあるので、それを的確な位置に来るようにしていただければと思います。（可能であれば、現状トップページにある静的箇所も一緒に調整いただいてOKです。）

[![Image from Gyazo](https://i.gyazo.com/4c19f8b360b7abeaee49df27718fe946.png)](https://gyazo.com/4c19f8b360b7abeaee49df27718fe946)

[![Image from Gyazo](https://i.gyazo.com/91d689367a09e662545e2ce671bc3854.png)](https://gyazo.com/91d689367a09e662545e2ce671bc3854)

2023-10-01 04:49 UTC, ma34vn commented on resources/views/auth/register.blade.php
> +                </div>
お手本サイトを動かしても、エラーメッセージが表示されて「名前」「メールアドレス」にoldが入っているだけで、同じ動作をしています（ユーザ新規登録画面で再入力を促しています）。
「再入力を求める仕組み」はお手本にない仕組みのように思えますが、認識は違いますでしょうか？

2023-10-01 04:50 UTC, ma34vn commented on resources/views/auth/register.blade.php
> +    </div>
お手本と違っているのは理解しました。
register.blade.php を修正してpushしました。

welcome.blade.phpについては古澤さんがエラーメッセージの場所に気付かれてなかったのだと思います。
私が勝手に直してもよくないので、古澤さんの方で直してもらえるよう、指摘してあげていただけますでしょうか。

2023-10-02 02:09 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +                </div>
わかりにくくてすみません。「再入力を求める」というのは既存の入力値が入っていないようにする=`old()`を用いない、という意味になります。

2023-10-02 02:12 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +    </div>
こちらは、古澤さんのタスクの段階では、実際の画面がなかったりなどして少しややこしいので、新規登録もしくはログインのタスクを行ってくださった方に調整をお願いすることも多々ありまして。。。お手数ですがお願いできますでしょうか？

2023-10-02 21:57 UTC, ma34vn commented on resources/views/auth/register.blade.php
> +    </div>
古澤さんのタスクは、トップページのタイトル表示も含んでいて、モックアップのトップページには、ご丁寧に「エラーメッセージが入る場所」と書かれているので、古澤さんの作業の中で修正されるべき作業と思います。
実際のチーム開発を考えたら、人が作成した箇所を安易に他の人がやるべきではないと私は思いますので、敢えて古澤さんからの修正をお願いしました。

とりあえず修正しましたので、ご確認をお願いいたします。

2023-10-02 21:59 UTC, ma34vn commented on resources/views/auth/register.blade.php
> +                </div>
ご回答ありがとうございます。
「パスワード」と「パスワード確認」のvalueを空に変更しました。
お手本サイトもエラーの時は名前とメールアドレスは入ってるので、上記2個のことを言われていると理解しました。

2023-10-02 23:35 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +                </div>
お疲れ様でした！

2023-10-02 23:38 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +    </div>
ありがとうございます！

> 実際のチーム開発を考えたら、人が作成した箇所を安易に他の人がやるべきではないと私は思いますので、

こちらごもっともだと思います。
他のお二方の進捗が遅く、牧野さんをかなりお待たせしていた状況と、これまでもエラーメッセージの表示位置の調整はどのタスクで行うと縛りなく、どなたかのタスクで適宜お願いしてきたという経緯もあり、お願いした次第です。

対応、ありがとうございました。

2023-10-02 23:40 UTC, Osk0830 approved these changes
お疲れ様でした！
対応ありがとうございました！
こちらマージしますね。

2023-10-02 23:40 UTC, merged