Feature/rahamato/create new post
yukihiroLaravel/joint_develop pull request #738
Opened 2023-10-01 01:55 UTC by RahmatRamdani85

## Issue
Closes [#677 ]
## 概要
-　投稿新規作成
## 動作手順
-　http://localhost:8080/ 実行して、ログインして、新規投稿書いて、”投稿する”ボタンを押す。
## 確認して欲しいこと
⁻　Routeの順番とcodingno確認をお願い致します。
よろしくお願い致します

2023-10-02 01:27 UTC, yukihiroLaravel requested changes
動画とコメントでご指摘させていただきましたので
いくつか修正ねがいます

https://www.loom.com/share/e915965a0d194ba4936a7ac88e28e2d0?sid=09f74f38-9b83-4091-a6a9-138dd814bb07

2023-10-02 01:27 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +
この空行２行は不要です

2023-10-02 01:27 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +</div>
インデントを修正

2023-10-02 01:27 UTC, yukihiroLaravel commented on routes/web.php
> +
この空行２行は不要

2023-10-02 01:27 UTC, yukihiroLaravel commented on app/Http/Requests/PostRequest.php
> +            'content' => 'max:140'
何も文字がない時のバリデーション

2023-10-02 01:27 UTC, yukihiroLaravel commented on routes/web.php
> +        });
インデント修正

2023-10-02 01:27 UTC, yukihiroLaravel commented on routes/web.php
> +});
Rout::group(['middleware' => 'auth']
のカッコの外に出すべき

2023-10-02 01:27 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +        </div>
インデントを修正

2023-10-02 13:18 UTC, RahmatRamdani85 commented on routes/web.php
> +        });
この部分を修正しました。

2023-10-02 13:18 UTC, RahmatRamdani85 commented on app/Http/Requests/PostRequest.php
> +            'content' => 'max:140'
requiredを追加しました。

2023-10-02 13:18 UTC, RahmatRamdani85 commented on routes/web.php
> +
この空行２行は削除しました。

2023-10-02 13:18 UTC, RahmatRamdani85 commented on resources/views/welcome.blade.php
> +</div>
この部分を修正しました。

2023-10-02 13:18 UTC, RahmatRamdani85 commented on resources/views/welcome.blade.php
> +        </div>
この部分を修正しました。

2023-10-03 13:08 UTC, yukihiroLaravel approved these changes
OKですのでマージしました！
おつかれさまでした！

2023-10-03 13:08 UTC, merged