#668 共通ファイル&ヘッダーフッター & トップページのタイトルのみ表示「Topic Posts」（ひろせ）
yukihiroLaravel/joint_develop pull request #739
Opened 2023-10-01 23:41 UTC by kouji0117

## issue
- Closes #668 

## 概要
- 共通ファイル&ヘッダーフッター & トップページのタイトルのみ表示「Topic Posts」

## 動作確認手順
- 下記コマンドを実行

## 考慮して欲しいこと
- Aチームの開発において、現在私がボトルネック状態になっており恐縮しているところであるが、できうる限りスピーディーに今後取り組みたい。

## 確認して欲しいこと
- 細かいコマンドのミスはもちろんであるが、全体的な手続き的なミスがあるかもしれないので、確認して欲しい。

2023-10-02 06:17 UTC, Osk0830 requested changes
お疲れ様でした！
概ねよくできていると思います！

少しだけコメントしましたので、
確認よろしくお願いいたします！

2023-10-02 06:17 UTC, Osk0830 commented on resources/views/commons/header.blade.php
> +            </ul>
- この部分、<li>要素のインデントだけが他に比べて下がりすぎているようですので、インデントが正しいか確認してみてください。

2023-10-02 06:17 UTC, Osk0830 commented on resources/views/layouts/app.blade.php
> +            @include('commons.error_messages')
- エラーメッセージようのパーツをこの部分で読み込んでしまうと、お手本サイトのような位置にエラーメッセージが出なくなってしまいます。お手本サイトで新規投稿時のエラーの挙動を確認して、このパーツをどこで読み込むべきか検討してみてください。

2023-10-02 06:17 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +    <h5 class="text-center mb-3">"○○"について140字以内で会話しよう！</h5>
- この部分、モックアップの内容これだけでしたでしょうか？

2023-10-04 06:05 UTC, Osk0830 requested changes
お疲れ様です！
こちらだいぶ完了に近づいてきたと思います。

少しだけコメントしましたので、
確認よろしくお願いします！

2023-10-04 06:05 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +        @include('commons.error_messages')
- 10行目のincludeしている部品は、9行目の「エラーメッセージが入る場所」という文言を削除して、そこに入れるべきではないでしょうか？

2023-10-04 06:05 UTC, Osk0830 commented on resources/views/commons/error_messages.blade.php
> +
- こちら表示確認のために変更されたのだと思いますが、確認が済んだら元に戻しておきましょう。

2023-10-04 06:05 UTC, Osk0830 commented on resources/views/layouts/app.blade.php
> +        </div>
- コードの整形という観点から不要な空行は削除しておいてください。

2023-10-04 23:32 UTC, kouji0117 commented on resources/views/layouts/app.blade.php
> +        </div>
12行目の空行を削除しました。

2023-10-04 23:32 UTC, kouji0117 commented on resources/views/commons/error_messages.blade.php
> +
コメントアウトをはずしました。

2023-10-04 23:32 UTC, kouji0117 commented on resources/views/welcome.blade.php
> +        @include('commons.error_messages')
10行目を9行目の中にはめこみました。

2023-10-05 00:30 UTC, Osk0830 requested changes
お疲れ様でした！
内容確認しました。

少しだけ調整が必要な箇所がありますので、
確認よろしくお願いします！

2023-10-05 00:30 UTC, Osk0830 commented on resources/views/commons/error_messages.blade.php
> +    </ul>
- ここは不要ですので削除しましょう。

2023-10-05 00:30 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +        <div class="w-75 m-auto">@include('commons.error_messages')</div>
- 他の人が見ても見やすいように、`@include()`の前後で改行してあげると良さそうですね。

2023-10-05 07:58 UTC, kouji0117 commented on resources/views/commons/error_messages.blade.php
> +    </ul>
削除し対応しました。

2023-10-05 07:59 UTC, kouji0117 commented on resources/views/welcome.blade.php
> +        <div class="w-75 m-auto">@include('commons.error_messages')</div>
そうですね、改行し対応しました。

2023-10-05 08:01 UTC, kouji0117 commented
修正いたしましたのでご確認お願い致します。

2023-10-05 23:41 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらマージしますね！

引き続き頑張っていきましょう！

2023-10-05 23:41 UTC, merged