#622ユーザ編集画面・ユーザ更新処理
yukihiroLaravel/joint_develop pull request #740
Opened 2023-10-02 14:42 UTC by naoki-yy

## issue 

- Closes #622 

  

## 概要 

- ユーザ編集画面の作成・ユーザ更新処理の実装

  

## 動作確認手順 

- 下記URLを指定
 http://localhost:8080/users/1/edit

  

## 考慮してほしいこと 

- 状況に応じて、下記コマンドで動作確認する必要あり。 

php artisan migrate:fresh --seed 

  

## 確認してほしいこと 

- 特にございません。

2023-10-03 00:01 UTC, Osk0830 requested changes
お疲れ様でした！
比較的難しいタスクだったと思いますが、全体的な骨組みはしっかりできていると思います！

修正が必要な箇所についていくつかコメントしましたので、
確認よろしくお願いします！

2023-10-03 00:01 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +        // $user = \Auth::user();
- 不要なコメントアウトは削除しましょう。

2023-10-03 00:01 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +        $user = User::find(1);
- このメソッドですと、存在しないidが入力された場合、サーバーエラーになってしまうと思います。現状ですと、仮に`/users/100/edit`とリクエストを送るとエラーになると思います。それを回避するために、`findOrFail()`メソッドを使いましょう。

2023-10-03 00:01 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +    }
- こちら、編集画面ですので、ログインしている本人のページ以外はアクセスできないよう、条件分岐をついかしましょう。

2023-10-03 00:01 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +        $user->password = $request->password;
- パスワードはDB登録時にハッシュ化させないと、パスワードとして機能しなくなります。ハッシュ化する処理を挟みましょう。

2023-10-03 00:01 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +
- こちらも、edit同様、本人だけが処理を行えるようにしましょう。

2023-10-03 00:01 UTC, Osk0830 commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
- 今のままですと、おそらく一度使ったアドレスを再度使えなくなってしまうと思います。名前だけ、もしくはパスワードだけ変更したいような場合も考慮して、既存の本人のアドレスはOKにしましょう。

2023-10-03 00:01 UTC, Osk0830 commented on app/Http/Requests/UserRequest.php
> +            "password" => "パスワード"
- この部分、「バリデーションメッセージの日本語化」のタスクが完了した際は、おそらく不要な記述になるのではないかと思います。後に再度確認してみるようにしていただければと思います。

2023-10-03 00:01 UTC, Osk0830 commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->softDeletes();
- こちら、1つ目のタスク時に入っていなかったんですね。。。見落としてたようです。すみません！

2023-10-03 00:01 UTC, Osk0830 commented on routes/web.php
> +Route::get('signup', 'Auth\LoginController@login')->name('signup');
- こちら、新規登録のルーティングのようですので、元のものが合ってると思いますが、なぜ変更されたのでしょうか？

2023-10-03 00:01 UTC, Osk0830 commented on routes/web.php
> +    Route::put('{id}', 'UsersController@update')->name('users.update');
- この部分、ログインしている人でないとアクセスできないよう、ミドルウェアを挟みましょう。

2023-10-03 22:38 UTC, naoki-yy commented on app/Http/Controllers/UsersController.php
> +        // $user = \Auth::user();
承知しました。

2023-10-03 22:39 UTC, naoki-yy commented on app/Http/Controllers/UsersController.php
> +        $user = User::find(1);
修正いたします。

2023-10-03 22:42 UTC, naoki-yy commented on routes/web.php
> +    Route::put('{id}', 'UsersController@update')->name('users.update');
修正いたします。

2023-10-03 22:44 UTC, naoki-yy commented on app/Http/Requests/UserRequest.php
> +            "password" => "パスワード"
かしこまりました。
後を考え、今のうちに削除しておきます。

2023-10-03 22:46 UTC, naoki-yy commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
unique:usersの部分、削除いたします。

2023-10-03 22:51 UTC, naoki-yy commented on app/Http/Controllers/UsersController.php
> +        $user->password = $request->password;
`Hash::make($request->password)`で書き直しました。

2023-10-03 22:55 UTC, naoki-yy commented on app/Http/Controllers/UsersController.php
> +    }
`if (\Auth::id() === $user->user_id)`で囲いました。

2023-10-03 22:55 UTC, naoki-yy commented on app/Http/Controllers/UsersController.php
> +
上記同様、`if (\Auth::id() === $user->user_id)`で囲いました。

2023-10-04 06:19 UTC, Osk0830 requested changes
お疲れ様です！
こちらだいぶ完了に近づいてきたと思います。

少しだけコメントしましたので、
確認よろしくお願いします！

2023-10-04 06:19 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +        }
- こちら動作確認するとエラーが出そうな感じがしますが、そんなことはなかったでしょうか？`$user`に`user_id`というのが存在しますでしょうか？
- if文の条件に合致しなかった場合もエラーになってしまいそうですが、いかがでしょうか？仮にログインしているユーザーのidとは違うidで、ブラウザからURL叩いてみた場合にどうなりますでしょうか？条件に合致しなかった際の処理を追加する必要がありそうです。

2023-10-04 06:19 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +        }
- こちら、もろもろ`edit()`と同様です。

2023-10-04 06:19 UTC, Osk0830 commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255'],
- emailはログインに用いる情報ですが、uniqueを取ってしまうと、予期せぬ重複が発生してしまい、ログインできないなどの問題が発生してしまいます。下記記事などを参考に、ユニークでなければいけないけど、元のemailと同じ場合はOKのようなバリデーションにしましょう。

https://eza-s.com/blog/archives/73/

2023-10-04 06:19 UTC, Osk0830 commented on routes/web.php
> +Route::get('signup', 'Auth\LoginController@login')->name('signup');
- この部分、どうなりましたでしょうか？

2023-10-04 06:19 UTC, Osk0830 commented on routes/web.php
> +    Route::put('{id}', 'UsersController@update')->name('users.update');
- 内容的にはOKそうですが、インデントがおかしいようなので修正してみてください。

2023-10-04 12:42 UTC, naoki-yy commented on routes/web.php
> +Route::get('signup', 'Auth\LoginController@login')->name('signup');
失礼いたしました。
元のものに修正いたしました。

2023-10-06 00:43 UTC, naoki-yy commented on app/Http/Controllers/UsersController.php
> +        }
`else {　return back();　}`を追記しました。

2023-10-06 00:43 UTC, naoki-yy commented on app/Http/Controllers/UsersController.php
> +        }
上記同様、`else {　return back();　}`を追記しました。

2023-10-06 00:48 UTC, naoki-yy commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255'],
ありがとうございます。
中々、記事内容が難しかったですが、
以下のコードを書き加えました。
`Rule::unique('users')->ignore($this->users`

2023-10-06 02:20 UTC, Osk0830 requested changes
お疲れ様でした！
一点調整が必要な箇所を除いては、おそらく大丈夫ではないかと思います！

ただ、拝見したところ、まだログイン機能のタスクが完了していないため、動作確認自体ができないようでしたね。
恐縮ですが、マージ自体は、ログイン機能実装後に動作確認ができてから行わなければならなそうですので、修正完了後は少しだけお待ちいただければと思います。

2023-10-06 02:20 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +    }
- 関数の戻り値が `return back()`のように同じ場合は、記述を調整すると重複して書く必要はなくなりますね。調整してみてください。

2023-10-07 23:02 UTC, naoki-yy commented on app/Http/Controllers/UsersController.php
> +    }
修正いたします.

2023-10-10 06:08 UTC, Osk0830 requested changes
お疲れ様でした！
動作確認もありがとうございました。

少しだけ修正が必要な箇所がありますので、
コメントの確認よろしくお願いします！

あと、別件ですが（既にお伝えしていたかもですが、汗）、
新規登録エラーメッセージの表示位置・幅の調整も、
合わせてよろしくお願いします！

[![Image from Gyazo](https://i.gyazo.com/3544eca0aa2f8109bbe6cd2a65296839.png)](https://gyazo.com/3544eca0aa2f8109bbe6cd2a65296839)

2023-10-10 06:08 UTC, Osk0830 commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="{{ route('users.edit',Auth::User()->id) }}" class="nav-link text-light">{{ Auth::user()->name }}</a></li>
- こちら、ログイン者のidだけを取得したい場合は、`Auth::user()`でインスタンスを取得するのではなく、`Auth::id()`を使いましょう。（Auth::`u`ser()は小文字です）
- 引数の間のカンマ `,`の後ろは、見やすく半角空白を入れてくだい。

- ただ、ここのリンクは、「詳細画面」に行くためのものであって、「編集画面」に行くためのものではないです！

2023-10-10 06:08 UTC, Osk0830 commented on resources/views/users/edit.blade.php
> +        <input type="hidden" name="id" value="" />
- idは、URIのパラメーターとして渡しており、コントローラーなどでもそれを利用しているので、`hidden`で別途渡す必要がないと思いますが、いかがでしょうか？

2023-10-10 06:08 UTC, Osk0830 commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255',Rule::unique('users')->ignore($this->id)],
- 同じアドレスで更新しようとすると、弾かれてしまいますね。。`ignore()`の中の記述を、ログイン者の idを取得する `Auth::id()`を使って、`ignore(\Auth::id())`のようにするといけると思います。この時、`\`も忘れずに入れてくださいね。

[![Image from Gyazo](https://i.gyazo.com/fff3a2b1876232c1cde3f424484f41e3.png)](https://gyazo.com/fff3a2b1876232c1cde3f424484f41e3)

2023-10-10 22:18 UTC, naoki-yy commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="{{ route('users.edit',Auth::User()->id) }}" class="nav-link text-light">{{ Auth::user()->name }}</a></li>
Auth::id()に修正いたしました。
また、ユーザ詳細画面は現在製作中のため、それがマージされた段階でリンクをユーザ詳細に直します。

2023-10-10 22:31 UTC, naoki-yy commented on resources/views/users/edit.blade.php
> +        <input type="hidden" name="id" value="" />
id部分、削除します。
ちなみにですが、hiddenはどういう場合に用いるのでしょうか？

2023-10-10 22:36 UTC, naoki-yy commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255',Rule::unique('users')->ignore($this->id)],
かしこまりました。
意味としては、自分のIDに紐づくメールアドレスは無視するということですね。
動作確認実施し、メールアドレスを変えずに編集処理が出来ました。

2023-10-10 23:57 UTC, Osk0830 commented on resources/views/commons/header.blade.php
> +                    <li class="nav-item"><a href="{{ route('users.edit',Auth::User()->id) }}" class="nav-link text-light">{{ Auth::user()->name }}</a></li>
了解です！
忘れないようにお願いします！
ユーザー詳細担当者に申し送りする感じでもOKです！

2023-10-10 23:57 UTC, Osk0830 commented on resources/views/users/edit.blade.php
> +        <input type="hidden" name="id" value="" />
こちらはSlackの方に書きましたので確認よろしくお願いします！

2023-10-10 23:58 UTC, Osk0830 commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255',Rule::unique('users')->ignore($this->id)],
> 意味としては、自分のIDに紐づくメールアドレスは無視するということですね。

そのとおりですね！

2023-10-10 23:59 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKなのでマージしますね！

引き続き頑張っていきましょう！

2023-10-10 23:59 UTC, merged