#678_ユーザ編集画面・更新(dera)
yukihiroLaravel/joint_develop pull request #741
Opened 2023-10-02 15:15 UTC by Jino225242

## issue
- Closes #678 

## 概要
- ユーザ編集画面・更新

## 動作確認手順
　1. ユーザ詳細画面の【ユーザ情報の編集】をクリックすることでユーザ編集画面に遷移
　2-1. 各カラム入力後、【更新する】をクリックすることでユーザ情報が更新される
　2-2. バリデーションに抵触する内容にて【更新する】をクリックすると、エラーメッセージとともにリダイレクトされる
　3-1.ログインしているユーザとは異なる、IDのユーザのユーザ詳細画面では 【ユーザ情報の編集】が表示されない
　3-2.URLに直接入力(ログインID：9にて、/users/8/editへアクセス)すると、abort(403)へ遷移　※アクセス権無し
　3-3.URLに直接入力(ログインID：9にて、/users/800/editへアクセス)すると、abort(404)へ遷移　※存在しないID
 
## 確認して欲しいこと（質問）
更新メソッドとしてUsersController.phpの中でupdateメソッドを本文末内容にて作りました。
ユーザ情報更新後、ユーザ詳細画面へ遷移させるように考え、
```
①            return view('users.show', $user->id);

```
としておりましたが、エラーが出てしまったため、
```
②            return redirect()->route('users.show', $user->id);
```
と書き換えたところ、うまく遷移させることができました。

①でのエラー文に対して、viewへ渡すデータを初期化するフローを組んでみたりいろいろと試行錯誤したのですが、修正するべき項目に皆目見当がつきませんでした。初歩的な部分で致命的な誤りがあるのでしょうか。
理解不足で申し訳ありませんが、ご教授いただきますようお願いいたします。

『エラー文』
ErrorException
array_merge(): Expected parameter 2 to be an array, int given

 ```
public function update(UserRequest $request, $id)
    {
        if ($id == Auth::id())
        {
            $user = User::findOrFail($id);
            $user->name = $request->name;
            $user->email = $request->email;
            $user->password = bcrypt($request->password);
            $user->save();
            // return redirect('/');
            // return view('users.show', $user->id);
            return redirect()->route('users.show', $user->id);
        }
    }
```

2023-10-02 17:02 UTC, yukihiroLaravel requested changes
いくつか修正点をお伝えしました！
ご確認ください🙇‍♂️
https://www.loom.com/share/7967f6e8ea6d422f80aca4f7bd0027cf?sid=cfa6f817-3d20-44de-a7cb-ff4eccc428fa

2023-10-02 17:02 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        }
if () {
}

2023-10-03 23:30 UTC, Jino225242 commented on app/Http/Controllers/UsersController.php
> +        }
修正完了です。if文のコード規約、確認しておらず失礼いたしました。
また、Route::group(['middleware' => 'auth'], function () {}について、失念しており申し訳ありませんでした。
これが抜けており、editメソッドでややこしい書き方にて組んでしまいました。

2023-10-04 01:05 UTC, yukihiroLaravel requested changes
すみません！
コンフリクトが起きているのでその解消と
少し修正点記載しましたので変更願います！

2023-10-04 01:05 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        else{
規約上

} else {

このように書きましょう！

2023-10-04 01:05 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        if ($id == Auth::id()){
if ($id == Auth::id()) {
{の前もスペース１つ入れましょう！

2023-10-04 12:17 UTC, Jino225242 commented on app/Http/Controllers/UsersController.php
> +        else{
修正完了いたしました。初歩的なところで失礼いたしました。

2023-10-04 12:17 UTC, Jino225242 commented on app/Http/Controllers/UsersController.php
> +        if ($id == Auth::id()){
修正完了いたしました。こちらも初歩的なところで失礼いたしました。

2023-10-04 15:46 UTC, yukihiroLaravel requested changes
１点以外完璧です！
そこだけ指摘しましたので修正願います！🙇‍♂️

2023-10-04 15:46 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::get('{id}', 'UsersController@show')->name('users.show');
すみません！
こちら僕の方で言ったかもしれませんが
showメソッドは、ログインしていなくてもアクセスできないとまずいので
このルーティングのみmiddleware の外に出しましょう！

2023-10-04 16:36 UTC, Jino225242 commented on routes/web.php
> +        Route::get('{id}', 'UsersController@show')->name('users.show');
お手本アプリをよく確認しておらず申し訳ありませんでした！！
再々修正完了しました。

2023-10-05 02:11 UTC, yukihiroLaravel approved these changes
OKなのでマージしました🙆‍♂️
お疲れ様でした！！

2023-10-05 02:11 UTC, merged