Feature/kazufumi/user show
yukihiroLaravel/joint_develop pull request #745
Opened 2023-10-07 08:22 UTC by kazufumikatsuyama

## issue
- closes #711

## 概要
- ユーザ詳細

## 動作確認手順
-  localhost:8080/users/1 などのURLで動作確認

## 考慮して欲しい事
- タイムライン、フォロー中、フォロワー、タブはちゃんとなりました。
　　余計なものがついていました。

## 確認して欲しい事
- 特にありません

2023-10-08 16:40 UTC, kazufumikatsuyama commented
承知しました
確認しました

2023-10-10 04:45 UTC, kazufumikatsuyama commented
承知しました。
修正をおこないました。

2023-10-10 05:15 UTC, yukihiroLaravel requested changes
確認しましてOKです！
1点だけコメントしましたのでご確認・修正願います！

2023-10-10 05:15 UTC, yukihiroLaravel commented on resources/views/posts/posts.blade.php
> +<div class="m-auto" style="width: fit-content"></div>
１点指摘漏れていましたが、
このdivタグの間にLaravel応用で使っていたような
ページネーションを入れないとイケないですね！

`<div></div>`

宜しくお願いします！

2023-10-10 08:45 UTC, kazufumikatsuyama commented
承知しました。
何から何まで、ありがとうございます。

2023-10-10 09:03 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした！！

2023-10-10 09:03 UTC, merged