#696トップページの投稿表示(寺島)
yukihiroLaravel/joint_develop pull request #746
Opened 2023-10-07 08:29 UTC by daihubemmono

## issue
- Closes #696 

## 概要
- トップページの投稿表示

## 動作確認手順
- ユーザーのアバター画像
- ユーザー名
- 投稿の本文
- 日時
- 【削除】ボタン
- 【編集する】ボタン
-【次ページ？】ボタン

## 確認して欲しいこと
※現時点で、ログイン機能を実装していないのでどのユーザーでも【削除】【編集する】ボタンが出てしまうのですが出ないように実装した方がいいですか？

2023-10-10 07:41 UTC, Osk0830 requested changes
お疲れ様でした！

いい感じにできてきていると思います！

少しだけコメントしましたので、
確認よろしくお願いします。

2023-10-10 07:41 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +        </div>
- コメントで書かれていましたが、ログイン機能自体が実装できていないので確認しづらくはありますが、ここ自体はログイン機能なしでも実装できると思いますので、実装して見てください。新規登録するとその直後はログイン状態になりますのでログイン時に本人の場合だけ表示される、という動作確認もできると思います！

2023-10-10 07:41 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +            <p class="text-muted">{{ $post->created_at }}</p>
- この部分、現在の投稿シーダーでは `created_at`カラムが空で、また新規投稿機能も実装されていないので、容易に表示確認できない部分かと思います。DBに直接値を入れ込むなりシーダーに手を加えるなどして、動作確認してみてくださいね。（並び順が意図通りかも含めて）

- また、上記のような特殊な確認が必要な場合、レビュワーにしっかりと伝わるよう、コメントで申し送りをしてくれるようにしてくださいね！

[![Image from Gyazo](https://i.gyazo.com/a51bb1a9a0eea46827d1ba2c2925dda5.png)](https://gyazo.com/a51bb1a9a0eea46827d1ba2c2925dda5)

2023-10-18 23:47 UTC, Osk0830 requested changes
お疲れ様でした。
だいぶ修正できてきたと思います。

ただ、一部修正が必要な箇所がありますので、
確認よろしくお願いします！

また、数日前にフルサワさんのログイン機能がチームのブランチにマージされていると思います。
そちらをプルしてこのブランチにも取り込み、動作確認するようにしてくださいね。

2023-10-18 23:47 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +  </li>
- この部分HTMLの構造がおかしいようです。現在、`<li>`内の`<div>`をループで生成していますが、`<li>`そのものがループで生成される必要があります。そうなっていないために、お手本サイトとHTMLの構造や見た目も違ってしまっています。（※`<ul> <li>`タグの意味についてもぜひ調べてみてくださいね）

[![Image from Gyazo](https://i.gyazo.com/b1ce8037f33d9f77747bc3514875ca3c.png)](https://gyazo.com/b1ce8037f33d9f77747bc3514875ca3c)

2023-10-18 23:47 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +    </div>
- お手本サイトを見てみると、この部分もログインしていない場合は表示されなくなっていると思いますので、あわせて修正お願いします。

2023-10-18 23:47 UTC, Osk0830 commented on app/Post.php
> +    public function user()
- 異なる内容が続いている箇所なので、10行目と11行目の間に空行を入れてください。

2023-10-23 04:48 UTC, Osk0830 requested changes
お疲れ様でした！
内容的にはこちらでOKそうですね。

ただ、少し細かい話になってしまいますが、
コードの整形という観点から少し修正が必要な箇所がありコメントしましたので、
確認よろしくお願いします！

2023-10-23 04:48 UTC, Osk0830 commented on app/Post.php
> +class Post extends Model
- 細かい内容になってしまいますが、コードの整形はコードの可読性を高める上でとても大事なポイントになります。ここの場合、`use`に関する記述である5行目と7行目は、間に空行なしで続けて書いて大丈夫そうですし、一方で、`use`の記述をしている7行目と`class`の定義を開始している8行目は異なる内容のため、間に見やすく空行を入れてあげるべきです。

2023-10-23 04:48 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +          </div>
- インデントがもう少し前に出るべきではないでしょうか？

2023-10-23 08:10 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKそうなのでマージしますね！

2023-10-23 08:10 UTC, merged

2023-10-23 14:31 UTC, daihubemmono commented on resources/views/posts/posts.blade.php
> +            <p class="text-muted">{{ $post->created_at }}</p>
承知しました！

そのままだとcreated_atカラムがNULLと表示されているのですが、DBに直接値を入力することで日時の表示はできております。

2023-10-23 14:31 UTC, daihubemmono commented on resources/views/posts/posts.blade.php
> +  </li>
@foreach ($posts as $post)の位置が間違っていたようです。
修正しました。

2023-10-23 14:31 UTC, daihubemmono commented on resources/views/welcome.blade.php
> +    </div>
@if (Auth::check())

@endif
を使うことで修正しました。

2023-10-23 14:31 UTC, daihubemmono commented on app/Post.php
> +    public function user()
承知しました！
空行入れます。

2023-10-23 14:31 UTC, daihubemmono commented on resources/views/posts/posts.blade.php
> +        </div>
Authファサードを使って、ログインしているユーザーが投稿した物のみ【削除】【編集する】ボタンが出現するように実装しています。

2023-10-23 14:31 UTC, daihubemmono commented on app/Post.php
> +class Post extends Model
承知しました。
そのようにいたします。

2023-10-23 14:31 UTC, daihubemmono commented on resources/views/posts/posts.blade.php
> +          </div>
すみません！
インデント揃えたつもりが揃ってませんでした。
直します。