#59共通ファイル作成(竹渕)
yukihiroLaravel/joint_develop pull request #75
Opened 2022-10-03 14:43 UTC by bucchi-orange

## issue
- Closes #59 

## 概要
-app.blade.phpを作成

## 動作確認手順
http://localhost:8080/
で正常に表示がされているか確認

## 考慮してほしいこと
commons.header
commons.error_messages
content
commons.footer
上記ファイルは -Closes #60 で作成予定

## 確認してほしいこと
```
@include()
@yeild()
```
の使い方が正しいか

2022-10-05 03:40 UTC, Osk0830 requested changes
お疲れ様でした！
環境の構築から実装、そしてプルリクまでの一通りの流れを、しっかりと理解されていて素晴らしいですね！

今回のタスクですが、要となってくるのは、他のBladeで今回作成した共通Bladeが読み込めるようにできているか、というところにあると思います。
現状は、ローカルホストの一番上のディレクトリである　[http://localhost:8080/](http://localhost:8080/)　にアクセスしても、上記が確認できない状態にあるかと思います。
ですので、

①welcome.blade.php を表示させる際に、app.blade.phpがextendsできているかをかくにんできるようにしといてみていただくと良さそうですね。

②その際、include用のbladeがまだできていないものに関しては、エラーが出ないように一旦コメントアウトなどしておくといいと思います。

③なお、今後ですが、僕もレビュアーとして追加していただけると助かります。メールなどでの通知も来て気付きやすくなるので、笑

　[![Image from Gyazo](https://i.gyazo.com/06a6861938435fe8b9e8b05c550a7149.png)](https://gyazo.com/06a6861938435fe8b9e8b05c550a7149)

2022-10-05 20:16 UTC, bucchi-orange commented
ご指摘があった点を修正しましたので、再レビューをお願いします。

## 変更点
・welcome.blade.php に app.blade.php を extend しました
・welcome.blade.php で topic posts のタイトルを表示するようにしました
・app.blade.php 内の未作成 blade ファイルをコメントアウトしました

2022-10-06 05:07 UTC, Osk0830 requested changes
お疲れ様です！
内容的には概ねOKなのですが、少しだけコメントしましたので、ご確認ください。

2022-10-06 05:07 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +    <h5 class="text-center mb-3">"○○"について140字以内で会話しよう！</h5>
- `@section`で始めたら、`@endsection`で終わりを示すように統一した方が良さそうですね。

　　[![Image from Gyazo](https://i.gyazo.com/c7e737044c42f2f649d20ae4b53cb9e9.png)](https://gyazo.com/c7e737044c42f2f649d20ae4b53cb9e9)

- あと、今、コードのインデントが綺麗に揃っていないようなので、コードを書いた際はインデントを揃えるよう習慣づけるのがいいかもしれません。エディタのコードフォーマット機能(拡張機能もあり)などを使うようにすると楽かもです。

2022-10-06 14:16 UTC, bucchi-orange commented
再び修正いたしました。
拡張機能のPHP Intelephenseを導入して、インテンドを整えました。
よろしくお願いいたします。

## 変更点
・抜けていた@endsectionを加えました
・インテンドを整えました

2022-10-07 00:58 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらマージしますね！

2022-10-07 00:58 UTC, merged