#60ヘッダー・フッター & トップページのタイトルのみ表示「Topic Posts」(竹渕)
yukihiroLaravel/joint_develop pull request #76
Opened 2022-10-08 02:30 UTC by bucchi-orange

## isuue
- Closes #60

## 概要
ヘッダー・フッター＆トップページのタイトル表示

## 動作確認手順
http://localhost:8080/
で正しく表示されるか確認

## 考慮してほしいこと
ヘッダーの表示は、条件分岐を実装していないため
現段階では全てのメニューが表示されてしまっている。

2022-10-09 00:18 UTC, Osk0830 requested changes
お疲れ様です！
概ねよくできていると思います！
少しだけコメントしたので、確認よろしくお願いします！

2022-10-09 00:18 UTC, Osk0830 commented on resources/views/commons/header.blade.php
> +                <li class="nav-item"><a href="" class="nav-link text-light">新規ユーザ登録</a></li>
- <ul>の閉じタグが抜けてないでしょうか？
- 今、全てが正常に表示できることは確認できているので、ログインしている状態としていない状態で必要な表示を切り分けるところまで実装してみるといいかもしれませんね。
- あと、実装時の慣習として、リンク先が決まっていないか実装できていない場合の`href`には`#`を入れておくことが多いので、今回もそうしておきましょう。

2022-10-10 02:33 UTC, bucchi-orange commented
指摘いただいた点を修正いたしました。
再レビューお願いいたします

## 変更内容
・href="#"にしました
・抜けていた</ul>を追加しました
・@if でログイン中とそれ以外でヘッダーの表示内容を切り分けました

2022-10-11 01:17 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらマージしますね！
引き続き頑張っていきましょう！

2022-10-11 01:17 UTC, merged