Feature/yasuyuki/user show
yukihiroLaravel/joint_develop pull request #761
Opened 2023-10-13 14:45 UTC by YasuLaravel

## issue
-closes 

## 概要

## 動作確認手順

## 考慮してほしいこと

## 確認してほしいこと

2023-10-15 12:19 UTC, Osk0830 requested changes
お疲れ様でした！
全体的に概ねよくできていると思います！

いくつか修正・調整の必要な箇所がありますので、
確認よろしくお願いします！

2023-10-15 12:19 UTC, Osk0830 commented on app/Post.php
> +    public function user()
- ここは、9行目と10行目の間に1行空行を入れましょう。

2023-10-15 12:19 UTC, Osk0830 commented on app/User.php
- 46行目以降、不要な空行が数行入っているようですので削除しましょう。

2023-10-15 12:19 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +
- 不要な空行は削除しましょう。

2023-10-15 12:19 UTC, Osk0830 commented on app/Http/Controllers/Controller.php
> +
- こちらは編集不要ではないでしょうか？

2023-10-15 12:19 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                <p class="mt-3 mb-0 d-inline-block"><a href="">{{$user->name}}</a></p>
- href属性に遷移先のリンクを貼ってくださいね。ユーザー詳細ページへのリンクになるので、ユーザー詳細ページで見ている場合は、遷移先は現在いるページと同じになってしまいますが、トップページなどで見ている場合は、ここをクリックするとそのユーザーの詳細ページに遷移できるという具合です。
- `{{`の後ろや`}}`の前は半角空白を入れましょう。

2023-10-15 12:19 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                    <p class="text-muted">{{$post->created_at}} </p>
- `{{`の後ろや`}}`の前は半角空白を入れましょう。

2023-10-15 12:19 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                    <a href="" class="btn btn-primary">編集する</a>
- 現状、編集画面はマージされているので、ここにもリンクを貼っておいてくださいね。

2023-10-15 12:19 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +
- 不要な空行は削除しましょう。

2023-10-15 12:19 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                </div>
- この部分は、ログイン者本人の投稿の場合にのみ表示されるようにしてください。
- また、インデントが少しおかしいようですので調整しましょう。

2023-10-15 12:19 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +                    </div>
- ここはログイン者自身のページである場合にのみ表示されるようにしましょう。

2023-10-15 12:19 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +            </div>
- インデントが少しおかしいようですので調整しましょう。

2023-10-15 12:19 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +            <li class="nav-item"><a href="" class="nav-link ">タイムライン</a></li>
- ここにも必要なリンクを貼ってくださいね。

2023-10-19 12:52 UTC, YasuLaravel commented on app/Post.php
> +    public function user()
空行入れました。

2023-10-19 12:53 UTC, YasuLaravel commented on app/User.php
削除しました

2023-10-19 12:53 UTC, YasuLaravel commented on app/Http/Controllers/UsersController.php
> +
空行削除しました。

2023-10-19 12:55 UTC, YasuLaravel commented on app/Http/Controllers/Controller.php
> +
無意識に改行していました。削除しました

2023-10-19 12:57 UTC, YasuLaravel commented on resources/views/posts/posts.blade.php
> +                <p class="mt-3 mb-0 d-inline-block"><a href="">{{$user->name}}</a></p>
href属性に遷移先のリンクを貼りました。また　}}の後ろに半角の空白を入れました。

2023-10-19 12:57 UTC, YasuLaravel commented on resources/views/posts/posts.blade.php
> +                    <p class="text-muted">{{$post->created_at}} </p>
空白を入れました。

2023-10-19 12:58 UTC, YasuLaravel commented on resources/views/posts/posts.blade.php
> +                    <a href="" class="btn btn-primary">編集する</a>
リンクを貼りました。

2023-10-19 12:58 UTC, YasuLaravel commented on resources/views/users/show.blade.php
> +
削除しました。

2023-10-19 12:59 UTC, YasuLaravel commented on resources/views/posts/posts.blade.php
> +                </div>
ログイン者本人の投稿の場合に表示されるように追記しました。インデント修正しました。

2023-10-19 13:00 UTC, YasuLaravel commented on resources/views/users/show.blade.php
> +                    </div>
ログイン者自身のページである場合のみ表示されるようにしました。

2023-10-19 13:01 UTC, YasuLaravel commented on resources/views/users/show.blade.php
> +            </div>
調整しました。

2023-10-19 13:01 UTC, YasuLaravel commented on resources/views/users/show.blade.php
> +            <li class="nav-item"><a href="" class="nav-link ">タイムライン</a></li>
リンクを貼りました。

2023-10-19 23:56 UTC, Osk0830 requested changes
お疲れ様でした！
こちら全体的にほぼ完成に近づいたと思います！

もう少しだけ調整が必要そうな歌唱がありますので、
確認よろしくお願いします！

2023-10-19 23:56 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +                    </div>
- ifで囲む位置がおかしくないでしょうか？現状だと、ボタンの表示対象外の場合でも、11行目に始まる空の<div>が出力されてしまいます。この<div>はあくまでボタンを囲むために必要なものだと思いますので、ボタンが非表示の場合は<div>そのものが出力されないようにしましょう。デベロッパーツールでも違いを確認しながら進めてみてくださいね。

2023-10-19 23:56 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                     <a href="{{ route('users.update', Auth::id()) }}" class="btn btn-primary">編集する</a>
- 引数として渡す値の取得方法ですが、結果としては同じですが、ページの意味合いから考えて、`Auth::id()`よりは、$post->user_id`や`$user->id`の方が合っている気がします。今後、なんらかの権限を持つ人であれば編集ボタンをクリックできる、という拡張などがあった場合にも、その方が良さそうな気がします。

2023-10-19 23:56 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +    @endforeach
- この部分、同じ値を取得するのに、`$post->user_id`と`$user->id`が混用され、非常に分かりにくい気がします。どちらかに統一できるなら統一した方がいいと思います。`$post`は必ず必要ですし、理屈的にもすべて投稿を基準にユーザーの情報を取得しているので、こちらを使う方が整合性が取れている感じもします。

- 名前やメールアドレスの取得も、`$post`を基準にしてもいいかもですね。そうなると、コントローラーからユーザーの情報を送る必要もなくなるかと思います。（ただ、どちらが正しい、というわけではないので、この点については現状のままでもOKです）

2023-10-19 23:56 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +       return view('users.show',$data);
- 引数の間にあるカンマの後ろは半角空白を入れましょう。

2023-10-19 23:56 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +                <h3 class="card-title  text-light">{{$user->name}}</h3>
- `{{ $user->name }}`のように半角空白を入れましょう。

2023-10-19 23:56 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +            <li class="nav-item"><a href="#" class="nav-link {{ Request::is('users/' . $user->id) ? 'active' : '' }} ">タイムライン</a></li>
- この部分、`Request::is()`を用いてもいいですが、これだとURIに変更があった場合やURIが長い場合など色々と面倒なので、`Request::routeIs()`を使うといいと思います。下記などを参考にされてみてください。

https://shiro-changelife.com/laravel-url-judge/

2023-10-20 12:45 UTC, YasuLaravel commented on app/Http/Controllers/UsersController.php
> +       return view('users.show',$data);
空白を入れました。

2023-10-20 12:47 UTC, YasuLaravel commented on resources/views/users/show.blade.php
> +                <h3 class="card-title  text-light">{{$user->name}}</h3>
半角空白入れました

2023-10-20 12:54 UTC, YasuLaravel commented on resources/views/users/show.blade.php
> +            <li class="nav-item"><a href="#" class="nav-link {{ Request::is('users/' . $user->id) ? 'active' : '' }} ">タイムライン</a></li>
変更しました。

2023-10-20 14:24 UTC, YasuLaravel commented on resources/views/users/show.blade.php
> +                    </div>
ifの囲むいちを変更しました

2023-10-20 14:26 UTC, YasuLaravel commented on resources/views/posts/posts.blade.php
> +                     <a href="{{ route('users.update', Auth::id()) }}" class="btn btn-primary">編集する</a>
$post->user_idに変更しました

2023-10-20 14:27 UTC, YasuLaravel commented on resources/views/posts/posts.blade.php
> +    @endforeach
$post->user_idに統一しました。

2023-10-21 21:38 UTC, Osk0830 requested changes
お疲れ様でした！
修正確認できましたが、
少しだけ問題がありコメントしましたので、
確認よろしくお願いします！

2023-10-21 21:38 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                     <a href="{{ route('users.update', $post->user_id) }}" class="btn btn-primary">編集する</a>
- こちら前回見落としていたかもですが、リンク先がおかしいため、編集ページにアクセスできないと思いますが、いかがでしょう？

2023-10-21 21:38 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +            <li class="nav-item"><a href="#" class="nav-link {{ Request::routeIs('users/' . $user->id) ? 'active' : '' }} ">タイムライン</a></li>
- こちら、下記コメントについて、対応したとありますが、対応できていないようですので、確認お願いします。

https://github.com/yukihiroLaravel/joint_develop/pull/761#discussion_r1359866724

- `routeIs()`を使っているので、URIの文字列を直接記載するのではなく、ルート名を用いて指定するようにしましょう。URIの変更時の修正箇所縮小や長いURLの時の煩雑さの回避に繋がるためです。

2023-10-23 12:22 UTC, YasuLaravel commented on resources/views/posts/posts.blade.php
> +                     <a href="{{ route('users.update', $post->user_id) }}" class="btn btn-primary">編集する</a>
リンク修正しました。

2023-10-23 12:23 UTC, YasuLaravel commented on resources/views/users/show.blade.php
> +            <li class="nav-item"><a href="#" class="nav-link {{ Request::routeIs('users/' . $user->id) ? 'active' : '' }} ">タイムライン</a></li>
修正しました。

2023-10-23 23:01 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKなのでマージしますね〜

2023-10-23 23:02 UTC, merged