#695 ユーザ詳細（ふるさわ）
yukihiroLaravel/joint_develop pull request #765
Opened 2023-10-19 16:28 UTC by furusawa501

## issue
- Closes
 #695 

## 概要
- #695 （ふるさわ）

## 動作確認手順
- http://localhost:8080/ を表示。
- testuser1@test.comでログイン
- ヘッダーの'testuser1'をクリックしユーザ詳細画面へ遷移することを確認
- ユーザのgravatar画像が表示されていることを確認
- 「ユーザ情報の編集」クリックして「ユーザ情報を編集する」へ遷移することを確認
- adminerなどでpostsテーブルのデータを編集、user_idが'1'のレコードを１件以上になるように複製
- 「TopicPosts」ヘッダーの'testuser1'をクリックしユーザ詳細画面を表示しタイムラインの最下部にページ切り替えが表示されていること、'2'をクリックして２ページ目に遷移することを確認
- VSCodeなどでUsersController.phpの40行目「$user = User::findOrFail($id);」の$idを’2’などに書き換える
- ユーザ詳細画面を再表示し「ユーザ情報の編集」「削除」「編集する」ボタンが非表示になることを確認 

## 考慮して欲しいこと
- 特にありません

## 確認して欲しいこと
- 特にありません

2023-10-21 21:18 UTC, Osk0830 requested changes
お疲れ様でした！
全体的にとても良くできていると思います。

少しだけコメントしましたので、
確認よろしくお願いします。

2023-10-21 21:18 UTC, Osk0830 commented on app/Post.php
> +    public function user()
- 内容が変わっているので、10行目と11行目の間に空行を入れましょう。

2023-10-21 21:18 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="{{ route('user.show', $user->id) }}" class="nav-link {{ Request::is('users/'. $user->id) ? 'active' : '' }}">タイムライン</a></li>
- ここは、`Request::is()`でもいいですが、URIに変更があった際にこちらも合わせて変更しなければならなかったり、URIが長くなると記述が煩雑になったりとデメリットが多いので、`Request::routeIs()`を使うといいと思います。下記参考に試してみてください。

https://shiro-changelife.com/laravel-url-judge/

2023-10-21 21:18 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +                            <p class="mt-3 mb-0 d-inline-block"><a href="">{{ $user->name }}</a></p>
- こちらの `<a>`タグにも必要なリンクを貼りましょう。

※この箇所は、最終的には、寺島さん実装中の一覧表示用のパーツを読み込んで使うのがいいので、寺島さんの作業内容がマージされたタイミングで忘れずに修正お願いしますね。

2023-10-22 12:42 UTC, furusawa501 commented on app/Post.php
> +    public function user()
ありがとうございます。見やすさの点でも重要ですね。修正します。

2023-10-22 12:45 UTC, furusawa501 commented on app/Post.php
> +    public function user()
テスト

2023-10-22 16:14 UTC, furusawa501 commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="{{ route('user.show', $user->id) }}" class="nav-link {{ Request::is('users/'. $user->id) ? 'active' : '' }}">タイムライン</a></li>
リンクありがとうございます。```Request::Is()```と動作が同じなので```Request::routeIs()```を使うほうがメンテナンスや記述が楽になると理解しました。

2023-10-22 16:26 UTC, furusawa501 commented on resources/views/users/show.blade.php
> +                            <p class="mt-3 mb-0 d-inline-block"><a href="">{{ $user->name }}</a></p>
コメントとは別ですが、寺島さんの投稿一覧```posts.blade.php```を参考にしたため```@foreach```の位置に間違いがあることに気が付きました。‘‘‘<li‘‘‘タグの前に入れる必要がありますので、その修正はこのタスクで実装しご指摘の修正は次のタスクで実装します。

2023-10-25 17:01 UTC, furusawa501 commented on resources/views/users/show.blade.php
> +                            <p class="mt-3 mb-0 d-inline-block"><a href="">{{ $user->name }}</a></p>
寺島さんの投稿一覧がマージされたので一覧表示用のパーツを```@include```しました。

2023-10-25 17:08 UTC, furusawa501 commented on app/Http/Controllers/UsersController.php
> +        return redirect()->route('user.show', ['id' => $user->id]);
見落としていたので、牧野さんに確認して追加しました。

2023-10-27 09:44 UTC, Osk0830 requested changes
お疲れ様でした！
ほぼ問題なさそうです！
ただ、ふるさわさんのタスクとは直接関係ない部分ですが、一点だけ修正をお願いしたい箇所があります。
お手数ですがよろしくお願いします！

2023-10-27 09:44 UTC, Osk0830 commented on resources/views/users/edit.blade.php
> +    <form method="POST" action="http://localhost:8080/users/{{ $user->id }}">
- すみません！こちらの`action`の箇所、僕がまきのさんのタスクレビュー時に見落としたっぽいですが、この記述はおかしいです。`route()`メソッドを用いて記述を正しく修正する必要がありますが、ふるさわさんの方で修正できそうでしたら修正お願いします。不明点などありましたら、まきのさんと確認しながら修正お願いできればと思います。

2023-10-27 13:48 UTC, furusawa501 commented on resources/views/users/edit.blade.php
> +    <form method="POST" action="http://localhost:8080/users/{{ $user->id }}">
承知しました。

2023-10-29 12:52 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKそうなのでマージしますね！

2023-10-29 12:52 UTC, merged