#707 投稿編集画面・更新(かずふみ)
yukihiroLaravel/joint_develop pull request #766
Opened 2023-10-20 08:27 UTC by kazufumikatsuyama

## issue
- closes #707 

## 概要
- 投稿編集画面・更新

## 動作確認手順
- test1@test.com でログインして
　編集するボタンで、編集画面に飛ぶか
　文字を入れ、
　更新するボタンで、トップページに行き、更新されているか
　確認。

## 考慮して欲しいこと
- 特にありません

## 確認して欲しいこと
- 特にありません

2023-10-21 12:50 UTC, kazufumikatsuyama commented
修正しました。
よろしくお願いします。

2023-10-22 12:27 UTC, yukihiroLaravel requested changes

2023-10-22 12:27 UTC, yukihiroLaravel commented on resources/views/posts/edit.blade.php
> +    <form method="POST" action="{{ route('post.update', $post->id) }}" class="d-inline-block w-100">
ここにinclude持ってくる

2023-10-22 22:25 UTC, yukihiroLaravel approved these changes

2023-10-22 22:25 UTC, merged