#693：「投稿新規作成」を追加
yukihiroLaravel/joint_develop pull request #768
Opened 2023-10-23 13:52 UTC by ma34vn

### 概要
＃６９３：「投稿新規作成』機能の追加について、プルリクを作成しました。

### 制約事項
特になし

### 動作確認手順
Top画面からtestuser3でログインして、コメント欄にテキストを入力して「投稿する」ボタンを押下。
Top画面のコメント一覧の一番上に、入力したコメントが表示されること、postsテーブルにデータが追加されたことを確認。

### 考慮して欲しいこと
特になし
### 確認してほしいこと
特になし

2023-10-24 10:24 UTC, Osk0830 requested changes
お疲れ様でした！
基本は概ねOKだと思います。

修正が必要そうな箇所についていくつかコメントしましたので、
確認よろしくお願いします。

2023-10-24 10:24 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        return redirect('/');
- ログインユーザーのidはURIに含める必要はなさそうです。コントローラー内で取得するだけでOKではないでしょうか？
- こちら必要なバリデーションを挟んでください。本文が空ではダメで、文字数の制限もあると思います。

2023-10-24 10:24 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +                    <textarea class="form-control" name="content" rows="4"></textarea>
- ユーザビリティの観点から、バリデーションで弾かれた際に、既存の入力内容が保持されているようにしてあげた方がいいと思います。

2023-10-24 10:24 UTC, Osk0830 commented on routes/web.php
> +Route::post('posts/{id}', 'PostsController@post')->name('posts.post');
- こちら、ミドルウェアを挟んで、ログイン者のみアクセスできるようにしてください。
- URIについては、コントローラー部分に書いたように `id`を含める必要はないように思われます。

2023-10-24 10:24 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +            <form method="POST" action="{{ route('posts.post', Auth::id()) }}" class="d-inline-block w-75">
- URIの変更があった場合はこちらも併せてお願いします。

2023-10-24 11:58 UTC, ma34vn commented on app/Http/Controllers/PostsController.php
> +        return redirect('/');
引数から$idを削除し、PostRequestを作成してバリデーションを入れました。

2023-10-24 11:58 UTC, ma34vn commented on resources/views/welcome.blade.php
> +                    <textarea class="form-control" name="content" rows="4"></textarea>
value に old('content')を入れるようにしました。

2023-10-24 12:00 UTC, ma34vn commented on routes/web.php
> +Route::post('posts/{id}', 'PostsController@post')->name('posts.post');
Router を middleware の中に入れて、引数は与えないようにしました。

2023-10-24 12:07 UTC, ma34vn commented on resources/views/welcome.blade.php
> +            <form method="POST" action="{{ route('posts.post', Auth::id()) }}" class="d-inline-block w-75">
引数を削除しました。

2023-10-25 05:02 UTC, Osk0830 requested changes
お疲れ様でした！
こちらほとんどOKなのですが、一点だけ修正が必要な箇所がありますので、
確認よろしくお願いします！

2023-10-25 05:02 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +                    <textarea class="form-control" name="content" rows="4" value="{{ old('content') }}"></textarea>
- <input>要素とは異なり、<textarea>の入力値はvalue属性で管理されません。そのため、現状バリデーションで弾かれた際に、既存の入力値が消えてしまうと思います。

2023-10-25 09:59 UTC, ma34vn commented on resources/views/welcome.blade.php
> +                    <textarea class="form-control" name="content" rows="4" value="{{ old('content') }}"></textarea>
なるほど！確かに入力値は消えていました。
修正しましたのでよろしくお願いいたします。

2023-10-26 12:37 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKなのでマージしますね！

2023-10-26 12:37 UTC, merged