Feature/naoki yy/user follow follower
yukihiroLaravel/joint_develop pull request #769
Opened 2023-10-23 13:56 UTC by naoki-yy

## issue 

- Closes #657   

  

## 概要 

- フォロー機能

  

## 動作確認手順 

- 下記コマンドを実行 

php artisan migrate --seed 

- `docker exec -it laravel_app bash`を打ち、
　`php artisan tinker`でtinkerを起動。
　`use App\User`
　`$user1 = User::find(2)`
　`$user2 = User::find(3)`
　`$user1 ->follow($user2->id)`
　上記のコマンドで、adminer上でfollowsテーブルにレコードが登録されたことを確認。
`  $user1->isFollows($user2->id)`
   上記のコマンドで、trueと出れば、フォロー成功。
  

## 考慮してほしいこと 

- トップページの投稿表示が実装されていないため、実際に画面上での操作は出来ません。

  

## 確認してほしいこと 

- 特にございません。

2023-10-24 10:15 UTC, Osk0830 requested changes
お疲れ様でした！
全体的にとても良くできていると思います！

少しだけコメントしましたので、確認よろしくお願いします。
あと、ユーザー詳細もマージされたので、ボタンの組み込みも合わせてお願いします！

2023-10-24 10:15 UTC, Osk0830 commented on app/User.php
> +        }
- 今の状態ですと自分自身をフォローできてしまうと思います（もちろん、ボタンの出し分けはしているので、画面上からはできないですが、tinkerで試してみるとできちゃうかと）。自分自身はフォローできないように記述を少し追加してみてください。念のため、`unfollow()`の方にも追加すると良さそうです。

2023-10-24 10:15 UTC, Osk0830 commented on app/User.php
>      public function posts()
- function同士の間は、見やすく空行を1行ずつ入れてあげましょう。

2023-10-31 14:59 UTC, naoki-yy commented on app/User.php
>      public function posts()
承知しました。

2023-10-31 14:59 UTC, naoki-yy commented on app/User.php
> +        }
承知しました。

2023-11-01 00:15 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKそうなのでマージしますね！

2023-11-02 01:00 UTC, Osk0830 approved these changes
お疲れ様でした！
今度こそマージしますね！

2023-11-02 01:00 UTC, merged