#710 ユーザ編集画面・更新(むらい)
yukihiroLaravel/joint_develop pull request #771
Opened 2023-10-24 04:27 UTC by haru-murai

## issue
- #710 
##  概要
- ユーザ編集画面・更新
## 動作確認手順
- ユーザ詳細画面の【ユーザ情報の編集】をクリックすることでユーザ編集画面に遷移
- 各カラム入力後、【更新する】をクリックすることでユーザ情報が更新され、ユーザ詳細画面に推移する
- バリデーションに抵触する内容にて【更新する】をクリックすると、エラーメッセージが表示される
- ログインしているユーザとは異なる、IDのユーザのユーザ詳細画面では 【ユーザ情報の編集】が表示されない
- URLに直接入力(ログインID：4にて、/users/3/editへアクセス)すると、abort(403)へ遷移　※アクセス権無し
- いったんログアウトし、ユーザ情報を変更したユーザでログインを試みたところ、ログインに成功
## 考慮してほしいこと
- 特になし
## 確認してほしいこと
- エラーメッセージの表示に関して、app.blade.phpに
@include('commons.error_messages')を記述いたしましたが、edit.blade.phpのほうに記述したほうがよろしいのでしょうか。

2023-10-25 16:53 UTC, yukihiroLaravel requested changes

2023-10-25 16:53 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        }
下記の書き方に変更
```
        if($id == \Auth::id()) {
            $user = \Auth::user();
            return view('users.edit', $user);
        }
        abort(403, 'アクセス権がありません'); 
```

2023-10-25 19:11 UTC, haru-murai commented on app/Http/Controllers/UsersController.php
> +        }
ご指摘ありがとうございます。
修正し、コミットいたしました。
ご確認よろしくお願いいたします。

2023-10-26 05:44 UTC, yukihiroLaravel approved these changes
問題ないのでマージしました！
難しい部分を、おつかれさまでした！

2023-10-26 05:44 UTC, merged