Feature/yasuyuki/create new post(yasuyuki)
yukihiroLaravel/joint_develop pull request #777
Opened 2023-10-28 00:37 UTC by YasuLaravel

## issue
-closes 

## 概要
投稿新規作成

## 動作確認手順
localhost8080 にアクセス後下記メールアドレスパスワードでログインする。
mail:test1@test.com
pass:test1
ログイン後ボックス内に文字を入力し投稿するボタンをクリックする。
アドマイナーで投稿されているのを確認。

## 考慮してほしいこと
なし
## 確認してほしいこと
なし

2023-10-28 04:42 UTC, Osk0830 requested changes
お疲れ様でした！
ほぼ問題ないですね！

少しだけ修正が必要な箇所がありますので、
確認よろしくお願いします！

2023-10-28 04:42 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +                    <textarea class="form-control" name="content" rows="4"></textarea>
- ユーザビリティの観点から、バリデーションに弾かれた際に、既存の入力内容が残っているようにしましょう。

2023-10-28 04:42 UTC, Osk0830 commented on app/Http/Requests/PostRequest.php
> +    }
- まだ、バリデーションメッセージの日本語化が完了して分かりにくいのですが、今の状態だと日本語化が完了しても `content`は英語のままになってしまうと思います。`content`が「本文」という日本語で表示されるようにだけ設定しておいてください。

2023-10-29 02:19 UTC, YasuLaravel commented on resources/views/welcome.blade.php
> +                    <textarea class="form-control" name="content" rows="4"></textarea>
old 関数を追記しました。

2023-10-29 02:48 UTC, YasuLaravel commented on app/Http/Requests/PostRequest.php
> +    }
本文と表示されるように追記しました。

2023-10-29 13:01 UTC, Osk0830 requested changes
お疲れ様でした！
一点は修正されていましたが、一点はおかしな記述になってしまっていました。
コメントしましたので確認よろしくお願いします！

2023-10-29 13:01 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +                    <textarea class="form-control" name="content" rows="4">value="{{ old('content') }}"></textarea>
- HTML的におかしな記述になっていますので、修正お願いします。その際、<input>と異なり、<textarea>は入力値を`value属性`で保持しない点注意してくださいね。

2023-10-30 13:25 UTC, YasuLaravel commented on resources/views/welcome.blade.php
> +                    <textarea class="form-control" name="content" rows="4">value="{{ old('content') }}"></textarea>
修正しました。

2023-10-31 03:20 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKなのでマージしますね！

2023-10-31 03:21 UTC, merged