投稿削除その１(寺島)
yukihiroLaravel/joint_develop pull request #780
Opened 2023-10-30 05:39 UTC by daihubemmono

## issue
- Close #692

## 概要
- 投稿削除機能

## 動作確認手順
- 削除ボタンを押した時に投稿が削除されるかどうか確認

2023-10-31 03:33 UTC, Osk0830 requested changes
お疲れ様でした！
基本的に問題ないと思います！

一点修正が必要な箇所がありますので、
確認よろしくお願いします！

2023-10-31 03:33 UTC, Osk0830 commented on routes/web.php
> +Route::delete('{id}', 'PostsController@destroy')->name('post.delete');
- 「削除」はセキュリティ的にしっかりと警戒すべき操作なので、ルーティングの段階からミドルウェアを挟むようにしましょう。

2023-11-01 00:56 UTC, daihubemmono commented on routes/web.php
> +Route::delete('{id}', 'PostsController@destroy')->name('post.delete');
delete_alertを使ってセキュリティー機能を実装しました。

2023-11-01 01:16 UTC, Osk0830 commented on routes/web.php
> +Route::delete('{id}', 'PostsController@destroy')->name('post.delete');
この処理もいいですね！
ただ、これはログインしているかどうかなどの問題に対応できないので、他のいくつかのルーティング同様、ミドルウェアを挟む形にしていただきたい、ということです。

2023-11-02 01:04 UTC, Osk0830 approved these changes
お疲れ様でした！
しっかりと修正できているのでマージしますね！

2023-11-02 01:05 UTC, merged