Feature/kouji/top page post display2
yukihiroLaravel/joint_develop pull request #781
Opened 2023-10-30 09:47 UTC by kouji0117

## issue
Closes https://github.com/yukihiroLaravel/joint_develop/issues/664

## issue
『トップページの投稿表示』の実装

## 動作確認手順
Google Chrome（[http://localhost:8080）にて](http://localhost:8080%EF%BC%89%E3%81%AB%E3%81%A6/)
　正しく表示されているか確認した。

## 考慮してほしいこと
トップページの実装は、進めたが、Aチームの他の皆さんの実装も進んでいることから、コンフリクト等が心配である。

## 確認してほしいこと
適切な実装となっているかどうか。

2023-10-30 09:58 UTC, Osk0830 requested changes
お疲れ様でした！
プルリクは正常になりましたね！

内容ですが、いくつかおかしい箇所がありコメントしましたので、
確認よろしくお願いします！

2023-10-30 09:58 UTC, Osk0830 commented on app/User.php
> +    public function post()
- このメソッドは、1人のユーザーに複数の投稿が紐づいているので、複数形の方がいいです。

2023-10-30 09:58 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +             @endforeach
- foreachで繰り返す部分がおかしくないでしょうか？

2023-10-30 09:58 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                     <form method="POST" action="">
- ここは今回のタスクとは無関係なので追記不要です。

2023-10-30 09:58 UTC, Osk0830 commented on resources/views/welcome.blade.php
> -
- ここはなぜ削除されたのでしょうか？

2023-10-30 11:44 UTC, kouji0117 commented on resources/views/welcome.blade.php
> -
9-21行を復活させて、@authを用いてログイン前だと、『コメント記入欄』と『青色ボタン』が非表記になるよう修正しました

2023-11-01 10:36 UTC, Osk0830 requested changes
お疲れ様でした！
確認したところ、前回のコメントで書いた内容が修正されていないようでしたので、
再度確認お願いします！

2023-11-01 10:36 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                </div>
以前、下記コメントでも書きましたが、foreachでループする対象がおかしいです。スクショでわかるように、<div>がいくつも生成されていますが、<li>が複数生成されるようにする必要があります。

https://github.com/yukihiroLaravel/joint_develop/pull/781#discussion_r1375946172

[![Image from Gyazo](https://i.gyazo.com/23605a71486e3be26dafb318f8a46865.png)](https://gyazo.com/23605a71486e3be26dafb318f8a46865)

2023-11-03 12:17 UTC, kouji0117 commented on resources/views/posts/posts.blade.php
> +                </div>
div　と　li　の位置を変更してみました。
動作確認したところ、お手本と見た目は、同じ表示となりますがいかがでしょうか。
ご確認よろしくお願い致します。

2023-11-05 00:24 UTC, Osk0830 requested changes
お疲れ様でした！
こちら内容的にはOKそうですが、少しだけ調整が必要な箇所がありますので、
確認よろしくお願いします！

2023-11-05 00:24 UTC, Osk0830 commented on resources/views/welcome.blade.php
> -            <h1><i class="pr-3"></i>Topic Posts</h1>
- こちらのファイル、インデント（行頭の位置）がガタガタになっているので、綺麗に整理してみてください。

[![Image from Gyazo](https://i.gyazo.com/ff3a3dd7912c8a59788fead3d0258c79.png)](https://gyazo.com/ff3a3dd7912c8a59788fead3d0258c79)

2023-11-05 07:21 UTC, kouji0117 commented on resources/views/welcome.blade.php
> -            <h1><i class="pr-3"></i>Topic Posts</h1>
お疲れ様です。
・インデントを修正しました。
・ログイン時のユーザー認証を@ifを用いた形としました。
・@includeを必要な部分のみの表記としました。

2023-11-08 00:19 UTC, Osk0830 approved these changes
お疲れ様でした！
遅くなってすみません。。！

こちらしっかり修正できているのでマージしますね！

2023-11-08 00:19 UTC, merged