#691 投稿編集画面・更新（ふるさわ）
yukihiroLaravel/joint_develop pull request #783
Opened 2023-10-31 16:09 UTC by furusawa501

## issue
- Closes
 #691

## 概要
-#691 投稿編集画面・更新（ふるさわ）

## 動作確認手順
- ```http://localhost:8080/``` を表示
- ```testuser1```でログイン
- トップページの投稿一覧から適当に投稿を選んで「編集する」ボタン押下
- 投稿がテキストボックスに表示されていることを確認
- 投稿を編集し「更新する」ボタン押下
- トップページに遷移し編集が反映されていることを確認
- 再度適当に投稿を選んで「編集する」ボタン押下
- １４０文字以上の投稿しエラー表示され、入力した投稿がテキストボックスに表示されていることを確認
- 空の投稿をしてエラー表示されることを確認

## 考慮して欲しいこと
- 特にありません。

## 確認して欲しいこと
- 特にありません

2023-11-01 00:25 UTC, Osk0830 requested changes
お疲れ様でした！
全体的によくできていると思います！
三項演算子を利用した部分などいい感じですね！

少しだけコメントしましたので、確認よろしくお願いします！

2023-11-01 00:25 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +    }
- 編集ページですので、投稿者本人だけがアクセスできるようにしましょう！

2023-11-01 00:25 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +    }
- こちらも、edit同様、投稿者本人の場合にのみ更新処理がなされるようにしてください。

2023-11-01 00:25 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +          <p class="text-muted">{{ $post->updated_at }}</p>
- ここですが、現状投稿一覧は、作成日基準で新しいものから降順で表示されるようになっているので、表示される日付が作成日でなく更新日になってしまうとちょっとおかしな感じになりませんかね？この部分、デモサイトはどうなってましたかね？

2023-11-01 16:33 UTC, furusawa501 commented on resources/views/posts/posts.blade.php
> +          <p class="text-muted">{{ $post->updated_at }}</p>
すみません、勘違いでした。デモサイトは作成日でしたので元に戻します。

2023-11-01 16:35 UTC, furusawa501 commented on app/Http/Controllers/PostsController.php
> +    }
直接アドレスバーにpostidを入力するとログインユーザ以外の投稿を変更できてしまいますね。
修正します。

2023-11-01 16:35 UTC, furusawa501 commented on app/Http/Controllers/PostsController.php
> +    }
edit同様こちらも修正します。

2023-11-08 00:26 UTC, Osk0830 approved these changes
お疲れ様でした！
遅くなってすみません。。！

こちらしっかり修正できているのでマージしますね！

2023-11-08 00:27 UTC, merged