Feature/naoki yy/user destroy
yukihiroLaravel/joint_develop pull request #787
Opened 2023-11-02 14:47 UTC by naoki-yy

## issue 

- Closes #660  

  

## 概要 

- 投稿削除 

  

## 動作確認手順 

- 下記を実行 

- トップページの削除ボタンを押し、投稿が消えるかどうか。

- Adminerでpostsテーブルのdeleated_atカラムで削除ボタンを押した日時が出ているかを確認 

  

## 考慮してほしいこと 

- 削除ボタンを押す動作確認のため、やすゆきさんのタスクでマージされたposts.blade.phpをwelcome.blade.phpにincludeしています。

  

## 確認してほしいこと 

- 特にございません。

2023-11-04 23:59 UTC, Osk0830 requested changes
お疲れ様でした！
動き自体は問題ないと思います。
ただ、いくつか修正が必要な箇所がありますので、
確認よろしくお願いします！

2023-11-04 23:59 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +            return back();
- こちら、`return`がif文の中にあると、if文の条件に合致しなかった場合何もreturnされず、処理が止まってしまいます。

2023-11-04 23:59 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
>                           <button type="submit" class="btn btn-danger">削除</button>
- インデントが少し崩れているようです。
- `route()`メソッドの引数を区切るカンマの後ろは半角空白を入れる感じで統一しましょう。

2023-11-04 23:59 UTC, Osk0830 commented on routes/web.php
> +Route::delete('users/{id}/destroy', 'PostsController@destroy')->name('post.delete');
- 投稿の削除だと、URIがおかしい感じがします。`posts/{id}`に対するDELETEメソッドのようにするのが整合性が取れているかと思います。
- こちらはミドルウェアを挟みましょう。
- また、他のルーティングとまとめて整理できそうなので、整理してみてくださいね。

2023-11-05 00:31 UTC, naoki-yy commented on app/Http/Controllers/PostsController.php
> +            return back();
returnを外に出すよう修正します。

2023-11-05 00:32 UTC, naoki-yy commented on resources/views/posts/posts.blade.php
>                           <button type="submit" class="btn btn-danger">削除</button>
インデント、カンマの件、修正します。

2023-11-05 00:34 UTC, naoki-yy commented on routes/web.php
> +Route::delete('users/{id}/destroy', 'PostsController@destroy')->name('post.delete');
承知しました。

2023-11-05 01:24 UTC, Osk0830 approved these changes
お疲れ様でした！
`Route::delete('{id}/destroy'`の「desteoy」の部分は冗長な感もありますが、
一旦問題ないのでマージしますね！

2023-11-05 01:24 UTC, merged