#165 投稿のフラッシュメッセージ(かずふみ)
yukihiroLaravel/joint_develop pull request #788
Opened 2023-11-03 03:30 UTC by kazufumikatsuyama

## issue
- closes #165

## 概要
- 投稿のフラッシュメッセージの実装

## 動作確認手順
⒈ test3@test.comでログインする
⒉ 適当な文字を入力して、投稿するのボタンを押す
　「投稿に成功しました。」メッセージが表示される
⒊ 編集ボタンを押し、また適当な文字を入れ、更新するボタンを押す
　「投稿編集に成功しました。」メッセージが表示される
⒋ 削除ボタンを押したら
　「削除に成功しました。」メッセージが表示される

## 考慮してほしい事
resource>views>commons>success_message.blade.php
で、もっと簡潔なプログラムがあるのではないかと
思ったんですが
うまく行かなかたです。

## 確認してほしい事
特にありません

2023-11-03 11:58 UTC, yukihiroLaravel requested changes
１つアドバイス書きましたのでご確認ください！

2023-11-03 11:58 UTC, yukihiroLaravel commented on resources/views/commons/success_messages.blade.php
> +@if (session('destroyMessage'))
@elseif (session('destroyMessage'))

このようにしたほうがコードを簡略化できると思いました！

2023-11-03 11:58 UTC, yukihiroLaravel commented on resources/views/commons/success_messages.blade.php
> +@if (session('editMessage'))
@elseif (session('editMessage'))

このようにしたほうがコードを簡略化できると思いました！

2023-11-03 11:58 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +        @include('commons.success_messages')
まとめられていて素晴らしいですね✨

2023-11-04 02:35 UTC, kazufumikatsuyama commented
ご指摘ありがとうございます。

承知しました。
やってみます。

2023-11-05 10:18 UTC, yukihiroLaravel requested changes
いくつかコメントしましたので
ご確認ください！

2023-11-05 10:18 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        return back()->with('destroyMessage', '・削除に成功しました。');
他と合わせて
「投稿削除に成功しました。」
にしたほうがいいかと思います！

2023-11-05 10:18 UTC, yukihiroLaravel commented on resources/views/commons/success_messages.blade.php
> +@endif
インデントを下記のように揃えましょう！
```
@if (session('successMessage'))
    <div class="alert alert-success w-75 m-auto">
        {{ session('successMessage') }}
    </div>
<!-- 削除に成功　-->
@elseif (session('destroyMessage'))
    <div class="alert alert-success w-75 m-auto">
        {{ session('destroyMessage') }}
    </div>
<!-- 編集に成功　-->
@elseif (session('editMessage'))
    <div class="alert alert-success w-75 m-auto">
        {{ session('editMessage') }}
    </div>
@endif
```

2023-11-05 11:23 UTC, kazufumikatsuyama commented
ご指摘ありがとうございます。
確認しました。

修正いたしました。
よろしくお願いします。

2023-11-05 12:03 UTC, yukihiroLaravel approved these changes
OKですのでマージしました！
おつかれさまでした！

2023-11-05 12:03 UTC, merged