Feature/naoki yy/post edit
yukihiroLaravel/joint_develop pull request #792
Opened 2023-11-03 16:16 UTC by naoki-yy

## issue 

- Closes #659 

  

## 概要 

- 投稿編集画面・更新

  

## 動作確認手順 

- トップページにて、自身の投稿の左下部にある編集するボタンを押し、編集画面が出るか確認
- その後、内容を変え、更新するボタンを押し、トップページの投稿表示画面で投稿内容が変わっているか確認。
- Adminerでpostsテーブルのupdated_atカラムに日付が入っていることを確認 

## 考慮してほしいこと 

- トップページの投稿表示はマージされていませんが、動作確認の実施のため、
やすゆきさんの方で実装されたposts.blade.php（投稿表示するブレード）をincludeしています。

 
## 確認してほしいこと 

- 特にございません。

2023-11-05 00:16 UTC, Osk0830 requested changes
お疲れ様でした！
こちら概ねOKですが、少しだけ修正が必要な箇所がありますので、
確認よろしくお願いします！

2023-11-05 00:16 UTC, Osk0830 commented on resources/views/posts/post_edit.blade.php
> +        <textarea id="content" class="form-control" name="content"></textarea>
- こちら、ユーザビリティの観点から、①初回は現在DBに登録されている投稿内容が、②直前に入力していた内容があるのにバリデーションで弾かれた際は直前に入力していた内容が、それぞれ表示されるようにしてあげてください。

2023-11-05 00:16 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +            $post->user_id = $request->user()->id;
- 投稿者のidを変更することはないので、不要な記述だと思います。

2023-11-05 00:16 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                <p class="mt-3 mb-0 d-inline-block"><a href="{{ route('user.show', $post->user_id) }}">{{ $post -> user->name }}</a></p>
- `->`前後は空けずにつけて書きましょう。

2023-11-05 00:38 UTC, naoki-yy commented on app/Http/Controllers/PostsController.php
> +            $post->user_id = $request->user()->id;
`$post->user_id = $request->user()->id;`の箇所を削除いたします。

2023-11-05 00:40 UTC, naoki-yy commented on resources/views/posts/posts.blade.php
> +                <p class="mt-3 mb-0 d-inline-block"><a href="{{ route('user.show', $post->user_id) }}">{{ $post -> user->name }}</a></p>
修正いたします。

2023-11-05 00:47 UTC, naoki-yy commented on resources/views/posts/post_edit.blade.php
> +        <textarea id="content" class="form-control" name="content"></textarea>
Valueを使いました。

2023-11-05 09:42 UTC, Osk0830 commented on resources/views/posts/post_edit.blade.php
> +        <textarea id="content" class="form-control" name="content"></textarea>
- input要素と違って、textareaは、valueで入力値を管理しないです。そのため、おそらく現状だと、バリデーションで弾かれた際に入力内容表示されなくならないでしょうか？

2023-11-05 14:21 UTC, naoki-yy commented on resources/views/posts/post_edit.blade.php
> +        <textarea id="content" class="form-control" name="content"></textarea>
Valueを使わない方法で、修正いたしました。

2023-11-06 07:37 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKそうなのでマージしますね〜！

2023-11-06 07:37 UTC, merged