#753_replyリプライ(dera)
yukihiroLaravel/joint_develop pull request #793
Opened 2023-11-04 22:28 UTC by Jino225242

## issue
- Closes #753  

## 動作確認手順

- ログアウト状態
1. リプライ一覧表示　：投稿に対するリプライ一覧が表示される
2. リプライ投稿　　　：投稿に対してリプライ不可（ログインページへ遷移）
3. リプライ編集　　　：アクセス不可（URLへルーティングを直接入力するとログインページへ遷移）
4. リプライ削除　　　：アクセス不可（URLへルーティングを直接入力するとログインページへ遷移）

- ログイン状態
1. リプライ一覧表示
投稿に対するリプライ一覧が表示され、自身のリプライの場合は下部に「編集」「削除」アイコンが表示される
2. リプライ投稿
各投稿の下部に「リプライ」アイコンが表示され、クリックすることでリプライ投稿画面へ遷移し、リプライ投稿可能となる
3. リプライ編集
リプライ一覧表示にて自身投稿のリプライ下部に表示された「編集」アイコンをクリックすることで、リプライ編集画面へ遷移し、リプライ編集可能となる
4. リプライ削除
リプライ一覧表示にて自身投稿のリプライ下部に表示された「削除」アイコンをクリックすることで、リプライ削除画面へ遷移し、リプライ削除可能となる

  
## 考慮して欲しいこと
「いいね」機能をじゅんやさんが作業中のため、「いいね」アイコンはルーティング未入力として作成しておりました。
『全体修正』に関わる部分も２つ目のPRとしてあげさせていただきました。

## 確認して欲しいこと（質問）
仕様を考えていた時には想定できていなかったエラーが多数発生してしまい、以下のコードが非常に煩雑に感じております。
少しでもスマートになる部分があれば、ご教授いただけますでしょうか。
`app/Http/Controllers/ReplyController.php`
`resources/views/replies`
`resources/views/posts/posts.blade.php`

2023-11-05 06:18 UTC, yukihiroLaravel requested changes
https://www.loom.com/share/38e7b8cec7354aa484f9b37eb3f7cb5a?sid=b5182a25-3b6a-4d03-9c3e-ea8bea0967ff

2023-11-05 06:18 UTC, yukihiroLaravel commented on app/Http/Controllers/ReplyController.php
> +            return view('replies.index', compact('post', 'replies'));
return redirect(リプライインデックスのルーティング)

PRGの原則

2023-11-05 06:18 UTC, yukihiroLaravel commented on app/Http/Controllers/ReplyController.php
> +        return view('replies.index', compact('post', 'replies'));
return redirect(リプライインデックスのルーティング)

PRGの原則

2023-11-06 15:41 UTC, Jino225242 commented on app/Http/Controllers/ReplyController.php
> +            return view('replies.index', compact('post', 'replies'));
return redirect()->route('replies.index', $postId);　に修正いたしました。

2023-11-06 15:41 UTC, Jino225242 commented on app/Http/Controllers/ReplyController.php
> +        return view('replies.index', compact('post', 'replies'));
こちらも、return redirect()->route('replies.index', $postId);　に修正いたしました。

2023-11-07 09:35 UTC, yukihiroLaravel requested changes
ほぼ完璧です。
細かいインデントのみ修正お願いします🙇‍♂️
https://www.loom.com/share/0a6eca90f6234eefa86dc3d3593f41fa?sid=fe7ebd9a-50e6-46b9-8a6f-935dd4a05cae

2023-11-07 09:35 UTC, yukihiroLaravel commented on app/Reply.php
> +        }
インデント

2023-11-07 09:35 UTC, yukihiroLaravel commented on app/User.php
> +        }
インデント

2023-11-07 09:35 UTC, yukihiroLaravel commented on app/Post.php
> +        }
インデント

2023-11-08 06:23 UTC, yukihiroLaravel approved these changes
OKです！！

問題ありませんのでマージしました。
ご確認お願いいたします☺️

2023-11-08 11:42 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！

難易度が高い機能を高いクオリティでやっていただけたと思います。
おつかれさまでした！☺️

2023-11-08 11:42 UTC, merged