#671 フラッシュメッセージ表示（ごめ）
yukihiroLaravel/joint_develop pull request #809
Opened 2023-11-12 17:19 UTC by gomez8927

## issuse
- closes #671 
## 概要
フラッシュメッセージ表示

## 動作確認手順
下記コマンドを実行
git add .

git commit -m"フラッシュメッセージ"

git push origin feature/horigome/flash-messages

git log

## 考慮してほしいこと
自分の書いた記述が適用されているかどうか。
今回練習でたくさんフラシュメッセージが表示されるようにしまいた。（必要かどうかは別として）

## 確認して欲しいこと
6つのControllerとapp.blade.phpのコードが正しいか確認お願いします。
以下変更内容

・Register Controller
新規登録→「新規登録しました」

・LoginController
ログイン→「ログインしました」
ログアウト→「ログアウトしました」

・PostsController
投稿→「投稿しました」
投稿編集→「投稿を編集しました」
投稿削除→「投稿を削除しました」

・UsersController
ユーザー情報の編集→「ユーザ情報を更新しました」
画像アップロード→「画像をアップロードしました」

・Follow Controller
フォロー→「フォローしました」
アンフォロー→「アンフォローしました」

・Reply Controller
返信→「リプライしました」
            「リプライを削除しました」

appでは、文字のサイズにフラシュメッセージの幅が調整されるように以下のコードを入力。大丈夫でしょうか？
```
<style>
            .alert-custom {
                display: inline-block;
                max-width: 100%;
                margin-top: 20px; /* 余白調整 */
            }

```

また5秒後に消えるような設定にしたいと思い以下のコードを書いたが、うまく機能せず断念。
問題点がわかればアドバイスお願いします。
```
<script>
    $(document).ready(function() {
        console.log("Document is ready");
        setTimeout(function() {
            console.log("Starting fadeOut");
            $(".alert").fadeOut('slow', function() {
                console.log("FadeOut completed");
            });
        }, 5000);
    });
</script>

```

2023-11-12 23:51 UTC, yukihiroLaravel requested changes
コメントしました！
https://www.loom.com/share/a522ed7a54034b4dba54d7e760f9dd7b?sid=42e98831-0ce4-473b-b865-5c38a0236ee4

2023-11-12 23:51 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        return back()->with;
ここのwithは不要ではないでしょうか？

2023-11-13 04:01 UTC, gomez8927 commented on app/Http/Controllers/PostsController.php
> +        return back()->with;
訂正しました

2023-11-13 08:01 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！

2023-11-13 08:01 UTC, merged