#65トップページの投稿表示(竹渕)
yukihiroLaravel/joint_develop pull request #81
Opened 2022-10-23 07:58 UTC by bucchi-orange

## issue
-Closes #65 

## 概要
- トップページの投稿表示

## 動作確認手順
- localhost:8080にアクセスして
トップページの投稿画面が正常に表示されるかを確認してください

## 考慮してほしいこと
- シーダーの関係で、updated_atが表示されません。
データベース(localhost:8088)にて手動で登録いただければと思います。

- ユーザーの詳細画面は次回に実装します

2022-10-25 04:09 UTC, Osk0830 requested changes
お疲れ様です！
ほとんどできていると思います！
少しだけコメントしたので、確認よろしくお願いします。

2022-10-25 04:09 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +            </div>
- こちらのhrefの部分は、ユーザー詳細画面の作成に着手していない段階ですので、詳細画面のルーティング、URIもまだ未定だと思います。なので、現段階では、`#`にしとく方が望ましいですね。
- また、仮にルーティングが決まり、URIが確定した段階でも、hrefの箇所は、URIを直書きせずに、`route()`関数などを用いて生成するのが望ましいです。仮に、URIに変更が生じた場合でも、ルーティングファイルだけを書き換えれば済むからです。こちらに関しては、ユーザ詳細などの実装を行う段階で調べてみて、わからないことがあればご質問くださいね！

2022-10-25 04:09 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                    <p class="text-muted">{{ $post->created_at }}</p>
- 以前MTG時に少しお話ししましたが、現在のダミーデータは、DBファザードのinsert()で挿入されているため、created_atなどのカラムがnull状態です。そのため、日付部分に何の表示もありません。ただ、この状態ですとお手本通りの表示が実現できているかの確認ができないので、ローカルでDBのpostsテーブルに必要な情報を入力してみて、正常に表示できていることが確認できるスクショを添付するなどしてもらえるといいかもですね。

[![Image from Gyazo](https://i.gyazo.com/8f4647041ee00d22065107a16f3ed2f3.png)](https://gyazo.com/8f4647041ee00d22065107a16f3ed2f3)

↓例えば、こんな感じのキャプチャとか。。笑
[![Image from Gyazo](https://i.gyazo.com/77917d7be7f9f11a54a7e85f8e1c2de7.png)](https://gyazo.com/77917d7be7f9f11a54a7e85f8e1c2de7)

2022-10-25 04:39 UTC, bucchi-orange commented on resources/views/posts/posts.blade.php
> +            </div>
分かりました！
今夜修正します！

2022-10-25 04:40 UTC, bucchi-orange commented on resources/views/posts/posts.blade.php
> +                    <p class="text-muted">{{ $post->created_at }}</p>
アドバイスありがとうございます！
上の修正と合わせて、改めてPRします。

2022-10-25 13:25 UTC, bucchi-orange commented
ご指摘の点修正いたしましたので、再レビューをお願いします

## 変更点
- ユーザー詳細画面へのリンクを#に変更しました。
- DBのpostテーブルに必要な情報を登録して、投稿日の表示を確認しました。
↓こちらが確認画像です。
![タイトルなし](https://user-images.githubusercontent.com/112021852/197784096-453e66ee-7d1f-4e54-bc6d-5f4650baf374.png)

2022-10-26 02:12 UTC, Osk0830 approved these changes
お疲れ様です！
こちら問題ないと思うので、マージしますね！

一応一点だけコメントしたので、お手隙の際にでもご確認いただければと思います^^

2022-10-26 02:12 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +            </div>
- 4行目で、$post->userを、$userにせっかく代入してるので、8行目でも、9行目同様、$userを用いると統一性があっていいかもですね。

2022-10-26 02:12 UTC, merged

2022-10-26 04:39 UTC, bucchi-orange commented on resources/views/posts/posts.blade.php
> +            </div>
確かにそうですね！
次のissueで合わせて修正しておきます。