#67 投稿新規作成(竹渕)
yukihiroLaravel/joint_develop pull request #83
Opened 2022-10-30 03:05 UTC by bucchi-orange

## issue
- Closes #67

## 動作確認手順
localhost:8080
にアクセスし、新規投稿が行えるかを確認する

## 確認してほしいこと
バリデーションの実行のために
app/http/requests/PostRequest.php
を作成しましたが、その方法であっているか

2022-11-01 04:32 UTC, Osk0830 requested changes
お疲れ様でした！
レビュー遅くなってすみません！
全体的に良くできていて素晴らしいと思います！
ユーザビリティの観点から少し改善した方がいいと思われる箇所がありコメントしましたので、確認よろしくお願いします！

2022-11-01 04:32 UTC, Osk0830 commented on app/Http/Requests/PostRequest.php
> +}
フォームリクエスト自体の作成・利用方法は正しくできていると思います！
ただ、少し残念なのは、ユーザビリティを考えた時に、バリデーションメッセージで、「投稿の本文」が`text`と表示されたり、「必ず入力して」ほしい旨が`指定`となったりするのは少し不親切かと思われるので、内容に応じたわかりやすいメッセージが表示されるようにしてみてください。

[![Image from Gyazo](https://i.gyazo.com/0596cd75f4356917e17c7e6db644dbe0.png)](https://gyazo.com/0596cd75f4356917e17c7e6db644dbe0)

[![Image from Gyazo](https://i.gyazo.com/98741ffe40fae70a1d6a240d37b9f850.png)](https://gyazo.com/98741ffe40fae70a1d6a240d37b9f850)

2022-11-01 04:32 UTC, Osk0830 commented on resources/views/posts/create.blade.php
> +            <div class="text-left mt-3">
指定の文字数を超過してバリデーションで弾かれた際に、せっかく前に入力していた内容が消えてしまうのは、ユーザビリティ的に良くないと思うので、戻ってきた際に前のメッセージが残っているようにしてみましょう。

2022-11-01 08:56 UTC, bucchi-orange commented on resources/views/posts/create.blade.php
> +            <div class="text-left mt-3">
分かりました。
修正加えます！

2022-11-01 15:03 UTC, bucchi-orange commented
ご指摘いただいた点を修正しましたので、再レビューをお願いします。

## 修正内容
- bladeファイルにold('text')を追加して、エラーの際に元の入力内容が消えないようにしました。
- エラーメッセージが『text』であった点を『本文』に変更しました。
- requiredでのエラーメッセージを変更しました。

2022-11-02 06:32 UTC, Osk0830 approved these changes
お疲れ様です！
修正OKなので、こちらマージしますね〜。
引き続き頑張っていきましょう！

2022-11-02 06:32 UTC, merged