#833 共通ファイル & ヘッダー・フッター & トップページ表示（はいしま）
yukihiroLaravel/joint_develop pull request #836
Opened 2023-11-26 08:04 UTC by hatschi2023

## issue
- Closes #833 

## 概要
- 共通ファイル & ヘッダー・フッター & トップページ表示を作成

## 動作確認手順

- http://localhost:8080/
接続時に下記の共通ページの表示が正しく実装されているか、確認をお願いします。
1. トップページ
2. ヘッダー
3. フッター

## 考慮してほしいこと
- 前回の作業を見直していく中で、初回の作業ブランチ名を間違えて作成していたことに気づきました。
そこで今回は初回でマージ前なので、自学もかねてローカルのチームブランチを削除して最初からやり直しました。
そのため本コミット履歴には、既にリポジトリでマージされていた林さんのコミットが含まれています。
（作業ファイルが異なるため差分は発生していません）

## 確認してほしいこと
- 前回ご確認いただいた内容（ファイルの権限変更以外）について
指摘いただいた箇所を削除しました。

- ubuntu事案の大量のファイル権限変更について
コンテナ経由で作成した、新規ファイルの権限エラーは相変わらず発生しますが、
今回以降、作成したファイル（ディレクトリ）に対してのみ権限変更することにして様子を見たいと思います。
（※前回はプロジェクト全体に対して権限変更かけていたので）
教えていただいたコマンド（**git config core.filemode false**）のおかげか、
コミット前のステータス確認でも、前回の問題は出ませんでした。

2023-11-26 14:04 UTC, yukihiroLaravel requested changes
プルリクの出し方、issueも含め、
完璧かと思います！☺️

権限問題も一旦なくなってよかったです！

１点だけ指摘しましたのでご確認ください！

2023-11-26 14:04 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +class UsersController extends Controller
細かい指摘で今更ですが
こちらのクラス名とファイル名について

UsersController
ではなく
PostsController

の方がふさわしいかと思います！

現時点では投稿もユーザーも表示されておらず、
わかりにくいのですがお手本アプリを見ていただくと
仕様的にはトップページでは
ユーザ一覧を表示させるのではなく、投稿(Post)一覧を表示させる役割
だからです！

なので、ゆくゆくの仕様を考えると、
PostsControllerの方がいいと思いました！

2023-11-27 00:55 UTC, hatschi2023 commented on app/Http/Controllers/UsersController.php
> +class UsersController extends Controller
早速レビューありがとうございます！
なるほど！各機能の名前も今後のことを考えて設計していくものなのですね。
わかりやすさをより考慮して開発していきたいと思います！

2023-11-27 04:08 UTC, yukihiroLaravel approved these changes
すべて問題ないのでマージしました！

おつかれさまでした☺️

2023-11-27 04:08 UTC, merged