posts(投稿)テーブルのマイグレーションとシーダー作成（鈴木）
yukihiroLaravel/joint_develop pull request #837
Opened 2023-11-26 09:29 UTC by takahito717

## issue
- Closes #834 

## 概要

- posts（投稿）テーブルのマイグレーションとシーダー作成

## 動作確認手順
- 下記コマンドを実行
php artisan migrate --seed
- Adminerでpostsテーブルが作成され、5個のレコードが保存されていることを確認

## 考慮して欲しいこと
- 

## 確認してほしいこと
- テーブルのカラムが正しいかを確認していただきたいです。titleが必要かどうかで迷いました。
- シーダーで登録した情報が5個でしたが、この数でいいのかどうか判断できませんでした。

2023-11-27 13:58 UTC, Osk0830 requested changes
お疲れ様でした！
概ねOKです！
少しだけ修正いただきたい箇所がありますので、
確認よろしくお願いします！

2023-11-27 13:58 UTC, Osk0830 commented on app/User.php
> +    }
- こちらのメソッド名ですが、1対多の関係で、一人のユーザーに複数の投稿が紐づいているという関係にあることを表すため複数形にするのが基本ですので、`posts`のように複数形にしましょう。

2023-11-27 13:58 UTC, Osk0830 commented on database/migrations/2023_11_26_055808_create_posts_table.php
> +            $table->string('content', 140); //140文字の制限を設定
- 今回の、現段階での要件では、投稿にタイトルは不要で、本文だけあればOKです！

2023-11-27 14:42 UTC, takahito717 commented on app/User.php
> +    }
該当箇所修正しました。

2023-11-27 14:43 UTC, takahito717 commented on database/migrations/2023_11_26_055808_create_posts_table.php
> +            $table->string('content', 140); //140文字の制限を設定
マイグレーションファイルとシーダーからtitleを削除しました。

2023-11-30 11:32 UTC, Osk0830 approved these changes
お疲れ様でした！
通知気づかず大変遅くなってしまい申し訳ありません。。！
こちらOKなのでマージしますね！

2023-11-30 11:32 UTC, merged