ユーザ編集画面、更新
yukihiroLaravel/joint_develop pull request #838
Opened 2023-12-02 11:05 UTC by hatschi2023

## issues
closes #827

## 概要
- ユーザ編集画面、更新

## 動作確認手順

- http://localhost:8080/users/1/edit
接続時に下記ページが正しく実装されているか、確認をお願いします。
1. ユーザ編集画面の表示
・ログイン後のユーザ情報（ユーザ名、メールアドレス）が表示されていること

2. ユーザ情報を編集し（※メールアドレスの変更必須）、更新ボタン押下
入力が正しい場合トップ画面が表示
データベースに変更が保存されていること

3. 入力不備がある場合
編集画面が再表示され、バリデーションでエラーが表示されること
データが保存されないこと

## 考慮してほしいこと
- 更新後の画面はひとまずトップページに設定しています。
後日ユーザ詳細画面が実装されたら、そちらに変更する予定。

## 確認してほしいこと（質問）
- ユーザ情報更新時のバリデーションについて
現状メールアドレスを変更しないと、エラーが出てしまいます。
解消するにはどうすればよいでしょうか。

- UsersController のedit/updateメソッドで、ユーザ情報を取得するのに下記のどちらがよいのかわかりませんでした。　
どちらが正解でしょうか。
$user = \Auth::user();
$user = User::find($id);　←採用した

- 現状ではログインユーザ以外のユーザの編集画面がurl指定で表示できてしまいます。
どこに制御を追加するべきでしょうか。

2023-12-02 11:26 UTC, yukihiroLaravel requested changes
プルリクへコメントと
動画で撮影しました！

ご確認ください。

https://www.loom.com/share/9a93a6f914934a62a5d3f48b81e4e947?sid=7673ade7-2827-4ba6-a707-623a1dd7c99b

2023-12-02 11:26 UTC, yukihiroLaravel commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
方法
https://qiita.com/Masataka_Sugia/items/0a9e2b240aa5b149f1d9

2023-12-02 11:26 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        return view('users.useredit',$data);
if (ログインユーザのid == $id) {
   編集画面にいく
}
abort(404);

2023-12-02 11:26 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        return view("welcome");
PRGパターン

return redirect("/");

2023-12-02 14:55 UTC, hatschi2023 commented on app/Http/Controllers/UsersController.php
> +        return view('users.useredit',$data);
修正しました！

2023-12-02 14:56 UTC, hatschi2023 commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
修正しました！

2023-12-02 14:57 UTC, hatschi2023 commented on app/Http/Controllers/UsersController.php
> +        return view("welcome");
修正しました！

2023-12-02 15:56 UTC, yukihiroLaravel requested changes
コメントしました！ご確認ください！

2023-12-02 15:56 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        else
このelseの書き方でもできるかもしれないのですが
一般的なPHPの書き方と異なり
見辛いので当初お伝えの通り
下記でいきましょう

```
if (条件) {
  return ~
}
abort(404);
```

2023-12-02 15:56 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        if (\Auth::check() && \Auth::id() == $id)
ログインしていないとそもそもここには到達できないので
\Auth::check()
は不要かなと思います！

また、
\Auth::id()を改めて定義して使うより
直前に定義しているものを使うほうが効率的なので

$user->id == $id

という書き方もできるかと思いました！

2023-12-03 03:25 UTC, hatschi2023 commented on app/Http/Controllers/UsersController.php
> +        if (\Auth::check() && \Auth::id() == $id)
勉強になります！修正いたしました！

2023-12-03 03:25 UTC, hatschi2023 commented on app/Http/Controllers/UsersController.php
> +        else
修正いたしました！

2023-12-03 11:40 UTC, yukihiroLaravel requested changes
さらに２点だけコメントしましたので、
お手数ですがご確認願います！

2023-12-03 11:40 UTC, yukihiroLaravel commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:25', Rule::unique('users')->ignore(\Auth::id())],
今きづいたのですが、メールアドレスが２５文字以内ですと、それを超えるメールアドレスも全然ありうるので
データベースと同じ上限文字数に変更しておきましょう

2023-12-03 11:40 UTC, yukihiroLaravel commented on app/Http/Requests/UserRequest.php
> +            'name' => ['required', 'string', 'max:25'],
今きづいたのですが、
名前も２５文字制限でもいいのですが、今回はお手本通りとして
データベースと同じ上限文字数に変更しておきましょう

2023-12-03 11:57 UTC, hatschi2023 commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:25', Rule::unique('users')->ignore(\Auth::id())],
25→255に修正しました！

2023-12-03 11:57 UTC, hatschi2023 commented on app/Http/Requests/UserRequest.php
> +            'name' => ['required', 'string', 'max:25'],
25→255に修正しました！

2023-12-03 13:28 UTC, yukihiroLaravel approved these changes
OKですのでマージしました！
おつかれさまでした☺️

2023-12-03 13:28 UTC, merged