ユーザー詳細（林）
yukihiroLaravel/joint_develop pull request #842
Opened 2023-12-07 05:36 UTC by tatsuhirohayashi

## issue
・Closes #828 

## 概要
ユーザー詳細

## 動画確認手順
ログイン後、ヘッダーのユーザー名を押下。
正しくユーザー詳細画面が表示されているか確認。

## 考慮して欲しいこと
・特になし

## 確認してほしいこと
・特になし

2023-12-08 13:03 UTC, Osk0830 requested changes
お疲れ様でした！
こちら概ねよくできていると思います！

少しだけ修正が必要な箇所がありコメントしましたので、
よろしくお願いします！

2023-12-08 13:03 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="{{route('user.show', $user->id)}}" class="nav-link {{ Request::is() ? 'active' : '' }}">タイムライン</a></li>
- こちらの記述が一部不足しているため、どのタブが有効かがわからない状態です。こちらを見直してみましょう。

[![Image from Gyazo](https://i.gyazo.com/3067e36e666b52ed644b8db900c6296b.png)](https://gyazo.com/3067e36e666b52ed644b8db900c6296b)

- その際、`is()`より `routeIs()`の方がスマートに書けるので、是非お試しくださいね！

https://shiro-changelife.com/laravel-url-judge/

2023-12-08 13:03 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +        ];
- Bladeの方で投稿の一覧が表示されていないようですが、こちらは鈴木さんが作った分をパーツとして使う予定なので未着手ということでしょうか？投稿が表示される状態になって、ページネーションまでを含む動作確認お願いしますね！

2023-12-08 13:03 UTC, Osk0830 commented on routes/web.php
> +        Route::get('{id}', 'UsersController@show')->name('user.show');
- デモサイトでは、非ログイン時でも、ユーザー詳細画面見れないでしょうか？

2023-12-08 14:28 UTC, tatsuhirohayashi commented on routes/web.php
> +        Route::get('{id}', 'UsersController@show')->name('user.show');
非ログインでもユーザー詳細見れるので、そのようにルーティングを変更しました。

2023-12-08 14:29 UTC, tatsuhirohayashi commented on resources/views/users/show.blade.php
> +                <li class="nav-item"><a href="{{route('user.show', $user->id)}}" class="nav-link {{ Request::is() ? 'active' : '' }}">タイムライン</a></li>
routeIs()を使って書きました。

2023-12-08 15:00 UTC, tatsuhirohayashi commented on app/Http/Controllers/UsersController.php
> +        ];
こちら仮に投稿一覧ページを作って、ユーザー詳細画面にincludeさせる形で表示させました。

2023-12-09 23:32 UTC, Osk0830 requested changes
お疲れ様でした！
前回の指摘事項は概ね修正できていると思います！

ただ、少しだけ修正が必要な箇所がありますので、
確認よろしくお願いします！

また、現状のシーディングファイルのデータでは、
投稿日の表示やページネーションなどの挙動が確認できないと思いますが、
この部分の動作確認は完了してますでしょうか？
もし完了している場合は、どのように動作確認を行なったという内容も、
コメントに記載するようにしていただければと思います！

よろしくお願いします。

2023-12-09 23:32 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                <img class="mr-2 rounded-circle" src="{{ Gravatar::src($user->email, 55) }}" alt="ユーザのアバター画像">
- 投稿に関するリストなので、`$user->`のようにすると、このパーツを埋め込む場所によっては値が取得できないことがある可能性があります。他の場所と同じく、投稿を起点にユーザーのデータを取得するようにしてください。

2023-12-09 23:32 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                    <p class="text-muted">{{$post->user->created_at}}</p>
- ユーザーの初回登録日を表示するのはおかしくないでしょうか？投稿の作成日が表示されるようにしてください。

2023-12-09 23:32 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +        @include('posts.posts' , ['user' =>$user, 'post' => $user->posts])
- こちら、インデントを一つ下げるのが正しいと思います！
- また、`=>`の前後に半角空白が入っていない箇所がありますので、しっかり揃えてみてくださいね。

2023-12-10 05:15 UTC, tatsuhirohayashi commented on resources/views/posts/posts.blade.php
> +                    <p class="text-muted">{{$post->user->created_at}}</p>
created_atではなく、updated_atに変更しました。

2023-12-10 05:16 UTC, tatsuhirohayashi commented on resources/views/posts/posts.blade.php
> +                <img class="mr-2 rounded-circle" src="{{ Gravatar::src($user->email, 55) }}" alt="ユーザのアバター画像">
$post->user->emailに変更しました。

2023-12-10 05:16 UTC, tatsuhirohayashi commented on resources/views/users/show.blade.php
> +        @include('posts.posts' , ['user' =>$user, 'post' => $user->posts])
修正をしました。

2023-12-11 06:37 UTC, Osk0830 requested changes
動作確認までお疲れ様でした！

少しだけおかしな部分がありコメントしましたので、
確認よろしくお願いします！

2023-12-11 06:37 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                    <p class="text-muted">{{$post->user->updated_at}}</p>
- こちら、前回の指摘でもお伝えしたように、ユーザーに関するひづけではなく、「当該の投稿がいつ作成されたか」の情報を表示するようにしてください。

2023-12-11 06:37 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +            @include('posts.posts' , ['user' => $user, 'post' => $user->posts])
- コントローラーから、`$posts`として投稿データを渡してきているので、それをそのまま渡すようにしましょう。`$user->posts`だと再度取得していることになると思います。ただ、仮にここで渡しているデータを部品で使うようになっていると、本来だとページネーションが機能しないと思いますが、今は機能しているのではないでしょうか？それは、部品の方で、`$post`という変数に入っている値を利用していないからです。（ということは、そもそもここで渡す必要がない、ということにもなります）
- また、部品の方で、`$user`を利用している箇所、ありますでしょうか？
- 変数の中身が複数の値を含んでいる配列である場合、変数名もわかりやすく複数形にしましょう（例：`$post`ではなく、`$posts`）

2023-12-11 08:16 UTC, tatsuhirohayashi commented on resources/views/posts/posts.blade.php
> +                    <p class="text-muted">{{$post->user->updated_at}}</p>
具体的にどうすればいいでしょうか？

2023-12-11 08:23 UTC, tatsuhirohayashi commented on resources/views/users/show.blade.php
> +            @include('posts.posts' , ['user' => $user, 'post' => $user->posts])
ごめんなさい、言っている意味が理解できません。
とりあえず理解できる範囲で修正しました。

2023-12-11 13:13 UTC, tatsuhirohayashi commented on resources/views/posts/posts.blade.php
> +                    <p class="text-muted">{{$post->user->updated_at}}</p>
$post->updated_atにしました。

2023-12-12 06:28 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                    <p class="text-muted">{{$post->user->updated_at}}</p>
@tatsuhirohayashi 
いい感じに修正できてきていると思います。ただ、`updated_at`ですとデモサイトの要件とは異なるようです。
下記試しに、テスト1を投稿→テスト2を投稿→最初の投稿であるテスト1を編集・更新してみたもものですが、テスト1の日付は新規投稿時のものから変化がありません。どの値を表示させる必要があるか再度検討してみてください。

[![Image from Gyazo](https://i.gyazo.com/bb278eeb5710badb218dd77c4243b08b.png)](https://gyazo.com/bb278eeb5710badb218dd77c4243b08b)

2023-12-12 06:33 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +            @include('posts.posts' , ['user' => $user, 'post' => $user->posts])
@tatsuhirohayashi 
分からない部分がある場合、「理解できない」の一言ではなく、どこは理解できるがどの部分は理解できないというところを明確にしながら、Slackで質問するようにしてください。

修正いただいた点は、一つは間違っていませんが、なぜこのようにすべきなのかが分からないなどありましたら、その点もご質問ください。

また、`$user`を渡していますが、部品の方でこの変数を利用している箇所はないようです。どの値がなぜ必要で、なぜこのような形式でこう書くのかを一つ一つ検討・理解していきましょう。

[![Image from Gyazo](https://i.gyazo.com/9e3301b2f6073711339faf4347f77b91.png)](https://gyazo.com/9e3301b2f6073711339faf4347f77b91)

2023-12-12 06:39 UTC, tatsuhirohayashi commented on resources/views/posts/posts.blade.php
> +                    <p class="text-muted">{{$post->user->updated_at}}</p>
$post->createdに変更しました。

2023-12-12 06:43 UTC, tatsuhirohayashi commented on resources/views/users/show.blade.php
> +            @include('posts.posts' , ['user' => $user, 'post' => $user->posts])
わかりました。

2023-12-12 06:50 UTC, tatsuhirohayashi commented on resources/views/users/show.blade.php
> +            @include('posts.posts' , ['user' => $user, 'post' => $user->posts])
「$user->postsだと再度取得していることになると思います。ただ、仮にここで渡しているデータを部品で使うようになっていると、本来だとページネーションが機能しないと思いますが、今は機能しているのではないでしょうか？」
ここの部分の意味がわかりません。

2023-12-13 23:55 UTC, Osk0830 approved these changes
お疲れ様でした！
こちら現状の修正で問題なさそうなのでマージしますね！

理解できない箇所とのコメントをくださった点については、
明日のMTGで一緒に動かしながら確認してみましょう！

2023-12-13 23:55 UTC, merged