フォロー機能（林）
yukihiroLaravel/joint_develop pull request #849
Opened 2023-12-16 11:04 UTC by tatsuhirohayashi

## issue
・Closes #822  

## 概要
・フォロー機能

## 動作確認
・ログイン後、自分以外のユーザー詳細を開く。
・フォローするボタンを押してAdminerでもデータが反映されていることを確認する。
・フォローを外すボタンを押してAdminerからデータが消えていることを確認する。

・自分のユーザー詳細画面を開き、フォローをするボタンが出ていないことを確認する。

## 考慮して欲しいこと
特になし

## 確認して欲しいこと
特になし

2023-12-17 01:52 UTC, Osk0830 requested changes
コミットの整理含め、お疲れ様でした！
全体的にとても良くできていると思います。

少し修正が必要な箇所がありコメントしましたので、
よろしくお願いします！

2023-12-17 01:52 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        return view('welcome', [ 'posts' => $posts,]);
- こちらは今回のタスクとは関係ない部分なので、変更せずに、一旦元に戻しておいてください（鈴木さんが作業中のタスクのため）

2023-12-17 01:52 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +    @include('posts.posts', ['posts' => $posts])
- こちらも変更せずに、一旦元に戻しておいてください（鈴木さんが作業中のタスクのため）

2023-12-17 01:52 UTC, Osk0830 commented on database/migrations/2023_12_16_195142_create_follows_table.php
> +}
- 動作確認しやすいよう、こちらに関するシーディングファイルも作成し、いくつかデータが入っているようにしておいてください。
- さらにそれを`DatabaseSeeder.php`に登録して、シーディングを一括で実行できるようにしておいてください。

2023-12-17 01:52 UTC, Osk0830 commented on app/User.php
> +    }
- 現状ですと、ログインしているユーザーが自分自身をフォローできてしまいますが、挙動としてはおかしいので、自分自身はフォローできないようにしてください。（tinkerで動作確認してみてください）

[![Image from Gyazo](https://i.gyazo.com/933aa77b3a7a7367f268b665b79e157a.png)](https://gyazo.com/933aa77b3a7a7367f268b665b79e157a)

[![Image from Gyazo](https://i.gyazo.com/8516428e07acf98361faf12ac7945852.png)](https://gyazo.com/8516428e07acf98361faf12ac7945852)

2023-12-17 01:52 UTC, Osk0830 commented on app/User.php
> +    }
- こちらも念のため、`follow()`メソッドと同じく、自分自身に対する操作はNGとなるようにしておきましょう。

2023-12-17 01:52 UTC, Osk0830 commented on app/User.php
> +    }
- こちらはリレーションメソッドなので、同じリレーションメソッドである `following()`と近い位置に移しておきましょう。51行目あたりですかね。コードの可読性を高めるためです。

2023-12-17 01:52 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +                        <div class="text-center">@include('follow.follow_button')</div>
- この辺、インデントが少しおかしくなっているので、インデントを整えてください。

[![Image from Gyazo](https://i.gyazo.com/d33b61466369654f6f647b2f25af8d9a.png)](https://gyazo.com/d33b61466369654f6f647b2f25af8d9a)

- 「ユーザー情報の編集」ボタンに比べて、アバター画像とくっつきすぎていて窮屈に見えます。「ユーザー情報の編集」ボタンを参考に、上にマージンを入れるのに必要なBootstrap4のクラスを追加してください。

[![Image from Gyazo](https://i.gyazo.com/f501b91f55e78fe2b567e452bd32c8d4.png)](https://gyazo.com/f501b91f55e78fe2b567e452bd32c8d4)

[![Image from Gyazo](https://i.gyazo.com/dd10d5f7e9c865a1d9294a1bef48e507.png)](https://gyazo.com/dd10d5f7e9c865a1d9294a1bef48e507)

2023-12-17 04:18 UTC, tatsuhirohayashi commented on database/migrations/2023_12_16_195142_create_follows_table.php
> +}
いくつかデータを入れて、シーディングを一括で実行しました。

2023-12-17 04:21 UTC, tatsuhirohayashi commented on app/User.php
> +    }
コードを近い位置に移しました。

2023-12-17 04:30 UTC, tatsuhirohayashi commented on resources/views/users/show.blade.php
> +                        <div class="text-center">@include('follow.follow_button')</div>
インデントの位置を整えて、ボタンの位置も調整しました。

2023-12-17 04:39 UTC, tatsuhirohayashi commented on app/Http/Controllers/PostsController.php
> +        return view('welcome', [ 'posts' => $posts,]);
もとに戻しました。

2023-12-17 04:39 UTC, tatsuhirohayashi commented on resources/views/welcome.blade.php
> +    @include('posts.posts', ['posts' => $posts])
もとに戻しました。

2023-12-17 04:57 UTC, tatsuhirohayashi commented on app/User.php
> +    }
自分自身がフォローできないようにしました。

2023-12-17 04:57 UTC, tatsuhirohayashi commented on app/User.php
> +    }
自分自身がフォローできないようにしました。

2023-12-17 05:07 UTC, tatsuhirohayashi commented on app/User.php
> +    }
ただ、tinkerで動作確認ができていません。

2023-12-19 08:01 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらしっかり修正できているようなのでマージしますね！

2023-12-19 08:01 UTC, merged