#69 投稿編集画面・更新(竹渕)
yukihiroLaravel/joint_develop pull request #85
Opened 2022-11-05 06:22 UTC by bucchi-orange

2022-11-07 05:15 UTC, Osk0830 requested changes
お疲れ様です！
遅くなってすみません！

全体的には良くできていると思います。
いくつかコメントを残しましたのでご確認ください！

2022-11-07 05:15 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +    }
- 編集画面に遷移するためのボタンは、本人の投稿である場合しか出ていないので、ぱっと見大丈夫そうに見えますが、今の状態ですと、`http://localhost:8080/posts/edit/10`のように存在するidを入力すると、ログインさえしていれば他人の編集画面にもアクセスできてしまいます。ログインしている人の投稿である場合に限り、編集画面に遷移でき、そうでない場合はアクセスできないように工夫してみてください。

2022-11-07 05:15 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        return redirect(route('home'));
- こちらも、念のため、編集画面同様の判定を挟んだ方がいいですね。
- あと、58行目のように、内容が更新される必要がないものは、あえて再度書き直す必要はなさそうですね。

2022-11-07 05:15 UTC, Osk0830 commented on resources/views/posts/edit.blade.php
> +        </div>
- `old()`メソッドの使い方はこれでOKです！

2022-11-07 08:30 UTC, bucchi-orange commented on app/Http/Controllers/PostsController.php
> +    }
分かりました！
工夫してみます

2022-11-07 08:31 UTC, bucchi-orange commented on app/Http/Controllers/PostsController.php
> +        return redirect(route('home'));
こちらも変更いたします

2022-11-07 08:31 UTC, bucchi-orange commented on resources/views/posts/edit.blade.php
> +        </div>
分かりました
ありがとうございます！

2022-11-08 20:07 UTC, bucchi-orange commented
ご指摘の点修正いたしました
再レビューをお願いいたします

## 修正点
- PostsController の showEdit と update メソッドに if 文を追加し、ほかのユーザーの編集画面にアクセスできないようにしました。
- エラーの際は /Session でエラーメッセージを表示し、ホーム画面に戻るようにしました。

## 確認してほしい点
- /Session の使い方がこれで良いか
-  /Session 以外でこの機能を実装する方法があるか。
以上を教えていただきたいです。

2022-11-09 02:24 UTC, Osk0830 approved these changes
お疲れ様です！
こちらOKなのでマージしますね〜！

2022-11-09 02:24 UTC, merged