#826　投稿新規作成
yukihiroLaravel/joint_develop pull request #853
Opened 2023-12-21 13:57 UTC by takahito717

## issue
- Closes #826 

## 概要
- 投稿新規作成機能の実装

## 動作確認手順
- ログインしてから投稿し、トップページに投稿が表示されるか確認

## 考慮してほしいこと
特になし

## 確認してほしいこと
特になし

2023-12-23 06:14 UTC, Osk0830 requested changes
お疲れ様でした！
大枠はできていると思います！

修正が必要な箇所がいくつかありコメントしましたので、
確認よろしくお願いします！

2023-12-23 06:14 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +
- トップページは最初から表示されるようになっているので、こちらのアクションは不要ではないでしょうか？

2023-12-23 06:14 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        $post->save();
- `Auth::user()`はログインユーザーに関する情報をすべて取得してくるためのものですが、ここでは `id`しか使わないので、`Auth::id()`で idだけ取得する感じの方がいいと思います。それですと、45行目のようにいちいち変数に入れず、49行目の右辺に `Auth::id()`を記述する感じでOKだと思います。

2023-12-23 06:14 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +            <form method="POST" action="/posts" class="d-inline-block w-75">
- `action`の部分はURLを直接していせず、`route()`メソッドを用いてルーティング名で指定する形にしましょう。今後URLに変更が生じた場合などにも問題なく対応できるよにするためにも、URLの直書きは避けましょう。

2023-12-23 06:14 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +                    <textarea class="form-control" name="content" rows="2"></textarea>
- ユーザビリティの観点から、バリデーションで弾かれた際に、前に入力していた内容が表示されるようにしてください。

2023-12-23 06:14 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +                    @enderror
- エラーメッセージを表示させるための部品はすでにチームのブランチに用意されているようですので、ここではそれを読み込む形で活用しましょう。

2023-12-23 06:14 UTC, Osk0830 commented on routes/web.php
> +Route::get('/posts/create', 'PostsController@create');
- こちらのルーティングはどこで使うのでしょうか？

2023-12-23 06:14 UTC, Osk0830 commented on routes/web.php
> +Route::post('/posts', 'PostsController@store');
- ルーティングに名前をつけ、`route()`メソッドなどで利用できるようにしましょう。

2023-12-25 12:52 UTC, takahito717 commented on app/Http/Controllers/PostsController.php
> +        $post->save();
わかりました。修正します。

2023-12-25 12:53 UTC, takahito717 commented on routes/web.php
> +Route::get('/posts/create', 'PostsController@create');
このルーティングは消し忘れです。エラーが出なかったため見落としていました。

2023-12-25 12:53 UTC, takahito717 commented on app/Http/Controllers/PostsController.php
> +
修正します。

2023-12-25 12:54 UTC, takahito717 commented on routes/web.php
> +Route::post('/posts', 'PostsController@store');
わかりました。修正します。

2023-12-25 14:00 UTC, takahito717 commented on resources/views/welcome.blade.php
> +            <form method="POST" action="/posts" class="d-inline-block w-75">
/postsを名前を付けたRoute::post('/posts', 'PostsController@store')に変更して指定します。

2023-12-25 14:21 UTC, takahito717 commented on resources/views/welcome.blade.php
> +                    @enderror
@include('commons.error_messages')に変更します。

2023-12-25 15:33 UTC, takahito717 commented on resources/views/welcome.blade.php
> +                    <textarea class="form-control" name="content" rows="2"></textarea>
old関数を使用して入力した内容が保持されるように変更しました。

2023-12-27 12:10 UTC, Osk0830 requested changes
修正お疲れ様でした！
機能的にはほぼ問題なくできてきたと思います。
少しだけ修正お願いします。

①
「content」と表示されるとユーザーに伝わりにくいので、
「本文」や「投稿」などと表示されるようにしてください。

[![Image from Gyazo](https://i.gyazo.com/63b4d0abd9c555a422fb4cd0b0a88d1f.png)](https://gyazo.com/63b4d0abd9c555a422fb4cd0b0a88d1f)

②
テキストは左寄せの方が良さそうです。
こちらデモサイトと同じような表示になるようにしてください。

[![Image from Gyazo](https://i.gyazo.com/f4dc22411b83d68769d98e05be151c69.png)](https://gyazo.com/f4dc22411b83d68769d98e05be151c69)

2023-12-30 02:21 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらしっかり修正できているのでマージしますね！

2023-12-30 02:21 UTC, merged