投稿の詳細検索（はいしま）
yukihiroLaravel/joint_develop pull request #855
Opened 2023-12-24 15:30 UTC by hatschi2023

## issue
- Closes #854
## 概要
- 投稿の詳細検索

## 動作確認手順
①ヘッダーの検索バーから、投稿の簡易検索（キーワードで部分一致検索）ができることを確認
②詳細検索の条件に使用するため、adminerから投稿データの作成日（postsテーブルのcreated_at）を適当に入力する
③ヘッダーの詳細検索リンクから詳細検索画面に遷移し、複数条件での検索ができることを確認

## 考慮して欲しいこと
・簡易検索バーを本文中からヘッダーに移動しました。
・今回新たに詳細検索用にSearchContorollerを作成し、処理を記載しましたが、
前回はPostsController のindexメソッドに、投稿の一覧表示の処理と共に、簡易検索処理を記載しました。
検索処理がそれぞれのコントローラにある形になりますが、問題ないでしょうか。

2023-12-31 03:37 UTC, yukihiroLaravel requested changes
コメントしましたので、お願いいたします！
https://www.loom.com/share/afe3bfeef85a48e3b7824249c2a2cc5d?sid=4f4e0d63-33a0-4bcb-8179-51e8161e9a9c

2023-12-31 03:37 UTC, yukihiroLaravel commented on routes/web.php
> +
ここに２行も空行不要かと思いました！

2023-12-31 03:37 UTC, yukihiroLaravel commented on app/Providers/AppServiceProvider.php
> +        View::share('searchContent');
不要かと思います

2023-12-31 08:15 UTC, hatschi2023 commented on routes/web.php
> +
削除しました！

2023-12-31 08:15 UTC, hatschi2023 commented on app/Providers/AppServiceProvider.php
> +        View::share('searchContent');
削除しました！

2023-12-31 08:21 UTC, hatschi2023 commented on resources/views/search/simple_search.blade.php
>          <input type="submit" value="検索">
ご指摘いただいたAppServiseProviderの記載を削除すると、ユーザー詳細画面に遷移する際にエラーが出てしまうため、$searchContentがNullだった場合のデフォルト値を追記しました。

2024-01-01 11:27 UTC, yukihiroLaravel approved these changes
OKですのでマージしました！
大変な部分もありましたがお疲れ様でした☺️

2024-01-01 11:27 UTC, merged