投稿への画像添付機能（林）
yukihiroLaravel/joint_develop pull request #857
Opened 2024-01-04 11:59 UTC by tatsuhirohayashi

## issue
・closes

## 概要
投稿への画像添付機能

## 動作確認手順

## 考慮して欲しいこと
まだエラーが解決出来ず、未完成であること

## 確認してほしいこと
以下のサイトを参考にしました。
https://www.kamome-susume.com/laravel-img-upload/

2024-01-10 03:59 UTC, Osk0830 requested changes
お疲れ様でした！
機能的には大枠でできていると思います！

いくつか修正が必要な箇所がありコメントしましたので、
確認よろしくお願いします！

2024-01-10 03:59 UTC, Osk0830 commented on app/Post.php
> +}
- `$table`と`$fillable`は共にクラスのプロパティなので、17行目の `{`と23行目の`}`は不要だと思います。
- 慣例的にプロパティはメソッドより上に書きましょう。
- 追記した `$table`プロパティですが、Laravelのデフォルトの設定で、単数系のモデル名（ここでは `Post`）に対応する複数形のテーブル名（ここでは `posts`）が存在した場合、自動的にモデルとテーブルが紐づくようになっていますので、今回のような場合、`$table`プロパティの追記自体が不要です。

2024-01-10 03:59 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        if (isset($img)) {
- 画像ファイルの種類を限定したり、ファイルの容量を制限するバリデーションを挟まないと予期せぬエラーが起こります。必要なバリデーションを追加してください。

2024-01-10 03:59 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +
- この部分、インデントがおかしくなっているようです。

2024-01-10 03:59 UTC, Osk0830 commented on resources/views/posts/index.blade.php
> +                    <img src="{{ Storage::url($post->img_path) }}" width="25%">
- 画像は必須ではない仕様となっているため、この `<img>`要素は投稿に紐づく画像が存在する時だけ生成されるようにしましょう。

[![Image from Gyazo](https://i.gyazo.com/53afc01c26fe90653292579df9bc9241.png)](https://gyazo.com/53afc01c26fe90653292579df9bc9241)

2024-01-10 03:59 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +                    <input type="file" name="img_path">
- ユーザビリティを考えて、できれば画像ファイル（pngやjpgなど）だけ選択できるように制限しましょう。

2024-01-10 03:59 UTC, Osk0830 commented on resources/views/welcome.blade.php
>                          <button type="submit" class="btn btn-primary">投稿する</button>
- 見た目的な問題として、下記矢印で示した箇所あたりは上下間の余白が少しあった方が良さそうです。

[![Image from Gyazo](https://i.gyazo.com/53c209fa72bbbad253eebfaf199e7ebb.png)](https://gyazo.com/53c209fa72bbbad253eebfaf199e7ebb)

2024-01-10 03:59 UTC, Osk0830 commented on routes/web.php
> +
- あまり不要な空行は入れないようにしましょう。

2024-01-10 04:41 UTC, tatsuhirohayashi commented on app/Post.php
> +}
修正しました。ただ、プロパティーをメソッドより上に書くとエラーが発生してしまうため、そこだけは直せていません。

2024-01-10 04:45 UTC, tatsuhirohayashi commented on routes/web.php
> +
わかりました。

2024-01-10 04:51 UTC, tatsuhirohayashi commented on resources/views/welcome.blade.php
>                          <button type="submit" class="btn btn-primary">投稿する</button>
修正しました。

2024-01-10 05:36 UTC, tatsuhirohayashi commented on resources/views/posts/index.blade.php
> +                    <img src="{{ Storage::url($post->img_path) }}" width="25%">
修正しました。

2024-01-10 05:44 UTC, tatsuhirohayashi commented on resources/views/welcome.blade.php
> +                    <input type="file" name="img_path">
制限しました。

2024-01-10 05:46 UTC, tatsuhirohayashi commented on app/Http/Controllers/PostsController.php
> +        if (isset($img)) {
必要なバリデーションを追加しました。

2024-01-10 05:46 UTC, tatsuhirohayashi commented on app/Http/Controllers/PostsController.php
> +
修正しました。

2024-01-10 06:35 UTC, Osk0830 reviewed
修正確認しました。
概ねOKですが、まだ少し修正が必要な箇所がありますので、
確認よろしくお願いします。

2024-01-10 06:35 UTC, Osk0830 commented on app/Post.php
> +];
- こちら、`protected`を付与する必要がありますね。その上で、11行目の次に移動させましょう。

2024-01-10 06:35 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +            'img_path' => '|image|mimes:png,jpg|max:2048',
- `image`の前の`|`は不要ではないでしょうか？
- バリデーションで弾かれた際のエラーメッセージについて調整が必要そうです。

①img_pathというのはユーザーからしたら何のことか分かりません。
②ファイルの種類の問題なのか、ファイルサイズの問題なのかが分かるようにしてあげないと、ユーザーは何が問題なのか特定できず困ってしまいます。

[![Image from Gyazo](https://i.gyazo.com/39285d1df7b81adbef8c0ff506885407.png)](https://gyazo.com/39285d1df7b81adbef8c0ff506885407)

2024-01-10 06:35 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +                        <input type="file" name="img_path">
- こちら、選択できるファイルを制限したとコメントにありましたが、現状どのような種類のファイルでも選択できてしまいます。

[![Image from Gyazo](https://i.gyazo.com/78e6e75aae03770995f1b4f6fceeca01.png)](https://gyazo.com/78e6e75aae03770995f1b4f6fceeca01)

2024-01-11 00:38 UTC, Osk0830 requested changes
お疲れ様でした！
だいぶ仕上がってきましたね！

あともう一歩まで来ていると思いますので、
確認よろしくお願いします！

2024-01-11 00:38 UTC, Osk0830 commented on app/Http/Requests/PostRequest.php
> +            'img_path' => '画像',
- せっかくこのフォームリクエストのファイルが作成されているので、`store()`メソッドでこちらを使うようにしましょう。
- また、前回のレビューで書いたように、ファイルの種類の問題なのか容量の問題なのかが分かるようにバリデーションメッセージをもう少し調整してみてください。

2024-01-11 00:38 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
>          ]);
- フォームリクエストを使うようにすれば、このバリデーション自体は不要になると思います。

2024-01-11 00:38 UTC, Osk0830 commented on app/Post.php
> +];
- この部分インデントがおかしくなっているので調整お願いします。

2024-01-11 00:38 UTC, Osk0830 commented on resources/lang/ja/validation.php
> +        'img_path' => '画像'
- フォームリクエストを使うようになればこの部分への追記自体は本来不要ですが、置いておいてもいいですし、状況見て判断してください。

2024-01-11 11:06 UTC, Osk0830 approved these changes
お疲れ様でした！
メッセージの出し分けの件、なぜか僕の環境では再現できないですが、
他に問題なさそうなのでマージしますね！
マージ後にチーム内で確認よろしくお願いします！

2024-01-11 11:06 UTC, merged