投稿削除機能(とくしげ)
yukihiroLaravel/joint_develop pull request #86
Opened 2022-11-10 12:43 UTC by tokushige-s

## issue
- 投稿削除機能

## 概要
- 投稿削除機能の実装

## 動作確認
- トップページ、ユーザ詳細ページでの削除実行

## 確認してほしいこと
特にありません

2022-11-10 13:50 UTC, yukihiroLaravel requested changes
素晴らしいですね！
１点以外いい感じだと思います！
コメントしましたので修正願います☺️

2022-11-10 13:50 UTC, yukihiroLaravel commented on routes/web.php
> +Route::delete('{id}', 'PostsController@destroy')->name('post.delete');
こちら、ログインユーザしか削除機能は使えてはイケないので
`Route::group(['middleware' => 'auth'], function () {`
の中に入れないといけないですね！！

2022-11-10 14:51 UTC, tokushige-s commented on routes/web.php
> +Route::delete('{id}', 'PostsController@destroy')->name('post.delete');
ありがとうございます。
修正します。

2022-11-11 02:49 UTC, yukihiroLaravel approved these changes
確認できました！
OKですのでマージしました☺️
引き続きがんばりましょう✨

2022-11-11 02:49 UTC, merged

2022-11-11 22:29 UTC, tokushige-s commented
ありがとうございました。
頑張ります。