#862　返信機能（鈴木）
yukihiroLaravel/joint_develop pull request #864
Opened 2024-01-17 16:00 UTC by takahito717

## issue
- Closes #862 

## 概要
- Replyテーブル・シーダーの追加の追加
- 返信送信・削除機能の実装

## 動作確認手順
- マイグレーション・シーダーを実行し、Replyテーブルが作成され返信が追加されているか確認する
- 各投稿の下に返信が表示されているか確認する。返信は
「”ユーザー名”さんの返信: これはi個目の返信です。」となっている。
- ログイン時に投稿の下に返信フォームが表示されているか確認する
- 入力せずに送信、１４０文字以上の文章を送信するとバリデーションエラーメッセージが表示される
- 返信を送信すると投稿の下に「”自分のアカウント名”さんの返信: 返信内容。」、灰色の文字で投稿日時、削除ボタンが表示される。削除ボタンは自分の返信にのみ表示される。
- 削除ボタンを押すと投稿が削除され、「返信を削除しました！」が表示される。

## 考慮してほしいこと
特になし

## 確認してほしいこと
特になし

2024-01-19 11:07 UTC, Osk0830 requested changes, later dismissed
お疲れ様でした！
機能的には動くように書けていると思います。
ただ、不要な記述があったり、意味が伝わりにくかったり、全体的な統一性が取れていないなど、見直してみるべき点があるようです。
コメントしましたので、確認よろしくお願いします！

2024-01-19 11:07 UTC, Osk0830 commented on app/Http/Controllers/RepliesController.php
> +    }
- 他のコントローラーやルーティングとの兼ね合いを考えた際、このミドルウェアはルーティングの段階で挟むようにした方が統一性があって分かりやすい気もしますが、いかがでしょう？

2024-01-19 11:07 UTC, Osk0830 commented on app/Http/Controllers/RepliesController.php
> +    }
- ここで`article_id`としているのは、投稿のidのようですね。そうなると、他の機能では全て`post`と称しているので、`article`ではなく`post`で統一する方が良さそうですね。今回のタスク全体で一度変数名を見直してみてください。
- `post (article)`のidがいくらパラメータから渡ってくるとしても、この値が本当に `posts`テーブルに存在する値なのかどうかについてバリデーションでチェックする必要がありそうです。仮に、存在しない値であった場合に、データベースに登録しようとした際にエラーが発生してしまいます、
- `reply`の内容を`reply`としてしまうと、名前がごちゃごちゃになって分かりにくそうな感じがします。replyの内容自体は、例えば `content`のようにしておくのが分かりやすそうです。カラム名を一度検討してみてください。

2024-01-19 11:07 UTC, Osk0830 commented on app/Reply.php
> +    }
- ここだけ`App\User`のような記述にすると、他と統一性がなくなります。記述方法を統一しましょう。

2024-01-19 11:07 UTC, Osk0830 commented on app/User.php
> +use Illuminate\Database\Eloquent\Relations\HasMany;
- こちら必要でしょうか？

2024-01-19 11:07 UTC, Osk0830 commented on routes/web.php
> +    Route::get('/{post}', 'RepliesController@show')->name('showReply');
- これは必要でしょうか？

2024-01-19 11:07 UTC, Osk0830 commented on app/Http/Controllers/RepliesController.php
> +    }
- こちら対応するbladeもないようですが、そもそも現実装で必要でしょうか？

2024-02-14 14:26 UTC, hatschi2023 approved these changes

2024-02-14 14:28 UTC, hatschi2023 approved these changes

2024-02-14 14:34 UTC, hatschi2023 commented
動作確認しました！

2024-02-14 23:56 UTC, yukihiroLaravel approved these changes

2024-02-15 01:42 UTC, merged