フラッシュメッセージ(とくしげ)
yukihiroLaravel/joint_develop pull request #88
Opened 2022-11-15 13:27 UTC by tokushige-s

## issue
- フラッシュメッセージ

## 概要
- フラッシュメッセージの作成

## 動作確認
- 投稿時に「投稿しました！」と表示されることを確認

## 確認してほしいこと
- 特にありません

2022-11-16 01:46 UTC, yukihiroLaravel requested changes
いいですね！
1点コメントしましたのでその点修正願います🙇‍♂️

2022-11-16 01:46 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +        <div class="alert alert-success text-center">
こちら今下記画像の通り、
topic post のタイトル幅にフラッシュメッセージ幅が合っていますが
できたら、投稿入力欄の幅に合わせた方が綺麗かと思います！

やってみて、やり方わからなければ聞いて下さい！
<img width="1195" alt="スクリーンショット 2022-11-16 10 43 32" src="https://user-images.githubusercontent.com/93365035/202062990-f59056b7-377d-4f27-9363-9795f19caaae.png">

2022-11-16 07:40 UTC, tokushige-s commented on resources/views/welcome.blade.php
> +        <div class="alert alert-success text-center">
ありがとうございます！
修正やってみます。

2022-11-17 00:49 UTC, tokushige-s commented
## 修正内容
- フラッシュメッセージの表示を投稿入力欄の幅に合わせる。

2022-11-17 01:07 UTC, yukihiroLaravel approved these changes
完璧です！
マージしました☺️
ご確認ください！

2022-11-17 01:07 UTC, merged

2022-11-17 02:14 UTC, tokushige-s commented
ありがとうございました！