フラッシュメッセージ、削除、編集(とくしげ)
yukihiroLaravel/joint_develop pull request #89
Opened 2022-11-17 04:12 UTC by tokushige-s

## issue
- フラッシュメッセージ、削除、編集

## 概要
- 投稿削除及び投稿編集時のフラッシュメッセージの表示

## 動作確認
- 投稿削除した際トップページとユーザページでのフラッシュメッセージの表示を確認
- 投稿編集した際トップページにフラッシュメッセージの表示を確認

## 確認してほしいこと
- フラッシュメッセージの色についてですがsuccessとdangerで色が変わるようですが他の色もありますか？

2022-11-17 04:43 UTC, yukihiroLaravel requested changes
確認しました！いいですね✨

ブートスラップの色含めて、コメントしました。
少し修正してみて下さい😆

2022-11-17 04:43 UTC, yukihiroLaravel commented on resources/views/posts/create.blade.php
> +    @else
この @end はなくても動くと思います！

2022-11-17 04:43 UTC, yukihiroLaravel commented on resources/views/posts/create.blade.php
> +        <div class="alert alert-success text-center">
こちらの色はdangerの方が良くないでしょうか？

カラーについては、
primary　などいろいろカラーがあるの見てみて下さい。

https://getbootstrap.jp/docs/5.0/utilities/colors/

2022-11-17 06:24 UTC, tokushige-s commented on resources/views/posts/create.blade.php
> +        <div class="alert alert-success text-center">
ありがとうございます！
修正します。

2022-11-17 06:27 UTC, tokushige-s commented on resources/views/posts/create.blade.php
> +    @else
ここお聞きしようと思ったのですが
@elseがあってもなくてもエラーが出なかったので
どうなんだろうと思っていたのですが
@elseだけでいいんですね。
ありがとうございます！
修正します。

2022-11-17 09:13 UTC, tokushige-s commented
## 修正内容
- @elseの削除
- 投稿削除の際のフラッシュメッセージのカラー変更

2022-11-18 12:51 UTC, yukihiroLaravel approved these changes
OKです！

マージしました☺️
引き続きがんばりましょう🔥

2022-11-18 12:51 UTC, yukihiroLaravel commented on resources/views/posts/create.blade.php
> +    @else
すみません、書き間違えてました。
@else を削除して
@endif
だけでOKということでした！

2022-11-18 12:51 UTC, merged