#879 ユーザー新規登録機能（あべ）
yukihiroLaravel/joint_develop pull request #923
Opened 2024-01-30 00:55 UTC by abeai0

## issue
- Closes #879

## 概要
- ユーザー新規登録機能

## 動作確認手順
- http://localhost:8080/signup へアクセス、名前・メールアドレス・パスワードを入力して新規登録ボタンを押す
- http://localhost:8088 へアクセス、ユーザーが登録されていることを確認

## 考慮して欲しいこと
- トップページ未実装のため、register.blade.phpの1,2,41行目はコメントアウトしないと表示されないこと
- layouts.app未実装のためcssがあたっていないこと

## 確認してほしいこと

2024-02-01 13:07 UTC, Osk0830 requested changes
お疲れ様でした！
概ねよく書けていると思います！
少しだけコメントしましたので、
確認よろしくお願いします！

2024-02-01 13:07 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +    </h1>
- 非常に細かい話になりますが、`<i>`要素もテキストも共にインラインの要素で、インラインの要素を列挙する際にHTML内に改行を入れてしまうと、ブラウザが半角空白に変換してしまい、予期せぬ空白ができてしまうことがあります。なのでHTML内で改行を挟まないようにしましょう。

2024-02-01 13:07 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +                    value="{{ old('password') }}">
- パスワードは再度入力するようにした方がいいですね。

2024-02-01 13:07 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +                    value="{{ old('password_confirmation') }}">
- こちらも上記同様です。

2024-02-01 13:07 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +            @csrf
- バリデーションに弾かれた際のエラーメッセージはどこに表示されるのでしょうか？

2024-02-09 01:08 UTC, abeai0 commented on resources/views/auth/register.blade.php
> +            @csrf
- 「新規登録」の下に表示されるように修正しましたのでご確認お願いします。

2024-02-09 01:08 UTC, abeai0 commented on resources/views/auth/register.blade.php
> +                    value="{{ old('password_confirmation') }}">
- ご指摘ありがとうございます、修正しました。

2024-02-09 01:08 UTC, abeai0 commented on resources/views/auth/register.blade.php
> +                    value="{{ old('password') }}">
- ご指摘ありがとうございます、修正しました。

2024-02-09 01:08 UTC, abeai0 commented on resources/views/auth/register.blade.php
> +    </h1>
- ご指摘ありがとうございます、修正しました。

2024-02-10 02:56 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKそうですのでマージしますね！

2024-02-10 02:56 UTC, merged