#912 共通ファイル＆ヘッダー・フッター＆トップページのタイトル表示(チームD井手)
yukihiroLaravel/joint_develop pull request #927
Opened 2024-02-01 07:30 UTC by yamaha-win

## issue
 - Closes #912

## 概要
 - 共通ファイルの表示
 - ヘッダー・フッターの追加
 - トップページのタイトル表示「Topic Post」

## 動作確認手順
 - 表示ができるか確認をお願いします。

## 考慮してほしいこと
 - Laravel応用講座などいろんな所から参考にしました。

## 確認してほしいこと
 - 最初のページのみ表示できるか確認をお願いします。

2024-02-01 08:10 UTC, yukihiroLaravel requested changes
おつかれさまでした！
レビューしました！

原則タスクと関係のあるファイルのみをいじるべきなので
タスクと無関係のファイルはすみませんが
一旦もとに戻しましょう！

2024-02-01 08:10 UTC, yukihiroLaravel commented on app/User.php
> +    use SoftDeletes;
ここは今回のタスクとは無関係なので
追加行をもとに戻しましょう！

2024-02-01 08:10 UTC, yukihiroLaravel commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->softDeletes();
ここも今回のタスクとは無関係なので
追加行をもとに戻しましょう！

2024-02-01 09:34 UTC, yamaha-win commented
指摘された２ヵ所を修正しました。

2024-02-02 13:24 UTC, yamaha-win commented on app/User.php
> +    use SoftDeletes;
該当箇所を元に戻しておきました。
宜しくお願いいたします。

2024-02-02 13:24 UTC, yamaha-win commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->softDeletes();
該当箇所を元に戻しておきました。
宜しくお願いいたします。

2024-02-02 14:31 UTC, yukihiroLaravel approved these changes

2024-02-02 14:31 UTC, merged