#912 共通ファイル&ヘッダー・フッター & トップページのタイトルのみ表示(いのうえ)
yukihiroLaravel/joint_develop pull request #928
Opened 2024-02-01 12:28 UTC by inouehiroshi440409

## issues
- Closes #912 

## 概要
- 共通ファイル&ヘッダー・フッター & トップページのタイトルのみ表示

## 動作確認手順
- 下記URLからトップ画面が表示されることを確認  
http://localhost:8080/  
- header、footerの表示を確認

## 考慮して欲しいこと

## 確認して欲しいこと
- fontawesomeの記述
```
<h1><i class="fa-brands fa-x-twitter pr-3"></i>Topic Posts</h1>

2024-02-03 01:53 UTC, Osk0830 requested changes
お疲れ様でした！
概ねよくできていると思います！
少しだけ修正が必要な箇所がありコメントしましたので、
確認よろしくお願いします。

2024-02-03 01:53 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +}
- トップページは、内容的に投稿の一覧ですので、ユーザーの一覧であることを示唆するUsersControllerのindexアクションではなく、PostsControllerを作成し、そのindexアクションを用いて表示させるようにするのが良さそうです。

2024-02-03 01:53 UTC, Osk0830 commented on routes/web.php
> +Route::get('/', 'UsersController@index');
- どのコントローラーにした方がいいかは先にコメントした通りですので、ルーティングもそれに合わせて修正しましょう。

2024-02-03 01:53 UTC, Osk0830 commented on resources/views/commons/header.blade.php
> +        </div>
- こちらテンプレの問題っぽいですが、`<ul>`の閉じタグが抜けているので追加してください。

2024-02-03 01:53 UTC, Osk0830 commented on resources/views/layouts/app.blade.php
> +            @include('commons.error_messages')
- エラーメッセージのパーツをここに読み込んでしまうと、↓のお手本サイト通りの位置には表示されないと思います。このパーツをどこで読み込むべきか検討してみてください。

[![Image from Gyazo](https://i.gyazo.com/2263f3fcd8dde6be83178637849b4f52.png)](https://gyazo.com/2263f3fcd8dde6be83178637849b4f52)

2024-02-03 01:53 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +            </div>
- この辺インデントがおかしくなっているようです。インデントを調整しましょう。

2024-02-03 13:34 UTC, inouehiroshi440409 commented on resources/views/layouts/app.blade.php
> +            @include('commons.error_messages')
申し訳ございませんが、お手本の位置がわからないので、教えていただければと思います。

2024-02-03 13:36 UTC, inouehiroshi440409 commented on resources/views/welcome.blade.php
> +            </div>
申し訳ございませんが、どこがおかしいのかがわからないので、教えて頂けないでしょうか？

2024-02-06 00:11 UTC, inouehiroshi440409 commented on resources/views/layouts/app.blade.php
> +            @include('commons.error_messages')
コメントアウトはしたのですが、どうしたら位置を変えられるかわからないので教えて頂ければと思います。

2024-02-08 11:22 UTC, Osk0830 requested changes
お疲れ様でした！
内容的にはOKだと思います！

①
インデントの件コメントしましたので、
確認よろしくお願いします！
（HTMLのインデントは要素の階層構造、すなわち親子関係・兄弟関係が明確に伝わるようにしましょう）

②
MTG時もお伝えしましたが、レビューでコメントした箇所については、どのように対応したかなどわかるように、全てにリプライでコメントを付してくださいね！

[![Image from Gyazo](https://i.gyazo.com/bfd7db5268f45ffd97e5cdd2522df345.png)](https://gyazo.com/bfd7db5268f45ffd97e5cdd2522df345)

2024-02-08 11:22 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +            </div>
- 7行目で終わっている<div>と続く<h5>は兄弟要素ですので、インデントは同じ位置に揃う必要があります。
- また、9行目の<div>と10行目から始まる<div>も、ともに<h5>と兄弟要素になりますので、インデントが揃う必要がありますね。

2024-02-08 11:34 UTC, inouehiroshi440409 commented on resources/views/welcome.blade.php
> +            </div>
7行目と9、１０行目が揃えばよろしいでしょうか？

2024-02-08 13:46 UTC, Osk0830 approved these changes
お疲れ様でした！
まだ一箇所インデントがおかしい箇所がありますが（コメント参照ください）、ほぼほぼOKなので一旦マージしますね。
良きタイミングで修正お願いしますね。

2024-02-08 13:46 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +        <h5 class="text-center mb-3">"○○"について140字以内で会話しよう！</h5>
- 8行目も一つ前に出るべきですね。

2024-02-08 13:46 UTC, merged