posts（投稿）テーブルのマイグレーションとシーダー作成 #913（きよはる）
yukihiroLaravel/joint_develop pull request #931
Opened 2024-02-02 23:02 UTC by kiyoharu420

## issue
-Closes #913 

##概要
ーポストマイグレーションとシーダーの実装

##動作確認手順
ー下記コマンドを実行
php artisan migrate --seed
-アドマイヤでpostsテーブルに１２個のレコードが保存されていることを確認

##考慮しほてしいこと
ー足りないと指摘されたのは外部キー制約でしょうか？
追加してみました。

##確認してほしいこと
ー

##

2024-02-03 01:41 UTC, yukihiroLaravel requested changes
昨日足りないと言っていたのは
user_idと外部キー制約ですので、ほぼ完璧です！
すばらしいです。

その他１点指摘しましたのでご確認ください☺️

2024-02-03 01:41 UTC, yukihiroLaravel commented on app/Posts.php
> +}
こちらのファイルは今回のタスクには関係していませんので
動作確認も取れないので
一旦は丸々削除していいかなと思いました！

あと、作成するとしたらファイル名は単数系で
Post.php
としましょう！

2024-02-03 04:06 UTC, kiyoharu420 commented on app/Posts.php
> +}
ありがとうございます。いらないのなら、またどこかで悪さしないように消します。

2024-02-03 04:43 UTC, kiyoharu420 commented on app/Posts.php
> +}
削除しました。
確認お願いします。

2024-02-03 06:25 UTC, yukihiroLaravel requested changes
確認してご連絡しました！
あと、昨日お伝えの通り、再度修正してpushした際も
プルリクのURLをslackの返信欄に貼っていただけるとたすかります！！

https://www.loom.com/share/cb1fb7d2607548d0a0262c8380eeae69?sid=7f9bedd7-2cac-4fdb-ab7a-78474936eabb

2024-02-03 08:56 UTC, kiyoharu420 commented
動画で指摘いただいたタイトル削除しました。
よろしくお願いします。

2024-02-07 09:30 UTC, yukihiroLaravel requested changes
titleをきちんと消せたか動作確認できましたか？
まだtitleが残っていましたので
削除願います！

2024-02-07 09:30 UTC, yukihiroLaravel commented on database/migrations/2024_02_02_130427_create_posts_table.php
> +            $table->string('title');
この１行が削除できていなさそうですね・・・！
削除ねがいます！

2024-02-07 09:30 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +            'title' => 'テスト投稿',
こちら含めて下記全ての

'title' => 'テスト投稿',

は不要なので削除しましょう！

2024-02-07 12:48 UTC, kiyoharu420 commented on database/seeds/PostsTableSeeder.php
> +            'title' => 'テスト投稿',
修正して、プッシュできていませんでした。
再度プッシュしました。
確認お願いします。

2024-02-07 20:42 UTC, yukihiroLaravel approved these changes

2024-02-07 20:42 UTC, merged