#910 ユーザログイン・ログアウト(川原)
yukihiroLaravel/joint_develop pull request #934
Opened 2024-02-03 14:18 UTC by natsumi-kawahara-epkotsoftware

## issue
- Closes #910

## 概要
- ユーザログイン・ログアウト

## 動作確認手順
- ①http://localhost:8080 へアクセスし、
画面右上にある「ログイン」を押下し、ログイン画面になっていることを確認
- ②メールアドレス：test1@test.com、パスワード：test1を入力し、ログインボタンを押下
- ③ログイン後の画面が「Topic Posts」であることを確認し、右上に「ログアウト」があることを確認
- ④右上の「ログアウト」を押下し、トップページに戻ったことを確認

## 考慮して欲しいこと
- 今回は特にありません。

## 確認してほしいこと
- 今回は特にありません。

2024-02-03 23:32 UTC, yukihiroLaravel requested changes
コメント・指摘させていただきましたのでご確認ください☺️

2024-02-03 23:32 UTC, yukihiroLaravel commented on resources/views/auth/login.blade.php
> +            <form method="POST" action="{{ route('login.post') }}">
現状ですとバリデーションエラーが出る場所が
お手本と違っていないでしょうか？

おそらくこのあたりにバリデーションエラーメッセージを埋め込まないとイケないと思います！

また、ここに埋め込むだけだと
共通ファイルのバリデーションエラーメッセージと重複してしまいますが
app.blade.phpからエラーメッセージをincludeしている行を削除すればいいと思います！

2024-02-03 23:32 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
> +
この空行は不要ですね！

2024-02-03 23:32 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
> +@endif
お手本だとこの位置にユーザ名が表示されるのではなく
このファイルでいう１４行目の

`<li class="nav-item"><a href="" class="nav-link text-light">ログインユーザ名</a></li>`

こちらにAuth::user()->nameが表示されるよう埋め込みましょう！

2024-02-04 14:48 UTC, natsumi-kawahara-epkotsoftware commented on resources/views/auth/login.blade.php
> +            <form method="POST" action="{{ route('login.post') }}">
@yukihiroLaravel 

現状、エラーメッセージが出るところは合っていると思うのですが、いかがでしょうか？

<img width="1195" alt="スクリーンショット 2024-02-04 23 46 30" src="https://github.com/yukihiroLaravel/joint_develop/assets/117135604/87841ca2-a748-4f5e-b0a3-bdbe085198b0">

2024-02-05 11:16 UTC, yukihiroLaravel requested changes
いくつか指摘しました！

また、すみませんが他の方のプルリクがマージされた関係で
コンフリクトが発生していますので
動画を見つつ、どの部分を活かすべきでどの部分を消すべきなのか考えながら
（必要であればチームメンバーに相談しながら）
コンフリクト解消しましょう！

2024-02-05 11:16 UTC, yukihiroLaravel commented on resources/views/auth/login.blade.php
> +    @include('commons.error_messages')
この位置ですと、
エラーメッセージの横幅が
お手本アプリよりも少し幅広にならないでしょうか？

なので、今回であれば、１５行目・１６行目あたりに配置した方がいいかと思いました！

2024-02-05 11:16 UTC, yukihiroLaravel commented on resources/views/commons/header.blade.php
> +                        <p class="text-right mr-3 pb-3">ユーザー：<span class="user-name">{{ Auth::user()->name }}</span></p></a></li>
こちらコンフリクト解消すれば自動的に治るかもしれませんが
「ユーザー：」というのはお手本にはないと思いますので、削除しましょう。

今回の要件は、一旦は
「お手本に近い見た目・実装とすること」ということなので
その要件を満たすように確認して作りましょう！

2024-02-05 11:16 UTC, yukihiroLaravel commented on resources/views/layouts/app.blade.php
> +            <!-- @include('commons.error_messages') -->
このコメントアウトの行も不要かなと思いますので
完全に消しましょう！

2024-02-05 11:31 UTC, natsumi-kawahara-epkotsoftware commented on resources/views/auth/login.blade.php
> +    @include('commons.error_messages')
@yukihiroLaravel 
よく見たら幅広になっていました。
16行目に書くことで、お手本と同じ大きさになりました。

2024-02-05 21:31 UTC, yukihiroLaravel approved these changes
コンフリクト解消含め、いいですね！

OKなのでマージしました！
お疲れ様でした！！

2024-02-05 21:32 UTC, merged