Feature/yokoi/posts seeder
yukihiroLaravel/joint_develop pull request #935
Opened 2024-02-03 17:40 UTC by KosukeYokoi

ゆきひろさん、お疲れ様です。
やり直しのプルリクエストを再送します。

新ブランチ名
feature/yokoi/posts_seeder　です。

何度もお手数ですがよろしくお願いします。

2024-02-03 23:45 UTC, yukihiroLaravel requested changes
いくつかコメントさせていただきましたので
ご確認お願いします！

あと先日MTG冒頭でおつたえのプルリク先のブランチの選択が
   develop_d ← feature 
ではなく
   main ← feature 
になっていましたので僕の方で正しく変更しました。

これも先日お伝えの通り、プルリクの
files changed を見れば気付けますので
しっかり確認しましょう✨

2024-02-03 23:45 UTC, yukihiroLaravel commented on database/migrations/2024_02_04_012130_create_posts_table.php
> +            //$table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
すでにusersテーブルはdevelopブランチに存在しますので
こちらのコメントアウトは削除しましょう！

2024-02-03 23:45 UTC, yukihiroLaravel commented on database/migrations/2024_02_04_012130_create_posts_table.php
> +            $table->dropForeign(['user_id']);
この１行ですが
ここで削除する意味はないと思いますので消したほうがよさそうですね！

2024-02-04 01:51 UTC, KosukeYokoi commented on database/migrations/2024_02_04_012130_create_posts_table.php
> +            //$table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
ローカルで削除しました。

2024-02-04 01:51 UTC, KosukeYokoi commented on database/migrations/2024_02_04_012130_create_posts_table.php
> +            $table->dropForeign(['user_id']);
ローカルで削除しました。

2024-02-04 09:27 UTC, yukihiroLaravel requested changes

2024-02-04 09:27 UTC, yukihiroLaravel commented on database/seeds/PostsTableSeeder.php
> +        }
こちら、
php artisan migrate:fresh --seed
このコマンドで動作確認してみたのですがエラーが出ます！
今後、エラーが出ないか？はしっかりと動作確認を行なった上で
プッシュ・プルリクを行いましょう！

これは、外部キー制約のせいで
usersテーブルに1から4のuser_idしか存在しないのに
ここでは`$i`を用いていることでuser_id が1~5まで保存されようとしているので
エラーが発生しています。

1~4までのみを保存することも可能ではありますが
可能ならページネーションも確認したいので11個くらいpostデータを作りたいところです。

そこで、for文を用いたやり方だと少し難易度が高いので
Laravel応用のusers のseederファイルの書き方を真似て
for文を記述せずに１つ１つのデータを保存する形で対応してみましょう！

2024-02-04 14:35 UTC, KosukeYokoi commented on database/seeds/PostsTableSeeder.php
> +        }
Laravel応用の手本に近づけてローカルでコード修正しました。

2024-02-05 05:40 UTC, yukihiroLaravel approved these changes
問題ないと思いますのでマージしました！
お疲れ様でした😊

2024-02-05 05:41 UTC, merged