#895ユーザ新規登録(オオハシ）
yukihiroLaravel/joint_develop pull request #936
Opened 2024-02-04 09:53 UTC by kenta-oohashi

## issue
- Closes#895

## 概要
- ユーザ新規登録

## 動作確認手順
- http://localhost:8080/signup へアクセスし名前・メールアドレス・パスワードを入力して新規登録ボタンを押したら、Adminerのusersテーブルに登録されているか

- 登録したらトップページに戻るか

## 考慮してほしいこと
- 申し訳ございません。間違えてdevelopブランチでregisterコントローラをいじり、保存してしまいました。そのため、git commit -mをするときに、registerコントローラには変更されていないことになっていると思います。今後はこのようなことがないようにいたします。大変申し訳ございませんでした。

2024-02-06 03:20 UTC, Osk0830 requested changes
お疲れ様でした！
概ね良くできていると思います！

①
少しだけ修正が必要な箇所がありコメントしましたので、
確認よろしくお願いします。

②
既にヘッダーなどマージされてますので、

- 新規登録画面に遷移するためのリンク貼り
- 下記赤枠で囲った箇所の表示分け（ログイン時と非ログイン時）

も併せて行っていただければと思います！

[![Image from Gyazo](https://i.gyazo.com/50dea86de3f9cd4cce47b91b04571bc0.png)](https://gyazo.com/50dea86de3f9cd4cce47b91b04571bc0)

2024-02-06 03:20 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +@extends('layouts.app')
- バリデーションで弾かれた際のエラーメッセージはお手本サイト通りの位置に表示されますでしょうか？

[![Image from Gyazo](https://i.gyazo.com/13817d9bb7cc73c99f90ff64ef9f51ae.png)](https://gyazo.com/13817d9bb7cc73c99f90ff64ef9f51ae)

2024-02-06 03:20 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +                </div>
- パスワード関連の入力項目は、バリデーションで弾かれた際に既存の入力内容を残さず、再入力しなければならないようにしてください。

2024-02-07 14:28 UTC, kenta-oohashi commented
##  issue
- Closes#895
## 概要
- ユーザ新規登録（修正版）

##確認して頂きたいこと
- トップページheaderにある新規ユーザ登録ボタンを押すと新規ユーザ登録ページへ移動できるかの確認

- ログイン時には、トップページのheader部分が、ユーザーログイン名とログアウトに表示が変わっているか。ログインしていないときはログインと新規ユーザ登録に表示がなっているか

- 新規ユーザ登録するときのバリデーションの位置が、新規ユーザ登録と名前記入欄の間に出るか

- バリデーションはじかれた時に、既存の入力内容を残さず、再入力しなければならないようになっているか

2024-02-08 11:27 UTC, Osk0830 requested changes
お疲れ様でした！
内容的にはほぼほぼOKだと思います！

①
一点だけコメントしましたので、確認よろしくお願いします！

②
MTG時もお伝えしましたが、レビューでコメントした箇所については、どのように対応したかなどわかるように、全てにリプライでコメントを付してくださいね！

[![Image from Gyazo](https://i.gyazo.com/d11e8e9540dc38937a84af95c171f744.png)](https://gyazo.com/d11e8e9540dc38937a84af95c171f744)

2024-02-08 11:27 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +                </div>
- この部分、value属性自体無くすか、残すなら空にしましょう。

2024-02-08 16:22 UTC, kenta-oohashi commented on resources/views/auth/register.blade.php
> +                </div>
承知しました！
パスワードとパスワード確認欄のValue属性を消してプルしましたので確認よろしくお願いいたします！

2024-02-08 16:25 UTC, kenta-oohashi commented
##  issue
- Closes#895
## 概要
- ユーザ新規登録（修正版）

##確認していただきたいこと
register.blade.phｐのフォームメソッド「POST」欄のパスワードとパスワード確認欄のValue欄を削除しましたのでその確認をよろしくお願いいたします。

2024-02-10 03:37 UTC, Osk0830 requested changes
お疲れ様でした！
ほぼほぼOKですね！

少しだけコメントしましたので、確認よろしくお願いします！

2024-02-10 03:37 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +    <div class="row mt-5 mb-5">
- エラーメッセージを表示するボックスの幅が、お手本サイトに比べてかなり大きくなってしまっています。お手本サイト通りになるよう、パーツを読み込む位置を検討しましょう。

[![Image from Gyazo](https://i.gyazo.com/03edfde0ae38a02ddf3d764402469617.png)](https://gyazo.com/03edfde0ae38a02ddf3d764402469617)

2024-02-10 03:37 UTC, Osk0830 commented on resources/views/commons/header.blade.php
> +                @else
- こちらはOKです！ただ、せっかくなので、ログインしたユーザーの名前が表示されるようにしてあげましょう。

[![Image from Gyazo](https://i.gyazo.com/29b501e8a0052d17da7ed7aad8dc7e16.png)](https://gyazo.com/29b501e8a0052d17da7ed7aad8dc7e16)

2024-02-10 15:40 UTC, kenta-oohashi commented on resources/views/auth/register.blade.php
> +    <div class="row mt-5 mb-5">
承知しました。赤枠の幅を５４０ｐｘに変更しました

2024-02-10 15:40 UTC, kenta-oohashi commented on resources/views/commons/header.blade.php
> +                @else
Auth::user()->nameを使い表記できるようにしました

2024-02-10 15:47 UTC, kenta-oohashi commented
## issue
- #895 
##概要
- ユーザ新規登録（修正版）
##確認していただきたいこと
- 新規登録時のバリデーションエラーの幅
- ログイン時のヘッダーが、今までは「ログインユーザ名」と表記されていたが、ログインしたユーザの名前が表記されるようになったか

2024-02-12 01:12 UTC, Osk0830 requested changes
お疲れ様でした！
ナビゲーション部分はOKです。
エラーメッセージの部分についてコメントしましたので、
確認よろしくお願いします！

2024-02-12 01:12 UTC, Osk0830 commented on resources/views/auth/register.blade.php
> +    <div class="row mt-5 mb-5">
- 要素のスタイルそのものを変更してしまうと、他の箇所で利用する際にも影響が出てしまいます。現状だと、インクルードする位置だけ調整すればスタイルの指定は不要な状況ですので、スタイルの指定は消し、インクルードする位置を調整してみてください。

2024-02-12 01:12 UTC, Osk0830 commented on resources/views/commons/error_messages.blade.php
> +    <ul class="alert alert-danger" role="alert" style="max-width: 540px; margin: 0 auto; text-align: left;">
- 先に書いた通り、スタイルの指定は削除しましょう。

2024-02-12 13:08 UTC, kenta-oohashi commented
## issue
- #936 
## 概要
-ユーザ新規登録（修正版）
## 確認していただきたいこと
- 新規登録時のバリデーションエラー幅の確認

2024-02-12 13:10 UTC, kenta-oohashi commented on resources/views/commons/error_messages.blade.php
> +    <ul class="alert alert-danger" role="alert" style="max-width: 540px; margin: 0 auto; text-align: left;">
ご指摘ありがとうございます！
スタイル指定は削除し、インクルードの位置を修正しました。

よろしくお願いいたします！

2024-02-13 15:39 UTC, kenta-oohashi commented
## issue
- #936 
## 概要
- 新規ユーザ登録(修正版)
## 確認していただきたいこと
- web.php とcomposer.lockで起きていたコンフリクトが解消しているか

2024-02-15 03:41 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKなのでマージしますね！

2024-02-15 03:41 UTC, merged