#892 トップページの投稿表示（小林）
yukihiroLaravel/joint_develop pull request #938
Opened 2024-02-05 10:25 UTC by Celadon67

##issue
-closes #892

##動作確認
-[http://localhost:8080/　を打ち込むと添付したスクリーンショットの表示となります
![スクリーンショット 2024-02-05 191934](https://github.com/yukihiroLaravel/joint_develop/assets/151298156/d877f44d-2ff0-4f69-af2d-750bbd27581c)

##考慮してほしいこと
-2024/2/5 19;21現在、ログインユーザ名、ログアウト、ログイン、新規ユーザ登録　タブを押しても画面がそちらに移行しません
-2024/2/5 19;21現在、投稿欄に書き込んで投稿しても画面遷移しません

2024-02-06 00:18 UTC, Osk0830 requested changes
お疲れ様でした！
概ね良くできていると思います！

いくつか修正が必要な箇所がありコメントしましたので、
確認よろしくお願いします！

2024-02-06 00:18 UTC, Osk0830 commented on routes/web.php
> +Route::post('signup', 'Auth\RegisterController@register')->name('signup.post');
- こちら新規で追加されたようですが、今回のタスクとは関係のない内容かと思いますので削除してください。

2024-02-06 00:18 UTC, Osk0830 commented on echo
- こちら不要なファイルが生成されているようですので一旦削除していただければと思います。

2024-02-06 00:18 UTC, Osk0830 commented on composer.bat
- こちらのファイルは Windowsでだけ用いられるファイルのようですし、必要な場合は各自のローカルで生成されるようなので、共有する必要はなさそうです。こちらのファイルは `.gitignore`に入れて共有されないようにしておいてください。

2024-02-06 00:18 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                    <p class="mb-2">{{ $post->content}}</p>
- マイグレーションで指定してあるカラム名と異なるため、投稿内容が表示されないようです。

2024-02-06 00:18 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                    <p class="text-muted">{{ $post->created_at }}</p>
- 現在のシーディングでは、`created_at`カラムが nullのため、Adminerで手動で日時の情報を入れてみて、それが正常に表示されるかの確認もよろしくお願いします！

2024-02-06 00:18 UTC, Osk0830 commented on resources/views/welcome.blade.php
- 投稿フォーム部分ですが、お手本サイトでは、ログイン時にしか表示されないと思いますので、そうなるように、このタスク内で併せて調整いただければと思います！

2024-02-06 03:34 UTC, Celadon67 commented on routes/web.php
> +Route::post('signup', 'Auth\RegisterController@register')->name('signup.post');
了解いたしました。

2024-02-06 03:34 UTC, Celadon67 commented on echo
echoをローカルで物理的に削除するということで大丈夫でしょうか?

2024-02-06 03:34 UTC, Celadon67 commented on composer.bat
1: workspace直下で「新しいファイル」アイコンを押し、「.gitignore」を生成。
2: 「.gitignore」ファイルを編集し、.composer.bat/と記載。

この手順で合っていますか?

2024-02-06 03:34 UTC, Celadon67 commented on resources/views/posts/posts.blade.php
> +                    <p class="mb-2">{{ $post->content}}</p>
Laravel応用講座を参考に10行目を作成していたため、引き渡せていませんでした。
以下の写真のように投稿がみれるようになりました。
![スクリーンショット 2024-02-06 120747](https://github.com/yukihiroLaravel/joint_develop/assets/151298156/dd11f730-4352-47ae-9f58-d44f9c3cdc61)

2024-02-06 03:34 UTC, Celadon67 commented on resources/views/posts/posts.blade.php
> +                    <p class="text-muted">{{ $post->created_at }}</p>
表示できるようになりました。
![スクリーンショット 2024-02-06 120747](https://github.com/yukihiroLaravel/joint_develop/assets/151298156/ba1a3360-1a4c-4178-b806-a2ccfdadd906)

2024-02-06 03:35 UTC, Celadon67 commented on resources/views/welcome.blade.php
@if(Auth::check())を入れて修正しました。

2024-02-07 09:29 UTC, Osk0830 commented on echo
はい！それで大丈夫です！

2024-02-07 09:32 UTC, Osk0830 commented on composer.bat
`.gitignore`はすでに存在しますので、こちらに追記いただければOKです。ただ、ここに書く前に存在したファイルは ignoreの対象にならない可能性ありますので、その場合は `compser.bat`自体は一度物理的に削除いただいてOKです。

[![Image from Gyazo](https://i.gyazo.com/92bdb7a14995f87aecc9180eb5e8df72.png)](https://gyazo.com/92bdb7a14995f87aecc9180eb5e8df72)

2024-02-08 11:13 UTC, Osk0830 requested changes
お疲れ様でした！
ほぼほぼOKですが、一点だけ気になる箇所があったので、確認よろしくお願いします！
また、Bladeなどに変更を加えた際は、インデントがしっかり合っているか確認するようにしてくださいね！

2024-02-08 11:13 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +    @endif
- こちらは何でしょうか？
- また、前回のレビューでコメントさせていただいた、「投稿フォーム」の出し分はできているでしょうか？

2024-02-08 13:42 UTC, Osk0830 requested changes
お疲れ様です！
レビューで指摘した内容はOKなのですが、不要な記述が入ってしまっているので、修正よろしくお願いします！

2024-02-08 13:42 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +                <form method="POST" action="{{ route('post.store') }}" class="d-inline-block w-75">
- こちら表示させるとエラー出ませんでしょうか？まだ作られていないルーティングなどは書き入れないようにしましょう。formそのものの変更は新規投稿タスクの管轄ですので、method・csrfなど、表示の出し分け以外全てもとのままにしておいてください。

2024-02-12 02:31 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKなのでマージしますね！

2024-02-12 02:31 UTC, merged