#894 ユーザログイン・ログアウト (石井)
yukihiroLaravel/joint_develop pull request #940
Opened 2024-02-09 14:54 UTC by sora1012

## issue
- Closes #894

## 概要
- ユーザーログイン・ログアウト

## 動作確認手順
- http://localhost:8080/ へアクセス
- メールアドレス：[test1@test.com](mailto:test1@test.com)
- パスワード：test1
- ユーザとしてログインされたら、「ログアウト」を押してトップページへ移るか確認

## ご考慮いただきたいこと

## ご確認いただきたいこと

2024-02-10 03:51 UTC, Osk0830 requested changes
お疲れ様でした！
基本的にはできていると思います！

いくつか修正が必要な箇所がありコメントしましたので、
確認よろしくお願いします！

2024-02-10 03:51 UTC, Osk0830 commented on resources/views/auth/login.blade.php
- バリデーションに弾かれた際にエラーメッセージが表示されないですね。エラーメッセージ表示用のパーツを読み込みましょう。どの位置に読み込むかなどはお手本サイトを参考にしてくださいね！

[![Image from Gyazo](https://i.gyazo.com/e871cb6cffdefc1a4e676b73102a2489.png)](https://gyazo.com/e871cb6cffdefc1a4e676b73102a2489)

2024-02-10 03:51 UTC, Osk0830 commented on resources/views/auth/login.blade.php
> +                    <input id="password" type="password" class="form-control" name="password" value="{{ old('password') }}">
- バリデーションで弾かれた際にパスワードは再入力しなければならないよう、既存の情報を保持・表示させないようにしましょう。

2024-02-10 03:51 UTC, Osk0830 commented on resources/views/commons/header.blade.php
> +                @else
- こちら順序や内容が既存のものと変わってるようなので、元に戻しておきましょう。

2024-02-10 03:51 UTC, Osk0830 commented on routes/web.php
> +Route::post('signup', 'Auth\RegisterController@register')->name('signup.post');
- こちらは今回のタスクとは無関係ではないでしょうか？

2024-02-10 09:44 UTC, sora1012 commented on routes/web.php
> +Route::post('signup', 'Auth\RegisterController@register')->name('signup.post');
こちらのルーティングを入力せずにテストしたところ、
Route [signup] not defined. 
とエラーが出たため、定義しております🙇‍♂️

2024-02-12 01:04 UTC, Osk0830 commented on routes/web.php
> +Route::post('signup', 'Auth\RegisterController@register')->name('signup.post');
- ヘッダーのナビゲーションにまだ作業完了していないリンクまで貼っているからですね。ログイン・ログアウト以外のリンクは一旦空にしておいてください。

2024-02-16 03:49 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKなのでマージしますね！

2024-02-16 03:49 UTC, merged