#906 ユーザ編集画面・更新
yukihiroLaravel/joint_develop pull request #941
Opened 2024-02-09 16:14 UTC by yuyakondo333

## issue
 - Close #906
 
## 概要
 - ユーザ編集画面・更新
 
## 動作確認手順
 - ユーザ情報更新
① localhost:8080/users/{{ id }}/editでユーザ情報を編集するhtmlを出力
② 更新するボタンを押してユーザ情報が変わっていることを確認
③ ユーザ情報、メールアドレス、パスワードのいずれかが空白、パスワードが一致しない事でバリデーションエラーが出力されることを確認

 - ユーザ情報削除
退会するボタンからモーダルの退会するボタンをクリックしてwelcome.blade.phpへ遷移することを確認

## 考慮してほしいこと
 - 本来は更新するボタンをクリックした際にユーザ詳細画面へ遷移するかと思うのですが、設定していないためエラーが起こると考えられます。今回はあらかじめ設定しておきました。
 UserController.php 45行目 ```return view('users.detail');```

 - テストとしてwelcome.blade.phpに設定してユーザ名、メールアドレス、パスワードが変更していることを確認できました。
 
## 確認してほしいこと
- 考慮して欲しいことに記載した部分の動作確認をお願い致します。
```return view('users.detail');```
↓
```return view('welcome');```

2024-02-10 14:11 UTC, yukihiroLaravel requested changes
レビューしましたので
動画となりますがご確認ください

https://www.loom.com/share/3220bf3868904da1b449389a9a62b34c?sid=b136a6d5-b945-4da4-a986-684a716d2490

2024-02-10 14:11 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        return view('users.edit', ['user' => $user]);
if (条件: ログインしているユーザIDと$idが一致するか確認) {
   return view('users.edit', ['user' => $user]);
}
abort(404);

2024-02-10 14:11 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $validatedData = $request->validate($rules);
フォームリクエストを使いましょう

2024-02-10 14:11 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +    public function update(Request $request) {
フォームリクエストを使いましょう

2024-02-10 14:11 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +    }
削除

2024-02-10 14:11 UTC, yukihiroLaravel commented on resources/views/users/edit.blade.php
> +    @if(Auth::check())
不要になる

2024-02-10 14:11 UTC, yukihiroLaravel commented on resources/views/users/edit.blade.php
> +            <input type="hidden" name="id" value="{{ Auth::id() }}" />
削除？

2024-02-13 06:37 UTC, yukihiroLaravel requested changes
漏れておりすみませんが
１点ご指摘しましたのでご確認お願いします🙇‍♂️

2024-02-13 06:37 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        $user = \Auth::user();
今気づきましたが今の書き方ですと
$id
を使っておらず存在する意味がないので
`$user = User::find($id);`
としてUserを使うようにしましょう！

2024-02-13 12:55 UTC, yuyakondo333 commented on app/Http/Controllers/UsersController.php
> +        $user = \Auth::user();
かしこまりました！
```
App\User;
$user = User::find($id);
```

以上を追加して修正します。

2024-02-14 01:36 UTC, yukihiroLaravel approved these changes
とてもいいですね！！
問題ありませんのでマージしました！
お疲れ様でした☺️

2024-02-14 01:36 UTC, merged