#905 投稿新規作成（西田修）
yukihiroLaravel/joint_develop pull request #944
Opened 2024-02-11 05:43 UTC by osmnishida

## issue
- closes #905 

## 概要
- 投稿新規作成

## 動作確認手順
トップページにアクセス
投稿欄に文字入力
”投稿する”ボタンをクリック
データベースにアクセス
Postsテーブルに投稿した内容が反映されているかを確認

2024-02-11 14:24 UTC, yukihiroLaravel approved these changes
かなり素晴らしいできですので
細かい部分のみ指摘しました！

ご確認ください！

2024-02-11 14:24 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +use App\Post;
上記使っていないので不要かと思います！

2024-02-11 14:24 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::post('', 'PostsController@store')->name('post.store');
上記でもいいですが、
念のためにURLに/をいれましょう！
`Route::post('/', 'PostsController@store')->name('post.store');`

2024-02-11 14:24 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +                    <textarea class="form-control" name="content" rows=""></textarea>
ここのrowsは入力欄の高さを示すので
`rows="4"`
これくらいが適切かと思います！

2024-02-11 15:02 UTC, osmnishida commented on app/Http/Controllers/UsersController.php
> +use App\Post;
かしこまりました。削除します。

2024-02-11 15:03 UTC, osmnishida commented on routes/web.php
> +        Route::post('', 'PostsController@store')->name('post.store');
かしこまりました。修正します。

2024-02-11 15:06 UTC, osmnishida commented on resources/views/welcome.blade.php
> +                    <textarea class="form-control" name="content" rows=""></textarea>
かしこまりました。rowsについて理解しました。

2024-02-11 15:13 UTC, osmnishida commented
修正いたしました。
ご確認よろしくお願いいたします。

2024-02-12 00:42 UTC, yukihiroLaravel requested changes
たびたびすみません！
いくつか動作確認上見落としがありましたので
再度すみませんが修正お願いしたい部分があります🙇‍♂️
よろしくお願いします！

2024-02-12 00:42 UTC, yukihiroLaravel commented on resources/views/auth/user_edit.blade.php
> +        <label for="password_confirmation">パスワードの確認</label>
すみません、見落としていましたが
こちらのファイルは今回のタスクには無関係なので
不要かと思いました！

ご確認お願いします🙇‍♂️

2024-02-12 00:42 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
>          <div class="w-75 m-auto">エラーメッセージが入る場所</div>
今のままですと、
バリデーションエラー（空欄でボタンを押下したときや、140文字以上での入力のとき）が発生したときに
エラーメッセージが出ないので、
ここにエラーメッセージを入れましょう！

2024-02-12 01:15 UTC, osmnishida commented on resources/views/auth/user_edit.blade.php
> +        <label for="password_confirmation">パスワードの確認</label>
かしこまりました。
今回のタスクには無関係でしたので、このファイルは削除します。

2024-02-12 01:15 UTC, osmnishida commented on resources/views/welcome.blade.php
>          <div class="w-75 m-auto">エラーメッセージが入る場所</div>
かしこまりました。
エラーメッセージ入れるように修正します。

2024-02-12 01:18 UTC, osmnishida commented
不要ファイルの削除、エラーメッセージ表示するように修正しました。
ご確認よろしくお願いいたします。

2024-02-12 01:24 UTC, yukihiroLaravel approved these changes
OKです！
問題ないのでマージしました。
お疲れ様でした☺️

2024-02-12 01:24 UTC, merged