#876 新規投稿機能（あべ）
yukihiroLaravel/joint_develop pull request #947
Opened 2024-02-14 01:37 UTC by abeai0

## issue
- Closes #876 

## 概要
- 新規投稿機能の実装

## 動作確認手順
- ログイン後トップページに投稿フォームが表示されることを確認
- フォームに何も入力せずに「投稿する」ボタンを押すとエラーが出ることを確認
- 下記141文字の文章を入力し、文字数制限のエラーが出ることを確認
```
親譲りの無鉄砲で小供の時から損ばかりしている。小学校に居る時分学校の二階から飛び降りて一週間ほど腰を抜かした事がある。なぜそんな無闇をしたと聞く人があるかも知れぬ。別段深い理由でもない。新築の二階から首を出していたら、同級生の一人が冗談に、いくら威張っても、そこから飛び降りる事は出
```
- 140文字以下の文章を入力して「投稿する」ボタンを押すとトップページに戻ることを確認
- データベースのPostsテーブルにログインしたユーザーのidでテスト投稿の内容がcontentカラムに保存されていることを確認

## 考慮して欲しいこと
- バリデーションメッセージの日本語対応が未のため英語表記のままです

## 確認してほしいこと
- 投稿の文字数制限は半角文字も全角文字も共通で140文字にしていますが、半角文字は0.5文字でカウントされるようにした方がいいのでしょうか？

2024-02-15 04:02 UTC, Osk0830 requested changes
お疲れ様でした！
全体的にとても良くできていると思います！

一点だけ修正お願いしたい箇所がありますので、
確認よろしくお願いします！

2024-02-15 04:02 UTC, Osk0830 commented on routes/web.php
> +  Route::post('/', 'PostsController@store')->name('post.store');
- これでも間違いではありませんが、今後コメント投稿など他の投稿も出てくる可能性など考えると、ルートのURLへのPOSTだと分かりにくくなりそうな気がします。何の投稿なのか分かりやすいように、Laravelのデフォルト流儀にしたがって、`/posts`へのPOSTにするのが良さそうです。

2024-02-15 04:08 UTC, abeai0 commented on routes/web.php
> +  Route::post('/', 'PostsController@store')->name('post.store');
- ありがとうございます。/postsに変更しました。

2024-02-16 03:47 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKなのでマージしますね！

2024-02-16 03:47 UTC, merged