#890_feature/ohtomo/User_edit_and_update_functions（ohtomo）
yukihiroLaravel/joint_develop pull request #948
Opened 2024-02-14 06:02 UTC by to-ohtomo

# issue
Closes #890ユーザ編集画面・更新（ohtomo）

# 概要
ユーザ編集画面・更新処理追加

# 動作確認手順
（１）ユーザ情報編集
・URL:localhost:8080/users/{id}/editにて、編集画面が表示されることを確認しました
・編集画面が表示された際、現状のユーザ名、メールアドレスが入力されることを確認しました

（２）ユーザ情報更新
・編集画面にてパスワードを入力しない状態、また、修正がない状態で「更新する」ボタンをクリックすると、
エラーが表示されることを確認しました
・編集画面でメールアドレスを変更し「更新する」ボタンをクリック後、ユーザ編集画面に戻り、メールアドレスが修正されたことを確認しました

（３）その他
・編集画面に「退会する」ボタンが表示されることを確認しました
・「退会する」ボタンをクリックすると「確認」画面が表示されることを確認しました

# 考慮してほしいこと
・UsersController.phpにて、ログインされているユーザを確認するようにしていますが、
現状、ログインに関するタスクが完了していないため、実際にログインしていない状態で確認を進めました。

・現在ログインされているユーザがいない場合、ユーザ詳細画面に移行する想定ですが、現状はまだユーザ詳細画面が作成できていないため、ログインされているユーザがいない場合は、トップ画面に移行するようにしています。

・「更新する」ボタンクリック後は、ユーザ詳細画面に移行する想定ですが、現状はまだユーザ詳細画面が作成できていないため、更新後も編集画面に移行するようにしています。

# 確認してほしいこと
今回ユーザ編集、更新ができるようにファイルの作成/編集を行いましたが、内容等に問題がないかレビューをお願い致します。

2024-02-15 03:55 UTC, Osk0830 requested changes
お疲れ様でした！
大枠はできていると思います！

いくつか修正が必要な箇所がありますので、
確認よろしくお願いします！

また、先ほど大橋さんのログイン機能マージしましたので、
そちら取り込んで作業進めていただければと思います！

2024-02-15 03:55 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +        if ($user = \Auth::user()) {
- 条件式が、「比較」ではなく「代入」になってますが、これは何を意図しているのでしょうか？

2024-02-15 03:55 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +        }
- ifの条件に合致してif文内が実行されれば、そこの returnで処理は終わりますので、このようなケースは、`else { ... }`で囲わなくても同じになります。もちろん、囲ったからといって間違いではないです。

2024-02-15 03:55 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +        return back();
- ユーザー情報の更新という大事な内容ですので、ログインしている人自身の情報であるときだけ更新できるようにしましょう。これは「編集画面を表示」する edit アクションの方も同様です。

2024-02-15 03:55 UTC, Osk0830 commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
- これだとメールアドレスを必ず変更しなければならなくなりますが、それは現実的ではないと思います。本人の元のメアドと同じ場合はOKとなるようにしてください。`ignore()`を使えますので調べてみましょう！

2024-02-15 03:55 UTC, Osk0830 commented on resources/views/users/edit.blade.php
> +        <input type="hidden" name="id" value="{{ old('id')}}" />
- ここの `old()`は何を意味するのでしょうか？
- また、そもそもこのinput要素自体必要かどうか、どこで使っているのか検討してみてくださいね。

2024-02-15 03:55 UTC, Osk0830 commented on routes/web.php
> +});
- このルーティングはログインしていない状態ではそもそもアクセスできないよう「ミドルウェア」を挟みましょう。

2024-02-17 05:37 UTC, to-ohtomo commented on app/Http/Controllers/UsersController.php
> +        if ($user = \Auth::user()) {
比較になるように修正致します。

2024-02-17 05:45 UTC, to-ohtomo commented on app/Http/Controllers/UsersController.php
> +        }
ご教示有難うございます。今後活用させていただきます。

2024-02-17 05:47 UTC, to-ohtomo commented on app/Http/Controllers/UsersController.php
> +        return back();
承知しました。ログインしているユーザの場合にのみ更新できるように修正します。

2024-02-17 05:48 UTC, to-ohtomo commented on app/Http/Requests/UserRequest.php
> +            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
ご教示有難うございます。ignore()について確認し修正します。

2024-02-17 05:48 UTC, to-ohtomo commented on resources/views/users/edit.blade.php
> +        <input type="hidden" name="id" value="{{ old('id')}}" />
失礼しました。修正致します。
また、input要素自体が必要かについても検討します。

2024-02-17 05:49 UTC, to-ohtomo commented on routes/web.php
> +});
ご教示有難うございます。ミドルウェアを追記するようにします。

2024-02-18 08:57 UTC, to-ohtomo commented
下記ファイルをそれぞれ修正致しましたので、お手数ですが、レビューをお願い致します。

# UsersController.php
・条件分岐の記載を修正しました
・ログインユーザのみ編集、更新できるように修正しました

# UserRequest.php
・メールアドレスが同じであっても更新できるように修正しました。
・コメント行等、不要な記載を修正しました。

# edit.blade.php
・valueの記載を修正しました

# web.php
・middlewareを追記しました

2024-02-19 01:48 UTC, Osk0830 requested changes
お疲れ様でした！

機能的には問題なさそうなのですが、
いくつか調整が必要な箇所がありコメントしましたので、
確認よろしくお願いします！

2024-02-19 01:48 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +        if (Auth::user()->id != $id) {
- コードをスマートにして無駄な処理を行わないようにするという観点から、15行目でログインユーザー情報を取得して `$user`に格納していると思いますので、17行目で再び取得することはせず、`$user`に格納されている値を利用しましょう。
- 余談ですが、ログインユーザーの `id`だけ必要な場合は、`Auth::id()`を使うのがデータが小さくなり、スマートです。

2024-02-19 01:48 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +        $user->update($request->all());
- この行は要りますでしょうか？

2024-02-19 01:48 UTC, Osk0830 commented on resources/views/users/edit.blade.php
> +        <input type="hidden" name="id" value="{{ $user->id }}" />
- この hidden要素はなくても大丈夫ではないでしょうか？

2024-02-19 01:48 UTC, Osk0830 commented on resources/views/users/edit.blade.php
> +        </div>
- バリデーションで弾かれた際に、元の入力データが保持されるようにしましょう。

2024-02-20 06:13 UTC, to-ohtomo commented on app/Http/Controllers/UsersController.php
> +        if (Auth::user()->id != $id) {
ご教示有難うございます。
下記のように修正させていただきます。
if ($user->id != $id)

2024-02-20 06:14 UTC, to-ohtomo commented on app/Http/Controllers/UsersController.php
> +        $user->update($request->all());
ご教示有難うございました。
こちらの行は削除させていただきます。

2024-02-20 06:16 UTC, to-ohtomo commented on resources/views/users/edit.blade.php
> +        <input type="hidden" name="id" value="{{ $user->id }}" />
こちらもご教示有難うございました。
こちらの行は削除させていただきます。

2024-02-20 06:17 UTC, to-ohtomo commented on resources/views/users/edit.blade.php
> +        </div>
修正させていただきましたので、ご確認をお願い致します。

2024-02-20 07:36 UTC, to-ohtomo commented
下記ファイルを修正させていただきましたので、お手数ですが、再レビューをお願い致します。
・UsersController.php
・edit.blade.php

2024-02-21 10:42 UTC, to-ohtomo commented
conflictを改善しましたので、お手数ですが、レビューをお願い致します。

2024-02-22 13:31 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKなのでマージしますね！

2024-02-22 13:31 UTC, merged