Feature/yokoi/toppage display
yukihiroLaravel/joint_develop pull request #949
Opened 2024-02-14 09:58 UTC by KosukeYokoi

概要
• トップページ表示の投稿表示
動作確認手順
localhost:8080にアクセスして、ランダムなアイコン、名前、投稿コメント、投稿時刻が表示されることを確認
考慮して欲しいこと
特になし
確認して欲しいこと
ユーザログイン・ログアウト機能がローカルで取り込まれてないので、このままの修正したコードでいけるかが
気になってます。

以上です、宜しくお願い致します。

2024-02-15 00:17 UTC, yukihiroLaravel requested changes
コメントと動画で修正点ご連絡しました！
ご確認ください！

https://www.loom.com/share/fb7108fc9c9e43f7a6e1f436edec55ff?sid=0ea731bd-4e2d-455c-b679-25330d174526

2024-02-15 00:17 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +}
不要？

2024-02-15 00:17 UTC, yukihiroLaravel commented on app/User.php
> +    }
使われていない関数なので削除？

2024-02-15 00:17 UTC, yukihiroLaravel commented on app/User.php
> +        }
インデントがおかしいので
スペース４つ分左へ移動

2024-02-15 00:17 UTC, yukihiroLaravel commented on database/migrations/2024_02_04_012130_create_posts_table.php
> +}
二重にpostsテーブルを作成していまっているので削除

2024-02-15 00:17 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
>      }
この関数は使わなくなったので削除すればOK

2024-02-15 00:17 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
>      }
```
class UsersController extends Controller
{
}
```

2024-02-15 00:17 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +            <form method="POST" action="{{ route('post.create') }}" class="d-inline-block w-75">
ファイル全体ですが、一旦元に戻してから
下記のみ追記しましょう。

```
<h5 class="text-center mb-3">"趣味や仕事"について140字以内で会話しよう！</h5>
```
```
<!-- 投稿一覧を表示するコンテンツを追加 -->
<div class="post-list">
            @include('toppage', ['$posts' => $posts])
</div>
```

2024-02-15 00:17 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('/', [PostsController::class, 'index']);
書き方を他と統一

```
Route::get('/', 'PostsController@index');
```

2024-02-15 00:17 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('/users/{user}', [UsersController::class, 'show'])->name('users.show');
この二つは別の方の担当タスクなので削除しましょう

2024-02-15 00:17 UTC, yukihiroLaravel commented on resources/views/toppage.blade.php
> +                    <!-- 本人でない場合、ボタンを非表示にする -->
２行不要

2024-02-17 13:15 UTC, KosukeYokoi commented on app/Http/Controllers/UsersController.php
> +}
不要部分消去しました。

2024-02-17 13:15 UTC, KosukeYokoi commented on app/User.php
> +    }
未使用でしたので消去しました。

2024-02-17 13:16 UTC, KosukeYokoi commented on app/User.php
> +        }
インデント修正しました。

2024-02-17 13:18 UTC, KosukeYokoi commented on app/Http/Controllers/UsersController.php
>      }
消去しました

2024-02-17 13:19 UTC, KosukeYokoi commented on resources/views/welcome.blade.php
> +            <form method="POST" action="{{ route('post.create') }}" class="d-inline-block w-75">
全て元に戻して、指摘部分のみ変更しました。

2024-02-17 13:19 UTC, KosukeYokoi commented on routes/web.php
> +Route::get('/', [PostsController::class, 'index']);
他の記述と統一しました。

2024-02-17 13:20 UTC, KosukeYokoi commented on routes/web.php
> +Route::get('/users/{user}', [UsersController::class, 'show'])->name('users.show');
削除しました。

2024-02-17 13:21 UTC, KosukeYokoi commented on resources/views/toppage.blade.php
> +                    <!-- 本人でない場合、ボタンを非表示にする -->
動作も変わらないため、2行削除しました。

2024-02-17 13:22 UTC, KosukeYokoi commented on database/migrations/2024_02_04_012130_create_posts_table.php
> +}
ファイル自体を削除しました。

2024-02-17 14:02 UTC, yukihiroLaravel requested changes
お疲れ様です！
またいくつか指摘しましたので
ご確認お願いいたします☺️

2024-02-17 14:02 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +
この行の追加は不要です

2024-02-17 14:02 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +use App\User;
この行の追加は不要です

2024-02-17 14:02 UTC, yukihiroLaravel commented on app/Post.php
> +//namespace App\Post; // ディレクトリ構造に合わせて修正
この行の追加は不要です

2024-02-17 14:02 UTC, yukihiroLaravel commented on app/User.php
> +        }
前もお伝えしていたかもですが
この３行はスペース４つ分左に移動しましょう。

2024-02-17 14:02 UTC, yukihiroLaravel commented on composer.json
> +	"thomaswelton/laravel-gravatar": "~1.0"
インデントを１つ（スペース４つ分）入れましょう

2024-02-17 14:02 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +            @include('toppage', ['$posts' => $posts])
インデントが付きすぎているので
スペース４つ分左に移動しましょう。

2024-02-17 14:02 UTC, yukihiroLaravel commented on routes/web.php
> +Route::get('/', 'PostsController@index');
前もお伝えしたかもですが
１９行目があれば
１８行目の
`Route::get('/', 'UsersController@index');`
これは不要です！

2024-02-17 14:02 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
>  use App\Http\Requests\UserRequest;
Postsコントローラのindexメソッドの設立により
このファイルのindexメソッドも使わないことになりますので

```
public function index()
{
        return view('welcome');
}
```
この関数は削除願います！

2024-02-18 12:26 UTC, KosukeYokoi commented on app/Http/Controllers/UsersController.php
> +
不要とのことで削除しました。

2024-02-18 12:26 UTC, KosukeYokoi commented on app/Http/Controllers/UsersController.php
> +use App\User;
不要とのことで削除しました。同じ記述が重複もしてました。

2024-02-18 12:29 UTC, KosukeYokoi commented on app/Http/Controllers/UsersController.php
>  use App\Http\Requests\UserRequest;
削除いたしました。

2024-02-18 12:36 UTC, KosukeYokoi commented on resources/views/welcome.blade.php
> +            @include('toppage', ['$posts' => $posts])
インデント調整しました。

2024-02-18 12:37 UTC, KosukeYokoi commented on composer.json
> +	"thomaswelton/laravel-gravatar": "~1.0"
インデント調整しました。

2024-02-18 12:37 UTC, KosukeYokoi commented on app/User.php
> +        }
スペース移動しました。

2024-02-18 12:37 UTC, KosukeYokoi commented on app/Post.php
> +//namespace App\Post; // ディレクトリ構造に合わせて修正
削除しました。

2024-02-18 12:39 UTC, KosukeYokoi commented on routes/web.php
> +Route::get('/', 'PostsController@index');
片方あれば不要かと思いますので削除しました。

2024-02-18 13:43 UTC, yukihiroLaravel requested changes
たびたびすみませんが、指摘させていただきましたので
ご確認をおねがいいたします！

2024-02-18 13:43 UTC, yukihiroLaravel commented on database/migrations/2024_02_04_012130_create_posts_table.php
> -    {
なぜかpostsテーブルマイグレーション消してしまっていますね💦
これは消したらまずいと思います！！

2024-02-18 13:43 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
> +            @include('toppage', ['$posts' => $posts])
ここがまだ治っていませんね💦
スペース４つ分左に移動です！

2024-02-18 13:43 UTC, yukihiroLaravel commented on resources/views/welcome.blade.php
>  </div>
ここはよこいさんがつけた部分ではないと思いますが
２３行目の`</div>`
は意味をなしていないので不要かと思います！

2024-02-18 13:43 UTC, yukihiroLaravel commented on resources/views/toppage.blade.php
> +<div class="m-auto" style="width: fit-content"></div>
あと、忘れていましたが、
１１件以上投稿がある場合に備えて
ページネーション が表示されるように
下記のようにページネーション を埋め込みましょう！
```<div class="m-auto" style="width: fit-content">{{ $posts->links('pagination::bootstrap-4') }}</div>```

2024-02-18 13:43 UTC, yukihiroLaravel commented on resources/views/toppage.blade.php
> +<ul class="list-unstyled">
また、このファイルは
toppage以外にも使う場合がありますので
toppage.blade.phpではなく
posts.blade.phpという名前にファイル名ごと変更したほうがいいかと思います！

2024-02-18 13:43 UTC, yukihiroLaravel commented on routes/web.php
> +
この３行の記述も不要かと思います！

2024-02-19 10:15 UTC, KosukeYokoi commented on resources/views/toppage.blade.php
> +<ul class="list-unstyled">
名前を変更しました。また、それに伴いwelcome.blade.phpの２６行目も@include('posts', ['$posts' => $posts])に変更しました。

2024-02-19 10:17 UTC, KosukeYokoi commented on resources/views/toppage.blade.php
> +<div class="m-auto" style="width: fit-content"></div>
最終行に指定のコードを埋め込みました。

2024-02-19 10:20 UTC, KosukeYokoi commented on resources/views/welcome.blade.php
>  </div>
２３行目の</div>削除しました。

2024-02-19 10:21 UTC, KosukeYokoi commented on resources/views/welcome.blade.php
> +            @include('toppage', ['$posts' => $posts])
すみません、再度直しました

2024-02-19 10:22 UTC, KosukeYokoi commented on routes/web.php
> +
削除しました。

2024-02-19 13:37 UTC, yukihiroLaravel requested changes

2024-02-19 13:37 UTC, yukihiroLaravel commented on resources/views/posts.blade.php
> +<div class="m-auto" style="width: fit-content"></div>
ここ不要

2024-02-19 14:49 UTC, yukihiroLaravel approved these changes
OKです！！
いろいろ苦労されたと思いますが
おつかれさまでした☺️！

2024-02-19 14:50 UTC, merged