#891 ユーザ詳細（オオハシ）
yukihiroLaravel/joint_develop pull request #953
Opened 2024-02-16 08:49 UTC by kenta-oohashi

## issue
- Colses #891 
## 概要
- ユーザ詳細機能
## 動作確認手順
- トピックポストで新規ユーザ登録した後に、http://localhost:8080/users/1 など、登録したユーザのマイページに飛び、ユーザ詳細が表示されるか
- 表示内容がお手本と同じになっているか
##考慮してほしいこと
- まだログイン機能が実装されていないので、URLに直接http://localhost:8080/users/1 などを打ち込み、登録してあるユーザのページに飛ぶ必要がある
## 考慮してほしいこと
- まだフォロー機能、フォロワー機能を作っていないため、ユーザー詳細画面でフォロー中、フォロワーの所を押しても何も起こりません

2024-02-19 01:36 UTC, Osk0830 requested changes
お疲れ様でした！
大変お待たせしてすみません。。！

機能的には問題なさそうなのですが、
いくつか調整が必要な箇所がありコメントしましたので、
確認よろしくお願いします！

[![Image from Gyazo](https://i.gyazo.com/725cdc6aa87ecd69e5f3fc9039bd7372.png)](https://gyazo.com/725cdc6aa87ecd69e5f3fc9039bd7372)

2024-02-19 01:36 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +        ];
- こちら、インデントを揃えましょう。

2024-02-19 01:36 UTC, Osk0830 commented on resources/views/users/show.blade.php
[![Image from Gyazo](https://i.gyazo.com/7045f645589d36ed4c278bfa4360cebc.png)](https://gyazo.com/7045f645589d36ed4c278bfa4360cebc)

2024-02-22 15:09 UTC, kenta-oohashi commented on resources/views/users/show.blade.php
・トップ画面の投稿者の名前から詳細ページに飛べるようにしました
・詳細ページでタイムラインを表示できるようにしました！

2024-02-22 15:12 UTC, kenta-oohashi commented
## issue
- Colses #891
## 概要
- ユーザ詳細機能
## 確認していただきたいこと
- トップページに表示されている投稿をした投稿者の名前からユーザ詳細画面に飛んでいけるか
- 詳細ページのタイムラインの所に自分の投稿が出るか

2024-02-24 08:41 UTC, Osk0830 requested changes
お疲れ様でした！
ほとんど仕上がってきていますね！

少しだけ修正が必要な箇所がありますので、
確認よろしくお願いします。

2024-02-24 08:41 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
>     }
- 前回気づかずに恐縮ですが、ユーザー詳細画面を表示させるためのアクションですので、投稿に関するあれこれを管理するPostsコントローラーではなく、ユーザーに関するあれこれを管理するUsersコントローラーに書くべきですね。ただ、今Usersコントローラーの方にも既に同じ記載があるようですので、こちらはそのまま削除で大丈夫そうですね。

2024-02-24 08:41 UTC, Osk0830 commented on app/Http/Controllers/UsersController.php
> +
- なぜ削除に関する記述があるのでしょうか？タスクと関係ない記述は含めないようにしてください。

2024-02-24 08:41 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +                        </div>
- この塊はインデントが一つ前に出るべきですね。

2024-02-24 11:51 UTC, kenta-oohashi commented on app/Http/Controllers/PostsController.php
>     }
承知しました

2024-02-24 11:51 UTC, kenta-oohashi commented on app/Http/Controllers/UsersController.php
> +
承知しました

2024-02-24 11:51 UTC, kenta-oohashi commented on resources/views/users/show.blade.php
> +                        </div>
承知しました

2024-02-24 11:53 UTC, kenta-oohashi commented
## issue
- Colses #891
## 概要
- ユーザ詳細機能
## 確認していただきたいこと
- 指摘いただいた修正が終わっているか

2024-02-24 12:51 UTC, kenta-oohashi commented
## issue
- Colses #891
## 概要
- ユーザ詳細機能
## 確認していただきたいこと
- ご指摘いただいた微修正
- ユーザ詳細画面のユーザ情報の編集ボタンを押したら編集画面に遷移するか

2024-02-26 12:12 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKそうなのでマージしますね！

2024-02-26 12:12 UTC, merged