#908 トップページの投稿表示(いのうえ)
yukihiroLaravel/joint_develop pull request #954
Opened 2024-02-16 13:41 UTC by inouehiroshi440409

#908 トップページの投稿表示(いのうえ)
## issue
- closes #908 
## 概要
トップページの投稿表示

## 動作確認
- localhost:8080へアクセスしてトップページに投稿が表示されていることを確認する

## 考慮して欲しいこと
- 特になし
## 確認して欲しいこと
-特になし

2024-02-19 00:45 UTC, Osk0830 requested changes
お疲れ様でした！
大変お待たせしてすみません。。！

機能的には問題なさそうなのですが、
いくつか調整が必要な箇所がありコメントしましたので、
確認よろしくお願いします！

2024-02-19 00:45 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +>>>>>>> develop_a_mutsuki_dra
- コンフリクト解消時に不要なメモ（コメント）を残してしまっているようですので、不要なコメントは綺麗に削除しましょう。
- また、モデルファイルの読み込みなどで記述が重複しているようです。重複している記述は整理しましょう。

2024-02-19 00:45 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                <p class="text-muted">{{$post->created_at}}</p>
- コードを綺麗に整形し、可読性を高めるという意味で、`{{`の後ろや`}}`の前には半角空白を入れる形で統一しましょう。ちょうど、5行目のような感じですね。

2024-02-19 00:45 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +
- 不要な空行は削除しましょう。

2024-02-19 00:45 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +>>>>>>> develop_a_mutsuki_dra
- こちらも不要なコメントは削除しましょう。

2024-02-19 11:46 UTC, inouehiroshi440409 commented on app/Http/Controllers/PostsController.php
> +>>>>>>> develop_a_mutsuki_dra
修正を致します。

2024-02-19 11:50 UTC, inouehiroshi440409 commented on resources/views/posts/posts.blade.php
> +                <p class="text-muted">{{$post->created_at}}</p>
修正致します。

2024-02-19 11:51 UTC, inouehiroshi440409 commented on resources/views/posts/posts.blade.php
> +
修正致します。

2024-02-19 11:52 UTC, inouehiroshi440409 commented on resources/views/welcome.blade.php
> +>>>>>>> develop_a_mutsuki_dra
修正致します。

2024-02-20 13:15 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKそうなのでマージしますね！

2024-02-20 13:15 UTC, merged