#869 フォロー機能（あべ）
yukihiroLaravel/joint_develop pull request #962
Opened 2024-02-19 16:10 UTC by abeai0

## issue
- Closes #869 

## 概要
- フォロー機能の実装

## 動作確認手順
- php artisan migrate を実行
- localhost:8080 にアクセス、登録済みのユーザーでログインしてログインユーザー以外の投稿の下部に「フォローする」ボタンが表示されることを確認
- 「フォローする」ボタンを押して「フォローをはずす」ボタンに切り替わることを確認、データベース上でfollowsテーブルにデータが登録されたことを確認
- localhost:8080/users/{ログインユーザーのid} にアクセス、ユーザー詳細ページのフォロー中のタグをクリックし、フォローしたユーザーが表示されるか確認
- 「フォローをはずす」ボタンを押して、フォローをはずしたユーザーの表示が消えるか確認、データベース上でfollowsテーブルのデータが消えるか確認
- 再度フォローをして、localhost:8080/users/{ログインユーザーのid}/edit にアクセス、ユーザー退会をして、データベース上でfollowsテーブルのデータが消えるか確認

## 考慮して欲しいこと
- トップページ、ユーザー詳細ページの投稿一覧表示部分は他のメンバー担当部分のため仮の表示にしています
- ユーザー詳細ページのフォロー中、フォロワーの表示部分もユーザー名・最新の投稿を仮で表示させています
- 仮表示の部分のレイアウトは後で修正していく予定です

## 確認してほしいこと
- ユーザー削除時にフォロー、フォロワーに削除されたユーザーがあった場合中間テーブルのデータも消えるように、User.phpの92,93行目に
 ```
Follow::where('follow_user_id', $user->id)->delete();
Follow::where('followed_user_id', $user->id)->delete();
```
と記述したのですが、もっといい書き方があれば教えてください。

2024-02-23 22:03 UTC, Osk0830 requested changes
お疲れ様でした！
体調の関係で大変お待たせしてしまい、恐縮です。。！

本当に色々なことを考え、またとても綺麗に実装されていて、
実に素晴らしいと思います！

今の感じでも動作的には問題なさそうですが、
より良くするためには、ということも含めてコメントしましたので、
確認よろしくお願いします！

2024-02-23 22:03 UTC, Osk0830 commented on app/User.php
> +    }
- 現状ですと、仕組み的には自分自身をフォローすることも可能になってしまっているようです。自分自身である場合はフォローできないような仕組みにしてくださいね。（自分自身をフォローできるかどうかは、tinkerなどで確認できると思います！）

[![Image from Gyazo](https://i.gyazo.com/328f1fd961cae3b908d6e86918665242.png)](https://gyazo.com/328f1fd961cae3b908d6e86918665242)

- 念のため、`unfollow()`にも同じような仕組みを追加しておくといいかもしれません。

2024-02-23 22:03 UTC, Osk0830 commented on app/Follow.php
- 中間テーブルは、テーブルとテーブルの「関係性」を示すもの、言い換えれば何らかの「存在・物体」であるモデルと他のモデルの「関係」を管理するもので、この「関係」自体は「存在・物体」ではないと思います。モデルは、「存在・物体」の雛形のようなものなので、「関係」にはモデルを設定しないのが一般的です。現在の実装を見てみると、ユーザー退会時にモデルを使ってはいますが、それ以外の場面ではモデルのインスタンスを呼び出す必要があるタイミングもそうそうないのではないでしょうか？一度、モデルを設定しない方向での実装を考えてみるといいかもしれません。

2024-02-23 22:03 UTC, Osk0830 commented on app/Http/Controllers/UserController.php
> +        return view('users.show', $data);
- タブ内でもページネーションが効くようにしておくといいと思います！

2024-02-23 22:03 UTC, Osk0830 commented on app/User.php
> +            Follow::where('followed_user_id', $user->id)->delete();
- モデルを設定しないとした場合は、Usersコントローラーの `delete()`アクションでの削除を検討してみてください。

2024-02-23 22:03 UTC, Osk0830 commented on resources/views/users/followers.blade.php
> +    </li>
- この仕組みもいいですが、今の内容ですと、ユーザーをフォローしているのか投稿をフォロー（イイねのような感じ）しているのかが分からなくなってしまいそうですね。。ここでは投稿そのものは表示せず、ユーザーの名前だけが並ぶようにするのがよくないでしょうか？

2024-02-23 22:03 UTC, Osk0830 commented on resources/views/users/followers.blade.php
> +@endif
- この仕組みにするのであれば、`foreach`までをも条件分岐に含めるのが分かりやすくないでしょうか？

2024-02-23 22:03 UTC, Osk0830 commented on resources/views/users/show.blade.php
- こちらの内容は、ユーザー詳細のタスクが完了してから確認させていただきますね。ユーザー詳細マージ後にそれを取り込んで調整いただいた後ご連絡いただければと思います！

2024-02-23 22:03 UTC, Osk0830 commented on resources/views/users/timeline.blade.php
- こちらはユーザー詳細そのもののタスクかと思いますので、おいおい削除してくださいね。

2024-02-23 22:03 UTC, Osk0830 commented on routes/web.php
> +        Route::delete('edit', 'UserController@destroy')->name('user.delete');
- `delete`のURLを `edit`に変更する必要がありますでしょうか？

2024-02-23 22:03 UTC, Osk0830 commented on routes/web.php
> +    Route::delete('users/{id}', 'FollowController@destroy')->name('unfollow');
- URLが結構分かりにくい感じになりそうですね。。何のURLかが一目で分かるような感じにすると良さそうですね！

2024-02-24 12:44 UTC, abeai0 commented on app/Follow.php
- ありがとうございます。修正します。

2024-02-24 12:44 UTC, abeai0 commented on app/Http/Controllers/UserController.php
> +        return view('users.show', $data);
- ページネーション付け忘れていました。ありがとうございます、修正します。

2024-02-24 12:48 UTC, abeai0 commented on app/User.php
> +    }
- if文を使ってログインidとフォロー対象のidが同じでない場合にattach($id)され、ログインidと対象のidが同じ場合はfalseを返すようにしました。

2024-02-24 13:50 UTC, abeai0 commented on app/User.php
> +            Follow::where('followed_user_id', $user->id)->delete();
- UserControllerの56~59行目にdetachメソッドを使って記述してみました。退会ユーザーがフォローされていた場合のdetachはforeachでしていますが、他に書き方があれば教えていただきたいです。

2024-02-24 13:58 UTC, abeai0 commented on resources/views/users/followers.blade.php
> +@endif
- ありがとうございます、修正します。

2024-02-24 14:26 UTC, abeai0 commented on resources/views/users/followers.blade.php
> +    </li>
- トップページの投稿表示とレイアウトを合わせました。
- プロフィールとして表示できるものが名前だけになるので、最新の投稿はあったほうがいいのではないかと考えました。
- フォローボタンの位置をユーザー名の隣にすることでユーザーへのフォローだとわかりやすくしてみました。

2024-02-24 14:27 UTC, abeai0 commented on resources/views/users/show.blade.php
- ありがとうございます。

2024-02-24 14:28 UTC, abeai0 commented on resources/views/users/timeline.blade.php
- ありがとうございます、ユーザー詳細表示がマージされた時に削除します。

2024-02-24 14:29 UTC, abeai0 commented on routes/web.php
> +        Route::delete('edit', 'UserController@destroy')->name('user.delete');
- ありがとうございます、元に戻しました。

2024-02-24 14:32 UTC, abeai0 commented on routes/web.php
> +    Route::delete('users/{id}', 'FollowController@destroy')->name('unfollow');
- ありがとうございます。prefixでまとめて、followとunfollowというurlにしてみました。

2024-03-02 04:20 UTC, Osk0830 approved these changes
お疲れ様です！
こちらだいぶスマートに仕上がったのではないかと思いますのでマージしますね！

2024-03-02 04:20 UTC, Osk0830 commented on app/User.php
> +    }
- if文がネストして若干可読性が落ちるかと思いますが、この部分、if文の条件に論理演算子を用いるともう少し見やすく書けないでしょうか？

2024-03-02 04:20 UTC, Osk0830 commented on app/User.php
> +        }
- こちらも上と同じですね。

2024-03-02 04:20 UTC, merged