#907　ユーザ詳細(きよはる）
yukihiroLaravel/joint_develop pull request #966
Opened 2024-02-22 13:58 UTC by kiyoharu420

## issue
- Closes #907 

## 概要
‐ ユーザ詳細

## 動作確認手順
http://localhost:8080/users/1
のページでユーザー詳細がされているか確認

2024-02-25 03:04 UTC, yukihiroLaravel requested changes
遅くなりすみません🙇‍♂️
指摘いくつかしました！

また、コンフリクトがまた起きていたので
最新のdevelopのマージも合わせてお願いいたします・・・！

2024-02-25 03:04 UTC, yukihiroLaravel commented on database/seeds/DatabaseSeeder.php
> +=======
コンフリクト起きてますね💦
こちら３行丸々削除しましょう

2024-02-25 03:04 UTC, yukihiroLaravel commented on database/seeds/DatabaseSeeder.php
> +>>>>>>> develop_c_mutsuki_dra
コンフリクト起きてますね💦
こちら１行丸々削除しましょう

2024-02-25 03:04 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +            <li class="nav-item"><a href="{{ url('/timeline') }}" class="nav-link {{ Request::is('timeline') ? 'active' : '' }}">タイムライン</a></li>
こちらChatGPTなどで対応されましたか？
ここはtimelineというURLはないのでおかしいと思います！

この１行はこのようにしておきましょう
```
<li class="nav-item"><a href="{{ route('user.show', ['id' => $user->id]) }}" class="nav-link {{ Request::is('users/' . $user->id) ? 'active' : '' }}">タイムライン</a></li>
```

2024-02-26 14:10 UTC, kiyoharu420 commented
## issue
- Closes #907 

## 概要
‐ ユーザ詳細　修正１

## 動作確認手順
‐　http://localhost:8080/users/1
　のページでユーザー詳細がされているか確認
　
-　修正しました。
- よろしくお願いします。
- すみませんチャットgptでした。

2024-02-26 14:25 UTC, yukihiroLaravel requested changes
１点確認漏れていました！

2024-02-26 14:25 UTC, yukihiroLaravel commented on resources/views/users/show.blade.php
> +                <img class="mr-2 rounded-circle" src="{{ Gravatar::src('test1@test.com', 300) }}" alt="ユーザのアバター画像">
１点確認漏れていました！

ここは書くユーザで画像を変更するため、
src="{{ Gravatar::src($user->email, 300) }}"
このように記述しないといけないと思います！

2024-02-29 13:02 UTC, kiyoharu420 commented
## issue
- Closes #907 

## 概要
‐ ユーザ詳細　修正２

## 動作確認手順
‐　http://localhost:8080/users/1
　のページでユーザー詳細がされているか確認
　
-　修正とコンフリクト解消しました。
- 　よろしくお願いします。
- 　

2024-02-29 13:15 UTC, yukihiroLaravel approved these changes
OKだと思いますのでマージしました！
大変だったと思いますがお疲れ様でした・・・！☺️

2024-02-29 13:15 UTC, merged