#875 ユーザ詳細
yukihiroLaravel/joint_develop pull request #967
Opened 2024-02-22 15:01 UTC by sol6406

## Issue
- Closes #875
## 概要
- ユーザ詳細
　
## 動作確認手順
- ローカルホストにてログイン
- アドレス
test1@test.com
- パスワード
test1
- ログイン後ヘッダー右側にある test1をクリックし、詳細ページへ。

## 考慮してほしいこと
## 確認してほしいこと
- ログイン中とログアウト中のユーザ詳細の変化部分が正しく分かれているか。

2024-02-24 10:01 UTC, Osk0830 requested changes
お疲れ様でした！
機能的には概ね問題なさそうですね！

ただ、コードの整理・整形が必要な箇所が多くみられましたので、
確認よろしくお願いします！

2024-02-24 10:01 UTC, Osk0830 commented on app/Http/Controllers/UserController.php
> +use App\Http\Controllers\Controller;
- 各コントローラーは、`App\Http\Controllers`の名前空間に置かれ、Controllerクラスを継承しているので、ここで useする必要はないです。

2024-02-24 10:01 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +             ['posts' => $posts]);
- この部分、今回のタスクとは関係ない箇所ではありますが、コードがおかしい形になっているので、一般的な書き方に整形しておいてください。一般的には下記のように書きます。

```
return view('welcome', [
    'posts' => $posts,
]};
```

2024-02-24 10:01 UTC, Osk0830 commented on app/Http/Controllers/UserController.php
> +        return view('users.show',$data);
- カンマの後ろは半角空白を入れてください。

2024-02-24 10:01 UTC, Osk0830 commented on app/Post.php
> -
- この空行は、コードの見やすさという観点から削除しないようにしましょう。

2024-02-24 10:01 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +                        @endif
- 13行目はインデントを一つ下げましょう。
- また、カンマの後ろには半角空白を入れてください。

2024-02-24 10:01 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +            <li class="nav-item"><a href="{{ route('user.show', $user->id) }}" class="nav-link {{ Request::is('users/'.$user->id) ? 'active' : '' }}"><a href="{{ route('user.show', $user->id) }}">タイム
- <a>タグの中に<a>タグを挟むのはHTMLの文法エラーです。この部分おかしな構造になっているので見直してみてください。

2024-02-24 10:01 UTC, Osk0830 commented on resources/views/users/show.blade.php
> +        <div class="m-auto" style="width: fit-content"></div>
- この要素はなぜ必要なのでしょうか？

2024-02-24 10:01 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +<div class="m-auto" style="width: fit-content"></div>
- この要素はなぜ必要なのでしょうか？

2024-02-24 10:01 UTC, Osk0830 commented on resources/views/users/timelain.blade.php
> +<li class=" mt-5 text-center">
- 最初のダブルクオーテーションの後ろの半角空白は取ってください。

2024-02-24 10:01 UTC, Osk0830 commented on resources/views/users/timelain.blade.php
> +{{ $users->links('pagination::bootstrap-4') }}
- なぜYouTubeの内容が必要なのでしょうか？また、そもそもこのファイルは必要でしょうか？

2024-02-24 10:01 UTC, Osk0830 commented on routes/web.php
> +
- この記述はなくても大丈夫じゃないでしょうか？

2024-02-24 10:01 UTC, Osk0830 commented on routes/web.php
> +
- 空行が不要に多すぎるようです。

2024-02-25 04:14 UTC, sol6406 commented on app/Post.php
> -
```
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
```
空行を挿入しました。

2024-02-25 04:15 UTC, sol6406 commented on app/Http/Controllers/UserController.php
> +        return view('users.show',$data);
```
return view('users.show', $data);
```
半角空白挿入しました。

2024-02-25 04:25 UTC, sol6406 commented on resources/views/users/show.blade.php
> +                        @endif
https://gyazo.com/d31026b20597ecf82e2952f0b8198c47

インデントを下げ、カンマの後ろに半角空白を挿入しました。

2024-02-25 04:25 UTC, sol6406 commented on app/Http/Controllers/PostsController.php
> +             ['posts' => $posts]);
上記のように変更しました。

2024-02-25 04:34 UTC, sol6406 commented on app/Http/Controllers/UserController.php
> +use App\Http\Controllers\Controller;
コントローラにControllerクラスを継承しているから、useは必要なかったのですね。きちんと理解ができていませんでした。名前空間とuse宣言についてもう一度復讐します。

2024-02-25 04:38 UTC, sol6406 commented on resources/views/posts/posts.blade.php
> +<div class="m-auto" style="width: fit-content"></div>
すみません、消し忘れです。show.blade.phpのコピペのようです。
削除しました。

2024-02-25 04:49 UTC, sol6406 commented on resources/views/users/timelain.blade.php
> +{{ $users->links('pagination::bootstrap-4') }}
このファイルはタイムラインの投稿表示をする前に、阿部さんがタイムラインのbladeを作ったという話を聞いたのでまねして作ってみようと思い、応用講座の内容が使えるかなとコピペしたまま、その日の作業は中断しました。
後日includeしたらタイムラインのbladeを作らなくてもいいと思ったのでそのまま消し忘れてプルしました。
timelain.blade.phpは削除しました。

2024-02-27 07:19 UTC, sol6406 commented on routes/web.php
> +
削除しました。

2024-02-27 07:20 UTC, sol6406 commented on routes/web.php
> +
空行削除しました。

2024-02-28 01:26 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらしっかり修正できているのでマージしますね！

あと、次のタスク時でもOKですので、
投稿一覧などの下記箇所クリックした際にもユーザー詳細に飛べるよう、
リンクを貼っておいてくださいね。

[![Image from Gyazo](https://i.gyazo.com/b85d45987260d3344862ddda74cce91d.png)](https://gyazo.com/b85d45987260d3344862ddda74cce91d)

2024-02-28 01:26 UTC, merged