#917 フォロー機能(近藤佑哉)
yukihiroLaravel/joint_develop pull request #968
Opened 2024-02-22 15:55 UTC by yuyakondo333

## issue
 - Closes #917 
## 概要
 - フォロー機能
## 動作確認手順
1.  トップページで"フォローする"ボタンをクリックすると"フォロー解除"ボタンに変更していることを確認
2. フォローしたユーザ：following_user_id、フォローされたユーザ：followed_user_idがそれぞれのカラムに入っていることを確認
3. "フォロー解除ボタン"をクリックすると"フォローするボタン"に変更していることを確認
4. 2.で追加されたレコードがデータベース上で削除されていることを確認

## 考慮してほしいこと
#### ↓今回の仕様になります↓
- トップページでログインしてるユーザがフォロー、フォロー解除可能
- 自分以外のユーザの投稿のメールアドレスの下に"フォローする"、"フォロー解除"ボタンが表示される
- "フォローする"ボタンは緑、"フォロー解除"ボタンはアウトラインの赤を使用（違和感がない色且つ被らないようにするため)
## 確認してほしいこと
特になし

2024-02-23 02:27 UTC, yukihiroLaravel requested changes
いくつかご指摘しましたので
ご確認お願いします！

2024-02-23 02:27 UTC, yukihiroLaravel commented on app/Http/Controllers/FollowController.php
> +    public function store($id) {
```public function store($id) {```
ではなく
他の部分と合わせて
```
public function store($id)
{
}
```
こうしましょう！

2024-02-23 02:27 UTC, yukihiroLaravel commented on app/User.php
> +        return $this->belongsToMany(User::class, 'followers', 'following_user_id', 'followed_user_id')->withTimestamps();
followsも
followersも
まったく同じメソッドになっていないでしょうか？

2024-02-23 02:27 UTC, yukihiroLaravel commented on app/User.php
> +    }
```public function ~~~() {```
ではなく
他の部分と合わせて
```
public function ~~~()
{
}
```
こうしましょう！

2024-02-23 02:27 UTC, yukihiroLaravel commented on app/User.php
> +    }
```public function ~~~() {```
ではなく
他の部分と合わせて
```
public function ~~~()
{
}
```
こうしましょう！

2024-02-23 02:27 UTC, yukihiroLaravel commented on app/User.php
> +    }
```public function ~~~() {```
ではなく
他の部分と合わせて
```
public function ~~~()
{
}
```
こうしましょう！

2024-02-23 02:27 UTC, yukihiroLaravel commented on app/User.php
> +    }
followedという関数名だと
ユーザがフォローされているという
受け身のように見えるので
シンプルにfollowなどの項がいいと思います。

2024-02-23 02:27 UTC, yukihiroLaravel commented on app/User.php
> +    }
unfollowedという関数名だと
ユーザがフォローされているという
受け身のように見えるので
シンプルにunFollowなどの項がいいと思います。

2024-02-23 02:27 UTC, yukihiroLaravel commented on app/User.php
> +    }
isFollowedという関数名だと
ユーザがフォローされているという
受け身のように見えるので
シンプルにisFollowなどの項がいいと思います。

2024-02-23 02:27 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::delete('{id}/unfollow', 'FollowController@destroy')->name('unfollow');
上記２つのルーティングであるフォロー機能もユーザ同士の機能なので
下記のusersのルーティンググループの中にいれてもOKかと思いました！
```
Route::group(['prefix' => 'users'],function(){
});
```

2024-02-23 03:54 UTC, yuyakondo333 commented on app/Http/Controllers/FollowController.php
> +    public function store($id) {
"{"←こちらのの位置を移動させました。

2024-02-23 03:55 UTC, yuyakondo333 commented on app/User.php
> +    }
"{"←こちらの位置と関数名を変更させました。

2024-02-23 03:56 UTC, yuyakondo333 commented on app/User.php
> +    }
"{"←こちらの位置と関数名を変更させました。

2024-02-23 03:56 UTC, yuyakondo333 commented on app/User.php
> +    }
"{"←こちらの位置と関数名を変更させました。

2024-02-23 04:00 UTC, yuyakondo333 commented on routes/web.php
> +        Route::delete('{id}/unfollow', 'FollowController@destroy')->name('unfollow');
フォロー機能のルーティングをusersグループのルーティングにまとめました。

2024-02-23 11:24 UTC, yuyakondo333 commented on app/User.php
> +        return $this->belongsToMany(User::class, 'followers', 'following_user_id', 'followed_user_id')->withTimestamps();
そうですね。followsを削除します。

2024-02-23 15:20 UTC, yukihiroLaravel requested changes
また少し指摘させていただきました！
お願いします！

2024-02-23 15:20 UTC, yukihiroLaravel commented on app/User.php
> +    public function followers()
細かい件ですが
この関数がfollowersという名前ですと
英語的に主体のユーザをフォローしている人を表すのですが
62行目・71行目・80行目で使うのでしたら
followersではなく、
followings（フォローしている相手）という関数名の方がふさわしいかと思いました！

2024-02-25 03:23 UTC, yukihiroLaravel requested changes
１点手元で行うとエラーが出たので
記述しました！
ご確認ください！

2024-02-25 03:23 UTC, yukihiroLaravel commented on database/migrations/2024_02_20_235017_create_followers_table.php
> +class CreateFollowerTable extends Migration
CreateFollowerTable
ではなく
CreateFollowersTable
が正しくないでしょうか？

僕の環境で実行したところ
綴り間違いによりマイグレーション実行時に
エラーが出ました、、、

2024-02-25 05:02 UTC, yukihiroLaravel approved these changes

2024-02-25 05:02 UTC, merged