#963 検索機能（あべ）
yukihiroLaravel/joint_develop pull request #974
Opened 2024-02-26 07:49 UTC by abeai0

## issue
- Closes #963 

## 概要
- 検索機能の実装

## 動作確認手順
- トップページを開いて一覧表示が「投稿」と「ユーザー」で表示が切り替わることを確認
- 検索窓に「test」と入力して虫眼鏡のボタンを押して検索結果が表示されるか確認
- ページネーションでページが変わっても検索結果が引き継がれているか確認
- ページネーションでページを変えたときに「投稿」「ユーザー」で違うページ番号になっていることを確認

## 考慮して欲しいこと
- 今回は特にありません

## 確認してほしいこと
- 今回は特にありません

2024-03-05 03:14 UTC, Osk0830 requested changes
お疲れ様です！
何だかんだとお待たせする感じになり恐縮です。。！
内容的には実に素晴らしいと思います！
ただ、若干ややこしい印象を受ける箇所もあり、
もしかしたらもう少しだけスマートになるかもしれないと思いコメントしました。
（処理追いきれてない部分あったらすみません。。）
一度確認いただければと思います。

2024-03-05 03:14 UTC, Osk0830 commented on app/Http/Controllers/SearchController.php
> +            $data += ['activeList' => $activeList];
- 理解不足でしたら恐縮です。。33行目の内容を上で `$data`に一気に格納せず後入れする意図などあったりしますでしょうか？

2024-03-05 03:14 UTC, Osk0830 commented on app/Http/Controllers/SearchController.php
> +            $users = $usersQuery->orderBy('id', 'desc')->paginate(10, ["*"], 'users-page')->appends(["posts-page" => $request->input('posts-page')]);
- 検索のためのコントローラーを別途作らずに、Postsコントローラーに統合してしまった方が、ここの重複的記述など避けられるのではないでしょうか？アクションを一つにまとめるのもありではないかと思いますし、アクション内で一部はクラスメソッドとして書き出すなどすると、もう少し見通しのいい省コードした記述になりそうな気もしますので、一度検討してみていただければと思います。

2024-03-05 03:14 UTC, Osk0830 commented on public/css/style.css
> +}
- bodyやmainのように他のページでも使用する要素にこのようなスタイルを指定してしまうと、全ページに影響してしまいますね。。影響してほしいページにだけ影響するよう、クラスセレクタなどを使って制御してみましょう。

2024-03-05 03:14 UTC, Osk0830 commented on public/css/style.css
> +    margin-bottom: -2rem;
- できれば、よほどの理由がない限り、ネガティブマージンは使わない方がいいですが、これはやむを得ないケースでしょうか？

2024-03-05 03:14 UTC, Osk0830 commented on public/scss/style.scss
- こちらに気づかず、CSSにコメントしちゃいました。。

2024-03-05 03:14 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +@endif
- この辺は、ユーザーともほぼ同じなので、部品化できそうな気もしますが、いかがでしょう？

2024-03-05 03:14 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +    @endif
- この辺も部品化できそうな気がしますがどうですかね？

2024-03-05 03:14 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +    @endphp
- ここら辺、なんかちょっとややこしい感がありますね。。コントローラーからリターンされたものをそのまま使うより、こうした方が分かりやすい感じでしょうか？（追いきれてない部分あったら恐縮です。。）

2024-03-05 03:24 UTC, abeai0 commented on public/css/style.css
> +}
- mainの要素が短い場合にfooterを最下部に配置するするためのスタイルなのでどのページにも影響してほしいのですが、こういった場合もclassを使用した方がいいでしょうか？

2024-03-05 03:27 UTC, abeai0 commented on public/css/style.css
> +    margin-bottom: -2rem;
- Bootstrapのジャンボトロンにパディングが設定されており、それを相殺して表示位置を調整するためにネガティブマージンを使用しました。

2024-03-05 03:27 UTC, abeai0 commented on public/scss/style.scss
- 大丈夫です！

2024-03-05 03:29 UTC, abeai0 commented on resources/views/posts/posts.blade.php
> +@endif
- ありがとうございます。やってみます。

2024-03-05 03:34 UTC, abeai0 commented on resources/views/posts/posts.blade.php
> +    @endif
- 投稿の編集・削除ボタンの部品化は投稿の編集機能がマージされた後の方がいいと思ったのでとりあえずこのままにしています。
- ページネーションの部分は部品化してみます。

2024-03-05 03:39 UTC, abeai0 commented on resources/views/welcome.blade.php
> +    @endphp
- 'data' => $dataでinclideにデータを渡すとエラーが出てしまったような気がするのですが、一旦やってみます！

2024-03-05 03:43 UTC, abeai0 commented on app/Http/Controllers/SearchController.php
> +            $users = $usersQuery->orderBy('id', 'desc')->paginate(10, ["*"], 'users-page')->appends(["posts-page" => $request->input('posts-page')]);
- ありがとうございます。やってみます。

2024-03-05 03:47 UTC, Osk0830 commented on public/css/style.css
> +}
なるほどですね。そのような意図なら要素セレクタもありかもですね。

2024-03-05 03:47 UTC, Osk0830 commented on public/css/style.css
> +    margin-bottom: -2rem;
了解です！

2024-03-05 03:48 UTC, abeai0 commented on app/Http/Controllers/SearchController.php
> +            $data += ['activeList' => $activeList];
- 後入れにする必要ないですね！ありがとうございます、修正します。

2024-03-05 03:49 UTC, Osk0830 commented on resources/views/welcome.blade.php
> +    @endphp
`$data`はBladeに渡ってきた時に展開されるからですね。そもそも親Bladeが持っている変数は、わざわざ渡さなくても、インクルード先で同じ名前でアクセスできると思いますが、いかがでしょう？？

2024-03-05 03:53 UTC, abeai0 commented on resources/views/welcome.blade.php
> +    @endphp
- 毎回渡さないといけないと思い込んでいました！ありがとうございます。

2024-03-08 01:20 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKだと思うのでマージしますね！

2024-03-08 01:20 UTC, merged