投稿編集・更新機能（オオハシ）
yukihiroLaravel/joint_develop pull request #976
Opened 2024-02-27 09:01 UTC by kenta-oohashi

## issue
- Colses #887 
## 概要
- 投稿編集・更新機能
## 動作確認手順
-  ログイン後、投稿の編集ボタンを押して、編集ページに遷移するか
-  編集ページがお手本アプリと同じような仕様になっているか
-  投稿内容を書き換えた後、編集ボタンを押して、編集内容が更新され、かつ、トップページに遷移するか
## 考慮してほしいこと
- 特になし

2024-02-28 01:03 UTC, Osk0830 requested changes
お疲れ様でした！
大枠ではできていると思います！
細かい修正が必要な箇所コメントしましたので、
確認よろしくお願いします！

2024-02-28 01:03 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +    }
- 投稿の編集画面なので、投稿したユーザーと今ログインしているユーザーが一致する場合のみ編集ページを表示させ、それ以外の場合は元いたページに戻るようにさせましょう。
- `$post`の変数に、すべての投稿を格納し、それをBladeに渡していますが、編集画面でこのデータは必要でしょうか？

2024-02-28 01:03 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +    }
- こちらも、`edit()`アクション同様、本人である場合にのみ更新処理が走るようにしましょう。

2024-02-28 01:03 UTC, Osk0830 commented on resources/views/posts/edit.blade.php
- バリデーションで弾かれた際のエラーメッセージは表示されますでしょうか？

2024-02-28 01:03 UTC, Osk0830 commented on resources/views/posts/edit.blade.php
> +            <textarea id="content" class="form-control" name="text" rows="5">{{$post->text}}</textarea>
- ユーザビリティの観点から、バリデーションで弾かれた際には、直前の入力内容が表示されるようにしてください。

2024-02-28 14:18 UTC, kenta-oohashi commented on app/Http/Controllers/PostsController.php
> +    }
承知しました！対処いたします

2024-02-28 14:18 UTC, kenta-oohashi commented on resources/views/posts/edit.blade.php
出ていなかったので、出るように変更いたしました！

2024-02-28 14:19 UTC, kenta-oohashi commented on resources/views/posts/edit.blade.php
> +            <textarea id="content" class="form-control" name="text" rows="5">{{$post->text}}</textarea>
oldを使い、表示されるようにしました

2024-02-28 14:24 UTC, kenta-oohashi commented
## issue
- Colses #887 
## 概要
- 投稿編集・更新機能
## 動作確認手順
-  PostsControllerのfunction editとupdateの所で、投稿したユーザーと今ログインしているユーザーが一致する場合のみ編集ページを表示させ、それ以外の場合は元いたページに戻るようになっているか
-  バリデーションで弾かれた際のエラーメッセージは表示されるか
-  バリデーションで弾かれた際には、直前の入力内容が表示されるか
## ご質問
- 「$postの変数に、すべての投稿を格納し、それをBladeに渡していますが、編集画面でこのデータは必要でしょうか？」というご指摘をいただき、$posts = $user->posts()->orderBy('id', 'desc')->paginate(10);を削除いたしました。投稿編集機能という事で、$post = Post::findOrFail($id);は残してありますが、こちらも削除した方がよいでしょうか？

2024-03-01 12:27 UTC, kenta-oohashi commented
## issue
- Colses #887 
## 概要
- 投稿編集・更新機能
## 確認してほしいこと
-  コンフリクトが解消したか

2024-03-02 04:30 UTC, Osk0830 requested changes
お疲れ様でした！
だいぶ仕上がってきましたね。

少しだけ調整必要な箇所がありますので、
確認よろしくお願いします！

2024-03-02 04:30 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        }else{
- `{`や`}`の前後には半角空白を入れましょう。

2024-03-02 04:30 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        }else{
- `{`や`}`の前後には半角空白を入れましょう。

2024-03-02 04:30 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        return redirect()->route('welcome');
- この4行はインデントを一つ下げましょう。
- 投稿者は不変でuser_idが変わることはないので、user_idを入れ直す記述は不要ですね。削除しましょう。

2024-03-02 04:30 UTC, Osk0830 commented on routes/web.php
> +Route::get('/', 'PostsController@index')->name('welcome');//トップページへの遷移
- 同じURLで同じアクションのルーティングは2つ共存できません。今回は24行目に名前をつけただけなので、25行目だけ残して24行目は削除でいいですね。

2024-03-02 14:45 UTC, kenta-oohashi commented on app/Http/Controllers/PostsController.php
> +        }else{
修正いたします！

2024-03-02 14:45 UTC, kenta-oohashi commented on app/Http/Controllers/PostsController.php
> +        }else{
修正いたします！

2024-03-02 14:47 UTC, kenta-oohashi commented on app/Http/Controllers/PostsController.php
> +        return redirect()->route('welcome');
確かにご指摘いただいて、考えてみるとそうですね。勉強になりました、ありがとうございます！

2024-03-02 14:47 UTC, kenta-oohashi commented on routes/web.php
> +Route::get('/', 'PostsController@index')->name('welcome');//トップページへの遷移
了解しました！

2024-03-02 14:49 UTC, kenta-oohashi commented
## issue
- Colses #887 
## 概要
- 投稿編集・更新機能
## 確認してほしいこと
-  ご指摘いただいた、}else{　の所に半角スペースが入っているか
- PostControllerの５１～５４行目のインシデントが一つ分下がっており、かつ、$post->user_id = $request->user()->id;が削除されているか
- Web.phpの２４行目のRoute::get('/', 'PostsController@index');が削除されているか

2024-03-03 06:24 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKそうなのでマージしますね〜！

2024-03-03 06:24 UTC, merged