feature/ohtomo/#888_Deletion_of_posts_function
yukihiroLaravel/joint_develop pull request #977
Opened 2024-02-27 13:04 UTC by to-ohtomo

## issue
・Closes #888

## 概要
投稿削除

## 動作確認手順
・top画面でログインしているユーザの投稿のみ削除できることを確認
・ユーザ詳細のタイムランにて投稿を削除できることを確認

## 確認してほしいこと
・以前作成したUserController.phpのpublic function updateにて、
update完了後、編集画面に戻るように設定していましたが、ユーザ詳細が完成したため、
update完了後、ユーザ詳細にリダイレクトするように修正しました。
下記のように記載しております。
（return redirect()->route('user.show', ['id' => $id]);）
お手数ですが、併せてレビューをお願い致します。

2024-02-28 01:15 UTC, Osk0830 requested changes
お疲れ様でした！
ほぼできていると思います！
少し修正が必要そうな箇所コメントしましたので、
確認よろしくお願いします！

2024-02-28 01:15 UTC, Osk0830 commented on routes/web.php
> +        Route::get('/posts/{id}', 'PostsController@destroy')->name('post.delete');
- こちらのルーティングは必要でしょうか？

2024-02-28 01:15 UTC, Osk0830 commented on routes/web.php
> +        Route::delete('/posts/{id}', 'PostsController@destroy')->name('post.delete');
- `prefix`として `posts`を付けてグループ化しているので、今の状態ですとURLが `/posts/posts/1`のように無駄に長くなってしまうので調整しましょう。

2024-02-28 08:47 UTC, to-ohtomo commented on routes/web.php
> +        Route::get('/posts/{id}', 'PostsController@destroy')->name('post.delete');
ご指摘有難うございます。こちらは不要ですので削除致します。

2024-02-28 08:47 UTC, to-ohtomo commented on routes/web.php
> +        Route::delete('/posts/{id}', 'PostsController@destroy')->name('post.delete');
失礼しました。こちら修正致します。

2024-02-28 14:07 UTC, to-ohtomo commented
下記ファイルの内容を修正させていただきましたので、お手数ですが、再レビューをお願い致します。
・web.php
・posts.blade.php

2024-02-28 14:14 UTC, to-ohtomo commented on resources/views/posts/posts.blade.php
> +                        <form action="{{ route('post.delete', $post->id) }}" method="POST">
<form method=" action="{{ route('post.delete',...と記載してしまっていたので、<form action="{{ route('post.delete'...に修正しました

2024-02-28 14:15 UTC, to-ohtomo commented
下記ファイルの内容を修正させていただきましたので、お手数ですが、再レビューをお願い致します。
・ web.php（Route::get削除、delete('{id}',...に修正しました）
・posts.blade.php（<form method=" action="{{ route('post.delete',...と記載してしまっていたので、<form action="{{ route('post.delete'...に修正しました）

2024-02-28 14:15 UTC, to-ohtomo commented
下記ファイルの内容を修正させていただきましたので、お手数ですが、再レビューをお願い致します。
・ web.php（Route::get削除、delete('{id}',...に修正しました）
・posts.blade.php（<form method=" action="{{ route('post.delete',...と記載してしまっていたので、<form action="{{ route('post.delete'...に修正しました）

2024-02-29 13:42 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKそうなのでマージしますね！

2024-02-29 13:42 UTC, merged