#903 投稿編集画面&更新(川原)
yukihiroLaravel/joint_develop pull request #978
Opened 2024-02-27 14:51 UTC by natsumi-kawahara-epkotsoftware

## issue
- Closes #903

## 概要
- 投稿編集画面・更新

## 動作確認手順
- http://localhost:8080/ へアクセスし、ログインした後、自分の投稿を編集して更新されるか確認する。
- 更新ボタンを押したら、投稿一覧の画面が表示されることを確認する。

## 考慮して欲しいこと
- 特になし

## 確認してほしいこと
- 今回は特にありません。

2024-02-28 10:02 UTC, yukihiroLaravel approved these changes
完璧です！
問題ないのでマージしました☺️
おつかれさまでした！

2024-02-28 10:10 UTC, yukihiroLaravel requested changes
お疲れ様でした！
いくつかご指摘しましたので
ご確認お願いいたします！

2024-02-28 10:10 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $posts = $user->posts()->orderBy('id', 'desc')->paginate(10);
このpostsは今使われていないので削除していいと思います！

2024-02-28 10:10 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +            'posts' => $posts,
このpostsは今使われていないので削除していいと思います！

2024-02-28 10:10 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        $user = \Auth::user();
このuserは今使われていないので削除していいと思います！

2024-02-28 10:10 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +            'user' => $user,
このpostsは今使われていないので削除していいと思います！

2024-02-28 10:10 UTC, yukihiroLaravel commented on app/Http/Controllers/PostsController.php
> +        return view('posts.edit', $data);
現状の状態ですと
ユーザ本人が投稿したものでないpostも編集できてしまうので
制限を加えましょう。
実際、お手本アプリも本人以外の投稿編集画面にアクセスしようとすると
エラーを出す仕様になっております。

なので、下記のように書き換えてみましょう。

```
if (ログインユーザ本人の投稿かどうか判定する判定式) {
    return view('posts.edit', $data);
}
abort(404);
```

(ログインユーザ本人の投稿かどうか判定する判定式)
↑ここの部分は考えてみてください！

2024-03-04 12:06 UTC, natsumi-kawahara-epkotsoftware commented on app/Http/Controllers/PostsController.php
> +        $user = \Auth::user();
@yukihiroLaravel 
$user = \Auth::user();
この表記がないと、エラーになってしまうので、そのままにしています。

2024-03-04 14:22 UTC, yukihiroLaravel approved these changes

2024-03-04 14:22 UTC, merged