Feature/yokoi/withdraw
yukihiroLaravel/joint_develop pull request #983
Opened 2024-03-02 05:50 UTC by KosukeYokoi

概要
• ユーザ退会
動作確認手順
•新規ユーザ登録後、複数コメント投稿して、退会後に画面ではユーザ名やコメントは消えているが、
DBテーブル上ではデータが残っていることを確認

考慮してほしいこと
なし

確認してほしいこと
・講師確認でユーザがきちんと論理削除となっているか

2024-03-02 06:22 UTC, yukihiroLaravel requested changes
ご指摘しましたので、ご確認・修正ください！

2024-03-02 06:22 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +        //Auth::logout(); // ログアウト
不要なコメントアウトは削除してください！

2024-03-02 06:22 UTC, yukihiroLaravel commented on app/User.php
> +    }
すでに同様の関数posts()は上で定義されているので不要です！

2024-03-02 06:22 UTC, yukihiroLaravel commented on app/User.php
> +            $user->post()->delete();
下記の関数削除に伴いposts()
にしないといけません

2024-03-02 06:22 UTC, yukihiroLaravel commented on app/User.php
> +
以前動画でも少し触れましたが
こちらの関数使われていないですよね？

削除しましょう！

2024-03-02 06:22 UTC, yukihiroLaravel commented on routes/web.php
> +
これはログインしていないユーザでもアクセスできるルーティングになってしまっているので
下のログイン後のルーティンググループのところに移動させましょう！

2024-03-02 06:22 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
>      }
ここに空行を１行入れましょう！

2024-03-02 06:22 UTC, yukihiroLaravel commented on app/Http/Controllers/UsersController.php
> +
不要なコメントアウトや空行は消しましょう

2024-03-02 06:41 UTC, KosukeYokoi commented on app/Http/Controllers/UsersController.php
> +
コメントアウトと空行を削除しました。

2024-03-02 06:45 UTC, KosukeYokoi commented on app/Http/Controllers/UsersController.php
>      }
public function edit($id) {　の下に空行を1行入れました。

2024-03-02 06:46 UTC, KosukeYokoi commented on app/Http/Controllers/UsersController.php
> +        //Auth::logout(); // ログアウト
コメントアウトを削除しました。

2024-03-02 06:59 UTC, KosukeYokoi commented on app/User.php
> +            $user->post()->delete();
46行目のposts()の内部に処理を移行しました。

2024-03-02 07:00 UTC, KosukeYokoi commented on app/User.php
> +    }
こちらのpost()は削除しました。

2024-03-03 12:14 UTC, yukihiroLaravel requested changes
１点指摘漏れていましたが、指摘しました！

2024-03-03 12:14 UTC, yukihiroLaravel commented on routes/web.php
> +        Route::delete('users/{id}', 'UsersController@destroy')->name('users.destroy');
ここにルーティングを置くと
users/users/{id}
というルーティングになりますので
users/
というURLは省きましょう！

2024-03-03 12:24 UTC, yukihiroLaravel approved these changes
OKですので、マージしました！
おつかれさまでした！

2024-03-03 12:24 UTC, merged