ユーザーアイコン変更機能
yukihiroLaravel/joint_develop pull request #995
Opened 2024-03-06 08:16 UTC by abeai0

## issue
- ないです

## 概要
- ユーザーアイコン変更機能の実装

## 動作確認手順
- usersテーブルへカラムを追加したので、php artisanコマンドを実行してください
- 登録済みのユーザーでログイン、users/{id}/editページに行ってユーザーのアイコンの下に画像投稿フォームがあることを確認
- 任意の画像（png,jpen,jpgのみにしてあります）を選択し、ユーザー情報を入力、更新ボタンを押す
- 更新後ユーザーアイコン画像が変更されることを確認
- usersテーブルのiconカラムとstrage/app/public/images内にデータが増えていることを確認
- もう一度アイコン画像を更新し、古い画像のデータが消えることを確認

## 考慮して欲しいこと
- 投稿ボタンのレイアウトなどは整えていません、画像のプレビュー表示機能も後で実装予定のためありません
- ユーザー情報編集画面以外のアイコン画像はまだ変わりません

## 確認してほしいこと
今回はありません

2024-03-11 22:04 UTC, Osk0830 requested changes
お疲れ様でした！
既存のファイルの有無による処理の変更、処理のクラス内メソッドの切り出し、<form>外の<input>要素の配置などなど、色々と考慮して実装されていて非常に素晴らしいと思います！
細かい部分ではありますが、少しだけコメントしましたので、
確認よろしくお願いします！

2024-03-11 22:04 UTC, Osk0830 commented on app/Http/Requests/UserRequest.php
> +            'icon' => 'image |mimes:png,jpg,jpeg'
- サーバーの設定などとの兼ね合いで決まったりするものではありますが、サーバーの容量を圧迫しないようにする最も含めて、ファイルサイズの上限も指定してあげましょう。

2024-03-11 22:04 UTC, Osk0830 commented on resources/views/users/edit.blade.php
> +                        <input type="file" form="user_updata" name="icon">
- バリデーションでファイルの種類は限定してますが、ユーザビリティの観点から、ここで選択できるファイルも限定してあげると良さそうですね。

2024-03-12 00:24 UTC, abeai0 commented on resources/views/users/edit.blade.php
> +                        <input type="file" form="user_updata" name="icon">
ありがとうございます。修正します。

2024-03-12 00:26 UTC, abeai0 commented on app/Http/Requests/UserRequest.php
> +            'icon' => 'image |mimes:png,jpg,jpeg'
ありがとうございます。修正します。
ファイルサイズの上限は一般的にはどの程度までになっているのか教えていただけますと助かります。

2024-03-13 10:40 UTC, Osk0830 commented on app/Http/Requests/UserRequest.php
> +            'icon' => 'image |mimes:png,jpg,jpeg'
20MBとかが多いような印象ですね〜

2024-03-13 10:41 UTC, Osk0830 approved these changes
お疲れ様でした！
こちらOKそうなのでマージしますね！

2024-03-13 10:41 UTC, merged