#871　投稿編集、更新（小野寺）
yukihiroLaravel/joint_develop pull request #999
Opened 2024-03-06 23:30 UTC by sol6406

## Issue
- Closes #871
## 概要
- 投稿編集、更新
　
## 動作確認手順
- ログイン後ユーザーが投稿していれば投稿内容の下にある編集ボタンを押す
-投稿内容を変更し、下にある更新ボタンを押す
-押した後、トップに戻るはずなので投稿内容の確認
## 考慮してほしいこと
## 確認してほしいこと
空白、空行の確認はしましたが、抜けがあればご指摘お願いします。
前回のユーザ詳細にて投稿表示のユーザ名からの詳細へのリンクも張りましたので確認お願いします。
その他HANさんであればこうは書かないという所があればご指摘お願いします。できればヒントもお願いします。

2024-03-11 22:40 UTC, Osk0830 requested changes
お疲れ様でした！
概ねよくできていると思います！
少し調整・修正が必要な箇所がありコメントしましたので、
確認よろしくお願いします！

2024-03-11 22:40 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        }
- インデントが少しおかしいので修正しましょう。
- if文の条件に合致しなかった場合の `return`処理がないようです。今、仮に、自分自身に投稿ではない投稿の編集ページにアクセスした場合どうなるか確認してみましょう。

2024-03-11 22:40 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        $post->save();
- こちらも本人の投稿かどうかで処理を切り分けましょう。

2024-03-11 22:40 UTC, Osk0830 commented on resources/views/posts/edit.blade.php
> +    @endphp
- こちらは処理で利用していないようですが、必要でしょうか？

2024-03-11 22:40 UTC, Osk0830 commented on resources/views/posts/edit.blade.php
> +    </form>
- 全体でインデントがおかしいので調整しましょう。

2024-03-11 22:40 UTC, Osk0830 commented on resources/views/posts/edit.blade.php
> +                    <textarea id="content" class="form-control" name="content" rows="5">{{ $post->content }}</textarea>
- ユーザビリティの観点から、バリデーションで弾かれた際に、直前の入力内容が表示されるようにしましょう。

2024-03-11 22:40 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                            <a href="{{ route('post.edit',$post->id) }}" class="btn btn-primary">編集する</a>
- カンマの後ろは半角空白を入れましょう。

2024-03-12 15:31 UTC, sol6406 commented on app/Http/Controllers/PostsController.php
> +        }
インデント修正しました。
idが合致しない場合、前のページに戻るようにしました。

2024-03-13 14:39 UTC, sol6406 commented on resources/views/posts/edit.blade.php
> +    @endphp
削除しました。

2024-03-13 15:41 UTC, sol6406 commented on resources/views/posts/edit.blade.php
> +    </form>
インデント修正しました。
どうでしょうか？

2024-03-15 13:45 UTC, sol6406 commented on resources/views/posts/edit.blade.php
> +                    <textarea id="content" class="form-control" name="content" rows="5">{{ $post->content }}</textarea>
textareaタグでold関数を囲みました。

2024-03-15 14:03 UTC, sol6406 commented on app/Http/Controllers/PostsController.php
> +        $post->save();
どうでしょうか。
ご確認おねがいします。

2024-03-17 04:53 UTC, Osk0830 requested changes
お疲れ様でした！
ほぼ完成に近づいてきましたね。
少しだけ調整が必要な箇所がありますので、
確認よろしくお願いします！

2024-03-17 04:53 UTC, Osk0830 commented on database/seeds/PostsTableSeeder.php
> +                'content' => '',
- こちらはなぜ変更したのでしょうか？

2024-03-17 04:53 UTC, Osk0830 commented on app/Http/Controllers/PostsController.php
> +        return back();
- こちら、`update()`の記述同様、if文のブロックは全体的にインデントが一つずつ前に出るべきですね。

2024-03-17 04:53 UTC, Osk0830 commented on resources/views/posts/posts.blade.php
> +                            <a href="{{ route('post.edit',$post->id) }}" class="btn btn-primary">編集する</a>
- こちら修正できていないようですね。

2024-03-18 14:25 UTC, sol6406 commented on database/seeds/PostsTableSeeder.php
> +                'content' => '',
チームミーティング時、テーマに沿った投稿を一人5つ考えようということで動くことになったのですが、その時に誤って消してしまい、そのままでした。戻しています。

2024-03-18 14:26 UTC, sol6406 commented on app/Http/Controllers/PostsController.php
> +        return back();
$post
と同じインデントに揃えました。

2024-03-18 14:27 UTC, sol6406 commented on resources/views/posts/posts.blade.php
> +                            <a href="{{ route('post.edit',$post->id) }}" class="btn btn-primary">編集する</a>
保存されていませんでした。すみません。

2024-03-21 13:02 UTC, Osk0830 approved these changes
お疲れ様でした！
こちら大丈夫そうなのでマージしますね！

2024-03-21 13:03 UTC, merged